### ISSUE TITLE
Windows: Crashes when not running as admin

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1004]
This is what I did:

1. Run DDNet
2. Update available -> restart DDNet as admin and update
3. Rerun DDNet as non-admin -> crash

I can just keep running as an admin, so it doesn't really matter, but if Windows users report errors, just tell them to permanently run it as admins.

**Comment by daverck** [comment]
you re speaking of latest developpement release ?

**Comment by PathosEthosLogos** [comment]
Yes. No problem on another computer actually, so it could be a corruption problem when I updated it on the other computer (it's on bad wifi). Closing the issue unless it arises again.
