### ISSUE TITLE
The k client can still server menu music while in-game

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1013]
I'm not sure if it's fixed in DDNet servers, but is there a way to just completely disable it without deleting the audio file?

**Comment by def-** [comment]
Sounds more like a bug in k-client, doesn't it?

**Comment by fokkonaut** [comment]
Just turn off play background music

**Comment by PathosEthosLogos** [comment]
No, it's not a bug in k-client. The k-client _forces_ most (if not all) other clients to listen to the song.

I have my background music setting off and this is not in the server list menu. The k-client forces others to listen to it _in-game_.

**Comment by Learath2** [comment]
What kind of black magic is that? I'll give it a check

**Comment by PathosEthosLogos** [comment]
Let me explain its behaviour to the best of my ability:
1. Join a game (I know this still happens in FNG servers. I remembered this happened in DDNet servers long time ago, so if it's not fixed, it's still in effect) -- not sure if it's specific mods
2. The k-client user activates something, and leaves an _invisible object_ (for lack of a better description) in-game where they are standing.
3. The k-client user tee is still affected by gravity, but the invisible object isn't and the object stays there even when the tee left the spot. The music plays with stereo at max volume. You can hear the music go left and right depending on your position to this invisible object.

**Comment by Learath2** [comment]
It's heard by everyone thus it must be creating a sound on the server, I couldn't find any calls to `CGameContext::CreateSound` that could allow user input as sound and no other function can create a `CNetEvent_SoundWorld` so this should be impossible, if you encounter it on ddnet please let me know :)

**Comment by fokkonaut** [comment]
noby added the command /earrape to his fng2+ server.
