### ISSUE TITLE
Glew should be able to be loaded externally

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1016]
instead of using the bundled version. Useful for packagers especially.

> 16:03 <+quinerr> Hi, I'm packing ddnet for debian. However I see currently src heavily depends on bundled libs
> 16:18 <+quinerr> Hmm you know debian ftp master
> 16:18 <+quinerr> block everything
> 16:31 <+quinerr> I still get embedded-library errors for 11.0.3
> 16:41 <+quinerr> It's glew which is bundled in

**Comment by def-** [comment]
@heinrich5991 You're the cmake guy, want to try this?

**Comment by heinrich5991** [comment]
I suppose.

**Comment by def-** [comment]
I'm wondering why quinerr only talked about glew btw. Shouldn't we have the same problems with json-parser, libwebsockets, md5, pnglite, wavpack. zlib seems to be the only one that can use system lib if available.

**Comment by heinrich5991** [comment]
I'd guess `md5` is okay.

`libwebsockets`, `pnglite` and `wavpack` have Debian packages. I couldn't find the `json-parser` in Debian packages – that might be a problem.
