### ISSUE TITLE
Window size doubles on every launch [macOS]

### ISSUE THREAD

**Issue by weez15** [ddnet/ddnet#1018]
Every time I launch DDNet, the window size doubles.

**Comment by def-** [comment]
Sounds like the infamous highdpi problem. You have a retina display, right?

**Comment by weez15** [comment]
Yes

**Comment by def-** [comment]
Can you try the version from https://ddnet.tw/downloads/DDNet-nightly-osx.dmg ?

**Comment by weez15** [comment]
Same problem

**Comment by def-** [comment]
Same link, please try again.

**Comment by weez15** [comment]
The resolution is lower, however. 😥

**Comment by def-** [comment]
Ah right, of course... Please try again, can you also make sure that switching to another window and back doesn't hang the game?

**Comment by weez15** [comment]
The resolution is good. The window size doubles. Switching doesn't hang the game.

**Comment by def-** [comment]
Please try again, sorry for this.

**Comment by weez15** [comment]
The resolution is good. The window size keeps at 3360*2100 24 bit(8:5) no matter how I change it, which is a little bit large for me. 

When in window mode, checking the full screen checkbox works fine:
![image](https://user-images.githubusercontent.com/24721459/35922413-6e235aae-0c15-11e8-9009-557261086510.png)
And there is no problem when playing in the game.

I reboot the game later. The screen fade to black and then fade to normal. Suddenly, the game appears in the screen. The background is red for 0.1 second, then becomes gray:
![image](https://user-images.githubusercontent.com/24721459/35922124-a53bdd5a-0c14-11e8-8cc3-b6d462fbd5ba.png)
And there is no problem when playing the game in that area.

So I try to re-enable full screen to play in full screen without rebooting the game.
I uncheck the full screen checkbox, all listbox breaks.
I re-check the full screen checkbox, the listboxs still breaks:
![image](https://user-images.githubusercontent.com/24721459/35922287-1bf44d2e-0c15-11e8-9307-2b4b61a4259f.png)
![image](https://user-images.githubusercontent.com/24721459/35922968-f12b7750-0c16-11e8-92f0-e462d37bda62.png)

I have the same listbox issue in version 11.0.3 when the game starts in fullscreen. When the version 11.0.3 starts in window mode, listboxs don't break. :P

**Comment by def-** [comment]
Would be awesome if someone with macosx could look into this. It's a bit hard to fix these problems without access to a device.

**Comment by Learath2** [comment]
I'll have a mac in a week \o/

**Comment by weez15** [comment]
I'll learn C++ on macOS in a year :D

**Comment by weez15** [comment]
it no longer doubles after I manually inserted "cl_save_settings 0" into settings_ddnet.cfg. I think it's "save on exit" that mistakes the current resolution as 2x larger on hidpi. manually inputting "cl_save_settings 0" in f1 console doesn't change it in the next launch, too.
