### ISSUE TITLE
In-game Demo

### ISSUE THREAD

**Issue by torhns** [ddnet/ddnet#1019]
Watching demo in game is good idea! Do you want to see the demo with cheater without leave from server?

**Comment by ChillerDragon** [comment]
Yes, would be great. But hard to implement as far as i know.

**Comment by torhns** [comment]
Because of this, I did not start doing this

**Comment by Learath2** [comment]
Would require major refactoring or hackery. Demo browser in-game is possible but we don't really have much space to add new tabs.

Wontfix.
