### ISSUE TITLE
Update libwebsockets

### ISSUE THREAD

**Issue by yangfl** [ddnet/ddnet#1022]
As of libwebsockets 2.4.1, many APIs have been changed. For example, `libwebsocket_callback_on_writable` is gone. This stops ddnet from linking against system libraries, which is required by Debian packaging guideline.

Please consider updating bundled libwebsockets codes.

**Comment by def-** [comment]
Yeah, I'll do that now.

**Comment by def-** [comment]
Someone else want to try this? @eeeee  maybe?

Otherwise I'll do it when I find some time.
