### ISSUE TITLE
Update wavpack

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#1023]
Teeworlds currently uses version 4.something, current distributions ship version 5.
```
../src/engine/client/sound.cpp: In static member function ‘static int CSound::DecodeWV(int, const void*, unsigned int)’:
../src/engine/client/sound.cpp:485:50: error: cannot convert ‘int (*)(void*, int)’ to ‘const char*’ for argument ‘1’ to ‘WavpackContext* WavpackOpenFileInput(const char*, char*, int, int)’
  pContext = WavpackOpenFileInput(ReadData, aError);
                                                  ^
```

**Comment by heinrich5991** [comment]
(Debian oldstable has 4.something, but we're trying to get DDNet packaged for stuff that's newer than stable. Debian stable has 5.something.)

At least `pnglite` hasn't seen major updates since it was included in Teeworlds. :)

**Comment by def-** [comment]
Note that we use the wavpack Tiny Decoder in its most recent version, 4.40, not full wavpack. So maybe we should just keep using our own since we don't need full wavpack support.

**Comment by PathosEthosLogos** [comment]
Should this be closed?
