### ISSUE TITLE
Typing in Japanese no longer works

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1030]
Typing in Korean works still, though a bit wonky, but not different than before. It's just Japanese that doesn't work anymore.

**Comment by def-** [comment]
Since which version?

**Comment by PathosEthosLogos** [comment]
That's a good question. I'm not entirely sure. If I must guess, then 11.0.2 or 11.0.1.

**Comment by Learath2** [comment]
@PathosEthosLogos still?

**Comment by PathosEthosLogos** [comment]
@Learath2 I just tested it. It actually seems to work, though still very, very funky. It's really difficult to explain why/how it's funky, but the way I'm forced to type right now is to use a symbol (like a comma) to *finish typing* so to speak. 

Seems like Korean is still the same. It works, but need to press spacebar or a symbol every time before pressing enter to send message.

I'd have to say that Korean works better/simpler than Japanese at the moment.

**Comment by PathosEthosLogos** [comment]
I would like to bump this with a new found issue.

Now with Korean servers online, there are more Korean and Japanese players active now, and of course, more Chinese players than ever before -- even more than Germans now.

Korean typing is a bit difficult and due to some bugs, it keeps muting the players because typing Korean automatically spams the chat for some reason.

I would also like to make a side note that Arabic is still disconnected and not a continuous script.

**Comment by Learath2** [comment]
Japanese was working for a while, now it's completely broken on macOS, haven't debugged it yet.
