### ISSUE TITLE
Pressing "home" or "end" in settings -> player -> text edit fields

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1031]
I think it's just an unintended UI/UX behaviour--to reproduce:
1) go to settings -> player
2) click on text field for either name or clan
3) press home/end
And you'll see that the flag selection changes instead of the text cursor moving to the beginning/end of the text edit field.

**Comment by def-** [comment]
Well, *both* happen at once since both inputs are active ;)

**Comment by Learath2** [comment]
Interestingly bors didn't close this one. Fixed by b14370e6.
