### ISSUE TITLE
ctrl+delete similar to ctrl+backspace (and ctrl+arrow keys)

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1032]
Few patches ago, ctrl+backspace was implemented and works phenomenally. Thanks for that! It's also nice to navigate around text with ctrl+arrow key as well.

How about doing the same thing for ctrl+delete? To clarify, it's to delete a word after the cursor, whereas ctrl+backspace was to delete a word before the cursor.

**Comment by def-** [comment]
we're talking about chat input here, not f1?

**Comment by PathosEthosLogos** [comment]
@def- Yes, the chat, but it'd be nice if it works in f1 as well.
