### ISSUE TITLE
f1 as non-editable, selectable (with cursor) text field?

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1033]
Currently, there is no way to select text in-game. How about making f1 text-selectable, enabling copy/paste after selecting text?

This would require the f1 console to _freeze_ (so that it doesn't automatically scroll as new messages appear) and enable auto scroll when end key is pressed and page down key is pressed to the end of the log. So a click into the text field would freeze it.

**Comment by Jupeyy** [comment]
fix in #4151
