### ISSUE TITLE
A graphic user interface for console commands

### ISSUE THREAD

**Issue by Irradius** [ddnet/ddnet#1046]
I would to propose this feature

**Comment by ChillerDragon** [comment]
f4

**Comment by heinrich5991** [comment]
Can you elaborate on what you mean with "GUI for console commands"? I'd guess more than the current console activated by f1/f2?

**Comment by Irradius** [comment]
to make more explicit many hidden feature... to categorize commands in a menu, so become more intuitive than a long list alphabetically sorted

**Comment by Learath2** [comment]
I don't think this belongs in the client but we maybe need better documentation.

**Comment by Irradius** [comment]
I would do the opposite  instead. Because I like when I can play a game, and learn while doing directly, without study the theory in a separate place

**Comment by heinrich5991** [comment]
The console isn't really ment for general use. You can tweak settings that will make your client less usable.

**Comment by def-** [comment]
So if an option is considered useful for many users, then add that one to options. Otherwise leave them hidden in f1 and refer to https://ddnet.tw/settingscommands/
