### ISSUE TITLE
AllTheHaxx has a few useful features (and it's open source)

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1061]
Feature list: https://allthehaxx.github.io
Source: https://github.com/AllTheHaxx/AllTheHaxx

I mentioned this briefly in the forum before without linking it or mentioning the name because I didn't want to link this client. Github seemed like a safe choice.

1) Built-in IRC client would be very useful: the main server list menu should be split in half, where the bottom half is for IRC global chat (in as default, leave as an option), as well as people joining clan chat, etc.

2) Serverlist cache, fast serverlist updating: I think this is potentially a big upgrade for populating the server list

3) Recent servers: I haven't used the client so I'm not 100% sure, but my guess is that this client has a separate tab for it. I think there can just be another category at the top, maybe next to ping (last joined "3d" ago or something like that)

4) Translator for chat: devs didn't seem to like Google API for translator, so maybe Moses can be an option -- https://www.quora.com/How-do-I-integrate-Moses-machine-translation-into-my-realtime-website/answer/Niko-Papula   (there's link to Github under "Google Project Hosting")

5) Crypted chat: possible for /pm or /w?

Bonus) Skin fetcher: I can see some die-hard skin fans wanting this

**Comment by heinrich5991** [comment]
Some sort of serverlist cache might be good.

**Comment by Learath2** [comment]
@heinrich5991 as in clientside caching of the servers? It's quite misleading don't you think?

Maybe we could just keep the names but any other info will be terribly outdated.

**Comment by daverck** [comment]
I like their
- translator for chat
- Skin fetcher
- console colors
- free melon power

**Comment by Henningstone** [comment]
@daverck the last one is the best (and most unique!) in my opinion :smile:

**Comment by corneum** [comment]
i like the cinematic mousemovement from the client. would be nice to have for videos

**Comment by PathosEthosLogos** [comment]
So, will any of these be implemented? Should I create a separate issue for each point instead? I think that might make it easier to discuss and disentangle the logistical process.

Console colours sound like a good start though.

**Comment by PathosEthosLogos** [comment]
Created separate issues for each point! Closed
