### ISSUE TITLE
recvmmsg on server

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1067]
Should reduce number of syscalls significantly. Why are we not using it again? I remember the timeout parameter is broken, but we could use it non-blocking instead.

**Comment by def-** [comment]
Anyone want to take a look? Otherwise I'll try probably

**Comment by heinrich5991** [comment]
It's a good idea to not consume resources while waiting for messages. Using nonblocking sockets and sleeps means that the server will consume resources even if entirely idle.

**Comment by def-** [comment]
If we received <= 1 messages in the last recv* call, then call recvfrom next time, else use recvmmsg. (or something like that?)

**Comment by def-** [comment]
Tried, didn't work well, reverted.
