### ISSUE TITLE
Provide server info from https://ddnet.tw in json format

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1074]
- provide all ddnet servers with players over https with a few possible filters (ddnet, global)
- should update at least once a minute, maybe every 10 seconds?
- ping could still be requested per ip in client
- in json format, client can parse it for internet and ddnet tabs

Advantages:
- Much faster to refresh with slow internet connections
- Server hosters don't know players ip just from server browser use, was often used for DoSing (but for ping we'd still need to send a udp packet to the server probably)

Disadvantages:
- Server could be unreachable from ddnet.tw but reachable for you, then it doesn't show up, client could fall back to normal serverinfo request then

Thoughts?

**Comment by heinrich5991** [comment]
This is basically a HTTPS master server.

We'd want the possibility to register via HTTPS as well, only provide backward compatibility by fetching server IPs from the previous masters and querying the IP addresses periodically.

The servers would register to all its known HTTPS master servers by providing a JSON with a few mandatory fields, like name, game type, etc. The clients fetch from all master servers and use the most up-to-date info they receive (merge the different lists). Optionally, they can request to ping individual or all servers.

LAN server discovery must continue to work, ofc.

**Comment by heinrich5991** [comment]
(I'm also interested in trying this, have thought about it before.)

**Comment by Learath2** [comment]
This makes the ping calculation guesswork, I guess we could just not display ping until we actually ping the server.

I'd love to see if this works out as well.

**Comment by def-** [comment]
Well, you could request a single one from each ip, but then the players are giving away their ip of course.

**Comment by Learath2** [comment]
#1834 should help this
