### ISSUE TITLE
CMake doesn't detect distribution MySQL libraries on Debian 8.10

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#1089]
`mysql_config` exists, `libmysqlclient-dev` and `libmysqlcppconn-dev` are installed. Reported by @Laxa on Quakenet, #ddnet.

**Comment by Laxa** [comment]
Performed tests again tonight, on a fresh VM, problem was not there and no more problem on the original server. I probably fucked up at some points with dependencies, or cmake is not that smart :)
This issue can be closed
