### ISSUE TITLE
Swap tees, claim tee that has timeout

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1103]
In the last days I watched large teams in team 0 playing for hours. Two situations occur commonly:

1. Player has to stop playing after X hours, leaves the group
2. Player has a timeout and never comes back, tee dies too

Both result in the group thinning out over time even though they're not making mistakes.

These could both be solved using the mechanisms for timeout protection so that another player can jump in as a replacement. Right now that can be done manually, but many players don't know about how to do so. Instead we could introduce two new mechanisms:

1. /swap to swap tees with another player (with their approval of course). Note that this could also be used for speed runs to swap the tees and get faster times when one player is better in the part.
2. 1 minute before timeout protection runs out the tee becomes freely claimable for anyone. Note that this could also be abused though, with trolls taking over the tee and quickly killing the team.

I'm not sure whether the advantages are bigger than the disadvantages. Opinions?

**Comment by Ryozuki** [comment]
To solve the speedrun thing, add 1 minute more to the timer, if it's in a team, to the team timer.
Just like currently does /save

The problem i guess is the free claimable tee for anyone. Too many trolls. A way around this i think would be to make a custom vote, where only the nearby players for the tee can vote. So they can decide if they want the new player there, which would help against trolls? Maybe its to complicated.

**Comment by def-** [comment]
> To solve the speedrun thing, add 1 minute more to the timer, if it's in a team, to the team timer. Just like currently does /save

That's not acceptable, timer should not be manipulated. For teams it only works because they are forced to wait that exact time before loading. Forcing players in team 0 is a bit awkward.

**Comment by 12pm** [comment]
I don't think everyone would be ok with a random player (that they might not even like or whatever) getting their progress (in wich they might have invested a lot time) because their connection breaks down. It should only work if the original player specifically allows someone to take his spot.

**Comment by daverck** [comment]
I like the swap command

**Comment by fokkonaut** [comment]
https://github.com/ddnet/ddnet/issues/756

**Comment by Learath2** [comment]
Can we discuss this and implement or close?

Since people already effectively swap using either saves or timeouts, I think we should just implement this so it's not as much a PITA. Maybe with a time penalty?

**Comment by heinrich5991** [comment]
I'm not against implementing this, I'd like to have a similar period like save/load or timeout where the affected tees can't do anything.

**Comment by l-ouis** [comment]
i wouldn't implement the second thing where anyone can claim a tee, imagine some pro lags out at the end of some insane map and some guy that can't pass moderates just gets a free insane rank (the whole server would be spamming to try to get that spot)

I think the first idea is good, sometimes you have to go when you're far in a map. I know a lot of times on USA servers, there will be a 4-team or so going through the map and another friend might join while we're already far, and if one tee has to go, the new friend can just take the place.

> Note that this could also be used for speed runs to swap the tees and get faster times when one player is better in the part.

I think there should be some protection against this. In 2p speedrunning a part of it is that each player has to know how to optimize the parts they have to do, and allowing them to seamlessly swap kind of destroys that aspect.

A possible solution would be to freeze both players for 3 seconds after a swap, but then you have problems regarding super hammers.
