### ISSUE TITLE
Try reenabling aio now that memory allocation is thread-safe

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#1108]
@Learath2, please test once you get back to your Windows computer.

**Comment by Learath2** [comment]
Tested, still crashes instantly with aio :(

**Comment by Learath2** [comment]
After an upgrade to Windows 10 this no longer happens for me. I don't think we had any other instance of it either, so I guess we can close this?

**Comment by heinrich5991** [comment]
@Learath2 aio is currently not enabled on Windows. Can you check that it doesn't crash when you enable it?

**Comment by Learath2** [comment]
I'm far away from my desktop, but last time we attempted enabling it, it worked fine and the aio test passes fine for a couple hundred thousand iterations.

The bug that made us disable aio was perfectly consistent, always caused a crash instantly on the first write, and crashed deep in kernel32 or ntkernel.

**Comment by Learath2** [comment]
Since I no longer reproduce this and no one else seems to have encountered the same issue, maybe we should try this again?

**Comment by def-** [comment]
Sounds ok to me. @heinrich5991 ?

**Comment by Robyt3** [comment]
Windows uses a different logger implementation, so this issue is obsolete?

**Comment by heinrich5991** [comment]
Does someone remember why we have aio at all? To not block the server? Maybe we can just disable it in the client entirely, as it makes debugging harder?

**Comment by def-** [comment]
Also for client, blocking writes in same thread could be causing lags.
