### ISSUE TITLE
Editor Shortcuts [1-9...]

### ISSUE THREAD

**Issue by CptDalv** [ddnet/ddnet#1111]
I have not mapped much in TW so I cant really estimate the value of this feature but i thought of settable shortcuts like:

Ctrl + Numberkey
Saves current layer, rotation, selection, etc. to the corresponding key

Numberkey 
Selects the saved layer, rotation, selection etc. 

Saved Numberkeys could be displayed in a bar with the relevant tile

**Comment by Henningstone** [comment]
That sounds like a really useful thing to have! Keyboard shortcuts make everything quicker :D

**Comment by ChillerDragon** [comment]
I miss the possibility to switch selected tile or quads layer without the mouse but i don't know what would be a good solution.

**Comment by Learath2** [comment]
Maybe a feature to save brushes? Should be easy enough to code with an array of `CLayer`s.
