### ISSUE TITLE
Grey flags

### ISSUE THREAD

**Issue by lryjnks** [ddnet/ddnet#1115]
With the latest version of DDNet, the flags are no longer in color, is there a reason for this?

- DDNet 11.1.3
- Win10 x64
- GTX 1060

![ddnet_flags](https://user-images.githubusercontent.com/33368776/38637734-51f87510-3dcc-11e8-932f-b36a0ccf8fb4.png)

**Comment by def-** [comment]
Will be fixed in next release #1104
