### ISSUE TITLE
Faded out text rendering does not work properly

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#1124]
First bad commit: https://github.com/ddnet/ddnet/commit/c1a962b8705afa0698f93614a77f8a30cb59a163
Last good commit: https://github.com/ddnet/ddnet/commit/e642b14c88ec91b41a4a2859aa6523befa663517
Seems to be caused by #1081.

```
cl_nameplates 1
cl_nameplates_always 0
```
![Screenshot](https://i.imgur.com/Eoyryzx.png)

The player name plates are supposed to be gone, but are still displayed (as outlines maybe?). When the mouse is near such a player, the name plates are rendered normally.

**Comment by def-** [comment]
@Jupeyy ?
