### ISSUE TITLE
Downloaded maps should have a stronger hash function

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#1127]
Why has no one created an issue yet? :P

**Comment by def-** [comment]
because no one made an attack on the hash until today?

**Comment by Learath2** [comment]
We should probably update all the maps in `downloadedmaps/` to follow the new naming convention of `mapname_sha2_crc.map` but that'd mean if someone is using another client on their computer they'd need to re-download maps.

**Comment by yangfl** [comment]
sha1 is still pretty strong today, unless they have Google supercomputer, and the backward compatibility problem is more annoying since using multiple clients is not a rare practice.

However, we could use an enhanced protocol which sends additional strong hash info and compare them locally.

**Comment by heinrich5991** [comment]
@def- What should the client do if the server doesn't send a stronger hash? I think it would be good to cache the stronger hash per server IP address, map name and map CRC, and always download the map from servers where the client hasn't been before.

@yangfl There's basically no upside to using a broken hash function if better solutions are around (SHA2).

**Comment by yangfl** [comment]
> So the attack will still work against the old servers

Nevertheless we can't ask all teeworlds servers to make change. As long as there're old servers and DDNet clients are allowed to connect to them, the problem won't go.

**Comment by heinrich5991** [comment]
>Nevertheless we can't ask all teeworlds servers to make change.
That's true.

>As long as there're old servers and DDNet clients are allowed to connect to them, the problem won't go.
That's not true. The solution I proposed (and the one @def- doesn't like) does not depend on existing servers changing.

**Comment by PathosEthosLogos** [comment]
Issue closed?

**Comment by heinrich5991** [comment]
#1136 fixes this, but it's not merged yet.
