### ISSUE TITLE
request : when in pause do not show others team

### ISSUE THREAD

**Issue by daverck** [ddnet/ddnet#1138]
When spectating all teams are visible even if "/others" is disabled.

It would be nice to show others team only if combined with "/others" command.

**Comment by daverck** [comment]
now I just learned there is a /specteam cmd but it would be better to have only one in my opinion.

Also /pause is not the same as /spec on some map.

**Comment by def-** [comment]
See https://github.com/ddnet/ddnet/pull/1182
