### ISSUE TITLE
Set default chat key to enter

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1140]
Team chat could be set to right shift, because the symbol keys around the enter key are not the same across international keyboards.

**Comment by heinrich5991** [comment]
Motivation? There are some games that use 't' and some that use 'enter', in my experience.

**Comment by ChillerDragon** [comment]
@heinrich5991 team chat isn't on 't' it uses 'y' or 'z' idk and thats the point Pathos is talking about. I already had some trouble with it after updates of something that my teamchat changed key and so on.

**Comment by PathosEthosLogos** [comment]
I only came across one game that uses 't' as chat excluding TW. I think it's okay to follow the mainstream, since the return key is what new players expect it to be in general anyway.

**Comment by ZombieToad** [comment]
Source engine games(csgo,gmod) use y and u for chat and teamchat. GTA V uses t and y. minecraft uses t. i dont think new players are gonna be pressing enter to chat. i know i didnt. i cant even think if 1 multiplayer game that uses enter

**Comment by PathosEthosLogos** [comment]
All of the to games in the front page of Twitch uses enter/return key. I'm confident that more than 90% of top 1.000 games in Twitch use it.

**Comment by def-** [comment]
DDNet client binds both t and enter to chat.

**Comment by heinrich5991** [comment]
@PathosEthosLogos I'm not sure you did your research: CS:GO: https://gaming.stackexchange.com/questions/238199/how-to-chat-in-csgo
>The default key to chat in the Counter Strike series of games is y. This is All Chat, both teams will see what you can write here.
>To write a message so that only your team can read it you want to use Team Chat which is started with u.

**Comment by heinrich5991** [comment]
Oh, was already in the message above. CS:GO shows as featured game on my (unpersonalized) twitch home page.

**Comment by def-** [comment]
Right shift is +spectate already. Enter does what you want.
