### ISSUE TITLE
Current state of Teeworlds + DDNet

### ISSUE THREAD

**Issue by loru** [ddnet/ddnet#1141]
Hi,

[Please have a look at this issue](https://github.com/teeworlds/teeworlds/issues/1514), don't forget to answer there whether you are in favor or against it & if you have another proposal for the projects.
If you're simply a player, or the admin of one of the projects, whatever, just have a look!

Thank you!

**Comment by PathosEthosLogos** [comment]
@loru please close this thread. The original thread is closed.
