### ISSUE TITLE
Map editor build script

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1156]
I don't know if many people would profit from it because i don't really know the mapping behaviours of others. But i somtimes have maps where i use auto gametiles for many tiles and they have to be executed in the correct order. So if i change one little part of the map i have to apply all the gametiles agian and this can be very annoying for changing a lot of small things and testing.

So what i suggest is some sort of build button somewhere.
There you can describe what gametiles get applied in what order and maybe what tiles have which automapper. So after pressing the one button the map is ready to launch.

**Comment by def-** [comment]
I don't think that would apply to the work pattern for most mappers.
