### ISSUE TITLE
Built-in IRC client

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1161]
Split the main server list menu in half, where the bottom is the IRC chat.

Taken from #1061

**Comment by Learath2** [comment]
I don't really like this one, turning the client into emacs. An IRC client belongeth not in a game.

**Comment by ZombieToad** [comment]
discord is way better than irc

**Comment by Henningstone** [comment]
Yo let's make a Teeworlds client with a built-in discord client!

**Comment by def-** [comment]
I'd be against that. Just use a regular chat client on a second screen.
