### ISSUE TITLE
Serverlist cache (a good solution when master server is down + generally faster reload)

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1162]
From #1061 

Serverlist cache, fast serverlist updating: I think this is potentially a big upgrade for populating the server list

The master server recently went down. Server list caching would actually be a great solution for this!

**Comment by Learath2** [comment]
I don't really get this one, the only thing that can be cached is a server name, except for that any other information will be terribly out of date.

**Comment by PathosEthosLogos** [comment]
Just imagine a favourites tab that caches all servers. When the master server is down, it can just load the cache. Favourites/cache still works when the master server is down.

**Comment by ZombieToad** [comment]
i always though this was an annoying bug on ath because i  would join a server showing players on it and it would be empty

**Comment by savander** [comment]
Can't we just store Ip-addresses? You can ping servers by yourself. Doesn't master server send ip's only?

**Comment by Chairn** [comment]
I think this is partially solved with new JSON interface. If this is the case, can we close this issue?

**Comment by heinrich5991** [comment]
We now have fast reloads. Caching isn't implemented, not sure it would be all that useful.
