### ISSUE TITLE
Recently visited server category/tab

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1163]
From #1061 

Maybe give option to sort the server list by recent visits to the server or an entirely new tab for "recently visited servers"

**Comment by Learath2** [comment]
This sounds like a good idea for a new tab, but I'm not sure if we have the space for a new tab.

**Comment by PathosEthosLogos** [comment]
There is always room! Only design choice

Personally, I think reducing the amount of horizontal space needed for server name and putting in the clock/time icon would be nice. Then the values can be sorted by something like "4s" "5m" "2h" "3d" "5w" "2y"

**Comment by def-** [comment]
Doesn't make much sense for the DDNet model of having many interchangeable servers around.
