### ISSUE TITLE
Auto translator for chat

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1164]
From #1061 

Translator for chat: devs didn't seem to like Google API for translator, so maybe Moses can be an option -- https://www.quora.com/How-do-I-integrate-Moses-machine-translation-into-my-realtime-website/answer/Niko-Papula (there's link to Github under "Google Project Hosting")

**Comment by Learath2** [comment]
Don't think there is a good way to make this not look like a wacky add-on a Minecraft modder would make.

**Comment by def-** [comment]
I'd be against sending chats to some random server around the world. Learn English instead I guess.
