### ISSUE TITLE
Encrypted chat: possible for /pm or /w?

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1165]
From #1061 

I just thought there could be some security applied to the chats. My guess is that the messages are sent as plain text. If I'm wrong, please close the thread.

**Comment by Learath2** [comment]
Accounts should also make this possible. Currently it's plaintext

**Comment by def-** [comment]
Yes, chats are plaintext. I don't think we should add the complexity to change that. Use a proper chat program if you care about that.
