### ISSUE TITLE
Skin fetcher

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1166]
From #1061 

Automatically get new skins, especially when other tees have an unrecognised skin by the local client, the local client can auto search or download etc.

**Comment by Learath2** [comment]
As I said in #1061 this should be possible with @eeeee's lazy-loading from Teewebs and the skin db.

**Comment by savander** [comment]
In TrackMania, you can make skins and locator file. Locator contains URL link to skin download and then automatically downloads it. 
Maybe we should introduce similar behavior?

**Comment by fokkonaut** [comment]
ATH client has that. Look how they made it.
