### ISSUE TITLE
Coloured console text

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1167]
From a reply in #1061 

It would be really nice if this is applied! Distinguishing team colours, server message, etc. would be really helpful.

**Comment by Learath2** [comment]
Console text as in F1 or the actual stdout?

**Comment by PathosEthosLogos** [comment]
I was thinking F1, but both would be nice actually. I think stdout isn't really necessary for colour though, because nobody really uses it.

**Comment by def-** [comment]
Duplicate of #610
