### ISSUE TITLE
cl_dummy_fire doesn't work

### ISSUE THREAD

**Issue by ghost** [ddnet/ddnet#1180]
when I set cl_dummy_control and cl_dummy_fire,the dummy only fires one time.And when i changes to dummy,first click (fire) is invalid.
I don't exactly know what cl_dummy_fire is for,but it seems doesn't work correctly.
@QingGo

**Comment by QingGo** [comment]
Try to use "bind yourhotkey +toggle cl_dummy_fire 0 1" instead.
It is some kind of workaround after i have writed that code. I dont know how it work exactly but it work indeed. 
Hope anyone can make this function more perfect.

**Comment by CreeperGo** [comment]
I tried "bind l +toggle cl_dummy_fire 0 1",but sometimes when i press l,the dummy won't fire

**Comment by QingGo** [comment]
yes, the dummy won't fire when i press that hotkey quickly. But most of the time I just want to dummy fire once time at the exactly timing, instead of let it fire all the time..

**Comment by CreeperGo** [comment]
When cl_dummy_control is on,dummy copy doesn't work correctly either.Dummy won't copy fire,hook,etc.

**Comment by CreeperGo** [comment]
Rewrite needed :-(

**Comment by QingGo** [comment]
yes, so i add an addictional option cl_dummy_control, and you can choose to open it when you really need this function. This is an experimental function and I hope someone can make it perfect.

**Comment by CreeperGo** [comment]
https://github.com/ddnet/ddnet/pull/1181
Improved the fire(only fire one time),Fix dummy copy

**Comment by Chairn** [comment]
if there was a bug with dummy command, Plantknight would have tell us already. I vote to close this one.
