### ISSUE TITLE
Visual bug if laser blocker is placed in door range

### ISSUE THREAD

**Issue by 12pm** [ddnet/ddnet#1194]
Door isn't properly displayed, but still working:
![image](https://user-images.githubusercontent.com/30786226/42415935-11ac84cc-8261-11e8-9373-c5f9a7f6e689.png)

**Comment by ChillerDragon** [comment]
So its really a visual bug? Should it be visible and working door? Imo it could also be an gameplay bug because the blocker blocks stuff also doors?

**Comment by fokkonaut** [comment]
its a gameplay bug because the door shouldnt be able to go through the blocker. but i think it should stay in the game. idk cool to make invisible doors :D

**Comment by ChillerDragon** [comment]
Yea imo invisible blocks also sound like a feature. F3 for keeping it c:

Im sure you can do some funny stuff combined with envelopes and cool graphics.

**Comment by def-** [comment]
I don't think we should change it. I know some mappers used this intentionally.
