### ISSUE TITLE
F-Droid Android app repository

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1207]
I get a strong FOSS culture from DDNet/TW. Yet, it's on Google Play Store, but not on F-Droid when it should be the other way around.

What do you think about adding it into F-Droid? If you're still okay with Play, how about Aptoide? There are countries where Play isn't supported so they use Aptoide/F-Droid.

**Comment by def-** [comment]
DDNet is on play store? We didn't upload it.

**Comment by PathosEthosLogos** [comment]
Ah oops, I thought DDNet was on Play.

**Comment by heinrich5991** [comment]
We now have an android client again. But I guess it's not ready yet.

**Comment by def-** [comment]
I think it should be ready for F-Droid. What do we have to do to upload it and can I automatically upload new versions?

**Comment by Twig6943** [comment]
> F-Droid only accepts builds by them, or optionally builds by us that they can reproduce byte-for-byte on their servers. This means that either way, we're going to have them build DDNet.

Well if the team isn't down to go through allat the apk can be uploaded to a custom f-droid repository

**Comment by heinrich5991** [comment]
> > F-Droid only accepts builds by them, or optionally builds by us that they can reproduce byte-for-byte on their servers. This means that either way, we're going to have them build DDNet.
> 
> Well if the team isn't down to go through allat the apk can be uploaded to a custom f-droid repository

I think setting up our own F-Droid server is time less well spent than including ourselves into the official F-Droid repositories.

**Comment by Twig6943** [comment]
FYI there's also the option to upload it to fdroid repos with less strict policies (E.G. IzzyOnDroid)

**Comment by Twig6943** [comment]
If you're reading this please grab the apk via [Obtanium](https://github.com/ImranR98/Obtainium) for the time being

**Comment by heinrich5991** [comment]
The above comment is from a third party, the mentioned app is not recommended (and also not warned against) by DDNet.

**Comment by heinrich5991** [comment]
> FYI there's also the option to upload it to fdroid repos with less strict policies (E.G. IzzyOnDroid)

It seems IzzyOnDroid in particular doesn't accept games (except educational ones): https://gitlab.com/IzzyOnDroid/repo/-/wikis/Inclusion%20Policy

> Are there any app categories which are not acceptable to this repo?
> * Games are unlikely to be accepted (though exceptions are possible, e.g. for educational games)

**Comment by heinrich5991** [comment]
> I guess it'd be nice if we did the reproducible-builds route, then we can issue updates ourselves even if F-Droid doesn't.

Anyone trying to solve this issue: Check whether our Android builds are bit-by-bit reproducible.
