### ISSUE TITLE
"map "xyz.map" not found"

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1209]
Really weird error, never seen this before, but I just join the server, it downloads the map, but it's not found. I try joining again, it downloads again, but the map is not found again.

![1](https://user-images.githubusercontent.com/9344681/42890846-761723bc-8a73-11e8-8c29-33db39703385.png)
![2](https://user-images.githubusercontent.com/9344681/42890847-76310ce6-8a73-11e8-83af-ee1a343f8e2f.png)

**Comment by Learath2** [comment]
This probably has something to do with the stronger hash function patch, can you show the console output aswell?

**Comment by PathosEthosLogos** [comment]
Ah restarted DDNet, so no console output.

However, I found the .map and .map.tmp files. I deleted both (needed to close DDNet for this) and it downloaded fine. Maybe there needs to be a double check at the end of downloading the map of whether the map was successfully _closed_ (not sure what to call it) or not? As in the file download terminated fully?

**Comment by heinrich5991** [comment]
I could imagine the problem being that the HTTP download will refuse to overwrite an existing map file with the newly downloaded one on Windows. Could you try creating an empty file in the place where the downloaded map would go?

**Comment by PathosEthosLogos** [comment]
I'll test this or next weekend

**Comment by bojidar-bg** [comment]
I observed this problem on a friend's machine recently; the cause was lack of space on the drive it tried to download to.

**Comment by def-** [comment]
In that case we should show the correct error at least.
