### ISSUE TITLE
Ingame entities/gameskin changer

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1211]
Download the latest client and have a look.
http://k-client.rafabrony.com

(ingame) Changeable gameskins/entities/x-ray entities

especially if you play many different gamemodes or map for different modes this feature is good. being able to change gameskin is not that important but would also be cool.

**Comment by AssassinTee** [comment]
Maybe take a look at my client, the source is very old (6 years?). It can change every texture (and has an underlying folder structure).

[Assa Client on Github](https://github.com/AssassinTee/Assa-Client)

Since the development of my client is dead, do what you want.
