### ISSUE TITLE
dummys for multiple servers

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1212]
Download the latest client and have a look.
http://k-client.rafabrony.com

Connect multiple tees to different servers

You can watch for example tournaments way better without a new clients for each server. Also its good for moderators so they can handle more servers at once without the need of 10 clients.

I would imagine this like following:
Add a new button to ESC menu -> "Connect to another server"
If you click it, the server browser will open and you can select the server you want to connect a new tee to. then you click on a new button caller "connect new tee". 
I think it would be good to keep the 2 dummy limit per server so you can easily toggle between your dummy and your main with the normal toggle bind. Then there could be another new bind for toggling between the servers and/or like in K-Client a menu in ESC where you can select it.

**Comment by fokkonaut** [comment]
btw this should be made in engine\client\client.cpp

if you change the NetClient[1].Connect(ServerAddress) in DummyConnect() the dummy will actually be on another server. if you Change to it you will still see the map from your main tee, but you can send emotes and chat messages to the other Server and you get server messages from it. (checked with 2 clients, one on the server where the dummy connected)

**Comment by def-** [comment]
Don't think we should do this. I actually had it implemented and used it for spectating in a tournament, but didn't like the idea much in a general client.

**Comment by fokkonaut** [comment]
lol why?!

**Comment by def-** [comment]
If you want to watch people play on 10 servers, just run 10 DDNet clients, they don't take that many resources. Get a nice window manager for switching between them with a shortcut. Problem solved.

**Comment by fokkonaut** [comment]
i have 2000 skins and a high end pc. if i run ddnet multiple times it gets slow in loading stuff and i dont really think its a problem to add the function for multiple Dummies. many people like that feature and also there is no good reason to use for example K-Client anymore. For me, this feature is good and usefull.
