### ISSUE TITLE
unsynced quads

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1214]
if you use unsynced quads they will be synced on the client time (how long the client is active already, restarts at a restart of the game).

chillerdragon and i discovered this when we were about to make a clock in a map. It used unsynced quads and we wanted to have always the right time. it would have been possible because the server has a restart script that restarts it at 00:00. But it didnt work because the unsynced Quads are synced on the client time and not on the server time so its looking different for everyone.

so my question is: can we add Quads that are synced on the served time and not on the racetime/unsynced?

**Comment by timakro** [comment]
Seems more like a feature request than a bug to me. Unsynced quads always behaved like this.

**Comment by heinrich5991** [comment]
> can we add Quads that are synced on the served time

Synced quads are currently synced to server time.

**Comment by AssassinTee** [comment]
yeah and unsynced quads as well making this issue relevant again
