### ISSUE TITLE
dump_binds

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1217]
this command shows you a list of all your binds. i saw in other clients that you can write "bind x" and it shows you what is bound on x.

**Comment by Ryozuki** [comment]
`Console()->Register("dump_binds", "?s[key]", CFGFLAG_CLIENT, ConDumpBinds, this, "Print command executed by this keybindind or all binds");`

Execute dump_binds x
and it will show u the bind on x. Close this xD

**Comment by fokkonaut** [comment]
oh didnt know that. closed
