### ISSUE TITLE
OpenGL crash

### ISSUE THREAD

**Issue by Learath2** [ddnet/ddnet#1230]
Reported by onby on discord.
https://cdn.discordapp.com/attachments/342454474117218334/472013258379755520/Untitled.mp4

<details>
    <summary>Backtrace</summary>
Thread 10 Crashed:
0   libsystem_platform.dylib      	0x00007fff8a60f4b1 OSAtomicDequeue + 13
1   libsystem_malloc.dylib        	0x00007fff8e9368cc nano_malloc + 35
2   libsystem_malloc.dylib        	0x00007fff8e936877 malloc_zone_malloc + 71
3   libsystem_malloc.dylib        	0x00007fff8e935395 malloc + 42
4   libc++.1.dylib                	0x00007fff8347843e operator new(unsigned long) + 30
5   com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x000012340003c4a4 iSTD::CLinkedList<USC::CStructRegion*, USC::CAllocator>::CreateNode(USC::CStructRegion* const&) + 80
6   com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x000012340003c425 iSTD::CLinkedList<USC::CStructRegion*, USC::CAllocator>::Add(iSTD::CLinkedList<USC::CStructRegion*, USC::CAllocator>::CIterator const&, USC::CStructRegion* const&) + 21
7   com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x00001234003600e1 USC::CPassLivenessAndDefUsesAnalysis::ConditionalRegionIteratorNext(USC::CStructRegion const*, USC::CStructRegion*&, iSTD::CLinkedList<USC::CStructRegion*, USC::CAllocator>&, iSTD::CLinkedList<USC::CStructRegion*, USC::CAllocator>&, iSTD::CLinkedList<USC::CStructRegion*, USC::CAllocator>::CConstIterator&, iSTD::CLinkedList<USC::CStructRegion*, USC::CAllocator>&) const + 155
8   com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x00001234003606b6 USC::CPassLivenessAndDefUsesAnalysis::StructuralWorklistLiveness(USC::CStructRegion*, unsigned int, unsigned int, bool, bool&, iSTD::CLinkedList<USC::CStructRegion*, USC::CAllocator>&, bool, USC::SLivenessContextHolder const*) + 1144
9   com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x00001234003608c7 USC::CPassLivenessAndDefUsesAnalysis::StructuralWorklistLiveness(USC::CStructRegion*, unsigned int, unsigned int, bool, bool&, iSTD::CLinkedList<USC::CStructRegion*, USC::CAllocator>&, bool, USC::SLivenessContextHolder const*) + 1673
10  com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x000012340035e532 USC::CPassLivenessAndDefUsesAnalysis::StructuralWorklistRoot(USC::CStructRegion*, iSTD::CBitSet<USC::CAllocator>&, unsigned int, bool, bool, bool, bool&, USC::CGen4LIRControlFlowGraph*) + 304
11  com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x000012340035d121 USC::CPassLivenessAndDefUsesAnalysis::StructuralComputeLivenessSets(unsigned int, bool) + 541
12  com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x000012340035cc89 USC::CPassLivenessAndDefUsesAnalysis::Process(unsigned int, bool, bool, bool, bool, bool, unsigned int, unsigned int, bool, bool, bool, bool, bool) + 105
13  com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x00001234004319f0 USC::CGen4KernelFunctionList::LivenessAndDefUsesAnalysis(unsigned int, bool, bool, bool, bool, bool, unsigned int, unsigned int, bool, USC::LivenessPassEnum, bool, bool, bool) + 186
14  com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x0000123400430a6b USC::CGen4KernelFunctionList::VirtualRegistersToRegisters(bool, USC::SGrfPressureOpts, S3DKernelHardwareCapabilities const&, unsigned int, unsigned int, USC::SHADER_TYPE, unsigned int, USC::SGen4KernelFunctionListCompilationFeedback&) + 6119
15  com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x00001234001806ee USC::CGen8VertexShaderChannelSerialKernelProgram::Compile() + 730
16  com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x0000123400180088 USC::CGen8VertexShaderChannelSerialKernelProgram::Build() + 84
17  com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x0000123400180010 USC::CGen8VertexShaderChannelSerialKernelProgram::Initialize() + 188
18  com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x000012340017fed3 USC::CGen8VertexShaderChannelSerialKernelProgram::Create(void const*, PLATFORM_STR, S3DKernelHardwareCapabilities const&, USC::SGen6VertexShaderKernelProgramCacheKey const*, USC::CVertexShader*) + 173
19  com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x0000123400183973 USC::CGen8VertexShaderKernelProgram::Compile(void const*, PLATFORM_STR, S3DKernelHardwareCapabilities const&, USC::SGen6VertexShaderKernelProgramCacheKey const*, USC::CVertexShader*) + 123
20  com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x000012340018388c USC::CGen8VertexShaderKernelProgram::Create(void const*, PLATFORM_STR, S3DKernelHardwareCapabilities const&, USC::SGen6VertexShaderKernelProgramCacheKey const*, USC::CVertexShader*) + 208
21  com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x00001234004250a7 USC::RETVAL USC::CVertexShader::Compile<USC::SCompilerOutputVertexShader_Gen8>(USC::OPTIMIZER_LEVEL, USC::SVertexShaderCompileTimeOptions const&, USC::SVertexShaderDrawTimeData const&, USC::SCompilerOutputVertexShader_Gen8*&) + 357
22  com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x00001234000a8919 USC::CompileVertexShaderOpenGL(void*, USC::OPTIMIZER_LEVEL, USC::SCompilerInputStateVertexShaderOpenGL const*, USC::SCompilerOutputVertexShaderOpenGL_Gen8*&) + 961
23  com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x000012340000e148 USC::IM_Shader::Compile(void*, GFXCORE_FAMILY, void*) + 214
24  com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x0000123400062fb6 intelUpdateCtxSysProgramCommon(GLDContextRec*, GLDProgramRec*, GLDPipelineProgramRec*, void*, ShaderInfoCacheRec*, unsigned int) + 3640
25  com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x0000123400060843 gpusLoadCurrentPipelinePrograms + 569
26  com.apple.driver.AppleIntelBDWGraphicsGLDriver	0x000012340005e3af updateDispatch + 1697
27  GLEngine                      	0x00007fff8eebf315 gleDoDrawDispatchCoreGL3 + 536
28  GLEngine                      	0x00007fff8ee838b6 glDrawElementsInstanced_ACC_GL3Exec + 276
29  org.DDNetClient.app           	0x000000010bc10907 CCommandProcessorFragment_OpenGL3_3::Cmd_RenderQuadContainerAsSpriteMultiple(CCommandBuffer::SCommand_RenderQuadContainerAsSpriteMultiple const*) + 567
30  org.DDNetClient.app           	0x000000010bc0ec13 CCommandProcessorFragment_OpenGL3_3::RunCommand(CCommandBuffer::SCommand const*) + 1187
31  org.DDNetClient.app           	0x000000010bc1160c CCommandProcessor_SDL_OpenGL::RunBuffer(CCommandBuffer*) + 124
32  org.DDNetClient.app           	0x000000010bc0996e CGraphicsBackend_Threaded::ThreadFunc(void*) + 174
33  org.DDNetClient.app           	0x000000010bda8b6b thread_run + 43
34  libsystem_pthread.dylib       	0x00007fff8a039268 _pthread_body + 131
35  libsystem_pthread.dylib       	0x00007fff8a0391e5 _pthread_start + 176
36  libsystem_pthread.dylib       	0x00007fff8a03741d thread_start + 13
</details>

@Jupeyy o/

**Comment by Jupeyy** [comment]
apple, driver, closed?

The backtrace goes too deep into the driver impl, can't really tell anything by that, sry.
