### ISSUE TITLE
Sound beep when joining server

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet#1237]
When joining DDNet server and with cl_show_console 1, you got a beep beep on win7 client. I guess the windows console interprets some characters that are put to the console, especially ascii 0x07 that corresponds to the bell character.

This issue is not really new, it happend since 11.0 i think but i had to update today for teleport event.

**Comment by ZombieToad** [comment]
#985

**Comment by Chairn** [comment]
Well, close this one then.
