### ISSUE TITLE
Colline improvement

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#1248]
Sometimes people needs to use collision line like a sniper red dot for hisself
But it may occur issues for other players. Some of them even will not play with you while you "blinding" them by colline

I`d be happy if I`ll have two different (one for other players and other for myself) collines or if I`ll have possibility to turn off sending colline to server

P.s.:  my reason of always using it - I can easily detect rare mouse lags

**Comment by fokkonaut** [comment]
You can not not send it to the server, its a flag.

**Comment by def-** [comment]
cl_show_hook_coll_other?

**Comment by BannZay** [comment]
But I want to use it. Just need a way to hide it for other players
