### ISSUE TITLE
Truncate the downloads page with patch notes

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1267]
https://ddnet.tw/downloads

The page is very long now (which is a great sign), but not exactly friendliest towards weaker computers. How about just showing the latest patch notes and having a link to "see more patch notes" for older ones?

**Comment by heinrich5991** [comment]
Just to confirm, this is not a theoretical issue, but you have experienced it on a real computer? The page is almost only text, I thought browsers were capable of rendering huge pages with only test. ^^

**Comment by def-** [comment]
> Just to confirm, this is not a theoretical issue, but you have experienced it on a real computer?

On a 10 year old Intel Core2Duo L9400 using Linux it takes ~ 300 ms in Firefox and ~ 250 ms in Chromium to fully download and render the page for me. /ranks/ would be a bigger issue I imagine.
