### ISSUE TITLE
editor

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1285]
![ddnet exe screenshot 2018 09 01 - 17 44 21 68](https://user-images.githubusercontent.com/35420825/44947548-cb657800-ae0e-11e8-995c-93f12759818e.png)
![ddnet exe screenshot 2018 09 01 - 17 44 17 88](https://user-images.githubusercontent.com/35420825/44947549-cb657800-ae0e-11e8-9737-712d240f1889.png)

**Comment by fokkonaut** [comment]
oh, then fix the alpha xd

**Comment by bojidar-bg** [comment]
At first, it have alpha support as well, but someone complained they couldn't see their near-transparent (and remarkably invisible) tiles.

Not sure what to do about it, what about just clamping alpha to the (0.3..1) range?
