### ISSUE TITLE
bw support

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1287]
https://github.com/ddnet/ddnet/commit/48d1757793024f653d6f260195194914d8bf19ad

still doenst work

**Comment by def-** [comment]
How so? I join a BW server and I can zoom out.

**Comment by fokkonaut** [comment]
nope, i cant zoom and also dont have the eye wheel

**Comment by fokkonaut** [comment]
okay now this is funny. ive just reinstalled the client and its working, wonder whats wrong with my main client...

**Comment by fokkonaut** [comment]
okay now it doesnt work anymore, wtf is going on @def- ?

**Comment by fokkonaut** [comment]
oh, im dumb :D its because im on 11.4.2 and the fix was added after it. sorry!
