### ISSUE TITLE
Compile with MYSQL flag on Windows

### ISSUE THREAD

**Issue by 0xfaulty** [ddnet/ddnet#1290]
After spending a lot of time, I could not build a working version of ddnet for Windows with turned on MYSQL flag. Perhaps it would be worthwhile to check the availability of this feature and add build guides. In more detail about how I tried to build here (look recent messages): https://forum.ddnet.tw/viewtopic.php?f=16&t=5765&start=20

**Comment by Ryozuki** [comment]
Can confirm you cannot compile ddnet with mysql flag on using bundled libraries as it doesn't find them.

```cmake
function(set_extra_dirs_lib VARIABLE NAME)
  set("PATHS_${VARIABLE}_LIBDIR" PARENT_SCOPE)
  set("HINTS_${VARIABLE}_LIBDIR" PARENT_SCOPE)
  if(PREFER_BUNDLED_LIBS)
    set(TYPE HINTS)
  else()
    set(TYPE PATHS)
  endif()
  if(TARGET_BITS AND TARGET_OS)
    set(DIR "ddnet-libs/${NAME}/${TARGET_OS}/lib${TARGET_BITS}")
    set("${TYPE}_${VARIABLE}_LIBDIR" "${DIR}" PARENT_SCOPE)
    set("EXTRA_${VARIABLE}_LIBDIR" "${DIR}" PARENT_SCOPE)
  endif()
endfunction()```

I'm no cmake expert but this function actually searches the dll files under mysql/windows/lib{32,64} and the dlls are under mysql/windows.

**Comment by def-** [comment]
Could you try again? I suspect we still need the libmysqlclient.dll
