### ISSUE TITLE
feature : automaticaly add afk to pseudo + bind

### ISSUE THREAD

**Issue by daverck** [ddnet/ddnet#1291]
you get the idea :)

**Comment by heinrich5991** [comment]
I don't get the idea.

What feature is AFK referencing? What's a pseudo + bind?

**Comment by Rei-Tw** [comment]
Maybe adding the [aAFK] tag before the nickname & add a bind on the client side to show it

**Comment by PathosEthosLogos** [comment]
You can already do this by:
bind KEY player_name "[AFK] your name"

**Comment by Learath2** [comment]
You mean like an afk flag is set on the tee and you can see the afk states of players by hitting a toggle bind on client side?

**Comment by def-** [comment]
There is an afk flag already in the server, tee closes its eyes then. But it's entirely affected by when the last input makes it to the server. I don't think this feature gives a big advantage, just write "afk" in chat when you're leaving and your teammates know.

**Comment by heinrich5991** [comment]
I think you can use /pause to achieve the same effect.
