### ISSUE TITLE
server full

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1293]
if a server is full and im trying to connect to it it doesnt say its full anymore, it tries to connect forever.
(tested on ddnet test server with max 6 players)

**Comment by timakro** [comment]
![image](https://user-images.githubusercontent.com/8438790/46305042-8faa0380-c5b0-11e8-9c54-766ac61b7842.png)

I can't reproduce it.

**Comment by fokkonaut** [comment]
maybe it was due to the debug version that made its rounds

**Comment by def-** [comment]
I think I fixed this some time ago.
