### ISSUE TITLE
Color codes in chat

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1296]
maybe not directly colorcodes, but some ability to highlight some parts of a message in grey or so because sometimes it can be usefull. maybe using `text` like on discord the code line

**Comment by PathosEthosLogos** [comment]
Or separate colours for chat and other messages in f1 please!

**Comment by def-** [comment]
I think the chat is already more powerful than necessary. Just use a proper chat client if you want to chat.
