### ISSUE TITLE
Update ctf_infiltrate on vanilla servers

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1297]
The map that is currently uploaded on the DDNet vanilla servers is actually the wrong version (my mistake, I think) that is asymmetrical for red and blue teams.

https://drive.google.com/open?id=1JsCNK5t3buEifgpnPFeHxEvzQJW0mi2m

This is the latest map. Please update it! Thank you!

**Comment by def-** [comment]
Done
