### ISSUE TITLE
Upping ticks per second?

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1298]
When in a game with the DDNet client, the ticks seem to indicate that the servers run at 50 ticks per second. Is this true? This means that 2 ping is minimum even on LAN.

What do you think about doubling the number of ticks per second to 100? This would cause the server to use twice as much bandwidth, so a caution/notice should be sent out to let the server owners know. However, I don't think this should be a problem, because each player takes less than 30 kbps upload at 50 ticks, which means it would be max 60 kbps. If there are 64 players in a server, that would result in 3840 kbps or less than 4 mbps per server (though more likely to be about 3 mbps) instance of a full (64) server.

The advantage of this would be that actions will be smoother. It is similar to upgrading a 60 Hz monitor to a 120 Hz monitor, except not only visually, but also by actions.

An option could be to have ticks as a server config command.

What do you think?

**Comment by heinrich5991** [comment]
You can use `sv_high_bandwidth 1` to send a snapshot every tick (50Hz) instead of every other tick (25Hz).

Actually doubling the ticks per second is a physics change.

**Comment by heinrich5991** [comment]
(Changing the ticks per second is also going to be hard, because it's hardcoded in a lot of places.)

**Comment by def-** [comment]
Physics changes are invalid, see all previous discussions about changing physics. sv_high_bandwidth can be used for more accurate client. But I don't think it's necessary.
