### ISSUE TITLE
Server info not necessarily sorted at the right time

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#130]
The code assumes that the packet containing the last players arrives last.

CC @fstd

**Comment by heinrich5991** [comment]
How does the code work at all? It always reads a multiple of 24 players (unless capped at 64 players), and afterwards checks for an unpacker error, so this should code should only work for 24/48/64 players???

**Comment by fstd** [comment]
Yeah that is not going to work. I'll try and dig up the original implementation, it has been a while.

**Comment by def-** [comment]
Hm, I remember this change being necessary because otherwise the following packets would overwrite the wrong players. But I guess the current solution isn't right either, hm.
