### ISSUE TITLE
Editor full screen mode

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1303]
https://forum.ddnet.tw/viewtopic.php?f=45&t=6630

**Comment by timakro** [comment]
Can't reproduce on Linux.

**Comment by Learath2** [comment]
Can't reproduce on macOS either.

**Comment by def-** [comment]
I'd guess it only happens in Windows Debug builds, so something might be uninitialized.

**Comment by bojidar-bg** [comment]
I think this should be reopened. Uninitialized variables are a bug.
