### ISSUE TITLE
Dummy for muiltiple servers

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1305]
https://github.com/ddnet/ddnet/issues/1212

@def- many people like this and want it to be implemented to ddnet

**Comment by Learath2** [comment]
I don't particularly like this idea either, I don't think it fits in a generic client. What will you even be doing with this feature?

(Off-topic: does your keyboard not have a shift key?)

**Comment by fokkonaut** [comment]
xD it does have^^

**Comment by def-** [comment]
Duplicate of #1212
