### ISSUE TITLE
VS15 build performs better than GCC

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1308]
On Windows obviously, reported by Jupstar on Discord.

**Comment by heinrich5991** [comment]
How was this observed?

**Comment by Jupeyy** [comment]
Well my bro got an AMD GPU, i asked him to test OpenGL3 xd
with the current release(and nightly) he got around 300FPS less (cl refresh rate and gfx refresh rate to zero) than with the autobuild (1300FPS max vs 1600FPS max)

**Comment by Jupeyy** [comment]
Ok, I switched to windows on my main machine to test, that I'm not talking shit... and guess what:

VS15 400FPS(note: i have a different setup) more than VS17(self compiled.. even tried to disable exception handling, checked all optimazations)

VS17 performs around average 100FPS better than the website release level(with "custom" optimazations)

I really tested it many times to be sure it's not a single CPU core that just performs better or smth.
Quick research didn't really gave the insight i would want.

Also he got an Intel Skylake, I got AMD ryzen 1st gen... so probably not architecture specific

**Comment by def-** [comment]
Is https://ddnet.tw/downloads/DDNet-11.4.4-win64.zip any better?

**Comment by heinrich5991** [comment]
Argh, this is the wrong way around.

**Comment by heinrich5991** [comment]
(Debug mode should be default if `DEV` is set, release otherwise.)
