### ISSUE TITLE
Missing icon in toolbar on Windows

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1310]
According to |UroboroS| Rockus.~ on discord

**Comment by heinrich5991** [comment]
I assume you mean in the task bar, if you execute DDNet?

**Comment by def-** [comment]
That's my guess too, I just quoted him.

**Comment by xse** [comment]
I can deny i get both icons (console and client) in my taskbar 
![deny](https://i.imgur.com/UaqT4lO.png)

**Comment by def-** [comment]
Thanks for checking!
