### ISSUE TITLE
Synchronising envelopes doesn't work

### ISSUE THREAD

**Issue by 12pm** [ddnet/ddnet#1318]
Animations with checked "Synchronised" option don't reset on going through start.

**Comment by heinrich5991** [comment]
This is expected. They're synchronized between all clients. It was some preparing work for the teeuniverse stuff, so it could be reverted — but I think we should rather render it the same way as it is rendered in vanilla maps.

**Comment by 12pm** [comment]
Don't you have synchronization between all clients with the option turned off already? Since teeuniverse is not a thing anymore, it would be nice to restore the old behavior.

**Comment by heinrich5991** [comment]
> Don't you have synchronization between all clients with the option turned off already?

No. If you have the option turned off, the animation is relative to the join time.

**Comment by 12pm** [comment]
https://github.com/ddnet/ddnet/issues/1214 Maybe default sync it to server time and make it optional to sync it to race time? At least for DDRace maps, reseting it on joining doesn't have any advantage over reseting it on server start really.

**Comment by heinrich5991** [comment]
Mh. It's probably hard to *properly* synchronize with race time: What happens before you start the race? What happens in the moment you start the race? I'd guess the animation flickered before we separated race time from game time, which doesn't sound particularly polished.

**Comment by heinrich5991** [comment]
Maybe it could wait in an unanimated state until the race starts.

**Comment by fokkonaut** [comment]
dont sync on race time, sync it on server time so every client will always see the same animation on the selected quad.

**Comment by Learath2** [comment]
Is this still wanted?

**Comment by fokkonaut** [comment]
ofc

**Comment by 12pm** [comment]
yes

**Comment by heinrich5991** [comment]
> dont sync on race time, sync it on server time so every client will always see the same animation on the selected quad.

I believe this is the case today if you select "synchronized".

> Is this still wanted?

I think synchronizing on race time is a bad idea because of the reason outlined above.

**Comment by Chairn** [comment]
Relevant PR: https://github.com/ddnet/ddnet/pull/602

One way could be to synchronize every game elements to race time which would also allow 100% reproducible run.

**Comment by heinrich5991** [comment]
Not synchronizing envelopes to race time but to server time is intended.

**Comment by AssassinTee** [comment]
> Not synchronizing envelopes to race time but to server time is intended.

hard disagree, unsynced envelopes should sync to server time, bunt synced envelopes to start time as the tooltip suggests.

Currently both sync to server time patching this feature out and making them behave the same, related #10678
