### ISSUE TITLE
Handle embedding mapres automatically

### ISSUE THREAD

**Issue by 12pm** [ddnet/ddnet#1322]
New (and experienced) mappers always mess up embedding mapres. Whether it's embedding standard tilesets, or not embedding custom ones. Since it seems to be complicated, it should be handled automatically imo.
The only scenario where it could go wrong is when you have a custom tileset with a standard tileset's name, which is a really bad practice.. Maybe there is a way to verify a tileset is standard besides the name check, to make it completely proof.

**Comment by heinrich5991** [comment]
I think this was already done in #1178. Is it broken?

**Comment by 12pm** [comment]
Your implementation adds everything as external(?). My idea is that standard tilesets are added as external and custom ones as embedded. And it would probably even be best to not list them seperately then and allow mappers to easily change it manually. Especially beginners seem to be really thrown off by the two settings.

**Comment by heinrich5991** [comment]
It's indeed broken, it embeds vanilla images but not non-standard ones… #1323 fixes it.
