### ISSUE TITLE
Merging accounts of people with '/' in the beggining of their names

### ISSUE THREAD

**Issue by AssassinTee** [ddnet/ddnet#1328]
Some update added, that a prefix like `(1)` is added before usernames, that are begging with the `/` (slash) charachter. So a name like mine `/\ssa` turned to `(1)/\sssa`. I guess you did it, because commands are begging with the `/` character and it makes it therefore impossible, to write my name in the chat.
I don't think it's an issue, that these names have changed on your servers. But you forgot to merge/move the database entries of all people, whose names begin with `/`.

I am now having two (name based) account's, which have different points and which need merging (moving them together to the `(1)name`).

I guess other people may have the same problem.

**Comment by def-** [comment]
Updated for your name. I guess we can do the change for all names, but some won't fit into the character limit anymore and thus be cut off. 213 names in total btw.

**Comment by AssassinTee** [comment]
how long do the changes in the database need to take effect?

**Comment by def-** [comment]
All players now updated. Thanks for the report. I'll do the points recalculation in half an hour or so.
