### ISSUE TITLE
Reset scroll and adjust scrolling range on searching in editor

### ISSUE THREAD

**Issue by 12pm** [ddnet/ddnet#1331]
When you search something in the editor (e.g. a map to load) and have scrolled down previously, it will keep the previous scrolling range and scroll position, hence showing nothing/incorrect results. Instead it should scroll to the top result and adjust the scrolling range to fit the results.

**Comment by fokkonaut** [comment]
also if you search for something and then use arrow keys to navigate up and down it will go to the normal map that is after the currently picked map.

**Comment by Learath2** [comment]
Huh, why didn't bors close this?
