### ISSUE TITLE
cmake -DCMAKE_BUILD_TYPE=ReleaseWithDebugInfos builds without optimization

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1334]
```
/usr/include/features.h:381:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
```
keeps printing for me.

**Comment by heinrich5991** [comment]
Use `-DCMAKE_BUILD_TYPE=RelWithDebInfo`.

It's still a bug that this happens on an unknown `CMAKE_BUILD_TYPE`.

**Comment by def-** [comment]
Ah, well shouldn't we just throw an error if the type is unknown?

**Comment by heinrich5991** [comment]
Hmm. Thinking about it, I think the warning isn't too bad. It at least shows that something is unexpected, better than accidentally disabling `-D_FORTIFY_SOURCE=2` without noticing.

Disallowing other build types doesn't seem all too useful, maybe one could add a warning when an unexpected build type occurs. Other than that, I think we can close this issue.

**Comment by def-** [comment]
But if I make a typo how do I find out?
