### ISSUE TITLE
Will DDNet be compatible with 0,7 in the future? If not, possible vanilla server hosting?

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1351]
Currently, there are no vanilla mods that has anti-spoofing feature and sorry to mention it as I'm sure you're aware, but 0,7 is a disaster.

From https://github.com/ddnet/ddnet/issues/1257
> Well, we could still cherry-pick the workaround into all mods we host. Anyone want to prepare something for Vanilla?

Will this happen?

**Comment by Ryozuki** [comment]
0.7 is a disaster. In my opinion ddnet shouldn't be ported.

**Comment by chachad** [comment]
It's would be good if most part of the DDRace-mod itself will be implemented with code that will allows developers to contribute their own mods mostly just inside /game/server/gamemodes directory without of editing original codebase without a good reason.

**Comment by Learath2** [comment]
The teeworlds code isn't flexible enough for that. Not enough places to hook in. I was once working on a server side Lua scripted version of teeworlds but I just didn't have the time to make anything of it.

**Comment by PathosEthosLogos** [comment]
I agree that Teeworlds should be abandoned and 0.7 is a disaster. I consider it a minor mod of DDNet that should keep up with DDNet instead of the other way around.

However, I still think that there should be some discussions around CTF, DM, and TDM mods, whether it should be available as a part of DDNet vanilla game modes, so to speak.

Actually, what are current game modes of vanilla DDNet? Just DDRace? Is there also something like DDRacemax and others along those lines?
