### ISSUE TITLE
overlay entities

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1354]
if you have entities on ingame, it would be  cool to make the Unhook entitie invisible IF there is a hookthrough on top. by that, we can make transparent hookthrough for entities (only using the new ht)

**Comment by 12pm** [comment]
Hookthrough with no unhook underneath has its own behavior, hence it has to be visible whether it’s hookthrough and unhook or only hookthrough.

**Comment by def-** [comment]
@12pm's argument makes sense.
