### ISSUE TITLE
Telegun-blocker should be a telegun-activator

### ISSUE THREAD

**Issue by 12pm** [ddnet/ddnet#1358]
It makes more sense to specifically activate telegun on tiles than to specifically deactivate it.

- As a player it's easier to find flashy spots than to find plain ones
- The common usage of the feature seem to be parts that work by teleporting to specific spots. To cheat-proof them, everything else needs to be blocked off. This requires way more tiles than activating those specific spots.
- Same goes for parts that work by teleporting to other tees or the air (with laser)
- The tile makes entities look really messy (see https://github.com/ddnet/ddnet/pull/1356), its usage should be reduced as much as possible

I don't think it's too late for this change as only 2 maps would need to be remapped.

Also related: with the current implementation it's not possible to block telegun on hookthrough. Would need to have a third layer to map either telegun-blocker or hookthrough with.

**Comment by Ryozuki** [comment]
`Same goes for parts that work by teleporting to other tees or the air (with laser)`
What you mean on this point?

I agree with the other points.

`with the current implementation it's not possible to block telegun on hookthrough`

We could add tele-blocker on the switch layer too, for this specific case.

To do this, i would need someone to do the images...

**Comment by 12pm** [comment]
> What you mean on this point?

Parts that only use the telegun feature to teleport to other tees or to fly through the air with laser also require a lot tele-blocker tiles to cheat-proof them.

As for the image, I guess the current one without the crossed circle works. Maybe Sonix still has the SVGs.

**Comment by 12pm** [comment]
Adding telegun-activator to the switch-layers sounds good. You can use the delay variable to activate it only for certain weapons and no delay to activate it for all weapons. Might even have a use for very complex setups.
