### ISSUE TITLE
Make teleporting to tees with telegun more reasonable

### ISSUE THREAD

**Issue by 12pm** [ddnet/ddnet#1359]
Currently you will always be ported to the middle (?) of the tee, no matter where you hit it. Imo this behaviour doesn't feel right, especially since it shoots you out of the tee. Instead it should be the same as with tiles, i.e. teleport to where you hit the tee.

I don't know if Pharice 2 uses the current behaviour, might break the map.

**Comment by Ryozuki** [comment]
Nope, i think right now it's pretty nice. And i was just making a map using that.

**Comment by 12pm** [comment]
Ryozuki doesn't want to change it :sob:
