### ISSUE TITLE
Add an option to keep movement when teleporting with telegun

### ISSUE THREAD

**Issue by 12pm** [ddnet/ddnet#1360]
This would make the feature more dynamic and probably enable cool new parts, especially for solo maps. Not sure what the best implementation would be tho.

**Comment by Ryozuki** [comment]
This is easy to implement, but how you want me to implement the option, a sv_ setting (saved on the map)? tune zone?

**Comment by 12pm** [comment]
There are 2 fine approaches imo:

1. Elegant approach: Another telegun-activator tile ("blue-telegun-activator"). This would be most obvious to players and easy to use for mappers. Using both activator types in a map would be really easy.
Its downside is that it doesn’t support teleporting on tees or the air. For teleporting on tees it probably doesn’t matter (at least with the current implementation), for teleporting in the air maybe it does.
2. Comprehensive approach: Tune zones. Could probably cover any use case with this, however, it’s less convenient to map with and less obvious to players.

**Comment by Ryozuki** [comment]
I would do the first approach.
