### ISSUE TITLE
Telegun laser should act based on the last tile it bounced off

### ISSUE THREAD

**Issue by 12pm** [ddnet/ddnet#1361]
Currently it seems like it doesn't teleport if it hit a telegun-blocker during its lifetime. Imo it should always teleport as long as the last tile it hit was a non-blocked one/telegun-activator.
My logic behind this is, that, especially with a specific telegun-activator tile, it seems logical that it activates the teleportion again. It would also open up for "puzzle approaches". The current implementation is also a bit intrusive if you deal with tight areas imo. I guess a reason for it was to prevent cheats, however, I think mappers can work around that quite easily.

**Comment by Ryozuki** [comment]
Looks good to me.
