### ISSUE TITLE
Mouse sensitivity is doubled on editor.

### ISSUE THREAD

**Issue by Ryozuki** [ddnet/ddnet#1367]

**Comment by def-** [comment]
sensitivity*

**Comment by Ryozuki** [comment]
🙄 😋

**Comment by fokkonaut** [comment]
the mouse cursor is another image. its not cursor.png, as i have my cursor flipped around and it should be upside down in the editor, which its not

**Comment by Learath2** [comment]
I investigated this a bit:

- The editor does not have 2x resolution it just renders the cursor smaller.
- The handling of the mouse seems to be exactly the same as in `menus.cpp`
- The `UpdateAndRender` function isn't getting called more then one time

Still no idea what's going on there :(

**Comment by fokkonaut** [comment]
editor mousesens = ui_mousesens

**Comment by Learath2** [comment]
ui_mousesens is what you have in menus and it's what's supposed to be in
editor. But editor is faster for some reason

**Comment by def-** [comment]
The main difference I noticed is that the editor's mouse updating happens once per frame while ingame and in UI it happens on every input update. The editor requires this behaviour and it shouldn't affect the mouse speed. I made a hacky fix for now since that's better than nothing I guess.
