### ISSUE TITLE
Add smart zoom from ATH

### ISSUE THREAD

**Issue by snailx3** [ddnet/ddnet#1369]
Zooming in/out in ATH feels much more smoother than in DDNet.
Mostly a "quality of life" improvement, but nonetheless very useful for recording videos.

(source code: https://github.com/AllTheHaxx/AllTheHaxx)

**Comment by fokkonaut** [comment]
ath zooz is bad, the one ddnet has is very good

**Comment by snailx3** [comment]
It's actually very good for recording anything in teeworlds

Also you can obviously disable it, adding this wouldn't hurt anyone as the old zoom would still be available

**Comment by PathosEthosLogos** [comment]
Got video demonstration?

**Comment by 1stDecadeTW** [comment]
SMART ZOOM is a camera that zooms out a bit when the tee gets higher in the sky or go faster.

Here is an example of how it should work in game (this is not tw, but this is how it is supposed to work):
https://youtu.be/PH6PvdtyVdk?t=36

This is how it will work using the hook or interacting with movable objects:
https://youtu.be/oKCsmWN9nwk?t=8

And this is a camera logic review: https://youtu.be/TCIMPYM0AQg

AllTheHaxx (ATH) teeworlds client has introduced this useful and awesome feature, you can test it by downloading the client, turning on the smart zoom in config and give it a try on a race map :D 

![screenshot_1](https://user-images.githubusercontent.com/44511917/48298251-c6ace800-e47f-11e8-9c0b-1b490e13c332.png)

**Comment by PathosEthosLogos** [comment]
So to summarise for the devs, I think there can be two level approach to this.

1) Slow zoom out when velspeed (tee's speed) is higher (than 35, let's say).

2) Give a slight dyn cam towards the direction the tee is travelling.

I think the first one can be the solution. If 1 is 100% zoom and <1 is zoomed out, maybe you can try some formula like `1 - (sqrt(velspeed-35)/35)`. If the camera does not work with proportions/ratios, then just add multiplier (so if distance from centre top corner of the screen is 100 pixels, then (100 + 100 * sqrt(velspeed-35)/35)) or something like that.

**Comment by snailx3** [comment]
It's also worthy to note that it works while zooming out when playing or watching anywhere, not just spectating a tee. 

Gives a better zoom feel aswell

**Comment by edg-l** [comment]
We got smooth zoom now.
