### ISSUE TITLE
mapping: Сommon layer where you can move everything at once, or delete, or replace

### ISSUE THREAD

**Issue by trikiman** [ddnet/ddnet#1382]
Сommon layer where you can move everything at once, or delete, or replace.

**Comment by 12pm** [comment]
This is already achieved by selecting multiple layers. Besides that, a "global" layer would not be very intuitive - you would end up having to switch to individual layers anyways.

**Comment by trikiman** [comment]
> This is already achieved by selecting multiple layers. Besides that, a "global" layer would not be very intuitive - you would end up having to switch to individual layers anyways.

Ye, i agree, but if u have 9 layers u need click 9 times every time. it is sad(

**Comment by 12pm** [comment]
Shift + left click on the group to select all layers
