### ISSUE TITLE
Better afk detection

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1388]
I realized that being afk causes some issues on ddnet. And a solution that could improve the situation a bit is a better afk detection with visible results. We already have the eye thing but that isnt perfect.

My idea was something like:

If a player sends no inputs for 25 seconds he gets a 5 second countdown to do something (like moving mouse) or he gets marked as afk. Being marked as afk means that the name is prepended with an [AFK] tag. To loose the tag agian the player just has to send some inputs agian.
The name change message wont show up in chat and has no delay.

The idea is to solve a issue that ingame stuff can't effectivly solve. Like people going afk at spawn and then getting dragged into the first part. In such situations it would be nice for the other players to see what tee to leave in freez because he is afk. The timer that warns you from being tagged as afk could be annoying for super chill players. But people have to know when they are tagged as afk or they wonder why nobody helps them. Maybe a clientside option to set the delay or a serverside and tweak it over time. I am not sure what the best solution for the details is.

**Comment by def-** [comment]
You can see in the eyes if someone is afk.

**Comment by def-** [comment]
In freeze the eyes are inverted, so closed means not afk, open means afk. /emote should not be able to override afk-ness, that's a bug in my opinion. Pause should look the same as being afk, because you can't react when you're in pause.

**Comment by ChillerDragon** [comment]
@def- agree. But still the eyes aren‘t visible enough for the speed of the game. I am not sure if names are the best solution. But we need something stronger and something that starts earlier.

**Comment by def-** [comment]
I think names are annoying since you'll see name changes all the time.

**Comment by ChillerDragon** [comment]
@def- oh do you mean the actual change being annoying? I didn't expect that to be a problem. Because the name change is silent and active players should mostly not detected false positive. And you actually want to see that someone is afk.

I see a bigger problem with how the names work then. First of all the length of the name is a problem. If AFK is prepended all names get longer that means if the tees are next to each other the probability of overlapping increases. This makes it harder to detect who is afk and who not.

The AFK in front of a name also shortens too long names and might cause more collisions with other names that are longer and only have different endings.

And just naming them AFK forcing to allow duplicated names is also not what you want. Because especially AFK tees are tees you want to ping in chat.

That leads to the next problem. If the name is modified what name should be used to ping the player in chat?


I think those problems are bigger than that it could be annoying to see changing names.

**Comment by ChillerDragon** [comment]
closed by https://github.com/ddnet/ddnet/pull/1821
