### ISSUE TITLE
Server icon doesn't look like server icon

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1393]
I just realized that the [server icon](https://raw.githubusercontent.com/ddnet/ddnet/master/other/icons/DDNet-Server.ico) does look pretty speed racy but not server at all.
I don't know if this is an known issue because it seems pretty obvious.

But an update would be nice c; maybe something like vanilla with a terminal.

**Comment by def-** [comment]
Sure, give us a nicer icon. A terminal looks even worse I think. Maybe something similar to the DDNet logo centered in front of some server rack: https://thenounproject.com/term/game-server/735570/

**Comment by ChillerDragon** [comment]
+1 for the rack
-1 for hiring me as a designer. I suck xd

**Comment by daverck** [comment]
![ddnet_sv_icon 7](https://user-images.githubusercontent.com/7854728/52527126-9d406a00-2cc3-11e9-9575-fef3c0985d01.png)
![ddnet_sv_icon 6](https://user-images.githubusercontent.com/7854728/52527058-c0b6e500-2cc2-11e9-946b-fededd412dcc.png)
![ddnet_sv_icon mouse](https://user-images.githubusercontent.com/7854728/52526909-4d13d880-2cc0-11e9-9e83-5f940af6b5fa.png)

**Comment by Learath2** [comment]
Hmm, I wonder what CC says about "derivative" work :)

**Comment by daverck** [comment]
Boring stuff :p

> Here's how you should attribute:
> Use the embedded attribution only if the icon is larger than 100px.
> Copy the attribution text below and include it in a bibliography or image caption.
> Learn more about giving credit
> 
> Attribution text should be :
>
> > Game Server by Deepz from the Noun Project

Where do you think I should put that ? In a text file inside the icons folder ?

**Comment by def-** [comment]
license.txt I figure.
