### ISSUE TITLE
Missing newline on whisper

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1394]
I realized atleast on windows the client console looks really ugly if some whispering is going on because it fails to newline:

![ss 2018-12-06 at 07 30 20](https://user-images.githubusercontent.com/20344300/49604165-86149180-f98d-11e8-9102-1e56182729c5.png)

**Comment by def-** [comment]
Problems with showing the → and ← I guess. @Learath2 is that related to your recent windows console change?

**Comment by ChillerDragon** [comment]
Oh found another bug. If you type "hello würld" in chat the console only writes "hello w" and also eats the newline.

**Comment by def-** [comment]
Why is there no proper way to make the console print utf8...

**Comment by Learath2** [comment]
Because on windows consoles are "devices"...
I'll take another look at it :(
