### ISSUE TITLE
Keep track of punishments

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1397]
A helper/mod command that lists all muted/vote muted/banned etc players would be nice.

**Comment by fokkonaut** [comment]
f2: bans, mutes

**Comment by ChillerDragon** [comment]
@fokkonaut nice thanks but still the nobo who implemented vote_mute didn't add vote_mutes. So thats the only thing that has to be added and then i can bind it all together I guess.

**Comment by fokkonaut** [comment]
i dont know what vote mute is, but i guess you can find the vote muted players in `mutes`

**Comment by ChillerDragon** [comment]
@fokkonaut vote_mute bans players from calling votes. Even tho it is very similar to mutes it is not listed there maybe I will make a pr to fix it if I find time.

**Comment by bojidar-bg** [comment]
> .. but still the nobo who implemented vote_mute ..

Git blame says it came about with c1952d3ff10100c112ea32f4cf8934039bcf80fc and 835f56001305f52985ff6da2cf82727cea025826. You were the author of both :thinking:. Just saying..

**Comment by ChillerDragon** [comment]
@bojidar-bg yes that was the joke about my statement xd

**Comment by 12pm** [comment]
Don’t think this is worth implementing. Doing `bans` and `mutes` separately doesn’t take much effort and is more clear.

**Comment by jxsl13** [comment]
call it vote ban and not vote mute.

**Comment by ChillerDragon** [comment]
@jxsl13 agree thats why i orginally called it vote ban https://github.com/ddnet/ddnet/pull/1118
