### ISSUE TITLE
Force no doesn't work while server is moderated

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1398]
``vote no`` has no effect if `` moderate``  is active.

**Comment by ChillerDragon** [comment]
a note from jao
> I don't like that f4 forces, a bit counter-intuitive
> forcing with the usual cmds is better

I share his opinion but maybe that just the use of the moderate command idk.

**Comment by Ryozuki** [comment]
"moderate" command was made to make moderating easier on **full** servers where sometimes fast response is needed, some fun votes get f3 so fast you sometimes can't react.

Are you sure it has no effect? Looking at code i can't find out while it wouldn't.

**Comment by ChillerDragon** [comment]
@Ryozuki I didn't test it agian but i guess it has no force no effect. I get your point about fast votes. But doesn't the moderate thing slows down the votes? And about a fast reachable f3 i suggest imporving your binds instead.

**Comment by Ryozuki** [comment]
eh i dont need to improve anything im not mod anymore :P

**Comment by 12pm** [comment]
Can't reproduce anymore
