### ISSUE TITLE
Add checks for server settings in editor

### ISSUE THREAD

**Issue by 12pm** [ddnet/ddnet#1406]
Should check if a command can be used as a map setting and whether it's spelled correctly.
Could also check whether tune_zone/switch_open commands are used.

Wrongly used commands could be highlighted similar to how unused/wrongly embedded tilesets are marked.

Mapping for something that isn't DDNet and that added their own commands (e.g. KoG) would be problematic, but for DDNet this should be helpful.

**Comment by def-** [comment]
I did a small check to see which ones are wrong in existing maps (using the https://github.com/ddnet/ddnet-maps repo and config_retrieve from DDNet tools):
```
$ for i in *; do cd $i/maps; ~/src/master-build/config_retrieve *.map; cd ../..; done
$ cat -- */maps/*cfg | cut -d" " -f1|grep -v "^#"|grep -v "^$"|sort|uniq -c|sort -n
      1 sv_delete_rocket_after_death
      1 sv_endless_drag
      1 sv_hit
      1 sv_infinite_ammo
      1 sv_max_team
      1 sv_no_items
      1 sv_pickup_respawn
      1 sv_regen
      1 sv_rocket_jump_damage
      1 sv_save_worse_scores
      1 sv_strip
      1 sv_taem
      1 sv_teleport
      1 sv_teleport_grenade
      1 sv_teleport_lose_weapons
      1 sv_teleport_vel_reset
      2 sv_team_size
      2 swtich_open
      3 sv_team_max_size
      3 sv_teleport_hold_hook
      4 sv_max_teamsize
      5 sv_freeze_delay
      5 sv_old_teleport_hook
      5 sv_pausable
      8 sv_old_teleport_weapons
     26 sv_solo_server
     30 tune_zone_leave
     43 sv_deepfly
     55 tune
     75 tune_zone_enter
    102 sv_pauseable
    127 sv_max_team_size
    153 sv_team
    159 switch_open
    559 tune_zone
```

Wrong ones:
GG: sv_taem -> sv_team, sv_max_team -> sv_max_team_size
run_galaxy: all settings don't exist
LichKing swtich_open -> switch_open
EscapeTheCave, Espace, Generic Fly, Zaiross-Gores, Bullets: sv_pausable -> sv_pauseable
Amazing Drags, Momentum, Tech: sv_team_max_size -> sv_max_team_size

**Comment by Learath2** [comment]
Macro magic to build a static array of all options?
