### ISSUE TITLE
Top and Bottom swapped?

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1410]
I was just wondering if sombody confused top and bottom or if it is me confusing something.
In this [lines in character.cpp](https://github.com/ddnet/ddnet/blob/master/src/game/server/entities/character.cpp#L1336):

```
int MapIndexL = GameServer()->Collision()->GetPureMapIndex(vec2(m_Pos.x + (m_ProximityRadius / 2) + Offset, m_Pos.y));
int MapIndexR = GameServer()->Collision()->GetPureMapIndex(vec2(m_Pos.x - (m_ProximityRadius / 2) - Offset, m_Pos.y));
int MapIndexT = GameServer()->Collision()->GetPureMapIndex(vec2(m_Pos.x, m_Pos.y + (m_ProximityRadius / 2) + Offset));
int MapIndexB = GameServer()->Collision()->GetPureMapIndex(vec2(m_Pos.x, m_Pos.y - (m_ProximityRadius / 2) - Offset));
```

I assume that L=Left,R=Right,T=Top,B=Bottom. But as we all know computer science and school maths coordinate systems are different. So the pos 0/0 is the top left of the map -> The higher the y value the lower in the map. So MapIndexB (which should be bottom I guess) is m_Pos.y - value. So if it is lower than the tee in y value it is aBove and not Below.

some ascii art for tl;dr dudes:
```
0 2 3 4 5 6 7 8 9 x
1
2
3
4          Bottom           <------ MapIndexB = Tee - offset
5          o                <------ Tee
6          Top              <------ MapIndexT = Tee + offset
7
y
```

**Comment by ChillerDragon** [comment]
Only took me 11h to realize that letf and right are probably swapped as well or i am totally confused now xd.

**Comment by def-** [comment]
So there probably is a viewport transformation to rotate this? Doesn'T sound like a bug to me.
