### ISSUE TITLE
composed binds (ctrl+, shift+, alt+)

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1417]
https://github.com/teeworlds/teeworlds/pull/1589/files
https://github.com/teeworlds/teeworlds/commit/c4fbceb02e118ae370e02152e776d8c94ec1abd4

**Comment by Learath2** [comment]
I wonder how this behaves if you bind sth like `KEY_CTRL + KEY_LSHIFT`. Will check it out tonight.

**Comment by def-** [comment]
So, how does it behave?
