### ISSUE TITLE
Alt tab isn't fluid

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1442]
According to Rockus on Discord. Apparently some other clients have more fluent alt tab. Any ideas what the reason is?

**Comment by bojidar-bg** [comment]
What platform(s) does the problem occur on? Might be platform-specific, I think.

**Comment by def-** [comment]
```
<n000b> @heinrich5991 about the lagging with alt tab. Disable fullscreen works indeed.
```

**Comment by def-** [comment]
```
Windows, igpu, opengl3 disabled. Never tried 0.7.
Wait, about the opwngl3 i am not sure:grimacing:
```

**Comment by PathosEthosLogos** [comment]
This should be resolved -- @def- I think you can close this.
