### ISSUE TITLE
Upgrading system.c

### ISSUE THREAD

**Issue by Learath2** [ddnet/ddnet#1444]
We are compiling `system.c` with C90 for some reason. Should we maybe start compiling it with C99 or replace it with a `system.cpp`(C++11)?

**Comment by def-** [comment]
The reason it's C is probably because it was meant to be used in other C based projects as well.

The reason i's C90 is probably for Visual Studio's C compiler compatibility.

**Comment by Learath2** [comment]
I guess we are keeping this C90 for MSVC
