### ISSUE TITLE
browser player list

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1484]
the player list for servers in the browser is not sorted correctly. it starts with the highest time and gos to the lowest, then the tees without times come

**Comment by def-** [comment]
Looks fine to me
![screenshot-20190312@184906](https://user-images.githubusercontent.com/2335377/54223329-8c1f8e80-44f7-11e9-92e6-7fa61f79c5b0.png)

**Comment by fokkonaut** [comment]
just checked, its on BW and DDNet++, so seems like for ddrace servers with gametpye != ddracenetwork

**Comment by def-** [comment]
ok, will fix.

**Comment by def-** [comment]
Looks like DDNet++ and BW turned around the score number...

**Comment by fokkonaut** [comment]
but how? ddnet++ is based on ddnet and we didnt make any edits to that part

**Comment by def-** [comment]
See m_Score in server.cpp.

Race/DDRace/DDNet send the scores as a negative int, BW and DDNet++ as a positive int.

**Comment by fokkonaut** [comment]
ah, right. i know the issue now
