### ISSUE TITLE
cl_dummy_resetonswitch doesnt work as intended

### ISSUE THREAD

**Issue by Zoozti** [ddnet/ddnet#1488]
cl_dummy_resetonswitch makes your dummy/main tee stop its keypresses when you switch your tees and the value of cl_dummy_resetonswitch is 1
but if you switch back it will start its keypresses it had before switching again. Should be fixed that ur tee stops his inputs completely like nothing ever pressed if the command is activated and you switch tee

**Comment by def-** [comment]
Maybe that actually should be a new command now that I think about it. Not sure what exactly the original resetonswitch is used for and if changing its behaviour would hinder that.

**Comment by fokkonaut** [comment]
resetonswitch releases all key presses when you switch to your dummy. If you hold d and switch, your dummy continues to move right, but not if resetonswitch is on

**Comment by Zoozti** [comment]
seems like the problem is solved in newer clients, it bugged only for my ddnet 9 client, just checked now.
So i guess you can close the issue, does anybody know where the commit is which fixes the command already?

**Comment by def-** [comment]
https://github.com/ddnet/ddnet/pull/635 ?
