### ISSUE TITLE
ddnet 11.8 fucked up speedups

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1494]
speedups are not smooth anymore

**Comment by def-** [comment]
How to test this?

**Comment by fokkonaut** [comment]
just go on a speedup, seems like prediction is missing or so

**Comment by def-** [comment]
Are you sure this is something that changed recently? Could you bisect?

**Comment by fokkonaut** [comment]
it happens everywhere, where you have a speedup. if i use cl_predict 0 it is smooth again.

**Comment by fokkonaut** [comment]
and yes, it has changed recently. in 11.7 i guess it wasnt there.

oh, and those are my settings: cl_predict 1, cl_predict_ddrace 0

**Comment by fokkonaut** [comment]
forgot to say: when cl_predict is 0, it works smooth. but if cl_predict is 1, then cl_predict_ddrace has to be 1 to has speedups smooth

**Comment by fokkonaut** [comment]
my cl_predict_ddrace was set to 0, dont know why. sorry :)

**Comment by def-** [comment]
Now I even made a map to test it :(

**Comment by fokkonaut** [comment]
im sorry for you, deem :/

**Comment by def-** [comment]
Calling me deem hurts even more :D
