### ISSUE TITLE
New server icon doesn't work

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1495]
Fails for me with:
```
x86_64-w64-mingw32-windres: /home/deen/isos/ddnet/ddnet-master/other/icons/DDNet-Server.ico: read of 270376 returned 97905
```
Any ideas? @daverck

**Comment by def-** [comment]
I guess it might be to large?

```
$ file *.ico
DDNet.ico:        MS Windows icon resource - 6 icons, 16x16, 32 bits/pixel, 32x32, 32 bits/pixel
DDNet-Server.ico: MS Windows icon resource - 6 icons, 256x256, 32 bits/pixel, 128x128, 32 bits/pixel
```

**Comment by def-** [comment]
![screenshot-20190316@205907](https://user-images.githubusercontent.com/2335377/54480872-5c8dc080-482e-11e9-9bdd-ce72ed45b876.png)
When I open it in Gimp it also looks broken.

**Comment by daverck** [comment]
https://iconverticons.com/online/ does'nt work 
ended up using 
https://offdrive.com/convert/png/icns
