### ISSUE TITLE
Autocomplete chat commands 

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1504]
```
Im 'corneum: could it be possible to autofill chat commands with TAB just like with names?
deen: strictly speaking the client doesn't know what commands the server supports
deen: It could assume the server is ddnet and provide those commands or we could have another way of sending those commands, like the ones for f2 are transmitted to client
Im 'corneum: it would be a nice general solution for commands that i dont want to bind yet still use regulary
Im 'corneum: i always misspell showothers the first try (((
```

**Comment by Learath2** [comment]
Well we have the protocol extension, could be implemented like the rcon autocomplete.

**Comment by def-** [comment]
Nope, I really don't like the rcon autocomplete because it takes a while to load all commands.

**Comment by Learath2** [comment]
Or we could use macro magic to build an array of commands while compiling and use that on ddnet servers, but that'd only work properly on servers with the latest version. Maybe instead of sending one by one like with rcon commands we could just send a block of them.

**Comment by def-** [comment]
> Or we could use macro magic to build an array of commands while compiling and use that on ddnet servers, but that'd only work properly on servers with the latest version. 

Yep, that's what I'd do for simplicity's sake. But it might introduce a dependency from client code into server code.
