### ISSUE TITLE
Document build arguments

### ISSUE THREAD

**Issue by rffontenelle** [ddnet/ddnet#1510]
Would be nice to have documented somewhere what are the arguments available in CMakeLists.txt  for running `cmake`, in order to avoid requiring to read the CMakeLists.txt's code and other files in `cmake/` folder every time one forgets it.

**Comment by rffontenelle** [comment]
I could provide a PR, but first I want to know what would be preferable: Comments in the beginning of the CMakeLists.txt listing each argument, or a wiki page, or a text file specific for it, or include into README...

**Comment by heinrich5991** [comment]
README.md.
