### ISSUE TITLE
Client freezes after pressing TAB in spectator view

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#1526]
I tested it on the latest master build on Linux.

How to reproduce it: 
1. start DDnet
2. join server 
3. type /spec in the chat or press your key.
4. press TAB to display the scoreboard.

Expected result:
Maybe you see the scoreboard? 

Actual result:
The client freezes and crashes somehow without an error message..........

**Comment by def-** [comment]
Version? OS?

**Comment by def-** [comment]
What server did you try on? I can't reproduce it.

**Comment by C0D3D3V** [comment]
It happens on every ddnet server (I tested it on a few differnet).
But with version 11.9 it does not happen, only with latest master version.

**Comment by def-** [comment]
Could you compile a Debug version and check with gdb where it hangs? So far no one can reproduce it.

**Comment by C0D3D3V** [comment]
It also happens with other actions. But they are all not as reproducible as the described one.

**Comment by C0D3D3V** [comment]
Ok I will try it.

**Comment by C0D3D3V** [comment]
I did a little testing. It's probably not on every server, I just had bad luck before. On 95.171.92.151:8323 with Map Ravillion it happens in any case. 

I don't know how to best debug this, because it frets so strangely but somehow works in the background anyway. 

Here from two attempts: 
https://pastebin.com/vPF6HMhs

https://pastebin.com/Yu892hdz

I'll try a little more.

**Comment by def-** [comment]
Got it, the backtrace helped, thanks. It's cl_show_ids, my mistake, didn't test the last version I pushed.

**Comment by def-** [comment]
Please try the fix provided in https://github.com/ddnet/ddnet/pull/1527 , works for me.

**Comment by C0D3D3V** [comment]
works!
