### ISSUE TITLE
[feature] section time / splits

### ISSUE THREAD

**Issue by plexigras** [ddnet/ddnet#1536]
I'm not sure what the best way would be to implement this but i would love to see how much i'm ahead / behind my highscore.

or maybe someone could help me make it so that the client logs my x and y coordinates when i get teleported so i can connect it with something like [livesplit](https://github.com/LiveSplit/LiveSplit).

**Comment by Ryozuki** [comment]
use ghost

**Comment by plexigras** [comment]
what?

**Comment by 12pm** [comment]
There are time checkpoint tiles already that do that. Only on a few maps tho since mappers have to place them.

**Comment by lukitsche** [comment]
@plexigras still interested in this? I know this is six years ago, but I am having the same idea now.
