### ISSUE TITLE
CHN language failed

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1543]
![](https://cdn.discordapp.com/attachments/293493549758939136/560810049044480005/ddnet.exe_Screenshot_2019.03.28_-_13.58.41.38.png)

**Comment by def-** [comment]
On Linux it looks differently wrong and different every time I open the client. Will debug
![screenshot-20190328@180030](https://user-images.githubusercontent.com/2335377/55177397-6f37bc00-5183-11e9-9acb-338cd59f1245.png)

**Comment by def-** [comment]
Example string: `[CHN][Tom] iDDNet CHN Practise (Featured) 练习服(精选) [0/`

**Comment by def-** [comment]
With Chinese language set it's rendered fine. So the problem seems to be that we look up characters that are not in our font.
