### ISSUE TITLE
cl_confirm_disconnect_quit_time

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1550]
i am not happy with the result of this change:

1. if you set it to -1 or 0, it shows the popup all the time.
~~2. if you set it to > 0, it will not show the pop up, even after the racetime is > x~~
3. it is one setting, for both: disconnect and quit. i would like to have it seperated, as before: because i dont like to press OK when i disconnect, but i do want to click ok for quitting the game, because sometimes in the game if you want to open settings, i hit the X accidently and the popup saves me. 

so, please fix and seperate those

**Comment by def-** [comment]
1. -1 always shows it
2. Have you tried it? Works for me. x is in minutes
3. I don't think anyone else has problems with clicking on the wrong button. Who goes into settings anyway?

**Comment by fokkonaut** [comment]
"-1 to turn off" != "-1 always shows it"

**Comment by fokkonaut** [comment]
zero is meant to always show it

**Comment by fokkonaut** [comment]
yea, i tried it with set to 1, but now set to 2 and it works, sorry. but still, point 1 and 3 are not good for me
