### ISSUE TITLE
Process stays alive even after quitting client

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1554]
As MiM reported on forum https://forum.ddnet.tw/viewtopic.php?t=6791 :

> About the process thingy, just want to report that something might be wrong
> (it happens rarely maybe im at fault)
> I always close ddnet with ctrl+shift+q, sometimes the game closes but the process still exists

**Comment by Jupeyy** [comment]
I think we had quite alot of cleanup of the closing code, reopen if reported again.
