### ISSUE TITLE
cmd for change status if u mod or admin.

### ISSUE THREAD

**Issue by trikiman** [ddnet/ddnet#1557]

**Comment by trikiman** [comment]
![image](https://user-images.githubusercontent.com/39918652/55290769-13b63a00-53e0-11e9-8199-cc5ab94647aa.png)
I mean ID

**Comment by def-** [comment]
I don't understand, what do you want to change?

**Comment by trikiman** [comment]
i wanna cange id(without leave and join server).

**Comment by trikiman** [comment]
i wanna cange id(without leave and join server).

**Comment by trikiman** [comment]
> I don't understand, what do you want to change?

i wanna cange id(without leave and join server).

**Comment by def-** [comment]
why?
