### ISSUE TITLE
Grenade double explosion fix is broken

### ISSUE THREAD

**Issue by corneum** [ddnet/ddnet#1559]
you all know the problems with tunezones and the fixed grenade physics.
turns out that the map "Lunar Base" by Blue has been impossible for the past 1.5 years
on the map at CPtele 12 when door 9 is open and you want to go over it with grenade boost it is now pretty muchg impossible.
i let N9mkOik, kys:), Lexin and Cor try the part (all very high ranked players , all already finished the map in a casual manner and 2 of them are in the top5)

jao added that link thats meant to fix it in the server setting but it didnt increase the boost enough.

pls fix

**Comment by bojidar-bg** [comment]
Should be fixed somewhere around: https://github.com/ddnet/ddnet/blob/67d36b695d6b2be03683d45ca7b2d91a6098c9fe/src/game/mapbugs.cpp#L47

**Comment by def-** [comment]
I also noticed that Binary was upgraded as well. @heinrich5991 I'd suggest removing the Map Bugs thing and just adding a map setting `old_grenade_explosion` and setting it on Binary and Lunar Base.

**Comment by def-** [comment]
@heinrich5991 any opinion?

**Comment by def-** [comment]
@heinrich5991 In a few days I'll probably do what I proposed. If you have any complaints about that please say so.
