### ISSUE TITLE
system's pnglite reported as not found, but actually it is found

### ISSUE THREAD

**Issue by rffontenelle** [ddnet/ddnet#1568]
cmake's output reports the pnglite was not found in the system:
```
-- Checking for module 'pnglite'
--   Package 'pnglite', required by 'virtual:world', not found
-- Found Pnglite: src/engine/external/pnglite
```
but in a few lines below it reports as found:
```
-- Dependencies:
...
--  * Pnglite found
```
If it was using bundled pnglite, it would print "Pnglite not found (using bundled version)"

Even `ldd` reports a dynamic link to pnglite:
```
$ ldd /usr/bin/DDNet | grep png
	libpnglite.so => /usr/lib/libpnglite.so (0x00007f901933f000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f9017d92000)
```

Environment:
- Arch Linux 64-bit
- packages: [ddnet 12.0.1-2](https://aur.archlinux.org/packages/ddnet/), [pnglite 0.1.17-1](https://aur.archlinux.org/packages/pnglite/)
- build log: [ddnet-12.0.1-2-x86_64-build.log](https://github.com/ddnet/ddnet/files/3038449/ddnet-12.0.1-2-x86_64-build.log)

**Comment by heinrich5991** [comment]
From your log (it looks different from your excerpt):

    -- Checking for module 'pnglite'
    --   Package 'pnglite', required by 'virtual:world', not found
    -- Found Pnglite: /usr/lib/libpnglite.so  

The same happens if I try to reproduce it locally. The second line is output from `pkg-config` and is expected on Arch Linux, because the pnglite AUR package does not install the `pkg-config` metadata for pnglite. The line after, CMake announces that it has found pnglite on its own.

**Comment by def-** [comment]
So, not a bug I guess.

**Comment by rffontenelle** [comment]
Indeed. An Arch won't probably add a pkg-config file due to [KISS](https://wiki.archlinux.org/index.php/Arch_terminology#KISS). Closing

**Comment by rffontenelle** [comment]
Just for the record, [pnglite 0.1.17-2](https://aur.archlinux.org/packages/pnglite/) now installs a pkg-config file, so this warning message is not more.
