### ISSUE TITLE
Remove android related code

### ISSUE THREAD

**Issue by Ryozuki** [ddnet/ddnet#1575]
I think getting android support is a thing no one will ever do, and I also think it doesn't make sense to have this game on a mobile device.

**Comment by def-** [comment]
Well, it was nice to chat and spectate from Android, could even moderate. But playing is impossible without connecting a mouse and keyboard to your tablet or phone of course.

**Comment by def-** [comment]
See also https://github.com/ddnet/ddnet/issues/477

**Comment by fokkonaut** [comment]
Playing with mouse is also impossible, as the right mouse (hook) is used as "back" in android, so you cant use it. And if you really want the game on mobile for chatting/spectating you can just use the 9.3.1 (i guess?) client.

**Comment by fokkonaut** [comment]
close?

**Comment by Ryozuki** [comment]
Why close if the change is not made

**Comment by fokkonaut** [comment]
The android related code got removed?

**Comment by def-** [comment]
What are you talking about?
