### ISSUE TITLE
Integrate CPack DEB on cmake for easier debian package generation

### ISSUE THREAD

**Issue by Ryozuki** [ddnet/ddnet#1583]
I found this: https://cmake.org/cmake/help/latest/cpack_gen/deb.html#cpack_gen:CPack%20DEB%20Generator

And maybe it makes packaging easier on debian.

**Comment by def-** [comment]
@yangfl what's the best way from you guys? Do you want to add something DEB specific here?

**Comment by yangfl** [comment]
Hmm, we don't use CPack or anything other than debhelper.

**Comment by def-** [comment]
@Ryozuki Then I suggest you use the same if you want to build your own deb.
