### ISSUE TITLE
Explain game tiles in client

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1600]
instead of just in https://ddnet.tw/explain/?layer=game , should show an explanation when hovering other the respective game tile in editor.

**Comment by fokkonaut** [comment]
make it optional with a button, please

**Comment by bojidar-bg** [comment]
There should be plenty of space on the bottom, which is already used for tooltips.
It currently writes "Use left mouse button to paint with the brush. Right button clears the brush.".

**Comment by def-** [comment]
Exactly, that's where I want to add it.
