### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by trikiman** [ddnet/ddnet#1613]
sometimes  i need copy text from f1 and i got idea what if i will copy from console.

so i turn on "show console" restart tw trying copy smth from console(just mouse and ctrl+c) and back to tw and then i cant join to server because tw crash.

ps win 10.
pss what about just do possible copy from f1 in game?

**Comment by bojidar-bg** [comment]
> just mouse and ctrl+c

Not sure about windows 10, but if you do this on linux, you will just send an interrupt to the process, stopping it. If I remember correctly, you want to use mouse to select then press Enter to copy, though it is best to use the console window's context menu.

**Comment by def-** [comment]
I think he means ctrl-c to copy, not to kill process. And we should actually catch the SIGs, if not that's a bug.
