### ISSUE TITLE
time score/ normal score in demos

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1622]
demos use the score format that the client had on the last server he joined. the demo needs to know when the client had time score or normal score, because it can also change during gameplay if the server sends the msg to change score format.

**Comment by Learath2** [comment]
Hopefully that score format message is sent as a game message and not a system message...

**Comment by fokkonaut** [comment]
i think its sent as a system message, why? ...

**Comment by fokkonaut** [comment]
It didnt work when I sent it not as a system message, so I did. So we need a client-side fix or what?

**Comment by fokkonaut** [comment]
okay, so right now i send and receive the message as game message. (i send it with these flags: MSGFLAG_VITAL|MSGFLAG_RECORD) In the demo it will always have the format it had when i disconnected. so when i connect, enable time score and disconnect it will have time score in the demo. when i connect and use normal score format it and leave it will show that in the demo. cant it record changes while ingame?

**Comment by fokkonaut** [comment]
Would require a CNetObj_DDNetGameInfo, where the first bit is for Allowing Time score. Please add dummy support (both, dummy and main can have different score formats)

**Comment by Learath2** [comment]
> Would require a CNetObj_DDNetGameInfo, where the first bit is for Allowing Time score. Please add dummy support (both, dummy and main can have different score formats)

This contradicts with what you said in your PR. Either way I don't like this feature at all, why does the server get to dictate what type of score is to be shown? It should at most be a suggestion, so I'll implement it as such, if you want dummy and main having different displays that belongs on the client IMO.

**Comment by fokkonaut** [comment]
Mh? It is for custom gametypes, the same as this IsDDNet by timakro. Mods may base on DDNet but want a different score system. It is possible to toggle between different score modes (on my srv) and this is dummy independent. Right now (with that NETMSG) it works fine, just no recording im Demos.

**Comment by fokkonaut** [comment]
I couldnt get it to work using a CNetObj, but if I send the current NETMSG_TIME_SCORE as game message it ateast shows it correctly in the client demos. (not if i change it, but i just remove this feature server side.)

**Comment by fokkonaut** [comment]
just apply this and we are good to go
https://github.com/ddnet/ddnet/commit/7e2eb335ae5f4b0baca9574243caf4800fea893c

**Comment by heinrich5991** [comment]
> just apply this and we are good to go
> [7e2eb33](https://github.com/ddnet/ddnet/commit/7e2eb335ae5f4b0baca9574243caf4800fea893c)

As explained somewhere else, this is the wrong way to go. It's a persistent information about the game and it's important to be available at every tick. It is not like a chat message that is only important near the tick where it was sent.
