### ISSUE TITLE
mouse got slower since 12.1

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1630]
I thought maybe I broke something with the android removal, but didn't find any suspicious lines

**Comment by fokkonaut** [comment]
I didnt notice anything like that

**Comment by def-** [comment]
People reported it in https://forum.ddnet.tw/viewtopic.php?t=6803&p=67751#p67751

**Comment by PathosEthosLogos** [comment]
I thought it was since the implementation of inp_mouse_old

**Comment by def-** [comment]
We didn't change anything in inp_mouse_old though, did we?

**Comment by torhns** [comment]
I have the same problem

**Comment by fokkonaut** [comment]
@torhns, can you send me your settings_ddnet, please?

**Comment by def-** [comment]
Ok, I can reproduce it. Only happens with https://github.com/ddnet/ddnet/pull/1620 applied though
