### ISSUE TITLE
Vanilla Network USA #2 [DDNet] 1v1 vote not working

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1638]
74.91.114.132:8242

Vote for 1v1 is not working. Please fix!

**Comment by def-** [comment]
(This is not the correct place to report this.) I'll take a look later today.

**Comment by PathosEthosLogos** [comment]
@def- Sorry, feel free to close this.

Let me know where I should post these kinds of issues. Thanks!

**Comment by def-** [comment]
Discord, forum.

**Comment by def-** [comment]
![screenshot-20190415@175700](https://user-images.githubusercontent.com/2335377/56147101-e2c13200-5fa7-11e9-9e58-e319af107ca8.png)
works for me.
