### ISSUE TITLE
Instead of /showall send tees within current zoom level

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1641]
This will require for the client to tell the server its zoom level. Right now the CPU usage when using /showall 1 can increase from 20% to  70% on a full server.

- Reduces network load
- Can no longer watch any tee on map in demo

Maybe instead we should just make the client not render tees further away than the current zoom level? I think that would help with the CPU load and keep the ability to watch any tee in demo.

**Comment by ChillerDragon** [comment]
The demo thing is really sad. Would love to still have a possibility to record all tees on server :)

**Comment by def-** [comment]
Yeah, I think so too. So I guess just reducing the client-side CPU load is good enough.

**Comment by def-** [comment]
Weird, even when I remove the code that looked responsible the CPU stays high.
