### ISSUE TITLE
Add various character related stuff to the DDNet network character before releasing a new version

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#1649]
Thinking of stuff like "has jetpack", "no weapon hit", "no collision", "endless hook", …

Doing it before a new version allows us not to worry about backward compatibility.

**Comment by def-** [comment]
So this means I can't release a fix version for the dragger bug now?

**Comment by Ryozuki** [comment]
> 
> 
> So this means I can't release a fix version for the dragger bug now?

if you merge my pr i think its all fine
