### ISSUE TITLE
Why is max ping in scoreboard 1000 and not 999?

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1651]
![screenshot_2019-04-19_20-03-40](https://user-images.githubusercontent.com/20344300/56437115-7ebba800-62de-11e9-994c-60876077fe05.png)

Server pings and kills also have a 999 / 9999 limit. Which makes sense because 1000 consumes 1 space more for only 1 value more. And it is not that there is too much space in the scoreboard. Long clans get cut and names overlap with clans.

Just an idea.. maybe not even worth the effort.

**Comment by fokkonaut** [comment]
-> max ping in browser for filter is also 999 :) but imo 999 would look ugly here and its been 1000 for ages
