### ISSUE TITLE
Editor crashes the game when hovering over certain tiles

### ISSUE THREAD

**Issue by VxMiMxV** [ddnet/ddnet#1652]
Game crashes when i hover over a tile in the "space menu" in editor.
It's only with a couple of tiles as far as i can tell, the only ones that i 100% know crash the game are hook and gun teleport tiles on the tele layer (they don't in game layer)

I'm on win 8.1, all previous versions don't have this problem, tested it and only 
DDNet 12.2 32/64bit and the current nightly build crash for me.

**Comment by def-** [comment]
What's the space menu?

**Comment by fokkonaut** [comment]
@def- thats the menu where you pick the tile, probably related to your explainations

**Comment by def-** [comment]
Can't reproduce this, didn't see anything suspicious in Valgrind. Can anyone else reproduce?

**Comment by bojidar-bg** [comment]
I tried but couldn't, Arch Linux.

**Comment by Learath2** [comment]
Could this maybe be related to #1602?

**Comment by def-** [comment]
Yes, obviously. But can't reproduce it.

**Comment by VxMiMxV** [comment]
I'm willing to test stuff out to figure out what exactly is the problem.
Otherwise i can use an older client for mapping/using the editor
(since apparently i'm the only person experiencing this)

**Comment by def-** [comment]
You could share your settings_ddnet.cfg, maybe the resolution causes some problem?

**Comment by VxMiMxV** [comment]
That might be the issue actually since i do have an odd resolution, sorry for being dumb and not including it in the first post.
[settings_ddnet.txt](https://github.com/ddnet/ddnet/files/3114867/settings_ddnet.txt)

**Comment by def-** [comment]
Ha, now I can reproduce it! On switch layer, moving mouse around wildly.
