### ISSUE TITLE
Nightly: crash on dummy connect

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1657]
As soon as "connect dummy" is clicked, it:

1) goes to server list menu

2) crash immediately

**Comment by def-** [comment]
Only nightly or also 12.2?

**Comment by trml** [comment]
Does it happen on any type of server?

**Comment by def-** [comment]
Happens all the time? Might be a duplicate of https://github.com/ddnet/ddnet/issues/1415

**Comment by FallenKN** [comment]
latest master crashes when connecting a dummy on 0.6.5 under windows, maybe that was it?

**Comment by Learath2** [comment]
#1698 for that issue @FallenKN

**Comment by Learath2** [comment]
@PathosEthosLogos Still a thing?
