### ISSUE TITLE
Character flags

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#1659]
Freeze should maybe be a "ticks remaining" or "end tick" instead of a flag (for proper prediction).

Spectating should not be a character flag, should be a player flag (as it has nothing to do with the physical character).

**Comment by Learath2** [comment]
We should probably use the end tick as it changes less (better for the
delta)

**Comment by trml** [comment]
Prediction could perhaps also benefit from having available weapons, and strong/weak ID. Also, perhaps it could be possible to send the actual equipped weapon when you are in freeze (instead of ninja), when ddracecharacter is used?

**Comment by Ryozuki** [comment]
maybe close this
