### ISSUE TITLE
numplayers in serverbrowser

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1669]
the ddnet client has MAX_CLIENTS as 64 and in the browser it will only show numplayers with a max of 64 because of that, even if MaxClients sent by server is > 64.
A server with 120/256 players would look like this in the browser of ddnet client: 63/256

There are two ways to "fix" this:
Show maxclients for the server MAX_CLIENTS if its bigger than MAX_CLIENTS or properly add the NumPlayers variable to be able to handle thie

**Comment by kamillentee** [comment]
This works for me, is this fixed?

**Comment by edg-l** [comment]
probably

**Comment by fokkonaut** [comment]
Hey, this is not fixed.
