### ISSUE TITLE
Use scorelimit bar as weapon status

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1673]
Im 'corneum suggested on dev channel:

> afaik this field between the playerboard and spectator list is unused. maybe it could be used like this so you know what you have while in freeze. might also show jetpack superjump etc.
![waffenanzeige](https://user-images.githubusercontent.com/20344300/56686979-8f509180-66d5-11e9-818c-94ed7b6b89fa.png)

It is used for scorelimit but in race based gametypes this could make sense.

**Comment by fokkonaut** [comment]
As said on discord already, this belongs to the health and armor bar not to the scoreboard.

**Comment by ChillerDragon** [comment]
@fokkonaut agree also dislike the spot in scoreboard.

**Comment by C0D3D3V** [comment]
I think this is not what we want. Also we have now a weapon display and can talk about improving it.
