### ISSUE TITLE
ddnet folder is a mess

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1676]
![ss+(2019-04-24+at+10 52 41)](https://user-images.githubusercontent.com/20344300/56693040-c0d05980-66e3-11e9-8c3d-352205908627.png)

Especially on windows it is too much stuff there. Can we hide the dlls in a dependency folder? And the dilate, map_diff etc in a tools folder? And maybe even put both folders into data. For new users or people who redownload on updates and extend the folder with batch files this mess can get annoying and confusing.

**Comment by ChillerDragon** [comment]
oh and do we need storage.cfg? Does anybody uses it? If yes these people know what they are doing and they can place their own customized version there on need. Not sure if we should keep it there by default.

**Comment by fokkonaut** [comment]
Storage.cfg is pretty usefull, I use it.

**Comment by ChillerDragon** [comment]
@fokkonaut ok good to know that someone uses it. But as I said you probably know how to create a textfile.. and you use your own custom one I assume? So you replace it anyways.

**Comment by fokkonaut** [comment]
I use the default one but replaced the appdata path with my custom path

**Comment by PathosEthosLogos** [comment]
Isn't the standard to also put in the .dll files in `*/lib/`?

**Comment by ChillerDragon** [comment]
@PathosEthosLogos sadly the dlls have to be in the same file as the executable. And im not sure if it is cleaner/better to put the executable in lib as well and present a link to it in the root folder.

**Comment by def-** [comment]
> sadly the dlls have to be in the same file as the executable.

On Linux there is `-rpath` and on Windows there seem to be similar ways: https://stackoverflow.com/questions/107888/is-there-a-windows-msvc-equivalent-to-the-rpath-linker-flag

But to be honest I don't see it as a problem. It's nice to have all binaries in the same directory. Just create a shortcut instead of going into the directory manually every time. We could also have an installer on Windows that automatically creates shortcuts.

**Comment by Learath2** [comment]
We could install into `AppData/Local` like all the hip new self updating electron applications :P

**Comment by def-** [comment]
We are also self-updating and we even bring along curl so we'd fit right in.
