### ISSUE TITLE
HUD missing in vanilla

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1677]
![ddnet12-3-rls](https://user-images.githubusercontent.com/20344300/56695247-dbf19800-66e8-11e9-8309-515122af4824.png)
<img width="1920" alt="ddnet12-3-git-master" src="https://user-images.githubusercontent.com/20344300/56695253-deec8880-66e8-11e9-97bf-e9d55614dd40.png">

First screenshot is 12.3 from website and second is latest master self compiled. Only vanilla servers are affected as far as I can tell.

**Comment by ChillerDragon** [comment]
<img width="686" alt="log" src="https://user-images.githubusercontent.com/20344300/56695540-a1d4c600-66e9-11e9-9921-99429da8f444.PNG">

Might be an issue for my setup? Because I assume latest git is release on website. I compiled 32bit on windows 10 using MinGW.

**Comment by fokkonaut** [comment]
there is a f1 command to toggle this

**Comment by ChillerDragon** [comment]
``cl_show_hudscore`` is set to ``1`` thats why it is shown in ddrace servers. But why not on vanilla o.O ?

**Comment by Learath2** [comment]
Can't reproduce

**Comment by Ryozuki** [comment]
cant reproduce

**Comment by 12pm** [comment]
Your screen isn't on a vanilla server

**Comment by ChillerDragon** [comment]
@12pm it is on a vanilla 0.6.3 server that has https://github.com/chillavanilla/TeeworldsEconMod running which is basically an automated admin using say and broadcast commands. But i also tested on other vanilla servers and unofficial ddnet servers. It worked fine on all ddnetish servers and didnt work on all vanillaish servers.

**Comment by ChillerDragon** [comment]
Since I am the only one who can reproduce it and I didn't manage to debug it I guess its fine for now.
