### ISSUE TITLE
new prediction code

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1680]
- cl_predict_freeze is only acitve when antiping is on (dont know if that is correct?)
- the weapon switch is delayed and not immediately aswell as the fire animation of the weapon
- i have added the ddnet network character code to my modded server and it gets sent to the client, i debugged it. the client knows about all states of the players and about all states of its own character. BUT STILL there is the bug that if you are in super, the prediction for players doesnt work and the hook is invisible.
- dummy hammerfly doesnt work on non- DDraceNetwork servers. (maybe more stuff aswell) and therefore also not on DDrace, XXLDDRace servers or any vanilla server or a modded server gametype (like mine, which is based on an early release of ddnet, not the latest tho) this seems to be related to the super prediction aswell.

**Comment by fokkonaut** [comment]
i dont know if its just me, but on this server the prediction seems not to work? 91.79.103.196:8301

**Comment by fokkonaut** [comment]
(its a XXLDDRACE64 server, if that matters?)

**Comment by fokkonaut** [comment]
@trml @Ryozuki

**Comment by trml** [comment]
Will look into the freeze and super prediction.

I tested dummy hammerfly on vanilla and DDrace servers in team 0 and it seemed to work the same as on ddnet. What difference did you see? And was it with super? (Btw, the prediction of dummy hammerfly hasn't been added yet)

Weapon switch could be predicted (perhaps it could be added with a config option), but the client doesn't have accurate information about what weapons you can switch to (it is predicted based on previously equipped weapons and pickups), so predicting it may wrongly show you switching to a weapon you don't have sometimes. Actually the physics part of weapon switching is already predicted, it's just the graphics/skin part that is not shown yet (same thing with ninja skin in freeze). It could be fixed to work near perfectly on ddnet using ddnetcharacter, but would still affect non-ddnet servers.

**Comment by fokkonaut** [comment]
@trml also, speedups and stopper tiles (as far as i can tell) are not predicted on blockZ (may affect other mods aswell)

**Comment by Learath2** [comment]
@trml maybe you could keep track of the pickups to have a decently accurate list of weapons you have and reset it on kill. Which should work for any if not all mods and if a mod has a weird way to acquire a weapon it should probably also send a `DDNetCharacter`

**Comment by trml** [comment]
@Learath2 Yes, that could work. It kind of does that now, so maybe it wouldn't look bad, will test it.
