### ISSUE TITLE
since newer versions projectiles dont appear on big maps

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1682]
in my test case it was BlmapChill, a very big and old map.
ddnet client 12.3.1
not the server, changed map -> worked again
maybe related to the new prediction code

**Comment by fokkonaut** [comment]
lol, on my local server it doesnt work. on online server it does

**Comment by fokkonaut** [comment]
seems to be my server, mh

**Comment by fokkonaut** [comment]
yup, i just resized the map (made it smaller) and they would show up again (also, no antiping projectiles appear. it is a bug with the client, since the client gets the packages)

**Comment by def-** [comment]
@trml

**Comment by trml** [comment]
Is it also a problem with older client versions? One thing that could be related is that if a map is large enough, the server will send slightly different projectile data when you are far enough downwards/rightwards. But if that was the problem, it would not happen everywhere on the map (for example not in upper left corner).

Does it also happen to your own projectiles when all antiping options are enabled? Does it only affect projectiles and not laser?

**Comment by trml** [comment]
I think that the problem is not related to the size of the map, but that it creates too many projectiles (explosive bullets, etc). I had the same problem using an older client version. Emptying the game layer of the map made projectiles again.

**Comment by fokkonaut** [comment]
Emptying the game layer?

**Comment by fokkonaut** [comment]
I fixed it for myself by increasing the maximum snapshot IDs serverside.
