### ISSUE TITLE
Client doesn't read ddnet.png correctly?

### ISSUE THREAD

**Issue by VxMiMxV** [ddnet/ddnet#1684]
Whenever a friend tries to replace ddnet.png in entities_clear folder with my entites, game reads old file i guess

**Comment by fokkonaut** [comment]
Which file is it?

**Comment by VxMiMxV** [comment]
"fun fact, i closed the folder with entities, opened it again
and the file wasn't black (i left it black)
and now everything seems to work perfectly
how that happened - i don't know, it's the same folder and all, i'm 10000% sure. just curious whether it's going to fuck up again sometime xD" ~ quote from a friend.

**Comment by fokkonaut** [comment]
close
