### ISSUE TITLE
Hammer is being jerky

### ISSUE THREAD

**Issue by archimede67** [ddnet/ddnet#1709]
The hammering animation seems to be jerky, see this video
https://archithedev.tk/files/vids/JerkyHammer.mp4

@trml

**Comment by fokkonaut** [comment]
also the target cross is not updated with the new predicted weapon switch

**Comment by trml** [comment]
I somehow managed not to notice this while testing (it's caused by the last update). Will fix this soon.

**Comment by Learath2** [comment]
@archimede67 can you verify #1727 fixed this?

**Comment by archimede67** [comment]
Sure, i'll check when I have time

**Comment by archimede67** [comment]
@Learath2 I could test and see that #1727 fixed this ^^

**Comment by Learath2** [comment]
Thanks
