### ISSUE TITLE
MinGW with GCC 9 shows lots of warnings

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1713]
I'll probably take a look in a few days myself, but if anyone else wants to fix these, say so and go ahead.
[win64.log](https://github.com/ddnet/ddnet/files/3168242/win64.log)
[win32.log](https://github.com/ddnet/ddnet/files/3168243/win32.log)

**Comment by Learath2** [comment]
I think these were all fixed by #1796. Can you verify @def-?
