### ISSUE TITLE
Update 12.4.1 ate some settings.

### ISSUE THREAD

**Issue by VxMiMxV** [ddnet/ddnet#1716]
Binds and everything else is fine i think.
As far as i can tell only menu coloring got reset.
![Screen 1781](https://user-images.githubusercontent.com/47721445/57560234-bd94c900-7385-11e9-9b2d-574b6db0e3e9.png)

**Comment by Learath2** [comment]
With #1678 all the custom colors got reset, we moved to a new color format so it was inevitable without very ugly code to maintain forever that read old style colors.

**Comment by def-** [comment]
Wait what? Since when is it acceptable to just break existing settings? I definitely didn't expect that.

**Comment by def-** [comment]
Now it's too late for many, I guess, but with changes like this it's no wonder people end up not wanting to update.

**Comment by Learath2** [comment]
I mean it was quite obvious from the patch, I left it up for review for quite some time.
