### ISSUE TITLE
Disconnect warning does not appear after load

### ISSUE THREAD

**Issue by Learath2** [ddnet/ddnet#1720]
The menu seems to get the race tick from `CClient` which gets it from `CGameClient` which gets it from `CGhost`.

I haven't debugged this yet, but I don't really see anything wrong with how `CGhost` keeps track of time. However `CGhost` tracking the race time seems off, to me. Some other component should be keeping track of race related things and `CGhost` should be querying that instead.

Reported by Syltoox.

**Comment by def-** [comment]
I think that's expected. I think I remember it's the time on server, not race time.

**Comment by Robyt3** [comment]
The disconnect warning seems to consider the current race time (now) so the issue is likely resolved.

The refactoring opportunity remains, though. It's weird how `CGhost` keeps track of the current race time/tick for the entire client.
