### ISSUE TITLE
Center text entities.

### ISSUE THREAD

**Issue by VxMiMxV** [ddnet/ddnet#1721]
Just makes sense to me.
Here's how my original entities look like:
Scale 100
![Original entities scale 100](https://user-images.githubusercontent.com/47721445/57562129-998ab500-7390-11e9-9421-01ebdc31eef6.png)
Scale 60
![Original entities scale 60](https://user-images.githubusercontent.com/47721445/57562153-a8716780-7390-11e9-9556-bf20faea1034.png)

'FROM' is covered anyways..
Ideally it would be best to remake original entities but that's a whole other topic..
![NotCentered](https://user-images.githubusercontent.com/47721445/57562174-ba530a80-7390-11e9-97cf-535e4073f2cc.png)
![Centered](https://user-images.githubusercontent.com/47721445/57562183-c048eb80-7390-11e9-9353-4aa5c99932e6.png)
Imo this looks much better and would be less confusing.

Side note: dynamic scaling would be nice as well
(cl_text_entities_size changes based on if its a single digit number or if its  a numeral)
Or something like that.
Although i don't know if its even possible to implement that, just an idea i had to prevent numbers sticking out like this:

Scale 100
![Scale 100](https://user-images.githubusercontent.com/47721445/57562534-f5a30880-7393-11e9-8cf8-00627556e62d.png)
Scale 60
![Scale 60](https://user-images.githubusercontent.com/47721445/57562539-fcca1680-7393-11e9-9085-328e9c49f9e8.png)

**Comment by 12pm** [comment]
There is a lot stuff that doesn't make sense with this feature

**Comment by VxMiMxV** [comment]
neato

**Comment by BannZay** [comment]
What definitely makes sense to me is moving numbers right to the center of the tile. It looks much and much better.
