### ISSUE TITLE
Hookstop tile acts like hookthrough?

### ISSUE THREAD

**Issue by VxMiMxV** [ddnet/ddnet#1737]
![Screen 1839](https://user-images.githubusercontent.com/47721445/57973355-fea16480-79a7-11e9-981f-4b64d4b0eeb9.png)
Why does this tile act as hookthrough?
Noticed just now while playing Grandma.
![Screen 1840](https://user-images.githubusercontent.com/47721445/57973405-c9e1dd00-79a8-11e9-8fe4-082b47d8ad79.png)
(it has the same texture as new hookthrough tile, i'm guessing the mapper mistook hookstop for hookthrough)

**Comment by 12pm** [comment]
that's by design

**Comment by VxMiMxV** [comment]
neato

**Comment by fokkonaut** [comment]
close

**Comment by VxMiMxV** [comment]
I actually didn't get an answer though.

**Comment by Ryozuki** [comment]
> 
> 
> I actually didn't get an answer though.

If u are using new versions of ddnet, go to editor, hover over the tile, and u get a description on bottom.

Now, close this.

**Comment by fokkonaut** [comment]
You got, its by design. This is an intended feature

**Comment by VxMiMxV** [comment]
Why does this tile act as hookthrough?
-Because it's a feature.
neato
