### ISSUE TITLE
Install .desktop and icon files

### ISSUE THREAD

**Issue by rffontenelle** [ddnet/ddnet#1753]
Currently, DDNet installs only a binary to start and run the game, and also data folder. Starting the game requires double-clicking the binary in a file manager, or running the binary from the command-line interface.

My propose is to also install _.desktop_ and icon files, to better integrate with Linux desktop environment.

### DDNet.desktop files

Desktop environments like GNOME make use of _.desktop_ files in a way that the game can be found and ran by start typing its name in a search field. That's very handy for DDNet Client. For instance, in GNOME, one can press Super/Meta key and start typing "ddnet" and the DDNet Client would come up.

Here is a suggestion of _DDNet.desktop_ for your consideration: [DDNet.desktop.txt](https://github.com/ddnet/ddnet/files/3209281/DDNet.desktop.txt)

### .png icon files

The source code repository has _.ico_ and .icns files for both DDNet Client and Server. While _.ico_ can be extracted using [ImageMagick](https://imagemagick.org/index.php)' `convert` tool, for _.icns_ one could use [libicns](https://icns.sourceforge.io/)'s `icns2png` tool.

These extraction commands return _.png_ files in various sizes which could be installed into the proper hicolor folders (e.g. 256x256 icon in `/usr/share/icons/hicolor/256x256/apps/ddnet.png`), so that _DDNet.desktop_ can display the icon for the client.

For reference, see how the icon extraction is done in [AUR ddnet](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=ddnet&id=24ba420cc6b0e93ded3b8a89513ec362e0167c56) and [Debian ddnet](https://salsa.debian.org/games-team/ddnet/blob/6b4804b9e445e39a7457f90b307b9812d93fa658/debian/rules) packages.

**Comment by Ryozuki** [comment]
CPack install should also install a ddnet.desktop file to /usr/share/applications/

That way i can find ddnet with dmenu.

Here is what debian .deb installs

```
[Desktop Entry]
Type=Application
Name=DDNet
GenericName=Platform Game
Comment=A Teeworlds modification with a unique cooperative gameplay
Exec=DDNet
Icon=DDNet
Categories=Game;ArcadeGame;
Keywords=game;multiplayer;
```
