### ISSUE TITLE
Some players hear jumping sounds from all players

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1755]
no matter the distance, with /showothers 1. On current version.

**Comment by Ryozuki** [comment]
I got all the way down to:
https://github.com/ddnet/ddnet/blob/d482edc7d37884b4ce41e34828b03db3ac31da6d/src/engine/client/sound.cpp#L867

Is this using sdl2? It might be a sdl2 bug maybe.

I have no clue.

**Comment by fokkonaut** [comment]
Probably related https://github.com/ddnet/ddnet/issues/1532

**Comment by Jupeyy** [comment]
close same as #1532
