### ISSUE TITLE
Can't see unattached hooks from dummy

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#1766]
Bug report by texnonik via Discord:
>[9:35 PM] texnonik: dummy copy move glitch if you both try hook air or unhook block you don't see is dummy is hooking or not
>[9:35 PM] texnonik: https://cdn.discordapp.com/attachments/293493549758939136/584465342890246145/2019-06-01_22-34-08.mp4

archimede67 says that it even applies to all tees:
>[9:39 PM] archimede67: @heinrich5991 its the same for anyone not only his dummy
>[9:39 PM] heinrich5991: @archimede67 so the bug is that you don't see anyone's hooks?
>[9:39 PM] archimede67: when they are not hooking you or hookable, yea
>[9:40 PM] heinrich5991: sounds pretty serious :open_mouth:
>[9:40 PM] archimede67: @Ryozuki knows that bug i think
>[9:40 PM] archimede67: i was guessing its some prediction bug
>[9:40 PM] archimede67: because you see them hooking when you are in spec

**Comment by fokkonaut** [comment]
maybe related
https://github.com/ddnet/ddnet/issues/1734

**Comment by Learath2** [comment]
This only happens with antiping on, with predict other players. @trml

**Comment by fokkonaut** [comment]
Fix #1734 before the release too, I'd say.
