### ISSUE TITLE
File score not saving everytime

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1776]
Sometimes it works, sometimes it doesn't. The file score system doesn't always write ranks, but reading is no problem. The time gets added to the player, but when calling /rank it returns "Several players were found"

**Comment by fokkonaut** [comment]
Wrong indication probabaly, so fixed by this https://github.com/ddnet/ddnet/commit/fabdc7308772d5386f76803fd6eb04c2d7608120

**Comment by fokkonaut** [comment]
This is still a thing, not like described before tho. But ranks are not saved everytime when using file score

**Comment by edg-l** [comment]
We don't have file score anymore.
