### ISSUE TITLE
Feature Request: spectate_closest

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#1793]
Often times when spectating I want to switch between the same 2 tees rapidly. There could be a command "spectate_closest" that finds the tee nearest to the one you're currently spectating, and switches to it. Pressing it repeatedly would, most of the time, switch back and forth between the same 2 tees, as desired.

This sounds pretty easy/fun to implement. I might implement it eventually, but probably not in the near future.

**Comment by BannZay** [comment]
it will be even better if the next scenario will be also possible:
1. Enter spectate normally (without attaching to any player)
2. Find an interesting pair and place cursor somewhere near them
3. Press a button to attach to them

**Comment by trml** [comment]
0.7 has something like this: teeworlds/teeworlds@85b2f98d7
