### ISSUE TITLE
Speedups upwards with max speed are extremely buggy

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#180]
Try speedups of strength 5 and max speed 5 and move a bit inside them. Sometimes you move up slowly, sometimes quickly, sometimes you even move down. This also bugs Speedup prediction, especially on Windows.

**Comment by CytraL** [comment]
This fix can break some maps no?

**Comment by def-** [comment]
That's a potential problem, yes. But I consider it soo buggy, that I hope no map uses that.

**Comment by Laxa** [comment]
If I remember correctly, some maps used some speeders bug, can't remember any of the names though.
That's indeed the problem of ddrace, some mappers use those bugs as features and that can be quite annoying.
Remember the tee tower bug few years ago...

**Comment by Henningstone** [comment]
I use speedups (direction upwards) on the only map I did yet too, and when I am in it and press d, i fly up with a incredible speed, but when I don't do I move up quite slow, like it is configured.
