### ISSUE TITLE
Ghost shows me a high red + number immediately when I join a server

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1807]
Tried on Stronghold 2, not sure what that is supposed to mean.

**Comment by Learath2** [comment]
Smells like an uninitialized variable.

**Comment by Learath2** [comment]
This is rather tricky. The first issue is that @heinrich5991 kinda interpreted the code wrong while doing the capabilities patch so the SV_RECORD message gets interpreted wrong. 

The second issue however is that the timer code itself just doesn't make sense to me i.e. it should have never worked, maybe I'll have a better look tomorrow to understand how it used to work.
