### ISSUE TITLE
Client crash on dummy connect

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1812]
I was on Stronghold 3 and connected my dummy, before I even saw the view of the dummy the client crashed. When I entered the server, the dummy was there.

**Comment by Learath2** [comment]
The dummy was there because you never disconnected, timeout protection was waiting.

If the crash isn't reproducible or you can't get a backtrace for it, this issue should be closed.

**Comment by Learath2** [comment]
Can't reproduce, can't fix without atleast a backtrace.
