### ISSUE TITLE
Antiping hammer other tees on solo server

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1814]
If you try to hammer another tee on a solo server while antiping is on you cant spam the hammer, because the client thinks there is a delay but we actually cant hit the tee so we should be able to spam

**Comment by trml** [comment]
There was recently a fix related to this (weapons on solo servers). Does it still happen with the latest server source?

**Comment by Learath2** [comment]
@fokkonaut is this still a thing on latest master?

**Comment by FallenKN** [comment]
Didn't have a delay on latest
