### ISSUE TITLE
Show map infos in scoreboard

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1818]
From discord:

Evgesha:
> Can we make a feature
when you holdimg down "tab", instead of "Scoreboard" title there would be map name?
As for me its too useful, because Im using /mapinfo a lot, so instead of doing this I could simply press tab
Also maps would be known by names

Sounds like a neat feature to me. We maybe could also request /mapinfo on join and parse it to show the author?

**Comment by Ryozuki** [comment]
he is just lazy

**Comment by def-** [comment]
> We maybe could also request /mapinfo on join and parse it to show the author?

Nonono.
