### ISSUE TITLE
No way to assign another bind for play/pause for demo viewer

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#1820]
Space bar is used for play/pause and there is no way to rebind it. Please give us a way to rebind this!

**Comment by Learath2** [comment]
Not as easy as components like the demo player, the editor and the serverbrowser handle their own key presses. Binds don't really apply to them, so it'd be hard to find a neat way to do this.

**Comment by edg-l** [comment]
I don't understand, this is already in the client.

I got f7 bound to demo_play and it works, i use it to start recording and the demo playing at the same time. (it also stops it if you press it again)
