### ISSUE TITLE
Strong/weak order is wrong when killing a locked team through a death tile

### ISSUE THREAD

**Issue by 12pm** [ddnet/ddnet#1828]
The player who touched the tile should respawn first and have strong hook.
Reported by NovaShock

**Comment by Learath2** [comment]
I think this has to do with the fact that dying from a kill tile doesn't immediately call `CPlayer::Respawn` which means the respawn of the tee killed by the tile happens on a later tick, but the respawn of the tees in the team happens immediately.

I guess the best way to fix this would be to call `CPlayer::Respawn` on the tee calling `CGameTeams::OnCharacterDeath` aswell. Should be a pretty easy fix.
