### ISSUE TITLE
Empty lines in chat

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1835]
If the previous message is exactly the max lenght of characters per line, the next message will be empty, it doesnt matter if its a server or client message. I think because of the line ending it will go in the next line, but I dont know

**Comment by fokkonaut** [comment]
Best example: Write /showall

**Comment by Learath2** [comment]
I think this is dependent on resolution , I couldn't really get it to happen on my screen.

Please show a screenshot and give settings.

**Comment by fokkonaut** [comment]
![ddnet exe Screenshot 2019 07 19 - 01 39 19 21 (2)](https://user-images.githubusercontent.com/35420825/61499053-14da9980-a9c6-11e9-96da-817ebe0b5dcf.png)

gfx_screen_width = 1920
gfx_screen_height = 1080

**Comment by Learath2** [comment]
Hmm, this isn't just resolution either, it doesn't happen for me at 1080p either, but maybe that has sth to do with the macbook display being hidpi.

**Comment by fokkonaut** [comment]
Can anyone on windows check with 1080?

**Comment by FallenKN** [comment]
@fokkonaut doesn't happen for me on windows

**Comment by fokkonaut** [comment]
So why does it happen for me?

**Comment by 12pm** [comment]
can reproduce with fokos settings

**Comment by Learath2** [comment]
If you can reproduce you can fix \o/

I'm willing to bet that it happens when only a single character wraps and
it's a linebreak.

**Comment by 12pm** [comment]
there is no newline char

**Comment by fokkonaut** [comment]
![image](https://user-images.githubusercontent.com/35420825/94450344-72af6780-01ad-11eb-8d51-d0adf63316a7.png)

re-open please

**Comment by Learath2** [comment]
We still can't fix it until one of us can reproduce it. (Or you can fix it since you can reproduce it)

**Comment by heinrich5991** [comment]
I guess no one tried it on 1920x1080 on Windows yet.

**Comment by heinrich5991** [comment]
Ah, except 12pm.

**Comment by fokkonaut** [comment]
I will try what I can do

**Comment by def-** [comment]
I can reproduce until window is correct size. Will try to fix.

**Comment by def-** [comment]
![screenshot-20200928@180725](https://user-images.githubusercontent.com/2335377/94457884-7ba43700-01b5-11eb-9ce3-b9712b8cf97b.png)
There is also the opposite problem of the text overlapping the next line, but that one is harder to reproduce.
