### ISSUE TITLE
Change spectator view on paused demos

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1843]
It would be nice if you can select a tee while a demo is paused.

**Comment by fokkonaut** [comment]
You can, hold down right shift (or the bind for player picker) and select someone else

**Comment by ChillerDragon** [comment]
@fokkonaut oh wow it actually works but you have to press play then to see it. So you can't pause the demo and check all players.

So the issue here is not selecting a player but updating the view after selecting a player.

**Comment by C0D3D3V** [comment]
You would have to rerender that tick, because the selection is only evaluated after one tick
