### ISSUE TITLE
Highlight friends in tab/free-view

### ISSUE THREAD

**Issue by VxMiMxV** [ddnet/ddnet#1869]
Add an indicator/highlight the row?
This would be immensely useful for the free-view menu.
![Screen 3427](https://user-images.githubusercontent.com/47721445/62233548-172af380-b3c9-11e9-9af0-6492ed18b007.png)

**Comment by ardadem** [comment]
Something like this?

![ss](https://user-images.githubusercontent.com/13207692/62253663-4bb9a200-b3ff-11e9-86c4-81c5898ecac0.png)

**Comment by VxMiMxV** [comment]
Exactly.
Heart makes sense but i don't like it personally.

**Comment by Ryozuki** [comment]
I don't think this is useful at all.

**Comment by fokkonaut** [comment]
Not too pretty, just type /pause <name>

**Comment by Learath2** [comment]
How does `/pause` help here?
