### ISSUE TITLE
Undefined behavior when registering an unchangeable command with more flags

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1879]
When registering a command here https://github.com/ddnet/ddnet/blob/master/src/engine/server/server.cpp#L3033, so that you cant change it ingame, like `sv_test_cmds` or `sv_rescue` AND applying a flag, like `CFGFLAG_GAME` aswell, the server crashes on `shutdown` for example

**Comment by Learath2** [comment]
I can't reproduce this at all, I think you are invoking UB somewhere else in your code.
