### ISSUE TITLE
browse_icons

### ISSUE THREAD

**Issue by VxMiMxV** [ddnet/ddnet#1880]
I'm too dumb to make a pull request :^ could you just replace these?
re-drew them a little bit cleaner

**Comment by def-** [comment]
Thanks!

**Comment by def-** [comment]
Do you have an example screenshot to see the differences btw?

**Comment by VxMiMxV** [comment]
Sorry i've uploaded the wrong one, use this one please.
https://i.imgur.com/6zFvSj8.png
As for the screenshots, its really hard to tell the differences on them.
But generally there are less 'wonky,blurry' edges and stuff.
![boob](https://user-images.githubusercontent.com/47721445/62411899-aff48580-b5fa-11e9-85fd-fa1e30e0318f.png)

**Comment by Learath2** [comment]
It could be that the old ones looked a little blurry because of dilate, but
idk if we are supposed to
