### ISSUE TITLE
Unable to click any menu item

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1884]
Sometimes, I randomly cannot click on any buttons or boxes in the menu, like settings or ESC. I think this is caused by fast alt-tab switching.

**Comment by Learath2** [comment]
This happens to me on macOS all the time, I need to switch workspaces to get it working again.

**Comment by fokkonaut** [comment]
For me only a client restart fixes it, Windows

**Comment by Jupeyy** [comment]
I think i found a way to reproduce it

press left & right mouse click (hold them)
press F5 (refresh)

now you cannot click anything anymore

**Comment by Jupeyy** [comment]
@Robyt3 maybe u can take a look, you probably know the UI code best, dunno if it's an easy fix
