### ISSUE TITLE
Cannot play demo without map file

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#1886]
Why dont we store the map file inside of the demo file? Right now we cannot play the demo, if the map is edited. For example record a demo on DDNet server on Kobra 4. Then go to editor, and click "load current map". Just edit the map a bit and hit ctrl+s, so dont save it in your private maps folder. Then try to play the demo and you will get a "map differs from server hash1 != hash2".

**Comment by def-** [comment]
We do store the map file inside the demo. And then the client extracts the map file from the demo. Then the client tries to find the map file and loads the wrong one since there are multiple.
