### ISSUE TITLE
Inactive dummy should have afk indications (eyes, afk tag)

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1887]
Suggested by Noctua in PM. Not sure if we want that.

**Comment by VxMiMxV** [comment]
Would be cool to have a differently styled emote for that, and one that't not in the emote-wheel menu.
![Screen 3470](https://user-images.githubusercontent.com/47721445/62617077-56010200-b911-11e9-8526-433e21890e0f.png)
something like that, OR if dummy will end up having the bubble as well, make it universal, something like "inactive" instead of "AFK"

**Comment by FallenKN** [comment]
dummy isn't handled diffrently

**Comment by Learath2** [comment]
Maybe we can add a message to let the client set itself afk, so the dummy
switch can immediately send that and it's something we can use to improve
afk detection as a whole.

**Comment by fokkonaut** [comment]
We should send the server who our dummy is, so the server can set it. Because otherwise cheat clients would abuse this and add a setting "Afk emote (DDNet servers only)", and that would completely break the sense of this feature.

**Comment by BannZay** [comment]
I am completely don`t understand the magic sense of not allowing users to enter afk state.

 Just open this possibility to users. Then no questions left how to implement auto entering afk state on dummy switch

**Comment by BannZay** [comment]
> Maybe we can add a message to let the client set itself afk, so the dummy switch can immediately send that and it's something we can use to improve afk detection as a whole.

It will be a huge improve. Until you can`t manually enter afk mode this feature makes few times less sense

**Comment by Ekidoxx** [comment]
Close, since we have closed eyes & sleep emote for players inactive for longer than x seconds?

**Comment by BannZay** [comment]
@Ekidoxx I guess the issue was about to mark dummy once you switched to your main tee or vice versa. So people will know that this tee not able to interact with you right now.

> we have closed eyes & sleep emote

Can not see how does this can help in this case

**Comment by Ekidoxx** [comment]
Ah, then I misunderstood, my bad.

Well then, since we have the feature of marking tees as afk after a while, this could be used to immediately mark dummy with it after the switch between tees

**Comment by C0D3D3V** [comment]
> Maybe we can add a message to let the client set itself afk

Could us also allow to send afk state if you switch to another window.

**Comment by heinrich5991** [comment]
I don't think we want this.
