### ISSUE TITLE
off-screen editor buttons

### ISSUE THREAD

**Issue by VxMiMxV** [ddnet/ddnet#1896]
Buttons at the top go off-screen.
![Screen 3487](https://user-images.githubusercontent.com/47721445/63206668-4162fd80-c0b9-11e9-83a3-06034f536b02.png)

My resolution:
![Screen 3490](https://user-images.githubusercontent.com/47721445/63206678-65beda00-c0b9-11e9-9919-8f9787eb71d4.png)

**Comment by Learath2** [comment]
Pretty hard to fix with our current UI tools, It's not trivial to make the toolbar wrap :/

**Comment by VxMiMxV** [comment]
Seems like #2186 partly resolved this issue.
