### ISSUE TITLE
add cl_text_entities button in the editor?

### ISSUE THREAD

**Issue by VxMiMxV** [ddnet/ddnet#1897]

**Comment by 12pm** [comment]
why?

**Comment by VxMiMxV** [comment]
Am i the only one that primarily plays with text entities off?
There's no way to toggle text entities back on without connecting to a server is there?

**Comment by 12pm** [comment]
what editor are you talking about

**Comment by VxMiMxV** [comment]
![Screen 3493 (2)](https://user-images.githubusercontent.com/47721445/63225255-1918f300-c1ce-11e9-94ee-446bb5f31e9e.png)

**Comment by 12pm** [comment]
and why exactly do you need to turn text entities off for mapping?

**Comment by VxMiMxV** [comment]
I'm sure there are some instances where that would be useful, but that's not the point-i'm playing with text entities off almost all the time, i only turn them on when a part is very confusing. So having a button for this would be great for me personally instead of having to ctrl+shift+e, connect to a server, toggle text entities on, ctrl+shift e back (or typing cl_text_entities 1 in the console)

But if you think this is useless then you can close this.

**Comment by 12pm** [comment]
this button should be in settings and the config shouldn’t affect editor imo

**Comment by VxMiMxV** [comment]
Yeah 'the config shouldn't affect editor' seems reasonable.
But what do you mean that the button should be in settings?
Maybe have it in the key-bind section under 
![Screen 3494](https://user-images.githubusercontent.com/47721445/63227670-4921bf80-c1e9-11e9-943d-ecf26480d81c.png)
Text entities = toggle  cl_text_entities 1 0

**Comment by fokkonaut** [comment]
This is a feature not many people use/need. It doesnt deserve a setting in the menu, and yes jao, it shouldnt affect editor.

**Comment by 12pm** [comment]
why closed?

**Comment by VxMiMxV** [comment]
@fokkonaut 
> This is a feature not many people use/need. It doesnt deserve a setting in the menu, and yes jao, it shouldnt affect editor.

It's like saying entities is a feature not many people use/need.
Text entities is great for fps improvements, understanding parts better,etc.
Besides, some pc's can't handle mapping tunezone,switchfreeze with numbers on them for example. Not to mention editor becoming laggy.

@12pm 
Because i realized i won't be happy with the result, looked like this would result in removing the ability to turn text entities on/off in the editor.

My solution is still good i think - add a button for it in the editor.
