### ISSUE TITLE
Feature Request: toggle_cmd

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#1905]
Would be nice if we could use toggle with commands instead of just values.

Existing toggle command example usage:
`bind pagedown toggle cl_show_quads 0 1`

New toggle_cmd command example usage:
`bind j toggle_cmd "bind k kill" "unbind k"`

The existing toggle analyzes the current value of the variable it's toggling (0 or 1 in above example) and sets it to the _other_ value. The new toggle_cmd should just "remember" which cmd was executed last, and execute the _other_ cmd.

Hmmm... maybe it should be a list of cmds instead of just 2? Executed in order then wrapping around to start?

**Comment by d3fault** [comment]
In memory:
`std::unordered_map<std::string /*sha1SumOfSanitizedCommands*/, int /*indexOfCommandLastExecuted*/> toggleCmdStates;`

**Comment by H-M-H** [comment]
You can already achieve the described behavior using `exec`.
Example:
```
> cat 1.cfg
bind x "echo 1"
bind j "exec 2.cfg"
> cat 2.cfg
bind x "echo 2"
bind j "exec 1.cfg"
```
Additionally this can easily be extended to a wrapping list.
