### ISSUE TITLE
DDNet 0.7 lite

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1906]
- @fokkonaut is going to work on giving us a 0.7 DDNet server, he already ported DDNet server to 0.7 for his own mod so only needs to cut away a few features.
- I will make a map converter to 0.7 today so that we will have all maps available immediately.
- Remaining task is to take current DDNet client and apply only the network and skin related changes to have a 0.7 compatible client with the same look as current DDNet client.

We would then run a 0.7 compatible DDNet server in parallel to the current 0.6 ones and see how the acceptance is and decide on further steps.

Any volunteers?
Or thoughts about these plans?

**Comment by ChillerDragon** [comment]
What about using a 0.7 style client?

**Comment by Learath2** [comment]
No

**Comment by def-** [comment]
https://maps.ddnet.tw/compilations/maps7.zip

**Comment by def-** [comment]
https://github.com/ddnet/ddnet7 also exists now, thanks to @fokkonaut . What's missing is SQL. I will try to find time to add the SQL code, but if anyone wants to do it earlier, say so. Should be pretty easy to port and we'd be willing to assist.

**Comment by axblk** [comment]
One thing about maps: when they need to be updated anyway... what about properly extending them instead of just adding the custom layers via new flags?
Maybe the extra mapitems (https://github.com/ddnet/ddnet/pull/1329) can be used for this.

**Comment by def-** [comment]
https://maps.ddnet.tw/compilations/maps7.zip updated, shouldn't crash anymore.

@ChillerDragon is working on porting SQL

**Comment by ChillerDragon** [comment]
> https://maps.ddnet.tw/compilations/maps7.zip updated, shouldn't crash anymore.
> 
> @ChillerDragon is working on porting SQL

Thanks for fixing the tool <3

About sql.. I actually tried something but I guess it would take me way too long to implement that in a nice way. So @all feel free to look at it.

**Comment by def-** [comment]
Now we have Sixup by Learath2 which is even better.
