### ISSUE TITLE
Client deeply hangs on switch from browser while video playing on Windows

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#1907]
1. Play video (tried from twitch, youtube.music, Chrome, Edge, Internet Explorer)
2. Alt+Tab to game
If you are (un)lucky enough you will see...I can't even describe it. Something like this -
![123](https://user-images.githubusercontent.com/17499770/64914650-60a78600-d75e-11e9-89e1-595ececd393a.jpg)
Sometimes I cant reproduce it. Didn't figured out what it depends on
3. You are still able to switch from game to another app
In task manager CPU usage by the game will become zero at this point (usually it's about 50%)
4. Switching back to the game will lead to repeatedly blinking. And sometimes pc reboot is your only option in this situation

My workaround is creating an empty tab in my chrome, so if the active tab has no video elements it won't hang

**Comment by BannZay** [comment]
Intel HD Graphics 630 is my video card

**Comment by Learath2** [comment]
I highly doubt this is a mistake on our part but @Jupeyy might know something I don't.

**Comment by BannZay** [comment]
cannot reproduce it in Fullscreen or with VSync

My full list of graphics settings:
gfx_noclip 0
gfx_screen 0
gfx_screen_width 1920
gfx_screen_height 1080
gfx_borderless 1
gfx_fullscreen 0
gfx_alphabits 0
gfx_color_depth 24
gfx_vsync 0
gfx_resizable 1
gfx_display_all_modes 0
gfx_texture_compression 0
gfx_high_detail 1
gfx_texture_quality 1
gfx_fsaa_samples 0
gfx_refresh_rate 0
gfx_finish 0
gfx_backgroundrender 0
gfx_text_overlay 10
gfx_asyncrender_old 1
gfx_tune_overlay 20
gfx_quad_as_triangle 1
gfx_opengl3 1
gfx_enable_texture_unit_optimization 1
gfx_use_preinitialized_buffer 1

I dont mind if you just close it. But anytime I am ready to provide further information about that

**Comment by BannZay** [comment]
Sometimes I see graphics artifacts before deep hang. But once, game not crashed so I has time to make screenshot, here is it:

![screenshot_2020-02-06_05-36-06](https://user-images.githubusercontent.com/17499770/73914494-13b97d00-48c2-11ea-9859-6d4177579aaa.png)

I use modified game tiles and not standard zoom. I`ve ran gpu tests from manufacturer - no problems found. Problem persist with teeworlds only. No idea why =(

**Comment by Jupeyy** [comment]
Downloaded last driver from:
https://downloadcenter.intel.com/product/98909/Intel-HD-Graphics-630
?

Else try disabling OpenGL3.3.
If even that doesn't work, its a probably a setting in Windows, SDL or your PSU can't handle the sudden increase in power consumption.. could be anything really XD
Best is you try to make sure its no driver or other software

**Comment by BannZay** [comment]
I update the driver using the Lenovo auto-update tool because cannot install intel generic driver, it 
 complaining "Computer Manufacturer Graphics Driver Detected"

Tried disabling OpenGL3.3. It does not help =(

I tried to run the game on dedicated Nvidia GPU but everything feels pretty much different. Facing input delay or something.

I have tried 2 different versions of the driver, and several browsers, the problem stays.

**Comment by Jupeyy** [comment]
no idea if that works, but apearently you can still install intels latest driver
https://forums.lenovo.com/t5/Lenovo-Yoga-Series-Notebooks/Update-to-Latest-Intel-Graphics-Driver/td-p/4457633

**Comment by BannZay** [comment]
@Jupeyy, it worked for me. Many thanks!
Lenovo driver was relatively old - the release of 2017. I hope it solved my problem.

**Comment by BannZay** [comment]
Unfortunately, artifacts still happen
![screenshot_2020-02-08_16-41-15](https://user-images.githubusercontent.com/17499770/74087141-37cbb880-4a92-11ea-88ca-d561d223ab11.png)
![screenshot_2020-02-08_16-41-44](https://user-images.githubusercontent.com/17499770/74087146-3b5f3f80-4a92-11ea-9fcd-0cc9d1712336.png)

**Comment by Jupeyy** [comment]
Even without OGL 3.3?

**Comment by BannZay** [comment]
it looks okay without OpenGL 3.3. At least for now. Not sure what exactly solved the problem if it is solved. 
Hope it is. I will post my experience anyway

**Comment by BannZay** [comment]
I installed another video driver version. No crashes since then
