### ISSUE TITLE
Chat ping in demos

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1919]
I personally find it annoying when my teeworlds icon gets highlighted while I am watching demos.
![image](https://user-images.githubusercontent.com/20344300/65496077-1ccc2380-deb8-11e9-8b02-1d327e6dbe8f.png)

**Comment by fokkonaut** [comment]
Why would you minimize your client while watching a demo?

**Comment by def-** [comment]
cl_shownotifications 0

**Comment by def-** [comment]
How could the client determine whether you are currently editing a video or not?

**Comment by ChillerDragon** [comment]
@def- I think generally while replaying demos it is useless to be annoyed on desktop. This is a feature to let you know you should tab back into the game. I see no need for it during demo replay no matter why you watch demos. So it is not related to editing just to demo replay.
