### ISSUE TITLE
screen tearing even with vsync enabled

### ISSUE THREAD

**Issue by Patiga** [ddnet/ddnet#1921]
To have a smooth image I need to turn off vsync and up the cl_refresh_rate value. I have a 144hz monitor, and I keep the cl_refresh_rate at about 500 to fix this. Without any fps-limit I get at least 3000 fps.
This happens with opengl enabled as well as disabled, however on 0.7 it seems like 144 fps is sufficient. although vsync makes the screen tear again.

I don't know which role gfx_refresh_rate has, but it seems like a low number (144 as well) also enables the screen tearing.

**Comment by def-** [comment]
Does opengl3 on/off have any effect? This might be a driver issue. In some drivers you can set the number of frames to buffer, if you increase it the tearing should be substituted with higher latency.

**Comment by Patiga** [comment]
opengl3 on/off doesn't seem to affect the screen tearing.

**Comment by Jupeyy** [comment]
This is a bug in your setup

VSync is garantueed to be tearless, can try vulkan

https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPresentModeKHR.html

spec clearly says :
"VK_PRESENT_MODE_FIFO_KHR specifies that the presentation engine waits for the next vertical blanking period to update the current image. Tearing cannot be observed. "
