### ISSUE TITLE
version `CURL_OPENSSL_3' not found

### ISSUE THREAD

**Issue by Jubjub** [ddnet/ddnet#1943]
Hey guys,
I get an error after updating:
```
./DDNet: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./DDNet)
```

I imagine because of 3de73cf96aec19d6bfbfdba83e4b74a59dcc12ba

I do have `libcurl4` installed, but my distro doesn't package `libcurl3`.
Could it maybe be made so that it works with 3 and greater? Or maybe bundle it again?

Thanks, I must have that delicious hammer buffering.

**Comment by Learath2** [comment]
This seems to be an issue with debian packaging curl in a distro specific way.
https://github.com/curl/curl/issues/2433

@def- what do you want to do about this? Keep bundling or figure out a way to link with a libcurl that doesn't have this `CURL_OPENSSL_3` "symbol"?

**Comment by Jubjub** [comment]
Classic Debian move, I'm on unstable too so no way to get an older version of the lib (i think).

**Comment by def-** [comment]
Wait, actually I think the hammer buffering is server side, so you don't need to update client. I wrote that wrong in the changelog probably.

For now I'd revert, quickly release a new version and then you guys can figure something out to fix it properly? :D

**Comment by Learath2** [comment]
@def- works for me

**Comment by Jubjub** [comment]
Thanks everyone, top notch realtime issue solving! :100:
