### ISSUE TITLE
draw speed_arrow in the editor and allow rotating speedups with "r"?

### ISSUE THREAD

**Issue by VxMiMxV** [ddnet/ddnet#1950]
R = 45° rotation clockwise | Shift+R = 45° rotation anticlockwise
![boober](https://user-images.githubusercontent.com/47721445/67625465-e67b1e80-f83e-11e9-9002-f85117f65179.gif)
This should have been done a long time ago, and i'm surprised it wasn't,
which makes me think it's either impossible or really hard to implement.

I couldn't find any issue talking about this,
just crush my dreams and tell me it's not possible.

Edit:
And by "draw speed_arrow in the editor" i meant to draw it while speedup tile is in the selection tool.

**Comment by Learath2** [comment]
It should be possible
