### ISSUE TITLE
Suggestion: cl_dummy_hammer should hold mouse1 when frozen?

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#1963]
Now that we have f19220f which allows us to hammer directly on unfreeze, starting a fly when you're stacked on someone (not a dummy, a real player) in freeze has become very easy. The bottom player just holds mouse1 and the first 2 hammers (1 to get out of freeze, and the next to get unfrozen up in the air) are guaranteed to hit the driver back.

Maybe we should change the behavior of cl_dummy_hammer so it behaves the same way? Any time the dummy is frozen (not just in freeze tiles) they should be basically just holding mouse1? Then after they get unfrozen the normal timed hammering starts.

This might cause problems such as pushing the driver too high (into ceiling freeze tiles for example). For that reason maybe it should be configurable? Or maybe it should only work when the dummy is in freeze *tiles*?

**Comment by d3fault** [comment]
cl_dummy_hammer_hold 0 //off - current behavior
cl_dummy_hammer_hold 1 //only hold hammer if dummy in freeze tiles (probably a good/safe default)
cl_dummy_hammer_hold 2 //hold hammer if dummy frozen (possibly a good default, but see 3rd paragraph of op)

the value corresponds to the amount of times the dummy will be guaranteed to hammer u *back* when starting a stacked fly with dummy in freeze tile

**Comment by heinrich5991** [comment]
I was thinking about just making it always hold the hammer.

**Comment by heinrich5991** [comment]
(When dummy hammer is on, rehammering at the given interval.)

**Comment by d3fault** [comment]
wat

**Comment by BannZay** [comment]
should be fixed by bcf9e003d70862137d5127842a83ebdaf58ac0d6

**Comment by d3fault** [comment]
> should be fixed by [bcf9e00](https://github.com/ddnet/ddnet/commit/bcf9e003d70862137d5127842a83ebdaf58ac0d6)

Works, thanks :)
