### ISSUE TITLE
Don't allow votekicks for first ~30 seconds after map change

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#1966]
Players are considered afk immediately after map change as of 547f751 (which admittedly was my idea). SP|Someone leverages this to votekick people immediately after map change since everybody is afk (and their votes aren't counted).

**Comment by louisjgeer** [comment]
maybe first 10s, 10 seconds is a long time for everyone to connect.

**Comment by d3fault** [comment]
An alternative, and perhaps superior, solution would be to require 5 *non-afk* players on the server before you can vote, rather than just 5 players on the server (regardless of afk state).

**Comment by heinrich5991** [comment]
Or don't mark every player AFK after a map change, but rather only those players that were AFK *before* the map change. I.e. retain the AFK state.

**Comment by Learath2** [comment]
> Or don't mark every player AFK after a map change, but rather only those players that were AFK _before_ the map change. I.e. retain the AFK state.

This was the initial idea I had. However we have no setup in place to allow that. It'd require some restructuring.

**Comment by heinrich5991** [comment]
You could either track it at the engine level or do something like this: https://github.com/teeworlds/teeworlds/pull/2066.

**Comment by Learath2** [comment]
That teeworlds commit is exactly what I was looking for but was too lazy to
implement :) I can maybe fix this tonight or maybe tomorrow.

**Comment by BannZay** [comment]
I dont like seeing me in a afk status since I just connected and server didnt give me a chance to "not be afk"

Can we delay this of setting this status by these 10 seconds?

**Comment by heinrich5991** [comment]
@BannZay No. The fix is detailed in https://github.com/ddnet/ddnet/issues/1966#issuecomment-553116219. With the fix, only players that were AFK before a map change will get marked as AFK when they join.

**Comment by BannZay** [comment]
> don't mark every player AFK after a map change

@heinrich5991  Its not clear to me what about the case if player was not on the server before map change but just connected? Hope you wanted to say "Dont mark ever players as AFK but only when they were AFK before map change or stay inactive long enough"

**Comment by C0D3D3V** [comment]
@d3fault  is this still relevant?

**Comment by heinrich5991** [comment]
Yes. Players should also not be considered AFK after changing map, if they weren't considered to be AFK before.
