### ISSUE TITLE
Add infclass to the DDNet tab

### ISSUE THREAD

**Issue by bretonium** [ddnet/ddnet#1967]
Can i please get my infclass server added to the "DDNet" tab in the client? Server list for 0.6 is half-dead. I run the server for a year already and plan to continue doing so.

The server is 95.172.92.194:8306

**Comment by Jubjub** [comment]
This would be great, it's one of the 4 popular mods but a lot of people can't access it when the master servers are down.

**Comment by def-** [comment]
Done.
