### ISSUE TITLE
/save internals improvements

### ISSUE THREAD

**Issue by 12pm** [ddnet/ddnet#1969]
1) store game uuid in its own column since it's not relevant to the tee's state (the savegame buffer is also too small to append the entire uuid..)
2) log game uuid on load to be able to trace back

**Comment by Learath2** [comment]
Problem is that there can essentially be infinite saves and loads. Storing the chain can take some db space.

**Comment by heinrich5991** [comment]
We do (2) nowadays, and (1) isn't needed anymore I think. Close this issue?
