### ISSUE TITLE
Ctrl+shift+S saves current map

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1972]
Ctrl+shift+S acts different than going to 'file -> save as'.
Ctrl+shift+S instantly saves current map to the current file without user confirmation and then opens the map browser to select a new place to save it to.

I guess it is expected that it does not overwrite the current map and behaves like 'file -> save as'.

**Comment by BannZay** [comment]
Havent check yey, but, most likely this is because ctrl+s also triggers,

The same problem with ctrl+shift+e in case when your emote bar bound to shift.
