### ISSUE TITLE
Texture Change Option

### ISSUE THREAD

**Issue by Deathmanlol** [ddnet/ddnet#1975]
Hi, 

it would be cool if DDNet would have a option to change the Texure [Game.png, Particles.png, Gui_Cursor.png and Emoticons.png] in game, I like this function in other clients, but DDNet is the best client in my opinion, so i am kinda missing that function,
 
I like all the customize options in DDNet so its kinda sad this is not included (I know you can change the texture with renaming, but in game is better).

Would be nice.
 
Thanks in advance

**Comment by Ekidoxx** [comment]
https://github.com/ddnet/ddnet/issues/1211

**Comment by heinrich5991** [comment]
Indeed, duplicate.

**Comment by Deathmanlol** [comment]
sorry
