### ISSUE TITLE
Remove all chat messages that we cover with indicators in the HUD

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#198]
It would be nice to have an indication for whether you have jetpack (etc) instead of chat messages.

**Comment by east** [comment]
I like the idea. The question would be how to inform the client about such a status. Would be nice to have some status register which informs clients about jetpack, number of jumps, freeze, endless hook or even in/out of race. But we still have the netmsg type limitation in the protocol, so extending the protocol is kinda tricky.

**Comment by o-be-one** [comment]
why not playing with scoreboard ?

**Comment by H-M-H** [comment]
For jetpack, freeze and deepfreeze the weaponenumeration could be extended and replace WEAPON_NINJA (or WEAPON_GUN for jetpack) with the new enum. I already tested this with freeze some time ago and it worked quite good, though you need to check the clientversion and only send the new enums if it is high enough.

**Comment by feca1997** [comment]
You could detect special chat messages sent by the server and display them however you want.

**Comment by CytraL** [comment]
something like this https://github.com/CytraL/HClient/blob/master/src/game/client/components/chat.cpp#L733 ??  I see it ugly..

**Comment by def-** [comment]
If it works reliably, maybe. Or maybe HMH's idea would be better, then we would not need to send those texts to the players with new DDNet client version.

**Comment by H-M-H** [comment]
Do you think this is a good solution: https://github.com/H-M-H/ddnet/commit/10ae9242cd31449345882405ed4dab3752628e34
Makes #258 fixable btw.

**Comment by def-** [comment]
we also need to decide on what to show exactly:
- Freeze timer
- Solo
- Available weapons (including ninja, jetpack)?
- Can hook, collide
- Number of jumps

**Comment by Ekidoxx** [comment]
How about just using the signs from entities? Like
- Solo on: white tee from solo entity
- Solo off: black tee from solo entity
- Number of jumps: the jump particle from walljump/infinite jump with number indicator
- Freeze time: Start/End "stopwatch" with number indicator or ∞ while in deep

**Comment by C0D3D3V** [comment]
Do we still want to send these messages to old clients and vanilla? Or can we remove them completely

**Comment by heinrich5991** [comment]
> Do we still want to send these messages to old clients and vanilla? Or can we remove them completely

We still want to send these to old clients and vanilla. A version check around each of them is probably the way to go.
