### ISSUE TITLE
Editor: support entities bind

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1990]
Listen for the entities bind and if cl_overlay_entities gets updated or switched between lower 50 and above 50 then toggle the visibility of game/tune/speed/switch and front layer.

This in combination with the tab key can be used to quickly test the design in the editor.

**Comment by kamillentee** [comment]
@ChillerDragon Will you do a PR?

**Comment by ChillerDragon** [comment]
@kamillentee I already did https://github.com/ddnet/ddnet/pull/1992

**Comment by heinrich5991** [comment]
I don't think applying the in-game entities bind to the editor is a good idea.
