### ISSUE TITLE
Editor: option to leave editor on velocity change

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1993]
When frozen far in racing and waiting for others using the editor is a nice activity. Until you get flamed for not reacting :/

So a option to automatically close the editor when the tee changes velocity would be nice. Probably less false positives (speedups,draggers) than change  of velocity would be getting hit by a weapon or hook. Also a possibility is to close editor on unfreeze.

**Comment by BannZay** [comment]
I would go with more general solution as you can minize game, switch to dummy, open editor, anything else. One solution for all problems I only see in sound notification

**Comment by VoxelDoesCode** [comment]
Or maybe, you know how there is a notification text for when you're mentioned? What if that can also apply for velocity changes too?
