### ISSUE TITLE
SDL 2.0.9 and higher run extremly bad on Windows

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#1997]
So while i was on Windows now, I noticed, that SDL 2.0.9 and higher run insanly bad, and i really mean around 100% worse than 2.0.8.

I used the latest client and run with 2.0.8, 2.0.9 and 2.0.10 from here(64 bit):
https://libsdl.org/release/

I would really suggest to downgrade to 2.0.8 if we don't need features from higher versions.
Btw you can also see the difference in wine

**Comment by Learath2** [comment]
Did you try giving this a quick profile? It's a pretty horrible experience to profile anything on windows, but it'd be useful data.

**Comment by Jupeyy** [comment]
@Learath2 
![image](https://user-images.githubusercontent.com/6654924/70801940-7570d580-1db0-11ea-9e40-77efb6e57d75.png)
left is newer SDL right older, seems like SDL_WaitEventTimeout_REAL is the killer :D
but i have no plan whats using it nor whats its meant for

**Comment by Learath2** [comment]
Any half decent profiler should have a call tree view. Maybe there is one in VS as well that could help you see what leads to the `SDL_WaitEventTimeout_REAL` call.

**Comment by Jupeyy** [comment]
well out caller is CInput::Update(over SDL_PollEvent), but I can't digg deeper in that function(from SDL) in the profiler(not even in debug mode), and i also don't understand what these SDL functions are for anyway

**Comment by Learath2** [comment]
Without a debug build of SDL it'd be hard to dig into this anyway. Was 2.0.10 the same? I guess it might be the best idea to downgrade to 2.0.8

**Comment by Jupeyy** [comment]
yeah 2.0.10 the same :D, i ran a debug build of sdl, but SDL uses some dynamic addresses or something like that, atleast the profiler of VS couldn't find the functions, but won't matter anyway probably, except someone knows SDL code a bit :D, my bet is, they added some controller features or smth like that, that block longer than in older version xd

**Comment by Jupeyy** [comment]
we could ofc async that poll too, or maybe SDL has other functions, that don't block

**Comment by def-** [comment]
Nice catch, I'm getting 800 instead of 900 fps in Wine with 2.0.10 compared to 2.0.8 (at 1280x720 resolution). Setting
```
		SDL_EventState(SDL_JOYAXISMOTION, SDL_IGNORE);
		SDL_EventState(SDL_SENSORUPDATE, SDL_IGNORE);
```
doesn't have any effect.

**Comment by def-** [comment]
I have opened a bug upstream with my findings: https://bugzilla.libsdl.org/show_bug.cgi?id=4897

**Comment by def-** [comment]
@Jupeyy Can you try building SDL2 with Visual Studio to debug deeper as described in the SDL bug?

**Comment by Jupeyy** [comment]
with sdl 2.0.8
![screenshot_2020-02-12_12-47-20](https://user-images.githubusercontent.com/6654924/74332440-01de4b00-4d96-11ea-972e-54e97f1db249.png)

with sdl 2.0.10(same fps as with the tmp build in the mailing list!)
![screenshot_2020-02-12_12-48-20](https://user-images.githubusercontent.com/6654924/74332442-030f7800-4d96-11ea-80c6-3a950dbb69d4.png)

both compiled with VS 2017 on Windows 10 in Release mode 64bit

now static linked sdl to debug: left always old sdl, right new sdl

![image](https://user-images.githubusercontent.com/6654924/74334570-731ffd00-4d9a-11ea-85ba-49d7968d45d5.png)
![image](https://user-images.githubusercontent.com/6654924/74334607-86cb6380-4d9a-11ea-8e96-ed46b7f17d38.png)
![image](https://user-images.githubusercontent.com/6654924/74334625-8fbc3500-4d9a-11ea-8bc1-7b1a37c2511d.png)
![image](https://user-images.githubusercontent.com/6654924/74334641-98147000-4d9a-11ea-8e25-7add1e864df3.png)
![image](https://user-images.githubusercontent.com/6654924/74334660-a19dd800-4d9a-11ea-8daf-aaaef967b717.png)


hope this helps

**Comment by Jupeyy** [comment]
maybe hardware info helps:
mainboard:
Gigabyte X570 Aorus Elite AMD X570 So.AM4 Dual Channel DDR4 ATX Retail
cpu:
AMD Ryzen 7 3800X 8x 3.90GHz
GPU:
AMD Vega 64

Mouse: 
Logitech g900 at 1000hertz
keyboard:
logitech g810

no other plugged USB devices.
