### ISSUE TITLE
Travis Mac build failing since my SDL2 downgrade

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2003]
Not sure why, looks like ddnet-libs is missing: https://travis-ci.org/ddnet/ddnet/jobs/626232895

**Comment by Learath2** [comment]
I don't think it has anything to do with ddnet-libs given we don't used bundled libs on macOS and opus and opusfile also seem to be missing so your SDL2 change being it is unlikely.

However, I don't understand how this build ever worked, we don't seem to install any of the dependencies, maybe they just changed the mac image with a slimmer one.

**Comment by Learath2** [comment]
Since we don't use travis anymore and the macOS build seems to work in Github Actions, I'm closing this
