### ISSUE TITLE
latest update reset autoexec_server.cfg

### ISSUE THREAD

**Issue by VxMiMxV** [ddnet/ddnet#2010]
Or i might be crazy.

**Comment by def-** [comment]
Yes. Maybe we should add a note since people sometimes don't expect this. If you want your own autoexec_server.cfg to stay you have to put it in the config_directory

**Comment by VxMiMxV** [comment]
Put
>If you do not want updates to overwrite your settings, create a
file called myServerconfig.cfg....

At the top instead of bottom and make it all caps.
