### ISSUE TITLE
Bullet tiles' explosions only affect one player

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#2014]
As reported by corneum on discord:

> why do the explosions from mapped bullets only affect one player at the time?

**Comment by def-** [comment]
No idea if intended, but physics changes are generally too risky.

**Comment by fokkonaut** [comment]
This cant be intended. I cant think of any situation where this should be intended or where this is used as a mechanic.

**Comment by 12pm** [comment]
very possible that this behavior is used in some map

**Comment by Ekidoxx** [comment]
The _explosive bullet_ entities works correctly for everyone, if server is set to solo mode btw - you can see that i.e. on map [Bullet Master](https://ddnet.tw/ranks/solo/#map-Bullet_Master) by [fikmesån](https://ddnet.tw/mappers/fikmes-229-n/)

**Comment by def-** [comment]
On Space & Time I use this in the last part to make it easier. One player stands close to the bullets, so another can do the part without being affected. So I vote for keeping the behaviour.

**Comment by Ekidoxx** [comment]
Also it seems that in case of players in same team, the _explosive bullets_ work only for the player that spawned as last one (out of what I could test with dummy only)
