### ISSUE TITLE
Change fonts for Chinese support

### ISSUE THREAD

**Issue by ElXreno** [ddnet/ddnet#2019]
Hi! Can I suggest you to change fonts `DejaVuSansCJKName` and `DejavuWenQuanYiMicroHei` to something like Noto? Noto has better support of all symbols and languages in the world and also have SIL Open Font License 1.1.

**Comment by def-** [comment]
Noto looks large. I see > 100 MB for CJK.

**Comment by tim77** [comment]
> Noto looks large. I see > 100 MB for CJK.

Noto available in every Linux distribution now, preinstalled and used by default in KDE for example and this CJK family in GNOME.

**Comment by def-** [comment]
But we would probably still have to bundle it for Windows and Mac at least. Actually the files are more like 16 MB, but I think each noto file is only for either Chinese, Japanese or Korean. Any suggestion if there is a combined one we can use?

**Comment by def-** [comment]
Also, I don't think we can fall back to system fonts at the moment. We just use a single font file and all symbols have to be in there. Also the bigger the font file the more you'll notice lags.

**Comment by tim77** [comment]
> Any suggestion if there is a combined one we can use?

In Fedora Noto fonts splitted in subpackages since F30 if i remember correctly. Probably we don't need all of them, but this need to investigate more.

Fedora have strictly politics about bundling fonts, but this Dejavu fonts should be fine, i hope. But Noto is nice UX improvement in general.

> Also the bigger the font file the more you'll notice lags.

How so? Font size affects performance in ddnet?

**Comment by def-** [comment]
Yeah, unfortunately the lookups for symbols happen in the same thread as rendering, so if they take a while, or a symbol isn't cached yet, it might take a while.

**Comment by tim77** [comment]
Oh, if this affects performance this is a good reason and explain a lot. I hope @ElXreno can just mention this issue and explain reason why it should been bundled and no prob here with packaging it for official repos. TY a lot for explanation @def-

**Comment by ElXreno** [comment]
Thank you a lot for explanation @def-. I think, now I can close this issue.
