### ISSUE TITLE
Cannot unbundle patched json-parser library

### ISSUE THREAD

**Issue by ElXreno** [ddnet/ddnet#2022]
I can't unbundle json-parser because it patched and requires some features which exists only in your patched library. Can you help me with it?

**Comment by def-** [comment]
What feature exists only in our library? We should be using json-parser 1.1.0 from https://github.com/udp/json-parser

**Comment by ElXreno** [comment]
@def- check this stuff. https://github.com/ddnet/ddnet/blob/master/src/engine/external/json-parser/json.h#L274

**Comment by ElXreno** [comment]
How I can build DDNet with a system library?

**Comment by ElXreno** [comment]
Thank you very much for your help! Now I think DDNet will be available in Fedora repos.

**Comment by def-** [comment]
Glad to help and thanks for working on getting DDNet into Fedora, it's appreciated a lot!
