### ISSUE TITLE
Update envelope references when appending maps

### ISSUE THREAD

**Issue by 12pm** [ddnet/ddnet#2044]
> [3:15 PM] Ravie: hey I noticed an annoying thing in the editor: when you append layers that have envelopes onto another map that has envelopes the layers will keep the same number envelope instead of changing to what new number their old envelope got assigned

**Comment by Learath2** [comment]
Can you show an example? The Append function already seems to offset the envelopes to correct for this. What kind of layers exhibit this problem?
