### ISSUE TITLE
DDnet client keeps reducing itself every 30 seconds

### ISSUE THREAD

**Issue by hugo-dlb** [ddnet/ddnet#2051]
On the new 12.8.1 version, on Windows 10, for some reason many times when I launched the client it kept reducing itself (the desktop was showing).
I downgraded to 12.7.3 and it works fine.

Not sure what's going on, but it's every 30 seconds.

**Comment by def-** [comment]
Probably because we downgraded SDL2 to fix a performance issue. You can try dropping the SDL2.dll from 12.7.3 into 12.8.1 version and that should fix it.
