### ISSUE TITLE
Reset Dummy/Main Function

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#2053]
Hello friends,

I'd like to know if its possible to add a function similar to cl_dummy_resetonswitch to the ddnet client.
Basically I'd love to reset my main or dummy via a single key press without having to switch to my dummy like the command mentioned above.

Yes, im aware it's possible to just enable hammerfly but upon disabling it, he'll just hook in the same direction he held before.

**Comment by BannZay** [comment]
I would go with `bind o "cl_dummy_resetonswitch 1; toggle cl_dummy 1 0; toggle cl_dummy 1 0; cl_dummy_resetonswitch 0"` but it does not work =(

So crazy idea, but maybe we could have a possibility to force update, so it could work like this
 `bind o "cl_dummy_resetonswitch 1; toggle cl_dummy 1 0; `**force_update;**` toggle cl_dummy 1 0; cl_dummy_resetonswitch 0"` ?
