### ISSUE TITLE
cl_show_friends

### ISSUE THREAD

**Issue by VxMiMxV** [ddnet/ddnet#2059]
I know /showothers is server-side and having it always on might lag when there are a lot of players on a server but it'd be really cool to have a client-side command that always shows players in your friendslist.

If that's not possible, maybe have 
/showfriends 1 
/showfriends 0 
so you can have a bind for example bind a "+left; say /showfriends 1"

**Comment by Learath2** [comment]
Problem with this is the server doesn't know your friends and your client doesn't get all the clients by default. You'd either need to let the server know of your friends (privacy?) or you'd need to send all characters by default (traffic).

**Comment by VxMiMxV** [comment]
Eh, how about /showteam which only shows players on your team?

**Comment by VxMiMxV** [comment]
/specteam does this:

![specteam](https://user-images.githubusercontent.com/47721445/75088441-89257e80-554d-11ea-90e7-048ba4fe668a.gif)

(Toggles the visibility of every other tee when your tee is in pause/spec as far as i can tell)

I'm asking for something like /showothers
(see tees when you/they are in solo without having to pause/spec)

But only for your team or a specific tee (/showteam or /show <playername>)

**Comment by VxMiMxV** [comment]
Now i found out you can actually use this:
bind x "toggle cl_show_others 1 0"
(sorry i confused /showothers with /showall when i said 'its a server side command)
could we get cl_show_others 2?
2 = only your team. 

And btw, /specteam is broken-you can't see tees that are in a solo.

**Comment by BannZay** [comment]
cl_show_others 2 makes a lot sense to me. I would use it by default for myself if possible
