### ISSUE TITLE
cl_showrecord personal best disappears when connecting dummy

### ISSUE THREAD

**Issue by VxMiMxV** [ddnet/ddnet#2077]
![2020-03-01_11-13-24](https://user-images.githubusercontent.com/47721445/75623778-fcfb0300-5bad-11ea-9d2f-bfe24a11a5a6.gif)

Fix possible?

**Comment by fokkonaut** [comment]
Should be a simple fix, my guess is this is not an array, so it just gets overridden by the dummie's personal best?

**Comment by def-** [comment]
Can't we just remove cl_showrecord? scoreboard shows the same info.

**Comment by VxMiMxV** [comment]
Okay nevermind :)
