### ISSUE TITLE
New freezehammer doesn't always work with deepfly bind, but should

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#2079]
The map "Next LvL" has parts that use the new freezehammer. This is fine but the new freezehammer should be more consistent when triggered via the deepfly bind. I was playing the map a few days ago and the deepfly bind **was** consistently triggering the freezehammer.... but then just playing again now the deepfly bind is never triggering freezehammer :(. I tried swapping strong/weak but it didn't fix it.

Here's a video of it in action: [desktop.zip](https://github.com/ddnet/ddnet/files/4301322/desktop.zip)

**Comment by fokkonaut** [comment]
Freezehammer? I thought that was rcon only

**Comment by Learath2** [comment]
He probably means the auto hammer when you are hammering out of freeze

**Comment by Learath2** [comment]
@d3fault what is a deepfly bind?

**Comment by fokkonaut** [comment]
@Learath2 join the map Just Deepfly, its written there. What it does is basically when you hammer, your dummy hammers too.

**Comment by d3fault** [comment]
fixed by bcf9e00
