### ISSUE TITLE
Feature request: "Visible" players in /spec

### ISSUE THREAD

**Issue by Ekidoxx** [ddnet/ddnet#2080]
As said by **Boci#1337** on discord ([link](https://discordapp.com/channels/252358080522747904/293493549758939136/685965489037639720)):
> i have a great idea
> when someone goes spec, you would see his ghost, of where he went spec
> like if he were in freeze, but like 40% opacity

6 other people, including me, seem to like the idea, so there is graphical representation of possible solution by using new skin, let's say `x_spec`

| Skin |
| :---: |
| ![x_spec](https://user-images.githubusercontent.com/14035306/76167084-5fcb3c00-6164-11ea-9ab3-8f7a24ef1295.png) |

| In-game preview compared to regular skin |
| :---: |
| ![unknown](https://user-images.githubusercontent.com/14035306/76167011-b84e0980-6163-11ea-83c3-9505def7ce47.png) |

-----

For whoever wants to test how the mentioned skin looks in-game:
[x_spec.zip](https://github.com/ddnet/ddnet/files/4303527/x_spec.zip)
###### _Note: You have to remove the `x_` part from the skin name to see it in client settings_

**Comment by VxMiMxV** [comment]
I like the idea.
I really don't like the dashed tee design though.
Just drop the tee opacity by like 40%?

Or maybe something like this instead?
![10](https://user-images.githubusercontent.com/47721445/76183405-8d49d100-61c8-11ea-9198-261620161d2f.gif)

![20](https://user-images.githubusercontent.com/47721445/76183185-dfd6bd80-61c7-11ea-846a-8445f4b877f0.gif)
[Skin](https://i.imgur.com/2n9wVsH.png/spec_x)

**Comment by Learath2** [comment]
Dropping tee opacity doesn't leave a way to distinguish spec'd tees from `/showothers` ones

**Comment by VxMiMxV** [comment]
Does it really need to?
/showothers is turned off every time you join a server by default.
Maybe could do some meme like inverting player name colors while in /spec?

Or make it black:
![Screen 5032](https://user-images.githubusercontent.com/47721445/76199308-ebd67580-61ef-11ea-9d5a-4b9754d9cee5.png)

**Comment by fokkonaut** [comment]
I like the dashed tee skin. But names should be shown aswell.
