### ISSUE TITLE
We ALL need a cl_showall 0/1 plzplz

### ISSUE THREAD

**Issue by nebnebneb** [ddnet/ddnet#2087]
Typing /showall everytime u join is megaboring, if someone could code a console command to automate it on ddnet's settings it'd be megacool
Megathx

**Comment by def-** [comment]
`bind minus "zoom-; say /showall 1"`

**Comment by fokkonaut** [comment]
I did it once, but it got rejected.
https://github.com/ddnet/ddnet/pull/1840

**Comment by trikiman** [comment]
> `bind minus "zoom-; say /showall 1"`

it is not help cus i dont press zoom button but my default zoom too big.

**Comment by def-** [comment]
Also related: https://github.com/ddnet/ddnet/issues/1641
