### ISSUE TITLE
Add 0.7 server support?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2106]
Similar to what unique-race has done, this allows 0.7 and 0.6 players to play on the same server: https://github.com/unique-clan/unique-race
Start was: https://github.com/unique-clan/unique-race/commit/5675762cf6fc321ea3a7211f55b08b103b97a8ab

Ask @timakro for more details

Any volunteers up for the task?

**Comment by fokkonaut** [comment]
I coud port timakros version I think, I also made my 0.7 server support ddnet clients.

**Comment by edg-l** [comment]
i think this is done with sixup
