### ISSUE TITLE
cl_dyncam not working

### ISSUE THREAD

**Issue by dr-death2** [ddnet/ddnet#2113]
Hi there,

i'm experiencing problems with cl_dyncam on Linux. I can activate or deactivate it on the menu. I can activate or deactivate it with keybinds. Nevertheless in the game the dynamic camera is *always* activated. It seems changing the property has absolutely no effect.

System: Linux Mint v19.3, DDNetClient v12.9.2

I also tested the DDNet-Windows-Client 12.9.2 running on the same Linux system with wine. There cl_dyncam works as expected.

Any Ideas? Anything i can test for you?

Kind Regards

**Comment by Jupeyy** [comment]
cl_dyncam 0
cl_mouse_followfactor 0

if cl_dyncam is 1
cl_dyncam_follow_factor 0

**Comment by dr-death2** [comment]
Thank you for your reply, jupeyy.

Playing around with `cl_mouse_followfactor` and `cl_dyncam_follow_factor` solved my issue. I neither know what the exact problem was nor which of these parameters solved it. But after resetting `cl_mouse_followfactor` to 400 cl_dyncam can now again be toogled via keybind or gui and works as expected.

Many thanks and best regards.
