### ISSUE TITLE
Warning "Can't set BUILD_RPATH" when antibot feature is enabled

### ISSUE THREAD

**Issue by rffontenelle** [ddnet/ddnet#2114]
When `-DANTIBOT=ON` is enabled, the following message is issued by CMake even in version 3.17:
```-- Can't set BUILD_RPATH in CMake before 3.8, pass -Wl,-rpath,'$ORIGIN' manually if you wish to emulate this. Or just install a newer version of CMake...```

**Environment:**
- Distro: Arch Linux
- Packages: [ddnet 13.0](https://aur.archlinux.org/packages/ddnet), [cmake 3.17.0](https://www.archlinux.org/packages/extra/x86_64/cmake/)

**Comment by Learath2** [comment]
@heinrich5991 ^^
