### ISSUE TITLE
macOS CI broken

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#2127]
See #2126.

CC @Learath2

**Comment by def-** [comment]
Wait, so I broke that somehow? I am pretty sure I waited for mac results for everything I submitted.

**Comment by heinrich5991** [comment]
I don't know.

Usually, system headers should not be affected by warnings. I'm also not sure what turns on `-Wnullability-completeness`, perhaps it's our `-Wextra`?

**Comment by Learath2** [comment]
https://go-review.googlesource.com/c/go/+/205457/
https://github.com/golang/go/issues/35247

I guess it could be a mismatch between the compiler and the SDK causing the compiler not to identify the system headers as system headers.

**Comment by heinrich5991** [comment]
Seems to be fixed.
