### ISSUE TITLE
Deleting old branches

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2129]
I suggest deleting these branches: DDRace, 128players, 516, 517, aio, emoji, heinrich5991-pr_ddnet_map_settings, new_db_scheme, pr_ddnet_map_settings. Any opinions?

**Comment by Ryozuki** [comment]
I would go for it

**Comment by def-** [comment]
Deleted DDRace new_db_scheme 516 517. For the rest let's see what the others think.

**Comment by heinrich5991** [comment]
Go ahead.
