### ISSUE TITLE
Add ffmpeg lib and header file for building client with record feature in windows

### ISSUE THREAD

**Issue by QingGo** [ddnet/ddnet#2144]
I want to add ffmpeg lib and header file to ddnet/ddnet-libs repo, and renew the ffmpeg version in cmake/FindFFMPEG.cmake, for buildind a DDNet Client with video feature in Windows OS more convenience.
I will submit two PR for that and refer to this issue later.

**Comment by QingGo** [comment]
Add ffmpeg lib and header file: https://github.com/ddnet/ddnet-libs/pull/6

**Comment by QingGo** [comment]
Renew the ffmpeg lib version in cmake/FindFFMPEG.cmake for windows OS building: https://github.com/ddnet/ddnet/pull/2145

**Comment by def-** [comment]
This will quite increase the regular client size, right? How did you build ffmpeg or did you get it from somewhere else?

**Comment by QingGo** [comment]
The zip file of ddnet build with video record feature will be 26.2MB here which is not remarkable increase as I think. I get the ffmpeg header and lib file from it's offical website, here is the link: https://www.ffmpeg.org/download.html#build-windows and https://ffmpeg.zeranoe.com/builds/

**Comment by QingGo** [comment]
I build the newest code using mingw64 toolchain in WSL2, and this time the zip file have the size about 41MB(last time I build these code with MS, just replace the excuable "DDNet.exe", add the relate dll file, and zip the folder, finally get a 26.2MB zip file.)
The build command is below:
``` bash
cmake -DCMAKE_BUILD_TYPE=Release -DPREFER_BUNDLED_LIBS=ON -DVIDEORECORDER=ON -DCMAKE_TOOLCHAIN_FILE=../ddnet-master/cmake/toolchains/mingw64.toolchain ../ddnet-master
make package_default
````
I upload the target zip file to github. If anyone using a Window OS  want to test whether it work normally can download this:
https://github.com/QingGo/ddnet_win_build_vedio_record/raw/master/DDNet-13.0.2-win64-VIDEORECORDER.zip

**Comment by def-** [comment]
Both PRs merged, can be closed I guess. Thanks!

**Comment by QingGo** [comment]
Thank you!
