### ISSUE TITLE
Missing Servers 

### ISSUE THREAD

**Issue by iManKho** [ddnet/ddnet#2147]
Hi, i am a player of TeeWorlds or DDnet since 6 years ago (more or less), from Chile (LATAM).

My problem its what, there's servers that i can't found (specificly "DDnet OpenFNG Chile" and "DDnet Infection Chile servers or gerenally), and i don't know why. I Use a bot ever?, yes, but it was four years ago, when DDnet doesn't exist (i think), and i played with other names, but i never abuse of the bots, only to test them, and that's all, i never recieved a message of "Permanent Ban" before and, i write again, was four years ago.

Now i not use any bot, only DDnet and that's all, i like so much the iCTF, DM, Infection, Zcatch and specially OpenFNG mods or maps, but since 6 mounths approx. that i can't found it in the browser, only the FNG servers that are no Officials of DDnet and there are from other countrys, i never did a thing that was cause of a ban (like block in not-block maps, be a trash-talker, hacks or use others IP, etc) so i simply don't know why i can't found these servers of "OpenFNG" or "Infection" (if Infection still active in Chile), i tried uninstalling the game or changing my name, but it isn't work.

I expect an answer soon, sorry for my bad english ( i barely speak it or write it), and that's all, i cant give any more details either 'cause i don't remember if i did something wrong before (which I absolutely doubt). 

Thanks four your expected help :)!.

**Comment by def-** [comment]
For FNG, did you search for "DDNet Chile - FNG2"? Try connecting directly to 131.221.32.165:8220

Infection on DDNet Chile doesn't exist.

**Comment by iManKho** [comment]
Hi, well, i know now why, some Moderator banned me for "BOT", so with my WIFI IP i can't join to the server, but with my Phone Internet i can, so i'm gonna enter and talk with some moderator so i can see if they can unban me :)
