### ISSUE TITLE
Server info has become less reliable

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2149]
At least it feels like that to me. When I refresh DDNet tab in client sometimes the server I'm on doesn't even appear in the list. On ddnet.tw/status I'M also often seeing much lower numbers. Haven't investigated further, maybe it's just some rate limiting we do,

**Comment by Chairn** [comment]
Sometimes, when a server has a lot of players (over 50 i'd say), it won't even appear in server list, or it would appear with only 2 players, and no server name (in DDNet tab).

So i confirm this weird behavior.

**Comment by Learath2** [comment]
> Sometimes, when a server has a lot of players (over 50 i'd say), it won't even appear in server list, or it would appear with only 2 players, and no server name (in DDNet tab).
> 
> So i confirm this weird behavior.

I think this would happen if the first packet of the serverinfo is lost, currently there is no mechanic for it but maybe we should be requesting again if this happens? @heinrich5991 ?

**Comment by Chairn** [comment]
Here is a screenshot i just take with the Back in Time server:
![screenshot_2020-05-03_17-55-48](https://user-images.githubusercontent.com/10178629/80918899-8625e600-8d67-11ea-8676-20ab95e1cd0f.png)
