### ISSUE TITLE
Can't whisper to players with quotes at beginning and end of name (eg. "nameless")

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#2151]
SP | Someone (aka Zombietoad) found this bug.
Given a player with the name "nameless" (including quotes!):
`/w "nameless" test`
doesn't work. it gives some error about player not found, I forget

**Comment by fokkonaut** [comment]
This is known long already

**Comment by heinrich5991** [comment]
But it's a bug. Thanks for the bug report. :)

**Comment by def-** [comment]
Also, I didn't know it or I would long've fixed it.
