### ISSUE TITLE
add possibility to lock chat?

### ISSUE THREAD

**Issue by VxMiMxV** [ddnet/ddnet#2153]
![Screen 5258](https://user-images.githubusercontent.com/47721445/80523013-bb0ff280-898d-11ea-8594-f92a86cea2c6.png)

Would be cool to be able to lock it with for example F1 like anything else.

**Comment by Ekidoxx** [comment]
You could also bind it to numlock iirc

**Comment by VxMiMxV** [comment]
I meant the possibility to have it locked like for example space (hold space down, press F1, let go of space, press F1 again = space is locked)

**Comment by def-** [comment]
> You could also bind it to numlock iirc
This probably stopped working with the SDL2 switch or something like that.

For now I implemented this as `cl_showchat 2`, but could also imagine a way to generically hold any `+` command.

**Comment by VxMiMxV** [comment]
`bind u +toggle cl_showchat 2 1` 

^ bind works like the standard + you're able to lock it with f1, thanks.
