### ISSUE TITLE
Tee keeps crying when holding fire while frozen

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet#2162]
Old behavior was crying once when firing and no more sound when you hold fire.
New behavior is crying while you hold fire and being frozen, which is quite annoying.
I believe it is caused by this commit:
https://github.com/ddnet/ddnet/pull/2086/commits/d22a1a8f060b98e40d315faca2faaf282abab487

**Comment by def-** [comment]
@fokkonaut ^

**Comment by fokkonaut** [comment]
I dont understand why that should happen
