### ISSUE TITLE
show bind if you just type bind <key>

### ISSUE THREAD

**Issue by trafilaw** [ddnet/ddnet#2165]
Maybe it is possible to show binds when you just type bind <key> and then comes the bind which is on the key right now
Like I bind on Q Kill and then I type bind q thats shows something like `bind q kill` or something else xd

**Comment by fokkonaut** [comment]
dump_binds q

**Comment by trafilaw** [comment]
Well, thats for all binds ^^

**Comment by fokkonaut** [comment]
Read again, `dump_binds <key>`

**Comment by trafilaw** [comment]
Ah okay thanks xD

**Comment by Ekidoxx** [comment]
honestly, would never guess ._.
