### ISSUE TITLE
New automatic tip message on DDNet Servers

### ISSUE THREAD

**Issue by Zoozti** [ddnet/ddnet#2174]
Make a new server message that appears from time to time which announces not to kickvote tees that are "blocking" by seeming to be afk but to start spectatorvotes instead.
I see it very often that players get kicked for "afk block" or just "afk" that are clearly a dummy and the main tee is playing far in the map (or the opposite, dummy is far, main is in a hammerhitpart for example) and often the vote passes.
When i talk to the votestarters that its better to vote for spectator instead of kickvote they mostly agree but didnt think at it in the moment.
Little reminder would be good here.

Maybe like: "If a player seems to be afk and blocks a part by it do not start a kickvote but vote him to spectator instead."

**Comment by def-** [comment]
Done.
