### ISSUE TITLE
Collision with switch tile with number 0 leads to client crash 

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#2182]
Steps to reproduce:
1. Create map with switch (off/on) tile and host on server. I created small one here - [bugged.map](https://github.com/ddnet/ddnet/files/4639027/bugged.zip)
2. Connect to server
3. Touch this tile by your tee

100% reproducible for me

Some debug info below:

Exception thrown: write access violation.
CEntity::Collision(...)->**m_pSwitchers** was 0x111011101110112. occurred
occured at void CCharacter::HandleTiles(int Index)
on line 787 "Collision()->m_pSwitchers[Collision()->GetSwitchNumber(MapIndex)].m_Status[Team()] = true;"

**Comment by def-** [comment]
Thanks, fixed
