### ISSUE TITLE
Publish DDNet to Flathub

### ISSUE THREAD

**Issue by ElXreno** [ddnet/ddnet#2187]
Hi! I have a suggestion. How about publishing DDNet to flathub.org?
If we publish DDNet on flathub, DDNet can be installed anywhere where is flatpak exists without any problem (but maybe there are exceptions, I can't fully guarantee it).

I already have working prototype [here](https://github.com/ElXreno/tw.ddnet.ddnet), but need to change [ddnet.appdata.xml](https://github.com/ddnet/ddnet/blob/master/other/ddnet.appdata.xml) a little bit before push if you agree with my suggestion.
Also we must decide [Application ID](https://docs.flatpak.org/en/latest/conventions.html#application-ids) because maybe you don't like what I wrote for current prototype (right now is `tw.ddnet.ddnet`).

What do you think about it?

**Comment by def-** [comment]
Hi @ElXreno. There have been a few approaches to package applications in a cross-distribution way for Linux, none of which could yet be considered successful. So I personally don't see how Flathub will.

So that's why I haven't put any work into that. But if you're willing to maintain a build, I'm totally fine with it and have to say: Thanks for the effort!

tw.ddnet.ddnet seems fine to me as the app id.

**Comment by Learath2** [comment]
I really don't like this whole ecosystem and wouldn't really want to
support it's spread.

**Comment by ElXreno** [comment]
@Learath2 can you explain why you don't like it?

**Comment by Learath2** [comment]
Flatpak is yet another step in systemd's world domination plans. Just like poor udev and dbus they'll maintain that it's not a part of systemd and it doesn't depend on systemd, right until enough people use it. Then it'll slowly start depending on systemd, then it'll be a part of the systemd project, then whoops  we accidentally absorbed the entire thing: no other configuration is supported soz.

I don't agree with the idea of distro unification and I don't support decreasing choice.

**Comment by def-** [comment]
> Flatpak is yet another step in systemd's world domination plans.

This sounds very far-fetched. See for example: https://flatpak.org/faq/#Is_Flatpak_tied_to_systemd_

**Comment by Learath2** [comment]
Neither was udev nor dbus nor GNOME

**Comment by ElXreno** [comment]
Now [DDNet available in Flathub](https://flathub.org/apps/details/tw.ddnet.ddnet)! :tada: 
Thanks @def- and @heinrich5991 for your help!

**Comment by def-** [comment]
Thanks!
