### ISSUE TITLE
Can't clone this repo

### ISSUE THREAD

**Issue by ElXreno** [ddnet/ddnet#2196]
When enabled `transfer.fsckobjects` in git configuration file, I can't clone this repo because:
```
Receiving objects: 100% (99229/99229), 243.77 MiB | 23.71 MiB/s, done.
error: object ef726cdbc13e62798213b118a7be991b99fec355: zeroPaddedFilemode: contains zero-padded file modes
fatal: fsck error in packed object
fatal: index-pack failed
```

If I understand properly this object broken in github, right?

**Comment by heinrich5991** [comment]
Yes. Not much we can do about it without rewriting all history.

**Comment by ElXreno** [comment]
Oh, okay. Thanks for the info @heinrich5991. 
I close this issue.
