### ISSUE TITLE
Long name when showing id collides with clan tag

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet#2211]
![screenshot_2020-05-23_23-51-24](https://user-images.githubusercontent.com/10178629/82741237-670bea00-9d50-11ea-8479-5a1ccaa67915.png)

**Comment by def-** [comment]
Same without cl_showids btw, so the name field is just too large when the clan field is large too.
![screenshot_2020-05-24_08-25-58](https://user-images.githubusercontent.com/2335377/82747341-46678280-9d98-11ea-9bbb-26f1f7ecf83e.png)

**Comment by Jupeyy** [comment]
Should be fixed by #3636
