### ISSUE TITLE
The "vote" to change to /practice mode should use the f3/f4 vote system, or should be explained better

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#2222]
TITLE WAS: The vote to change to /practice mode doesn't work when it's just my dummy and I in a team

> [chat]: *** 'd3fault' voted to enable /practice mode for your team, which means you can use /r, but you can't earn a rank. (1/2 required votes)

I try switching to dummy at this point hoping I have the ability to vote (edit: f3/f4), but nope.

I think we need to do the "same IP" trick for voting (maps, kicks, etc) that works 99.999% of the time (but doesn't work 0.0001% of the time when your dummy has a different IP than your primary).

Workaround: enter /practice mode before your dummy joins the team (so there is no vote).

**Comment by d3fault** [comment]
oh I realized it doesn't use the normal vote system ("f3" and "f4")... but I think it should! current way is kinda ugly

**Comment by heinrich5991** [comment]
The practice mode shouldn't be enabled accidentally, therefore the explicit wish.

I'm against f3/f4, first this conflicts with any outstanding votes which means you could get tricked into pressing f3 accidentally.

**Comment by def-** [comment]
Yeah, this is by design. I also didn't want to extend the f3/f4 vote system to allow multiple ongoing votes, one per team etc.
