### ISSUE TITLE
Suggestion: Add indicator to show which teams are in /practice mode

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#2223]
I don't know what kind of indicator there should be, all I know is I don't want to waste my time spectating some noobs in practice mode :-P

**Comment by heinrich5991** [comment]
They should probably get a player flag. Perhaps they could be shown separately/hidden by default (by the client!) in scoreboard/spectator board?

**Comment by fokkonaut** [comment]
What about greyscaling their team color?

**Comment by def-** [comment]
> What about greyscaling their team color?

That was also my idea.

**Comment by d3fault** [comment]
> What about greyscaling their team color?

One problem with that is differentiating between the different teams that are in practice mode. Unless.... 63 shades of grey? B)

I do like the idea in general though, and how about going a step further and greyscaling their tee as well? To add insult to injury :)

**Comment by C0D3D3V** [comment]
The issue was about a general indicator. But if you want it in the scoreboard I rename it.

**Comment by AssassinTee** [comment]
For this to work we'd need a network extension, CHARACTERFLAG_PRACTICE_MODE exists but a player needs to be in view for this to be send. I'd be really simple to extend the ddnet player but harder and more correct to extend the existing network code for teams
