### ISSUE TITLE
Suggestion: Restore player "state" when using /rescue

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#2225]
You might have lost all weapons since you were last "grounded", and maybe the weapons are needed to proceed with the map. Pressing /r should give you back all the weapons you had when you were last "grounded". Not just weapons tho, all player state (like whether or not you have endless, jetpack, etc etc). Could probably copy/paste code from save/load for this (or better yet, share the code paths).

A map demonstrating what I mean is "Loopie". After getting the first nade there's a swing through shields a little bit after that... and if you don't 1 shot it (2 is pussy) it's gg and /r can't help you because you no longer have nade and can't proceed with map.

**Comment by def-** [comment]
Done in b1b5dab1ddb41d616d08169cd49e6a793dfe7604

**Comment by heinrich5991** [comment]
Only for weapons, not other status effects. Should probably share code with saving/loading.
