### ISSUE TITLE
Pretend that hookthrough is a single layered tile

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#2238]
New hooktrough tile should be a single layered tile. Due to technical issues it is not. But we should affect user as less as possible. So I am proposing to simulate it as much as possible

Proposition:
1. At front layer ignore any possible modifications (except described at p2) of locations where this tile resides.
2. If this tile removed from game layer remove it from front layer as well.
3. Update graphics (remove tile image from front layer).
4. Also we should render this tile even if game layer is hidden

Possible drawbacks:
you can place nothing at position where this tile sits but there is very less amount of tiles you can place on top of solid block and also it is not currently possible.

**Comment by BannZay** [comment]
It is always possible to make it single layer entity (from user point of view) by letting it depend on new  hidden "service" layer. Such approach better but will require a lot of work

**Comment by def-** [comment]
The reason we don't have this is for Vanilla client compatibility, namely to predict the tee not falling through it.

**Comment by BannZay** [comment]
@def- , seems, you didnt read my message
