### ISSUE TITLE
Might as well let players join a team in /practice mode even after starting line

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#2244]
...because why not? (both the tee wanting to join the team, and the team being joined, can be already passed the starting line)

Usual lock/invite rules still apply tho ofc...

**Comment by d3fault** [comment]
#pa/rty

**Comment by def-** [comment]
The problem with that is that it will fail when a map has switches and you didn't activate them in the team.

Also, this seems a bit ugly to implement. I'm against it.

**Comment by Learath2** [comment]
^^ and I don't even want to imagine what kind of consequences this could have, especially at the hands of our resident pentesters.

**Comment by d3fault** [comment]
Ok maybe I shouldn't have suggested being able to *form* a practice team at any point, since there's switches to consider (good point). However what if we allow a more limited variant where a tee can join an already-started practice team? Because of the switches reason you mentioned, the practice team has to be initially *formed* before the starting line (even if just a team of 1), but I think it would be cool if more could join the run as it's going.

Use case: was running a Springlobe /practice with a few USA homies and a bunch more homies joined and I wanted to /invite them to the throwaway run but couldn't :sob: 

I don't see any vulnerabilities with this, since practice runs don't count and we're already handling the case where a player *leaves* a practice team.

**Comment by def-** [comment]
Yeah, but then you also need to teleport the players to you and so on. Needs many more features to work well. (I'm not against it, just saying it's too much work for me to do it.)

**Comment by C0D3D3V** [comment]
Now we have teleport command, so the use case would be more valid. But I do not really think it is a good use case. Normally you do not want to practice with some random players that just joined. And if you want you could just teleport before you start the race, so the race does not count, and the team will not get locked for new players, so everyone can join as they want.

**Comment by archimede67** [comment]
Should be fixed by #7885
