### ISSUE TITLE
/practice last /r position doesn't get saved

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#2248]
When u inair and do /save and then /load, ur last /r pos is at the /load position.

**Comment by def-** [comment]
That seems ok. Is that really a problem?

**Comment by Jupeyy** [comment]
well, idc, but we had the problem that we saved midair, used /r after loading again and were at the beginning at the map, where we used /load which overrided our last /r position

**Comment by def-** [comment]
Ok, now I understand, that's a bit worse than I thought. I guess we should /r position immediately after loading.
