### ISSUE TITLE
Flags are not antiping-predicted well

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2253]
As posted by Oblikumquat on Discord.

@trml
[anti.zip](https://github.com/ddnet/ddnet/files/4744338/anti.zip)

**Comment by Piepow** [comment]
I'm Oblikumquat from Discord and that video was me testing antiping on my own 0.7 client. The antiping on DDNet client doesn't have these issues :D Sorry for the confusion

**Comment by def-** [comment]
Oops, I misunderstood.
