### ISSUE TITLE
Feature: Sharable SaveState "Codes" for /practice

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#2259]
For those of us that can copy/paste from DDNet:

tl;dr:
string copyPasteMe = base64encode(signWithPrivateServerKey(rawSaveData));
upon trying to load, the data has it's signature checked to make sure the user hasn't changed it
the "codes" needn't be saved server side, users can exchange them among themselves freely

**Comment by def-** [comment]
I'm against this, way too complex. Maybe we just need something like super for practice. See for example https://github.com/ddnet/ddnet/issues/2391
