### ISSUE TITLE
double hook sounds player attach 

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#2300]
dont send the hooksound player attach from character.cpp to sixup clients, they handle hooksound based on coreflag_hook_attach_player clientside, so we get two sounds

**Comment by def-** [comment]
can confirm. @Learath2

**Comment by def-** [comment]
Fixed by https://github.com/ddnet/ddnet/commit/9d9d5e26e62c61068149caa91f39ae3fb508fc08
