### ISSUE TITLE
src/game/server/teeinfo.cpp:32:91: error: array used as initializer

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2320]
In the build for release:
```
/ddnet-master/src/game/server/teeinfo.cpp: In constructor ‘CTeeInfo::CTeeInfo(const char*, int, int, int)’:
/ddnet-master/src/game/server/teeinfo.cpp:32:91: error: array used as initializer
 CTeeInfo::CTeeInfo(const char *pSkinName, int UseCustomColor, int ColorBody, int ColorFeet)
                                                                                           ^   
/ddnet-master/src/game/server/teeinfo.cpp: In constructor ‘CTeeInfo::CTeeInfo(const char**, int*, int*)’:
/ddnet-master/src/game/server/teeinfo.cpp:40:94: error: array used as initializer
 CTeeInfo::CTeeInfo(const char *pSkinPartNames[6], int *pUseCustomColors, int *pSkinPartColors)
                                                                                              ^   
```

Probably because it's an old gcc version. @Learath2 Do you want to take a look? I could also do so later.

**Comment by Learath2** [comment]
How old is this GCC? I thought this kind of initialization with a string literal was legal since C++11 which is quite old.

**Comment by def-** [comment]
```
g++ (Debian 4.9.2-10+deb8u1) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
```
Maybe I have to upgrade? But so far everything worked.

**Comment by Learath2** [comment]
Ah apparently it works fine since gcc 5.1 per one stackoverflow answer. I
guess we can use a brace initializer instead?

**Comment by def-** [comment]
Yes, would be nice. If I update my Debian chroot I'll probably find out that someone is still using CentOS with glibc from the last century.

**Comment by Learath2** [comment]
You are the one with access to the compiler, I'll just end up making a bunch of commits.
