### ISSUE TITLE
Difficulty field in 0.7 could be used to map DDNet difficulties to

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2334]
Casual: Novice
Normal: Moderate, DDmaX, Oldschool, Solo, Dummy
Competitive: Brutal, Insane

If you want to get fancy you could also look at the points/stars and split up DDmaX, Oldschool, Solo, Dummy as well.

@Learath2 Want to take it? Or anyone else? Should be pretty easy to implement, I can also do it myself.

**Comment by def-** [comment]
Actually we have the points information in the scripts, so we can just create a map specific "sv_difficulty" setting in the map.cfg

**Comment by Learath2** [comment]
Well I'm out for tonight, I can do it tomorrow or much later tonight if
noone else wants it
