### ISSUE TITLE
MySQL < 8 not supported anymore

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2343]
@Zwelf Can you take a look?

As reported by jason54 on Discord
![unknown](https://user-images.githubusercontent.com/2335377/85521437-8a061400-b604-11ea-942b-d4d1de03aff0.png)
Got the collation fixed for /mapinfo, but /rank and /top5 don't work because of the RANK() OVER construct.

**Comment by Zwelf** [comment]
RANK() OVER support was added in MySQL 8 (released [in 2018](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/)): https://stackoverflow.com/a/52393883 https://dev.mysql.com/doc/refman/8.0/en/window-function-descriptions.html#function_rank
* Ubuntu 18.04 packages MySQL [5.7.30](https://packages.ubuntu.com/bionic/mysql-server)
* Ubuntu 20.04 packages MySQL [18.0.20](https://packages.ubuntu.com/focal-updates/mysql-server)

If we want to support Ubuntu 18.04 with MySQL, then we have to revert the database queries to not use `RANK() OVER`:

* 68aa157c1150c24a5c6f981f09de2fb339a055ee (/rank)
* a92509a5df7ece5e092b330922ace3af8cdf9ea5 (/top5)
* 1d7289c8f082eea7224d40a22eaaef814a5e6e88 (/top5team sadly not a separate commit)
* 83fbee5f815398eefa90f179e1d774699a184263 (/teamrank)
* 62f3f40c00a9c169f772f9c64bc0e143181b9556 (/points)
* 7514e93a8a3b583bfe42c433b53f8bac590f41f7 (/top5points)

**Comment by def-** [comment]
Yep, I found out the same (on Discord). My suggestion would be to have both variants in the code with a TODO to remove the old one when common distributions (Debian, Ubuntu, CentOS) all support MySQL 8 in all supported versions. But that will probably take a few years. Considering Ubuntu 18.04 will be supported until April 2028: https://wiki.ubuntu.com/Releases

Hmmm. Opinions?

**Comment by heinrich5991** [comment]
Given that MariaDB is a drop-in replacement that is essentially just better, would it be possible for jason54 to move to MariaDB? I don't know a reason for using MySQL except when it's already used.

**Comment by def-** [comment]
I don't think MariaDB is "just better". MariaDB has an unfortunate history of ignoring bug reports, see for example https://www.manuelrigger.at/dbms-bugs/ :

>  All our bug reports for MariaDB were verified quickly. However, only one of them was fixed, which is why we have stopped testing this DBMS.

**Comment by heinrich5991** [comment]
Okay, didn't remember that one. Sorry.

**Comment by def-** [comment]
I'm leaning towards requiring MySQL 8 or MariaDB 10.2, but the only problem with that is that Ubuntu 18.04 LTS only has MariaDB 10.1 as well...
