### ISSUE TITLE
When a tee joined the server before you and went into /spec you don't see it

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2344]
at all. @edg-l

**Comment by edg-l** [comment]
I don't know why this happens, the client must know something since you can see the player in the scoreboard in spectators.

**Comment by def-** [comment]
because the client never received a net char object for this tee I guess

**Comment by def-** [comment]
Also happens when you can't see the tee at the moment that they go into spec. So basically you only see the tees that were very close to you when they went into spec.
