### ISSUE TITLE
Disable 3 word default pws for saves?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2362]
They seem to not be received so well and cause confusion.

@Zwelf Would it be possible to safely fix it so that we just get an error again and the team can choose a new code on their own?

**Comment by heinrich5991** [comment]
Perhaps a message that the other save code is already occupied would suffice?

**Comment by Zwelf** [comment]
We would need two round trips if we want to only save when the save-code does not exists.
1. Check if the save code exists -> Result probably to CScorePlayerResult
2. kill the team and start current save procedure

We could add a command to check if the save code already exists. Then informing the player might be enough (and telling them that they can check beforehand if the save code already exists)

**Comment by heinrich5991** [comment]
What I mean is: Currently the player isn't informed about the reason that their save code was changed. They just see "successfully saved to some other save code". Adding a line about their specified save code already being occupied might clear that confusion.

**Comment by def-** [comment]
> We could add a command to check if the save code already exists.

I think that's too much work, people just want to try /save foo, and if it doesn#t work they'll want /save foo2
