### ISSUE TITLE
Array out of bounds access in `CPlayers::RenderPlayer`

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#2365]
https://github.com/ddnet/ddnet/blob/df66d83a04789b628d1526e9414ec9f4c231a7e8/src/game/client/components/ghost.cpp#L343

ClientID: -2

https://github.com/ddnet/ddnet/blob/df66d83a04789b628d1526e9414ec9f4c231a7e8/src/game/client/components/players.cpp#L218

Access to array with index -2.

**Comment by def-** [comment]
Just add a ClientID >= 0 I guess?

**Comment by heinrich5991** [comment]
To fix this, yes. I haven't checked the whole function and the `RenderHook` function, there might be more of this kind.
