### ISSUE TITLE
Switching from editor to desktop and back makes the mouse disappear

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2369]
> Cøke: new editor bug, when you are in the editor, switch to the desktop and switch back to the editor the mouse is gone and you can't do anything anymore. that means you have to delete everything mapped that is not saved... so before you go to the desktop it is best to save and close the editor

I can't reproduce. Can anyone confirm? Is this with fullscreen on Windows?

**Comment by def-** [comment]
Arellien on Discord reports the same issue, but already had it before DDNet 14.0. So it could be related to https://github.com/ddnet/ddnet/pull/2186

@BannZay any idea?

**Comment by BannZay** [comment]
Can not reproduce =(

**Comment by BannZay** [comment]
I have left a game for some time and it reproduced for some reason. For some reason, X coord is broken. See screenshot
![ddnetBrokenState](https://user-images.githubusercontent.com/17499770/85853813-d6e01b00-b7bb-11ea-865d-ff78e6026a8a.png)

**Comment by def-** [comment]
@BannZay could you try to fix it please? I hear from Cøke that more mappers are now having this problem.

**Comment by BannZay** [comment]
@def- it is pretty hard to reproduce. Okay, I will come back in 2-3 days if I fail to solve it

**Comment by def-** [comment]
> Lady Saavik: @deen I took SDL2 file from DDNet 12.5 and it's fixed

So we'll try taking SDL 2.0.8 instead of SDL 2.0.12 again.

**Comment by BannZay** [comment]
@def- about bug, keyboard was never broken in my case.

Update: Bug affects editor only, you can still play ingame, use game menu etc. 
I can change top left editor coordinates by moving mouse. X stay static and always have some magic constant = -67108864, but I can see a changes for Y, it could be changed from -37 to 37 when you drag mouse up&down. If you change zoom - ranges increases.

I have memory dump of process, but not managed to reproduce it with debuggable process yet

**Comment by def-** [comment]
Oh, so you can still ctrl-s to save the map and ctrl-shift-e to leave editor.

**Comment by BannZay** [comment]
Leave editor - easy
Save map - no. The problem is that is asks you to confirm override of the existing file, but as far as I know it is not possible to confirm from keyboard

**Comment by def-** [comment]
too bad.
