### ISSUE TITLE
DDNet 14 client can't join DDNet-Server on LAN?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2370]
> ᶰ°Konͧsti: @deen any idea why i cant join DDNet server 14 on lan?

I can't reproduce on Linux and with Win64 in wine. Anyone can?

**Comment by def-** [comment]
> onby: @deen i tried on osx and it doesnt work for me either

@Learath2 Do you think this could be related to sixup?

**Comment by Learath2** [comment]
I built from scratch both the server and the client on osx and it works fine for me. To know where the issue actually happens needs more debugging.

**Comment by Learath2** [comment]
This also seems to be happening with the server we ship on ddnet.tw will investigate further tomorrow.

**Comment by fokkonaut** [comment]
Had something like this too when i first added bridge server. Might want to debug the client too, in engine/client/serverbrowser.cpp at the Set() function. This helped me find some bugs on the serverside tokens
