### ISSUE TITLE
Add new option in next patch please.

### ISSUE THREAD

**Issue by annrial** [ddnet/ddnet#2383]
_cl_show_hook_coll_own_ and _cl_show_hook_coll_other_ -> these options just turn on/off your/other people hooklines, so if i use it 0 i just don`t see my or their line. The thing like "_cl_show_hook_coll_always_" is almost the needed option but when you use it, u see the hookline always for everyone (your and other players). It would be great to have 1 more option, which will show your hookline always for you only. (Something like: _cl_show_hook_coll_always_ "**1**" + _cl_show_hook_coll_others_ "**0**, like these two options doesn't work together). A lot of people in gores don't like to see my line always for example, but i just got used to it and i need it for my comfortable gameplay. 

So i ask you to make a new option, for example called _cl_show_hook_coll_own_always_ "1/0" so when u use it like "1" you always see a hookline from your tee but you see other players hooklines only when they press button for it. Same for them, like when i use this option, i should see my hooline, but other players should not, until i will press button for a hookline bind. So option will show me the line which only i can see until i will press hookcoll bind to show it for all.

Would be nice to see such new option in next patch, i know a lot of people who want this one (maybe because of me). Can you make such option please.

**Comment by def-** [comment]
1. `bind s +showhookcoll`
2. Hold s
3. Press t for chat
4. Unhold s
5. Press Escape

Now your own hook collision stays there.

**Comment by Ekidoxx** [comment]
Or for more common version, replace `t` & `Escape` with `F1` console (less hand movement needed :P)

**Comment by annrial** [comment]
> 1. `bind s +showhookcoll`
> 2. Hold s
> 3. Press t for chat
> 4. Unhold s
> 5. Press Escape
> 
> Now your own hook collision stays there.

Man, i know how to do such trick, thats not what i mean. We need an option, that i will see my hookline, but other people not. Like some people getting annoyed when others use hookline all time.

**Comment by def-** [comment]
But others can set `cl_show_hook_coll_other 0`. I don't think we need even more options here, sorry.

**Comment by def-** [comment]
Actually let me implement it as `cl_show_hook_coll_own 2` (and another `cl_show_hook_coll_other 2`). Then I can remove `cl_show_hook_coll_always`.

**Comment by annrial** [comment]
> Actually let me implement it as `cl_show_hook_coll_own 2` (and another `cl_show_hook_coll_other 2`). Then I can remove `cl_show_hook_coll_always`.

I didn't get what u mean with `cl_show_hook_coll_own 2` but the option i asked for is needed, i mean it would be nice. I know more than 100 people from gores who will be happy to see such option, because i always use hookline and many of them don't want to see it all the time, but they don't want to use `cl_show_hook_coll_other 0` because sometimes they need to see hookline.
Btw, even without new option, `cl_show_hook_coll_other 0` and `cl_show_hook_coll_always 1` doesn`t work together, so i could use it like that, so they won't see my line and i won't see their lines, but i would see mine, but these 2 options do not work together, i still see all lines.

**Comment by annrial** [comment]
I can do a survey among gores players if u want. I'm sure i will get not less than 100 people wishing to get an opportunity to have such option.

**Comment by def-** [comment]
No need for a survey, you'll get your feature in the next release.

**Comment by annrial** [comment]
> No need for a survey, you'll get your feature in the next release.

If it will work how we mean, then would be great, thanks a lot in advance.
