### ISSUE TITLE
Tele number should differentiate between normal and checkpoint teles

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2384]
and indicate for both whether the number is already used. As suggested by Cøke on Discord.

Not so easy/clean to implement unfortunately.

**Comment by Nyte-BK201** [comment]
Maybe a logic inside map editor which rearrange all tele/checkpoints/teleto like what IDE auto-format does can solve .
Build up on automap feature

**Comment by BannZay** [comment]
The problem is in numbers itself ? Maybe we just need to change a representation to distinguish them better ? (like another teleport color or prefix it with C digit or whatever else for checked teleports)
