### ISSUE TITLE
Show only team members in command like /showothers

### ISSUE THREAD

**Issue by ExP98** [ddnet/ddnet#2394]
Use a command like /showothers but show only teammates (in solo parts), not all.
Also, this command could be expanded to "team mode" when you see only ur mate (even in freeze scaled by alpha) and only team messages + some server messages (e.g., when you finish and get the message about how your time is better or worse)

**Comment by def-** [comment]
There is already /specteam, which is a bit similar. I don't think we should add more commands though, already have too many.

**Comment by ExP98** [comment]
/specteam does absolutely other stuff. I am talking about seeing my teammate (and only him!) in solo parts. Specteam just hides other players (even my teammate) in solo when I am in /pause or /spec.
This command could be more  about /showothers but not /specteam

**Comment by def-** [comment]
Learath2 suggested to implement this as /showothers 2
