### ISSUE TITLE
Saving on solo server sometimes kills you when save code exists

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2404]
@Zwelf  Could you take a look please?

Reported by barsik on Discord

```
[2020-06-28 17:52:05][debug]: line='/save 1'
[2020-06-28 17:52:05][game]: kill killer='3:gerdoe' victim='3:gerdoe' weapon=-2 special=0
[2020-06-28 17:52:05][chat-command]: 3 used /save 1
[2020-06-28 17:52:05][sql]: ERROR: This save-code already exists
```

**Comment by def-** [comment]
Same if I do `/save` without specifying a save code.

**Comment by def-** [comment]
Solo servers have `sv_solo_server 1` and `sv_team 3`.

**Comment by gslav** [comment]
DDNet client version 14.0.2. Manjaro with linux 5.6.16-1.

Just did some tests in game:
`/save` —  kills player, doesn't save
`/save 1` — kills player, doesn't save
`/save '1'` — kills player, makes savepoint which can be loaded
`/save a1` — kills player, makes savepoint which can be loaded
`/save 1a` — kills player, makes savepoint which can be loaded
`/save 'a1'` — kills player, makes savepoint which can be loaded

So, I can create a savepoint if the savecode is passed as a string (in quotation marks or just contains any letter), but I can not, if the savecode consists of only numbers and isn't non-quoted.
