### ISSUE TITLE
Duplicate ranks in teamranks

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2405]
Seems like this is happening recently on all servers with teamranks. When there is an existing teamrank already for the exact team, it should be updated instead of inserted. I couldn't find a mistake in the code and couldn't reproduce it. Do you have any ideas @Zwelf?

It's not a huge problem since I have a script to remove-duplicate-teamranks.py, but still weird.

**Comment by Zwelf** [comment]
Were the old team ranks made with `DDNet7 = true` (and the new with `DDNet7 = false`)? I have no idea otherwise.

**Comment by def-** [comment]
No, both with false.

**Comment by def-** [comment]
SaveTeamScoreThread assumes std::sort is equivalent to mysql's order by

I don't think that's true for all unicode names, is it? This might explain some of the duplicate team ranks we got. Maybe just std::sort both of them?

**Comment by Zwelf** [comment]
Both use binary values to order the strings (I checked it at the time of writing the code). Maybe some sort of unicode normalization (I am thinking of same character with different unicode/utf8 representation)?

**Comment by def-** [comment]
I think I switched to utf8 collation long ago:
```
MariaDB [teeworlds]> SELECT DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME
    -> FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'teeworlds';
+----------------------------+------------------------+
| DEFAULT_CHARACTER_SET_NAME | DEFAULT_COLLATION_NAME |
+----------------------------+------------------------+
| utf8mb4                    | utf8mb4_general_ci     |
+----------------------------+------------------------+
1 row in set (0.000 sec)
```

Maybe I forgot to set it in ddnet code. I'll push a fix.
