### ISSUE TITLE
rendered tee in /spec is showing up for other teams

### ISSUE THREAD

**Issue by Zoozti** [ddnet/ddnet#2410]
just as the headline says, when i spec in team others can see the tee outline even when im in an other team which is unneccesary

![screenshot_2020-06-29_20-42-53](https://user-images.githubusercontent.com/48534318/86043558-2e46eb00-ba49-11ea-9602-567c7e6569e7.png)

**Comment by def-** [comment]
With /showothers on? Try turning it off?

**Comment by Zoozti** [comment]
i never have /showothers on and just tried to be sure. It was off^^

**Comment by Zoozti** [comment]
and i realized that it makes a difference whether the tee that spec is in team or in team 0. If a player in team specs, people in team 0 will only see the rendered tee without a name. If the player in team 0 specs players in a team will see the outline and the name

**Comment by def-** [comment]
@edg-l Could you take a look?
