### ISSUE TITLE
Language Update (Hungarian) for 14.+

### ISSUE THREAD

**Issue by RIH-Cellegen** [ddnet/ddnet#2428]
+Added 95%~ of the missing texts that has been added to 14.0 and above.
+Fixed most texts, that was being larger, than intended.
+Fixed translations on "Dummy" for better understanding.
!Didn't test the translation of the "Tutorial Phase" yet, but i think it stands out good, as scaling goes well for it.
!There's a bug with "Connect Dummy" and "Disconnect Dummy" on the Hungarian translation, which I've tried to apply, but
with no success. Please fix the texts where on the missing text section they stand out with "[!]" marks.

[hungarian.txt](https://github.com/ddnet/ddnet/files/4853979/hungarian.txt)

**Comment by def-** [comment]
Thanks, will add.
