### ISSUE TITLE
Follow XDG basedir specification

### ISSUE THREAD

**Issue by AriaMoradi** [ddnet/ddnet#2431]
basically same as https://github.com/teeworlds/teeworlds/issues/1504

**Comment by AriaMoradi** [comment]
also move all data files from the older version to the new location automatically
and remove `$HOME/.teeworlds`

**Comment by heinrich5991** [comment]
Automatically moving is probably a no-go, because the user might have older clients relying on the old location.

**Comment by Learath2** [comment]
We could move it automatically but leave a symlink in place maybe

**Comment by AriaMoradi** [comment]
how about making a copy and working with the xdg versions
older versions will not lose access to the old data

**Comment by def-** [comment]
> how about making a copy and working with the xdg versions

I don't like that solution because then you have two data directories that could be used in parallel, lots of confusion for players.

> We could move it automatically but leave a symlink in place maybe

This is the way to go (if we want this). Honestly most applications I use are in .foobar and not .config/foobar.

**Comment by AriaMoradi** [comment]
would merging https://github.com/teeworlds/teeworlds/pull/1513 work or does it need more work?

**Comment by def-** [comment]
I think so, cherry-picked it for now: https://github.com/ddnet/ddnet/pull/2454

**Comment by def-** [comment]
Here's my thoughts on what to do:

Only ~/.teeworlds exists:
- Move to ~/.config/teeworlds
- Symlink ~/.teeworlds -> ~/.config/teeworlds
Only ~/.config/teeworlds exists:
- Symlink ~/.teeworlds -> ~/.config/teeworlds
Both ~/.teeworlds and ~/.config/teeworlds exists:
???

Not sure of a good solution for the last one. We can't just remove ~/.teeworlds, should we merge them, should we ignore the existing ~/.teeworlds, fail with an error message?

**Comment by AriaMoradi** [comment]
> Not sure of a good solution for the last one. We can't just remove ~/.teeworlds, should we merge them, should we ignore the existing ~/.teeworlds, fail with an error message telling the user to somehow merge them manually and remove ~/.teeworlds?

I think using ~/.config/teeworlds and warning the user that we are doing it would be best.
because if they only use the ddnet clinet and the original teeworlds client then that's most definitely will be fine.
and if they also use (older) clients that don't have this feature, they just have to be aware.

And also I think 
1- If $XDG_CONFIG_HOME is set to something other than the standard path, we should respect it.
2- If $XDG_CONFIG_HOME is not set, then fall back too ~/.config/teeworlds

**Comment by Learath2** [comment]
#2698 can close this too

**Comment by Jupeyy** [comment]
fixed by #4509
