### ISSUE TITLE
Using cl_text_entities_size comand with openGL 3 makes tiles with text become a black square

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#2438]
Probably comes with 6a6a5f00
Issue gone if you remove checks here: https://github.com/ddnet/ddnet/blob/a62eeeb8296fcfb6313006f69f4be9b65d6ba2d7/src/game/client/components/mapimages.cpp#L214

I dont understand a reason why it been working before so not gona make PR for now

**Comment by def-** [comment]
@ChillerDragon Can you take a look?

**Comment by ChillerDragon** [comment]
@def- tbh I had no either what I was doing either. Im not familiar with graphics at all and just hacked the commit from Magnus into tw src and did try and error until it built. Im sure some more graphics savvy devs have an idea. @Jupeyy
