### ISSUE TITLE
Practice mode broken on solo servers

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#2445]
>[9:40 PM] ScReeNy: @here there is a major bug on solo servers again
>[9:41 PM] ScReeNy: if u finish in practice mode you actually finish the map
>[9:42 PM] ScReeNy: would abuse but am too busy, sry bout that. See latest #record as proof
>[9:42 PM] Soreu: https://tenor.com/view/yikes-monkey-look-and-leave-yikes-monkey-look-and-leave-gif-14895670

(Reportedly, have not verified. I disabled /practice on all servers.)

**Comment by Ekidoxx** [comment]
The mentioned rank:
> [[9:41 PM] DDNet BOT](https://discordapp.com/channels/252358080522747904/338779500085116938/728334439813480459): Top 1 rank on [[Solo](https://ddnet.tw/ranks/solo/)] [Memoria](https://ddnet.tw/maps/Memoria/): 06:19.58 [mc chicken](https://ddnet.tw/players/mc-32-chicken/) (next best time: 07:26.84 - 15.1% improvement!)
