### ISSUE TITLE
Weird artefacts overlaying some textures

### ISSUE THREAD

**Issue by Vy0x2** [ddnet/ddnet#2452]
Client Version: 14.0.1
Person said, he hasn't deleted any files in data
Appeared mid-gameplay
He had screensharing activated in discord I guess?

Screenshot:
(Thanks for uploading ekidoxx)

**Comment by Ekidoxx** [comment]
For future, in case the hosting dies or so ¯\\_(ツ)_/¯
![dllhost_3qg0F2buuC](https://user-images.githubusercontent.com/14035306/86537916-bb2ef000-bef2-11ea-8cc5-9be6723399ed.png)

@Vy0x2 you don't have to upload it anywhere, just drag over the textbox on GitHub, and it will upload it to its servers

**Comment by Learath2** [comment]
I'd guess this is no longer an issue in the latest version

**Comment by Jupeyy** [comment]
reopen, if reported again
