### ISSUE TITLE
0.7 client, in /pause there is no Free view listing

### ISSUE THREAD

**Issue by KRN-8** [ddnet/ddnet#2455]
in /pause there is no Free view listing (Spectate players still work normally, only every other spectate way is broken)
![obrazek](https://user-images.githubusercontent.com/67783847/86619936-bbdf8900-bfbb-11ea-9a35-36705fcaffa3.png)

**Comment by Learath2** [comment]
I know this bug, I never figured out how to fix it

**Comment by fokkonaut** [comment]
@Learath2 you need to send a teamchange for being in pause/spec
https://github.com/fokkonaut/F-DDrace/blob/956736b79ca4e08c08434e3f6d57ba2bf97858a0/src/game/server/player.cpp#L1261

**Comment by Learath2** [comment]
Fixed by 85a2268b2a0f2c82d1f439a6b5605ac82c82444b
