### ISSUE TITLE
Use system locale to set language on first execution

### ISSUE THREAD

**Issue by edg-l** [ddnet/ddnet#2459]
https://en.cppreference.com/w/cpp/locale/locale
https://en.cppreference.com/w/cpp/io/ios_base/getloc

Most games do this.

**Comment by heinrich5991** [comment]
That would be great.

Does it return sensible results on all platforms?

**Comment by heinrich5991** [comment]
Perhaps also https://partner.steamgames.com/doc/api/ISteamApps#GetCurrentGameLanguage.

**Comment by def-** [comment]
Hm, I guess it's not so easy the map the returned locale to an actual language. We'd need to have our own mapping or use something like boost.
