### ISSUE TITLE
Client()->Rcon("crashmeplx") is being sent on CTF 16 players servers

### ISSUE THREAD

**Issue by nzyuzin** [ddnet/ddnet#246]
As I've been told in irc, Client()->Rcon("crashmeplx") serves as an indicator for ddrace/ddnet client.

Also, as seen in comments above this line https://github.com/def-/ddnet/blob/791e260e652d9e7b00279a0247cb81dee1385efb/src/game/client/gameclient.cpp#L420 this functionality is tied to 64 player servers. (am I correct on this?)

The problem for me is that I see Rcon("crashmeplx") in logs on my CTF 16 players too, which is somehow confusing.

It would be cool if "crashmeplx" was only sent on appropriate server/game types.

**Comment by def-** [comment]
Closed after IRC discussion, I guess.

**Comment by nzyuzin** [comment]
I actually wanted to try to disable crashmeplx on CTF and dm gametypes as soon as I get the time.

>_<

**Comment by def-** [comment]
What if someone made a 64 player vanilla CTF later on? But I guess that's not going to happen so it's probably ok. Ah, another problem is that you might not now the gametype at that point of the connection yet.

**Comment by nzyuzin** [comment]
If someone makes 64 players vanilla CTF server, then that certain someone may probably come up with a better implementation of 64 players support indication.

>Ah, another problem is that you might not now the gametype at that point of the connection yet.
Of course it needs some investigation but that doesn't cancel the issue itself. :)

**Comment by def-** [comment]
That new indication will not work for any old 64 player client though, not sure if that would be a good idea.

**Comment by nzyuzin** [comment]
*That new indication* can be supported on server side along with the old one.

The point is to have clients switch to new indication slowly, starting from CTF servers exclusively and then replacing old hacks completely.

As it won't hurt anybody, we are free to experiment with CTF now, aren't we?

Anyway, I think it would be better to check if it is at least feasible to "turn off" chrashmeplx on ctf and after PR is ready, continue the discussion there.

@def-, Could you please reopen the issue for now?

**Comment by def-** [comment]
> That new indication can be supported on server side along with the old one.

I did try that and not succeed, I think the other methods reported too late.

**Comment by def-** [comment]
Still see no change in the situation and no good reason to disable the old hack.
