### ISSUE TITLE
Verify that client sends server "zoom level" at correct time, depending on zooming in vs out, now that we have smooth zoom

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#2470]
Maybe this is already handled, idk.

Since zoom is now non-instant (a46b266), the client needs to be smarter about when it "tells" the server about it's zoom level (1782d95). Specifically, when zooming *in* the client should wait until *after* the "smooth zoom animation" finishes before sending the server the new zoom level... and when zooming *out* the client should send the server the new zoom level *before* the "smooth zoom animation" starts. Reason: so tees aren't considered "out of range" and not rendered *during* the zoom animation.

Also slightly OT: I'm going to assume only the *target* zoom level is being sent to server? not every zoom level in-between *during* a zoom animation? that would result in a lot of wasted bandwidth.

**Comment by def-** [comment]
> I'm going to assume only the target zoom level is being sent to server? not every zoom level in-between during a zoom animation? that would result in a lot of wasted bandwidth.

Every zoom level inbetween is sent at the moment. Will fix.
