### ISSUE TITLE
Tees disappear on wide screens

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#2475]
But apparently reappear after turning on dyncam?

**Comment by heinrich5991** [comment]
https://streamable.com/3jctap

**Comment by heinrich5991** [comment]
Perhaps caused by #2401.

**Comment by lryjnks** [comment]
Monitor: 21:9 UltraWide
Resolution: 3840x1600

**Comment by def-** [comment]
Can reproduce, will take a look.

**Comment by lryjnks** [comment]
Sorry wrong info dyncam doesn't matter for me too :)
