### ISSUE TITLE
Audio bug in other programs when DDNET is open

### ISSUE THREAD

**Issue by Logharaa** [ddnet/ddnet#2491]
This problem has appeared recently, perhaps since 14.0.
I am using an audio interface (Focusrite Solo), and when DDNET is opened, if I try to listen to music (with Tidal or on Youtube) the sound is scrambled, with noise.
What's weird is that this bug doesn't show up right away. I couldn't tell how long it would take.

The sample rate of my audio interface is 44100, like in the game, and the buffer size is 512. There have been no updates on my audio interface, only DDNET.

**Comment by def-** [comment]
Assuming you're on Win64 and this might be an SDL2 problem since we downgraded SDL in 14.0.3

Can you grab the SDL2.dll from 14.0.2 (https://ddnet.tw/downloads/DDNet-14.0.2-win64.zip) and put it into the current 14.2 directory and run that? Does it help?

**Comment by Logharaa** [comment]
I do this and I'll let you know

**Comment by def-** [comment]
Another idea would be that we send a request for a frequency but instead get another frequency provided by the system and we ignore that.

The reason for the downgrade was https://github.com/ddnet/ddnet/issues/2369

**Comment by Logharaa** [comment]
Well, after several tests, the bug occured again without DDNET open... So finally it's not related to DDNET, maybe a recent Windows update...
