### ISSUE TITLE
Player count too low in ddnet.tw/status

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2495]
Noticed during tournament, 400 real number vs 270 in status

**Comment by def-** [comment]
We use the old GETINFO_64_LEGACY for it, not sure if that's related but sometimes I saw player counts of exactly 24 while it should've been ~50.

I didn't notice any firewall rules that should have an impact.

**Comment by Learath2** [comment]
Could it be a lost packet? The legacy protocol only supports 24 clients per packet.

**Comment by def-** [comment]
This seems 100% reproducable locally:
```
  t = Teeworlds(timeout=3)
  serverAddress = ("176.9.114.238", 8313)
  server = Server64(t, serverAddress)
  server.request()
  t.run_loop()
  count = 0
  for player in server.playerlist:
    count += 1
  print(count) # Maxes out at 24
```

**Comment by def-** [comment]
Even with the initial version of teeworlds.py from 2014, so teeworlds.py didn't break, the DDNet server did for the fstd packet.

**Comment by def-** [comment]
To reproduce on server side: https://github.com/def-/ddnet/pull/new/pr-fake-full-server

**Comment by def-** [comment]
Working on a fix now.
