### ISSUE TITLE
prediction bugs out if you're shooting a weapon and start chatting (shotgun and laser too, but not as spectacular)

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2500]
As reporded by Ravie on Discord
![gif](https://user-images.githubusercontent.com/2335377/87241155-8bb34280-c420-11ea-8acf-a727588615fa.gif)

@trml could you take a look?

**Comment by fokkonaut** [comment]
same for walking while chatting

**Comment by trml** [comment]
Fixed by #2512 (the pr linked the wrong issue).
