### ISSUE TITLE
Hook sounds disappearing for players hooking other players

### ISSUE THREAD

**Issue by Fireball-Teeworlds** [ddnet/ddnet#2508]
Example: https://youtu.be/ZKXxNgFj-HA.

- Some players will not make hook sounds when hooking other players
- Wall hooking sounds are fine
- It seems that everyone will be missing hook sounds coming from that player (confirmed by asking another person who was there if they hear anything)
- If you record a demo, hook sounds will be missing from that demo too
- Rejoining the server doesn't fix the problem (if you're not the player that isn't making sounds)
- It's possible that changing the map doesn't help either, but I've only checked this once when all 3 players present were missing hook sounds - it might've been a different bug.

This has also been reported by nexusrf on Discord: [a video posted on #developer](https://discord.com/channels/252358080522747904/293493549758939136/732255672707711106).

Steps to reproduce: ?

**Comment by fokkonaut** [comment]
Probably related to Sixup @Learath2, because sixup clients dont need player hook sound, they have it clientside

**Comment by Fireball-Teeworlds** [comment]
@fokkonaut you were right!
