### ISSUE TITLE
Normalize DDNet databases

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#251]
ddnet databases could save lots of space by saving player and map ids instead of names and server ids instead of server names (more than 3 chars so GER2 also works)
- implement the new DB format in parallel in sql_server.cpp
- convert the DB
- echo sv_new_format 1 > servers/*.fifo
(same for ranks.py and players.py for official servers too)

**Comment by def-** [comment]
Also seems a bit wasteful to have 25 checkpoint values stores in the record_race table while most maps don't even use checkpoints.

Also record_race and record_teamrace have lots of duplicate data.

**Comment by def-** [comment]
**finishes**

    FinishID | MapID | PlayerID | TeamID | CountryID | Timestamp | Time

Same TeamID => Were in a team together
TeamID null => Team 0

**finishes_cp**

    FinishID | cp1 | cp2 | ... | cp25

**player**

    PlayerID | Name

**maps**

    MapID | Map | Server | Points | Stars | Mapper | Timestamp

**countries**

    CountryID | Name

**Comment by heinrich5991** [comment]
Consider keeping a backup of the database before normalizing it!

**Comment by def-** [comment]
An auto-increased ID field is problematic with our replication scheme. Need to set `auto_increment_increment` and `auto_increment_offset` on all servers for that with some safe space for more servers.

**Comment by H-M-H** [comment]
What about using stored Procedures instead of direct inserts. Those procedures could check for duplicates and let the lower timestamp win.

**Comment by def-** [comment]
So the stored procedure would potentially have to change all IDs that were inserted already. This seems pretty complicated to me, I'm wondering what the proper way is here. Probably to simply use master servers which are always guaranteed to be in sync.

**Comment by H-M-H** [comment]
> So the stored procedure would potentially have to change all IDs that were inserted already.

Exactly.

**Comment by user578** [comment]
Do you want to change db scheme soon or this is just long-range plan? I'm curious because I have a project that use db dump with current scheme.

**Comment by def-** [comment]
Not sure, I'm probably not going to work on it right now.
