### ISSUE TITLE
Prediction problem with hook off tile

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2510]
As reported by Cøke on Discord. Seems to happen every time you hook some. @trml Want to take a look?

**Comment by trml** [comment]
I couldn't find the discussion, but is this with the hook others on/off tile?

**Comment by Learath2** [comment]
@def- if you remember when it was maybe you can find it? In the future you should probably copy paste the relevant log

**Comment by def-** [comment]
Sorry, I missed @trml 's reaction. Cøke wrote to me in private in German so I'll translate:

> it always stutters so weird when hook others was off with tile
> will this still be fixed?
> The tile seems to work, but after you had used it once it always stutters when you hook others or get hooked.
> That's also why I recommend mappers not to use it

**Comment by def-** [comment]
slou ingame writes:

> antiping stops working often after players touch no hit tile

@trml Could you look into these issues?

**Comment by def-** [comment]
On DDNet Discord in #bugs this bug is being reported again for no collision tile, with version 15.2.3 including the #3276 fix. So it didn't suffice:
![screenshot-20201125@190059](https://user-images.githubusercontent.com/2335377/100265483-9cd49a00-2f50-11eb-830c-a2c1087abcfc.png)

**Comment by trml** [comment]
@def- Will try to fix it. To fix the previous bug I made the client only use ddnetcharacter to predict collision, but it turns out that these maps don't set the character flags (and only relied on tunings), so there has to be a server fix too.
