### ISSUE TITLE
Feature Suggestion: Smooth Spectate (spectate_next/previous/etc)

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#2513]
ayy

**Comment by Learath2** [comment]
Should be possible with the new curves we have, interpolating to the target tee. One issue I had while thinking about this was how to guarantee that the interpolation ends in finite time. E.g. the tee could be going too fast for the camera to catch up ever.

**Comment by C0D3D3V** [comment]
This is a subset of the request in #3750 
Here is only asked for a smooth transition between different spectator position, #3750 would make everything smooth?
