### ISSUE TITLE
Bug: Ninja slash would cross unsolo tiles without triggering unsolo

### ISSUE THREAD

**Issue by Nyte-BK201** [ddnet/ddnet#2516]
This leads to failure in some maps for example moderate minion TELE 5.
Haven't test if solo can be skipped as well.

**Comment by Zoozti** [comment]
That behaviour is known and is also used in many maps.
Any unsolid tile except kill can be skipped.
Watch wiki.DDNet.tw which explains it

**Comment by Nyte-BK201** [comment]
I see. So basically, it is a tick resulting behavior the same with falling speed >32 unit would trigger a wrong teleport/ skip a freeze tile.  This is somehow weird and funky though.

**Comment by heinrich5991** [comment]
No, it's a bit different. For the game code, you're essentially teleporting between positions when using Ninja. You can skip through teleporters with this; you can't¹ skip through teleporters with enough speed.

¹ You can trigger multiple teleporters in a row, effectively skipping a teleporter and trigger a one that is not in the front row, but you can't go through teleporters entirely unaffected.

**Comment by Nyte-BK201** [comment]
> No, it's a bit different. For the game code, you're essentially teleporting between positions when using Ninja. You can skip through teleporters with this; you can't¹ skip through teleporters with enough speed.
> 
> ¹ You can trigger multiple teleporters in a row, effectively skipping a teleporter and trigger a one that is not in the front row, but you can't go through teleporters entirely unaffected.

That's more even weird that you can skip a freeze tile but not a teleport tile with enough speed

**Comment by Zoozti** [comment]
Nah, you cant skip freeze by speed

**Comment by Learath2** [comment]
This is because of the naive implementation being fixed later by another
naive fix and the mappers relying on the odd behaviour of both
implementations. Now it's impossible to fix
