### ISSUE TITLE
Clarify licensing of existing skins

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#2518]
https://heinrich5991.de/teeworlds/ddnet/2020-08-18-skins.csv

Generated by `cat skins.csv | xsv select author | tail +2 | sort | uniq -c | sort -rn`.

- [x]     30 Whis: CC-BY (~via [Discord](https://discordapp.com/channels/252358080522747904/293493549758939136/734187639762321480)~, first one was an impostor, now really via Discord PM)
- [x]     17 Teeworlds: zlib (https://github.com/teeworlds/teeworlds/blob/aecb97fa0a7c61e9cc241b602191134415404016/license.txt) 
- [x]     16 forsaken (https://forum.ddnet.tw/viewtopic.php?t=5932): CC-BY-SA (via Discord PM)
- [x]     15 Ravie: CC0 (via [Discord](https://discordapp.com/channels/252358080522747904/293493549758939136/734189606672531487))
- [x]     15 DanilBest (https://forum.ddnet.tw/viewtopic.php?t=5967): CC-BY-SA (via Email)
- [x]     12 eb3580f257da9f74864fb3e10fe7a8fbe7cd668e: CC-BY-NC-SA (https://www.teeworlds.com/forum/viewtopic.php?id=1016, by Lappi)
- [ ]     11 Moby Dog
- [x]      3 Miper: CC-BY-SA (via Discord PM)
- [ ]      1 ghost
- [ ]      1 fe789f3b788486be9545486ac999a98b75d05922
- [ ]      1 e5a2f5412e6783021549aa776e56b7a5149c6f5c
- [ ]      1 e3559581b2e0c3ebe8ec690a038c801e340a3027
- [ ]      1 chew
- [x]      1 btd: zlib (inherited from DDRace)
- [ ]      1 a8ad349ed81d4d839afbd3abc6852da0743276f2
- [ ]      1 Why
- [ ]      1 Patwo.*
- [x]      1 Obst (9e3cd7836969ee2a90515e84361d6b61f71a4a91): zlib (inherited from DDRace)
- [x]      1 Aoe: CC0 (via Discord PM)
- [ ]      1 7a5935d298e112aef1b1d20d1a8e9d18b9d66dff
- [ ]      1 0549e1ef62e6a8eb8589fb8e3f4a76a498d4f360

Others, currently not packaged:

- [x] Soreu: CC-BY-SA ([via Github](https://github.com/ddnet/ddnet/issues/2518#issuecomment-660549358))

**Comment by heinrich5991** [comment]
Thanks! @Ekidoxx

**Comment by def-** [comment]
Time to act on this. Let's set a deadline, like 1 week from now, and then remove all skins that have no licence.

**Comment by heinrich5991** [comment]
Permission given by Moby Dog to distribute the following skins:
```
Ablush Neon.png
Apish Coke.png
Armour Fels.png
Evil Puffi.png
Flying Silex.png
Freakin Bloody.png
Heinrich The Phantom.png
Hidden Assassin.png
Irradiated Sunny.png
Jigsau.png
License.txt
Mobys Skull.png
Muuuh.png
Mystic Ultranoob.png
Unfinished Clown.png
```

[procodex skinstorage.zip](https://github.com/ddnet/ddnet/files/5075420/procodex.skinstorage.zip)
