### ISSUE TITLE
(External) recording tool for demos

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#252]
Probably using ffmpeg or x264 directly. @Learath2 was working on this, but gave up.

I believe it would be nice as an external tool, but I'm not sure.

The important parts are:
- Easy to use for normal people (GUI?)
- Easy to set resolution and fps (25,30,60)
- No need to download 30 MB ffmpeg for every DDNet client user

**Comment by ardadem** [comment]
@def- you may want close it

**Comment by def-** [comment]
Oh right, we have this by now. Just have to keep working on my custom ffmpeg build and then I'll include it in all official client builds.
