### ISSUE TITLE
May install tools to /usr/libexec

### ISSUE THREAD

**Issue by yangfl** [ddnet/ddnet#2520]
https://github.com/ddnet/ddnet/blob/127e4e643dd40e617221e62e268daef3512a92b6/CMakeLists.txt#L2280

According to [FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s07.html) it's better to put internal binaries under /usr/libexec, but it can be discussed.

**Comment by edg-l** [comment]
I don't even have that dir on arch

**Comment by heinrich5991** [comment]
From your source:
> /usr/libexec includes internal binaries that are not intended to be executed directly by users or shell scripts.

That is not the case for the tools installed by DDNet, they're only there to be directly executed by the user.
