### ISSUE TITLE
Doors without having switch layer are always opened

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#2526]
As everybody knows, doors can be placed using game, front and switch layer. Doors placed by any other layer than switch are always closed, but if the map does NOT contain a switch layer, then they will always be opened.
Is this a bug or intended behaviour?

**Comment by def-** [comment]
The implementation works by checking for switch layer existance to initialize the data structures, so this is expected.

I'd keep it as is, physics changes and all that.

**Comment by AssassinTee** [comment]
@def- please reopen, because doors are rendered as closed but you can pass through them.

**Comment by Robyt3** [comment]
This should be fixed. See https://github.com/ddnet/ddnet/issues/12000#issue-4160567541.

**Comment by KebsCS** [comment]
> Needs a scan of ddnet-maps to check if there are any with door tiles in the game or front layer but no tiles with non-zero number in the switch layer (or no switch layer at all) to make sure that fixing this doesn't change their behavior.

I ran a scan on all ddnet maps, and the only map that has it is `mo_factory` on oldschool

<img width="678" height="383" alt="Image" src="https://github.com/user-attachments/assets/ed13fce1-9dd7-493a-a024-ba62a0fac8bf" />

**Comment by KebsCS** [comment]
Map above got fixed https://github.com/ddnet/ddnet-maps/commit/44ffdeead624e4ae659ceb5a1b499f392eecc8f5#diff-c8a140425d6fc49ad0f3b1dd15c09ca5d9505d38200867768a339f55cfb0077c
