### ISSUE TITLE
save/load saves who had strong/weak before now

### ISSUE THREAD

**Issue by Zoozti** [ddnet/ddnet#2528]
which is a very bad behaviour. There are often parts that are MUCH harder with weak where u cant swap now.
People which finished in the past and were able to swap weak/strong now have an unfair advantage because people cant do that anymore. I dont see the use of saving who has strong since there is a penalty already anyway.
This must be reverted

**Comment by heinrich5991** [comment]
Can you give an example of a map where the load/save penalty of 1 minute is worth it for swapping weak/strong?

**Comment by heinrich5991** [comment]
Also, please be more mindful of your language. I'll close the next issue with stuff like "This must be reverted". You can say something like "I think this should be reverted".

**Comment by Zoozti** [comment]
Like every map that contains rocketfly or similiar things? I just played today the map Firedelay and needed 20 minutes for a part that could be first try if i had strong.

Did you ask the community when u added that pr?
Because i dont think it should be reverted. It Definitely must be, i cant say it weaker
