### ISSUE TITLE
CC-BY-NC-SA skin license

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#2547]
> lightbulb, tank, emo, bunny, hedgehog, napoleon, roman, caesar, nosey, savage:
> Copyright Lappi
> CC-BY-NC-SA license

I would argue that CC-BY-NC-SA is too restrictive. It certainly does not line up with the rest of ddnet's source and data licenses. Unless Lappi re-licenses, we should delete these skins.

**Comment by heinrich5991** [comment]
I'd prefer to keep the skins.

**Comment by def-** [comment]
Same, let's keep them.

**Comment by d3fault** [comment]
it effectively adds a NC clause to the whole of DDNet when distributed as a .zip or other bundle. this contradicts the permissive zlib/BSD licenses.

related: I wanted to keep the Sonic skin, but licensing issues made me understand why it needed to be dropped

**Comment by def-** [comment]
@heinrich5991 do you know how to reach Lappi maybe? We could ask for a relicense?

**Comment by Learath2** [comment]
We could also skirt this issue by letting the client download skins as required from the skin db?

**Comment by d3fault** [comment]
> We could also skirt this issue by letting the client download skins as required from the skin db?

that would be awesome. going even further, would be nice if clients could use whatever skins they wanted and it was automagically distributed (through server I suppose, p2p is psbl but harder because ports) to everyone else in the server

**Comment by Learath2** [comment]
One thing I'd be concerned about with letting people use any skin they want
is the obvious swastika tee issue

**Comment by heinrich5991** [comment]
@yangfl Would adding a cmake option to not install stuff under NC work? Where can I read that ND is problematic?

**Comment by yangfl** [comment]
It's not only about the installation process, but the source code tree. Info about non-free NC/ND https://www.gnu.org/licenses/license-list.html#NonFreeDocumentationLicenses

**Comment by heinrich5991** [comment]
Debian publishes its own source code tree, would a script to remove NC/ND skins from the source tree work?

**Comment by yangfl** [comment]
Yes there is, but it would be better and more appreciated for upstream to remove them in the source tarball, so that downstream don't have to modify the tarball.

**Comment by Learath2** [comment]
If we merge #2733 we can also stop shipping these and let them be fetched at runtime
