### ISSUE TITLE
Opengl3 causes text entities to render as black blocks

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2551]
Noticed locally, Im 'corneum has the same issue.

**Comment by def-** [comment]
@Jupeyy any ideas?

**Comment by Jupeyy** [comment]
Cannot reproduce without LIBGL_ALWAYS_SOFTWARE=0 nor with LIBGL_ALWAYS_SOFTWARE=1

Do you mean these, or other things? @def- 

![screenshot_2020-08-10_20-27-05](https://user-images.githubusercontent.com/6654924/89817172-ff438f00-db47-11ea-929c-645a86423f58.png)

**Comment by def-** [comment]
Weird, the issue disappeared today. Had it yesterday during tournament and couldn't read the CP numbers because of it. Today they look fine.
Edit: Ok, found out what's causing it. Changing cl_text_entities_size while the game is running makes it black. Should be easy to reproduce now.

**Comment by Jupeyy** [comment]
btw double of #2438
