### ISSUE TITLE
RFC: Move out the libraries to another repo

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#256]
DDNet's repo is inflated in size by having all these libraries inside, that are only required for some use cases. It may make sense to move them to another repository and somehow pull that in when they're required?

I'd be a bit worried that it complicates the building process, so not sure. Request for comments.

**Comment by Zwelf** [comment]
Henningstone and me created an automatic download of sdl and freetypes.
See https://github.com/teeworlds/teeworlds/pull/1347

**Comment by def-** [comment]
This looks good. Interested in making it work with all the libraries we have in the `other` directory, so that it just pulls the necessary files for the current compilation, and make a PR?

**Comment by Zwelf** [comment]
Yes, I'd like to work on that.

**Comment by def-** [comment]
Done.
