### ISSUE TITLE
sv_sql_failure_file is not being respected anymore

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2569]
I noticed that ddnet-server.sqlite contains both regular ddrace as well as block entries now. We use a separate server for the block server ranks. Maybe we should just use the same server for both instead?

**Comment by Zwelf** [comment]
The fallback sqlite file is now specified with `sv_sqlite_file`. I would suggest rename the block database to something like `sv_sqlite_file ddnet-block.sqlite`. But I have no opinion whether just the same database should be used (would this mix up points?)

**Comment by def-** [comment]
I don't think we have points on block. I just didn't want to polute the real DB with block finishes.
