### ISSUE TITLE
Auto-download skins from DDNet DB

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#257]
http://ddnet.tw/skins/ contains a lot of skins that could be automatically downloaded during game. @eeeee has an implementation for that for teewebs (which he wanted to make a PR with) and so does @CytraL for H-Client.

**Comment by eeeee** [comment]
My PR was for dynamically loading skins from disk, not from http

**Comment by def-** [comment]
Oh, then I misunderstood. Still a good idea for people who have many skins and low RAM.

**Comment by CytraL** [comment]
can keep selecting them in skins panel?

**Comment by Learath2** [comment]
Dont we only load the active skins to ram after eeeee's commit

**Comment by CytraL** [comment]
And this is good?
