### ISSUE TITLE
Teamchat messages twice when dummy is in pause

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#259]
The client doesn't know the difference between /pause and actual spectating, so when it recieves a teamchat message and the dummy is in pause, it prints it twice.

**Comment by FallenKN** [comment]
A workaround could be to check if the message above is same with the message we are going to print. Could be used to prevent "spam" aswell, but it would be a 'hackish' solution.

**Comment by def-** [comment]
Yeah, you could add a little number next to the text to show how often it has been repeated.

**Comment by heinrich5991** [comment]
The proper fix would be to tell the client about its spec'ed state instead of fixing it up on the client side again.
