### ISSUE TITLE
/pause not saving the previous cursor position

### ISSUE THREAD

**Issue by Nyte-BK201** [ddnet/ddnet#2591]
If you paused and move your view pos then unpause, you will have your cursor position moved to an unpredictable position. This causes failure when pause to look out and unpause.

A possible fix is that in client-side, detect "/pause" in chat to save cursor position and load when another "/pause" is detected. This fix could have your cursor not in that very last second of your pause if you have a high ping. But it is a quick fix which does not affect server-side.

**Comment by fokkonaut** [comment]
Needs a serverside fix

**Comment by def-** [comment]
Skeith says:

> Seems to only happen if your hammer is facing to the left, if your cursor is anywhere on the left side of your screen, it'll reset it to the bottom center. From my testing

**Comment by C0D3D3V** [comment]
I also noticed this. But I did not have time to debug it yet

**Comment by saltyElefant** [comment]
Also true for /spec. If your cursor is to the left of your tee, it will get moved to the bottommost position after /spec or /pause.
