### ISSUE TITLE
Alt tabbing hang issue

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#2599]
My game hangs time to time after switching to other window and back. But I didn't know how to reproduce it till today.

Now I know that I can easily reproduce it by clicking many times on "Borderless window" toggle

Didn't managed to record this bug via obsstudio, phone cam helped - https://vimeo.com/user121620494/review/449001565/2f9adc954d

**Comment by fokkonaut** [comment]
Its due to resolution change, set Teeworlds' resolution to the same you are using on your os, then it shouldnt hang

**Comment by BannZay** [comment]
But I already use the same resolution as my os. 
![displaysettings](https://user-images.githubusercontent.com/17499770/91437797-1d60fd00-e873-11ea-8804-e92173cb618e.png)

Monitor 1 is not in use. "Show only on 2" selected

**Comment by def-** [comment]
Might be a problem with the refresh rate chosen in relation to multiscreen?

**Comment by BannZay** [comment]
Hmm? is this question for me ?  Refresh rate for monitor 2 is 60 Hz

**Comment by BannZay** [comment]
@def- I have not face this problem for a long time already, should be closed I guess. Seems like was fixed somewhere.

Not sure if #2897 is related. Will see if it bring this issue back.

**Comment by BannZay** [comment]
I mean I can still reproduce it by spamming "Borderless window" but it does not affect normal gameplay anymore
