### ISSUE TITLE
3D textures and 2D array textures

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#2607]
So 0.7 teeworlds uses 3D textures, they are in OpenGL since version 1.2.

They use them because of texture bleeding in texture atlases(as in current ddnet source for older opengl). But they weren't made for this purpose(as its name suggests.. its for interpolating in a third dimension) and that's why 0.7 had to disable mipmapping for them(means lower resolutions interpolate the texture, instead of using a prepared mipmap).
This generally isn't really a problem, tw isn't very power hungry and the visual difference isn't too huge.
(Another advantage of both of them is, that it'd be easier to enable buffering for older OpenGL contexts aswell)

Tho i'd like to implement them too, for my current pr #2598, i use 2D texture array for OpenGL 3.3+.
2D texture arrays are core since OpenGL 3.0.
Their advantage is simple: mipmapping and their are garantueed to have a depth of atleast 256... since teeworlds has exactly 256 tiles in a tilemap, that fits perfectly.

So i'd of course be nice to have 2D array textures as default, that means my question is:
Should we try to make OpenGL 3.0 default and do anything < 3.0 as fallback.
I know that there are drivers out there that are really restrictive and broken, i searched the internet a bit, that's what i found:
from https://opengl.gpuinfo.org/listcapabilities.php:

Around 97+% 2D array textures seem to be supported:
https://opengl.gpuinfo.org/displaycapability.php?name=GL_MAX_ARRAY_TEXTURE_LAYERS

Tho since OpenGL 3.0 core GL_MAJOR_VERSION is requestable and only 84% support that..
So either that report is broken or almost 16% implement texture arrays as an extension.

Regarding the fallback:
glGet*(GL_MAJOR_VERSION) should either fail, or give the major version, so that would be an additional fallback option
(https://www.khronos.org/opengl/wiki/OpenGL_Context#Context_information_queries)

Additionally glGetString(GL_VERSION) will return 'The string returned starts with "\<major version\>.\<minor version\>". ' and is available in older OpenGL versions.. another fallback.

I could implement these all, but would really like to hear an honest opinion from @def- @heinrich5991 @Learath2 @edg-l

**Comment by def-** [comment]
The 2D texture arrays sound quite nice. Do they improve performance significantly?

Should I test your PR on some 2009 era laptops to see if it works on Linux and Windows?

My fear with this is that it might look slightly different and people will be annoyed at every change. Also, that there will be more people with graphics problems. We already seem to have a few all the time. I guess the main question is how much benefit do we expect from this for the average player and is it worth annoying a small percentage because of that.

**Comment by Jupeyy** [comment]
the biggest problem is, that we still require the border fix tool, while 0.7 already has a solution for it.

it won't improve performance by itself, but it will enable buffering for opengl 2.0+, and that will probably improve performance just like 3.3+ does.

it will look different yes, but it will be consistent, independend of the zooming level or the resolution

It will always look like the left

![screenshot_2020-08-20_23-30-31](https://user-images.githubusercontent.com/6654924/90828026-91644800-e33d-11ea-8b86-cbceb01c76ca.png)

While the current behaviour for older GL is pretty much undefined, because the texel offset calculation is wrong, it will now always use the full tile

so more consitency for future mapping, etc.

Also i'll ofc create OpenGL 2.0 with 3D textures, the question is, how secure would it be to try to create a OpenGL 3.0(has nothing todo with OpenGL 3.3) context and fall back to 2.1 if that fails.

Because else the people won't go in graphic settings and change something

**Comment by Learath2** [comment]
This dotted appearance is IMHO very ugly

**Comment by Jupeyy** [comment]
@Learath2 this is actually on the entities.png

**Comment by Jupeyy** [comment]
Maybe this makes it clear(view images in new tab at real resolution):

New:
![screenshot_2020-08-21_00-20-55](https://user-images.githubusercontent.com/6654924/90831553-4699fe80-e344-11ea-8ba1-979761712d95.png)

Old:
![screenshot_2020-08-21_00-20-59](https://user-images.githubusercontent.com/6654924/90831557-4863c200-e344-11ea-9224-7fe4975c4a3d.png)

**Comment by fokkonaut** [comment]
Finally, and so much better than the old behaviour

**Comment by def-** [comment]
Yeah, new looks much better to me. Fine from my side. @heinrich5991 @Learath2 agreed?

**Comment by Learath2** [comment]
Certainly looks much better, fine for me too especially since we can have fallbacks anyway.
