### ISSUE TITLE
Submit DDNet to some Distributions, App stores

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#261]
- ~~Trying Debian already: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794166~~ (in Debian now)
- Further Linux distributions (CentOS/Fedora, SUSE, ~~Archlinux~~, Gentoo) and the BSDs
- Windows store?
- ~~Some Mac thing?~~ (too expensive)
- ~~Android store? (25 $ is ok-ish)~~ (no up-to-date Android version of DDNet)

**Comment by CytraL** [comment]
- Mac: 99$/year
- Android: 1 pay of 25$
- Windows: idk when the app is free

**Comment by nzyuzin** [comment]
DDnet is in AUR already.

https://aur.archlinux.org/packages/teeworlds-ddnet/

**Comment by Learath2** [comment]
I'll submit a package for gentoo. They seem to have some obsession with using system libraries so it might take me some time to patch it up.

**Comment by itsrachelfish** [comment]
@def- Does any work need to be done to get DDnet approved in Debian? I see that ticket has been open since 2015

**Comment by def-** [comment]
No idea. I didn't find any better way to suggest a Debian package. If you can find one, please do it or report back.

**Comment by heinrich5991** [comment]
Arch Linux AUR package now lives here: https://aur.archlinux.org/packages/ddnet.

**Comment by def-** [comment]
RafaelFF tried ArchLinux: https://lists.archlinux.org/pipermail/aur-general/2018-February/033878.html

**Comment by def-** [comment]
We're in Debian now: https://tracker.debian.org/pkg/ddnet

**Comment by itsrachelfish** [comment]
@def- This is great news!! Thank you for your hard work

**Comment by def-** [comment]
Getting DDNet into Debian and thus Ubuntu was not my work, credit goes to @yangfl and SZ Lin.

I guess I'll close the issue now, seems good enough, other distributions might pick us up organically or not.

**Comment by ChillerDragon** [comment]
Why is mac too expensive what about ``brew`` and ``macports``

**Comment by ChillerDragon** [comment]
Ye i understand the high cost problem. I was only talking about the free package managers i have no idea how hard it is to submit something there but i can try c:

**Comment by ChillerDragon** [comment]
![homebrew](https://user-images.githubusercontent.com/20344300/45539747-e8d11380-b80a-11e8-8958-49f6aeebef16.png)

Homebrew seems to dislike auto updates. But macOS ddnet client doesn't support it anyways or is it planned in the future?

**Comment by def-** [comment]
Of course if you are using a package manager then the auto-upgrade is useless and should be disabled. We can add an #ifdef for that in the code that package managers can toggle through cmake.

**Comment by heinrich5991** [comment]
Heh, @def- thought of the same thing. ^^ #1292

**Comment by ChillerDragon** [comment]
Oh and i think classic brew is designed for cli tools not gui games.
Maybe we should try the binary version named brew cask? What do you think?

https://github.com/Homebrew/homebrew-cask

**Comment by Learath2** [comment]
brew-cask does allow apps that update themselves

**Comment by Tardo** [comment]
Fragmented security... how many repos exists for generate the same binary? For me nothing is best that download game from the source.
