### ISSUE TITLE
Pinyin tab completion

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2621]
Would requite a pinyin to unicode mapping, see https://unicode.org/reports/tr38/

**Comment by Robyt3** [comment]
Who exactly does this help? If you can't read Chinese names to begin with, then how do you figure out what to write in pinyin to get the player name you are looking for with tab completion? And if you can read a Chinese name, then you probably know how to write it in pinyin, so you could just use the IME to convert pinyin to Chinese directly.

And what about all the other non-latin scripts?

**Comment by Learath2** [comment]
I don't see much value either, especially with the massive table we need to include.

However lookalike completion for cyrillic would actually be cute :D

I wonder if there is some standard for this.
