### ISSUE TITLE
Tool to diff maps

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#263]
Sometimes a map bug is fixed and we want to verify that no cheat was added (long story here: http://forum.ddnet.tw/viewtopic.php?f=3&t=1759). A simple tool that accepts 2 maps and shows where the differences are, would be invaluable to have. @Chairn is working on this I believe.

**Comment by CytraL** [comment]
Chairn are you still working on it?

**Comment by Chairn** [comment]
I am, slowly, but i am.

**Comment by def-** [comment]
This was added as map_diff.
