### ISSUE TITLE
Have the server sort default to some combination of number of players and ping

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2633]
As suggested by nuborn on Discord.

Maybe servers with players with ping < 100 first, then servers with players with < 200 etc., same with empty servers after all servers with players.

**Comment by trml** [comment]
Was thinking about perhaps a score based on a combination of both (with the lowest scores to empty servers). For example something like "log2(players + 1e-20) - ping/25" that would give equal weight to a doubling of players and a decrease of ping by 25.

**Comment by def-** [comment]
Sounds good too. The next problem is how to display this in the GUI

**Comment by trml** [comment]
The easiest would perhaps be something like having three sort orders for Players and Ping, and maybe highlight both on the combined sort? (was trying out something like that now). Also thought about a separate GUI element, but not sure where the best location would be (without using a column).

**Comment by def-** [comment]
Yeah, I guess a third click can make the fields for ping and players light up in yellow or something to show that it's the special sort. Do you want to implement this @trml ?

**Comment by trml** [comment]
I can do that, yes.
