### ISSUE TITLE
Enabling DNSBL banning should not ban IPs that are playing already, only new ones

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2640]
There are quite a lot of people getting banned by DNSBL actually. I can't imagine they are all evil. Do we really need to always run DNSBL and disallow joining server?

I have disabled dnsbl banning for now, I think we should only make it ban newly joining ips (careful not to ban when dummy joins) and then allow moderators to enable it.

Update: Mods say that DNSBL banning is quite good, so maybe we don't need this after all. Opinions?

**Comment by Learath2** [comment]
Well mods will have to be able to enable it on all servers at the same time
as ban evaders just serverhop

**Comment by def-** [comment]
Seems a bit too annoying

**Comment by Robyt3** [comment]
Should this apply only to `sv_dnsbl_ban` or all `sv_dnsbl` functionality?

**Comment by murpii** [comment]
> Should this apply only to `sv_dnsbl_ban` or all `sv_dnsbl` functionality?

Just to `sv_dnsbl_ban`, in my opinion. Chat/Vote bans aren't too severe and don't end people's runs.
