### ISSUE TITLE
Vote to move players to freeze instead of kicking?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2641]
Kasia suggests so that newcomers don't get kicked when they have trouble doing a part and are considered to be blocking. They can then still watch how the part is done when frozen.

**Comment by heinrich5991** [comment]
Thoughts:

More prone to abuse, because it funvotes with it aren't as damaging.

Needs to be implemented separately from in-game freeze, otherwise it could be used to cheat.

**Comment by def-** [comment]
Yeah, seems a bit too complicated.
