### ISSUE TITLE
Use Steam API to provide links to join to another player

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2642]
We already support running `DDNet ddnet:ger.ddnet.tw:8303`.

@heinrich5991 recently added Steam API support, so I think this can be extended more easily now: https://github.com/ddnet/ddnet/pull/2615

**Comment by Learath2** [comment]
I did some research on this but it's apparently not that trivial. Seems we'll need to implement the steam gameserver api on the servers to get this to work.

**Comment by def-** [comment]
Too bad, I hoped just a link would be fine.

**Comment by Learath2** [comment]
Atleast I couldn't find it in the api docs
