### ISSUE TITLE
Mouse not trapped in DDNet window after game start

### ISSUE THREAD

**Issue by thomasjahoda** [ddnet/ddnet#2645]
Every single time I start the game using Steam (haven't tried somewhere else) the mouse is not responsive. I first need to click so the mouse is usable. I have no extra cursor while the mouse is not trapped and alt-tab does not work for some reason during the same time. If other Windows 10 Steam users like me have this issue, this is a **bad first impression for the common newbie**.

Some additional info that may help:
* The Steam overlay notification "Access the Steam community while playing" only appears after the mouse is trapped.
* The screen is visible directly after starting the game without having to click in the task bar or anything. I just have no control over my PC until I do a mouse click.

Some system info in case this bug is not easily reproducable:
* Windows 10, Intel, Nvidia
* Graphics settings: default (which means fullscreen)
* No interfering background programs like Teamviewer are running.

Possible duplicate of https://github.com/ddnet/ddnet/issues/2091

**Comment by def-** [comment]
I get this only just after I updated the client when using the version from ddnet.tw. Do you get this on every start?

**Comment by Learath2** [comment]
This happens on macOS on every start too, couldn't debug it either

**Comment by def-** [comment]
@thomasjahoda @Learath2 please try the build artifact from https://github.com/ddnet/ddnet/pull/2654
> Could you test this with the build artifacts from Github builds, by putting the DDNet.exe into steam directory and launching DDNet from Steam?

**Comment by thomasjahoda** [comment]
@def- Can confirm that this fixes the issue consistently. Thanks for the quick fix!

**Comment by def-** [comment]
Great to hear. Thanks for reporting this so well!
