### ISSUE TITLE
Graphics broken for many players with 14.5 update

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2659]
@Jupeyy 

Got many reports today of broken graphics, had to revert the update back to 14.4.1. Attached some screenshots from Discord.
![4](https://user-images.githubusercontent.com/2335377/91337877-55653300-e7d4-11ea-8f1e-49df7e11c9c5.jpg)
![3](https://user-images.githubusercontent.com/2335377/91337881-56966000-e7d4-11ea-9fc5-73b548fc0097.png)
![2](https://user-images.githubusercontent.com/2335377/91337883-572ef680-e7d4-11ea-9ba4-44d3c37cc81c.png)
![1](https://user-images.githubusercontent.com/2335377/91337885-572ef680-e7d4-11ea-9b7c-44f2c53e28cb.png)

**Comment by Jupeyy** [comment]
1 and 4 already reported its fixed by replacing their broken custom entities.

2 probably same

3 is fixed with background map loading

**Comment by Jupeyy** [comment]
Ofc I can resize their broken entities to deniable by 16 , but the resize is never as great as gimp resizing

**Comment by Jupeyy** [comment]
Ok wrote a patch that resizes the image, but resizing is defs a problem, because of the interpolation, e.g. resizing the original entities by 2 pixels will then resize it to this ingame:

![screenshot_2020-08-27_01-56-16](https://user-images.githubusercontent.com/6654924/91368169-b0188200-e808-11ea-8a06-7eb887e16275.png)

(sampled the red From tele tile)

But atleast no black textures anymore

**Comment by Learath2** [comment]
How does the size of the tilemap end ip wrong in the first place? Is it
that the tiles are not of the correct size? I don't see how that could
happen.

**Comment by Jupeyy** [comment]
custom entites, ofc that doesnt happen with the default tilemap :D

**Comment by def-** [comment]
Maybe we should just show an error message instead if the entities are not divisible by 16. Sorry, somehow I missed that this could all be caused by the entites bug and I didn't even know so many people play with entities all the time.

**Comment by Learath2** [comment]
> custom entites, ofc that doesnt happen with the default entities tilemap :D

Yeah, but what is actually happening? The tiles can't be of the wrong size. Are there too few tiles? Could we just pad the image?

**Comment by Jupeyy** [comment]
Well if you have 17 pixels in a row and 16 tiles in a row, you have a problem :D
bad or resize makes no difference.. you cannot know where the padding have to be inserted without analyzing the image

**Comment by Learath2** [comment]
Oh, I know we can't fix it automatically. I was wondering the human aspect
of it. Like how this happened in the first place :D

**Comment by def-** [comment]
They download the image that discord/forum scaled instead of clicking on "Original image"

**Comment by def-** [comment]
I'm not entirely convinced only entities are broken, see for example this thread: https://steamcommunity.com/app/412220/discussions/0/2923353981917186378/

**Comment by Jupeyy** [comment]
we'll see when he answers, but for the 2 cases they can also manually downgrade to opengl 1.
a fallback cannot fix a broken driver

**Comment by def-** [comment]
That seems hard for newcomers to find out. Can't we detect if the graphics is broken somehow?

**Comment by Jupeyy** [comment]
I honestly dunno, atleast no not dirty hack i think, like drawing a test tilemap and analyzing the image data from the framebuffer(like taking a screenshot of it)

And if you want to stay with the old renderer, I'm ok with that too, you just need to be clear about it

**Comment by def-** [comment]
The new renderer seems to be better in a few ways, but for me there are just 2 issues remaining, and if they can be fixed I'd totally support the upgrade:

1. Some drivers are buggy, we should detect that (I'd be ok with your hacky solution) and auto-downgrade to lower opengl versions for those
2. Looks slightly blurrier (less important)

**Comment by PathosEthosLogos** [comment]
I believe this issue can be closed now.

**Comment by Ekidoxx** [comment]
@def- 
[Entities by Soreu - 30.08.2020.zip](https://github.com/ddnet/ddnet/files/5146169/Entities.by.Soreu.-.30.08.2020.zip)
Not dilated nor optimized in any way.

**Comment by def-** [comment]
Thanks, will add!
