### ISSUE TITLE
libsteam_api.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Mailaender** [ddnet/ddnet#2669]
I just packaged this for @openSUSE games, but I get this on startup:

> DDNet: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory

Note: I don't have Steam installed at the moment.

**Comment by heinrich5991** [comment]
We build a libsteam_api.so. If you use `make install`/`ninja install`, it should end up in /usr/lib/ddnet/libsteam_api.so. How do you install it? What does `readelf -a DDNet | grep -i rpath` output?

**Comment by Mailaender** [comment]
I didn't use ninja. `readelf -a /usr/bin/DDNet | grep -i rpath` does not output anything. See https://build.opensuse.org/package/show/home:Mailaender:branches:games/ddnet

**Comment by def-** [comment]
Very nice that you're packaging for openSUSE!. Is the file maybe called steam_api.so?

**Comment by Mailaender** [comment]
It is called `/usr/lib64/ddnet/libsteam_api.so` and it is also installed on the system.

**Comment by def-** [comment]
Ok, then it seems like the rpath is indeed missing. @heinrich5991 Any idea how to fix that cleanly?

**Comment by Mailaender** [comment]
There is a policy against it: https://en.opensuse.org/openSUSE:Packaging_checks#Beware_of_Rpath

**Comment by def-** [comment]
I see:

> Often, rpath is used because a binary is looking for libraries in a non-standard location (standard locations are /lib, /usr/lib, /lib64, /usr/lib64). If you are storing a library in a non-standard location (e.g. /usr/lib/foo/), you should include a custom config file in /etc/ld.so.conf.d/.

Not sure if we want to keep the trouble of having a libsteam_api.so stub

**Comment by heinrich5991** [comment]
As I understand it, putting it into /etc/ld.so.conf.d would make it a global shared object, something we wanted to avoid, because other people might be building something called libsteam_api.so. I'll try statically linking it instead for openSUSE.

**Comment by def-** [comment]
> I'll try statically linking it instead for openSUSE.

Or for any non-steam release?

**Comment by Mailaender** [comment]
That fixed it. Submitted it to @openSUSE games now: https://build.opensuse.org/request/show/830880
