### ISSUE TITLE
DDNet Crashes on Ubuntu 15.04

### ISSUE THREAD

**Issue by imcaffrey** [ddnet/ddnet#267]
When I was trying to connect to a server,it told me like this

```
[15-08-01 21:13:43][client]: loading map, map=Mountain_Shadow wanted crc=682c1a94
[15-08-01 21:13:43][datafile]: loading. filename='maps/Mountain_Shadow.map'
[15-08-01 21:13:43][datafile]: could not open 'maps/Mountain_Shadow.map'
[15-08-01 21:13:43][datafile]: loading. filename='downloadedmaps/Mountain_Shadow_682c1a94.map'
[15-08-01 21:13:43][datafile]: could not open 'downloadedmaps/Mountain_Shadow_682c1a94.map'
[15-08-01 21:13:43][client/network]: starting to download map to 'downloadedmaps/Mountain_Shadow_682c1a94.map'
[15-08-01 21:13:43][fetcher]: Thread started...
[15-08-01 21:13:43][fetcher]: Task got http://maps.ddnet.tw/Mountain_Shadow_682c1a94.map:downloadedmaps/Mountain_Shadow_682c1a94.map
[15-08-01 21:13:43][fetcher]: Downloading downloadedmaps/Mountain_Shadow_682c1a94.map
[15-08-01 21:13:45][fetcher]: Task failed. libcurl error: name lookup timed out
```

and after I restarted the client, the log in terminal showed this and the client crashed.

```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  4 (X_DestroyWindow)
  Resource id in failed request:  0x440000f
  Serial number of failed request:  139
  Current serial number in output stream:  141
```

Should I provide any other information?

**Comment by Learath2** [comment]
You sure you can resolve maps.ddnet.tw ?

**Comment by def-** [comment]
> You sure you can resolve maps.ddnet.tw ?

Even if maps.ddnet.tw can't be resolved, it should switch to regular map download instead.

**Comment by Learath2** [comment]
True that. One other thing is it reproducible ?

**Comment by imcaffrey** [comment]
@Learath2 @def- 
Yes I can resolve maps.ddnet.tw
I cant say it happens every time. But it happens every week.
So I guess I can say it is reproducible.

**Comment by Learath2** [comment]
Well I couldn't reproducei it here on neither windows nor debian so If you could try using a bogus dns and see if it fallsback properly It would be huge help

**Comment by imcaffrey** [comment]
@Learath2 
I don't quite understand what you mean....
It happened again today,but it doesn't happen every time I use DDNet.
So Im not sure what should I do.
Sorry for the trouble caused.

**Comment by Learath2** [comment]
Its no trouble really. If you could just enter an invalid dns like 127.0.0.1 and try downloading a map it could tell me what is failing

**Comment by imcaffrey** [comment]
@Learath2 
Im using Wifi.I don't have access to the router at the moment....
I'll try tomorrow.(about 16 hours later)

**Comment by Learath2** [comment]
You change your dns on your own computer tho no need to change it from the router.

**Comment by imcaffrey** [comment]
But when I change the dns on my own computer,everything remains the same.Even if I change it to 127.0.0.1.(I'm still able to download maps and face the exactly same problem.)
So I guess I have to change the one on the router.

**Comment by Learath2** [comment]
You change it to 127.0.0.1 and you can still resolve stuff ? Thats weird :P

**Comment by imcaffrey** [comment]
Yeah I understand.I'll try tomorrow.D

**Comment by imcaffrey** [comment]
@Learath2 
It's crazy that even I change my dns server to 127.0.0.1
I am still able to download maps.

**Comment by Learath2** [comment]
You should be able to download maps thats the point. Just check your console it should say something like "HTTP failed. Falling back to gamesever."

**Comment by imcaffrey** [comment]
Oh I meet this everyday.
This sentence does appear.

**Comment by Learath2** [comment]
That means the fallback itself is working the only thing I dont understand is how it could become stuck.

**Comment by imcaffrey** [comment]
@Learath2 
any other information that I can provide?

**Comment by godwhoa** [comment]
Could that extra flag fix this? http://stackoverflow.com/a/21902693

**Comment by godwhoa** [comment]
@Learath2 Found a way to reproduce which was to set dns to invalid server.
Adding `CURLOPT_NOSIGNAL` does fix this making a pull request soon. [demo](https://youtu.be/R2X3jxUBNtc)

**Comment by imcaffrey** [comment]
LGTM. Not sure whether it's fixing. But thanks for your attention @godwhoa
