### ISSUE TITLE
Umlauts stopped working?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2679]
@Jupeyy I just noticed I can't input öäü on Linux. Any idea? Might be related to the font fallback thing.

**Comment by Jupeyy** [comment]
Don't think its related to that, on debian bullseye its working
so its either your locale or arch has a newer SDL version that broke it.

**Comment by def-** [comment]
Hm, no. Actually it only fails in the Steam version, not locally. Maybe something is wrong with the SDL version I build for Steam?

**Comment by Jupeyy** [comment]
ah in steam(not client) i had that too:

https://wiki.archlinux.org/index.php/Steam/Troubleshooting#SetLocale('en_US.UTF-8')_fails_at_game_startup_or_typing_non-ASCII_characters_does_not_work_in_the_Steam_client

had to generate the en_US.UTF-8 then it worked, starting steam in terminal also showed that this locale could not be loaded, but dunno if that affects the client too(maybe bcs of steam overlay)

**Comment by def-** [comment]
Nope, I don't think that's it. Works in Steam itself, only in client it's broken. I'll check out how I build the SDL lib.

**Comment by Jupeyy** [comment]
for me it works in steam

**Comment by def-** [comment]
This gets fixed by building SDL 2.0.12 instead. So maybe something in my up-to-date arch is incompatible with old SDL. Quite annoying.
