### ISSUE TITLE
Warn players when they have overwritten files in $DATADIR

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2680]
We could use the new warning popup for that at startup, it should instruct players where to put the files instead.

The problem is that users keep updating their files in $DATADIR (data/ next do DDNet.exe) and then get angry/confused when the autoupdater changes something. Instead users should have their custom files in $USERDIR ($APPDATA$/Teeworlds, ~/.teeworlds). 

To implement this we could store a hash for each file. This is a bit similar to the consistency check Steam implements as well.

**Comment by Learath2** [comment]
I guess we can use #2748 to track this
