### ISSUE TITLE
Mouse cursor still works ingame when console is open?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2685]
Reported by becc on Discord, can't reproduce on Linux:

> When you open console and click any mouse button, the click will happen in background on the teeworlds-game-cursor, so you could accidentally join a server or something

**Comment by stnwtr** [comment]
**Platform / Client:** Windows 10 (64 bit) with DDNet Client version 14.0.2

**Steps to reproduce:**
1. Open DDNet Client
2. Hover mouse to something clickable like a server list entry or some settings
3. Press F1 to open in-game console
4. A second mouse (the original Windows mouse in this case) appears
5. If you click any mousebutton, the clicks will still be applied to the yellow teeworlds cursor

**Comment by BannZay** [comment]
Thanks for additional description. It allowed me to reproduce the problem

Seems the fix is here: https://github.com/ddnet/ddnet/blob/c05e22d291824749eec877ac0a79ec23c41ec397/src/game/client/components/console.cpp#L762

But I didnt figured out why this code was commented out

**Comment by def-** [comment]
Did you try it, does it fix it?

**Comment by BannZay** [comment]
yes we could just uncomment line 762. I tried it - it worked

**Comment by def-** [comment]
Make a PR?
