### ISSUE TITLE
Official maps show the red texture warning

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2687]
@Jupeyy is it supposed to show for graphics on official maps? Should we go through them and fix all?
![screenshot-20200831@125808](https://user-images.githubusercontent.com/2335377/91713254-b2bd0380-eb89-11ea-9819-0a1c2f96ec37.png)

**Comment by Jupeyy** [comment]
yes, we need to fix those, the warning is only showed on tile layers
and appearently the logo is a tile layer

**Comment by def-** [comment]
My map_convert_07 did not detect this, weird. I have to check why.

**Comment by def-** [comment]
Aaah, what I found out is that for 0.7 only the width has to be divisible by 16. Is it the same for us here or does height also matter?

**Comment by Jupeyy** [comment]
yeah both, maybe they forgot it in 0.7

it has to be a clean tile set:
16x16 tiles
