### ISSUE TITLE
Tutorial and/or "Getting Started" help

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#269]
When the client is started for the first time, we should show the new player around, explain some stuff and show how the game works, potentially with a tutorial map.

Some ideas here:
- http://forum.ddnet.tw/viewtopic.php?t=1942
- http://forum.ddnet.tw/viewtopic.php?t=1941&p=20587#p20587

**Comment by imcaffrey** [comment]
We might also add a "help" function

BTW

I think it might be good if we add some instruction on deleting the searching "Novice ...."  becuase some novice don't understand what they were doing and thought there were only those servers.

**Comment by PathosEthosLogos** [comment]
I think it's important that this stays optional and not forced to fresh installers.

**Comment by Henningstone** [comment]
Yea, some sort of dialog box asking the player "Do you want to play the tutorial now?" after the dialog which asks you for name and language would be appropriate.

**Comment by heinrich5991** [comment]
Language should probably be determined by the environment..

**Comment by def-** [comment]
Being worked on by @timakro

**Comment by def-** [comment]
Some explanation is in the start screen. What I consider as missing:

- The map!
- Info tile from https://github.com/ddnet/ddnet/pull/612
- Server side translation, client has to tell server its preferred language automatically?
- Teehistorian replayer https://github.com/ddnet/ddnet/issues/2937 could be used to show how a part is done

**Comment by Learath2** [comment]
Why not client side translation? To allow custom uses of the info tile?

**Comment by def-** [comment]
Yes, and also because we want to use the same translation framework for things like "You have %d jumps". I guess you could also make that work client-side, but it's more work.

**Comment by def-** [comment]
Case in point for this:

> just starting the game you see a horrible user interface with a bunch of text and buttons where you get so confused af, and your first impression is just like ''ok no way, i need to stop playing this right now''. there's no tutorial, no explanations, no guides, this is like a game where the goal is try to keep the new players out of their own game 

https://steamcommunity.com/id/itsrodrigoal/recommended/412220/

**Comment by Learath2** [comment]
We should put out a request to the mappers, see if we can find one that wants to work with us to make a nice tutorial.

I also had a friend recently suggest that maybe we could use the clips we have on the wiki inside the client to demonstrate the moves if #2937 doesn't look like it'll get finished

**Comment by houseme-kyle** [comment]
I have reached out to a mapper who is willing to work with me on creating a tutorial map. Please let me know if someone has already started on this or wants to run point.

**Comment by def-** [comment]
Which mapper?

**Comment by houseme-kyle** [comment]
> Which mapper?

Soapy Sandwich

**Comment by houseme-kyle** [comment]
DDJoy made a fantastic tutorial video, that would complement a tutorial map nicely. Would there be a simple approach to integrate a video? Even if it is an external link for the user to click through to. 

The video in question:
https://www.youtube.com/watch?v=gp4wXgS3uO4

**Comment by def-** [comment]
Links are possible, see the start screen. We do include ffmpeg already, so we could also try displaying a video, but I'm not sure if we should.

**Comment by houseme-kyle** [comment]
> Links are possible, see the start screen. We do include ffmpeg already, so we could also try displaying a video, but I'm not sure if we should.
> 
> Edit: The Wiki page linked in "Learn" now shows this video

That's awesome, thanks. When looking at this issue more deeply will see how it can be incorporated, but I agree it probably best to have it as a link and not integrated.

**Comment by def-** [comment]
Tutorial map is nearly done. My plan is:

- Implement a selection at the start after "Welcome to DDNet screen" to connect to closest tournament server (or skip tournament).

> I'd put a list of available tutorial servers into the ddnet-info.json, maybe one per ping region?

- Implement message on map finish for tutorial map:

> Congratulations, you just finished the tutorial! Now press Escape and go to
> the "Browser" to select another server to play on together with others.
> Novice maps are the easiest, so you should start with them.

**Comment by edg-l** [comment]
It would be cool to also have #4267 which im sure can help new people too.
