### ISSUE TITLE
Switch to our own config directory?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2698]
At the moment we collide with Teeworlds. If Teeworlds has a default in the config set and you ran it before then the first time running DDNet will not show you the welcome screen and also keep the Teeworlds defaults instead of ours. I guess this should be changed by now. Something like ~/.ddnet instead of ~/.teeworlds

**Comment by Jupeyy** [comment]
"If Teeworlds has a default in the config set and you ran it before then the first time running DDNet will not show you the welcome screen and also keep the Teeworlds defaults instead of ours"

We should disable that for sure.

But i dont care, if we need a new directory.

**Comment by Jupeyy** [comment]
I think the best would be to have some new icon in the client that opens the native file explorer inside the config directory.
Bcs most mappers/old players are probably used to teeworlds config dir and new players don't test config_directory.bat (especially not with steam)

**Comment by Ekidoxx** [comment]
New, DDNet's directory would be good idea IMO.



Also, yeah, the `config_directory.bat` ain't intuitive name and it doesn't really tell in any way that this is actually the correct place to put custom overriding files.

So maybe rename the `config_directory` to `Custom content and settings` and convert it to `.exe` with either cog-alike icon, or better yet, icon made out of ["random" skin](https://ddnet.tw/skins/index.php?search=random)

**Comment by edg-l** [comment]
https://wiki.libsdl.org/SDL_GetPrefPath

**Comment by ChillerDragon** [comment]
> If Teeworlds has a default in the config set

Wait how does ``settings_ddnet.cfg`` and ``settings07.cfg`` clash? I never had any problems with that.

**Comment by def-** [comment]
settings.cfg does because we loaded that as a fallback.

**Comment by ChillerDragon** [comment]
> settings.cfg does because we loaded that as a fallback.

Oh okay. But I am not sure if that is going to be used by vanilla again any time soon. Imo it is nice to have all teeworlds clients in one directory. Makes talking to people asking for the demo directory for example easier. Or sharing maps etc.

**Comment by Jupeyy** [comment]
fixed by #4509
