### ISSUE TITLE
Token handshake for serverinfo requests

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#2706]
The current extended protocol of ddnet server info should have a token handshake.
You might think about "what about vanilla info requests or the old protocols that we still support?" and I say we should rate limit those. In case of an attack we should not send the other formats to the clients, but only allow the handshake one for latest ddnet clients. The handshakes can be analyzed and filtered, normal requests just respond with the serverinfo packet directly...

**Comment by heinrich5991** [comment]
> The current extended protocol of ddnet server info should have a token handshake.

Agree.

**Comment by fokkonaut** [comment]
Is anyone working on it? Would be very cool!

**Comment by heinrich5991** [comment]
Not needed anymore, we have HTTPS masters now: #5064.
