### ISSUE TITLE
Prevent glibc error on Linux

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#271]
Some people get an error about the glibc version while compiling. I think this is caused by using the system OpenSSL, but the statically bundled libcurl. The solution would be to only use system OpenSSL when we're also using system libcurl.

**Comment by def-** [comment]
Hm, I don't think it's caused by this. Maybe it's the order of arguments? Unfortunately I can't reproduce this on my systems.

**Comment by CytraL** [comment]
Idk... when i had this issue fstd tell me use "bam config" and all works fine. I think that are a conflict with libcurl and openssl too.
