### ISSUE TITLE
Client News

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2714]
Should we get rid of the in-client news? Feels a bit redundant with Website, Discord, Steam also all having news sections.

**Comment by edg-l** [comment]
i like them

**Comment by Jupeyy** [comment]
I like it as a changelog

**Comment by BannZay** [comment]
I use it as change log as well - very useful

**Comment by BannZay** [comment]
The only improvement I would like to see is links to webpages for additional information. Steam users might use overlay browser
