### ISSUE TITLE
Steam overlay rendering incorrectly

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#2757]
> [2:50 PM] murpi: This is probably known but I'll report it anyway.
> The steam overlay isn't properly working on my end when playing the steam ddnet version.
> I think there's something wrong with the overlay resolution, it looks pretty.. I don't know what to call it, dull?
> It hurts my eyes looking at it :aniblobsweat: 
> Also it's not possible to move windows opened in the overlay e.g the friendslist, or steam browser

**Comment by murpii** [comment]
https://i.imgur.com/Uf3dUi6.png 
looks not as sharp in comparison to other games like:
https://i.imgur.com/UiHCfFB.jpg

**Comment by heinrich5991** [comment]
![screenshot 1 by murpi](https://i.imgur.com/Uf3dUi6.png)
![screenshot 2 by murpi](https://i.imgur.com/UiHCfFB.jpg)

**Comment by BannZay** [comment]
> Edit: 1920x1080 resolution

Both games uses fullscreen + os resolution?

**Comment by murpii** [comment]
> > Edit: 1920x1080 resolution
> 
> Both games uses fullscreen + os resolution?

Yes

**Comment by murpii** [comment]
@heinrich5991 you can close this, I no longer have this issue on the latest version.
