### ISSUE TITLE
move_sqlite.py fails with "table record_maps already exists"

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2760]
@Zwelf 
```
Log of the transfer:

BEGIN TRANSACTION;
Traceback (most recent call last):
  File "scripts/move_sqlite.py", line 104, in <module>
    main()
  File "scripts/move_sqlite.py", line 101, in main
    transfer(args.f, args.to)
  File "scripts/move_sqlite.py", line 38, in transfer
    cursor_to.execute(line)
sqlite3.OperationalError: table record_maps already exists
```
Should I be worried?

**Comment by def-** [comment]
pebkac. The file existed already.

**Comment by Zwelf** [comment]
I initially assumed that the script would be called maximal one time per day and that moving ranks from sqlite to mysql would effectively occur even more rarely.
So it is kind of fault of the script. It could include the time in the file name, or just append a number to allow multiple moves per day, without removing the previous sqlite file.
