### ISSUE TITLE
Differences in graphics for ddnet game and front layer

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#2765]
Problem:
Different tile images for tiles with ids 6 (shifted "outdated" inscription), 9 (snow at the bottom), 12 (snow at the bottom)
Not critical but we getting out of sync.

Related to 3767eebead65d482a5666df145f368ef070ec2fd. If I revert it - problem is gone

Steps to reproduce:
1. Start editor
2. New map
3. Add front layer
4. Keep space
5. Click on Game layer 
6. Click on front layer
6. Repeat steps 5-6 until you can`t see the differences in existing tiles

**Comment by BannZay** [comment]
@Ekidoxx take a look on this issue please, you are the master in this area tho

**Comment by Ekidoxx** [comment]
Noticed this today too, no idea how I messed that ^^'
Will send fixed version today/tomorrow

**Comment by BannZay** [comment]
Because you are a human, thanks

**Comment by Ekidoxx** [comment]
Sent fixed version via Discord

**Comment by BannZay** [comment]
fixed in #2769
