### ISSUE TITLE
Can not set sv_test_cmds 

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#2773]
Description says "Turns testing commands aka cheats on/off"
But handler does not change its state.

Update either description or behavior.

**Comment by fokkonaut** [comment]
Wanted, need to set it in config on server start to avoid cheating

**Comment by BannZay** [comment]
Unfortunately I spent lot of time to figure out why my "grenade or tele" does not work (as rcon does not say anything instead silently does nothing)

And then I spent another amount of time to figure out why my rcon command with description "turns cheats on" does not actually turn them on ?!

@fokkonaut wanted undescriptive description or what?
@def-  why did you close?

**Comment by BannZay** [comment]
@fokkonaut to avoid cheating why would not set rights to allow this command to be changed by admin only

**Comment by def-** [comment]
Because then the admin can cheat and that's what we're trying to prevent

**Comment by Ekidoxx** [comment]
Shouldn't things like `sv_freeze_delay` only work in initial settings too?

**Comment by def-** [comment]
But then they can't be set in map settings.

**Comment by BannZay** [comment]
Can not we allow this settings for maps but not for admins?

**Comment by def-** [comment]
Currently not. You could try to make it possible, but I fear that has a higher chance of breaking something than ending up useful.

**Comment by ardadem** [comment]
There's no point about disabling test commands if you can enable it on the fly.
