### ISSUE TITLE
MacOs version doesn't work since the recent update.

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#2780]
As reported on discord by -insert weird letters-

> ä̵́̋s̴̅͑d̷̒͐ģ̵͛g̶̋͑ Today at 02:20
> Hey guys I need help, Whenever I open DDnet on steam it says its launching for a fews seconds and it dissappears or it dosent > launch. Ive tried restarting my computer, updating steam and reinstalling the game. Any Ideas?
> Im on a MacOs

and on steam forums by Drax "MacOs game cannot be launched."
> The game that I play every day has stopped even today, please I want you to find a solution, thank you.

**Comment by Ekidoxx** [comment]
Link to the message:  https://discord.com/channels/252358080522747904/745926398140612678/752684880508223538 by @ä̵́̋s̴̅͑d̷̒͐ģ̵͛g̶̋͑#3758

**Comment by def-** [comment]
Fixed in https://github.com/ddnet/ddnet/commit/7abe20175aec9da0391cdc2dd7a70ddca39b9422 (I hope)

**Comment by def-** [comment]
Verified by onby
