### ISSUE TITLE
Windows Defender Detects DDNet.exe 14.7.1 as Trojan:Win32/Wacatac.G!ml

### ISSUE THREAD

**Issue by dragere** [ddnet/ddnet#2786]
After yesterday's ddos on GER1, Windows Defender has removed DDNet.exe
If the exe is put into the same directory, it will be removed again.

Using a completely new directory still works, so I'm not sure if you can do anything about it.

**Comment by Ekidoxx** [comment]
The issue was solved for several people by just updating their antivirus' viruses definition version. The false detection was also already reported to Microsoft.

**Comment by def-** [comment]
Please report this to Windows Defender as a false positive, linking to our website and steam for reference of what DDNet is. The more people report this the higher the chance that they won't falsely detect us again in the future I guess.
