### ISSUE TITLE
Sort players in spectator mode alphabetically regardless of their rank

### ISSUE THREAD

**Issue by Ekidoxx** [ddnet/ddnet#2808]
Right now in both the scoreboard and when in spectator mode, players are sorted first by who-has-better-rank-time in let's call it group A, and then, whoever doesn't have finish is sorted alphabetically in group B - and that's annoying af since years.

This kind of sorting does have sense in the scoreboard, because there you want to see who's best, but in the list in spectator mode its making it so much harder to find the player you want, since you have to go thru the whole list one-by-one as the player can be placed anywhere.

The command `/spec <nick>` is not much helping due to allowing nearly all of unicode characters in nickname, and as of so it happens to be even more annoying than just checking one nick after another in spectator mode.

So please, make the list in spectator mode sorted fully alphabetically, regardless of one's rank. And if there are teams, list them at very end (as it is currently) though with still keeping the alphabetical order of its members' nicks.

---

![image](https://user-images.githubusercontent.com/14035306/93005503-e1f04f00-f551-11ea-94f4-672af3d3a858.png)
![image](https://user-images.githubusercontent.com/14035306/93005505-e452a900-f551-11ea-9aba-4ebe1e3354ff.png)

**Comment by def-** [comment]
Use ctrl-shift-tab for /spec tab completion.

Actually players are sorted by team first, then in the team by rank, then by name. I think we should keep the team sorting at least.

**Comment by Ekidoxx** [comment]
Well, to me teams are shown at end:
![image](https://user-images.githubusercontent.com/14035306/93029914-27c71900-f61f-11ea-8faa-e277411aab69.png)

But whether the teams would show at beginning or at the end doesn't make much of a difference anyway

**Comment by def-** [comment]
Well team 0 clearly comes before any other team, so that's what I meant.
