### ISSUE TITLE
significant lag when other player send chat inculding many CJK character

### ISSUE THREAD

**Issue by QingGo** [ddnet/ddnet#2810]
I can feel a significant lag(maybe 0.1~0.5 s) when other player send chat inculding many CJK characters in newest DDNet client (14.7.1). In older verion before steam, such as 12.8, did not have such problem.

I think maybe we could take one or more of the following methods to alleviate this problem:
1. Pre-load the info and bitmap of every character into memory every time when starting the client.
2. Pre-load the info and bitmap of every character into memory, then dump it into files on disk when the first time starting the client. After that when starting the client, we could load these directly from files.
3. Pre-load the info and bitmap of the top-n most frequency character.
4. Provide a config option to whether pre-load the character info.

the relative code is in engine/client/text.cpp:
``` cpp
	SFontSizeChar *GetChar(CFont *pFont, CFontSizeData *pSizeData, int Chr)
	{
		std::map<int, SFontSizeChar>::iterator it = pSizeData->m_Chars.find(Chr);
		if(it == pSizeData->m_Chars.end())
		{
			// render and add character
			SFontSizeChar& FontSizeChr = pSizeData->m_Chars[Chr];

			RenderGlyph(pFont, pSizeData, Chr);

			return &FontSizeChr;
		}
		else
		{
			return &it->second;
		}
	}
```

**Comment by def-** [comment]
I didn't notice this. Maybe it only happens on a few systems?

**Comment by QingGo** [comment]
> I didn't notice this. Maybe it only happens on a few systems?

do you mean OS system? I use Windows 10 OS system. Some players feel the same as me.

**Comment by QingGo** [comment]
Only when I receive message full with CJK characters which had not encountered before, I feel lag. Repeated CJK characters message didn't make me lag. I upload a video to youtube https://youtu.be/et_SsWyCd5U?t=27 . The lag is begin at 0:26. 

And I found maybe most of the older player use old version of DDNet Client, so they did not encount this issue. When most of new player use steam client, they may think it is normal behavior.
