### ISSUE TITLE
Improve afk players feature

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#2821]
Add marks and mark players who switched to another app (when client lost focus) and players which switched to dummy as not active. Consider about allowing player to mark themself as not active so they can press a button to let everyone know that they are about to leave their keyboard

**Comment by heinrich5991** [comment]
> Consider about allowing player to mark themself as not active so they can press a button to let everyone know that they are about to leave their keyboard

To me, that sounds like it would be abused as some sort of emote, lessening its effectiveness.

**Comment by BannZay** [comment]
Ehm? So need to make it less abusable, for example add delay

**Comment by BannZay** [comment]
I mean every single feature can be abused this is not special one tho

**Comment by d3fault** [comment]
Players are already shown as "asleep" (eyes) when in /pause, so adding the AFK/"Zzz" emote to that shouldn't be too difficult. As for abuse, "emote muting" could be expanded to cover the AFK "Zzz" (except when players are AFK from _timeout_ *only*, since that can't be abused anyways)

**Comment by Learath2** [comment]
We can let the client dictate it's afk state, that shouldn't cause much issue.

**Comment by heinrich5991** [comment]
> I mean every single feature can be abused. This is not special one tho.

This is not true. In some cases there's no good way to add a feature without adding some possible abuse. But the best features (and they do exist) are those that cannot be abused by design (or have incentives aligned against the abuser).

**Comment by Astramast** [comment]
Maybe just add "..." emote to /pause state, so it's different visually from afk/away for a big moment player, but make it more clear that the player is afk/not having his hands on keyboard momentally, and then it's just players having to learn to use /pause when they go away for some seconds and others to not interact with /paused players since they know they won't be active in the action. I think this is more a problem of communication than a problem of the application itself.

**Comment by heinrich5991** [comment]
We have the sitting animation state to mark people who are in /pause nowadays.

**Comment by heinrich5991** [comment]
> > To me, that sounds like it would be abused as some sort of emote, lessening its effectiveness.
> 
> I don't understand how it can be abused? I mean how it can trigger others?

If people started using it as something other than actually marking themselves as afk, then the afk sign would become less useful in figuring out whether other people are currently away from their clients for a long time.

**Comment by trikiman** [comment]
> > > To me, that sounds like it would be abused as some sort of emote, lessening its effectiveness.
> > 
> > 
> > I don't understand how it can be abused? I mean how it can trigger others?
> 
> If people started using it as something other than actually marking themselves as afk, then the afk sign would become less useful in figuring out whether other people are currently away from their clients for a long time.

still dont get why it is problem. better "overkill" than "underkill". i mean if we have more afk sings its fine no? for me diff between 5min afk and /afk no exist. Why for u it is exist? What's wrong with a man marking himself as afk?

u think why ppl rename himself like afk, jsut for fun? They do it cus they need afk and dont wanna ruin other players run. but rename work bad cus spam if too much tee.
