### ISSUE TITLE
Entities text numbers bug

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#2822]
![image](https://user-images.githubusercontent.com/17499770/93074988-d5711100-f68d-11ea-8db3-f2eff551e584.png)

**Comment by def-** [comment]
@Jupeyy

**Comment by BannZay** [comment]
Reproduces on master and latest released build with both OpenGL versions. (cl_text_entities_size 100)
Reverting #2655 solves the issue with digit 4 only. This might be the old issue

**Comment by Jupeyy** [comment]
Yes it's because u cannot calculate font size perfectly because freetype rounds each glyph attributes on it's own. And i tried to use the space as much as possible. But since it is only 1-2 pixels it can also just be clamped away
