### ISSUE TITLE
Border button broke my map frequently

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#2823]
If you not changed layer and pressed on a place where tele/switch number picker stays then you are fucked (because Border resides in this place). 

I don't think this button is usable nowadays. Please add confirmation message at least or move this button to less frequently used place.

**Comment by BannZay** [comment]
I would just remove this button since I never used it on purpose

**Comment by gerdoe-jr** [comment]
I agree, but this button can help sometimes. Also, this button can break up whole map by inadvertence, before applying.

It should ask confirmation before applying border tiles.

**Comment by BannZay** [comment]
@gerdoe-jr does this button helped you ever? Would you like it to be in menu bar?

**Comment by gerdoe-jr** [comment]
Once I needed map like 100x100 for quick testing some stuff, if this button didn't exist, I would stuck for several time to map it.

**Comment by BannZay** [comment]
I asked in discords #mapper channel about this button. 6 votes to remove the button, 0 to keep it.

**Comment by Learath2** [comment]
At the very least this should be hidden behind a menu as we have no way to
undo things

**Comment by Ekidoxx** [comment]
Then, as already suggested, maybe just add pop-up box with confirmation required?
