### ISSUE TITLE
[Feature request] Editor fill with the tile

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#2824]
Similar to Windows Paint (or other image editor) fill feature (https://youtu.be/tAcRRD9OOqg?t=33)

It should fill bounded by unhokable and hookable tile area with a tile from the brush

**Comment by Learath2** [comment]
Problem with a tool like this is that we have no undo, so one missclick can destroy all your work :/

**Comment by BannZay** [comment]
> Problem with a tool like this is that we have no undo, so one missclick can destroy all your work :/

Yea =(
Can we maybe do in a safe way ? For example, add a possibility to see affected area before committing the change.

**Comment by BannZay** [comment]
Like when you click first time - affected tiles become highlighted, when you click second time - affected tiles changed.

**Comment by def-** [comment]
I'm against this without proper undo, which we don't have.
