### ISSUE TITLE
Turn on Anti-Ping by default

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#2842]
We should turn on Anti-Ping by default for our new Steam playerbase. Needing to "lead" hooks/etc by a certain amount of time, especially when that amount of time is variable (dependent on your ping), gives a poor gaming experience. I see perfectly competent gamers missing hooks/etc by a consistent amount: the amount they *should* be leading (but aren't). I wouldn't be surprised at all if many of the new Steam players have rq'd (permanently) simply because the "leading" is dumb.

Honestly once you go Anti-Ping you never go back. I can play on 200ms GER/etc servers because of Anti-Ping.

Anti-Ping only hurts when you have a really bad connection in the first place (so you're ruining something that's already ruined). We could probably detect those bad connections (both the large latency and the packet loss variety) and give a friendly message: "Hey, you might want to turn off anti-ping while you're in this server".

**Comment by def-** [comment]
We discussed this before. Some people really like Antiping because they can play fine with high ping, some really hate it because all the other tees are randomly jumping around the screen.

If we want the message, we should probably do it the other way around and suggest antiping when ping is > 100 or something like that.

**Comment by d3fault** [comment]
I understand but I think the "jumping around on screen" is the uncommon case and that most players, especially newbies, won't recognize/understand/follow the suggestion to enable Anti-Ping. I also argue that Anti-Ping is useful even with just 50ms (considered "good") ping.

Defaults should cater to the common case. For most players, Anti-Ping will function correctly and eliminate the need to "lead" hooks/etc.

**Comment by def-** [comment]
We also can't detect currently if someone still has the implicit default or set the value to off consciously. (I might take a look at that problem later.) This means we would be changing the setting for everyone.

**Comment by def-** [comment]
Previous discussion on Discord: https://discord.com/channels/252358080522747904/295908390956433410/745780659615957013

**Comment by d3fault** [comment]
Yes it appears to be a dupe unresolved conversation but I think the end-all argument is: if your ping is so high that Anti-Ping is buggy, you probably won't be able to play with Anti-Ping *off* either!

Turning it on for everyone is fine, you recently did that with Weapons Auto-Switching and it wasn't a big deal (I just turned it off again). Experienced players know their way around the game and can easily turn Anti-Ping off again, whereas newbies have never even heard of Anti-Ping and won't ever know to try turning it on before giving up on the game forever.

**Comment by d3fault** [comment]
I do think some notifying "hey your ping is high, you should try finding another server" is a good idea but that's really a separate issue. btw geoip lookups (apt install libmaxminddb0) and suggesting a more appropriate server would be trivial and helpful (and require no coordination between servers)... but ddnet already sorts the server list by ping by default so geoip would just be a fallback mechanism in case they changed the sorting on accident or something.

**Comment by edg-l** [comment]
Antiping looks bad even with good internet, please don't

**Comment by d3fault** [comment]
> Antiping looks bad even with good internet, please don't

bad how? I remember when I made the switch a couple years ago Anti-Ping felt/looked weird for a little while..... but that was only because I was so used to having Anti-Ping off. that went away in about a week and I lived happily ever after

**Comment by axblk** [comment]
With a ping below 60 it's okay, anything above that is just tees jumping around. Even with ping < 20 it's still a bit glitchy. However, with a snap rate of 50 instead of 25 (`sv_high_bandwidth 1`), it feels pretty smooth to me.

In my opinion, it still feels rather bad with a high ping, but it's useful to eliminate the last milliseconds of latency so that all elements on the screen are really in sync.
