### ISSUE TITLE
inet_ntop does not exist on Windows XP

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2846]
So I can't build with websockets for now. Alternative could be something like this: https://github.com/libevent/libevent/blob/e5302ac71614abeb283e4c037ca60f10744921d7/evutil.c#L1819 or this: https://stackoverflow.com/questions/12892063/windows-socket-programming-linking-error-for-inet-ntop

@QingGo Do you want to take a look?

**Comment by def-** [comment]
The alternative would be to upgrade our requirement to Windows Vista, but I think there are still too many WinXP users to do that.
![screenshot-20200917@141538](https://user-images.githubusercontent.com/2335377/93469132-57607480-f8f0-11ea-9f9c-3dab32deab56.png)

**Comment by QingGo** [comment]
@def- I'll try to get an alternative way of inet_ntop in Windows XP. By the way, where are these data from, from ddnet.tw website access header? And Is it newest data?

**Comment by def-** [comment]
Yes, from last week on ddnet.tw

**Comment by QingGo** [comment]
I think this problem can be fix in this PR https://github.com/ddnet/ddnet/pull/2848 . But I have no way to check if it really work normally at Windows XP

**Comment by def-** [comment]
I'll check.

**Comment by def-** [comment]
Fixed by #2848
