### ISSUE TITLE
New scrollbar not rendered exactly at the top 

### ISSUE THREAD

**Issue by edg-l** [ddnet/ddnet#2852]
When its at the top there is a little margin
![image](https://user-images.githubusercontent.com/15859336/93515756-67487a80-f929-11ea-8b18-b1f7b0af9618.png)
At the bottom there is no margin
![image](https://user-images.githubusercontent.com/15859336/93515769-6ca5c500-f929-11ea-9f01-9c26e6bdc357.png)

**Comment by Jupeyy** [comment]
btw the old scrollbar had the same problem just opposite, its the scrollbar logic that is broken
it wasnt aligned the the last server item

**Comment by edg-l** [comment]
Okay now that i rechecked it looks ok, not sure what i was thinking.
