### ISSUE TITLE
Improve "Run Server"

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#2858]
Currently newbies can start server with the button which is nice!
But they can not connect to the server. 
Even though they will find Lan tab they might not know password.

Can we display password ingame or allow client to not ask user and send it automatically ?
Minimal acceptable thing is notification with "how to connect" with password inside IMO.

**Comment by def-** [comment]
there is no pw to join the server.

**Comment by BannZay** [comment]
My bad, I wanted to say about rcon. But eventually I see that if user figured out how to use rcon (to change map for example) they have to be able to find out where to get autogenerated rcon
