### ISSUE TITLE
Hover effect can affect 2 rectangles

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#2868]
![image](https://user-images.githubusercontent.com/35420825/93663529-f4deb400-fa68-11ea-8c85-31dd865d7f89.png)
![image](https://user-images.githubusercontent.com/35420825/93663536-0627c080-fa69-11ea-84dc-433c8f0b0bf1.png)

**Comment by def-** [comment]
Floating point numbers I guess.
The same is probably true for clicking but it doesn't matter then because the first one is just chosen.

Your cursor is broken.

**Comment by fokkonaut** [comment]
I rotated my cursor on purpose :D
