### ISSUE TITLE
Unmasked entities dont work

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#2870]
https://github.com/ddnet/ddnet/commit/b83d8735fe88c5ce261abb8d0079b97744a08603#diff-a7af8d91219b48b53d23d434be04ae5cR143

@Jupeyy why did you add this? The server can send the flag to not mask the entities, and in my mod i send this because i do have custom ddnet.png with tiles that are outside of the masked area. Can we please remove the need of masked entities again just to use ddnet.png?

**Comment by Jupeyy** [comment]
,? If mod type is unknown e.g. by sending the flag the default ddnet without masking is used

**Comment by Jupeyy** [comment]
Have u even tried this

**Comment by fokkonaut** [comment]
I think you didnt get what I mean.
My server sends the Gameinfoflag entities ddnet, so that the client uses the ddnet entities. But my server (different from ddnet: ) sends the unmasked entities flag aswell, because my mod uses tiles that are not used in ddnet, therefore i need them unmasked, so the client also renders the "unused" tiles, which are used in my mod and in my custom ddnet.png. If I dont send unmask flag, then of course the client will choose the ddnet entities but it wont render the unused tiles
