### ISSUE TITLE
Sort demos by map

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#288]
> If there was a way to sort autorecorded demos by the map played, or search for demos played on a specific map, that would make it sooo much easier for finding old runs. If something like this could be added that'd be great.

http://forum.ddnet.tw/viewtopic.php?t=2056

**Comment by east** [comment]
I think we should create an info/cache file next to the demo file. This way we could easily store information like, demo-markers, map-name and demo-length.

example:
autorecord_2015-08-15_22-02-09.demo
autorecord_2015-08-15_22-02-09.json

(if json isn't efficient enough we could use a flat file format)

**Comment by nzyuzin** [comment]
Immediate problem of this issue however can be resolved by adding 'map' column to demos table.

**Comment by east** [comment]
https://github.com/ddnet/ddnet/blob/master/src/engine/demo.h#L13
Right, I didn't know we already have this information available.

**Comment by def-** [comment]
If we do #297, it's auto-sorted by map, then we can instead add a simple way to choose to sort by date instead.

**Comment by nzyuzin** [comment]
Cool idea :+1:
But could you explain further what kind of simple way to sort by date you mean?

**Comment by def-** [comment]
Either by ctime from file info or parse the date string if there is one inside.

**Comment by nzyuzin** [comment]
Nah, I'm talking about UI side.
I don't see how it fits in the current UI.

Button to sort by date alongside with 'refresh' or 'open' buttons?
That looks inconvenient to me.
If we choose to add a column with date, then there's no need to store date in filename and still we're back to changing implementation of demo list.

**Comment by def-** [comment]
Like in the serverbrowser where you can sort by each column.

**Comment by nzyuzin** [comment]
Then it's just the same as @east suggested though, instead of adding 'map' column we add 'date' column.

At the moment we have *date* column because maps have it just in their names.

**Comment by def-** [comment]
This is fixed since we now give the demos nicer names.
