### ISSUE TITLE
New server info request/response protocol

### ISSUE THREAD

**Issue by east** [ddnet/ddnet#289]
The current implementation of server info request/response has some considerable flaws. E.g. It's usable for reflection attacks and has some design issues (see here #130).

Ideas:
- Add token handshake to prevent nowadays common ip spoofing attacks. (maybe use heinrich5991's implementation: https://github.com/teeworlds/teeworlds/pull/986 see "Connless packet")
- Make it more dynamic in general (dynamic sized playerlist, maybe even without boundaries for > 64 players)
- What about compression? The server status contains a lot of utf8 strings, so we could fairly reduce the size and save bandwidth.

Keep in mind that the old info request protocol won't be dropped because of compatibility to other clients. But in case of strong attacks we could prevent DoS by disabling it temporarily.

**Comment by heinrich5991** [comment]
Not sure how you would protect it against reflection attacks, it'd probably incur an extra rountrip.

**Comment by def-** [comment]
I guess we don't need this anymore. We have rate limiting now for example.
