### ISSUE TITLE
"Warning: Server executable not found, can't run server"

### ISSUE THREAD

**Issue by rffontenelle** [ddnet/ddnet#2891]
In the main menu, "Run server" button won't start server instance, even though it is installed in `/usr/bin/DDNet-Server`. Environment: Arch Linux 64, [ddnet] 15.0.4 (AUR)

[ddnet]: https://aur.archlinux.org/packages/ddnet/

**Comment by def-** [comment]
At the moment we just look in /usr/share/ddnet. I guess we should look at argv[0] to deduce the path. Unfortunately this is not a generic solution as it still fails on OSX.

**Comment by rffontenelle** [comment]
Notice this is the installation path set by CMakefile, nothing non standard.
