### ISSUE TITLE
"ctrl + shift + d" bind is moving tee again

### ISSUE THREAD

**Issue by Brokecdx** [ddnet/ddnet#2930]
"ctrl + shift + d" bind is moving tee again ^

**Comment by def-** [comment]
Probably related to the implementation of multi modifier binds. https://github.com/ddnet/ddnet/pull/2675

@plsplsplslol could you take a look?

**Comment by def-** [comment]
bisect agrees with my guess:
```
6782f934193bdaf1c12fd531dde83eed31ae6ecc is the first bad commit
commit 6782f934193bdaf1c12fd531dde83eed31ae6ecc
Author: plsplsplslol <alpootagpro@gmail.com>
Date:   Sat Aug 29 17:01:56 2020 -0700

    support multiple modifiers for binds

 src/game/client/components/binds.cpp | 85 +++++++++++++++++++++---------------
 src/game/client/components/binds.h   |  2 +-
 2 files changed, 50 insertions(+), 37 deletions(-)
```

**Comment by plsplsplslol** [comment]
ctrl + shift + d has always moved my tee for me. In the binds code there is a section where +xxx binds ignore modifiers so I just left it in there.

**Comment by Learath2** [comment]
ctrl + shift + d wasn't moving tees after I first got the modifier patch in, though I don't remember how I made it behave so specifically

**Comment by def-** [comment]
With this code in binds.cpp:
```
        if(Mask == ((1 << MODIFIER_CTRL) | (1 << MODIFIER_SHIFT)))
        {
		if(m_aapKeyBindings[0][e.m_Key] && e.m_Flags&IInput::FLAG_RELEASE)
			Console()->ExecuteLineStroked(0, m_aapKeyBindings[0][e.m_Key]);
		return true;
	}
```
