### ISSUE TITLE
Open directory buttons

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#2944]
- Themes (sadly the theme selection is already pretty small, and under windows there is also another option "open console"),
so there is just no place anymore, any ideas @def- ?

- Skins

- Demos

**Comment by def-** [comment]
> Themes (sadly the theme selection is already pretty small, and under windows there is also another option "open console"),
so there is just no place anymore, any ideas @def- ?

Could add a second row? Then the info text would also fit in 5:4 again
