### ISSUE TITLE
Add PvP tab in the browser to distinguish DDNet from modes like FNG, CTF, etc.

### ISSUE THREAD

**Issue by l-ouis** [ddnet/ddnet#2977]
A lot of players might get confused when they are on the DDNet tab and join servers such as fng, ctf, dm, block, etc.

So, I think it's a good idea that we move all modes in which players go against other players (vanilla modes, fng, block, infection, etc.) into a separate tab called "PvP" so players both won't get confused in the DDNet tab and can also access all the pvp modes easily in a separate tab.

**Comment by b3z** [comment]
Maybe the filter list is a better place to put that. I guess any player who knows TW for at least a week won't choose their servers by PvP or not PvP. I think people chose servers by mod. (gores, ddrace, fng, zctach, vanilla ctf, ...) so a tab would be more or less useless.

**Comment by l-ouis** [comment]
any opinions/update on this?

i still think the main argument for it is that people might get confused when they join bomb or ctf while on the ddnet tab, they have totally different mechanics but in the same grouping

if we have kog as a whole tab, I'm sure we can make space for pvp modes too. also, there are servers like noby's fng which aren't part of ddnet but are still in the ddnet tab, which is also a little inconsistent. it'd be more organized if they were all in a separate mode.

**Comment by def-** [comment]
Since we don't care about our pvp servers much I don't want to make a specific tab for them. We just run them because we can, other people might have better pvp servers.

**Comment by heinrich5991** [comment]
I think we should remove them from the privileged position in the DDNet tab. Their position makes it harder for third-party PvP servers to compete.

**Comment by def-** [comment]
This also means they are no longer counted in https://ddnet.tw/stats/

**Comment by edg-l** [comment]
Removing them from the ddnet tab sounds the most fair.

**Comment by b3z** [comment]
Why do they have to be removed from the stats? @def-

**Comment by def-** [comment]
Because at the moment I use the same file for determining:
- official servers (checkmark)
- show in ddnet tab
- show in ddnet.tw/status and statistics

**Comment by Robyt3** [comment]
We now have community filters. Being able to set some communities as tabs is planned (#7774).
