### ISSUE TITLE
Add Refresh button on Skins page

### ISSUE THREAD

**Issue by louis45508** [ddnet/ddnet#2979]
I noticed in the new version there was a Refresh button for Assets such as game.png, entities, etc.

I think it'll be helpful to have the same button for skins so people can easily import and test skins without having to relog the client.

**Comment by def-** [comment]
@Jupeyy want to take a look?

**Comment by Jupeyy** [comment]
I am working on something else currently, but if there is no hurry i can do it after that

**Comment by def-** [comment]
Sure, not for this release I think.

**Comment by timakro** [comment]
I will help a friend get started with Hacktoberfest next week and I'd like to claim this issue for them. They will open a PR next week with my help.

**Comment by Jupeyy** [comment]
there is CClientData, and it conatins:
m_SkinInfo
m_RenderInfo
and
m_SkinID

especially the first two, contain m_Texture, which might be deallocated by the skin refresh(but are set, when receiving the snapshots.
So make sure to either load the skins after the main loop or reset these values, 
in #2987 i made it a bit safer by not using the texture directly, tho i'd prefer no wrong skin is displayed :D
