### ISSUE TITLE
Editing multiple layers only affects the first layers in group

### ISSUE THREAD

**Issue by qxxxb** [ddnet/ddnet#2981]
Using DDNet 15.1 rc 2

## Example

![screenshot_2020-10-03_01-12-16](https://user-images.githubusercontent.com/46016483/94984003-9bb95a80-0515-11eb-8a47-4c8d7f4c014b.png)

### Expected behavior

![screenshot_2020-10-03_01-14-07](https://user-images.githubusercontent.com/46016483/94984022-bf7ca080-0515-11eb-8852-c5a45b9e1f6a.png)

### Actual behavior

![screenshot_2020-10-03_01-12-19](https://user-images.githubusercontent.com/46016483/94984028-c60b1800-0515-11eb-9b97-f461dfb8f14c.png)

**Comment by def-** [comment]
Might be related to https://github.com/ddnet/ddnet/pull/2949 

@Learath2 can you take a look?
