### ISSUE TITLE
Adjust directory trasversal - (Replacing DIR data type, from <dirent.h>, data type in system.c)

### ISSUE THREAD

**Issue by n0toose** [ddnet/ddnet#2988]
## Description

I'm currently trying to port ddnet to [Haiku](https://haiku-os.org), a POSIX-compatible, Unix-like, alternative operating system.

However, Haiku (as well as other systems) does not support `readdir()` from `dirent.h`, which seems to be a function limited and designed for Linux only.

In many software ports for the Haiku operating system, [find_directory()](https://www.haiku-os.org/docs/api/FindDirectory_8h.html) (Haiku-only) is used. Some live examples of the function being used in patches can be found [here](https://github.com/haikuports/haikuports/search?q=find_directory). However, I am not sure if implementing that in `system.c` will increase complexity for no real reason, or whether another alternative should be considered instead.

## Instances

https://github.com/ddnet/ddnet/blob/6bb8cda483f666f23161f02d347c69c8d8b02bd9/src/base/system.c#L1970
https://github.com/ddnet/ddnet/blob/6bb8cda483f666f23161f02d347c69c8d8b02bd9/src/base/system.c#L2022

## Information

Read more:
- [die.net](https://linux.die.net/man/3/readdir)
- [opengroup](https://pubs.opengroup.org/onlinepubs/007908799/xsh/dirent.h.html)
- [man7](https://www.man7.org/linux/man-pages/man3/readdir.3.html)

- [Implementation of find_directory() in LibreOffice](https://kod.acikkaynak.gov.tr/libreoffice/core/commit/41427a5682ba83167f3b0abfa0e1e61b9ea6fa9d)

**Comment by def-** [comment]
Weird, my readdir manpage says:
```
CONFORMING TO
       POSIX.1-2001, POSIX.1-2008, SVr4, 4.3BSD.
```

**Comment by def-** [comment]
Ok, found something: https://dev.haiku-os.org/ticket/10991

Anyway, it seems only to be used in in fs_listdir_info. Maybe you could add an #elif defined() special case for Haiku there?

**Comment by panos** [comment]
Yeah, I linked that link earlier, @def-.

I always mix up my POSIXes, but I'm aware of my lonesomeness as far as using that system is concerned and I'll get on with it. What is that function used for again? (Perhaps... I could do away with it for the time being, get it to compile, then rewrite it once it demonstrably does.)

**Comment by def-** [comment]
It is used for the list of demos in the main menu as well as the list of ghosts in the ingame menu.

**Comment by panos** [comment]
Hey, should I move on with upstreaming the changes for Haiku in the Makefile, despite not having completed the port in the source code itself?

**Comment by def-** [comment]
Sure, that's fine for me.

**Comment by Robyt3** [comment]
@n0toose Is this still relevant? Looks like https://github.com/haikuports/haikuports/pull/7931 was merged.

**Comment by Robyt3** [comment]
Stale.
