### ISSUE TITLE
DDNet server type filter slightly too long

### ISSUE THREAD

**Issue by Piepow** [ddnet/ddnet#2989]
![image](https://user-images.githubusercontent.com/20409621/94994511-06928200-0566-11eb-8a3c-3f07376ddd77.png)

Seems to be a new bug from DDNet 15.1

**Comment by def-** [comment]
![screenshot-20201003@165459](https://user-images.githubusercontent.com/2335377/94994636-2ee7a400-0599-11eb-92b9-bc71e98a3a48.png)
Weird, fits for me. Any ways to reproduce?

**Comment by Piepow** [comment]
I think the bug only appears when u join a server and open the browser from in-game
![screenshot_2020-10-03_13-55-08](https://user-images.githubusercontent.com/20409621/94998507-33539300-0580-11eb-9905-8d2daf2bb49f.png)
