### ISSUE TITLE
Compiling problems on Linux

### ISSUE THREAD

**Issue by Henningstone** [ddnet/ddnet#299]
I'm not sure if I made a mistake, but compiling the client under Linux doesn't work for me. Everything else compiles fine.
If always fails to link the executalbe.
```
[60/60] #1 link DDNet
/usr/bin/ld: other/curl/linux/lib64/libcrypto.a(dso_dlfcn.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib/x86_64-linux-gnu/libdl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
bam: 'DDNet' error 256
bam: error: a build step failed
```
Am I missing some dependencies or something like that?

**Comment by Laxa** [comment]
I think you need to install openssl and remove bam.lua and try to compile again.

**Comment by Henningstone** [comment]
Ok first, removing bam.lua wouldn't be that smart since it is the Makefile ;)
And why do you think I need to install openssl? I'm a bit confused...

**Comment by Laxa** [comment]
Remove config.lua and try, you can also come on #ddnet, irc.quakenet.org.

**Comment by Henningstone** [comment]
Solved on irc, thanks @Laxa. The problem was indeed that I was missing libcurl4-openssl-dev.

**Comment by def-** [comment]
No, that's not the proper solution to this. Instead we should figure out why that error happens with the bundled libraries: https://github.com/ddnet/ddnet/issues/271

Some ideas:

- Specify libs in another order
- Add -ldl in another order
