### ISSUE TITLE
Consistent order in Settings -> Graphics -> Display Modes

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2991]
Should be same order whether supported is clicked or not. Will fix later.

**Comment by Ekidoxx** [comment]
Just for reference

![OFF](https://user-images.githubusercontent.com/14035306/94994863-a833c680-059a-11eb-9aa7-544cd0c6a16f.png)
![ON](https://user-images.githubusercontent.com/14035306/94994867-b08c0180-059a-11eb-94c2-b4e333885d66.png)
