### ISSUE TITLE
Adding the event type to server messages so that the client can filter and translate them

### ISSUE THREAD

**Issue by b3z** [ddnet/ddnet#2995]
I think it would be great to have the opportunity in settings > appearance where you can select what chat messages you want to see. e.g.
* join/leave
* map finishes
* team join messages
* general server messages
* name changes
and so on. 

Personally it bugs me to get tons of chat messages on big servers only because some players I have no relations with joining teams or so.

**Comment by def-** [comment]
For reference: What we currently have is /dnd

**Comment by b3z** [comment]
Yes I know. But then all server messages are ignored. Thanks for the reference though.

**Comment by Learath2** [comment]
This should probably be implemented by adding actual events/messages for these server events and emitting the actual message on the client. This would also allow us to slowly phase out these messages for actual UI indications for some things.
