### ISSUE TITLE
Editor Auto Rules improvements

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3013]
Reported by Soreu on Discord

> could you do something when rule name is way longer than its displaybox? xd like either scale the text size or make the box longer?

> also I can't select the top option of "none" xD
![unknown2](https://user-images.githubusercontent.com/2335377/95025791-96325080-068c-11eb-8d59-9a5931e99b18.png)
![unknown](https://user-images.githubusercontent.com/2335377/95025793-97637d80-068c-11eb-98c0-dac621370af6.png)

**Comment by def-** [comment]
Clicking none works for me

**Comment by saltyElefant** [comment]
Idk if it's fixed already for later versions, but with 15.1.2 I can't select None either once I have opened the autorules window and clicked on another rule before trying to select None again.

**Comment by def-** [comment]
Can't reproduce. @saltyElefant Any hints on the steps? @edg-l do you have any idea?

**Comment by saltyElefant** [comment]
Only appears on rules that need the scroll bar.

**Comment by def-** [comment]
Ok, I see. It stops working after having scrolled down I think.
