### ISSUE TITLE
Show file creation date when loading map in editor

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3016]
Similar to demos browser. Could even make it sortable if you want to go fancy. Anyone interested in implementing?

**Comment by murpii** [comment]
It'd be nice if we could get buttons which opens each directory aswell (maps/downloadedmaps/mapres and so on)

**Comment by Marmare314** [comment]
The original issue is part of #6419 i think.

**Comment by Robyt3** [comment]
First part is solved by #6419. Second part is moved to separate issue #6422.
