### ISSUE TITLE
Hookthrough tile that works better than the current one

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#302]
The current hookthrough tile is weird, hard to understand and leads to many bugs in maps. Instead we should have a simpler new one and deprecate the old one, of course keeping support for the old maps. The new one should just be placed on top of a tile and transform this tile into a fully-hook-through tile. Additionally a rotatable one for 4 directions would be nice to restrict hookthrough to 180° around this direction.

Does this have any difficulties or was it just not done to keep backwards-compatibility with the old hookthrough tiles which existed before front layer?

**Comment by heinrich5991** [comment]
Just backward compatiblity.

**Comment by def-** [comment]
Fixed by #365.
