### ISSUE TITLE
Order of game layers changes how transparently they're rendered

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#304]
See this:
![rendering](https://cloud.githubusercontent.com/assets/2335377/9495718/4947b150-4c0d-11e5-86c6-73e16c05f27b.jpg)

Found by Soreu and BannZay. It's probably because of the alpha mixing. We could sort  the layers so that game layer is always shown first, but that's ugly .Haven't found a nice solution yet, and don't know why this happens. Relevant code is in maplayers.cpp.

**Comment by Soreu** [comment]
Idk if it helps somehow, but "by an accident" found two commits that - to me - looks sorta related to this issue

https://github.com/cinaera/teeworlds/commit/2ac229f2288e65c501bb1eedd84ce4bbef9bba1b
https://github.com/cinaera/teeworlds/commit/16bb3621c3aff0eb05adb43f9457fb7dc90ec925

**Comment by cinaera** [comment]
Can you upload the map? Does it only appear ingame?

**Comment by Soreu** [comment]
[Download](http://www.filedropper.com/entitiestransparency) | [Mirror1](http://s000.tinyupload.com/index.php?file_id=07508287108121580681) | [Mirror2](http://expirebox.com/download/af4925dcfab6dfc762a0c23fc68a8748.html)

Yes, ingame only - the order doesn't affect the transparency in editor

**Comment by timgame** [comment]
Fixed by #343, thanks to cinaera.
