### ISSUE TITLE
Spawning is still shuffled when in a solo team

### ISSUE THREAD

**Issue by Azorlogh** [ddnet/ddnet#3041]
Bug scenario:

| Sequence of events                                |  Result                                         |
|------------------------------------------------------|--------------------------------------------|
| Player A is alone in a server                   | Their spawn point remains fixed. |
| Player B joins the server                         | Both players' spawns are now shuffled to prevent collisions. |
| Player A joins a team alone and locks it | Both of their spawn points are still shuffled even though there is no chance of collision. anymore |

**Comment by heinrich5991** [comment]
This is probably considered a gameplay mechanic and thus hard to change.

**Comment by Learath2** [comment]
I doubt it would invalidate any ranks though, maybe we could fix this?

**Comment by def-** [comment]
Fixed by https://github.com/ddnet/ddnet/pull/4661
