### ISSUE TITLE
black screen after tabbing in/and out of ddnet client

### ISSUE THREAD

**Issue by l-ouis** [ddnet/ddnet#3056]
When tabbing in and out of ddnet client (borderless window or fullscreened) I get a small black screen for about one second. Also happens on vanilla 0.7 client, but in no other programs/games.

Intel UHD 620
Windows 10

edit: might be specific to my computer only, so can anyone else reproduce?

**Comment by Jupeyy** [comment]
It was only after the driver update wasn't it? Maybe you could test a beta driver or use the old driver for now

**Comment by l-ouis** [comment]
yeah i changed to the microsoft basic adapter thing which doesnt show black screen, so it's probably a driver issue

i guess i'll have to find some old version of the driver and install that
