### ISSUE TITLE
Go through clang scan-build

### ISSUE THREAD

**Issue by Learath2** [ddnet/ddnet#3071]
Clang has a nice static analysis tool, we should go through it's results and clean up.

`scan-build cmake -DCMAKE_BUILD_TYPE=Debug -GNinja .. && scan-build ninja`
`scan-build: 40 bugs found.`

**Comment by edg-l** [comment]
`scan-view` to examine the generated report creates a website, that can be cool too

**Comment by heinrich5991** [comment]
@Learath2 Can you post the results?

**Comment by Learath2** [comment]
![sv](https://user-images.githubusercontent.com/490500/95692483-6d7aff80-0c26-11eb-87b7-bd5978b49010.png)

**Comment by edg-l** [comment]
https://ryozuki.xyz/ddnet-scan/2020-10-12-121550-3520-1/
