### ISSUE TITLE
e84d3a2 introduces performance problems and graphics tearing on my toaster

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#3072]
e84d3a2 makes the game jittery all the time, even though my fps (cl_showfps 1) doesn't drop at all. It hurts my eyes and affects my ability to play the game. There's also occasional tearing. I tried capturing it on video but it's kinda hard to notice in the video for some reason. I used git bisect to determine that this is the commit that introduces the jittery-ness and graphics tearing.

@Jupeyy can you please post the specs of the pc you test this with? keep in mind tw is a "[A retro multiplayer shooter](https://www.teeworlds.com/)", which implies that it should work on older computers such as my own.

My specs:
$ cat /proc/cpuinfo
> model name	: Intel(R) Core(TM)2 Duo CPU     E6550  @ 2.33GHz

$ lspci
> 00:02.1 Display controller: Intel Corporation 82Q35 Express Integrated Graphics Controller (rev 02)

2GB ram.

sure by modern standards this PC is a "toaster", but honestly it ain't all that slow and I've done ***3D*** gaming on muuuch slower computers

**Comment by d3fault** [comment]
I tried to do a git revert (so I could submit a PR) but it broked the game :(

**Comment by Jupeyy** [comment]
I don't see how that commit can break anything except if the tileset is not divisible by, ,16… which should rarely be the case, can you find the real commit

**Comment by Jupeyy** [comment]
You might be fallen in the opengl 1.x fallback, it doesn't build mipmaps, which might make the game oversharp.

if that is the GPU:
https://feedback.wildfiregames.com/report/opengl/device/Intel(R)%20Q35

Mesa 10.3.2 claims to support opengl 2.1, maybe try that version or any newer version

**Comment by Jupeyy** [comment]
If there is still an interest in this, reopen when you feel like it
