### ISSUE TITLE
make gfx_quad_as_triangle default 0 again?

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#3097]
As far as i can see it was added for the android support, bcs Android does not support GL_QUADS.
The config says "(fixes quad coloring on some GPUs)", but the question is, is it worth the performance loose, and is the info text only meant for android??

(only affects GL versions prior to 3.3, bcs in 3.3+ it was removed anyway)

**Comment by Jupeyy** [comment]
we could also just using quads for the ingame quads, not for everything

**Comment by def-** [comment]
Performance difference?

**Comment by Jupeyy** [comment]
yeah will be better:
#177

this was the issue appearently

**Comment by def-** [comment]
But some people could still have the issue, right?

**Comment by Jupeyy** [comment]
thats why i said, we still use triangles for ingame quads, but for the rest(where the color doesnt matter) we can use quads

**Comment by Jupeyy** [comment]
ah i see, my first comment said "using quads" but i meant "using triangles" :D
