### ISSUE TITLE
ddmax_freeze has pixelated curvatures

### ISSUE THREAD

**Issue by saltyElefant** [ddnet/ddnet#3098]
left current version, right redrawn

![screenshot_2020-10-14_16-24-17](https://user-images.githubusercontent.com/46008453/96003568-a4c1fa00-0e3a-11eb-9566-823ed54f4945.png)

Here is the newly drawn image:

![ddmax_freeze_fixed](https://user-images.githubusercontent.com/46008453/96003909-097d5480-0e3b-11eb-92fd-dfe5f9b2def9.png)

**Comment by def-** [comment]
Related to borderfix/add/rem I guess?

Your change looks much better to me, thanks. I'll make a PR to add it.

**Comment by saltyElefant** [comment]
The original just was completley opaque.
