### ISSUE TITLE
Editor bug

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#3104]
Reported by Ravie, better ask him for more details

![image](https://user-images.githubusercontent.com/6654924/96118974-946a5780-0eec-11eb-88c1-dff896706a01.png)

**Comment by def-** [comment]
Might be related to https://github.com/ddnet/ddnet/pull/2906

**Comment by Learath2** [comment]
FWIW, I can't see any bug with it on `master`. So Ravie will have to elaborate

**Comment by Chairn** [comment]
Closed with Ravie approval. His new quad cutting tool somehow circumvent the problem.
