### ISSUE TITLE
Solve the issue of exploding amounts of config options around chat

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#3106]
Needs to be solved before a release with #3093.

**Comment by heinrich5991** [comment]
See the discussion of that PR for more details.

**Comment by heinrich5991** [comment]
Apparently #3113 now included two more config options. Find a sane default and remove them.

**Comment by def-** [comment]
For me currently https://github.com/ddnet/ddnet/issues/3164 is a must have, then we can remove the options. But expect lots of backlash at removing these options, even before release. People already complained to me in Discord DMs because they watched @Banana090's video and it had more options and they want them.

**Comment by b3z** [comment]
Might be an idea to not have customization in settings but just in the config? I guess only hardcore tw players want to customize that much and those are customizing their config anyway?

**Comment by def-** [comment]
No, the idea is to reduce the number of configs that can interact with each other. Because there are many bugs hiding in untested combinations of config options.

**Comment by Banana090** [comment]
Omg, it causes so many bugs to just not go through background drawing loop...

**Comment by def-** [comment]
@heinrich5991 any idea about this issue? I think it's best to have the 2 options for the chat that were introduced because some people will like different styles. A few people asked me about them on Discord already.

**Comment by heinrich5991** [comment]
People will always like different styles, but going down that road results in complexity. It's hard to say no to config options, it's always easier to add just one more config option, shifting the burden to the future.

I'd say get rid of one of the two options.
