### ISSUE TITLE
Dyncam_sens replaces user's sens

### ISSUE THREAD

**Issue by nzyuzin** [ddnet/ddnet#311]
`dyncam_mousesens` replaces user's sens if user quits the game with dyncam enabled and dyncam_mousesens set.

This line is at fault:
https://github.com/ddnet/ddnet/blob/master/src/game/client/components/camera.cpp#L133

Only solutions that come to my mind would be to hold regular mousesens in a special config var and set value of one of two vars (`dyncam_mousesens` and `users_mousesens`) in `inp_mousesns` when user toggles dyncam. The problem with this solution is that having three mousesens variables is confusing. The other solution is somehow resetting `InpMousesens` to `s_OldMousesens` from linked line on game quit. But that would break saving state of dyncam between sessions.

Both solutions seem hacky to me so I think that it would be better to rewrite all the places in which `InpMousesens` is used and introduce new config variable `dyncam_enabled` which would be set in menu settings. (atm `Camera::ToggleDyncamic` is called there). Depending on value of this variable we would choose which sens to use at the current moment, standard or dyncam.

So that way we can have a cleaner solution, there will be no static variables in camera and it will be clear which sens is regular and which is dyncam sens.

Adding a slider in ui to set dyncam_sens would be great too.

**Comment by def-** [comment]
I'll just rework dyncam entirely and solve this.

**Comment by nzyuzin** [comment]
Good to know, thanks!
