### ISSUE TITLE
laser bounce star thingie doesnt render in beta for some reason

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3111]
> laser bounce star thingie doesnt render in beta for some reason
![screenshot_2020-10-16_10-33-46](https://user-images.githubusercontent.com/2335377/96278776-344fe000-0fd6-11eb-89de-8f89864d751b.png)

reported by louis

**Comment by Jupeyy** [comment]
Still can't reproduce, the shotgun fire effect is also completly off which is fixed already. Maybe it was related.

If new reports come in we can reopen
