### ISSUE TITLE
Spawn player with his wanted weapon

### ISSUE THREAD

**Issue by Banana090** [ddnet/ddnet#3114]
Annoying sound, annoying flickering on the screen. When player dies give him his last weapon on respawn already, without switching it for 3 times. (If there is no his weapon - give default obviously. Or how is it working already. Just immediately)

Reproduce:
1. Take hammer
2. Die

**Comment by heinrich5991** [comment]
Sounds good to me.

**Comment by Chairn** [comment]
cl_reset_wanted_weapon_on_death 0

**Comment by Banana090** [comment]
@Chairn this setting doing nothing

**Comment by Chairn** [comment]
Just tried with master branch and the cl_reset_wanted_weapon_on_death setting is indeed useless. But it does spawn with whatever weapon i had last in hand (tested on solo `Short Sky` map), so i guess it got fixed in between (maybe with new HUD?).
