### ISSUE TITLE
Auto recorded demos wonky

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#314]
Not sure how to reproduce the problem exactly, but I think voting the rcon "restart" or voting for restart causes the demo to stop recording and not even a part of it is saved. It could also be because of switching teams or spectating.

**Comment by H-M-H** [comment]
Okay we have three demorecorders currently, lets define what they are supposed to do:

1. Manual: I guess it is pretty clear here: start recording when requested and stop when requested or map was changed/disconnected and save the demo to a file.

2. Auto: It is not that clear here: record from the very beginning (server enter) until disconnect/map change or record each "round" (round needs some further definition).

3. Race: Start recording when touching the startline and stop it when the race is finished.

If I got it right currently we have problems with 2.

**Comment by def-** [comment]
No, we have problems with 3.

**Comment by PathosEthosLogos** [comment]
Was this fixed? So, should this be closed?

**Comment by def-** [comment]
No idea, the main problem is defining the problem in a reproducable way.
