### ISSUE TITLE
Add a weapon system like the skin system

### ISSUE THREAD

**Issue by Zwelf** [ddnet/ddnet#315]
It would be nice if you can select the weapon skin, which is shown in-game.

**Comment by Soreu** [comment]
If it helps - GIE Client have something like this already:

![Screenshot](https://camo.githubusercontent.com/d10b93cda54e8fe9a524f607bbb5e6f8d190c4e6/687474703a2f2f696d672e70696373686172652e61742f313336363133333031365f47616d65736b696e2e706e67)
http://teedes.ru/viewtopic.php?id=77

**Comment by def-** [comment]
I don't see a great use for this, but I guess some people do. Could be ported from one of the other clients if someone is interested.
