### ISSUE TITLE
Mac: stuck in in ingame chat.

### ISSUE THREAD

**Issue by b3z** [ddnet/ddnet#3150]
On Mac, when typing one of those characters ^ or ~ I get stuck in ingame chat and there is no way to legitimately close it or Teeworlds. 

The only way for me is to unplug my router so I get timeout protection and reboot my pc.

Client version: 15.1.3
MacOS 10.15.7 (19H2)

Edit:

When stuck in chat I only can append characters to the open chat.

**Comment by def-** [comment]
@Learath2 Any ideas about this (since you're also on Mac)?

**Comment by b3z** [comment]
Not fixed yet. Wait for @TsFreddie pr
