### ISSUE TITLE
Make chat look better by merging multiple lines from same person/server

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3164]
@Banana090 @Jupeyy Any one of you interested in implementing this? I think it would make the new chat look great.

Basically render all subsequent lines from same author in a single block, with no spacing between them. Then add the chat background around that. Also show the name only once. This should look the same as a long message getting broken over into multiple lines.

**Comment by Jupeyy** [comment]
i'm not sure if its really better, the problem is, that this will make new messages less obvious,
see for example discord:

![image](https://user-images.githubusercontent.com/6654924/96758831-93976100-13d7-11eb-8c74-bb8d6b8a371f.png)

else you might oversee msg that are appended

**Comment by def-** [comment]
Maybe just for server messages then? My main use case was making /top5 look nice again

**Comment by Jupeyy** [comment]
Yes, and i agree with you, it looks really weird, i guess for server messages this makes sense.

**Comment by Banana090** [comment]
it will look 100% bad, really bad. For server messages I have much better idea, waiting for you to implement server messages (the real ones. Packets.) and then I can start to work on it.

**Comment by def-** [comment]
> waiting for you

For me personally? I'm not planning to work on that.

**Comment by Banana090** [comment]
Not you personally of course <3, I mean someone from ddnet development staff. Because I guess I can't implement that

**Comment by Banana090** [comment]
Btw about the topic: I think merging server's messages temporarily for now is a good solution until we implement that thing with packets and move some messages away from chat.
