### ISSUE TITLE
Make the Discord bot congratulate players for every 5000 pts earned

### ISSUE THREAD

**Issue by Banana090** [ddnet/ddnet#3166]
Everything is in the title. That would be cool I guess, because it's kind of achievement for player. Wouldn't even be spam with 5000 pts rate.

More for the topic: there should be some kind of rewards for earning points. This suggestion could be one of them, but named ranks for global leaderboard position that can be shown in game is much better) (Like in CS:GO for example)

**Comment by def-** [comment]
You can make an issue here in jao's repo: https://github.com/12pm/ddnet-discordbot
