### ISSUE TITLE
Scale name/clan in scoreboard if too large

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3174]
As reported by louis on Discord

**Comment by murpii** [comment]
![screenshot_2020-10-22_18-49-16](https://user-images.githubusercontent.com/60477660/97058498-4c9f9c00-158e-11eb-97f5-3de025606be5.png)
louis's image as reference

Learath mentioned this issue before in the dev channel:
https://discordapp.com/channels/252358080522747904/293493549758939136/759054252143542293

**Comment by def-** [comment]
This has been fixed a while ago, they are cut off now and will be ellipsed with #5001
