### ISSUE TITLE
copy server address to clipboard

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#3177]
I find my self tabbing in and out a lot when sharing server ips with friends or similar. A button in the server menu that copys the address to clipboard would come in handy :)

**Comment by def-** [comment]
Browser -> Server address -> ctrl-c

**Comment by ChillerDragon** [comment]
Okay yea did not know about the new UI clipboard mechanics. Not very intuitive but if you know it its fine. So I am happy now but I am sure many people will keep tabbing in and out int the server info. Still worth a additional button?

**Comment by def-** [comment]
ctrl-c is the same as in most other GUI applications. I won't add a button, but you can. Maybe call it `Copy link to Clipboard` and include the `ddnet:` prefix

**Comment by ChillerDragon** [comment]
Yea I do not need it. Also probably not worth the effort to bloat something in there if there is a working alternative. Advertising the ctrl+c feature should do the job.
