### ISSUE TITLE
warn players when they choose a name that already has points on it

### ISSUE THREAD

**Issue by l-ouis** [ddnet/ddnet#3178]
i was thinking it would be awkward to choose a name that someone else already had and find that you already have good times on all novice maps. maybe warn players when they choose a name like "your name already has over 50 points on it"?

**Comment by def-** [comment]
We'd be showing that warning to all regular players when they rename to their own name then, right?

**Comment by 12pm** [comment]
only show it when u launch client first time

**Comment by b3z** [comment]
Maybe already warn in the box where you select the name the first time you startup ddnet.

**Comment by def-** [comment]
This comes directly after that popup. I opted not to do it in the popup to give players a chance to untick whether to send their name to server. When you don't send your name to server, no points check is done obviously.
