### ISSUE TITLE
IME will stuck ddnet on Linux

### ISSUE THREAD

**Issue by sirius1242** [ddnet/ddnet#3185]
In new edition of ddnet (15.1.3), after I typed in Chinese character with IME(fcitx), I can't do anything except appending characters, I even can't send the message or type ESC to quit text editing interface, so I have to kill the ddnet process and restart it. After downgrade to 15.0.5 (with the old text editing method), the problem was solved. This seems won't cause same problem on Windows.

Environment:
Arch Linux with kernel 5.8.14-arch1-1
IME: fcitx 4.2.9.8

**Comment by def-** [comment]
@TsFreddie Can you take a look?

**Comment by b3z** [comment]
Might be related to this problem #3150 ?

**Comment by b3z** [comment]
if you can provide me a bin? @TsFreddie

**Comment by TsFreddie** [comment]
ok. but i need to figure out how to skip circle ci and maybe get the artifact out of github actions. I'm not a mac user sadly.

**Comment by TsFreddie** [comment]
looks like it builds anyway. https://github.com/TsFreddie/ddnet/runs/1305252735?check_suite_focus=true see if you can download the artifact and run that.

**Comment by b3z** [comment]
Yes it runs fine now. It fixes #3150

**Comment by TsFreddie** [comment]
it'll be fine. thx for the notice tho.
