### ISSUE TITLE
Multiple text input bars shown

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3186]
![screenshot-20201025@114416](https://user-images.githubusercontent.com/2335377/97104886-7f917f00-16b7-11eb-9091-715c538db446.png)
Not sure when this started. @Jupeyy any idea?

**Comment by TsFreddie** [comment]
Looks like the IME logic where the edittext cursor is shown. I'll take a look at IME codes again just to make sure.

**Comment by TsFreddie** [comment]
The on the spot text logic is complete fucked in DoEditBox. I'll see if I can fix it.
