### ISSUE TITLE
Effects at 50Hz that works at 100Hz

### ISSUE THREAD

**Issue by CytraL** [ddnet/ddnet#320]
50Hz are working how 100Hz

https://github.com/ddnet/ddnet/blob/master/src/game/client/components/effects.cpp#L276
https://github.com/ddnet/ddnet/blob/master/src/game/client/components/effects.cpp#L298

**Comment by def-** [comment]
No idea.

**Comment by Henningstone** [comment]
The `100` has to be a `50` instead...
