### ISSUE TITLE
TextEx freeze with LTO(or Ofast) under specific conditions

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#3205]
if you name urself(i named my dummy) "BootyShaker3000"
and type "in da room" in the chat, and press tab for scoreboard it freezes reproducable.
This does not happen in normal debug or release mode.

Does not seem to be resolution dependend, and atleast what the LTO build showed it was because of the CTextCursor Compare = *pCursor; (atleast the cursor flag was zero)
calls.
it stopped at the word "room"

LTO is a bit cancer to debug, already happy i could find these stuff. I might try more later

compiler used:
gcc (Debian 10.2.0-15) 10.2.0

**Comment by Banana090** [comment]
I've got these freezes when first making the chat. It was caused by infinite loop inside text render. It tried to break the line and use next line for rest of text, but there also was not enough length, so it tried this again

**Comment by Jupeyy** [comment]
i assume it has todo with if(WordGlyphs <= 3) which might cause the text function to never exit, bcs it always tries to go to the next line, instead of breaking at some point
