### ISSUE TITLE
Support starting without wordlist.txt

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3206]
@Zwelf I find it a bit annoying having to copy both DDNet-Server and wordlist.txt now whenever someone wants to run a DDNet-Server. Maybe we should make it possible to still run without the wordlist and just print a warning?

**Comment by heinrich5991** [comment]
This sounds like we'd ignore the warning in practice. Better to include the wordlist in the executable instead if it's too annoying to copy around separately.
