### ISSUE TITLE
Why does kicking someone from your team kill the entire team

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3207]
Probably with locked team
Reported by Skeith.

**Comment by Banana090** [comment]
That's not a bug. People who kick players from started locked team must be punished

**Comment by Jupeyy** [comment]
> That's not a bug. People who kick players from started locked team must be punished

This is really not a useful contribution, what if he just went afk, or has timeout and told over discord "just kick me". something like that.

**Comment by heinrich5991** [comment]
Should probably have the effect of killing the tee and not the rest of the team.

**Comment by Banana090** [comment]
@Jupeyy did you see any situations like that? If he wants to kill the team he just /lock it and kill. For now I see only Skeith being in such situation that he kicks someone from the same team after starting and he is not right here, so behaviour should stay imo

**Comment by Jupeyy** [comment]
So you answered your own question? Skeith had the situation

**Comment by d3fault** [comment]
Even though I was as surprised as Skeith by this behavior change (it should be documented in the vote prompt I suppose), I'm actually in favor of killing the entire team. But similarly the entire team should be killed when a player leaves that team *for any reason* (disconnect, hit kill tile, etc). Rationale: People could use 64 players to cheat a really hard map, then disconnect all but 2 of those players right before the finish line to make it look like they beat the map with just a 2p team. They could even earn an r1 /teamrank using this strat.

A locked vs unlocked team should not dictate whether or not the entire team gets killed (it should always get killed), but only whether or not you're still in that team after you respawn.

One exception: Dummy maps ofc

**Comment by def-** [comment]
@d3fault Strongly disagree. We allowed playing in large team and having part of the team fail for 7 years. We definitely won't change that now.
