### ISSUE TITLE
Disable chat margin when on score tab

### ISSUE THREAD

**Issue by Banana090** [ddnet/ddnet#3215]
Bug from https://github.com/ddnet/ddnet/pull/3209

To make it look good it should disable new line alignment when scoreboard is active

**Comment by def-** [comment]
Or just turn off chat entirely when scoreboard is shown?

**Comment by Jupeyy** [comment]
So why aren't we just disabling the text alignment, instead of not showing it anymore

**Comment by Banana090** [comment]
Because there are too many problems and difficulties with scoreboard and chat
