### ISSUE TITLE
Fix chat/scoreboard collision

### ISSUE THREAD

**Issue by l-ouis** [ddnet/ddnet#3223]
#3217 fixes the ugly chat when the scoreboard is open, but some mods display stats in the chat at round end when the scoreboard is forced open.

also, some people like to talk in post-round chat ("good game", "gg", etc)

maybe a possible solution would be to allow them to hide the scoreboard by pressing [tab] so they can see chat afterward?

I don't think making the scoreboard smaller would work because on full servers the names are already so small: 
![screenshot_2020-10-31_09-22-31](https://user-images.githubusercontent.com/69405348/97781693-21ebaf80-1b5b-11eb-987b-7eb78b3ab24a.png)

**Comment by b3z** [comment]
You could hide the scoreboard when the chat is opened and go back to the normal "press tab for scoreboard" behavior.
So opening the chat breaks the permanent display of the scoreboard.

**Comment by def-** [comment]
> maybe a possible solution would be to allow them to hide the scoreboard by pressing [tab] so they can see chat afterward?

I like this idea.

**Comment by l-ouis** [comment]
also, opening scoreboard and then pressing [t] (or whatever you have binded to open chat) will open chat, but since it's hidden, you can't see what you're typing.

maybe keep full chat open, but render less of the chat? (i.e. maybe only show one line while scoreboard is active)
not sure if it would still collide with scoreboard, but if it doesn't collide i think it's a good idea so you can at least see a little bit of chat.

**Comment by Jupeyy** [comment]
What exactly is the problem with the old scoreboard / chat behaviour? They only collidate minimally, so just make the chat minimally smaller.
Not worth to kill vanilla based mods

**Comment by def-** [comment]
No, they overlapped totally in 5:4 resolution.

**Comment by Learath2** [comment]
Does it look too confusing if we render the chat behind the scoreboard? Even with the suggested tab solution we should make it clear that there is something to see behind the scoreboard.

**Comment by Jupeyy** [comment]
> No, they overlapped totally in 5:4 resolution.

Then disable it for the 2 users that use 5:4 . 99% have 16:9

**Comment by def-** [comment]
We need a solution here for the 15.2 release. Should we just render it normally behind the scoreboard without resizing as Learath2 suggested?
