### ISSUE TITLE
Client crash when selecting whole map to fill

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#3227]
![Base Profile Screenshot 2020 11 01 - 22 39 33 82](https://user-images.githubusercontent.com/35420825/97816118-2f0bba00-1c93-11eb-9723-af8d84a0aff9.png)

doesnt seem to happen always

**Comment by def-** [comment]
Can't reproduce. Version? Your own build? Debug?

**Comment by fokkonaut** [comment]
It happened on the shipped version

**Comment by Robyt3** [comment]
Do you mean shift-fill? In that case this is probably the same as #5463 and already fixed by #5701.

**Comment by Robyt3** [comment]
Closing as it's likely already fixed. Feel free to comment/reopen if it ever happens again.
