### ISSUE TITLE
gfx_opengl_major 1 by default on Intel GPU on Windows (with bad driver)

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3234]
Seems to have helped multiple people, for example on Discord and Steam: https://steamcommunity.com/app/412220/discussions/0/3003298578159903103/?tscn=1604354661

Not sure if we know the exact bad driver versions, but at least we can do it for Intel + Windows.

**Comment by def-** [comment]
@Jupeyy I would consider this high priority to get into the next release.

**Comment by Jupeyy** [comment]
Ok, i just need a list of driver versions, will ask louis what his driver version is

**Comment by Jupeyy** [comment]
will collect them so i dont need to search discord over and over again
deen: Intel UHD Graphics 620 driver date: 21.01.2020, driver v ersion: 26.20.100.7810
