### ISSUE TITLE
deepfly bind in controls

### ISSUE THREAD

**Issue by l-ouis** [ddnet/ddnet#3239]
just a suggestion - maybe add a place for deepfly in controls? It's a pretty common bind.

**Comment by kamillentee** [comment]
93a0dc3eeec08fe98936d1ba6545c992ed823053

Should be closed

**Comment by dropalways** [comment]
Issue was closed for an issue that was reverted, also as the original issue says its a common bind so it should be in the controls but implemented correctly unlike the original addition
