### ISSUE TITLE
Fat binaries for ARM for macOS

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3250]
Apple will probably soon announce MacBooks with ARM CPUs. We should support them probably. Anyone know yet how this will work, will it be like the old powerpc-supporting fat binaries? Will this work with osxcross?

**Comment by Learath2** [comment]
Can osxcross even create fat machO binaries? MachO has native support for
fat binaries so I would be really surprised if they don't just use that.

**Comment by b3z** [comment]
@Learath2 dangerous link you got there.

**Comment by Learath2** [comment]
Lol, how silly of github not to strip that. Worst case someone unsubscribes me atleast

**Comment by def-** [comment]
Depends on https://github.com/tpoechtrager/osxcross/issues/227

**Comment by def-** [comment]
I'll check if this works with https://github.com/ddnet/ddnet-scripts/commit/629ab30b853004192cc2395a0c5879be70606805

**Comment by def-** [comment]
Will also need https://github.com/discord/discord-api-docs/discussions/3229 for discord sdk
