### ISSUE TITLE
Updated _0.7 mapres

### ISSUE THREAD

**Issue by saltyElefant** [ddnet/ddnet#3288]
![generic_unhookable_0 7](https://user-images.githubusercontent.com/46008453/98588120-73b6d700-22cb-11eb-8bb6-9472f32dbaa0.png)
![grass_doodads_0 7](https://user-images.githubusercontent.com/46008453/98588128-77e2f480-22cb-11eb-97bc-af9899916109.png)
![grass_main_0 7](https://user-images.githubusercontent.com/46008453/98588136-7adde500-22cb-11eb-98b3-76b7660b1ab0.png)

The single tiles on grass_main_0.7 look a bit different now.

**Comment by saltyElefant** [comment]
added the brown tile at top @def- 

![grass_main_0 7](https://user-images.githubusercontent.com/46008453/98649241-aac2d200-2337-11eb-9008-87b7ad450d07.png)

**Comment by def-** [comment]
Thanks
