### ISSUE TITLE
Easy way to distinguish demos that have markers

### ISSUE THREAD

**Issue by BaklavaTee** [ddnet/ddnet#329]
I often add markers (using a bind) while recording a demo to keep track of the good moments. But such moments are rare, and about one demo out of ten contains a marker. So I wish there is an easy way to distinguish them.

Here are some suggestions:
1. Create a folder for marked demos (eg. demos/marked/), and automatically move demos that have markers to this folder.
2. Append a certain suffix for demos that have markers (eg *_marked.demo)
3. In the demo list, show a favorite icon beside marked demos

**Comment by def-** [comment]
The first two suggestions are hacky, the third would be nice, but needs to parse all demos, which would slow down the demo browser significantly.

**Comment by def-** [comment]
I guess let's just append a ! to the demo for now. Any better suggestions?

**Comment by bojidar-bg** [comment]
Append `_marked` to the demo, to both make it clearer, and remove possible problems coming from the special character in the name?

**Comment by def-** [comment]
It's not so easy actually, since we decide on the name when we start recording, but we only know about the marker during the demo. So I guess we'll have to move the demo after it's finished.
