### ISSUE TITLE
Particle traces are not always drawn after 15.1.3

### ISSUE THREAD

**Issue by pure-luck-999** [ddnet/ddnet#3323]
Today I've found out that some players of my DDNet code based mod (infNext) with new DDNet client versions doesn't see some custom entities in my game build up from particle traces. The latest released version that displays them correctly is 15.1.3.

Bisecting on this repository I've found out that commit that changed the behavior was this one:

https://github.com/ddnet/ddnet/commit/8d6148b20b2cde94d8e1fbe0a0dcd0bd81e86acc

Looking in my code I've found that most custom entities that are not drawn correctly uses some trick borrowed from infClass:

```
		CNetObj_Projectile * pObj = static_cast<CNetObj_Projectile*>(Server()->SnapNewItem(NETOBJTYPE_PROJECTILE, m_IDs[NUM_SIDE + i], sizeof(CNetObj_Projectile)));
....
			pObj->m_Type = WEAPON_HAMMER;
```

So when type of CNetObj_Projectile is set to WEAPON_HAMMER or WEAPON_NINJA, the projectile itself were not drawn in teeworlds 0.6/0.7.5 and DDNet prior to 5.2. Instead trace particles were drawn, but now they're not.

There is no adequate substitute to that because setting m_Type to WEAPON_GUN, WEAPON_SHOTGUN or WEAPON_LASER would not only draw a particle that should not be there but will produce a very unpleasant flickering effect as it's position is updated serverside with every snapshot.

This technique were used in my mod (and in infCroya mod too) to draw Infection Circles slowly rotating contours, poison gas random particles and air bubble particles. I cannot think of any solution I could apply server-side to maintain the prior aesthetics and functionality for new DDNet client users.

So if that possible could you revert behavior to the old one? To draw a particle trace even if no particle itself is defined for a weapon. Thanks!

UPD: as this code is similar to infClass one, it affects old infClass servers gameplay too. 

![image](https://user-images.githubusercontent.com/68428243/99437609-c3c51780-2923-11eb-90bd-7f7a3900bd46.png)

![image](https://user-images.githubusercontent.com/68428243/99437637-d0497000-2923-11eb-992b-dc079206f01a.png)

![image](https://user-images.githubusercontent.com/68428243/99437710-e1927c80-2923-11eb-8cf0-a7ee00cdf23a.png)

cc: @Jupeyy

**Comment by def-** [comment]
Did you find out which change exactly is responsible? This is close to software archeology. :D

**Comment by pure-luck-999** [comment]
@def- sure, fixed. Thanks!
