### ISSUE TITLE
str_sanitize_strong mangles UTF-8

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#3329]
Dunno if we should get rid of this function entirely or fix it in a way so it replaces non-ASCII bytes by `?`.

Causes ban reasons to be mangled:

https://cdn.discordapp.com/attachments/293493549758939136/778401637466898472/unknown.png

Apparently caused by this ban reason: للتجربة.

**Comment by Learath2** [comment]
Is it used anywhere else? If not we can get rid of it, I think.

**Comment by heinrich5991** [comment]
Not used anywhere else.

**Comment by def-** [comment]
Wait, so do we want to just send any utf8 ban reason? I don't see any reason to limit it
