### ISSUE TITLE
Rescue (/r) in /practice mode doesn't work with heart

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet#3330]
Everything is in the title. I believe it does'nt work because heart have 1.5 tile radius while rescue check only 1 tile radius so it thinks im not on a freeze tile.
![image](https://user-images.githubusercontent.com/10178629/99531766-87d19700-29a3-11eb-9ed7-95332b39ac4c.png)

**Comment by fokkonaut** [comment]
It's simply because rescue only checks for being on a freezetile, a heart is not a freezetile, its an entity. A simple check if a heart is nearby would be enough to fix this.
