### ISSUE TITLE
Create a DDNet test case for Phoronix Test Suite

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3332]
I want to see some performance numbers on different hardware. I can probably do it myself. The idea would be to play back a representative demo of reasonable length and measure the fps meanwhile.

**Comment by Jupeyy** [comment]
Sounds really cool. does it allow to run different configurations too?
different OGL versions would be nice :D

**Comment by def-** [comment]
Yes, we could probably do that. Also different resolutions etc. I'm trying to set it up atm.

**Comment by def-** [comment]
These are the options I want to do so far:

- Resolutions
- OpenGL 3.3, OpenGL 3.0, OpenGL 2.0, OpenGL 1.4 (are those the interesting ones?)
- Zoom levels
- Windowed, Full Screen
- Demos with few players and many players (~1 min each)

I'll need to implement a profiling mode that runs a demo and then prints the average fps at the end.

**Comment by Jupeyy** [comment]
Yes that sounds good

**Comment by def-** [comment]
We have the possibility to choose between website build, steam build or compile ourself. I'll probably go with compiling ourself for now, also enables benchmarking compiler differences etc.

**Comment by def-** [comment]
Got it working: https://openbenchmarking.org/result/2011189-NE-TEST2240837

**Comment by def-** [comment]
https://openbenchmarking.org/test/def/ddnet
Can be run with `phoronix-test-suite benchmark ddnet`

**Comment by def-** [comment]
> New Test Available:      pts/ddnet     v1.0.1 

https://openbenchmarking.org/test/pts/ddnet-1.0.1
