### ISSUE TITLE
Move 'Show name plates' thread to the 'HUD'

### ISSUE THREAD

**Issue by gerdoe-jr** [ddnet/ddnet#3333]
'Show name plates' is HUD part, imo. It isn't very comfortable to enable/disable whole HUD with tab changing.

**Comment by gerdoe-jr** [comment]
'Theme' part should stay in 'Assets', not in 'General'.

**Comment by Jupeyy** [comment]
I disagree on the Theme thing, it has nothing todo with assets

**Comment by C0D3D3V** [comment]
I do not understand what this issue is about? 
you can just use a bind like: `bind slash "toggle cl_showhud 0 1; toggle cl_showkillmessages 0 1; toggle cl_showchat 0 1; toggle cl_nameplates 0 1"`

**Comment by Jupeyy** [comment]
it's about GUI not about functionality

**Comment by C0D3D3V** [comment]
Ah I see sounds plausible

**Comment by Robyt3** [comment]
Duplicate of #7830.
