### ISSUE TITLE
Move 'bezier.h' and 'bezier.cpp' to 'src/game/client'

### ISSUE THREAD

**Issue by gerdoe-jr** [ddnet/ddnet#3334]
`bezier.h` and `bezier.cpp` are part of client only. Why should it stay in shared directory?

**Comment by fokkonaut** [comment]
Why not? Modded server can use it too without changing much. I think its okay to put "basic" functions like this in a shared directory.

**Comment by gerdoe-jr** [comment]
What is really necessary here can be used in server-side?

**Comment by Learath2** [comment]
It could be utilized for I guess AI routing and stuff? Whatever, it's just a utility class.

**Comment by C0D3D3V** [comment]
For me it looks more like it could be part of /base/
