### ISSUE TITLE
x264 not found, but installed

### ISSUE THREAD

**Issue by rffontenelle** [ddnet/ddnet#3342]
DDNet 15.2.3's build process does not find `libx264` in Arch Linux, even though the package [x264] is installed (as dependency of [ffmpeg]). Not sure if there is any impact in the end result.

It seems [FindFFMPEG.cmake line 9] checks only for libx264, resulting in the following build output:
```
-- Checking for module 'libx264'
Package 'libx264', required by 'virtual:world', not found
```

While the name 'libx264' is not valid in Arch Linux, 'x264' works perfectly:
```
$ pkg-config --cflags x264
-DX264_API_IMPORTS
```

Changing 'libx264' ->  'x264' in [FindFFMPEG.cmake line 9] solved for me, although I assume this would bring a regression for other distros.

Would it be possible to set CMake to also check for 'x264' lib name (instead of only 'libx264')?

**Environment**:
 - distro: Arch Linux 64-bit
 - ddnet version: 15.2.3
 - packages:
   - [x264] 3:0.160.r3011.cde9a93-1
   - [ffmpeg] 2:4.3.1-2
   - [cmake] 3.9.0-1
 - log:
   - [ddnet-15.2.3-1-x86_64-build.log](https://github.com/ddnet/ddnet/files/5575343/ddnet-15.2.3-1-x86_64-build.log)

[FindFFMPEG.cmake line 9]: https://github.com/ddnet/ddnet/blob/master/cmake/FindFFMPEG.cmake#L9
[x264]: https://www.archlinux.org/packages/extra/x86_64/x264/
[ffmpeg]: https://www.archlinux.org/packages/extra/x86_64/ffmpeg/
[cmake]: https://www.archlinux.org/packages/extra/x86_64/cmake/

**Comment by def-** [comment]
I get the same error locally on Linux, but had to add that to get the Windows build working. I should make it work without warning on both somehow.

**Comment by rffontenelle** [comment]
Is it correct to just print a warning, if not x264 is not found? (as I mentioned, I have no idea if this represents any impact and how)
