### ISSUE TITLE
Handle too long translations better

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3345]
Translations can be too long for text buffer and get cut off. We should somehow warn about this.

Text can be too long to be shown in graphics, maybe it can be scaled then?

Not so easy to solve.

**Comment by gerdoe-jr** [comment]
Please, just make something like a comment in `translation.json` of maximum characters amount. Translators would make text that fits. (imho)

**Comment by def-** [comment]
But it's not a fixed amount of characters. 10 times I is smaller than 10 times W

**Comment by gerdoe-jr** [comment]
Im talking about real buffer, because while translating I expected that if your text is too long, last character of this text becomes square.

**Comment by def-** [comment]
How to do this in code is not trivial, and both are relevant here.

**Comment by Chairn** [comment]
Fixed by https://github.com/ddnet/ddnet/pull/4786
