### ISSUE TITLE
Screen always scrollable

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#3347]
![screenshot_2020-11-21_16-52-35](https://user-images.githubusercontent.com/6654924/99881425-194a3e80-2c1a-11eb-9fa1-df756081e383.png)

To reprod.:

input any filter(so the selection is small)
Scroll (with the bar on the right)

**Comment by def-** [comment]
Oh, I never touched the bar on right before, always used scrollwheel.

**Comment by Jupeyy** [comment]
Me2, took me like 5 minutes to find out what i did different to trigger this xD
