### ISSUE TITLE
Allow binding to Escape

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#3351]
Example use case

```
bind Escape say bye
bind Escape +scoreboard
```

**Comment by def-** [comment]
But Escape is used to open menu, that would be annoying, wouldn't it?

**Comment by heinrich5991** [comment]
Escape is currently special-cased for quite a few things, closing the console, opening the game menu, disconnecting in connecting screen.

I don't think it would be a good idea to allow to bind it.

```
bind Escape say bye
```
Bad idea, spammy.

```
bind Escape +scoreboard
```

I guess you'd want to have that for longer than you hold your escape key?

**Comment by ChillerDragon** [comment]
> ```
> bind Escape +scoreboard
> ```
> 
> I guess you'd want to have that for longer than you hold your escape key?

Yea so that the server gets it at least one tick. But probably most + binds are blocked by active menus and so on. Im not sure if there are other use cases than my specific one tbh. I want to tell the server that I closed the Message of the day by pressing ESC and sending scoreboard. I struggle a bit to come up with other use cases. But I do not see why it should not work at all to bind to Escape.

**Comment by heinrich5991** [comment]
Perhaps escape could be made to close the MOTD instead? Would be a clearer shortcut than tab, anyway.

**Comment by ChillerDragon** [comment]
Escape can be used to close the MOTD but then the server does not know you closed it.

**Comment by heinrich5991** [comment]
Okay, what problem are you actually trying to solve? ^^ Why is it the server's business whether you close the MOTD or not?

**Comment by ChillerDragon** [comment]
If a custom mod has UI in the MOTD but I did not mean to dive that off topic in this issue. I think Escape should be a valid key to bind period. If you disagree close the issue please I have a hard time arguing since my use case is not general purpose.

**Comment by Robyt3** [comment]
To support controllers we also need to make this action bindable so all menus can be used with a controller, but Escape should always have the default behavior, so I'm closing this. For mods there should be a better interface than the MOTD (#2875).
