### ISSUE TITLE
Show available weapons, power-ups

### ISSUE THREAD

**Issue by Patiga** [ddnet/ddnet#3362]
It is easy to forget which weapons you already picked up, especially if you haven't used them in a while. Since you have to go through each weapon to check if you have it, i usually just don't do that. Also it happens way too often the players don't realize that they picked up endless hook, making a part much harder than it actually is.

I think displaying the available weapons + power-ups (jetpack, endless hook, infinite jumps, collision stuff, deepfly?, hit others...) would help significantly.
Those pieces of information are either in the chat or just invisible.

Space wise it could be below the hearts/shields (although imo the hearts/shields could be removed for when in a ddnet server anyways)

#198 partially covers this issue

**Comment by def-** [comment]
Definitely more useful than the hearts+shields we currently display, but I think this is part of #198. But we can keep this separately, maybe someone dares to work on it if it's a smaller issue.
