### ISSUE TITLE
Visually separate strong/weak hook

### ISSUE THREAD

**Issue by Patiga** [ddnet/ddnet#3363]
There are many different ways on how this could work + look.
imo, a nice solution would be to have a separate `ddnet_textures.png` image to `game.png` with just a different texture for weak hook.
That image file could be created forwards compatible so that it could hold more textures that might be added in the future.

**Comment by Learath2** [comment]
Uh problem is we only have relatively weak and relatively strong hook, so
until the pair is known, we don't know who is weak who is strong. This
would cause a flickering of the hook texture.

When I first thought about this I considered a bind like hookcol which
highlighted the tees you had strong on.

**Comment by def-** [comment]
I think the bind should just show a number on top of people, so that you can see who has strong on whom, not just for yourself.

**Comment by HiRavie** [comment]
There could be a little + or - icon displayed above names to show who you have a strong or weak hook on, possibly tint them green and red for easier recognition if needed.

**Comment by Patiga** [comment]
I don't really like the idea of a number above tees. An additional symbol is also too much clutter imo.
@Learath2 is the flickering actually noticeable if the weak hook is just a little different, maybe a bit thinner?

**Comment by Learath2** [comment]
If it is too similar it's not easy to notice who is weak who is strong

**Comment by Anime-pdf** [comment]
https://github.com/ddnet/ddnet/pull/3960

**Comment by Anime-pdf** [comment]
should this be closed?

**Comment by Patiga** [comment]
I'm still for this feature, imo it would be much more subtle and user-friendly

**Comment by BloodWod-513** [comment]
> I'm still for this feature, imo it would be much more subtle and user-friendly
I think it looks beautiful now
#3960

**Comment by Patiga** [comment]
@C0D3D3V I would still request this. That display you linked looks more like debug info, nothing I would like to tell someone to turn on.
Having separate hook textures was an idea, which could or could not work, I'm not sure. I would imagine that a slightly thinner hook wouldn't look strange, more like a small contraction after attaching to the other tee.
Maybe there is another way you could do this.

Weak and strong hook is a very central gameplay feature that is not signalled to normal players in nice way afaik
