### ISSUE TITLE
group skins by color/design

### ISSUE THREAD

**Issue by hussainx3** [ddnet/ddnet#3393]
**reduce crowding the  skins** 
by create  skins group by  color/design

**result this=**

1. more  tidy place  and easier to see skins
2. makers the skins can make more than one for same  a skin with other color or design  (without happening overstock to skins)
3. maybe later we can make other things like hat Santa etc.

![بدون عنوان-2](https://user-images.githubusercontent.com/75770812/101723048-8b48d180-3abc-11eb-9220-be3ee116e6ce.png)

**Comment by hussainx3** [comment]
by hussainx3

**Comment by def-** [comment]
Honestly I think the skins are ok as they are now, I don't know if people really change skins all that often.

**Comment by hussainx3** [comment]
yeah but should be trying make best game and this so ugly ,
there is about 20 skins coala and 20 skins kitty etc.

**Comment by hussainx3** [comment]
but if you not like this idea , you still can thinking about group to hats and clothes for skins

**Comment by Banana090** [comment]
Working on the update that solves this issue. Pretty big one, so I need some time

**Comment by Robyt3** [comment]
Doesn't seem worth it. If you have too many skins to organize, you could also delete some. If you want to switch skins really quickly, use binds to change your skin. "Grouping skins by design" is also not an easy problem, unless you simply sort them by name, which is what we already do.
