### ISSUE TITLE
Skin downloading produces graphics lag

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#3398]
When someone with a downloaded skin join or if someone changes the skin to one from the DB that is not available locally, my client lags for up to 2 seconds or so.

This report got triggered by Aoe reporting something similar on Discord, deen suggested it could be the skin downloader which made me investigate it for a bit. Thanks to cris for testing it with me.

The lag appears consistently, but seems to differ in length.

In races, the lag can be absolutely deadly, so I suggest we disable this feature in the next update unless we find a fix for it. A fix might be loading the PNG in the background, but I haven't tested this.

**Comment by heinrich5991** [comment]
Platform: Arch Linux, newest DDNet via Steam.

**Comment by heinrich5991** [comment]
Aoe is on Windows 10, with an SSD.

**Comment by def-** [comment]
Sigh, how come no one noticed this previously? I guess that means the skin downloader has to be removed.

**Comment by Learath2** [comment]
Is it the loading of the png or the download of the skin causing the lag?

**Comment by def-** [comment]
My guess would be disk IO if it takes 2 seconds. I never noticed any spikes, but I'm using an nvme ssd, so maybe not a fair comparison.

**Comment by Jupeyy** [comment]
such a lag almost has to be file IO, so @def- 's solution should be tried :D 

The problem is probably that it loads the skin from file on the main thread, i doubt its the saving after the download

**Comment by heinrich5991** [comment]
Aoe confirmed that it didn't happen again since he disabled skin downloading.

**Comment by Jupeyy** [comment]
Would be a good moment to switch to libpng, which allows memory loading and is more secure, etc.

**Comment by Learath2** [comment]
Saving is already done on a separate worker thread. If we are sure it's
file io, it's definitely the loading. Which we can indeed move to a thread
of it's own.

**Comment by def-** [comment]
> Would be a good moment to switch to libpng, which allows memory loading and is more secure, etc.

Then we have to somehow verify that the PNGs we load are compable with pnglite for Vanilla compat anyway.

**Comment by Jupeyy** [comment]
> > Would be a good moment to switch to libpng, which allows memory loading and is more secure, etc.
> 
> Then we have to somehow verify that the PNGs we load are compable with pnglite for Vanilla compat anyway.

perfect, because vanilla probably crashes on invalid formats, just we had them, before you fixed them a few weeks ago.
Also just to be sure about it again, embedded images still are NOT in PNG format

**Comment by def-** [comment]
I'd accept a PR for libpng, but probably not part of this fix. Seems like more work.

**Comment by heinrich5991** [comment]
Loading in skin downloader thread would be best.
