### ISSUE TITLE
Make averege time more correct

### ISSUE THREAD

**Issue by Banana090** [ddnet/ddnet#3399]
Some sport tournaments (speedcubing for example, which is solving Rubik's cube for time) uses a better approach to calculate average time by simply removing best and worst times from array of tries.
So we could discard about 10-15% of times when calculating average map time to make it more correct and usable.

The other way to do it is calculate what is called "median" rather then average time. The median is:
```
Times.Sort();
If (Times.Length % 2 == 1)
Median = Times[Times.Length / 2];
else
Median =  (Times[Times.Length / 2 - 1] + Times[Times.Length / 2]) / 2.f
````
Which gives you middle time which is more likely to be average

**Comment by Learath2** [comment]
This is called a truncated mean, one problem is that there is no cheap way to calculate this in sql. It takes a bit of work to discard the top and bottom 10%. A mean is also very robust, thought it's still not easy to calculate in SQL.

Do we even display an average somewhere? If so it'd be cheaper and easier to pre-calculate this.

**Comment by Chairn** [comment]
/mapinfo gives you the average time, and it's also shown in server info

**Comment by edg-l** [comment]
I vote for displaying the median too, quoting wikipedia:

> The basic advantage of the median in describing data compared to the mean (often simply described as the "average") is that it is not skewed so much by a small proportion of extremely large or small values, and so it may give a better idea of a "typical" value.

I think this is exactly what happens with ranks.

**Comment by Banana090** [comment]
Median seems to work well in this case. I don't know what you're using for SQL, but sometimes there is a supported MEDIAN function

**Comment by def-** [comment]
Median should work with a window function. MySQL and SQLite need to be supported

**Comment by def-** [comment]
For MariaDB/MySQL this is easy enough to solve:
```
SELECT l.Map, l.Server, Mapper, Points, Stars,
  (SELECT COUNT(Name) FROM record_race WHERE Map = l.Map) AS Finishes,
  (SELECT COUNT(DISTINCT Name) FROM record_race WHERE Map = l.Map) AS Finishers,
  (SELECT ROUND(AVG(Time)) FROM record_race WHERE Map = l.Map) AS Average,
  1 AS Stamp,
  2-1 AS Ago,
  (SELECT MIN(Time) FROM record_race WHERE Map = l.Map AND Name = "deen") AS OwnTime,
  (SELECT MEDIAN(Time) OVER (PARTITION BY Map) FROM record_race GROUP BY Map HAVING Map = l.Map) AS Median
FROM (
  SELECT * FROM record_maps
  WHERE Map LIKE "Springlobe 3"
  ORDER BY
    CASE WHEN Map = "Springlobe 3" THEN 0 ELSE 1 END,
    CASE WHEN Map LIKE "Springlobe 3" THEN 0 ELSE 1 END,
    LENGTH(Map),
    Map
  LIMIT 1
) as l;
```

The problem is SQLite, which I can't get working:
```
WITH
  l AS (SELECT * FROM maps
    WHERE Map LIKE "Springlobe 3"
    ORDER BY
      CASE WHEN Map = "Springlobe 3" THEN 0 ELSE 1 END,
      CASE WHEN Map LIKE "Springlobe 3" THEN 0 ELSE 1 END,
      LENGTH(Map),
      Map
    LIMIT 1),
  LimitMedian AS (select (2 - count(*)) % 2 from race where Map = l.Map),
  OffsetMedian AS (select (count(*) - 1) / 2 from race where Map = l.Map)
SELECT l.Map, l.Server, Mapper, Points, Stars,
  (SELECT COUNT(Name) FROM race WHERE Map = l.Map) AS Finishes,
  (SELECT COUNT(DISTINCT Name) FROM race WHERE Map = l.Map) AS Finishers,
  (SELECT ROUND(AVG(Time)) FROM race WHERE Map = l.Map) AS Average,
  1 AS Stamp,
  2-1 AS Ago,
  (SELECT MIN(Time) FROM race WHERE Map = l.Map AND Name = "deen") AS OwnTime,
  (SELECT AVG(Time) FROM (SELECT Time FROM race WHERE Map = lMap ORDER BY Time LIMIT LimitMedian OFFSET OffsetMedian)) AS Median
FROM l;
```
Error: no such column: LimitMedian

Any ideas?
```

**Comment by Learath2** [comment]
Did you examine the execution plan btw? Might be an expensive query

**Comment by Banana090** [comment]
that's calculated once per hour

**Comment by def-** [comment]
Didn't investigate, but it's fast enough on MariaDB.

**Comment by def-** [comment]
Ok, this is the issue: https://stackoverflow.com/questions/19297321/offset-and-limit-expressions-scope

I guess I need to solve it without LIMIT/OFFSET for sqlite.

**Comment by def-** [comment]
This should work:
```
WITH
  l AS (SELECT * FROM maps
    WHERE Map LIKE "Springlobe 3"
    ORDER BY
      CASE WHEN Map = "Springlobe 3" THEN 0 ELSE 1 END,
      CASE WHEN Map LIKE "Springlobe 3" THEN 0 ELSE 1 END,
      LENGTH(Map),
      Map
    LIMIT 1)
SELECT l.Map, l.Server, Mapper, Points, Stars,
  (SELECT COUNT(Name) FROM race WHERE Map = l.Map) AS Finishes,
  (SELECT COUNT(DISTINCT Name) FROM race WHERE Map = l.Map) AS Finishers,
  (SELECT ROUND(AVG(Time)) FROM race WHERE Map = l.Map) AS Average,
  1 AS Stamp,
  2-1 AS Ago,
  (SELECT MIN(Time) FROM race WHERE Map = l.Map AND Name = "deen") AS OwnTime,
  (SELECT AVG(CASE counter % 2 WHEN 0 THEN CASE WHEN rn IN (counter / 2, counter / 2 + 1) THEN Time END WHEN 1 THEN CASE WHEN rn = counter / 2 + 1 THEN Time END END) OVER (PARTITION BY Map) AS Median FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY Map ORDER BY Time) rn, COUNT(*) OVER (PARTITION BY Map) counter FROM race where Map = l.Map) as r) AS Median
FROM l;
```
