### ISSUE TITLE
/swap

### ISSUE THREAD

**Issue by Banana090** [ddnet/ddnet#3408]
Very useful command /swap [player] which allows you to swap characters of two players from the same team. Even in t0. Do not respawn tees, so there is no physics abuse. And it should go with some cooldown of course. 

A lot of cases to use. Swap parts in team when your teammate can't do it for long. Swap your dummy with real player if you're playing in t0 and there is impossible / hard dummy part

Swap in teams already exists as /save, which is not comfortable to use. In t0 there is swap possibility with timeout abuse

**Comment by Learath2** [comment]
#1103 already discusses this
