### ISSUE TITLE
Client & Server map desync

### ISSUE THREAD

**Issue by Banana090** [ddnet/ddnet#3413]
https://www.youtube.com/watch?v=-RyhFF-PwYw

By Matodor on Discord

Join the Server at specific moment of map changing <<<

**Comment by Matodor** [comment]
![image](https://user-images.githubusercontent.com/1778417/102172421-29201000-3eb2-11eb-872e-28ac45797683.png)
[milk_2020-12-15_07-06-12.zip](https://github.com/ddnet/ddnet/files/5693405/milk_2020-12-15_07-06-12.zip)

**Comment by Robyt3** [comment]
Duplicate of #2804.
