### ISSUE TITLE
Laser puller is not shown pulling in client anymore

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3414]
As reported by Cøke, worked on 15.1.2 server, broken on 15.2.3

**Comment by Learath2** [comment]
This is what I forgot to create an issue about!!! I couldn't debug this

**Comment by Jupeyy** [comment]
35fc1805590a863d73f532fd397ea863c5112266
first bad commit

**Comment by Jupeyy** [comment]
I assume a wrongly set bracket in the dragger code

**Comment by def-** [comment]
I can't reproduce this.

**Comment by Jupeyy** [comment]
@def- its just the bracket you see it when u compare the commit
To reprod, just connect dummy, the bracket for show_other == 2 is wrongly set

**Comment by def-** [comment]
I would prefer to reproduce it before fixing. Unfortunately I don't know how to make a map to recreate this scenario.

**Comment by Jupeyy** [comment]
Open client, strg shift e, add spawn point and few times underneath it, add a dragger, connect a second client or your dummy with show others 2, the one that is not dragged by the dragger can't see the laser
