### ISSUE TITLE
play with zoom out

### ISSUE THREAD

**Issue by hussainx3** [ddnet/ddnet#3421]
when we use zoom out become hard catch anything by hook because the mouse pointer become useless being very far and big

so my suggest

with every (zoom out) reduce where place the pointer can move  and minimize the size

by hussainx3

![zoom out](https://user-images.githubusercontent.com/75770812/102669291-4a794880-419f-11eb-9a5d-12a9e16efefe.png)

**Comment by heinrich5991** [comment]
I closed the PR implementing exactly this feature, thus this should probably be closed as well.
