### ISSUE TITLE
Broken kill message

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3429]
![screenshot-20201220@191958](https://user-images.githubusercontent.com/2335377/102721036-65ab9b80-42f8-11eb-806a-41d2cc10acf8.png)
Just noticed on tournament server, haven't seen this before

**Comment by Jupeyy** [comment]
Do you record auto demos?

**Comment by Jupeyy** [comment]
What i could imagine(if possible) is that this always been like that, that a non connected player leaves and some killmsg is sent, but since our skin changes its now visible, then it should be reprod. in a demo probably

**Comment by Jupeyy** [comment]
Ok can confirm, this is the case, have a killmsg that has no name for either killer or victim and still has a victim and killer id

**Comment by Banana090** [comment]
Seen this before
