### ISSUE TITLE
Rendering Demo should be a loading bar and not display the demo

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3446]
Currently it's very confusing for players. @sirius1242 Any idea how easy that would be? Can we render it in the background or does it have to be shown on-screen?

**Comment by l-ouis** [comment]
its actually helpful, since u can do stuff like toggle entities/change camera viewpoint in the middle of the demo, so if a loading bar is added there should be a checkbox to display the demo as it renders too.

**Comment by sirius1242** [comment]
I have ever thought of that things, including render with command line (without display environment). However, I'm not familiar with SDL, and didn't found the solution currently.
And I think, even if you can hide the rendering interface, you may still need CPU to do h264 encoding, that will still influence the experience of playing.
