### ISSUE TITLE
Weird behavior of ingame server browser if out-of-game server browser is on News page

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#345]
None of the tabs display as active and when you click the currently active tab, the server browser reloads.

**Comment by east** [comment]
Ehm, how do you connect on a server while being on News page?

**Comment by heinrich5991** [comment]
Console command "connect". Might be used by some teeworlds launcher that directly connects to a server (I think someone implemented a teeworlds:// protocol for that once).

**Comment by east** [comment]
Okay. Hm, I can only reproduce "None of the tabs display as active".
> [...] when you click the currently active tab, the server browser reloads.

By active tab you mean the server browser tab ingame? Reload on click of the tab is normal afaik.

**Comment by heinrich5991** [comment]
Yea, but not anymore since I merged a few commits some minutes ago: 24f973613a138895e3bc68207abb63a6ff679d49, edb2270ca14ac527ac2e65dd7d32cfd8f8f67037.

**Comment by east** [comment]
I see, my bad. 
Well, a proper solution would be to seperate the ingame browser tabs from ui_page into an own config variable. When the ingame browser is opened for the first time after server join, we could sync it with ui_page so the user stays in the same browser tab.
