### ISSUE TITLE
infclass class selector broken

### ISSUE THREAD

**Issue by bretonium** [ddnet/ddnet#3454]
In infclass we have a class selector. It looks like this: ![class selector circle](https://user-images.githubusercontent.com/1087672/103248215-fa05a600-4969-11eb-88d6-140de5e5ae2b.png)

Latest ddnet client version 15.2.4 does not show this class selector. git bisect indicates that https://github.com/ddnet/ddnet/pull/3002 is the breaking change.

I expect the circle to be visible in the latest DDNet version.

**Comment by def-** [comment]
@Jupeyy can you look into this?

**Comment by bretonium** [comment]
Thank you. The issue can be reproduced by joining an infclass server (infclassR or "official infclass" servers). If the server is empty, the class selector will be displayed at once, otherwise you might need to wait until the end of the round. Mod code is available at https://github.com/bretonium/my-infclass-server or https://github.com/necropotame/teeworlds-infclass.
