### ISSUE TITLE
updated blockworlds entities (cleaner & playable)

### ISSUE THREAD

**Issue by Brokecdx** [ddnet/ddnet#3464]
![blockworlds](https://user-images.githubusercontent.com/45873126/103425306-c7e68500-4bb1-11eb-9f32-3bc929bd0e21.png)

**Comment by def-** [comment]
Anyone who's playing blockworlds can judge if this is fine?

**Comment by Brokecdx** [comment]
https://user-images.githubusercontent.com/45873126/103459147-41df5100-4d0d-11eb-9978-4f9f0539c88b.mp4
