### ISSUE TITLE
bind shift+kp_5 doesn't work

### ISSUE THREAD

**Issue by l-ouis** [ddnet/ddnet#3475]
binding something like `bind shift+kp_5 say test` will not work, but the other numpad keys with shift will work.

**Comment by def-** [comment]
This is most likely an artifact of how your keyboard works. Works on my keyboard. See https://en.wikipedia.org/wiki/Rollover_(key)

**Comment by def-** [comment]
yaccre found out that this is a Windows issue
![screenshot-20210105@002213](https://user-images.githubusercontent.com/2335377/103589634-241c1280-4eec-11eb-9bf2-f4d912d8b41f.png)
