### ISSUE TITLE
Receiving client info spams the server console

### ISSUE THREAD

**Issue by Henningstone** [ddnet/ddnet#348]
Look at this:
![Spamimage](https://puu.sh/kI73r/9bc445c8cb.png)
That happens with clients that send the info frequently while being connected, i.e. bots etc...

The cause of the problem can be found here:
https://github.com/ddnet/ddnet/blob/master/src/engine/server/server.cpp#L336-L341
This method is called every time a client sends info, so just send the info very often and bam, there you go, gigabytes of log files if many people do this :) [to overdue it...]

Nevertheless, the server should realize if the name had been changed or not, since messages like above are completely useless.

I managed to stop the spam with this easy fix at the above mentioned lines:
```c++
// make sure that two clients doesn't have the same name
	for (int i = 0; i < MAX_CLIENTS; i++)
	{
		if (m_aClients[i].m_State >= CClient::STATE_READY)
		{
			if (str_utf8_comp_names(pName, m_aClients[i].m_aName) == 0)
			{
				if (i != ClientID)
					return -1;
				else
					return 0;
			}
		}
	}
```

// EDIT: It seems like commit https://github.com/ddnet/ddnet/commit/a58ad6aef78d94c297edf890107644401d1302d1 could have broken it, it makes no sense to me that this lines had been removed.
The commit message says "Always check that player names are not equal" and the commit itself removed the only bit of code which did so. @def- do you remember what the intention of removing this was?

**Comment by egon13** [comment]
Hmm i will test that later

**Comment by heinrich5991** [comment]
Should be fixed by https://github.com/ddnet/ddnet/commit/f20a6a49343d3fa3f2b2d58bc11dfae13d646a4f. If not, please respond.
