### ISSUE TITLE
Give warning to new players about joining brutal/insane servers

### ISSUE THREAD

**Issue by l-ouis** [ddnet/ddnet#3486]
Kynilix on discord:
> we need to make a points restriction for Brutal / insane to avoid people with literally 1 hour of gameplay since they started

I think this might be a good idea, similar to the "your name has already been chosen" popup.

For the first time a player joins a brutal/insane map, maybe have a warning like "this map is hard try playing novice first etc etc"? 
(not a point restriction)

Not sure if it would work well, and might not work if a brutal map is voted on a novice server.

**Comment by Banana090** [comment]
The only problem here is you don't know if you joined brutal or not

**Comment by def-** [comment]
I just watched a new player trying noob filter of a Brutal map for 10 minutes, and it's painful. I'm not sure if such a warning would be enough to deter them though, he didn't seem to understand my messages to him either.

**Comment by Robyt3** [comment]
Should be included in #2583.
