### ISSUE TITLE
Menu music plays ingame

### ISSUE THREAD

**Issue by Henningstone** [ddnet/ddnet#349]
to reproduce:
- have the sound activated
- join any server
- go to the settings page -> Sound tab
- uncheck "activate sound" and check it again.
=> music starts playing

Additionally, when leaving the server with this done and the music playing, you will have the music playing _twice_.

**Comment by cinaera** [comment]
Which version are you using?
Can't reproduce unfortunately

**Comment by Henningstone** [comment]
I am using the latest source from the master branch, of cause :) Some commit since this last release may have broken something.

**Comment by Henningstone** [comment]
Ok. Just have one look at [these lines](https://github.com/ddnet/ddnet/blob/master/src/game/client/components/menus_settings.cpp#L934-L943). You'll immediately see that it basically _can't_ work like it should.

**Comment by cinaera** [comment]
Oh, I assumed you mean to enable/disable the background music (:
Hm, the current code for 'use sounds' doesn't look very nice overall
