### ISSUE TITLE
Video recorder is not perfectly fluid

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3491]
When I watch every frame there seem to be some frames duplicated, some skipped. @H-M-H @sirius1242 any idea?

**Comment by sirius1242** [comment]
Emmm, I can't reproduce this problem with ddnet version 15.2.5-1 and ffmpeg version 2:4.3.1-3, and render video in 60fps.
What's the associative arguments for reproducing this problem?

**Comment by def-** [comment]
Oh well, might be another problem only I have. On my system the recorder was slow enough that it's running very slowly. To verify I looked at each frame in mpv and noticed that sometimes frames are duplicated.

**Comment by sirius1242** [comment]
Emmmm, I remembered that the frame gathering tick was calculate by tickspeed and fps argument, so I think it maybe caused by the rounding of calculate result. Does anyone else have same problem?

**Comment by def-** [comment]
Maybe it's because I use vsync and cl_refresh_rate 480?

**Comment by sirius1242** [comment]
I use vsync, too. But my cl_refresh_rate is 0 (infinite).

**Comment by Jupeyy** [comment]
With the video renderer rework, frames should never be skipped (+ #5253)

Reopen if it still happens
