### ISSUE TITLE
Pylint failure centrally but green locally

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3507]
```
datasrc/network.py:1:0: E0611: No name 'NetMessageEx' in module 'datatypes' (no-name-in-module)
datasrc/network.py:1:0: E0611: No name 'NetObjectEx' in module 'datatypes' (no-name-in-module)
datasrc/network.py:1:0: E0611: No name 'NetStringHalfStrict' in module 'datatypes' (no-name-in-module)
datasrc/network.py:360:1: E1123: Unexpected keyword argument 'teehistorian' in constructor call (unexpected-keyword-arg)
datasrc/network.py:399:1: E1123: Unexpected keyword argument 'teehistorian' in constructor call (unexpected-keyword-arg)
datasrc/network.py:403:1: E1123: Unexpected keyword argument 'teehistorian' in constructor call (unexpected-keyword-arg)
```
Locally I have Pylint 2.6.0 vs 2.4.4, failure seen here: https://github.com/ddnet/ddnet/pull/3506/checks?check_run_id=1696328976

**Comment by def-** [comment]
It seems to somehow assume the import will be `datasrc/seven/datatypes.py` instead of `datasrc/datatypes.py`

**Comment by def-** [comment]
I can't reproduce this either on Arch with Pylint 2.6.0 or Debian with Pylint 2.2.2, so no idea what is causing it.

**Comment by Learath2** [comment]
I would love to help but I never got this working locally either. You did :P

I wonder if it has something to do with the cwd.
