### ISSUE TITLE
Do not announce client-dummies to the masters

### ISSUE THREAD

**Issue by Henningstone** [ddnet/ddnet#351]
According to [this discussion](http://pastebin.com/kBPhvKxQ) on IRC, do not count dummies as players in the serverlist.

**Comment by east** [comment]
The server cannot determine what players are dummies.

**Comment by Henningstone** [comment]
This is what needs to be implemented :)

**Comment by east** [comment]
What I meant was that the server cannot determine dummies in general. The only solutions would base on heuristics like analyzing the players movement or searching for similar ip addresses of player&dummy.

**Comment by heinrich5991** [comment]
But we could implement a dummy protocol that says that this connection is a dummy.

**Comment by east** [comment]
And what about players not using the DDNet-Client? Is it worth to do such an update only to have an amount of dummies not listed in the player list?

**Comment by heinrich5991** [comment]
Dunno, could benefit everyone I guess.

**Comment by east** [comment]
I think it would be reasonable to instead switch over to server-side dummies (solves a bunch of other problems).

**Comment by Henningstone** [comment]
My intention was to provide a client which supports the server at hiding dummies to the master's. According to the irc-discussion, only that would match the rules, since having dummies is roughly the purpose of "dummy-drag-race". Idk how far they want to go with their 'rules', but I think that should be fine then right?

**Comment by H-M-H** [comment]
hmm and what about all old ddnet-clients, anyone using them would still make servers break the rules

**Comment by heinrich5991** [comment]
There's nothing breaking the rules per se. It would just be nicer, and allows us to do this in future.

**Comment by def-** [comment]
I don't think this should be done with the current client-dummies, which are totally independent players for the server and should stay so. Instead server-side dummies could be added, which could easily support this, for example from iDDNet.
