### ISSUE TITLE
Graphic bug in menu theme selection menu

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#3516]
![screenshot_2021-01-16_11-15-37](https://user-images.githubusercontent.com/20344300/104809273-63036f80-57ec-11eb-89e0-429af88f5ab3.png)

Tested on 88fb027cb26e91ee0726d0b54802d8455275f03f (self compiled on debian 10)

Also would be nice if one could select a theme using arrow keys (keys bindings always come in handy when the the GUI is buggy)

**Comment by ChillerDragon** [comment]
Hmm I just realized I also have plenty of invisible text in the editor if nobody can reproduce it maybe it is my system or graphics driver.

**Comment by def-** [comment]
Can't reproduce

**Comment by Banana090** [comment]
Seems like something with my PR about list boxes

**Comment by Jupeyy** [comment]
haven't got any reports like this, reopen, if it occurs again
