### ISSUE TITLE
Can't use save code

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3528]
On map Joyride I tried `/save foo`, but got a 3-word save instead. When I try `/load foo` it shows no save code.

My expectation would be that either I have used this save code already or can use it.

**Comment by Patiga** [comment]
I think this problem can be reduced to:
If you try to load a save of another player/name, it shows that it doesn't exist, which is misleading.

**Comment by def-** [comment]
Rather: Two players should be able to use the same save code, or not?

**Comment by def-** [comment]
Rather: Two players should be able to use the same save code, or not?

**Comment by Patiga** [comment]
Sounds good, every unique team constellation as well?

**Comment by def-** [comment]
Ah, that's the annoying part I guess. Makes it expensive to check. So I guess it's ok as it is.

**Comment by Learath2** [comment]
Could we maybe cheapen this check to allow people to use the same pw?

I think a hash with a combination of the password and the team should work in place of just the password as a key in the db

**Comment by Zwelf** [comment]
Learath method would work, but messages like "'%s' doesn't belong to this team" and "'%s' has to be in this team" to help load the savegame won't work anymore.

**Comment by Learath2** [comment]
Ah, I don't think that's really worth it then.

**Comment by Patiga** [comment]
Then maybe inform the player that his password was already in use?
