### ISSUE TITLE
Bind demo player controls

### ISSUE THREAD

**Issue by mahdiG** [ddnet/ddnet#354]
It would be great to have the player controls binded to keyboard/mouse keys.

**Comment by savander** [comment]
stop and play is bindable by demo_play command in console.

**Comment by mahdiG** [comment]
Thanks, I didn't know about demo_play.
But what about speed and ...?

**Comment by H-M-H** [comment]
Mousewheel can be used to adjust speed, is there something else missing ? If not I will close this issue soon.

**Comment by mahdiG** [comment]
Can I bind speed to keyboard keys? With mouse wheel I can't change speed directly from( for example ) 1 to 2. And when the player is hidden ( with esc button ) you can't be sure if you're on the speed you want or not.
