### ISSUE TITLE
Let gameserver tell client which http server to use for http map download?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3546]
Then we could make the CHN servers download maps from chn1.ddnet.tw instead of maps.ddnet.tw (which is not in mainland china because we don't have cloudflare enterprise)

**Comment by gerdoe-jr** [comment]
Then should client separate maps from different databases?

**Comment by Learath2** [comment]
I like the idea in general but I was concerned about the security aspects of this. E.g. what are the consequences of the server being able to make the client do arbitrary GET requests.

> Then should client separate maps from different databases?

The client won't load maps that have wrong sha or crc so putting it all in the same place should work too, but maybe `maps/<db>/` would be good organization-wise?

**Comment by heinrich5991** [comment]
> Then we could make the CHN servers download maps from chn1.ddnet.tw instead of maps.ddnet.tw (which is not in mainland china because we don't have cloudflare enterprise).

I think this is good for third-party servers, however, I don't think we should use it for the DDNet map download server, it'd give players from China bad download speed on non-CHN servers (and perhaps players from non-China bad download speed on CHN servers.

Maybe we could add that to the info we download at the start? I mean the preferred map download server for your current IP address.

**Comment by def-** [comment]
Yep, that would work and sounds better.
