### ISSUE TITLE
echo " _" is highlighted in console

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#3554]
![screenshot_2021-01-27_10-09-49](https://user-images.githubusercontent.com/20344300/105968862-e728e300-6087-11eb-9108-565bfe93252a.png)

Seems to be menu only and not in game

**Comment by fokkonaut** [comment]
While at it, why can't we echo the same message twice?

**Comment by def-** [comment]
> While at it, why can't we echo the same message twice?

Will fix too.
