### ISSUE TITLE
Map changing menu (Call vote)

### ISSUE THREAD

**Issue by Thekid36** [ddnet/ddnet#3563]
When choosing a map, the user can type the map name, the difficulty (stars), completed times and even the average time (I'm guessing is that).
The problem is that the # of completed times/average time doesn't link up with the map, when choosing from that.
Maybe even a filter/orderby system for map search would be great.

Some difficulty (stars) doesn't match up with the map difficulty and (at least for me) it is more accurate to choose by # of completed times, when finding a new map to play with new players.

Edit: another thing is maybe to add wether if you completed the map or not (just llike in the server selection list), showing the personal best time.

**Comment by def-** [comment]
The way it is implemented is a bit hacky and doesn't allow searching/sorting as you want. I would recomment using https://ddnet.tw/players/thekid36/ instead, which allows sorting.

**Comment by Chairn** [comment]
Using browser is probably the best solution and the one i use for several years. It also allow to compare with people you're playing with to find map that none have finished.
