### ISSUE TITLE
add "community skins" download option

### ISSUE THREAD

**Issue by l-ouis** [ddnet/ddnet#3569]
people complain about not having old funny skins like "tank" due to it not fitting teeworld's artstyle

adding these types of skins back into the database isn't the best option because download skins is on by default, meaning people would see unteeish skins. this is bad because the game should have a uniform art style by default.

a possible solution is to add another "community" database where the only guidelines for skins is to be not explicit and not trolls (invisible skin, a 256x128 image filled in with a solid color, etc), and have an opt-in option to download these skins similarly to the main database.

**Comment by plsplsplslol** [comment]
just add back the non teeish skins that are good

**Comment by l-ouis** [comment]
> just add back the non teeish skins that are good

we can add some of the sentimental ones like tank, but some people want skins like aqua.png back, which definitely does not fit the current artstyle and quality requirements.

again, the argument for not adding skins like aqua back is that skins should all be a certain quality level and must generally fit tw artstyle since the option is enabled by default.

**Comment by plsplsplslol** [comment]
tw artstyle is very diverse, I'm not sure what you mean by it

**Comment by heinrich5991** [comment]
Doesn't even need a some webserver setting, I think, a different URL would work, I think. "Just" needs some web UI for sorting these skins into the different folders.

**Comment by Jupeyy** [comment]
i think this would be really useful, and i agree with louis
different url, put a (fun/whatever) link next to the normal skin database, just like (all) with "News" and **default off**.
![image](https://user-images.githubusercontent.com/6654924/114623176-3063f880-9caf-11eb-965c-50732b949ea0.png)

If nobody is against it, i'd like to get to a point where we agree on the implementation:

Should it be just a mirror and the "fun" contains all skins(i guess this is the easiest)
Should the client just try to contact both URLs?(this is probably the nicer way)

**Comment by heinrich5991** [comment]
> Should it be just a mirror and the "fun" contains all skins(i guess this is the easiest)

I'd do this.

**Comment by Jupeyy** [comment]
For the database script:
I'd like it to be aware of, if a png already exists in the mirrored directory, bcs then its also easier to implement the HD database later(also by just altering the URL) and mirroring non existing skins

**Comment by Jupeyy** [comment]
It's maintained by DDNet, skins.tw is a wildcard
Also nicer control over if u want such skins or not.
I'm still for it, but needs website's skin database upgrade

**Comment by murpii** [comment]
PR #5397 implemented this, so the issue can be closed. As for #3742, normal and community skin submissions happen on discord, and with approval from the SkinDB crew, uploaded to the official database.
