### ISSUE TITLE
sometimes when i resize it gets cut off at bottom and top

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3571]
@Jupeyy Can you take a look? louis reports on Discord # bugs:

> sometimes when i resize it gets cut off at bottom and top
> going to borderless in this state also makes the top part of the screen (white bar in pic) just become transparent instead of take up whole screen
> hm couldnt reproduce it easily
> also it's a little unrelated but playing around between borderless/windowed makes my game do the freeze glitch thing

**Comment by Jupeyy** [comment]
that doesnt sound fixable, either borderless works or not

**Comment by Jupeyy** [comment]
i wonder if others can reproduce it too, or if thats an intel thing

**Comment by Jupeyy** [comment]
@def- is borderless meant to be fullscreen always? our current code just disables the windows borders, it doesnt set the fullscreen stuff like SDL_WINDOWS_FULLSCREEN_DESKTOP

**Comment by def-** [comment]
I don't know.
