### ISSUE TITLE
Add runtime Discord support for Linux x86-64

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3580]
Using dlopen: https://linux.die.net/man/3/dlopen

> a subsequent call with RTLD_NOW may force symbol resolution for a library earlier loaded with RTLD_LAZY.

**Comment by def-** [comment]
@edg-l Do you want to take this?

**Comment by heinrich5991** [comment]
I think https://github.com/ddnet/ddnet/pull/3579 would work, with an additional runtime check to only call into the Discord SDK when the glibc version is new enough.

Could only find stuff that outputs a string for querying the glibc version: https://man7.org/linux/man-pages/man3/confstr.3.html.

**Comment by def-** [comment]
But I got the error message before client was running already.

**Comment by heinrich5991** [comment]
Ah, nevermind then.
