### ISSUE TITLE
FPS drops on Map Faye

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3589]
Reported by Pipou:

> Today I noticed that somehow the map faye is bugged
> My fps drop either with the design or with the entities on
> I tried restarting my client, voting the map on another server but it remains the same
> It's also happening to other people too

**Comment by Jupeyy** [comment]
it has quite a few ninja particles, but they should be more optmized now, can he try the release candidate?

**Comment by def-** [comment]
Indeed, that works. Thanks!
