### ISSUE TITLE
shotgun bullets transparent

### ISSUE THREAD

**Issue by l-ouis** [ddnet/ddnet#3591]
![](https://media.discordapp.net/attachments/757720336274948198/805897809802690630/screenshot_2021-02-01_14-29-55.png)

idk how to reproduce, but if I spec then they're at full opacity but when I'm playing they're not for some reason (I was in a /team if that makes any difference)

**Comment by murpii** [comment]
@l-ouis still having this issue after update 15.3?

**Comment by l-ouis** [comment]
haven't seen it in a while, i guess if i don't get it again within a week we can just close this

**Comment by l-ouis** [comment]
update: most likely still a bug, novashock got it too (https://discord.com/channels/252358080522747904/757720336274948198/826454045325656114)

**Comment by murpii** [comment]
This seems to be related to the zoom level aswell. @def-  I couldn't reproduce this though :/



https://user-images.githubusercontent.com/60477660/114026910-1b363680-9877-11eb-9705-21a37767596d.mp4
