### ISSUE TITLE
Top time no longer displayed on KoG servers

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#3599]
Probably a regression from #3492.

From [Discord](https://discord.com/channels/252358080522747904/293493549758939136/806598560308920350):
>[7:54 PM] Jupstar ✪: was there a change in scoreboard, cant see top time on kog anymore
>[7:54 PM] Ryozuki: its a bug
>[7:54 PM] Ryozuki: reported iirc
>[7:55 PM] Ryozuki: i think it has to do with f client stuff
>[7:55 PM] Ryozuki: protocol change
>[7:55 PM] Ryozuki: but idk
>[7:55 PM] Jupstar ✪: oh i c
>[8:01 PM] heinrich5991: ah, that bug needs an issue I think

**Comment by fokkonaut** [comment]
Maybe its also broken on KoGs side, I just recently saw players asking where their rank is after finishing, others answered they have to reconnect

**Comment by Jupeyy** [comment]
I connected with ddnet 14.x and it worked ^^

**Comment by fokkonaut** [comment]
I am currently on a KoG server with 15.2.5 and I can see the top time.

**Comment by Jupeyy** [comment]
But wasnt there change after 15.2.5?

**Comment by fokkonaut** [comment]
well, should have been included in the description...

**Comment by Jupeyy** [comment]
the devs normally create issues with master branch ;)

**Comment by heinrich5991** [comment]
Hm, I think I can reproduce this on official DDNet servers, too.

**Comment by def-** [comment]
> ano: why did time cps stopped working on older clients?

Probably related

**Comment by Chairn** [comment]
Im using 15.2.5, and often can't see server top time as well as personnal best.
