### ISSUE TITLE
Wrong storage settings for DDNet-Server when run from Steam client

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3612]
![unknown](https://user-images.githubusercontent.com/2335377/107751185-5e63a580-6d1d-11eb-92be-e1e9a76b0ea1.png)

**Comment by def-** [comment]
Any suggestions for how best to fix it? Should we cd into the game directory before starting the server?

**Comment by Jupeyy** [comment]
is this caused by 6a79cc3e591e88bc38daa801f9d8269b3e0cfb25 ?

it used datadir/.. for example

**Comment by heinrich5991** [comment]
@def- Can you explain what is expected and what's wrong?

We can change the working directory in the Steam settings.

**Comment by Jupeyy** [comment]
> @def- Can you explain what is expected and what's wrong?
> 
> We can change the working directory in the Steam settings.

appearently ppl with steam version cannot start a local server(maybe windows only), bcs the server doesnt find the autoexec_server.cfg
after putting it into data dir, it worked for them

**Comment by def-** [comment]
> We can change the working directory in the Steam settings.

How?

**Comment by def-** [comment]
Ok, found it and fixed. It was in Installation -> General Installation settings for the Builds.

**Comment by def-** [comment]
Hm, actually this seems to work "as expected". storage.cfg defined to look in USERDIR, DATADIR, CURRENTDIR. But we never look into binary dir. Not sure how to fix this. When you run DDNet.exe with a shortcut on Windows, does the "Run Server" work?
