### ISSUE TITLE
cant change ingame entities using assets menu on 15.3.1

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#3615]
just uses default entities

**Comment by Jupeyy** [comment]
what kind of entities, ddnet?

**Comment by fokkonaut** [comment]
nvm, did something wrong

**Comment by fokkonaut** [comment]
well actually, something is wrong i think. @Jupeyy it didnt use my modified ddnet.png as fallback because my custom f-ddrace entities were not there i think

**Comment by Jupeyy** [comment]
if you want to support other entities than ddnet, you have to create a directory e.g. my_entities
and put the PNGs like the original names, so:
ddnet.png
f-ddrace.png
etc.

**Comment by fokkonaut** [comment]
yeah, i had a folder f-ddrace and only ddnet.png in it. Before the update it just took that, because i selected that folder ingame, and my server sends to use f-ddrace entities aswell as ddnet ones, but now in the new update it just used default ddnet.png instead of my ddnet.png in the folder that was selected.

**Comment by Jupeyy** [comment]
yes, because you added f-ddrace support XD

**Comment by fokkonaut** [comment]
as a fallback it should still go to ddnet.png, which it does, but it doesnt take the one from the selected folder, instead the original one

**Comment by Jupeyy** [comment]
then try to debug why in mapimages.cpp it enters: `if(!ImagePNGLoaded && TryDefault)`
Thats the only case where it seems to use default path, if all others failed
