### ISSUE TITLE
Dummy broken?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3619]
Halp reports broken dummy on Discord @trml ?

https://user-images.githubusercontent.com/2335377/107862935-9c151b00-6e50-11eb-856b-49049ce75d6e.mp4

**Comment by Jupeyy** [comment]
Looks exactly like the bugs they had, when the server wasnt compiled against 15.3 :D

**Comment by trml** [comment]
Was the server running latest master?

**Comment by def-** [comment]
Currently official DDNet servers runs 15.3-devel branch, not master

**Comment by def-** [comment]
Also reported here: https://forum.ddnet.tw/viewtopic.php?t=7091&p=68954#p68954

**Comment by Jupeyy** [comment]
/showall appearently fixes it(ppl on discord said that)

**Comment by def-** [comment]
That's weird. The distance calculation is quite simple. Maybe for dummy we sometimes send wrong size?

**Comment by Jupeyy** [comment]
had this bug now too, zooming one step out fixed it immediately

**Comment by def-** [comment]
Any idea how to reproduce? I checked the code, but it seems fine.

**Comment by Jupeyy** [comment]
Nope, was sheer luck, never happened before

**Comment by murpii** [comment]
projectiles of pistol shots don't show and are muted if you jump (sounds in general are muted if you jump) & laser shots don't bounce (disappears as soon you hit a surface)

**Comment by def-** [comment]
Ok, I have reproduced it. Connect player, connect dummy, zoom in all the way. Disconnect, connect, connect dummy.

ZoomToSend is 0 then. I will look into it and provide a fix.
