### ISSUE TITLE
Hey i was kicked on DDNet srv 2times by Hakuna Matata

### ISSUE THREAD

**Issue by egon13** [ddnet/ddnet#362]
Hey, i was kicked on DDNet srv 2times by Hakuna Matata
1x 
he kicked me for nothing 

i said next wrong move and i write it one DDNet issues
2x 
he kicked me for nothing too

**Comment by east** [comment]
This is not as issue related to the DDNet repository. You can get help on the forum http://forum.ddnet.tw instead.
