### ISSUE TITLE
Rewrite CDragger

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#3622]
I think it would be a great idea to rewrite CDragger class.
On my server I have noticed insane laggs, which are partly caused by draggers, thats because placing one single dragger tile from editor, will create `MAX_CLIENTS` new draggers, so in DDNet 64, for each tee one, and in my mod 128.
All of these draggers need to get snapped, which is not good at all, it creates many snap items and requires many calls to CDragger::Snap which will eat some ressources.
Also, I think there is still a memory leak in CDraggerTeam (?).
I think the best idea would be to handle all connections inside of one CDragger and to only snap one dragger at a time, even with /showothers turned on, it will reduce a lot of traffic and we would not need a weird for loop in CDragger::Snap anymore, since the Snap function is already called once per client.

**Comment by fokkonaut** [comment]
Draggers also have a bug: If the first tee to be dragged is in solo, then a tee from the same tee, but not solo cant be attached. other way round, if a tee is unsolo first and gets dragged, then also solo tees can get dragged.

**Comment by Learath2** [comment]
Need to be careful with this since it can create issues with teehistorian file playbacks in the future. @heinrich5991 could we accommodate for fixing the bug with solo?

**Comment by fokkonaut** [comment]
While at it, I really think it makes more sense to rewrite it a bit so it doesnt generate 64 draggers per dragger...
