### ISSUE TITLE
Suggestion: Add Quebec flag

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#3639]
From [Discord](https://discord.com/channels/252358080522747904/293493549758939136/814142826127818772):
>[3:32 PM] M Emile: Sorry if this isnt the proper channel but who should i ask to have a flag added
>[3:32 PM] M Emile: It would be nice for Québec people to find each other if we had our flag
>[3:40 PM] NeXus: Isnt quebec a city?
>[3:44 PM] NeXus: I think the idea is to only support countries. So you would search for people with a canadian flag
>[4:02 PM] Ama: yeah exactly lets docs ourselfs to random people on the internet
>[4:23 PM] M Emile: @NeXus Quebec is a province in canada, the main point is that quebec is a french province so it would help identify french speakers

Not sure if we have the resources to draw this flag.

Code would be [CA-QC](https://en.wikipedia.org/w/index.php?title=ISO_3166-2:CA&oldid=917202838).
![Flag of Quebec](https://upload.wikimedia.org/wikipedia/commons/5/5f/Flag_of_Quebec.svg)

**Comment by gerdoe-jr** [comment]
If you guys have resources for this and even have resources for another flags then add RU-XX flags too.

_One of them:_

[RU-TA](https://en.m.wikipedia.org/wiki/ISO_3166-2:RU):
![RU-TA SVG](https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_Tatarstan.svg)
