### ISSUE TITLE
SMALL LETTER L and SMALL LETTER I are considered confusable

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3644]
but they shouldn't be, according to https://util.unicode.org/UnicodeJsps/confusables.jsp?a=smile&r=None

Bug on our side or are we just using out of date unicode data?

**Comment by heinrich5991** [comment]
https://github.com/ddnet/ddnet/commit/6d88a29910e6f60aea7950e9ecfb71d6e2c6c860

**Comment by def-** [comment]
So this is intentional? I

**Comment by heinrich5991** [comment]
ӏ (U+04CF) and l (U+006C) are confusable. I guess we could try some other mapping, like mapping U+04CF to capital letter i.

**Comment by heinrich5991** [comment]
Looking at the confusables [of i](https://util.unicode.org/UnicodeJsps/confusables.jsp?a=i&r=None) and [of l](https://util.unicode.org/UnicodeJsps/confusables.jsp?a=l&r=None) doesn't inspire me with confidence that we'll not have overlapping nicks if we make i and lowercase L non-confusable.
