### ISSUE TITLE
Browser unwanted hover effect in player list

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#3646]
while selecting it will still make the hover effect for the player entry under the mode selection

![image](https://user-images.githubusercontent.com/35420825/109268221-0ba0e800-780b-11eb-9be7-7e1c08d33b23.png)

**Comment by def-** [comment]
Known issue, the last element of these lists are still drawn in the background and don't respect the visual limit. Not sure if we already have an issue for it though.

**Comment by Learath2** [comment]
#2990
