### ISSUE TITLE
`/mapinfo` time of 00:00.00 displayed when map not finished

### ISSUE THREAD

**Issue by Zwelf** [ddnet/ddnet#3653]
When calling `/mapinfo` of an unfinished map, I get a time of 00:00.00.

> [2021-02-28 15:18:04][chat]: *** : "Predator 1" by Ama & Tvgucker on Oldschool, ★★✰✰✰, 12 points, released 2 weeks ago, 258 finishes by 240 tees in 46:59 median, your time: 00:00.00
> [2021-02-28 15:18:06][chat]: *** : Zwelf is not ranked

Expected result:
> [2021-02-28 15:20:52][chat]: *** : "Predator 1" by Ama & Tvgucker on Oldschool, ★★✰✰✰, 12 points, released 2 weeks ago, 258 finishes by 240 tees in 46:59 median

**Comment by def-** [comment]
@heinrich5991 related to your recent changes?
