### ISSUE TITLE
fix controls for deepfly / 45 deg angle

### ISSUE THREAD

**Issue by l-ouis** [ddnet/ddnet#3667]
they are broken if you do not have:
mouse1 hammer mouse2 for deepfly 
and
200 sens and 400 mouse_max_distance for 45 degree angle

this will break a lot of people's controls and they will be confused, should either be removed temporarily or fixed quickly. the binds should grab the key binded to those controls and use those instead of using presets.

Also, maybe implement a single key for toggling deepfly similar to the hammerfly bind instead of having a separate key for on/off

**Comment by def-** [comment]
I don't see a good way to fix this, so I guess we should remove it.

**Comment by Learath2** [comment]
A meh way to fix this would be to make these into actual features rather than odd consequences of config options.

The proper way to fix it is a large console overhaul that lets us use config options as input, but given that's unfeasible I guess we can remove it.
