### ISSUE TITLE
Allow people to join team0 at any time

### ISSUE THREAD

**Issue by kamillentee** [ddnet/ddnet#3685]
On maps like the Zadrotos series it is very hard to play in team0 even if this map is very good for t0. With that feature you can start in a team and later join the party in team 0

- Would strenghten team 0, now some of players start in big teams like 6-10people just to avoid not getting away from start with all the bad and blocking players, later they cannot return to team 0
  - big teams have the chance to merge in team0 when their team size got reduced by left/failed players
- makes maps with very bad starts playable while still be playing in t0 later
- when a team got uneven a single player can decide to join team0 when there are players nearby. 
- when team 0 failed they they can start a fast rescue team that skips all the other slow groups in team0 to get to the point where they failed themselves
- failed teams can wait for other players instead of killing

Possible cheats:
- You can use sg bug on maps without spec much easier. It's possible now already but very hard. This alone should not be a reason to decline the idea as most sg bug maps got fixed due to exessive misuse some years ago and the ones left are already cheatable right now
- the same applies to hammerbomb
- feature should not be possible when a map forces team

**Comment by edg-l** [comment]
Big no, easy cheats with this.

**Comment by def-** [comment]
You can also get stuck on the map somewhere because you only triggered switches in team, but not in team 0

**Comment by kamillentee** [comment]
> Big no, easy cheats with this.

That's what I am trying to find out. I already started to collect possible cheats or bugs, would be very helpful if you can list your lots of cheats. I asked some cheaters already and this is so what I came up with so far, it does not look unsolvable.
This feature is very helpful like others before, thinking of /save /load, dummy and dummy copy, kill tiles not killing after finish, the instant hammer or even the possibility to join team0 after finish. All of them opened big cheat possibilities, this one here so far does not open a new cheat but makes it easier.


> You can also get stuck on the map somewhere because you only triggered switches in team, but not in team 0

That's a good catch. You can just cut parts that are normally blocked by doors that way. Copying the switches that changed in team to team0 is cheatable too I guess. 

There is always the possibility to not activate the team0 feature on maps that contain switches. Can even be an optional map setting, even though it would not fix the old maps then.

**Comment by Robyt3** [comment]
Too many downsides, especially the likelyhood if this adding one or more cheats.
