### ISSUE TITLE
Can't load save from 1 player, but other works

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3697]
Reported by anonymous() on Discord:

> when I tried to load a save from my main it said "you don't belong to this team" Then i tried from dummy and it worked

@Zwelf any idea?

**Comment by Learath2** [comment]
noby also reported the exact same issue. I browsed the code a bit but I couldn't spot it. This started happening after we scrapped the C++ connector so @heinrich5991 maybe?

If we could spot it in the logs that could also be useful, maybe it's a failed query?
