### ISSUE TITLE
master server issue -> keeps choosing same master server

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3703]
Instead the server should loop over the available ones.

As a workaround I set the server that works for all in /etc/hosts (done on Japan server now)

**Comment by heinrich5991** [comment]
Explanation of the current behavior: It chooses the one with the lowest load (if it responds at all). If a master is broken and no servers can register there, it'll continue to pick that one.

**Comment by Robyt3** [comment]
Superseded by #5156.

**Comment by heinrich5991** [comment]
This issue was about the old UDP masterserver, even. :D
