### ISSUE TITLE
Using a uppercase character in a searchbox puts the caret in a wrong position

### ISSUE THREAD

**Issue by edg-l** [ddnet/ddnet#3705]
![image](https://user-images.githubusercontent.com/15859336/111038347-b4189400-8428-11eb-912c-21627e615364.png)

**Comment by Jupeyy** [comment]
How to reproduce?
I type Jsd and it looks ok, not perfect, but characters in tw are kinda close.
Also doesnt look like on your screenshot for me

![image](https://user-images.githubusercontent.com/6654924/111041097-dca78a80-8436-11eb-877d-b627bad23d70.png)

**Comment by C0D3D3V** [comment]
Not reproducible
