### ISSUE TITLE
Changes don't apply when setting 'cl_assets_entities'

### ISSUE THREAD

**Issue by WatermelonDriveway** [ddnet/ddnet#3706]
version 15.3.2

Running the command with no value will output the current setting, and running the command with a specific value will highlight the correct option in the assets GUI menu, but the change doesn't actually apply in game.

Discovered this trying to make a bind.  According to Jupstar, "it has no console chain".

**Comment by def-** [comment]
@Jupeyy how about just periodically checking if the value was changed?

**Comment by Jupeyy** [comment]
I think i prefer console chains
