### ISSUE TITLE
/mapinfo - displays wrong map

### ISSUE THREAD

**Issue by H-M-H** [ddnet/ddnet#371]
imp: HMH:  also on my new map "Exit" it says "Experiment" when i do /mapinfo and not "Exit"

I guess it's something like this: **EXIT** --> **EX**per**I**men**T**

**Comment by def-** [comment]
No, it's because sql replication is broken with DDNet Brazil being down.

**Comment by H-M-H** [comment]
ahh ofcourse forgot about that :)
