### ISSUE TITLE
Separation of server messages into a separate list

### ISSUE THREAD

**Issue by hussainx3** [ddnet/ddnet#3712]
3 places for the  Different system messages  to make system messages arranging and clear 
(see the image)
 
![sm](https://user-images.githubusercontent.com/75770812/111328803-9f820900-867f-11eb-8fb8-b201d6773abf.png)

1-(putting system message above the chat not inside) and you have to hold "u" (show chat) for see it to not covering the screen when you play

2-putting icons for every effects like ,unhammer ,endless  etc... until  the save if you have one

3- this messages usually have an ordering related to chat messages this why we should leave it there

Notes

of course  is not necessary do this plan  Literally 

about points  2 we can leave it in chat and putting icons too

**Comment by hussainx3** [comment]
by hussainx3

**Comment by kamillentee** [comment]
Related commits #198 #1673 #2995 #3362 
Those request a better solution for the problem imho

**Comment by hussainx3** [comment]
![system message](https://user-images.githubusercontent.com/75770812/174491876-8c4c32ce-8532-4dae-b389-0db905a86e2f.png)
i think if you put this messages in list like this (/top5 //mpainfo....)
will be easier to read and ofc this list will come up in my screen just
(if i check of top5 or mapinfo no reason to make everyone  see it anyway)

**Comment by Robyt3** [comment]
Shouldn't be another system on top of the chat but separate, see #6825 and #2875.
