### ISSUE TITLE
make it possible to copy text from the console

### ISSUE THREAD

**Issue by NANAMAR** [ddnet/ddnet#3714]
![image](https://user-images.githubusercontent.com/80839147/111488883-b7728f00-874a-11eb-93fd-b9a3baf0f33c.png)

**Comment by Learath2** [comment]
I think @Jupeyy was the last one to be around the textrenderer, do you think this is feasible?

**Comment by Jupeyy** [comment]
I guess as a start we could give the console lines a hitbox and just copy the full line or smth

**Comment by kamillentee** [comment]
#1033

**Comment by Learath2** [comment]
I guess this is a duplicate then
