### ISSUE TITLE
Playing Teeworlds with a Ultrawide Monitor 34" 3440x1440 (21:9)

### ISSUE THREAD

**Issue by 1Baylife** [ddnet/ddnet#3716]
Hello
i already tried to change up the config editor manually, but it isnt working correctly.
Everytime i start the game the loading screen & the Server list etc. looks fine.
It automatically changes ingame in 3440 x 1440 (43:18).
When i try to use another option i have a blackscreen on both sides of the monitor.

**Comment by 1Baylife** [comment]
![image](https://user-images.githubusercontent.com/80917884/111679269-6c777b00-8821-11eb-8174-d4723c5bc6ae.png)

![image](https://user-images.githubusercontent.com/80917884/111679294-7305f280-8821-11eb-8d46-c30ba34ca076.png)

![image](https://user-images.githubusercontent.com/80917884/111679316-78633d00-8821-11eb-88b7-0c26bb1c621d.png)

**Comment by Jupeyy** [comment]
I dunno what exactly your problem is, but the last screen looks correct to me

**Comment by 1Baylife** [comment]
The problem is that its zoomed in check the two pictures and then you can notice the sight difference

**Comment by Jupeyy** [comment]
thats to expected tho, you can zoom out manually

**Comment by 1Baylife** [comment]
i already tried it but it zooms out uneven thats the problem its more space on the top of the screen instead of zooming out even

**Comment by Jupeyy** [comment]
Would it work with more precision, you can try #4096
