### ISSUE TITLE
Prediction/AntipingCode is messy

### ISSUE THREAD

**Issue by H-M-H** [ddnet/ddnet#372]
prediction is done from several places in code and it's hard to extend/improve it without even more hackish code

**Comment by nzyuzin** [comment]
How do you imagine an improvement of the current situation?
Would it be a refactoring of all antiping code to move it to a single class?

**Comment by H-M-H** [comment]
Yes something like this, maybe a class that inherits from gamecore but includes all other stuff required for prediction.

**Comment by heinrich5991** [comment]
I wonder whether we should have a tag for issues that aren't directly actionable. Maybe cleanup already is that tag though..

**Comment by H-M-H** [comment]
@trml maybe you could do something about this as you already have some experience with antiping code ?
Some cleanup is especially interesting for this (would be nice to have a way to add extra infos a clean way): https://github.com/ddnet/ddnet/tree/ddnet_network_character

**Comment by trml** [comment]
@H-M-H Yes. 
Better organization of the prediction code would be nice. Also, sending more information from the server would help.

I don't know if there is a better way of doing it. It doesn't seem that variable sized netobjects are currently possible. And for just adding some new flags this would work.
And if the netobjects needs to be changed at a later time, that would ideally only affect antiping and other ddnet-only features (but maybe also demo playback across different client versions, unless there is a way to exclude these netobjects from demos and replace them with ordinary netobjects).

**Comment by H-M-H** [comment]
@trml the demo stuff will probably be the biggest problem, the rest should be fine as client and server know the ddnet-version of each other, so the server can send different versions of ddnetobjects according to the clientversion (with information about freezetime, solopart, endlesshook...).

**Comment by Ryozuki** [comment]
i think with new antiping code we can close this.
