### ISSUE TITLE
Team ranks considered as failed?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3725]
Every DDNet server is full of failed team ranks in ddnet-server.sqlite, even though they seemed to have succeeded. This leads to duplicate team ranks after running the move_sqlite.py script.

Logs show this:
```
[2021-03-21 11:34:15][sql]: found team rank from same team (old time: 839.919983, new time: 830.780029)
[2021-03-21 11:34:15][sql]: save team score failed: (fetch:stmt:2014): Commands out of sync; you can't run this command
 now
```

Probably related to the MySQL C API change (@heinrich5991)

**Comment by def-** [comment]
See for example https://stackoverflow.com/questions/614671/commands-out-of-sync-you-cant-run-this-command-now

**Comment by def-** [comment]
scripts/remove-duplicate-teamranks.py can clean it up fortunately.

**Comment by Learath2** [comment]
@heinrich5991 ;/

**Comment by def-** [comment]
Still a big problem.
