### ISSUE TITLE
disallow the usage x_ skins on pvp servers

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#3732]
reported by Fera
![unknown](https://user-images.githubusercontent.com/60477660/112234867-be633b00-8c3d-11eb-9659-e744824b6132.png)
^ frozen but not actually frozen
![unknown (1)](https://user-images.githubusercontent.com/60477660/112234937-e94d8f00-8c3d-11eb-8fbf-ea789d78405f.png)
^ invisible

maybe on ddrace aswell?

**Comment by murpii** [comment]
another example
https://user-images.githubusercontent.com/60477660/112235245-88728680-8c3e-11eb-8264-7e228939d209.mp4

**Comment by murpii** [comment]
im drunk

**Comment by SoulyVEVO** [comment]
lmao
