### ISSUE TITLE
x264 library not found, but installed

### ISSUE THREAD

**Issue by rffontenelle** [ddnet/ddnet#3739]
[cmake/FindFFMPEG.cmake] is set to look for "libx264" pkg-config file, but Arch Linux's [x264 0.161] provides "x264" file (`/usr/lib/pkgconfig/x264.pc`). This is causing the following build output:

```
...
-- Checking for module 'libx264'
--   Package 'libx264', required by 'virtual:world', not found
...
```

See [build.log](https://github.com/ddnet/ddnet/files/6206845/ddnet-15.4-1-x86_64-build.log)
See also [x264 package's files](https://archlinux.org/packages/extra/x86_64/x264/files/)

[cmake/FindFFMPEG.cmake]: https://github.com/ddnet/ddnet/blob/4fb8798fd104acde77ea8058d1d00f466470547d/cmake/FindFFMPEG.cmake#L8
[x264 0.161]: https://archlinux.org/packages/extra/x86_64/x264/

**Comment by def-** [comment]
Yeah, I have that since we started bundling ffmpeg. Not sure how to fix it without breaking the bundled build.
