### ISSUE TITLE
Duplicated autoexec_server.cfg

### ISSUE THREAD

**Issue by rffontenelle** [ddnet/ddnet#3740]
**autoexec_server.cfg** is available in both [ddnet/ddnet] and [ddnet/ddnet-maps], with some differences (see 
[autoexec_server.diff.gz](https://github.com/ddnet/ddnet/files/6207484/autoexec_server.diff.gz) -- I had to zip it).

Should they be put in only one place, or be kept in sync?

[ddnet/ddnet]: /ddnet/ddnet
[ddnet/ddnet-maps]: /ddnet/ddnet-maps

**Comment by def-** [comment]
Thanks, I'll update the relevant parts in ddnet-maps repo. (need a while to clone it locally)
