### ISSUE TITLE
autoexec_server.cfg requires reset.cfg, which is not available

### ISSUE THREAD

**Issue by rffontenelle** [ddnet/ddnet#3741]
**autoexec_server.cfg** from this repository requires **reset.cfg** which is unavailable in here. See:
https://github.com/ddnet/ddnet/blob/17d12f16d4b5baa85ab1f07d8124199a1b15b698/data/autoexec_server.cfg#L113
**reset.cfg** is available in [ddnet/ddnet-maps], though.

Should **reset.cfg** be brought to [ddnet/ddnet] ?

[ddnet/ddnet]: /ddnet/ddnet
[ddnet/ddnet-maps]: /ddnet/ddnet-maps

**Comment by def-** [comment]
sv_reset_file defaults to reset.cfg anyway, if it can't be executed that's no problem. So I think all good.
