### ISSUE TITLE
Steam Workshop integration / Streamline user submissions for skins

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#3742]
As of now, skin submissions on discord don't work well. They get lost quick and members of the community don't really know where to submit them. I'd recommend adding the Steam Workshop so people can upload their artworks there for further review by the skin database team. This will hopefully also streamline the process of user submissions.

Possible fix for #3569 maybe?

**Comment by edg-l** [comment]
I'm against this, we shouldn't depend on steam much besides a store where people can find the game and know about it's existance.

If you want to streamline the process we should make some kind of website that makes it possible imho.

**Comment by C0D3D3V** [comment]
I would also like a website for submissions more, that could be linked in game, as well as in steam. Similar to https://skins.tw/
