### ISSUE TITLE
Smooth camera option

### ISSUE THREAD

**Issue by gerdoe-jr** [ddnet/ddnet#3750]
If we have smooth zoom we also should have smooth camera, i.e for movies.

**Comment by Marmare314** [comment]
This might be completed with #6663.

**Comment by Robyt3** [comment]
@gerdoe-jr Did the Multi View solve this issue for you or are your looking for something else? Please provide more details in the latter case.

**Comment by edg-l** [comment]
open another issue if there is still interest, i think the multiview is enough
