### ISSUE TITLE
Client takes almost 10 seconds to start

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet#3757]
Noticed this since i downloaded ddnet skin database. When there are almost 1000 skins, client takes 9.3 seconds to start, while taking only 2 seconds when there are only a 100.

Even worse, if i switch back to open GL 1 (gfx_openfl_major 1), client takes up to 26 seconds to start with 1k skins and 2 seconds with 100 skins.

Im curious to why nobody else complained about this, because im sure some people have way more skins than i do, so it might be related to the 32 bits windows version i use.

**Comment by Jupeyy** [comment]
Its mostly related to the speed of your storage drive.
gl 1.x can be slower if the skin isnt power of 2, which requires rescaling of the textures.

We could lay out storage loading into a different thread, so it doesnt collide with CPU time of components startup, or do a completly lazy loading process, but someone would need to implement it

**Comment by def-** [comment]
Also pnglite being slow? Anyway, there is no reason to download ddnet skin db since we have the skin fetcher.

**Comment by Chairn** [comment]
> 
> 
> Its mostly related to the speed of your storage drive.
Well, for first startup i'd say yes, but then there's system cache and loading time is actually still the same. 1k skins are around 20MB, so not that much.

> gl 1.x can be slower if the skin isnt power of 2, which requires rescaling of the textures.
I guess i would have a warning for this, no?

**Comment by Jupeyy** [comment]
No warning for this. this is a lack in opengl specs, and we cannot really change it, since some ppl actually have GPUs that dont support it and only get white textures

It's only 20MB in loading, but its like this:

storage drive with all its IOPS delay load 1 skin
client creates the texture(maybe rescales it in gl 1.x)
storage drive with all its IOPS delay has to load next skin
and so on.

So its not a continous load and also still alot of small files

**Comment by def-** [comment]
> Doesn't the client keep a local copy after downloading?

Yes, but we actually don't use the downloaded skins then, but redownload them. :D

We could put the skin loading etc at start into a separate thread. But it doesn't seem that important to me, takes 0.3 s on my system with the default skins, which seems bearable.

**Comment by fokkonaut** [comment]
I have 1000+ skins too, and for me only the initial start of the game takes long. When I first launch the game after my pc got booted, then it takes quite a time until the game or the console pops up, no matter how long I wait (so there is nothing in the background eating CPU)

**Comment by Chairn** [comment]
Although it is still currently the same situation, skins database download partially solve the problem so i close this issue.
