### ISSUE TITLE
blue tele broke, hook is no longer kept

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#3766]
https://user-images.githubusercontent.com/60477660/114068508-441df200-989e-11eb-9470-fd47cddbc70e.mp4

First clip actual result, second clip expected result

**Comment by def-** [comment]
@kyle-bradley Related to https://github.com/ddnet/ddnet/pull/3764 ?

**Comment by heinrich5991** [comment]
`ReleaseHooked` is now called all the time. But that releases the hooks of OTHER tees hooking you. That is wrong.

**Comment by def-** [comment]
I guess the lesson is not to change any physics at all. I have reverted all servers to the version with broken swap again.

**Comment by heinrich5991** [comment]
> I guess the lesson is not to change any physics at all.

Or testing. ;) But we don't have the framework for that yet.

**Comment by kyle-bradley** [comment]
I tried to draw attention to it. Wasn't sure what the reason/impact of some of the variations. 

`GameWorld()->ReleaseHooked(GetPlayer()->GetCID());`
Was added to 
- m_SvTeleportHoldHook (guessing this is the above)
- Pause

'm_Core.m_HookPos = m_Core.m_Pos;'
Was added to:
- Pause

Obviously, the variation for m_SvTeleportHoldHook needs to be kept (given the above). Let me know if it is intended to keep paused tees hookable and I'll make the change at the same time.

I should have emphasized these changes and potential side effects in more detail. Will do so in the future if I refactor code like this.

**Comment by kyle-bradley** [comment]
@def- @heinrich5991 thoughts? If not, then come tomorrow I'll keep it for pause and only change the teleport.

**Comment by heinrich5991** [comment]
I'd keep ReleaseHooked out of the ResetHook() function, keeping ReleaseHooked for pause, but not for teleporters.

**Comment by kyle-bradley** [comment]
Perfect, will do just that and put up a PR shortly.

**Comment by heinrich5991** [comment]
Should be fixed by #3768.
