### ISSUE TITLE
net_addr_from_str accepts invalid IP addresses

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#3774]
Examples:
"127.0.0.1a"
"127.0.0.1:1a"

**Comment by gerdoe-jr** [comment]
Huh, interesting, how did you find such bug... Also this issue can be closed, I guess.

**Comment by heinrich5991** [comment]
The tests are still disabled:

https://github.com/ddnet/ddnet/blob/1674a95b2d3bce397884f078e72c05c3b8d31ecf/src/test/netaddr.cpp#L81

The PR #3776 only fixed a different problem.
