### ISSUE TITLE
The X in the ingame menu is unintuitive for beginners

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#3786]
It seems to be expected that the X button in the ingame menu closes the menu, not the game. I played with a couple of new people and they clicked that button to get back to the game after changing their skin.

I don't have a good solution for this yet.

**Comment by fokkonaut** [comment]
Well, there is a warnin for closing the game, I see no problem here?

**Comment by heinrich5991** [comment]
> Well, there is a warning for closing the game, I see no problem here?

No, there is no warning there by default on new installations.

**Comment by fokkonaut** [comment]
Then that's the issue, as I said I would change that.

**Comment by heinrich5991** [comment]
Also, "spectate" in the ingame menu sounds non-destructive. Maybe the spectate button should be removed entirely.

**Comment by Scrumplex** [comment]
Maybe just swap the X with an exit- or power-off-icon? That would make it more clear to most people I think.

**Comment by def-** [comment]
I find that even more confusing. X is the usual symbol on Windows to close an application. For a power-off icon I would expect my computer to turn off.

**Comment by heinrich5991** [comment]
Just to comment on the current state of confusing X: X is usually used to close the window the X belongs to. For DDNet it doesn't close the menu though, but instead closes the whole application.

**Comment by gerdoe-jr** [comment]
Maybe, X should return us to main menu where player easily can press 'Exit' button.

**Comment by Astramast** [comment]
![exitdoor_87195](https://user-images.githubusercontent.com/57040071/120990712-1dd2e080-c781-11eb-9e96-f33ab83ba9c1.png)
Just replace the X by this :)

**Comment by Astramast** [comment]
And maybe add a x button to close the menu left of the quit button if really needed. If u see an X button and an Exit button, with the X button left to the 'last' button, u should logically think that x closes the menu and exit the game. (i would recommend to have only the exit button to avoid problems)

**Comment by heinrich5991** [comment]
I think the power symbol might actually work, I think I've seen other programs/games use it.

**Comment by heinrich5991** [comment]
It seems that every single new person I show this game to runs into this problem. Unless you tell them "when you try to close the menu, DON'T CLICK THE X" very often, they'll quit the client after adjusting sound settings or tee skins.

**Comment by def-** [comment]
https://www.fileformat.info/info/unicode/char/23fb/index.htm is not part of our font, so we'd have to add it.
