### ISSUE TITLE
Switch layer UNUSED tiles

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#3794]
A few updates ago I was able to place unused switch layer tiles (I used the three spawn tile indices). These were the only ones that were placable.
Now EVEN THESE got removed. Could we please get them back or could we get allowed to place all switch indices when UNUSED is activated? My mod relies on it, I am using switch layer because it has so many options with delay and number.

**Comment by gerdoe-jr** [comment]
Sometimes I think each mod should have editor for such purposes. Isn't this only your mod problem? You could revert some changes and work with your version of editor.

**Comment by fokkonaut** [comment]
I sadly can't, because I use switch layer since it has another parameter for each tile "delay" and "number". I see no problem allowing switch layer tiles when UNUSED is activated.
