### ISSUE TITLE
/swap resets switches

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#3806]

**Comment by def-** [comment]
This sounds bad enough that I have turned off /swap again with the timeout hack (unfortunately it still can't be turned off properly).

@kyle-bradley Why are the switches reset?

**Comment by def-** [comment]
Is anyone willing to fix this? Otherwise maybe we should add a setting to turn off swap. The timeout way of turning it off is ugly, people are always confused by it.
