### ISSUE TITLE
Unicode characters can still be used to have same name twice

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#381]
U+200F, U+200E for example

**Comment by heinrich5991** [comment]
Maybe we should enumerate all codepoints that render to nothing.

**Comment by def-** [comment]
`str_utf8_isspace` exists already.

**Comment by heinrich5991** [comment]
So the idea is to skip any "whitespace" while comparing two names?

**Comment by def-** [comment]
Not sure. The right-to-left stuff can also be used in more tricky ways. i'm not sure what the consequences for arabic speakers would be if it's filtered out entirely. From my understand arabic text is currently not correctly set anyway, and can't be entered either.

**Comment by heinrich5991** [comment]
We're currently not interpreting the RTL symbol in any way (and neither does a lib we're emplyoing), so this shouldn't pose a problem.

**Comment by def-** [comment]
Currently used to fake people everywhere.

**Comment by def-** [comment]
Fixed by https://github.com/ddnet/ddnet/pull/385

**Comment by def-** [comment]
Not sure if it's the same bug, but still have mutliple people with identical names on servers.

**Comment by H-M-H** [comment]
identical = same looking or really identical ?

**Comment by def-** [comment]
No idea.

**Comment by def-** [comment]
Haven't seen any since then, so no idea what's causing it. Can't fix without a way to reproduce.
