### ISSUE TITLE
Spec char should not be rendered with show-others-transparency

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#3816]
if the server sends spec char, the client should show it correctly. right now, if a player is in team and you send it's spec char to a client from another team it will render alpha 0.4 * show-others-transparency, which makes it very, very transparent and almost unvisible. Also the nameplate should not use that value. (Server decides when to send the spec-char, so this should not be a problem anyways)

**Comment by fokkonaut** [comment]
![image](https://user-images.githubusercontent.com/35420825/124767018-b94da180-df37-11eb-85b1-e3410495a902.png)
how it is

![image](https://user-images.githubusercontent.com/35420825/124767058-c2d70980-df37-11eb-8ce2-ab710eeddd54.png)
how it should be (can be achieved by going in /pause)

**Comment by trml** [comment]
How about setting it to minimum(0.4, show-others-transparency)? That way one avoids the double transparency, but the setting will still have an effect at lower levels.

**Comment by edg-l** [comment]
I think this is fine as it is

**Comment by fokkonaut** [comment]
I dont think it is. One example is this: Being in a solopart still shows spec-chars of other players, which will look like this (Way too transparent, tee and also the name, this is my issue too, there should be no double-transparency)
![image](https://user-images.githubusercontent.com/35420825/129627253-2d10467f-7b66-434c-84f5-60707cd50012.png)
