### ISSUE TITLE
Is it possible to fix the weird font rendering?

### ISSUE THREAD

**Issue by Nyte-BK201** [ddnet/ddnet#3817]
Latest stable client, game resolution 1440x900 (My display is 1080p).
The latest client's font rendering is weird.
Comparison with the same setting between version 15.4 and 14.2(also version before 14.2):
15.4:
![C7({)8N9CWN6JG}BK$W3JPD](https://user-images.githubusercontent.com/32067657/117528049-d5e65f80-b002-11eb-8fca-7c6fff5cdaf3.png)
14.2:
![Y~)BH@SVZ~@VD~7 KNK$45L](https://user-images.githubusercontent.com/32067657/117528079-f9a9a580-b002-11eb-84c0-c6c01e65e6b4.png)

The latest client renders the lowercase 's' with such a weird and thin waist.. And there are some other similar problems. I thought it was the font difference, but nothing changes after replacing the new font file with the old one.

**Comment by Nyte-BK201** [comment]
I am stuck in version 14.2 due to this rendering update :<

**Comment by Nyte-BK201** [comment]
> We switched to using DejaVuSans always, even with CJK language selected. The Chinese font is only used for the remaining characters. You can update to 15.4 and put the font you like in config_directory.bat in fonts subdirectory (you have to create it first)

Damn, I am changing the font in data/fonts and it doesn't work before I was telling that I should create a subdir in the config directory. What about the fonts in data/fonts? I changed that but nothing changes to the font

**Comment by Learath2** [comment]
This might be caused by the mess of a storage system we have finding some
extraneous data directory. Maybe check the console output to see where the
client thinks the datadir is.

But config-dir should always overwrite datadir, so if you don't want to
bother just put your font in config-dir.

**Comment by Jupeyy** [comment]
> UPDATE: Okay, now I realize the "DejaVuSans.ttf" is working in the latest client, I am dumb. Thx anyway. I think the fonts can be embedded into assets hud inside client like entities.

the reason why we won't do that is, bcs then ppl will complain that the UI breaks even more with other fonts, bcs the UI isnt really made for portability.
That already even happens with other languages selected than english. Would just get even worse then
