### ISSUE TITLE
Suggestion - rework tune_zone_leave

### ISSUE THREAD

**Issue by Bombm** [ddnet/ddnet#3829]
Currently tune_zone_leave NUMBER "x" just sends a server message. It would be useful to be able to run a command with that tune. 
Possible ways I can think of to make it compatible with maps, that currently use this tune would be:
1. Making the argument at "x" take also something like cmd/command and adding third argument if the second argument is cmd/command.
2. Adding a new tune_zone_leave_cmd.

**Comment by C0D3D3V** [comment]
What kind of commands are you thinking about? @Bombm

**Comment by Bombm** [comment]
> What kind of commands are you thinking about? @Bombm

Honestly I already don't quite remember what I was thinking when writing this issue, but I guess I was talking about triggering another tune.
Now that I think of it I feel like if something lke this is gonna be implemented, it would be better to add different tune tiles with different trigger conditions, if that is possible.

**Comment by Bombm** [comment]
> I still do not get it :D Can you not just place another tuning next to that tuning, so that you get other tunings after leaving one zone?

Iirc the idea was that you don't get the tuning effect before entering and then leaving. And someone actually needed that feature for a map, but it was too long ago already

**Comment by C0D3D3V** [comment]
So it sounds like a duplication of https://github.com/ddnet/ddnet/issues/4651

**Comment by heinrich5991** [comment]
Closing as the other issue is more specific.
