### ISSUE TITLE
request nickname when first time joining the name, name update

### ISSUE THREAD

**Issue by ghost** [ddnet/ddnet#3836]
it could be a good way to avoid new players "nameless tee" name. 
when you have nothing as name space or something else it should require a name to avoid (1) name and etc.

**Comment by Boti891** [comment]
the nickname request box should popup for people who has space as their name or nameless tee

**Comment by def-** [comment]
Most new players come from Steam and they already get the Steam name by default.

All new players get the name popup on first startup. I don't see the problem and I haven't seen many nameless tee around recently.

**Comment by gerdoe-jr** [comment]
Can be closed, I suppose?

**Comment by Robyt3** [comment]
The welcome popup which is shown on first start already asks for the player name.
