### ISSUE TITLE
Lower memory consumption

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#384]
DDNet servers take a lot of memory, especially with big maps. For example the recently released Nostalgia map can make a server use 43 MB. Something like run length encoding for the game layers could be used to save a lot of memory in return for some CPU. (might even be cheaper for CPU with better caching)

**Comment by heinrich5991** [comment]
Run length encoding alone would make it O(n) to access a tile. Some index would be needed I guess.

**Comment by def-** [comment]
You can do an RLE per line for example. Oh, I believe teewebs.net already does this, maybe we can just take its code.

**Comment by def-** [comment]
Something like this for RLE: https://github.com/powturbo/TurboRLE

**Comment by def-** [comment]
Probably not a good enough tradeoff.
