### ISSUE TITLE
Font renders red since #3798 (debian 10, gnome on xorg)

### ISSUE THREAD

**Issue by Zwelf** [ddnet/ddnet#3859]
Font renders red with slight black background like this:

![screenshot_2021-05-29_00-35-25](https://user-images.githubusercontent.com/9964758/120047812-d7a9ae80-c015-11eb-8afd-91f3197e78f5.png)

Pinpointed #3798 with git bisect.

System:
* Debian 10 (Gnome 3.30.2 on xorg)

**Comment by Jupeyy** [comment]
forgot to update your shaders?
try that first, most likely

**Comment by Jupeyy** [comment]
e.g. by `cmake ..` or replacing data dir with clean one

**Comment by Zwelf** [comment]
Thanks. That was the issue. It only affected me, since my DDNet start script changed the directory into a different build directory before running the new DDNet binary.
