### ISSUE TITLE
Double serverinfo causes 0 ping

### ISSUE THREAD

**Issue by Learath2** [ddnet/ddnet#3862]
Prior to #322 server sent ingame clients both the vanilla and the old extended serverinfo packets. The double send causes a 0 ping in the new ping calculation. Reported by @Jupeyy

**Comment by Jupeyy** [comment]
@heinrich5991 do you think just updating the token would be ok?

https://github.com/Jupeyy/ddnet/commit/10cde0e6263cbc78a355469868b66614f1338e75

Then the request send, when connecting doesn't collide with this one probably anymore(for servers that dont use ping ex):
https://github.com/ddnet/ddnet/blob/master/src/engine/client/client.cpp#L2808

Atleast i assume this causes it, bcs both packets get the same token

**Comment by heinrich5991** [comment]
Ah, now I understand the bug. Thanks. Will look into fixing it soon. Probably by simply generating a random token there instead of one based on the IP address.
