### ISSUE TITLE
Search text box in search browser gets text when F1 console is open

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3865]
Select the text box first by pressing ctrl-f or clicking on it. Then open console and write something.

Caused by:
```
b7adc5a690216d56fa8636c5efbfd91a5e4fe07d is the first bad commit
commit b7adc5a690216d56fa8636c5efbfd91a5e4fe07d
Author: Jupeyy <jupjopjap@gmail.com>
Date:   Wed May 26 15:01:50 2021 +0200

    Add UI Ex class to share common ui implementations
    between menus and editor for example
```

**Comment by Jupeyy** [comment]
Then this is the side effect of the 4 lines I marked. Too bad, if somebody with knowledge about the whole input stuff has an idea to fix it please tell. Else I'd just revert that PR, dunno any easy solution

**Comment by def-** [comment]
Can you just check whether the console is open and then ignore any inputs?

**Comment by Jupeyy** [comment]
Yeah, but makes the code more and more messy probably, but guess it's fine for ui code xd
