### ISSUE TITLE
Add /team first ! To create teams faster.

### ISSUE THREAD

**Issue by Astramast** [ddnet/ddnet#3878]
So this would be a chat command that put you in the first empty team available, so u delete the situation of when u write /team 1 and it say its locked, then /team 2 and its lock, etc and directly put u in first team number available. I hope its clear ^^"
(/team first or /team random or /team empty or /team -1 or whatever u want)

**Comment by Astramast** [comment]
Do as you wish but please do ;-;

**Comment by Chairn** [comment]
How does the second member join up the same team as fast?

**Comment by Astramast** [comment]
Add /team [teammatename]

**Comment by Astramast** [comment]
Also u can just /invite him, since this cmd works whatever team u are into. (ye im great english speker)

**Comment by Astramast** [comment]
U could also add /accept that automatically put u into the last invite team

**Comment by effyn** [comment]
> 
> 
> Add /team [teammatename]

I really like this idea, also for numeric names you could quote them like /team "15"

**Comment by effyn** [comment]
> 
> 
> Sounds good. I'd prefer making this a new command or a new client message, perhaps even with some UI.

Some suggestions:
- /newteam
- /nextteam
- /randomteam
- /emptyteam
- /freeteam
- /anyteam

**Comment by gerdoe-jr** [comment]
@Astramast, it's already added.

**Comment by C0D3D3V** [comment]
@gerdoe-jr what is already added?

I like the idea of a +team menu. We could bind it on the same key as the sepcator menu.
Also I like the command `/join [playername]`.

**Comment by gerdoe-jr** [comment]
@C0D3D3V I'm sorry for being that late, but I was talking about the main request, https://github.com/ddnet/ddnet/pull/4006
