### ISSUE TITLE
Death Tiles in Front Layer Has Incorrect "Hitboxes".

### ISSUE THREAD

**Issue by TsFreddie** [ddnet/ddnet#3880]
https://github.com/ddnet/ddnet/blob/47d63317aac0c84f540f379686925a17af6fadbf/src/game/server/entities/character.cpp#L1369-L1376

We checking four directions in Game Layer, but only three directions in Front, which makes the front layer's death tiles' hitbox smaller on one ~~side~~ corner. (a triangular hitbox?)

**Comment by Zwelf** [comment]
From the dev-channel:
![unknown](https://user-images.githubusercontent.com/9964758/120895920-670b1f00-c61f-11eb-93fe-e4edb2ae96c2.png)
