### ISSUE TITLE
Ping disappears in serverbrowser when ingame

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3899]
As reported by Quick on Discord
![screenshot-20210612@202149](https://user-images.githubusercontent.com/2335377/121785739-e23e7900-cbbb-11eb-9006-947fb9ba380d.png)
@heinrich5991 any idea?

**Comment by heinrich5991** [comment]
I got another report of this happening. The fix is to not apply the ping to servers that are just placeholders. Will fix in a while.
