### ISSUE TITLE
More than needed to pass, but vote failed anyway

### ISSUE THREAD

**Issue by Soreu** [ddnet/ddnet#390]
Happened just moment ago - twice in a row - on
```DDNet GER - 95.172.92.151:8308```
In case if it matters: I was logged in rcon as admin

First vote:
![screenshot_2015-12-23_15-56-34](https://cloud.githubusercontent.com/assets/14035306/11978799/7df60328-a98e-11e5-87d1-1a01f31bdab9.png)

Second vote:
![screenshot_2015-12-23_15-57-50](https://cloud.githubusercontent.com/assets/14035306/11978807/8debc5ec-a98e-11e5-8259-cb8ad8f0e16c.png)
![screenshot_2015-12-23_15-57-52](https://cloud.githubusercontent.com/assets/14035306/11978813/950fe5f6-a98e-11e5-8095-c0ffc5300e82.png)

**Comment by def-** [comment]
It's not a bug, it's a feature. When someone has spent more than 20 minutes in a map and is not afk they get a veto right. So map change votes will not pass without their yes vote.

**Comment by Soreu** [comment]
There was no info about veto right

**Comment by def-** [comment]
The info is only displayed when the veto guy votes no.
