### ISSUE TITLE
Add marker for configuring new `Ping` label

### ISSUE THREAD

**Issue by gerdoe-jr** [ddnet/ddnet#3901]
It was a way better when I could just check all servers' pings to choose correct one, now I can't see them (color of Russian servers is as yellow as Europeans and marked as `EUR`).

**Comment by gerdoe-jr** [comment]
Switching between old master/http-master?

**Comment by C0D3D3V** [comment]
Maybe we could ping a server as soon as you select it.

**Comment by heinrich5991** [comment]
> Switching between old master/http-master?

No, this won't be supported. The HTTP master is the way forward as it stops some attacks on masterservers and game servers.

> Maybe we could ping a server as soon as you select it.

Pinging a server leaks the client IP address to the server. I think it's better not to send any packets until the user actually wants to connect.
