### ISSUE TITLE
bors keeps timing out on PRs

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3907]
Don't know how to debug bors.

**Comment by heinrich5991** [comment]
Can you link an example?

**Comment by heinrich5991** [comment]
https://app.bors.tech/ has the dashboard, dk if that helps.

**Comment by def-** [comment]
https://github.com/ddnet/ddnet/pull/3906
https://github.com/ddnet/ddnet/pull/3902

**Comment by heinrich5991** [comment]
Found it, see #3908.
