### ISSUE TITLE
0.7 clients buggy in tunezones?

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#3915]
So a friend of mine played with F-Client and got a bug where he only sees scoreboard but not his tee... Luckily, after 30 minutes of racing I could make him use DDNet client and continue via timeout protection.
My guess is its due to a tunezone, but I am definitely not sure. Will ask which map it was later

**Comment by SoulyVEVO** [comment]
same thing happened to me when playing kobra 4 and reaching tune zone

**Comment by fokkonaut** [comment]
![image](https://user-images.githubusercontent.com/35420825/141185210-77e27e3c-68a4-4a0f-9e86-73104d81dc1c.png)
