### ISSUE TITLE
Editor No Mouse When Alt+tab

### ISSUE THREAD

**Issue by Astramast** [ddnet/ddnet#3916]
If u are in editor and u alt-tab, when u come back, u will have no more mouse. U can leave the editor, enter server anything, u will never have your mouse back until u alt+f4. I think u can save with ctrl+s so u don't loose the map but if u are afk-mapping in a server bcs you wait your mate, u cant map anymore without leaving the server :/ Pls fix =-=

**Comment by def-** [comment]
Please try nightly, should be fixed by https://github.com/ddnet/ddnet/pull/3905
https://ddnet.tw/news/nightly-build-revived/

**Comment by Astramast** [comment]
I am not on steam :D
+ could be nice to add the fix in the next patch ❤️

**Comment by def-** [comment]
You don't need Steam to try the nightly.
