### ISSUE TITLE
DDNet 15.5.2 not compatible with Fcitx 4

### ISSUE THREAD

**Issue by phone-burner** [ddnet/ddnet#3919]
DDNet Version: 15.5.2 amd64 steam
Problem: I can't input Chinese characters via Fcitx 4 in DDNet 15.5.2, while DDNet 15.3.2 is okay.

**Comment by def-** [comment]
@TsFreddie Any idea?

**Comment by TsFreddie** [comment]
Never explicitly supported any Linux IMEs. The behavior should be handled by SDL2.

Did we dump our SDL2 version for 15.5?

**Comment by phone-burner** [comment]
Solved. It is Steam that causes this problem. Fixed by replacing DDNet Steam version with official Linux x86_64 version.

**Comment by def-** [comment]
Would be great to report at Steam still.

**Comment by phone-burner** [comment]
> Would be great to report at Steam still.

![IMG_20210621_181108.jpg](https://user-images.githubusercontent.com/51866924/122746075-3af8ca80-d2bc-11eb-8272-0235e455e21f.jpg)
:(

**Comment by def-** [comment]
Meh, sorry that Steam is not taking alternative Linux environments seriously. DDNet client without Steam will always keep working, so you can use that instead.
