### ISSUE TITLE
"Å" isn't found when searching "å" in vote menu and vice versa

### ISSUE THREAD

**Issue by tuhatk** [ddnet/ddnet#3937]
![screenshot_2021-06-28_20-29-33](https://user-images.githubusercontent.com/62926936/123679312-094da980-d850-11eb-8889-da3ab7e1de67.png)
![screenshot_2021-06-28_20-29-35](https://user-images.githubusercontent.com/62926936/123679316-0a7ed680-d850-11eb-89a9-de201fed8a89.png)

**Comment by Learath2** [comment]
I guess we can alleviate this by using a `utf8_tolower` for searching.
