### ISSUE TITLE
Changing map twice causes double free

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#3939]
Found thanks to -Ofast, and weird that address sanitizer does not report this, but looking at it, i'd say it's definitely a bug:

https://github.com/ddnet/ddnet/blob/c24060f2448c5c88d74cffdacc3e09342ca9fa7a/src/game/server/gamecontext.cpp#L98

deletes `m_pScore` without setting it to zero

https://github.com/ddnet/ddnet/blob/c24060f2448c5c88d74cffdacc3e09342ca9fa7a/src/game/server/gamecontext.cpp#L100

initializes gamecontext without setting `m_pScore` to zero either (so at this point `m_pScore` points to invalid memory)

[...]

next time changing the map

https://github.com/ddnet/ddnet/blob/c24060f2448c5c88d74cffdacc3e09342ca9fa7a/src/game/server/gamecontext.cpp#L98
is called, it will delete an already free'd pointer

e.g. setting `m_pScore = 0` in the destructor also solves the issue for me. But i'm not sure if that causes any bugs, so better second opinion on this

**Comment by Jupeyy** [comment]
one note is that mem_zero(this...) is called, maybe undefined behavior?

**Comment by Chairn** [comment]
By the way, deleting null pointer is safe ;)

https://github.com/ddnet/ddnet/blob/master/src/game/server/gamecontext.cpp#L85-L86

**Comment by Jupeyy** [comment]
> By the way, deleting null pointer is safe ;)
> 
> https://github.com/ddnet/ddnet/blob/master/src/game/server/gamecontext.cpp#L85-L86

True, but I personally think its good style to not do it, guess the compiler optimizes it away anyway

**Comment by Jupeyy** [comment]
Anyway asked in stackoverflow, bcs i cannot find anything that look close to this issue, maybe its still a compiler bug, but yet Ofast never betrayed me to find weird code xD

https://stackoverflow.com/questions/68184981/c-is-this-ub-or-a-gcc-bug-mem-zerothis-after-destructor
