### ISSUE TITLE
[Bug] Frozen in arrow tile

### ISSUE THREAD

**Issue by nzyuzin** [ddnet/ddnet#394]
Not sure if it's the right place to report the bug, but here it is. Map is "Dark Rainbow".
![screenshot_2015-12-31_00-27-59](https://cloud.githubusercontent.com/assets/4072673/12056927/8ebc2562-af55-11e5-8715-f15df3c17b78.png)

On screenshot it's seen as I stand in arrow tile and don't move.

**Comment by Ryozuki** [comment]
The speeder just don't have enough power to move you

**Comment by Soreu** [comment]
I'd actually bet it's similar case to when tees get stuck on corners, or when the same "bug" is used to carry other tee, this time just really unlucky

**Comment by nzyuzin** [comment]
So conclusion then -- no bug?

**Comment by H-M-H** [comment]
To be honest: speeders feel like a whole big bug, see #180 for example. Not sure whether this should be fixed though.
