### ISSUE TITLE
Write more files at client close, instead of after fetching

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#3941]
Someone posted a picture of his config directory and had a lot of tmp files:
Then ScReeNy said on discord
"Its win defender blocking permissions for the folder if you refresh the serverlist too frequently, if i recall correctly"

He said its just a guess, but sounds reasonable

In particular ddnet-info.json

**Comment by heinrich5991** [comment]
> "Its win defender blocking permissions for the folder if you refresh the serverlist too frequently, if i recall correctly"
> 
> He said its just a guess, but sounds reasonable

Doesn't sound reasonable to me tbh. That would break a lot of programs. I find it more likely that they opened DDNet with some user that didn't have permission to overwrite the file.

**Comment by Jupeyy** [comment]
> Doesn't sound reasonable to me tbh. That would break a lot of programs. I find it more likely that they opened DDNet with some user that didn't have permission to overwrite the file.

Most users use steam, so even if its some permission problem, its still probably the anti virus, isnt it?
So blocking alot of IO would break many programs just as much, as just not giving write permission at all. In the end its broken vice versa

**Comment by Jupeyy** [comment]
In any way, we could minimize the amount of file IO, whats the sense of writing ddnet-info every time you reload the server browser

**Comment by heinrich5991** [comment]
> Most users use steam, so even if its some permission problem, its still probably the anti virus, isnt it?
> So blocking alot of IO would break many programs just as much, as just not giving write permission at all. In the end its broken vice versa

I'm saying the antivirus program cannot possibly do it. It would break far too many programs if random files don't actually get written out to disk. I do not believe this explanation.

> In any way, we could minimize the amount of file IO, whats the sense of writing ddnet-info every time you reload the server browser

Yea, probably just put it into a new table in the sqlite3 db.

**Comment by Jupeyy** [comment]
> I'm saying the antivirus program cannot possibly do it. It would break far too many programs if random files don't actually get written out to disk. I do not believe this explanation.

Ok, so the users actually start steam as administrator or what is the reason then?
In this case it also probably was the rename that failed not the writing itself.
There was a user, whos config got resettet after a few months without having any tmp files, somehow the read of the file must have failed for that.
I'm just curious if all these problems come from the fact the users started the program at admin at some point
