### ISSUE TITLE
HTTP master invalid serverinfo

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#3944]
With the new http serverinfo the client invalidates servers with more than 64 players.
Read from here: https://discord.com/channels/252358080522747904/293493549758939136/861643948669009940

**Comment by heinrich5991** [comment]
The correct solution is to send the player info for all the players, I think.

**Comment by heinrich5991** [comment]
Plus libtw2 needs to be patched to support more than 64, I guess.

**Comment by Learath2** [comment]
> The correct solution is to send the player info for all the players, I think.

This does increase the size of the serverinfo a fair bit, could it cause 128p servers to be vulnerable to reflection attacks? Maybe the client should display incomplete ones too?

**Comment by heinrich5991** [comment]
> This does increase the size of the serverinfo a fair bit, could it cause 128p servers to be vulnerable to reflection attacks?

More vulnerable, yes. We need the server to upload the server info to the masters instead.

> Maybe the client should display incomplete ones too?

There is no duplicate information in the JSON server info, there is no field for "actual player count", there's only the actual number of players in the player array.

**Comment by heinrich5991** [comment]
No longer needed, have HTTPS masters now: #5064.
