### ISSUE TITLE
Can we attach the binary files of the clients with the releases?

### ISSUE THREAD

**Issue by imcaffrey** [ddnet/ddnet#395]
I can't get access to our [site](http://ddnet.tw), and now I don't know how to get a client.

So I wonder if the binary files of our clients could be attached to the releases.

Thanks.

**Comment by Soreu** [comment]
Site is already back (second or third time, I guess)

**Comment by imcaffrey** [comment]
It is back now. Thanks.

I wonder if the binary files could be provided in [here](https://github.com/ddnet/ddnet/releases)

**Comment by H-M-H** [comment]
Done.

**Comment by imcaffrey** [comment]
:+1:
