### ISSUE TITLE
master servers don't refresh if they weren't found at startup

### ISSUE THREAD

**Issue by trml** [ddnet/ddnet#3951]
If you start the client without an internet connection, the client doesn't find the master servers (or any servers) after you are connected again. Restarting the game solves it, but this can perhaps be a bit unintuitive in some cases.

**Comment by Jupeyy** [comment]
probably bcs this is missing:
https://github.com/Jupeyy/ddnet/commit/7f57d3ed037108f8589f806249f9dae0d447e41a

**Comment by trml** [comment]
I tried on that branch, and it still seems to happen there.
More specifically, this is the message from the console when trying to refresh it: `[serverbrowse_http]: no working serverlist URL found`

**Comment by Jupeyy** [comment]
Ah i see, it just sets the state to DONE if it never succeded before

**Comment by Jupeyy** [comment]
updated the branch

**Comment by trml** [comment]
Yes, seems that was it, tried again and works perfectly now.

**Comment by def-** [comment]
@Jupeyy will this be fixed in a PR?

**Comment by Jupeyy** [comment]
Sure, I won't be able to update it tho if there is any review, since i'm not here the next weaks
