### ISSUE TITLE
LCTRL equals ALT GR

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#3953]
other way round, sorry

**Comment by heinrich5991** [comment]
Please describe what you try, what happens and what you'd like to happen instead. This bug report is near useless.

**Comment by fokkonaut** [comment]
Thought I was in a hurry but I didnt want to forget it. You might wanna read here (can copy it here later) https://discord.com/channels/252358080522747904/293493549758939136/864574906049363969

**Comment by heinrich5991** [comment]
> can copy it here later

That would be nice.

**Comment by Jupeyy** [comment]
I found no way to ask SDL to make it an unique key under windows with a german keyboard sadly,
If you find anything reopen

**Comment by fokkonaut** [comment]
Seems like an old issue for SDL: https://discourse.libsdl.org/t/alt-gr-as-one-key-scancode/19227/4
