### ISSUE TITLE
make invisible assets possible..

### ISSUE THREAD

**Issue by Botipont** [ddnet/ddnet#3976]
i want to make invisible particles for more fps but the game doesnt allow me to use it. is there any limit or something?

**Comment by gerdoe-jr** [comment]
Just paint one pixel somewhere on your asset ;)

**Comment by Botipont** [comment]
doesnt work for me and it shows the default

**Comment by vainiovano** [comment]
Invisible/transparent assets work perfectly for me. You have to ensure that the selected image format is "8bpc RGBA" (or something else that pnglite supports, idk).

[here's a transparent image file that can be used everywhere (game, entities, skins...)](https://user-images.githubusercontent.com/16741932/127729305-9b79fdd3-a248-452c-b77d-6c4d50c501e7.png)

**Comment by Botipont** [comment]
thanks
