### ISSUE TITLE
Feature: allow players to bind commands on connect

### ISSUE THREAD

**Issue by kaitlynia** [ddnet/ddnet#3994]
This would probably be well represented as a separate command, like `bind_connect`
ex. `bind_connect "say /ninjajetpack; say /mapinfo"`

Other useful ideas:
- resetting skin for players that use skin binds
- resetting name / clan for players that sometimes change their name as a joke but forget to change back
- cl_show_others 1/2 for players that normally want to see others and would rather manually turn it off later
- +weapon1 for players that don't normally equip the pistol while racing
- setting an initial zoom level (maybe for quickly spectating the map) that differs from their default

**Comment by C0D3D3V** [comment]
For show_others and zoom, we have settings in the menu. @kaitlynia could you test how far your issue is solved with the new command on join feature?

**Comment by kaitlynia** [comment]
@C0D3D3V
I really need to fix my notification settings on GitHub... Yes, my issue is solved as described. Closed

**Comment by kaitlynia** [comment]
Actually, I realized it's chat commands only. I specifically wanted to use commands like resetting name/skin/weapon/non-default zoom for quick spec and that's all console commands not chat

**Comment by ChillerDragon** [comment]
@kaitlynia what is your use case for this? And could it be replaced by a ``bind key exec your_reset_config.cfg``

**Comment by ChillerDragon** [comment]
I don't think this fits into ddnet given all the similar ideas that got rejected. @kaitlynia you could use a ddnet fork such as the [TaterClient](https://github.com/sjrc6/TaterClient-ddnet) which has ``tc_run_on_join_console``

**Comment by kaitlynia** [comment]
> @kaitlynia what is your use case for this? And could it be replaced by a `bind key exec your_reset_config.cfg`

Less important to me now but my use case was literally in the post above yours :P
