### ISSUE TITLE
Don't play chat sounds when chat is not shown

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#3999]
From [Discord](https://discord.com/channels/252358080522747904/293493549758939136/872012755060817920):
> [9:07 AM] hussainx3: :ddnet: suggesting:ddnet: 
not big thing but will be nice. cancel  the sound for chat on recording when i unshow chat
> ![](https://cdn.discordapp.com/attachments/293493549758939136/872012752674246686/unknown.png)
> [9:13 AM] chillerdragon: @Ryozuki: !!! someone ordered more sound options!!!
> [9:23 AM] plsplsplslol: its not more options
> [9:23 AM] plsplsplslol: just dont show new chat sound when chat is off

**Comment by murpii** [comment]
#3984 
oo

**Comment by heinrich5991** [comment]
Duplicate.
