### ISSUE TITLE
Client Memory Leak

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#400]
The client seems to leak memory if you run it for many hours, just watching people. CPU usage also keeps going up and up. Sometimes it takes up 4 GB and 100% CPU after running for a few hours. Not sure if this happens all the time and how to accelerate it.

Maybe it has to do with these things:
- Finished the map with dummy, just sit in /pause afterwards
- Map is Baby Aim 2.0

An idea to investigate this would be a memory profiler.

**Comment by H-M-H** [comment]
100% CPU is normal if cl_cpu_throttle is set to 0 I guess, does this also happen with cl_cpu_throttle 1 (it doesn't happen for me at least) ?

Some further observation indicates that this problems are connected to dummy, so if the dummy is connected memoryusage keeps increasing.

**Comment by def-** [comment]
Yes, I always run with `cl_cpu_throttle 1`.

**Comment by def-** [comment]
This is pretty bad, even after 1 hour of just playing with dummy it's using 800 MB of memory and 60% CPU already and slowly becoming more laggy.

**Comment by def-** [comment]
From what I can tell so far this is fixed, but would be nice if someone else can verifiy that it works and dummy isn't broken.
