### ISSUE TITLE
Can't build client using MSVS

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#4004]
Due to engine/shared/serverinfo.cpp, use of std::min in two places

**Comment by Jupeyy** [comment]
Is it because windows defines min max macros?
Can you test this:
https://github.com/Jupeyy/ddnet/commit/8c1bd1c2ccad2b54175a9f04e670e90dd9400937

**Comment by Jupeyy** [comment]
It's solved for now by #4099
