### ISSUE TITLE
Bug in editor mode with Blockworlds entities.

### ISSUE THREAD

**Issue by NouaaTW** [ddnet/ddnet#4007]
when we choose "Blockworlds" entities in editor mode and select "unfreeze" tile that put hook-through instead of the real unfreeze.

ps : sometime i had the unhookable instead of hook-through.

https://user-images.githubusercontent.com/75568768/129269453-b88aa32c-de35-4d0e-b52a-9d282b8bacfb.mp4

**Comment by def-** [comment]
Fixed by https://github.com/ddnet/ddnet/pull/4127
