### ISSUE TITLE
[client] [map editor] Alert if layer size too big  / layer size limit

### ISSUE THREAD

**Issue by Ameb** [ddnet/ddnet#404]
Soreu suggested in forum:
> I vote for popup message with info that 500x500 is already huge map (shown during starting first map), or cfg-command to limit max layers size (until someone remove the line) >.>

So maybe adding a max layer size parameter on config. If layer is bigger than parameter, show the pop up.

**Comment by Soreu** [comment]
Better idea from Lady Saavik - just show the popup message whenever someone tries to insert number bigger than 1k in layer-size field:
> **Too big layers**
>
>You are trying to set the height or width of a layer to more than 1000 tiles.
>This is actually possible, but only rarely necessary.
>It may cause editor to work slower, larger file size as well as higher server memory usage.
>Continue anyway?
>
>Ok / Abort

(^ she wrote that)

Of course it should show only once when the number pass "1k border" and once per client-launch

**Comment by H-M-H** [comment]
What about reducing the layersize on save ?

**Comment by CytraL** [comment]
What about check why works slow? All are made to be 'clipped'... no? only works slow in editor? For example... renderGrid can be slow if the map its too big.... and some time ago i see that load process on server side can be improved too.... etc. etc..

**Comment by def-** [comment]
It is slow because the map is hundreds of MB uncompressed.

**Comment by CytraL** [comment]
I not understand what is the problem with the size in memory...

**Comment by Soreu** [comment]
@H-M-H Then every save mappers would have to re-add more space?

**Comment by H-M-H** [comment]
The idea is to make the layers as small as possible on save and yes mappers would need to add more space when they reopen their map and want to add more stuff. Maybe a button like: "optimize layersize" would be sufficient.
