### ISSUE TITLE
Move 'bezier.h' and 'bezier.cpp' to 'src/game/client'

### ISSUE THREAD

**Issue by edg-l** [ddnet/ddnet#4081]
### Discussed in https://github.com/ddnet/ddnet/discussions/4078

<div type='discussions-op-text'>

<sup>Originally posted by **gerdoe-jr** November 18, 2020</sup>
`bezier.h` and `bezier.cpp` are part of client only. Why should it stay in shared directory?</div>

> Was moved to discussions by mistake

**Comment by Learath2** [comment]
It's a utility class, don't need to restrict it just to the client

Wontfix
