### ISSUE TITLE
Don't allow votekicks for first ~30 seconds after map change

### ISSUE THREAD

**Issue by edg-l** [ddnet/ddnet#4082]
### Discussed in https://github.com/ddnet/ddnet/discussions/4066

<div type='discussions-op-text'>

<sup>Originally posted by **d3fault** November 12, 2019</sup>
Players are considered afk immediately after map change as of 547f751 (which admittedly was my idea). SP|Someone leverages this to votekick people immediately after map change since everybody is afk (and their votes aren't counted).</div>

> Was converted to discussion by mistake

**Comment by heinrich5991** [comment]
Duplicate #1966.
