### ISSUE TITLE
Improve start line skip patch

### ISSUE THREAD

**Issue by Learath2** [ddnet/ddnet#4088]
A non started tee leaving the team makes the team unfinishable. This made a couple teams fail some with multiple hours in their timers. Without #3091 system messages are unreadable to some of our players and some players flat out ignore system messages.

Ideas:
1. We could just kill such unfinishable teams
2. We could nag them with system messages every 10s until they switch to practice mode

I don't see a way to address this case properly without falling victim to the case in https://github.com/ddnet/ddnet/pull/3959#discussion_r673216749

**Comment by heinrich5991** [comment]
Ah, I have an idea: Kill the team after one minute if they haven't switched to /practice mode. Sounds good?

**Comment by def-** [comment]
Sounds ok to me
