### ISSUE TITLE
Bind a key for "game" layer in editor

### ISSUE THREAD

**Issue by NitalpAyanami** [ddnet/ddnet#4109]
Hi, I would like to have a keybind  to hide/show the game layer in the editor because use the V icon is really boring and hard. Thanks <3

**Comment by def-** [comment]
There are no binds in editor.

**Comment by NitalpAyanami** [comment]
Yes so it would be nice to have a bind or a key like ctrl+S to save for example. And no game layer is not like front or tele or speedup. It would be cool to have 1 key for every of theses layers.

**Comment by NitalpAyanami** [comment]
I mean having a bind like ctrl+G indeed, wich when pressing it have the same effect than when you press the V icon next to the game layer. Also it would be nice if this bind was only for 1 specific game layer, and if possible it would be nice to have 1 bind for every layers as tele, front game etc.

**Comment by Robyt3** [comment]
Having 6 different hotkeys for all game layers seems excessive. I don't see good hotkeys for all of them that would be easy to remember. For example Tele and Tune can't both be Shift+T. And Switch and Speedup can't both be Shift+S. I don't like using the number keys 1-6 for this either. Adding just one hotkey Shift+G to show/hide all game layers seems more feasible.

**Comment by NitalpAyanami** [comment]
Agree.
