### ISSUE TITLE
Improve player timeout protection to be more accessable

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#4131]
It would be nice to be able to check a players timeout code by either rcon status or via server logs.
As of now it's only possible to see someones timeout code AFTER its been used, I think.

**Comment by edg-l** [comment]
afaik timeout codes are private, right?

Why do you want to see timeout codes?

**Comment by murpii** [comment]
> afaik timeout codes are private, right?
> 
> Why do you want to see timeout codes?

There are a few things which come to my mind.

- Just yesterday I had 2 people unable to claim back their tee after a timeout happened on Impel down.
- Theres a handful of people on discord having the exact same issue, but with a dummy playing on dummy maps.
- People gifting their dummy after someone died, but couldn't claim them for unknown reasons.
etc.

the latter one could be fixed by making /swap available everywhere/in every team including team 0 I guess, but iirc that wasn't something people wanted.

**Comment by murpii** [comment]
deen on discord:
>we hash this with the server ip address for security reasons, so the server doesn't get this exact timeout code
>otherwise one server hoster could steal your timeout code and use it on another server

I'll close this issue then if thats the case. With PR #4383 the occasional problems described above no longer happen, hopefully.
