### ISSUE TITLE
Bug in editor mode.

### ISSUE THREAD

**Issue by NouaaTW** [ddnet/ddnet#4135]
i already created an issue for the editor bug (#4007) and HamidReza585 "fixed" it but now we have another problem, when there is a front tile below the unfreeze we can not place it.

https://user-images.githubusercontent.com/75568768/131590227-62949a27-c864-4fa9-a612-05ec6946aa27.mp4

**Comment by NouaaTW** [comment]
ok so we cant place any tile when there is a front and we cant place a game tile when there is already a game tile

**Comment by def-** [comment]
@HamidReza585 ^

**Comment by HamidReza585** [comment]
Well which version are you using? I tried this with the latest release and the nightly beta and everything looks fine.

**Comment by NouaaTW** [comment]
hmm weird, i took it from the official code

**Comment by NouaaTW** [comment]
ok my bad, i used another version of ddnet. it work perfectly
