### ISSUE TITLE
0.7 way of m_Angle setup causes aim to jump

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#4138]
If a server sends [the 0.7 way of angle](https://github.com/teeworlds/teeworlds/blob/master/src/game/gamecore.cpp#L104), while someone is aiming straight left (angle -803 to +804, the border), then the aim of this guy jumps up for a sec, looking like a bot, but then its fine again.
[The ddnet way](https://github.com/ddnet/ddnet/blob/master/src/game/gamecore.cpp#L139-L149) of handling m_Angle for some reason doesnt cause this visual glitch, neither on ddnet or 0.7.

**Comment by fokkonaut** [comment]
As it seems, the ddnet way of setting up m_Angle doesnt work for 0.7 clients, but for them, this bug occurs when looking straight up. I will need to send angles individually

**Comment by C0D3D3V** [comment]
this is because of how we interpolate between the angles (prev and cur) i think, but this is only client sided, the transmitted angles themselves only differ in these edge cases. I will see if I can get this fixed.

**Comment by C0D3D3V** [comment]
mh is probably not so simple without paying attention to the difference between the client versions.

 The case -1|-1: 1005 -603
seems to be problematic. Since this differs by 2pi.

 One would have to send simply for old client versions the old angle and for new and 0.7 the 0.7 angle.

**Comment by C0D3D3V** [comment]
Are there mods that send the 0.7 way of angle? If so we can detect it and interpolate it correct.
I fixed in https://github.com/ddnet/ddnet/pull/4972 only the visual glitch if 0.7 clients join a ddnet server
