### ISSUE TITLE
Demo Replay Bug Viewing others when /pause /spec

### ISSUE THREAD

**Issue by Ryozuki** [ddnet/ddnet#414]
For example if i did /pause or /spec on a map, later on the replay, if i'm watching others they disappear. 

;( I can't record the tournament because of this saldy.

Also would be cool if you can enable showothers in the demo, i mean if i disabled the showothers while i was playing, if there would be a option to see them in the demo.

**Comment by east** [comment]
To see other players out of your range in demos you need to enable /showall ingame.

**Comment by def-** [comment]
There are three hacks to work around this:

- Manually write `/showall 1` when you join a server and want to record everything
- Use `cl_timeout_code "MYCODE;showall 1"` to have it auto enabled every time you join a server
- Use `bind minus "zoom-; say /showall 1"` to have it enabled as soon as you zoom out.

**Comment by Ryozuki** [comment]
@def- ok  thx
