### ISSUE TITLE
Vanilla shotgun broken while in spec

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#4140]
b1051d23984bed5de37eb5339cd8bd1271213f2b
breaks vanilla shotgun, when in spec (looking at someone shooting, while in spec)

@TsFreddie

**Comment by TsFreddie** [comment]
like in /spec spec or just while in spectator mode (/pause or team==1)

**Comment by TsFreddie** [comment]
oh vanilla, oops, i'm dumb
