### ISSUE TITLE
Client fails to load server settings from map

### ISSUE THREAD

**Issue by ardadem** [ddnet/ddnet#4144]
I get following error messages on console. Client fails to load server settings.

[2021-09-04 16:17:34][console]: No such command: sv_team.
[2021-09-04 16:17:34][console]: No such command: switch_open.
[2021-09-04 16:17:34][console]: No such command: sv_deepfly.
[2021-09-04 16:17:34][console]: No such command: sv_max_team_size.

This is the origin where messages came from:
https://github.com/ddnet/ddnet/blob/master/src/game/client/gameclient.cpp#L3019

and because of that g_Config.m_SvDeepfly always return the default value, which is set to "1".
https://github.com/ddnet/ddnet/blob/master/src/game/client/prediction/entities/character.cpp#L274

Probably it's the reason why deepfly prediction broken for me.

https://user-images.githubusercontent.com/13207692/132096909-61699a8f-8bcc-4444-9401-d13ffbb4d2ec.mp4

**Comment by def-** [comment]
Those are server settings, probably from autoexec.cfg and they do nothing in client. this seems expected
