### ISSUE TITLE
Fix shell injection in `open_link`

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#4154]
Since we pass untrusted file system paths to it, this is a security vulnerability.

**Comment by heinrich5991** [comment]
CC #4136

**Comment by ChillerDragon** [comment]
Maybe using a `$'string' ` and replacing all `'` with `\' `could do the job

**Comment by def-** [comment]
Is this still relevant? We pass the link as an argument now, no longer use shell:
```
int open_link(const char *link)
{
#if defined(CONF_FAMILY_WINDOWS)
	WCHAR wBuffer[512];
	MultiByteToWideChar(CP_UTF8, 0, link, -1, wBuffer, std::size(wBuffer));
	return (uintptr_t)ShellExecuteW(NULL, L"open", wBuffer, NULL, NULL, SW_SHOWDEFAULT) > 32;
#elif defined(CONF_PLATFORM_LINUX)
	const int pid = fork();
	if(pid == 0)
		execlp("xdg-open", "xdg-open", link, nullptr);
	return pid > 0;
#elif defined(CONF_FAMILY_UNIX)
	const int pid = fork();
	if(pid == 0)
		execlp("open", "open", link, nullptr);
	return pid > 0;
#endif
}
```

**Comment by heinrich5991** [comment]
This indeed looks safe. The only thing I can see is passing a sole `--something` argument to `open` on macOS or `xdg-open` on Linux, but both man pages look fine. One could probably block `-` as the first character, but it doesn't seem necessary. The [documentation on `ShellExecuteW`](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutew) also suggests that it's fine.
