### ISSUE TITLE
Hammer as standard weapon

### ISSUE THREAD

**Issue by gerdoe-jr** [ddnet/ddnet#4177]
> is there a way to make hammer the default spawn weapon? like, when you restart you have the pistol at hand, i would like to start with hammer instead since it's a bit annoying to change it everytime i respawn

By NouKex on Discord

**Comment by def-** [comment]
`bind k "kill; +weapon1"`

**Comment by gerdoe-jr** [comment]
Why not? If team was killed by another player my tee will respawn with pistol. It's useful when you are training your hammerfly skills on maps with first hammerfly part. I suppose it's very annoying to reset weapon to hammer each time you die.

(I don't think one more command will be appreciated but adding setting to player like `/setting firstweapon hammer` will do the work)

**Comment by def-** [comment]
You can also use Settings -> General -> Unset Reset wanted weapon on death

**Comment by gerdoe-jr** [comment]
Yeah. my dummy anyway gets gun instead of hammer :P
