### ISSUE TITLE
Kill board feature: highlight player's name

### ISSUE THREAD

**Issue by Azorlogh** [ddnet/ddnet#4186]
- Add a feature to highlight the player's name in a different color to the rest.
- Add UI config option to change kill message default text color & highlighted text color

My particular use case is to make fng easier to play without sound. (I sometimes don't know if I got a hit and needed to look at the kill board).

These new config options would go in the "HUD" section of the settings.
Since this section is already full, I propose that we change it to a tabbed UI, like the "Assets" section.

**Comment by heinrich5991** [comment]
Do you play with sound? There's a specific hit sound when you hit another tee.

**Comment by Azorlogh** [comment]
Most of the time, I do, and it is not a problem. But not always, and sometimes I play with music that is louder than the game.

This is a minor issue but since I have experienced this multiple times, I think it can be a nice little improvement.
I have begun working on it, I will open a PR soon.

**Comment by heinrich5991** [comment]
> Do you play with sound? There's a specific hit sound when you hit another tee.

Sorry, I missed that you explicitly mentioned this in your original comment.



> My particular use case is to make fng easier to play without sound. (I sometimes don't know if I got a hit and needed to look at the kill board).

**Comment by edg-l** [comment]
i guess its done
