### ISSUE TITLE
:bug: Weapon of Ghost is not transparent

### ISSUE THREAD

**Issue by AssassinTee** [ddnet/ddnet#4207]
Currently the racing ghost has a fixed transparency of 0.5, as you can see in the picture:

![screenshot_2021-10-12_15-51-03](https://user-images.githubusercontent.com/821401/136969160-32dbf1db-d32e-4ab0-a4b1-ee6788870479.png)

Sometimes it can be very confusing, when the ghost is really close. Therefore I suggest a variable to control the ghost transparency to be able to make it less visible.

Also I noticed on this screenshot, that the ghost-weapon is not transparent at all, which might be a bug :bug: and should be fixed

Kind regards,
Assa

**Comment by AssassinTee** [comment]
@kaitlynia as @lomination mentioned, the weapon should be transparent, too. Therefore I don't close this issue, because it's a missing feature or a bug

**Comment by lomination** [comment]
When i change alpha value in settings->ddnet, gost body and feet become transparent but not the hands
![Capture d’écran de 2022-03-01 18-22-16](https://user-images.githubusercontent.com/92266764/156219460-1fb8df87-d447-410c-bdb8-fa5cfe8b58cf.png)

**Comment by C0D3D3V** [comment]
should be fixed with https://github.com/ddnet/ddnet/pull/4770
