### ISSUE TITLE
Libs for Win64 Visual Studio

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#423]
Some of our 64bit libs currently only work for win64 with gcc because they miss .lib files. This includes opusfile and probably curl. I think the solution is to build these dlls with Visual Studio 64bit, and then add the .lib files as well.

**Comment by Ryozuki** [comment]
[libcurl.zip](https://github.com/ddnet/ddnet/files/272525/libcurl.zip)

**Comment by Ryozuki** [comment]
[libcurl.zip](https://github.com/ddnet/ddnet/files/272556/libcurl.zip)

Couldn't compile opusfile.
"Cannot open include file: 'ogg/ogg.h': No such file or directory"
You know how to fix it?

**Comment by def-** [comment]
Yes, you need to compile libogg and libopus first and add their include paths.

**Comment by Ryozuki** [comment]
Hmm tried it and i get libopus 1.0.1 or later required.

I think you can also get it from here: https://github.com/phoboslab/Quakespasm-Rift/tree/master/Windows/codecs/x64

**Comment by Ryozuki** [comment]
Maybe a bit too late but here you have:

Both them 64bit:
[libcurl.zip](https://github.com/ddnet/ddnet/files/736520/libcurl.zip)
[opusfile.zip](https://github.com/ddnet/ddnet/files/736519/opusfile.zip)

**Comment by CookieMichal** [comment]
Bump
```
1>   file COPY cannot find
1>   "Repos/ddnet2/other/curl/windows/lib64/libidn-11.dll".
1> 
1>   file COPY cannot find
1>   "Repos/ddnet2/other/opus/windows/lib64/libgcc_s_sjlj-1.dll".
```
