### ISSUE TITLE
ddnet does not detect remapped ESC

### ISSUE THREAD

**Issue by vimpostor** [ddnet/ddnet#4241]
On Linux (X11), I have remapped my Caps Lock to ESC with `setxkbmap us -option caps:escape -variant de_se_fi`.
In the original Teeworlds and in pretty much every game I know, they respect this setting and pressing Caps Lock activates ESC.

However, ddnet somehow does not detect the ESC when I press Caps Lock. Since I don't have a real ESC key on my keyboard, I am unable to enter the Pause menu. Probably ddnet is checking the keyboard a layer below than what most other applications do and checks the keyboard codes from the keyboard directly. It would be good, if ddnet could handle keyboard events like Teeworlds and thus allow such weird remappings.

**Comment by akai-hana** [comment]
Sorry to necro/comment on a closed issue, but this fix isn't working for me.

I'm also on Linux using `setxkbmap caps:swapescape`. Adding `inp_translated_keys 1` (or `0`, tried both) to my config file does nothing (`~/.local/share/ddnet/settings_ddnet.cfg` is the config file the game loads in my case). Also tried setting it directly through the console to see if it was maybe some issue with my config file, but that didn't work either.

**Comment by vimpostor** [comment]
> Sorry to necro/comment on a closed issue, but this fix isn't working for me.

I just tested it again on X11 and it still works for me with `inp_translated_keys 1`. Can you give us more details on your setup such as your WM and your used layout and any other special circumstances?

On an unrelated note, I have switched back to Vanilla Teeworlds for different reasons, as some UX details are still not as polished on ddnet. For example the pause behaviour with sticky keys on ddnet is very unintuitive and can regularly cause unwanted input as it is easy to forget that input was pressed when pause was entered. The Teeworlds behavior of explicitly needing to press the buttons again before unpausing was much more explicit and intuitive to me.
