### ISSUE TITLE
Problems with colored text output using screen?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4242]
Reported by StylerTime
![unknown](https://user-images.githubusercontent.com/2335377/138574147-e0bd0436-feac-4849-a4da-b694512a2b02.png)
Lines look empty instead of colored

**Comment by Kaffeine** [comment]
Is there a way to disable the color output? It affects the output in IDEs.
![image](https://user-images.githubusercontent.com/374839/145075621-c2b96c94-aa36-4f59-bd5c-2b1df940366e.png)

**Comment by def-** [comment]
No, not yet. I'd be ok with someone adding an option for that
