### ISSUE TITLE
"events" command doesn't function

### ISSUE THREAD

**Issue by refeax** [ddnet/ddnet#4269]
When setting "events" to 0 in the command tab, it doesn't prevent from holiday eye emotes as said on the official ddnet website.

**Comment by def-** [comment]
Some events are client-side, but the eyes are server-side, so only the server operator can disable them.

**Comment by def-** [comment]
You can use something like `/emote happy 99999` if you don't like the angry face during halloween.

**Comment by Jupeyy** [comment]
the config var is shared between client and server and uses the same description, which is irritating,
also using `cl_eye_duration 1` will reset the eye to evil eyes, instead of the last used one

I guess atleast the first point requires a description fix or split the config
