### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#427]
I'll mark ! for easy fixes

In-game:

Instead of click on the vote from the list then clicking on the "vote" button, just double clicking should start the vote.

Combine the "game" menu with "players" menu.

Also make the "players" menu same/similar with the scoreboard (tab) UI, arranged by players points and so forth, split by teams, and so forth.

Make the statsboard (not the scoreboard) bigger to be able to fit bigger numbers, more margins per players, etc. Just modernize the UI more or at least more consistent with the scoreboard.

Why is there a ghost menu under network menu?

Server list menu:

While viewing server list menu with friends list open, and while having a server selected (clicked) and a friend selected, pressing up/down moves both server selection and friend selection. Friend selection should not move.

F5 or ctrl+R should be a shortcut/hotkey to refresh the server list menu.

**Comment by def-** [comment]
Thanks, fixed the things I considered useful.
