### ISSUE TITLE
Client capabilities

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#4273]
We definitely need some sort of client capabilities, players reported that they don't see doors as closed anymore using F-Client, even tho I didn't change anything. I looked it up and it is because my F-Client sends exactly the entity switch required version :/ Meh ._. I don't have autoupdater in the client and this is the last release which is the most common version
https://github.com/fokkonaut/F-Client/blob/dfcf3c0dff831b4c59aadc71eacd76a18198eef8/src/game/version.h#L9

@def- do you think we can set the required version to 15061 and DONT release a 15060? :D Otherwise I would need to do another F-Client update which most people wouldn't notice or simply ignore because "their current clients works well". You know the teeworlds community :(

**Comment by Jupeyy** [comment]
Isn't that kinda your fault that you set the DDNet client version to something, that wasn't released?

**Comment by fokkonaut** [comment]
It is and I didn't say something against that, but I am asking to fix this issue on ddnet's side as that's way easier. Otherwise ddnet will have to deal with a lot players complaining and not understand probably.

**Comment by heinrich5991** [comment]
I'd prefer if you could release a fixed version of the F-Client.

**Comment by fokkonaut** [comment]
Done.
https://fokkonaut.github.io/F-Client
