### ISSUE TITLE
After the update i got this weird grey bar on the right

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4291]
Max on Discord reports: "After the update i got this weird grey bar on the right"
![20211104145652_1](https://user-images.githubusercontent.com/2335377/140333900-9d4f7224-3c1b-4dce-89e3-f1a685e58c42.jpg)

@Jupeyy any ideas?

**Comment by Jupeyy** [comment]
I guess we should not clamp the screen width to 21:9

https://github.com/ddnet/ddnet/commit/644fec7e55ce3992eb772837e405998d4c3df8b5#diff-89d5b3dd4497dfd2259c05f3c1c8b9dcd75fdcf1b0f83a2f435dbd0982a408e9R918-R921

(atleast remove the upper bound, the 5:4 can stay if its important to you that the UI doesnt break when using weird resolutions)
