### ISSUE TITLE
Problems with client for multiple people

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4293]
Since 15.6, reported on Discord.
![unknown](https://user-images.githubusercontent.com/2335377/140340156-b5f5ce42-e740-4ccf-93e3-37369f4bdcd9.png)
out of memory in first line looks weird.

**Comment by def-** [comment]
One weird idea is that we might be out of stack with https://github.com/ddnet/ddnet/commit/3eb3dcd48b070e724ec394488ed79d2203670325 (only 1 MB on Windows)

**Comment by def-** [comment]
Another idea is that sqlite3.dll might be broken, I asked them to replace with the one from 15.5.4

**Comment by def-** [comment]
Some of the players have a lot of unicode stuff, Russian names etc, so maybe related to https://github.com/ddnet/ddnet/commit/4a375242c54ccf99e5d5d8f9a4b949afae48d0b0

**Comment by def-** [comment]
For Nakimar https://github.com/ddnet/ddnet/pull/4296 fixes the problem, for Max not.

**Comment by def-** [comment]
@Robyt3

**Comment by Learath2** [comment]
I can reproduce this issue by creating a local user account with a cyrillic name. #4296 does not help for me
