### ISSUE TITLE
My game is crashing no matter which map I enter

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4297]
My game is crashing no matter which map I enter
It happened after I just updated the game to new version

Reported by anonymous on Discord

**Comment by Jupeyy** [comment]
maybe #4227 ?

bcs they are deleted as soon as you enter a map

**Comment by Jupeyy** [comment]
( Can you ask him to set auto demo to infinity )

**Comment by Chairn** [comment]
No way to get more info i suppose, so i close this one.
