### ISSUE TITLE
Dummy is a kind of hacker--click*

### ISSUE THREAD

**Issue by ST-Chara** [ddnet/ddnet#4305]
I set my server
sv_max_clients_per_ip 4
and dummy connect,I don't welcome dummy
But I can't stop them！！！！！！！！
Let the dummy appear only on the server where the motd has written some specific characters

like: sv_motd #dummyenable#

**Comment by def-** [comment]
Then set `sv_max_clients_per_ip 1` if you don't want any dummy

**Comment by ChillerDragon** [comment]
Using the motd is a bit hacky but we could introduce a game flag that tells the client if dummys are allowed. Like we do with zoom here https://github.com/ddnet/ddnet/blob/8ecb3646ac146726df9881a43ae7eddcee31c64f/src/game/server/gamecontroller.cpp#L585-L602

**Comment by ST-Chara** [comment]
i want player with online player and local player(sorry for my bad english)

**Comment by ST-Chara** [comment]
|ONLINE|--------dummy              sv_max_clients_per_ip 3
           /               \                                   sv_max_clients 4
          /                  \
      |local|             |local|     {another local connecting}===={connect fali}

**Comment by ST-Chara** [comment]
> Then set `sv_max_clients_per_ip 1` if you don't want any dummy

        |ONLINE|--------dummy              sv_max_clients_per_ip 3
       /          \                                   sv_max_clients 4
      /             \
  |local|             |local|     {another local connecting}===={connect fali}
