### ISSUE TITLE
Bad linebreaks in console

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4319]
In F1 and F2
![screenshot-20211106@192556](https://user-images.githubusercontent.com/2335377/140620038-6fb393e2-259d-47d5-ba43-6bac487c61bb.png)

**Comment by Jupeyy** [comment]
what is this resolution xD

**Comment by def-** [comment]
Noticed while trying https://github.com/ddnet/ddnet/pull/4320
But could happen with very long lines in any resolution

**Comment by murpii** [comment]
on 1920x1080
![DDNet_SGnvXp6ByV](https://user-images.githubusercontent.com/60477660/141673830-98601c33-2746-4372-9349-fb7356c06e35.png)
