### ISSUE TITLE
No longer able to copy text from Terminal

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#4331]
I'm no longer able to copy text from the black terminal (cl_show_console 1).
Workaround is to rightclick > Select all, which only works once though.

Windows 10 64bit, latest version (15.6.1)

**Comment by def-** [comment]
Probably related to the colors. Not sure how Windows handles them.

**Comment by Jupeyy** [comment]
@BloodWod-513 can you check this?

I think you also changed the behavior of windows console selecting in #3971, dunno if it was caused by this

**Comment by heinrich5991** [comment]
Yes, it's precisely what #3971 did.

**Comment by murpii** [comment]
oh, I see. Guess I have to live with it now.

**Comment by Jupeyy** [comment]
Maybe we can automatically toggle the mode, when window regains focus or smth like that

**Comment by def-** [comment]
Still means you can get a timeout, you don't get highlights ingame, etc, while having something selected.
