### ISSUE TITLE
Tee appears in the previous location for a short time after map change

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#4339]
when joining a server you see your tee at the position you was before you left for a second, it needs a short time to update where you actually are. Feels weird and happens with 15.6

**Comment by ChillerDragon** [comment]
Did the time increase? I know this from older versions but it always was super short so it didn't matter.

**Comment by Jupeyy** [comment]
I could imagine this is bcs we now show the map on the 2nd snapshot
heinrich probs can tell more

**Comment by Learath2** [comment]
Smells like a variable we don't reset properly between disconnects
