### ISSUE TITLE
Unplayable demos

### ISSUE THREAD

**Issue by Learath2** [ddnet/ddnet#4343]
Over the last week or so I spotted a couple very concerning bug reports about demos being unplayable. I'm not sure what went wrong here but we need to take a look.

**Comment by def-** [comment]
It seems that with @Robyt3's unicode changes we are now opening files case-sensitively on Windows. Maybe this matters for some demos. Also, we have this issue with KoG demos: https://github.com/ddnet/ddnet/pull/4330

**Comment by Robyt3** [comment]
Maybe is has to do with "check for filename case sensitive", whatever the respective code actually used to do or does now.

https://github.com/ddnet/ddnet/blob/0443a3ef659242b255483b61dd4b4a2b2e8c1154/src/base/system.cpp#L317-L339

Can someone share a demo where this happens and also what the map used in the demo is named locally?
