### ISSUE TITLE
terrible bug

### ISSUE THREAD

**Issue by Cheterthecat** [ddnet/ddnet#4349]
I can't move cursor.

**Comment by NouaaTW** [comment]
nice commit, you can try to check your mouse sens / UI sens by writing inp_mousesens / ui_mousesens. if the value = 0 then set what you want. if that doesn't work, give more information on discord/developer channel.

**Comment by heinrich5991** [comment]
Which operating system are you on? Where did you get DDNet? Steam? ddnet.tw? Distribution? What's your DDNet version?

**Comment by murpii** [comment]
Try typing `inp_mouseold 0` into the F1 console, then restart your game. Does this fix your problem?

**Comment by iTzMeRafa** [comment]
check if your mouse is plugged in

**Comment by murpii** [comment]
It's probably safe to say op has abandoned this issue since he doesn't reply to any of the suggestions/questions.

**Comment by bencie** [comment]
Hey, I have this problem too, but for me a really easy fix is to tab out, and tab back in everytime you start the game.
