### ISSUE TITLE
jao shooter causing lags in DDNet 15.6

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4360]
> so many people have strange laggs in my map jao shooter and it turns of that using ddnet DDNet 15.6.2 and higher causes game too lag . (video any server antiping on off same)
> using version DDNet 15.5.4 will not have laggs . ( thanks to @Cøke findet why it happens ) 
texnonik reported on Discord.

@trml related to prediction changes?

**Comment by fokkonaut** [comment]
Related to many draggers + EntityEx

**Comment by trml** [comment]
Yes, I had forgot about something in the last pr, will fix.
