### ISSUE TITLE
Max ping in serverbrowser filter considered harmful

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4365]
Since it doesn't work well with the new regions instead of actual ping

**Comment by BannZay** [comment]
I just updated the game and I am missing that option.
 
Hope someone will find a way to automatically filter out servers/regions with high ping.

**Comment by C0D3D3V** [comment]
@BannZay you can sort the server list by ping... But the ping is not very accurate... Sometimes in the list is a very high ping >300 reported, but if I join it is <10

**Comment by BannZay** [comment]
> @BannZay you can sort the server list by ping...

I can not. I use sorting by players, not really interested in 1-2 players servers

**Comment by heinrich5991** [comment]
Click the Players or Ping column three times. It'll give you a list of nonempty servers grouped by approximate ping. :) Basically what you're asking for, if I understand it correctly.

**Comment by BannZay** [comment]
> Click the Players or Ping column three times. It'll give you a list of nonempty servers grouped by approximate ping. :) Basically what you're asking for, if I understand it correctly.

Thank you.
 Yeah Ive done the same. Have been clicking ping and players many times untill list become decent. Not quite what I needed and I have no idea how have I achieved this, but it is okay.

As I said - it become less convenient and way less obvious.
