### ISSUE TITLE
map_extract fails to open absolute path with Unicode

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4369]
Reported by cheeser on Discord, works with relative paths.
![unknown](https://user-images.githubusercontent.com/2335377/142657082-29b9df2c-9f42-4707-abaf-4a7ae8b6c3b8.png)
Not sure what the issue is. @Robyt3 any idea?

**Comment by Robyt3** [comment]
In a nutshell, the issue is the encoding of argv in general.

See https://stackoverflow.com/a/5596232/1708371.
