### ISSUE TITLE
SDL2 mousewhell doesn't work for scrolling in lists

### ISSUE THREAD

**Issue by timakro** [ddnet/ddnet#438]

**Comment by def-** [comment]
fixed.

**Comment by Henningstone** [comment]
It does work now, but it is really bugged; at least for me (I'm on Ubuntu).

It scrolls only at random mouse wheel ticks and thus is very stuttering and unusable.
I checked out a commit before sdl2 got introduced to make sure it's not an issue with my mouse wheel.

**Comment by def-** [comment]
Can you check with Teeworlds master

**Comment by Henningstone** [comment]
Yap, updating SDL to 2.0.4 fixed the scrolling for both DDNet and teeworlds/master!

**Comment by def-** [comment]
Hm, too bad that it will take forever for SDL 2.0.4 to be available on Debian/Ubuntu.

**Comment by Henningstone** [comment]
Oh, on Ubuntu 16.04 it is already available! Let's hope it'll be updated for everything else aswell soon...
