### ISSUE TITLE
Resolution changing without restart on Windows and Mac OS X

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#439]
Recently I added resolution changing without restart, but unfortunately it only works on Linux. For more information see https://github.com/teeworlds/teeworlds/pull/881

**Comment by def-** [comment]
http://www.bytehazard.com/articles/sdlres.html

**Comment by Learath2** [comment]
I got this working on macOS, I'll PR it later this week

**Comment by kaitlynia** [comment]
Works on Windows, assuming this can be closed?
