### ISSUE TITLE
Port IME from Teeworlds 0.7

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4397]
Reported by 冷落:
> Another problem is that when the game uses full screen typing, my input method candidate field is not displayed,It's been like this for a long time

TsFreddie:
> we should just steal the teeworlds way, which is fully supported with focus and candidates.
> exclusive fullscreen can't have window manager running on top of games

**Comment by Jupeyy** [comment]
Would be really nice if @TsFreddie or @Robyt3 could port it, ofc only if they find the time for this, since it probably requires quite a bit of testing
