### ISSUE TITLE
weak/strong hook warning is wrong

### ISSUE THREAD

**Issue by Smetanolub** [ddnet/ddnet#4406]
you should do strong/weak hook warning backwards
like, when you see someone who have strong on you-red above him
and if you have strong on him-green above him
and i dont like this weak/strong hook warnings because it distracts. you should better do a colourful nickname
like red nickname on someone you have weak for
and green nickname if you have strong on him
also you should do a custom colour, of course...

**Comment by Smetanolub** [comment]
under weak/strong hook warnings i mean icons over tee

**Comment by fokkonaut** [comment]
> and if you have strong on him-green above him

that is the case
