### ISSUE TITLE
Zooming out can cause odd behaviour

### ISSUE THREAD

**Issue by Learath2** [ddnet/ddnet#4414]
![image](https://user-images.githubusercontent.com/490500/144072429-ddda0e52-ab4d-45d3-b891-b9f2a9972c78.png)

If you zoom out too much this seems to happen. I think the snap gets too large and something gets dropped causing this. Not sure what, maybe the character.

Could be that the server is old, it's at revision: 82c7b20001b4e614

@trml you were the last one to look around the snap order, anything come to mind?

**Comment by def-** [comment]
Was also reported here https://github.com/ddnet/ddnet/issues/4244 but apparently not fixed (fully) yet

**Comment by trml** [comment]
I think it's the version yes, since this was fixed in ae6bb9763 (I believe) a few commits after
