### ISSUE TITLE
Report player skin data to HTTP master

### ISSUE THREAD

**Issue by edg-l** [ddnet/ddnet#4415]
This would allow to show the player skins in the ddnet website /any custom website that uses the http master to get information.

I remember discussing that it shouldn't be a problem to add more data when reporting to the http master, I think this would be a cool feature. Maybe we could also report the time since a player connected.

**Comment by heinrich5991** [comment]
Can now be done, we have HTTPS masters now: #5064.

**Comment by def-** [comment]
Has been implemented
