### ISSUE TITLE
Application does not start up on MacOS when updating to 15.7

### ISSUE THREAD

**Issue by Julian-N** [ddnet/ddnet#4418]
Hello together,

i was updating DDNet on my MAC from 15.3.2 to Version 15.7 and my application does not start up anymore. 

I get the following error:
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/lib/libSDL2-2.0.0.dylib
Referenced from: /Applications/DDNet.app/Contents/MacOS/DDNet
Reason: tried: '/usr/local/lib/libSDL2-2.0.0.dylib' (no such file), '/usr/lib/libSDL2-2.0.0.dylib' (no such file)
(terminated at launch; ignore backtrace)

Application Specific Information:
Library not loaded: /usr/local/lib/libSDL2-2.0.0.dylib
Referenced from: /Applications/DDNet.app/Contents/MacOS/DDNet
Reason: tried: '/usr/local/lib/libSDL2-2.0.0.dylib' (no such file), '/usr/lib/libSDL2-2.0.0.dylib' (no such file)

**Comment by def-** [comment]
Will be fixed by https://github.com/ddnet/ddnet/pull/4417
You can try https://ddnet.tw/downloads/DDNet-15.7-test-osx.dmg
