### ISSUE TITLE
Console output does not work with Git Bash

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#4422]
Git Bash is a bash emulator that comes with Git for Windows.

It's useful for example because it supports displaying unicode characters.

It works with upstream teeworlds but not with the ddnet tools (e.g. `map_convert` prints output in cmd and powershell but not in Git Bash).

**Comment by def-** [comment]
Is this because of the colors we use in our output?

**Comment by Robyt3** [comment]
I believe not, as tools like `map_convert` only use `dbg_msg` and the colors only apply to output of `CConsole::Print`.

**Comment by Robyt3** [comment]
This seems to be caused by the async IO implementation. I can replicate the behavior on upstream with the ported changes (https://github.com/teeworlds/teeworlds/pull/3092).

**Comment by Robyt3** [comment]
0c13c8cebb09b7798309ea0317a2e85885fb5697 is the first bad commit (https://github.com/ddnet/ddnet/pull/1396)

**Comment by def-** [comment]
@Learath2 ^
