### ISSUE TITLE
0.7 Loading / Connection problem with map .Background'

### ISSUE THREAD

**Issue by phbenisc** [ddnet/ddnet#4430]
There are problems with loading of the map .Background' .
Therefore the map is unplayable with 0.7 clients.
It somehow seems to breaks the 0.7 client, either when loading from the server on vote change or on connection to the server.

Steps to reproduce:
* use fclient (0.7.5 / 3.3)  or teeworlds client (0.7.5)
* connect to ddnet server with a map
* change map to [.Background'](https://ddnet.tw/maps/-46-Background-39-/) 

Outcome:
The old map is displayed. 

Steps to reproduce:
* use fclient (0.7.5 / 3.3) or teeworlds client (0.7.5)
* connect to ddnet server with  [.Background'](https://ddnet.tw/maps/-46-Background-39-/)  running

Outcome:
client displayes 
![image](https://user-images.githubusercontent.com/5716653/145196747-43a0b092-fae4-4f92-b188-2c828d2b797d.png)

Server version was ddnet 15.7

**Comment by Robyt3** [comment]
`0.7 connections are not accepted at this time` means you don't have `sv_sixup 1`.

Even if you have it in your config, it will get disabled if you don't have a 0.7 version of the map in your `maps7` folder. Check the server log for

```
[sixup]: couldn't load map maps7/.Background'.map
[sixup]: disabling 0.7 compatibility
```
Run the command `map_convert_07 "data/maps/.Background'.map"` (or with `\` instead of `/` on Windows) to convert the map, then restart the server.

**Comment by phbenisc** [comment]
thank you @Robyt3 for the quick response and guide. I got it locally running. 
The thing is that the problem occured on an official ddnet server. 

Do the map maintainer also read github issues or do i need to contact someone in discord?

**Comment by heinrich5991** [comment]
Maybe some shell glob not catching files starting with a dot? In the map conversion process? @def-

**Comment by def-** [comment]
Right, that's exactly the problem, I'll fix it.

**Comment by def-** [comment]
https://github.com/ddnet/ddnet-scripts/commit/4a08c0575793ee75631d36c88de6272923b6031b#diff-d1808e31d7f9b82cb620b97b0be4554444d03016d42f3af2ae23a2bdbc5ad8b0
