### ISSUE TITLE
Finding the server a friend is playing on in serverbrowser requires tripleclick

### ISSUE THREAD

**Issue by H-M-H** [ddnet/ddnet#444]
Doubleclicking on the name of the friend is no longer sufficient.

**Comment by def-** [comment]
Works with asyncrendering off, hm.

**Comment by def-** [comment]
Last good commit: 97743b8e70658f0f6fe864dc8bc87b7e547ea7ad
First bad commit: db8a126315de1657253917b861b51306da9e3a53

I checked and couldn't find anything relevant in the commit, so this just seems to have happened with the SDL1.2 -> SDL2 switch without any code change. Mysterious.
