### ISSUE TITLE
macOS dmg should allow installation by dragging into Applications

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4442]
Other applications work that way, see for example Firefox. That seems cleaner than what we have now.

**Comment by heinrich5991** [comment]
How do we do it now?

**Comment by def-** [comment]
The dmg is mounted and shows DDNet and DDNet-Server (launcher). The Launcher requires you to drag a cfg into it to even run a server, it should use the autoexec_server.cfg instead to be simpler to use.

**Comment by def-** [comment]
<img width="1032" alt="Screenshot 2021-12-10 at 18 59 58" src="https://user-images.githubusercontent.com/2335377/145620476-504a1fc6-4aef-46b9-9746-3fda63e3c93b.png">
<img width="624" alt="Screenshot 2021-12-10 at 19 01 01" src="https://user-images.githubusercontent.com/2335377/145620484-7607b4e5-71e0-4a4e-8fa1-883578751cae.png">

**Comment by def-** [comment]
https://gist.github.com/jadeatucker/5382343

**Comment by def-** [comment]
I'm working on this using dmgbuild. Works fine so far, I'm asking Ravie for a background image for this since mine would probably not look so nice.

**Comment by def-** [comment]
Ok, dmgbuild is unfortunately not possible on macOS. I'm not sure if there is a good alternative. At the moment we can't cross-build for mac arm anyway because of the code signing issues.
