### ISSUE TITLE
settings for resolution have no effect

### ISSUE THREAD

**Issue by H-M-H** [ddnet/ddnet#445]
`gfx_screen_width` and `gfx_screen_height` have no effect anymore. The problem is probably in here somewhere: https://github.com/ddnet/ddnet/blob/master/src/engine/client/backend_sdl.cpp#L550 .

**Comment by def-** [comment]
What do you mean by "have no effect"? On what OS?

**Comment by H-M-H** [comment]
By that I mean the resolution will always be set to default screenresolution no matter what you put into your config. I am on OS X 10.11.4

I think `gfx_screen_width` and `gfx_screen_height` are just overridden.

**Comment by H-M-H** [comment]
Ahh, nice of course missing `{}` ^^. Works now.
