### ISSUE TITLE
allow mods to use unmute/muteid on people affected by sv_chat_initial_delay

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#4460]
Since this command is only used for certain individuals, we don't have to punish the entire server. Would it be possible to allow moderators to use unmute to enable people to talk affected by the initial chat delay?

**Comment by def-** [comment]
Is this really practical? When you have a server with 60 players do you want to unmute everyone individually?

**Comment by murpii** [comment]
> Is this really practical? When you have a server with 60 players do you want to unmute everyone individually?

it's not so bad as it sounds, since only newly joined clients get muted after this option has been enabled. Also if another mod joins, hes muted and can't talk either.

**Comment by def-** [comment]
This is not so easy to implement. We'd have to store the chat delay mutes as regular mutes and need to add a way to tell them apart from the normal ones because only some contexts actually respect the initial chat delay mutes, not all. I'll give it a try later.

**Comment by heinrich5991** [comment]
Fixed by #4469 (extra space in the "fixes …" message caused this to not auto-close).
