### ISSUE TITLE
Tee can get stuck in wall

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4474]
Reported by Czomik on Discord
I think this might be an occurence where making physics makes sense

https://user-images.githubusercontent.com/2335377/146673238-50c83f74-93c5-4d85-8f2a-a4e3ba200085.mp4

**Comment by def-** [comment]
https://user-images.githubusercontent.com/2335377/146673581-8123baf9-e39d-4108-8618-4d53ba760ece.mp4

[Pounamu_2_2021-12-18_00-02-51_1.demo.zip](https://github.com/ddnet/ddnet/files/7740718/Pounamu_2_2021-12-18_00-02-51_1.demo.zip)

**Comment by Chairn** [comment]
https://github.com/ddnet/ddnet/issues/190

**Comment by def-** [comment]
Sounds different to me.

**Comment by kamillentee** [comment]
#1738
