### ISSUE TITLE
Editor map saves should go into a temporary file first

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#4476]
Map saving should go to a temporary file first so that crashes don't corrupt the existing map file. Move it over to the correct name after finishing.

**Comment by heinrich5991** [comment]
PR was reverted.

**Comment by def-** [comment]
I don't know if it's possible to do this safely on Windows.

**Comment by heinrich5991** [comment]
It doesn't look like the map file is kept open while the map is in the editor. `CEditorMap::Load` creates a local `CDataFileReader` variable which is closed when it goes out of scope. Is it related to the map being open ingame maybe?

Regarding "safely": The approach didn't lose maps, it only created situations where the original map couldn't be overwritten, I think? Then an error message would be fine. Much better than losing your work when the editor has a bug that crashes while saving, deleting your old map.
