### ISSUE TITLE
GNU: can't switch from dummy to main tee since recent commit

### ISSUE THREAD

**Issue by samtinel** [ddnet/ddnet#4477]
Hello there!  
Since commit 72afa17349fd6922bfda1564eda304d2dc7a04af, switching between dummy and main tee does not work anymore. In the prior commit, 529c1654da5b0c912f60128ce9f69751b164adb9, it works fine.  
Operating System: GNU+Linux - Arch Linux x86_64
DE: KDE Plasma Wayland  

How to reproduce:  
1. checkout any commit after the "bad" one (the most recent commit at the of writing, 79e5703e21d097f653b51833dbfafc5993564080, included)
2. join a game
3. connect dummy
4. try to switch to the main tee
  
Expected result:  
Control gets shifted back to the main tee.  
  
Observed Result:  
Nothing happens.  
The key itself gets recognized - if I set the key to echo something, it works. I haven't figured out what in the commit broke it exactly, but I am happy to try any patches/leads out!

Things I've tried:  
Recompiling, using a different key and removing .teeworlds.

If this is expected for now, please excuse the noise!  
Samtinel

**Comment by samtinel** [comment]
It would be nice to know whether this happens on Microsoft Windows as well, but I don't have that at my disposal.

**Comment by def-** [comment]
Definitely not expected, let me see if I can reproduce it.

**Comment by def-** [comment]
Can reproduce, will fix.
