### ISSUE TITLE
change game tiles to the specific entities layer.

### ISSUE THREAD

**Issue by NouaaTW** [ddnet/ddnet#4478]
that would be cool to add that possibilty, for exemple if we create a blocker map (so change the entities to blockworlds) we can't use the "game tiles" options because the tiles are not the same as the ddnet ones. if we click on game tiles then freeze that will be not the freeze but the "end" tile

**Comment by heinrich5991** [comment]
Is this talking about the editor? I think we support it ingame.

**Comment by NouaaTW** [comment]
yes it is about editor, i had a video but github support only <10mo

**Comment by def-** [comment]
Can't find the video

**Comment by def-** [comment]
https://user-images.githubusercontent.com/2335377/146695419-869f97bf-85be-49bf-90c4-a2771a4d822d.mp4

Resized to 10 MB

**Comment by NouaaTW** [comment]
thx, so as i sad the game-tiles is wrong with blockworlds (and with other layers i guess).
