### ISSUE TITLE
Smoke when decelerating got lost somehow

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#4491]
In Teeworlds 0.7, accelerate a little faster than walking using the hook, and then press the opposite walking direction. You decelerate fast and emit a little smoke cloud.

I think we had that in DDNet/Teeworlds 0.6 as well, but it seems to have been lost?

**Comment by def-** [comment]
Seems to work for me

https://user-images.githubusercontent.com/2335377/146816085-64f7c476-adca-433d-946f-dd5e2ae595e7.mp4

**Comment by heinrich5991** [comment]
Hm, okay, can reproduce it working. Not sure what I found yesterday.
