### ISSUE TITLE
Compile DDNet 10 error

### ISSUE THREAD

**Issue by kinggta** [ddnet/ddnet#450]
In system.c have this errors when i want compiling

[ 1/18] #1 c src/base/system.c
src/base/system.c(1710) : error C2143: syntax error : missing ';' before 'type'
src/base/system.c(1711) : error C2065: 'p' : undeclared identifier
src/base/system.c(1711) : warning C4047: '=' : 'int' differs in levels of indire
ction from 'char *'
src/base/system.c(1711) : error C2065: 'p' : undeclared identifier
src/base/system.c(1711) : error C2100: illegal indirection
src/base/system.c(1711) : error C2065: 'p' : undeclared identifier
src/base/system.c(1713) : error C2065: 'p' : undeclared identifier
src/base/system.c(1713) : error C2100: illegal indirection
src/base/system.c(1713) : error C2065: 'p' : undeclared identifier
src/base/system.c(1713) : error C2100: illegal indirection
src/base/system.c(1715) : error C2065: 'p' : undeclared identifier
src/base/system.c(1715) : error C2100: illegal indirection
src/base/system.c(1718) : error C2065: 'p' : undeclared identifier
src/base/system.c(1718) : error C2100: illegal indirection
bam: 'objs/base/system.obj' error 2
bam: error: a build step failed

and this line is for :

int fs_makedir_rec_for(const char *path)
{
	char buffer[1024*2];
	str_copy(buffer, path, sizeof(buffer));
	char *p;
	for(p = buffer; *p != '\0'; p++)
	{
		if(*p == '/' && *(p + 1) != '\0')
		{
			*p = '\0';
			if(fs_makedir(buffer) < 0)
				return -1;
			*p = '/';
		}
	}
	return 0;
}

i think this must be:

int fs_makedir_rec_for(const char *path)
{
	char buffer[1024*2];
	char *p;
	str_copy(buffer, path, sizeof(buffer));
	
	for(p = buffer; *p != '\0'; p++)
	{
		if(*p == '/' && *(p + 1) != '\0')
		{
			*p = '\0';
			if(fs_makedir(buffer) < 0)
				return -1;
			*p = '/';
		}
	}
	return 0;
}

**Comment by def-** [comment]
Thanks, should be fixed.
