### ISSUE TITLE
Exclude /map from Run on join

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#4505]
It's more annoying than helpful, I think

**Comment by def-** [comment]
It's not useful, but why would someone even set it? I don't think we need a blocklist of forbidden chat commands. If people want to be annoying they can still `bind mouse1 "+fire; say /map Kobra"`

**Comment by heinrich5991** [comment]
What is it useful for, Run on join?

Is it just for recording demos? Perhaps we can add an option to request the whole map when recording a demo instead?

**Comment by murpii** [comment]
> It's not useful, but why would someone even set it? I don't think we need a blocklist of forbidden chat commands. If people want to be annoying they can still `bind mouse1 "+fire; say /map Kobra"`

Fair. I first figured this wouldn't work anyway cuz of the 30 seconds people have to wait before able to start a vote, but I just joined a couple of servers and noticed I started a vote by accident. As of why would someone would set it, just to be annoying I guess. Binding this to a key would spam the chat, Run on join is just sent once.
