### ISSUE TITLE
Editor browser filter

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#4508]
Sorah on Discord:
could we have some filter system for maps in the editor ? like date or filesize ( and display that stuff )
I remember some admin saying he already made it but never added it =P

**Comment by Learath2** [comment]
It was probably me who said they made it, but I only made it for the editor2 branch for vanilla. Maybe I can port it over sometime.

**Comment by kaitlynia** [comment]
from my duplicate issue:
It's a pain to remember what map I was working on last if I forgot what I named it, and ofc there is always the OS mod time but it would be nice to have this feature in game :D

**Comment by luk51** [comment]
> It was probably me who said they made it, but I only made it for the editor2 branch for vanilla. Maybe I can port it over sometime.

@Learath2 can you give me the link to the branch? i want to check it out.

**Comment by C0D3D3V** [comment]
https://github.com/teeworlds/teeworlds/tree/editor

**Comment by Robyt3** [comment]
Showing file size is unnecessary in my opinion. Doesn't seem very useful to show it in the editor file browser.

**Comment by Robyt3** [comment]
As stated before, sorting by file size doesn't seem useful and it adds unnecessary complexity, so I'm closing this. We can reopen if someone can provide a convincing argument how sorting by file size is useful.

**Comment by AssassinTee** [comment]
> As stated before, sorting by file size doesn't seem useful and it adds unnecessary complexity, so I'm closing this. We can reopen if someone can provide a convincing argument how sorting by file size is useful.

When submitting maps to ddnet, we have some rules about file sizes and maptesters are declining maps that are not optimized in file size. We also have external tools to check, what part of the map is taking how much space:

i.e.

<img width="545" height="725" alt="Image" src="https://github.com/user-attachments/assets/22d4ed66-d520-4373-9145-ad20657a7923" />

CC @Patiga do you think we can estimate the mapsize on a loaded map inside the editor?
