### ISSUE TITLE
Release 10.0.1 in MacOS X lost SDL2.framework

### ISSUE THREAD

**Issue by ACTom** [ddnet/ddnet#452]
Release 10.0.1 in MacOS X cannot run, There is only SDL.framework in Application, not SDL2.

**Comment by ACTom** [comment]
When I copy SDL2.framework to /Applications/DDNet.app/Contents/Frameworks, it doesn't work either, only copy SDL2.framework to /Library/Frameworks, DDNet can work.

Error Information:
`➜  MacOS ./DDNet
dyld: Library not loaded: @rpath/SDL2.framework/Versions/A/SDL2
  Referenced from: /Applications/DDNet.app/Contents/MacOS/./DDNet
  Reason: image not found`

**Comment by def-** [comment]
This should be fixed now. Try downloading 10.0.1 again please.
