### ISSUE TITLE
"Update now" button still not working since version 9 or 8

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#453]
I still have to manually download and install. I remember this issue was open/addressed. I thought it was fixed.

**Comment by def-** [comment]
What OS and CPU arch? Any messages in the log? What happens exactly?

**Comment by PathosEthosLogos** [comment]
Windows 8.1 x64
"Failed to download a file! Restart client to retry..."
Checking f1, there isn't anything, except when I started the client, it shows "failed to open 'autoexec.cfg'" which I don't have. I have autoexec_server.cfg file, though that's for the server I guess.

**Comment by def-** [comment]
I see two possibilities:

1. You have no permissions to download files. Change file permissions for the DDNet directory or start client as Admin
2. You start DDNet.exe with some shortcut and it sets the wrong current working directory. Try starting DDNet.exe directly.

Does it work if you download DDNet 10.0 directly and try to update it to 10.0.1? https://ddnet.tw/downloads/DDNet-10.0-win64.zip

**Comment by PathosEthosLogos** [comment]
Ah yes, it was the permissions problem. Thanks.
