### ISSUE TITLE
Support notch area on macOS?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4533]
Could move the timer to the side, then everything probably fits in fullscreen. Requires setting https://developer.apple.com/documentation/bundleresources/information_property_list/nsprefersdisplaysafeareacompatibilitymode?language=objc to no

**Comment by heinrich5991** [comment]
Could also move the timer on just macOS a little down. Supporting hardware of a single vendor might be a bit much though. ^^

**Comment by def-** [comment]
Easiest fix is to explicitly disable fullscreen from going into notch area
