### ISSUE TITLE
degraded perfomance on 15.8 on windows 11

### ISSUE THREAD

**Issue by edg-l** [ddnet/ddnet#4537]
According to Rei ayanami on discord

Says 144 fps don't feel like 144 and on 15.7 it feels smooth

**Comment by def-** [comment]
vsync off? The main thing we did was SDL upgrade

**Comment by edg-l** [comment]
He had 1000 fps according to the gui so i don't think its vsync

**Comment by def-** [comment]
and when you run 15.7 again it's fine? Can you take the SDL2.dll from 15.7 and copy it into 15.8 directory. Does that fix it?

**Comment by Reiiayanami** [comment]
Hi I'm Rei ayanami. I did it and it feels smoother like it used to be. To verify this I opened the steam's version of the client 15.8 and it did lagging whereas the 15.8 version with the SDL2.dll from 15.7 was not lagging. Thanks you.

**Comment by def-** [comment]
As a workaround I'll release 15.8.1 with SDL2 reverted on Windows. If someone wants to look into this and figure out the source of the regression would be great.

**Comment by def-** [comment]
<img width="814" alt="Screenshot 2021-12-28 at 20 11 17" src="https://user-images.githubusercontent.com/2335377/147599177-75fc4e2a-8f71-43f1-8020-b81f33d358e8.png">
