### ISSUE TITLE
is it possible to make guys from other teams dont affect your spawn?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4543]
Suggested by Nice on Discord

Should be easy to implement, I'll take a look later.

**Comment by Zwelf** [comment]
Would probably be good to increase minor teehistorian version for this change. (Slight physics change)

**Comment by heinrich5991** [comment]
> Should be easy to implement, I'll take a look later.

Physics change, speed runners protested this change before.

**Comment by heinrich5991** [comment]
Duplicate #3041 btw.
