### ISSUE TITLE
Alt-tabbing takes ages on Windows 10

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#4549]
On a computer of a friend of mine, alt-tabbing takes a long time. This applies to desktop fullscreen and fullscreen.

It seems like Windows changes the resolution back and forth but both DDNet and the desktop are configured to use 1920x1080.

Is this a general Windows problem or do I need to figure out more details?

**Comment by def-** [comment]
Maybe different color depth between Windows and DDNet fullscreen?

**Comment by heinrich5991** [comment]
It seems that both on my friend's computer, the bit depth is 32 in Windows and 24 in DDNet.

I can confirm that this is the case on my other Windows laptop. Changing gfx_color_depth from 24 to 32 doesn't do anything, it resets on next start.
