### ISSUE TITLE
Hz problems in fullscreen modes with alt-tab

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4559]
<img width="1078" alt="Screenshot 2022-01-01 at 19 37 31" src="https://user-images.githubusercontent.com/2335377/147857767-67bcf60f-b795-4a59-8b5c-2180c3a0c7c0.png">

**Comment by def-** [comment]
I can't reproduce this on macOS. Probably a Windows-related problem.

**Comment by Jupeyy** [comment]
Weird bug, from our code paths it looks like it is impossible, except when the reported resolution list would change without changing GPU driver settings. That would be really unexpected.

Also he can set the refresh rate of windows to 144 hz, makes more sense anyway i guess

**Comment by Jupeyy** [comment]
texnonik approved it's fine now, probably fixed by #4602
