### ISSUE TITLE
Add timescore to HTTP server info

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#4561]
What would the design look like? Simply add a flag to the whole serverinfo that says that all scores should be interpreted as times?

CC @fokkonaut

**Comment by fokkonaut** [comment]
Yes, like in vanilla :)

**Comment by edg-l** [comment]
see https://github.com/ddnet/ddnet/issues/4415

**Comment by Robyt3** [comment]
Closed by #6585.
