### ISSUE TITLE
Give switched shields an attribute which weapon to delete

### ISSUE THREAD

**Issue by Zoozti** [ddnet/ddnet#4572]
Switched hammer off/on tile let u set which weapon they shall turn off by using the delay feature in switches. The same can work for shields as the delay isnt used for them yet.

Setup delay:

1 - removes Ninja from player
2 - unused or maybe deletes jetpack?
3 - removes shotgun from player
4 - removes grenade from player
5 - removes laser from player

This could help mappers A LOT for parts where they have to deal with more weapons  and dont want to create a  mess with different teleporters to give the player only a specific weapon and avoids the spam of weapon and shield tiles.

**Comment by Zoozti** [comment]
> Would need a different graphic. Maybe the shield could be colored with the weapon color?

or u place the weapon that should be deleted on the shield xD

**Comment by Zoozti** [comment]
> Would need a different graphic. Maybe the shield could be colored with the weapon color?
![anti_shield_grenade](https://user-images.githubusercontent.com/48534318/154580734-94efe765-2f47-451c-a929-f08f3a08640a.png)
![anti_shield_katana](https://user-images.githubusercontent.com/48534318/154580744-4f5ec8b8-3e7a-40cd-9f7e-6dd1b4217190.png)
![anti_shield_laser](https://user-images.githubusercontent.com/48534318/154580750-d4450974-f341-4699-ba65-60fc701f22da.png)
![anti_shield_shotgun](https://user-images.githubusercontent.com/48534318/154580756-db16eac1-f530-459f-b650-2f4de1b7d2c2.png)


Cellegen just made a nice looking design for this issue :) Now Someone just has to code it xD

**Comment by Zoozti** [comment]
![Untitled-2](https://user-images.githubusercontent.com/48534318/154583668-c948232d-c2e7-477b-8521-60c720bd8e5b.png)
![Untitled-1](https://user-images.githubusercontent.com/48534318/154583675-f421540c-f264-435e-bde6-5758fed433aa.png)


i guess its easier to just add 4 new tiles lol... its definitely very helpfull.

Cellegen made these 2 images also :)

**Comment by Zoozti** [comment]
![Untitled-3](https://user-images.githubusercontent.com/48534318/154587315-ada4336a-9e8f-49e2-899d-6509b1273174.png)


> Can you also ask Cellegen to make data/editor/entities_clear/ddnet.png with the transparency?

he did :D

**Comment by C0D3D3V** [comment]
partially implemented by  #5159 
@Zoozti if you still prefer the delay number option  then please open a new issue :D
