### ISSUE TITLE
/rescue after using /swap moves tee to old swap location

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#4578]
if only one tee is frozen:
https://user-images.githubusercontent.com/60477660/148668004-600e16fa-9f9c-4102-9af7-0e6a72d85430.mp4
If both tee are frozen:
https://user-images.githubusercontent.com/60477660/148668013-0d1fe55f-ccb9-45a7-bffd-9ae5d99ce39d.mp4
both videos resulted in a softlock

Reported by JimmyJazzThe1st

**Comment by def-** [comment]
I think this is fixed already. Should be tried to reproduce on nightly.

**Comment by def-** [comment]
https://github.com/ddnet/ddnet/pull/4504

**Comment by murpii** [comment]
@def- I tested it on a official ddnet server
