### ISSUE TITLE
direction (move arrows of tees)

### ISSUE THREAD

**Issue by hussainx3** [ddnet/ddnet#4589]
i suggest put layer direction above blocks
because when it's under blocks you can't see directions Tees
it's example here ⬇ i can't know  here  how he did it
was holding A? or a little A and B? or not move at all
https://streamable.com/8gdkk6

**Comment by GiuCcc** [comment]
Put arrows to overlay could be enough

**Comment by C0D3D3V** [comment]
I experimented a bit with this and thought the easiest thing to do would be to include the arrows in the nameplates.

Then you have no problem with the arrows being covered by the nameplates or the other way around.

The whole thing can then look like this:

Directional arrows under player name:
![b3113846_32b65b0b-157a-4cf5-b257-8b0949fbec36](https://user-images.githubusercontent.com/14315968/153576065-e3d31257-c9e1-483b-a076-4d87d8a33655.png)
![grafik](https://user-images.githubusercontent.com/14315968/153576119-710a2b69-5673-47f3-a32b-6726fa499849.png)

![grafik](https://user-images.githubusercontent.com/14315968/153576699-8b2047e0-82ea-49b4-b423-cf5ebed097e0.png)

Above nameplate but below Strong/Weak indicator:
![grafik](https://user-images.githubusercontent.com/14315968/153576240-29a3fe39-5c1d-4bda-8757-3914dc62e1b4.png)
![grafik](https://user-images.githubusercontent.com/14315968/153576270-03da3505-4fb7-48ab-a576-a15c27ce0d96.png)
![grafik](https://user-images.githubusercontent.com/14315968/153577026-76a598a0-0765-4828-bb99-c393f01607c4.png)

I will make the pull request today. Maybe someone has preferences what looks better

**Comment by def-** [comment]
I prefer below

**Comment by archimede67** [comment]
Closed by #4697.
