### ISSUE TITLE
Ctrl + backspace doesn't work in console

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet#4596]
Ctrl + backspace erases a whole word and works in normal chat in game, but not in console.

**Comment by heinrich5991** [comment]
Works for me.

Which version/OS are you on?

**Comment by Chairn** [comment]
OS: windows 7
Version: 15.5.4

**Comment by heinrich5991** [comment]
Can you update to the latest version (15.8.1) to see if it still happens there?

**Comment by Chairn** [comment]
OK, it works, sorry for the inconvenience.
