### ISSUE TITLE
Windowed mode

### ISSUE THREAD

**Issue by p21x** [ddnet/ddnet#4597]
OS: Windows 10 Pro 20H2
Client version: 15.8.1-win64
Radeon software version: 22.1.1

Every time I launch client in windowed mode:
- `gfx_screen_height` resets to 1421, despite the value 1440 in `settings_ddnet.cfg`
- Windows taskbar overlaps the game until I manually set 1440p resolution in settings.
Sometimes it also shows top border of the game window. Then I have to set resolution, relaunch the game and set resolution again.

This isn't the case in official 0.7.5 client.

I can't use borderless windowed mode, because every time I alt+tab, screen flickers black, as if the game was in fullscreen mode.
All other games work fine in borderless windowed.

![top_border](https://user-images.githubusercontent.com/48730210/149581046-2cc3e4be-9f88-4d15-9d5a-7bff6856f19c.png)
![taskbar](https://user-images.githubusercontent.com/48730210/149581041-43f2e4e9-cc87-4e01-ad81-340b16e4a5a5.png)

**Comment by def-** [comment]
This probably happens because we allow resizing the window and Windows tells DDNet to change its size to accomodate for the window decorations. Not sure how to fix this well. Can we include the window decorations in our size? I'll try it wit h SDL_GetWindowsSize.

**Comment by def-** [comment]
Alternatively, can you try using borderless windowed mode?

**Comment by p21x** [comment]
> Does it flicker too if you choose a smaller resolution?

It doesn't.
Looks like borderless windowed at native resolution behaves like fullscreen, and at lower resolution it behaves like windowed.

I wouldn't mind the flickering, but my GPU has a hardware issue where alt+tab in fullscreen in any program can cause PC crash. So I resorted to windowed borderless in all programs until I can replace GPU.

**Comment by Jupeyy** [comment]
it seems that not setting `SDL_WINDOW_RESIZABLE` for windowed mode works.
But also only for windowed mode, adding `SDL_WINDOW_BORDERLESS` makes windows think that this game actually wants borderless fullscreen when the resolution matches(and gives it exclusive fullscreen again).

This seems to be some weird edge case under windows.

It seems like d3d12 has no issues with all this stuff. I assume it somehow forces the DWM(desktop window manager) to stay alive, or windows gives the directx backends some control to make it work without breaking the desktop.

We could maybe add a 5th window option called "windowed fullscreen", that doesnt allow resizing and is a real windowed window.

I'll provide a patch, you have to test it

**Comment by Jupeyy** [comment]
@p21x 
You can download the artifacts here (requires you to be logged into github)
https://github.com/ddnet/ddnet/actions/runs/1794374746

**Comment by Jupeyy** [comment]
Seems like `SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 0);` would also fix all these issues.(probably windows does that internally in windowed mode).

But this introduces quite a bit of performance regression

**Comment by p21x** [comment]
> @p21x You can download the artifacts here (requires you to be logged into github) https://github.com/ddnet/ddnet/actions/runs/1794374746

I launched this version, windowed fullscreen works fine
Thank you🥳🎉
