### ISSUE TITLE
Prediction: Bullets clip through walls

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#4608]
Happens since version 15.7

https://user-images.githubusercontent.com/60477660/149666299-774efa4f-79ac-4e63-837c-b6af7dc22c36.mp4

Map: Miper 4

**Comment by trml** [comment]
@def- would it be ok to undo line 379 from a817a2e60fc6c91a58043d45b68094e820bfc193, i.e. remove`if(pProj->GetOwner() >= 0)`? Since the owner is checked later before accessing anything within that block, and since the code should still be run for owner < 0 in some cases.

**Comment by def-** [comment]
Sure!
