### ISSUE TITLE
Exit cleanly on kill signals

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4610]
Should catch TERM and INT and handle them cleanly, like shutdown in rcon console. This makes the fifo file get removed properly, remaining ranks stored in sqlite file etc.

**Comment by Robyt3** [comment]
See https://github.com/teeworlds/teeworlds/pull/2885 and https://github.com/teeworlds/teeworlds/pull/2963 if you want symmetry with upstream SIGINT handling. I suppose SIGTERM should behave the same as SIGINT?

**Comment by def-** [comment]
Yes
