### ISSUE TITLE
Android Build Error

### ISSUE THREAD

**Issue by user5015** [ddnet/ddnet#4615]
When I tried building DDNet for android, using the command-
`scripts/android/cmake_android.sh all DDNet Release`
I got the error: 
`> Task :compileReleaseJavaWithJavac FAILED
/home/-/-/ddnet-master/build_android/src/main/java/tw/DDNet/NativeMain.java:3: error: package org.libsdl.app does not exist
import org.libsdl.app.SDLActivity;`

I followed the instructions at [https://github.com/ddnet/ddnet/tree/7e697963cf9f7657a22d74fdd0f85032f73baa2e/scripts/android](https://github.com/ddnet/ddnet/tree/7e697963cf9f7657a22d74fdd0f85032f73baa2e/scripts/android).
I also used the precompiled DDNet Libraries.

**Comment by def-** [comment]
@Jupeyy any idea?

**Comment by Jupeyy** [comment]
There are no precompiled DDNet libs for android

**Comment by user5015** [comment]
Well, I guess that was my mistake then. I thought for some reason that [https://github.com/ddnet/ddnet-libs](https://github.com/ddnet/ddnet-libs) was compatible with android.

**Comment by user5015** [comment]
Ok, so now I tried compiling the ddnet libs for android. I ran
`scripts/android/gen_android_libs.sh ../`
in the DDNet source folder.

It gave me this error-
`[100%] Built target opus
[100%] Built target opus
[100%] Built target opus
[100%] Built target opus

mkdir: cannot create directory ‘ddnet-libs’: File exists
cp: cannot stat 'android_libs/curl/build_android_arm/lib/libcurl.a': No such file or directory
cp: cannot stat 'android_libs/curl/build_android_arm64/lib/libcurl.a': No such file or directory
cp: cannot stat 'android_libs/curl/build_android_x86/lib/libcurl.a': No such file or directory
cp: cannot stat 'android_libs/curl/build_android_x86_64/lib/libcurl.a': No such file or directory
mkdir: cannot create directory ‘ddnet-libs’: File exists
mkdir: cannot create directory ‘ddnet-libs’: File exists
mkdir: cannot create directory ‘ddnet-libs’: File exists
mkdir: cannot create directory ‘ddnet-libs’: File exists
mkdir: cannot create directory ‘ddnet-libs’: File exists
mkdir: cannot create directory ‘ddnet-libs’: File exists
mkdir: cannot create directory ‘ddnet-libs’: File exists`

**Comment by Jupeyy** [comment]
true

```cmake
CMake Error at CMakeLists.txt:355 (message):
  The option CMAKE_USE_OPENSSL was renamed to CURL_USE_OPENSSL.


CMake Error at CMakeLists.txt:363 (message):
  Reconfig required

```
