### ISSUE TITLE
settings cfg binds different output after save

### ISSUE THREAD

**Issue by Vy0x2** [ddnet/ddnet#4660]
**Description:**
- If you paste a long bind into the settings.cfg it gets translated correctly but the game cuts the bind off at some point and after the next start the bind gets useless or deleted because the interrupt is inbetween a command. Tested on Windows if that makes any difference

**Reproduce:**
1. paste this bind into your settings.cfg
`bind 0 "say 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001234"`
2. Open ddnet client and press 0
-> 000...001234 will be in the chat
3. Close ddnet client normal (no alt f4 or stuff like this)
4. Open ddnet client again and press 0
-> 000...00123 will be in the chat

**Possible Solution:**
- Allow some longer strings to be saved pls? :) Or dont let the bind work correctly the first time, so no confusion appears.

**Comment by Robyt3** [comment]
Relevant undersized buffers (first one is only used for console printing):

https://github.com/ddnet/ddnet/blob/155a922d47b227122db6317ba42764ca9da5da9f/src/game/client/components/binds.cpp#L72

https://github.com/ddnet/ddnet/blob/155a922d47b227122db6317ba42764ca9da5da9f/src/game/client/components/binds.cpp#L456

**Comment by Chairn** [comment]
Does it works everytime if you put it in binds.cfg, and then exec binds.cfg in your autoexec_client.cfg?

**Comment by def-** [comment]
Can't reproduce, works fine for me. Are you on nightly build or on released one? If released one, please check if https://ddnet.tw/news/nightly-build-revived/ fixes it

**Comment by Vy0x2** [comment]
> Does it works everytime if you put it in binds.cfg, and then exec binds.cfg in your autoexec_client.cfg?

Yes, because binds.cfg I think will not become overwritten.



> Can't reproduce, works fine for me. Are you on nightly build or on released one? If released one, please check if https://ddnet.tw/news/nightly-build-revived/ fixes it

Very weird, the bind gets cut off at a different place today. The string yesterday had a length of 231 and today it only got cut off at a length of 257, this makes sense now atleast because the array aBuffer has a length of 256. -> The `4"` gets cut off.
So I couldnt reproduce today with the bind above either but with this one:
`bind 0 "say 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001234"`
(26 more zeros)

Can be reproduced on nightly too.

**Comment by heinrich5991** [comment]
Can reproduce now.
