### ISSUE TITLE
🐛 Nvidia shadow play may record the wrong window

### ISSUE THREAD

**Issue by AssassinTee** [ddnet/ddnet#4673]
I was recording something with Nvidia shadowplay and the recordings were not showing DDNet but instead another window while I had the Popup ingame that I may start recording. I was using the newer OpenGl support and don't know how to reproduce this while it may have to do something with tabing out with ALT+TAB (which is not working for me)

**Comment by def-** [comment]
Wouldn't this rather be an nvidia shadow problem?

**Comment by Jupeyy** [comment]
I think without more precise information, why this should be caused by DDNet code, there is no way to fix it.
So we have to assume this isn't a bug in DDNet, reopen if you find out more

**Comment by AssassinTee** [comment]
I can reproduce it now. DDNet is running on the right monitor (monitor 1) while shadowplay is capturing the left monitor (monitor 0)

**Comment by Jupeyy** [comment]
Let's say it like this:
Shadow play knows about ddnet
but ddnet doesn't know about shadow play
;)
