### ISSUE TITLE
Something Wrong in Game Layer

### ISSUE THREAD

**Issue by Ninecloud2077** [ddnet/ddnet#4679]
I made a DDNet map and start it on server
Server tips some wrong in the game layer and report this to here
I checked the code about this tip but I still don't know why
I can upload the map if need

**Comment by Ninecloud2077** [comment]
By the way
How to cancel a rank if I updated the map?

**Comment by def-** [comment]
You could just delete the ddnet-server.sqlite file. (or open it with a sqlite client and remove ranks individually)

Can you upload the exact error?

**Comment by heinrich5991** [comment]
If the map is not secret, it would be nice if you could upload it as well.

**Comment by Ninecloud2077** [comment]
It's on github.com/Ninecloud2077/server_maps but I want to commit new one

**Comment by def-** [comment]
No error loading this map with DDNet-Server for me. Can you show the exact output and how you run the server?

**Comment by Ninecloud2077** [comment]
I use Ubuntu to start it
Mod is TestDDN
Use config flie which in ddnet-maps
Changed sv_motd sv_name sv_port and three passwords
sv_register 1
Didn't do anything else

**Comment by Robyt3** [comment]
Insufficient information.
