### ISSUE TITLE
No sound when the focus is not on DDNET

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#4690]
Is that a feature that you have no sound when DDNet has no focus? 
I run DDNET in I3 with PulsAudio on Arch Linux (5.16.2-arch1-1). 

Would it be possible to create a setting for this so that you can select whether the sound is played without focus?

**Comment by Jupeyy** [comment]
and does it work when its on 0 xd

**Comment by C0D3D3V** [comment]
yes lol thanks

**Comment by Jupeyy** [comment]
great, bad naming for the config, but if we change it we change all config for all players :D
