### ISSUE TITLE
/practice teleport can be used to gain weapon projectiles at start

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#4694]
From [Discord](https://discord.com/channels/252358080522747904/757720336274948198/941506044750868500):
> [2:28 AM] louis: although i haven't found out any maps, you can use /tp to teleport to some "winner room" or shotgun/laser in practice, /tp back to spawn, shoot the laser/shotgun, then kill immediately so the weapon bounces back on you after you kill

**Comment by heinrich5991** [comment]
I disabled /practice on all servers.

**Comment by heinrich5991** [comment]
This is theoretically also an issue for /r.

**Comment by def-** [comment]
Ok, apparently not. So let's reset weapons when /practice has been used.
