### ISSUE TITLE
Duplicate message detection interacts badly with whispers

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#4696]
From [Discord](https://discord.com/channels/252358080522747904/757720336274948198/941558672918708315):
> [5:58 AM] Broso56: small anti-spam bug where if your in whisper and someone types the same message as you it doesnt make a sound or a new message but just adds a [2] next to whatever message was sent
> [6:00 AM] Broso56: so instead of 
> -> Friend: test
> <- Friend: test
> its just
> -> Friend [2]: test
>
> and no other message, even though the message was sent by 2 different people
>
> ![image](https://user-images.githubusercontent.com/366230/153585192-4c5fd6b9-05b1-4bd6-95a7-41881b61ee69.png)

@edg-l Ideas?

**Comment by def-** [comment]
In order to tell duplicate we have to keep track of who sent it too, not just the content of the message.

**Comment by srdante** [comment]
@def- We just need to check if its sending or receiving whisper
