### ISSUE TITLE
[GUI/SUPER] Key

### ISSUE THREAD

**Issue by FallenKN** [ddnet/ddnet#470]
Since we are ignoring those inputs, this will cause some useless buttons under some linux-systems.(appeared on Cinnamon-Desktop)
Whenever I press LGUI/LSUPER my System-Menu pops up without any accessibility, because DDNet still is stealing the focus (Mouse&Keyboard-Inputs).

![bug](https://cloud.githubusercontent.com/assets/13277346/15059845/cfd254a2-1325-11e6-8e8e-88134666ee53.png)

What about assigning LGUI/LSUPER to minimize?

**Comment by def-** [comment]
How was this in DDNet 9.3.1?

**Comment by FallenKN** [comment]
In 9.3.1 nothing happend default by pressing, but atleast I was able to bind minimize to it

**Comment by def-** [comment]
I'm still wondering why this behaviour exactly changed from SDL1.2 to SDL2. For your specific case we could have keyboard grab, then no key inputs would reach the window manager.

**Comment by FallenKN** [comment]
I don't really know either, but I rather have this bug instead of not being able to 'alt-tab'.
To tabbing out under Linux with SDL2 was one of the biggest benefits.

**Comment by def-** [comment]
Can you compile from git? Could you check if this fixes your issue? https://git.io/vwA6D

Otherwise we could probably also handle `SDL_WINDOWEVENT_ENTER` and `SDL_WINDOWEVENT_LEAVE`.

**Comment by FallenKN** [comment]
sadly this is not solving the problem, it only encounters in fullscreen-mode by the way

**Comment by def-** [comment]
Try using borderless window instead of fullscreen, it's better anyway.

**Comment by FallenKN** [comment]
while trying to play with borderless window I experienced some other bugs, for example I can activate borderless window and fullscreen at the same time and with much MouseDPI the mouse can leave Teeworlds while playing without input grab.

**Comment by def-** [comment]
That's always been the case to my knowledge.

**Comment by CytraL** [comment]
@FallenKN you can use RIGHT+LEFT Mouse click at the same time in Linux Mint? you know how disable this bind in the system? by default RIGHT+LEFT = Middle Click, but if disable it only disabled the action not the bind :/

Sry for offtopic :S

**Comment by FallenKN** [comment]
@CytraL This was already disabled, anyways I switched to another Distro.

My Reason to create this "Topic" was to assign minimize to LSUPER by default not more.

**Comment by josephgbr** [comment]
For the record, I use Arch Linux + GNOME 3.20 and I play in borderless window mode. Since DDNet version 10.0.1, the Super key won't work for me to call the GNOME's Activity Overview (equivalent of Start Menu of Windows). I also reported this in the [forum](https://forum.ddnet.tw/viewtopic.php?t=3618).

**Comment by def-** [comment]
I tried `inp_ignored_modifiers 1024` (f1) and `SDL_HINT_GRAB_KEYBOARD 0` (in backend.cpp) but neither worked. I guess this is an issue with all SDL2 programs and might even be intentional?

**Comment by Robyt3** [comment]
Is this still an issue with recent versions of the client? @FallenKN @rffontenelle

**Comment by Robyt3** [comment]
Thanks for checking, @rffontenelle.

I'll consider this fixed with recent client versions until we get another report.
