### ISSUE TITLE
Self-prediction regression in 15.7 on Jajpack

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#4702]
From [Discord](https://discord.com/channels/252358080522747904/757720336274948198/941846284556447764):
> [1:00 AM] plsplsplslol: self-prediction in switched freeze doesn't work with high ping on 15.7 version. if you play Jajpack with high ping, your tee won't be predicted at all (like playing with cl_predict 0) and will constantly jump around. this doesn't happen on ddnet 15.5.4
> [3:11 AM] plsplsplslol: it works better on 15.8.1 but it still has very noticable lag when you cross the start on Jajpack

**Comment by trml** [comment]
The start tiles on that map also have timed switch activation tiles under them, and the lag seems to caused by there being no prediction for those.
I made an attempt at adding prediction for it, but it seems like it will require a few things to work properly.
