### ISSUE TITLE
DDNet doesn't load some visual assets when Streaming through Discord, showing black squares

### ISSUE THREAD

**Issue by AlexeSimon** [ddnet/ddnet#4711]
Happens when using Discord to stream with direct application capture.
Doesn't happen with other games or other capturing programs.
Assets that aren't loaded seem to be random.
Need to fully restart DDNet in order to get the assets.
Starting the stream on an already started DDNet will unload assets and replace them with black squares (visible to both player and viewers).
Tried to change DDNet settings (OpenGL, full screen, etc) and Discord settings without success.

Opening this issue to document the phenomenon, even if it won't be fixed. 
Quoting Learath2 "Yep, we never figured out why this happens sadly".

![unknown](https://user-images.githubusercontent.com/43810016/154069215-ff214a1f-33ea-428c-bb14-39edb128ef4a.png)
![unknown](https://user-images.githubusercontent.com/43810016/154069223-1594f48d-5d24-4156-a6de-a5dbdf52876f.png)
![unknown](https://user-images.githubusercontent.com/43810016/154069233-ebc8aa5b-41c1-4be9-9602-7af050264838.png)
![unknown](https://user-images.githubusercontent.com/43810016/154069238-22b0e5e0-392a-4777-9739-71143629bb43.png)
![unknown](https://user-images.githubusercontent.com/43810016/154069243-4275f9f0-79a0-4c5b-83c2-d51ba5b91e48.png)

**Comment by Jupeyy** [comment]
Please report this to discord, there is nothing we can do

**Comment by Jupeyy** [comment]
The only guess I had was that discord uses a software renderer that has worse defaults than your GPU. But this should only affect OpenGL 3.3, but you said on discord you disabled it (`gfx_enable_texture_unit_optimization 0` would be the related command for this)

**Comment by def-** [comment]
https://support.discord.com/hc/en-us/articles/360046057772-Discord-Bugs

**Comment by Learath2** [comment]
FWIW I have this issue with DDNet, but not with DOOM (2016) which also runs on GL.

**Comment by AlexeSimon** [comment]
You may then tag this as wontfix (or whatever you use) and I'll report the same discord side.
I still think this should be documented here as it is easy for an user like me to think DDNet is the one at fault, as I never experienced this issue with any other games in my lengthy library.

**Comment by Jupeyy** [comment]
> FWIW I have this issue with DDNet, but not with DOOM (2016) which also runs on GL.

Ok, but let me ask one simple thing.
Why does it run without problems, when discord streaming isn't injected?
There simply must be a reason, and doom probably runs on OpenGL 4.5 which already uses bindless texture samplers, similar to vulkan's descriptors

**Comment by Jupeyy** [comment]
I downloaded the discord app now to test this, I cannot even reproduce this.

Do you have a nVIDIA GPU? I think all reports yet were from that.

Anyway, as Learath said on discord, we could try if the vulkan backend fixes it

**Comment by AlexeSimon** [comment]
After many tests with the Discord team we found the culprit:
**- Toggle off the "Use our latest technology to capture my screen" setting under User Settings > Voice & Video**
Closing this issue.

**Comment by Jupeyy** [comment]
Thanks for finding this out!

**Comment by Learath2** [comment]
If only they would divulge the "latest technology" that'a causing the issue we could debug and finally figure this out
