### ISSUE TITLE
Scotland flag.

### ISSUE THREAD

**Issue by ZombieToad** [ddnet/ddnet#4739]
Hello, as the [scottish government changed the colour of the flag of Scotland](https://web.archive.org/web/20120513070521/http://www.law.ed.ac.uk/sln/blogentry.aspx?blogentryref=7261), why not change it ingame for the next update? the blue is lighter on the new one. Here is a preview :

![🏴󠁧󠁢󠁳󠁣󠁴󠁿](https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Flag_of_Scotland.svg/256px-Flag_of_Scotland.svg.png)

Thanks in advance.

ZombieToad.

**Comment by def-** [comment]
Your image doesn't have the TW-style shade.

**Comment by ZombieToad** [comment]
hello sry i am not a graphic designer thats why i didnt open pull request. i just showed preview of the wikipedia image

**Comment by SoulyVEVO** [comment]
![XSC](https://user-images.githubusercontent.com/61762251/154816700-8ed1ad53-7547-425e-b4d7-afd34fd4ecd0.png)
