### ISSUE TITLE
Prediction makes feet flicker while standing on 255 jump tile

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4753]
which disables double jump.

@heinrich5991 want to take a look?

**Comment by Zoozti** [comment]
i still say we should drop the 255 limit at all. On KoG theres already a map that barely worked with 255 teleport numbers.

**Comment by heinrich5991** [comment]
(The 255 limit is pretty technical and not entirely trivial to remove.)

**Comment by heinrich5991** [comment]
How do I reproduce the bug? I can't get it to flicker.

**Comment by def-** [comment]
I joined local server and stood on top of the 255 jump tile at the start of tutorial map.

**Comment by heinrich5991** [comment]
It only seems to happen for me if I use either an old client or an old server. With the newest Steam version, I can't get it to happen. Can you try again?

**Comment by def-** [comment]
Ok, problem is on my side. Somehow I have DDNet 15.8.1 on my system even though homebrew should have updated it.
