### ISSUE TITLE
DDNet-Server writes to steam directory

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#4755]
The Server still writes to the steam directory `ddnet-server.sqlite` & `autoexec_server.log`
I guess it would be nicer to see the steam directory as read-only, who knows what permission problems this can cause on Windows

**Comment by def-** [comment]
Yes, I also don't like this in particular.

**Comment by ChillerDragon** [comment]
Would also be nice to create the ddnet-server.sqlite file in $USERDIR instead of $CURRENTDIR by default
