### ISSUE TITLE
Database connection failed, teamsave stored in sqlite

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4757]
@Zwelf I noticed these failures will always use the random 3 word password, which is then unguessable for the players. I'm not sure if there is a good way to solve this, just using their pw will fail when it already exists in real db.

Ideal would be to try the proper pw if it's unused, otherwise generate the 3 word one so we have it for admins to look up at least. Or maybe we should keep trying saves for a longer time instead of failing so quickly?

**Comment by heinrich5991** [comment]
People can check their ddnet-saves.txt nowadays.

Perhaps we could make it explicit that the save failed and only allow to save with /saverandom which generates these three words?

**Comment by heinrich5991** [comment]
> Ah, in this case the client still gets a message with the save code? Didn't know.

Yup.
