### ISSUE TITLE
Emoticons of the players are rendered behind the nameplate

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#4767]
What has been bothering me forever is that emoticons are rendered behind player names. I find that a bit unattractive because the emoticons are sometimes very beautiful and it would be cool if you always see them.
![image](https://user-images.githubusercontent.com/14315968/156173704-a533e682-3bc2-42b6-b00e-5db1ec014a0f.png)

Of course, they are also covered by blocks, since they are rendered in the player component.
![image](https://user-images.githubusercontent.com/14315968/156174100-65016521-9638-4790-97f7-d9eb8f45458f.png)

May I make a component "PlayersEmoticons" in which the emoticons are rendered? I would put them in the chain after NamePlates.

What is your opinion on this? I'm willing to implement it (it's not much effort), but there should be approval from you.

**Comment by Jupeyy** [comment]
Guess there are arguments against and for.
- Someone could hide his name behind the emoticon for whatever reason. It's less readable when someone spams it(e.g. by bind). It doesn't really affect gameplay, someone will always be against it xd

- emoticons with text cannot really be read with name above, depending on the situation the nameplate is mostly useless (counter to the pro argument), and your argument: emoticons are a piece of art

Guess its a "yet another config problem"

**Comment by C0D3D3V** [comment]
Yes, I have also thought about emoticon-spammers. But we also have the possibility to deactivate the emoticons in the player options for individual players. 
Previously, spammed emoticons were also usually mitigated by the nameplates (were partially covered and thus disturbed perhaps a little less), if the emoticons are above the nameplates are of course more concise and interfere with spamming perhaps more.
Personally, however, I have already deactivated emoticons for individual players, especially when the emoticons are binded to different actions that then disturb the whole time.
