### ISSUE TITLE
Server crashes (with ASAN) when recording a server demo

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#4781]
Use `record` in the rcon and try playing a map, in particular with a dummy. The following errors occur with ASAN/UBSAN:

```
/src/engine/server/server.h:465:63: runtime error: index -1 out of bounds for type 'CClient [64]'
    #0 0x55e948e5b3d4 in CServer::IsSixup(int) const (/build-asan/DDNet-Server+0xbfb3d4)
    #1 0x55e9491373be in IGameController::Snap(int) /src/game/server/gamecontroller.cpp:603
    #2 0x55e9490e5352 in CGameContext::OnSnap(int) /src/game/server/gamecontext.cpp:3639
    #3 0x55e948ddaf37 in CServer::DoSnapshot() /src/engine/server/server.cpp:856
    #4 0x55e948e21e59 in CServer::Run() /src/engine/server/server.cpp:2664
    #5 0x55e948e50b19 in main /src/engine/server/server.cpp:3732
    #6 0x7f831168e0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
    #7 0x55e948d99e5d in _start (/build-asan/DDNet-Server+0xb39e5d)
```

```
/src/game/server/gamecontext.h:471:52: runtime error: shift exponent -1 is negative
    #0 0x55e948fdfced in CmaskOne(int) /src/game/server/gamecontext.h:471
    #1 0x55e948fdfd3e in CmaskIsSet(long, int) /src/game/server/gamecontext.h:474
    #2 0x55e94901a1d3 in CProjectile::Snap(int) /src/game/server/entities/projectile.cpp:338
    #3 0x55e949154d1a in CGameWorld::Snap(int) /src/game/server/gameworld.cpp:124
    #4 0x55e9490e5805 in CGameContext::OnSnap(int) /src/game/server/gamecontext.cpp:3650
    #5 0x55e948ddaf37 in CServer::DoSnapshot() /src/engine/server/server.cpp:856
    #6 0x55e948e21e59 in CServer::Run() /src/engine/server/server.cpp:2664
    #7 0x55e948e50b19 in main /src/engine/server/server.cpp:3732
    #8 0x7f831168e0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
    #9 0x55e948d99e5d in _start (/build-asan/DDNet-Server+0xb39e5d)
```

When I hooked a dummy, the server crashed with `Illegal instruction (core dumped)` and no further log.

When the server doesn't crash, watching the resulting demo is very glitchy. Should be further investigated with ASAN whether that will be fixed on the server side or if client fixes are needed.

For the server, a server demo means that the `SnappingClient` will be `-1` when creating the snapshot. For the client, a server demo will have no local client, i.e. `LocalClientID` being -1.

**Comment by C0D3D3V** [comment]
Only for the server demos are the snapping client IDs  set to -1, right? Since I have just fixed both conditions, I would then directly refactor the -1 everywhere so that it has more meaning when reading the code.

**Comment by C0D3D3V** [comment]
Is it possible to change the position in a server demo? So that you watch a player? I just wanted to test whether I have fixed all conditions xD

**Comment by C0D3D3V** [comment]
I have overlooked that you can use R_shift, I usually only use L_shift. :D ok, seems to work, I'll open a PR.

**Comment by Robyt3** [comment]
> Is it possible to change the position in a server demo? So that you watch a player?

I think that's a client-side bug. Server demos should always start in free-view spectator mode.

**Comment by C0D3D3V** [comment]
I tried to reproduce your errors, but somehow ASan/UBSan does not output them at all. I see in the demo files that e.g. the pickups and projektiele are missing, but the errors are not output. Can you tell me if I have done something wrong? I have proceeded as described here: https://github.com/ddnet/ddnet#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck and have started the server in the client directly.

**Comment by C0D3D3V** [comment]
I have now fully tested my changes, all projectiles, pickups and hooks worked, can you please test it too because for me ASan/UBSan still doesn't work.

**Comment by def-** [comment]
Tested with ubsan, seems to work, no crash yet.
