### ISSUE TITLE
Move ingame binds console output to another level

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#4789]
Starting the game, without joining a server, reveals all binds including moderator rcon login binds. Lynn accidentally leaked hers whilst streaming.

**Comment by def-** [comment]
in the black console window on Windows? This is disabled by default (`cl_show_console 0`)

**Comment by def-** [comment]
Or in the binds in F1?

**Comment by murpii** [comment]
> Or in the binds in F1?
Binds in F1
