### ISSUE TITLE
Do not reset envelopes when starting a race

### ISSUE THREAD

**Issue by Henningstone** [ddnet/ddnet#479]
https://www.teeworlds.com/forum/viewtopic.php?pid=118240

The creator of this thread requested not do reset envelopes when passing the race lines, which happens because the gametimer for the particular player is being reset to zero. It is actually very annoying that e.g. clouds or whatever jump back to their starting position every time you restart the race...

> All I want is for the Envelopes to not get reset to zero every time you go over the race lines.

**Comment by def-** [comment]
This is also annoying to mappers who want to use sounds in DDNet maps. So a solution would be nice. Choices I see:
- A flag in new maps that tells the client to use the time from when it joined the server, not the start line (would only work with new DDNet clients)
- Server doesn't reset the time when you cross the start line, instead introduce a separate timer for the time since start line (a bit more hacky, breaks some old maps, works with all clients)

**Comment by Henningstone** [comment]
Your first solution would break synchronized envelopes, so that can't really be a solution, so I would rather choose the second one modify it a bit. 
I had the idea to store the current gametimer when starting a map, and while we are in a race, calculate the envelopes (and also sounds as you mentioned that) from `stored gametimer + current racetimer`. When we pass through the finish line, just use the server's gametimer again. That should keep it smooth if my thoughs were correct.

**Comment by heinrich5991** [comment]
Second solution would also "only work with DDNet client", other clients wouldn't see their current race timer.

**Comment by Henningstone** [comment]
Definitely for non-ddnet clients, the race timer must stay at the top of the screen, just as anybody is used to. I guess there will certainly a lot of complaining from anybody who plays with a non-ddnet(-based) client if it would be removed.
So it seems that leaving everything as it is for non-ddnet clients and fixing it rather clientside might turn out as the most practical solution, doesn't it? (Additionally, it would also be the simplest :wink: )

**Comment by heinrich5991** [comment]
The original author retracted their request btw.

**Comment by def-** [comment]
Oh, didn't know about the "synchronized" envelope flag. Does that work for sounds as well?

**Comment by Henningstone** [comment]
> Removing the X in the box for "Synchronized" envelopes does indeed fix the issue.

Hm, true... But why are there so many maps which have synchronized background envelopes? That makes just no sense and justifies that one could think it's a bug :worried:

**Comment by def-** [comment]
I guess that mappers have no idea what it does. Maybe improve the description text at bottom in editor and write a DDNet forum post about it.

**Comment by Soreu** [comment]
Yea, pretty much nobody knows about it or how it works
e.g. https://forum.ddnet.tw/viewtopic.php?f=13&t=3427&start=20#p36324

Maybe just set it by default to be unchecked instead of checked as it is now?
