### ISSUE TITLE
CMake error! Can't create makefile

### ISSUE THREAD

**Issue by ST-Chara** [ddnet/ddnet#4804]
System: Ubuntu 20.04 Desktop LTS

Output message:
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/flowerfell-sans/桌面/ddnet-client/AVCODEC_INCLUDEDIR
   used as include directory in directory /home/XX/桌面/ddnet
/home/flowerfell-sans/桌面/ddnet-client/AVFORMAT_INCLUDEDIR
   used as include directory in directory /home/XX/桌面/ddnet
/home/flowerfell-sans/桌面/ddnet-client/AVUTIL_INCLUDEDIR
   used as include directory in directory /home/XX/桌面/ddnet
/home/flowerfell-sans/桌面/ddnet-client/SWRESAMPLE_INCLUDEDIR
   used as include directory in directory /home/XX/桌面/ddnet
/home/flowerfell-sans/桌面/ddnet-client/SWSCALE_INCLUDEDIR
   used as include directory in directory /home/XX/桌面/ddnet
AVCODEC_LIBRARY (ADVANCED)
    linked by target "DDNet" in directory /home/XX/桌面/ddnet
AVFORMAT_LIBRARY (ADVANCED)
    linked by target "DDNet" in directory /home/XX/桌面/ddnet
AVUTIL_LIBRARY (ADVANCED)
    linked by target "DDNet" in directory /home/XX/桌面/ddnet
SWRESAMPLE_LIBRARY (ADVANCED)
    linked by target "DDNet" in directory /home/XX/桌面/ddnet
SWSCALE_LIBRARY (ADVANCED)
    linked by target "DDNet" in directory /home/XX/桌面/ddnet-client
X264_LIBRARY
    linked by target "DDNet" in directory /home/flowerfell-sans/桌面/ddnet-client

**Comment by Jupeyy** [comment]
```bash
sudo apt install libx264-dev libavfilter-dev libavdevice-dev libavformat-dev libavcodec-extra libavutil-dev
```

**Comment by Jupeyy** [comment]
@def- i guess now that we enable it by default we should move the ffmpeg package install in the README to the `Dependencies on Linux / macOS`section
