### ISSUE TITLE
inconvenience with /top5 global and /top5 local display

### ISSUE THREAD

**Issue by l-ouis** [ddnet/ddnet#4810]
I think /top5 global and /top5 local should be displayed separately in all cases, or with separate commands.

When a player from your region is in top5, the local top5 isn't displayed. 

I think this is already a bad way of displaying them since it requires a player doing /top5 to already be familiar with players in their region, which usually isn't the case.

let's say this is the top 5 for a certain map:
1. player1 (GER)
2. player2 (GER)
3. player3 (GER)
4. player4 (USA)
5. player5 (GER)

Now, if I were to join a USA server and do `/top5 #` where # is from 1 to 4, it would only show the global top5, since player4 has rank 4 and they did it on a USA server, meaning they will still show up in the global list. However, once I do `/top5 5`, player4 will no longer be in that list, so it will show local ranks, **_starting from local rank 5._**

So, from my understanding there is no way to find local ranks 2-4 in this scenario.

**Comment by def-** [comment]
@kyle-bradley ^

**Comment by def-** [comment]
@kyle-bradley are you available and interested in working on this?

**Comment by def-** [comment]
My approach would be to just always show global top 5, and local top 3, no matter what. Thoughts?

**Comment by srdante** [comment]
I believe that @def- 's suggestion would be the best one. Would solve the problem mentioned in the pull request in reference, and it's also practical to see both ranks at the same time, it's not such a big message to split into two commands.
