### ISSUE TITLE
The MySQL mode actually works correctly only for MariaDB

### ISSUE THREAD

**Issue by srdante** [ddnet/ddnet#4815]
The actual code does not work correctly using MySQL 8.0. Actually the `/top`, `/top5`, `/points`, `/top5points`, `/top5team`, `/rank` and `/teamrank` commands throw a SQL error.

**I didn't do a thorough analysis to see what's causing an error in the queries of the other commands.**

### `/top` and `/top5` Solution:

On MySQL 8.0 the Rank column needs to be scaped as \`Rank\` for some reason (The other columns is not needed).

After escaping the column name, the error changes to the following one:

```
#1055 - Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'test_db.record_race.Server' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

This second error happens since the `ONLY_FULL_GROUP_BY` flag on sql_mode is set by default on MySQL 8.0.

The group by for the this query should be `Name, Time, Server` instead of only `Name`.

**Comment by def-** [comment]
I'd definitely accept a PR for this if you can fix it. You could maybe even add a mysql installation in .github workflow so we test this in addition to mariadb, then we  don't break it again so easily.
