### ISSUE TITLE
Bindings for dummy (new feature?)

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#482]
Would be nice to have binding possibility to send to your dummy move actions (including jumping, even maybe shooting, etc)

bind b "+jump;toggle cl_dummy 1 0; +jump" is a worse solution wich works for now
unfortunelly bind b "+jump;toggle cl_dummy 1 0; +jump; toggle cl_dummy 1 0" not works.

May be very helpfull for many situations. I know this for sure. Many times i`m tryed to cheat bind system for passing with dummy parts like this 
![screenshot_2016-05-14_22-01-23](https://cloud.githubusercontent.com/assets/17499770/15270253/689d1cc4-1a21-11e6-8e02-189ab6151704.png)
in my past teeworlds gaming life

**Comment by def-** [comment]
As I said in forum, I consider dummy too powerful already and would rather see it removed and replaced with server-side dummies from iDDNet.
