### ISSUE TITLE
Cannot Get Full Servers in Server Browser!

### ISSUE THREAD

**Issue by ST-Chara** [ddnet/ddnet#4820]
Cannot get Full Servers in Server Browser the latest version of DDNet launcher

But i can get All servers in old DDNet!

**Comment by ST-Chara** [comment]
I can't get ALL Server name start by "626-Net"

**Comment by Jupeyy** [comment]
Seems like "626-Net" servers regulary fail to be part of the server list. I dont see how it is related to any ddnet version since https masters

**Comment by ST-Chara** [comment]
DDNet-14.2-linux_x86_64
This version is work

**Comment by ST-Chara** [comment]
![2022-03-14 12-31-29 的屏幕截图](https://user-images.githubusercontent.com/74450074/158105339-5789fbb5-5fc2-4578-a30b-a2f6e99fff50.png)
There photo

**Comment by C0D3D3V** [comment]
@ST-Chara 
How many 626-Net servers exist? Aren't the 5 already all?

**Comment by ST-Chara** [comment]
> @ST-Chara How many 626-Net servers exist? Aren't the 5 already all?

@C0D3D3V  Only the old version of ddnet client can see those servers!
Search it in newest DDNet Client!

**Comment by Jupeyy** [comment]
> Seems like "626-Net" servers regulary fail to be part of the server list.

^

I sometimes see them

**Comment by heinrich5991** [comment]
This seems like it might be a problem with the backward compatibility of the HTTPS masters. It is maintained here: https://github.com/heinrich5991/libtw2/tree/444e3e0160dec74afcf82e8e42398fe2027a76a2/stats_browser. I currently do not spend time on improving it.
