### ISSUE TITLE
Compact friends tab

### ISSUE THREAD

**Issue by kaitlynia** [ddnet/ddnet#4824]
Feature request: Add a setting to hide clan row from friends entries in the browser tab. I often don't care to know if the clan matches and people frequently change this anyway, so I want to cut down on the size of these vertically so it is easier to scan.

Recommended names for this:
- `cl_friends_compact`
- `cl_friends_hide_clan`

**Comment by def-** [comment]
Generally we don't want to add more options, it means we have more combinations to maintain and more chances for bugs.

**Comment by Chairn** [comment]
There's already `cl_friends_ignore_clan` to ignore it, but it still shows it. You can also edit ddnet.cfg when game is closed to remove the clan of all your friends so that it shows an empty row.

**Comment by Robyt3** [comment]
Friends tab was overhauled. Agree that we don't want more options for this.
