### ISSUE TITLE
Fallback skin option

### ISSUE THREAD

**Issue by kaitlynia** [ddnet/ddnet#4825]
The ability to add your own skin to your client is not very useful since other clients cannot download it. I understand this is already a common request, but in the meantime I suggest a different feature: an option to provide a fallback skin the case the client does not have the requested skin.

For example, I use a variant of the `whis` skin but I don't want other whis users to show as this skin. My solution would be to use my own name for it, but then everyone complains I am "bald" and I'm re-encouraged to just deal with having `whis` as the name for it.

UI in the skin settings page is problematic since there's no room for a text box like this, and it would likely need to be console-only or reconcile with the space used on that page currently.

Command name ideas:
- `player_skin_fallback`
- `dummy_skin_fallback`

Selected custom colors would apply to this skin as well.

**Comment by def-** [comment]
I'm against this. default skin should be shown. We don't want to allow players to show all skins since it means showing lots of bad skins. If you don't mind this, use this and tell your friends: https://skins.tw/how-to/ddnet-integration

**Comment by C0D3D3V** [comment]
The ability to set a fallback skin would tempt people to not share their own skin with others (or only with a certain group). Since we are a community-driven game, I think this is not a good idea. It would be better to improve the process of adding skins to the official repo or use skins.tw.

**Comment by sjrc6** [comment]
I think I agree with deen, I'm not sure having a backup skin is the best way to solve this. I do think there should be a way to know if someone is using the default tee or a skin that you don't have, and what the name of that custom skin is.
