### ISSUE TITLE
Kill splash effect not respecting Teeworlds Team color

### ISSUE THREAD

**Issue by srdante** [ddnet/ddnet#4836]
Currently when a game mode uses mode with Blue and Red team. The client automatically overwrites the tee colors for their respective teams. All effects and displays, whether in the kill history, in the tab and in the game respect the color of the current team.

With the exception of one effect, the explosion effect on tee death. This effect continues to follow the skin color or custom tee color, rather than the team color.

The teeworlds 0.6 server side, under the hood, updates tee colors when switching or joining teams to the correct color. But that wouldn't be necessary if the kill splash matched the team color automatically on client side (like all other visual elements).

**Comment by def-** [comment]
Yes, could be fixed if you want to work on it.
