### ISSUE TITLE
Game menu opens when console is opening

### ISSUE THREAD

**Issue by tyurderi** [ddnet/ddnet#484]
When I am ingame and opening the console via F1 and while the open animation is running and I press ESC to open the game menu opened too. This only works when the animation is running, not when its finished.

Before SDL2 this didn't worked and is a little bit annoying.

**Comment by timakro** [comment]
Do you want to be able to close the local console while the opening animation is still running?

**Comment by tyurderi** [comment]
Exactly, when pressing ESC it should close the local console while the animation is still running.

I've been used this to keep my hook hooking without using my mouse.

**Comment by Rootkitee** [comment]
Holding your hook with mouse then pressing ESC can keep it attached too (You can hit ESC again and chill without mouseinput)

**Comment by tyurderi** [comment]
@Rootkitee Well, never thought of doing that this way. 

Not sure if this issue should be fixed anyway.

**Comment by Soreu** [comment]
1. `[F1]` (to open console) → `[Esc]` – Immediately closes console, doesn't matter whether fully opened or in middle of animation
2. `[F1]` (to open console) → `[F1]` (to close console) → `[Esc]` – Cancels closing animation, and console remains open


To me it looks logical, or does it works differently on your OS?

**Comment by tyurderi** [comment]
@Soreu Yea, the first one doesn't works on my OS. It's ubuntu 14.04 (elementary os)

**Comment by tyurderi** [comment]
Works fine, thank you.
