### ISSUE TITLE
mapping when you slice quad and then press on " Square " it rotates this qauds

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4864]
Texnonik reports:

> mapping when you slice quad and then press on " Square " it rotates this qauds

![bf49fd5020f79559cc7ba1e105e3e4cc](https://user-images.githubusercontent.com/2335377/159344049-f974cbd5-7f2f-4934-8c16-34135ec52183.png)

@HiRavie could this be caused by your change?

**Comment by def-** [comment]
![Screenshot 2022-03-21 at 19 57 20](https://user-images.githubusercontent.com/2335377/159344450-bc297344-db20-4632-925d-8b2dfe305f8c.png)

**Comment by HiRavie** [comment]
The order in which the vertices are created matters. If they're not created in a clockwise order starting from the top-left one, it's basically like creating an already rotated quad. Clicking _Square_ on a rotated quad changes it back to default orientation even if it's not made by slicing. This is correct behavior imo.
