### ISSUE TITLE
Entities only mode feature

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#487]
On huge graphical mapps slow laptops could have a lot of troubles, when you need to disable all huge layers with huge lags.

Solution - Entities only mode for editor - hiding/showing all sound, tile, quads layers
Its also very nice when comfortable, and I wish this feature much <3

**Comment by timakro** [comment]
How would you disable them?

**Comment by BannZay** [comment]
Found all and hide them usnig "visible" property ( then this layers wont be rendred)

**Comment by timakro** [comment]
So your problem is it is too laggy to press all the visible buttons and you want a shortcut that presses the visible buttons of all non game layers?

**Comment by BannZay** [comment]
Ye in fact it just a shortcut which can help you with many times clicking on maps with big count of laters.
Could be helpfull for testers, weak laptops or just for mappers

**Comment by def-** [comment]
You can click V on a group to hide the entire group, that's good enough.
