### ISSUE TITLE
Freeze bullets don't render corretly.

### ISSUE THREAD

**Issue by luk51** [ddnet/ddnet#4873]
This is how it looks
rendered:
![rendered](https://user-images.githubusercontent.com/4086396/159645252-1cc75376-d419-4f18-aaae-39ab850d5190.gif)
screencast:
![screencast](https://user-images.githubusercontent.com/4086396/159645295-b09c5a55-7fcf-4216-80c6-4e922b04b787.gif)

In the rendered the bullets go through the tee, without freezing it.

**Comment by def-** [comment]
So it's the same in demo viewer?

**Comment by 1uk** [comment]
Hi,
no. Rendered bullets have random timing.
I try to put better gifs. I you look closely, there is a slight difference.

**Comment by 1uk** [comment]
> So it's the same in demo viewer?

Yes, in demo viewer the bullets have random timing.

**Comment by C0D3D3V** [comment]
I do not understand, why you closed this issue? 

And also did you test if this bug also happen if you use `/showall` in your demo?

**Comment by luk51** [comment]
idk, they are open but not work in progress. im not fixing it, and dont prompt anyone to fix it so feel free to open it again if you have permissions to do so.
but i dont want to be author / asignee / owner.
i dont care about this issue.
