### ISSUE TITLE
drmingw creates directory on D:/

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4877]
![Screenshot 2022-03-23 at 15 47 17](https://user-images.githubusercontent.com/2335377/159726754-37f6052a-a62a-4252-997e-9b80052ef538.png)
@Jupeyy is this expected?

**Comment by Jupeyy** [comment]
I dunno, i havent written that tool xD

**Comment by Jupeyy** [comment]
Can you ask him what the content is

**Comment by Jupeyy** [comment]
Maybe bcs of the locale?
Guess we can look if the path is pure ascii and only enable it then

**Comment by def-** [comment]
I did (before posting this), waiting for response.

**Comment by Chairn** [comment]
grep '\bD:' matches in drmingw libs

**Comment by sjrc6** [comment]
I also have this folder in D drive

**Comment by Jupeyy** [comment]
So what is in. Then it might be ez to find the code path

**Comment by sjrc6** [comment]
[a.zip](https://github.com/ddnet/ddnet/files/8336930/a.zip)

**Comment by Jupeyy** [comment]
updated drmingw files https://github.com/Jupeyy/drmingw/actions/runs/2032792037

Seems like code coverage was still enabled, sorry for that
