### ISSUE TITLE
texts in editor also scaled

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4879]
![unknown](https://user-images.githubusercontent.com/2335377/159799435-059d3f96-0de8-4af2-981f-0d18e5955ac3.png)
Reported by T tee on Discord

@Jupeyy I guess related to your change.

**Comment by Jupeyy** [comment]
How to reproduce this?

for me it uses the full width available

![image](https://user-images.githubusercontent.com/6654924/159853131-a3ddc7a6-fa6e-4c01-8811-bbfc9d2eb5ed.png)

(checked and in ddnet 15.9.1 it looks identical)

editor manually adjusted the fontsize too

https://github.com/ddnet/ddnet/blob/f67f4eef696eff076e9767e58c975a54e7383388/src/game/editor/editor.cpp#L4005-L4008

**Comment by def-** [comment]
Weird, I also can't reproduce.
