### ISSUE TITLE
Layer mixing feature

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#488]
Goal of this feature - mix few tile layers into one.
As I see way to do : make mixer group -> put few or more layers into -> press button =>
all tiles pushed to first layer. If succesful moved all tiles of layer = delete layer, else keep layer and conflict layers on it.

**Comment by def-** [comment]
Current way is good enough I believe and this is something that's rarely needed: Make brush on layer 1, select layer 2, insert brush.
