### ISSUE TITLE
Graphics mode hotswapping inconsistencies

### ISSUE THREAD

**Issue by Learath2** [ddnet/ddnet#4886]
Starting the game in "Fullscreen" or "Desktop fullscreen" and switching to "Windowed" will result in a window with no decorations, no border.

Starting the game in "Windowed borderless" and switching to "Windowed" will give borders but the new title will lack the icon for the client.
![image](https://user-images.githubusercontent.com/490500/159917582-aae9e654-6332-4c4e-b458-8a655922fee7.png)
vs
![image](https://user-images.githubusercontent.com/490500/159917660-acb73e5f-cc4c-4bd0-9ddb-585397b96cde.png)

This is on rc1

**Comment by Learath2** [comment]
@Jupeyy ^^

**Comment by Jupeyy** [comment]
> Starting the game in "Fullscreen" or "Desktop fullscreen" and switching to "Windowed" will result in a window with no decorations, no border.

its there for me, just not visible bcs windows doesnt move the window, press META + KEY_UP and it should be there


The icon is indeed not there, i'd say that's something SDL has to fix, if they don't explicitly state that icons will not load, or not?

**Comment by Learath2** [comment]
True, I didn't see a border below either so I just assumed the top one was missing too, silly of me, forgot win10 doesn't have much of a border other than the top.

The icon does smell like an sdl issue to me aswell

**Comment by Jupeyy** [comment]
Lets close it for now, maybe SDL improves this in 2 million years
