### ISSUE TITLE
add new components to gameclient

### ISSUE THREAD

**Issue by kbbytes** [ddnet/ddnet#4887]
Hello,
I'm getting an error while I going to add new file to client/components folder so I added my file and also add that to gameclient.h but i'm getting error like blow,
my code line: 
CDropweapon m_DropWeapon;
my errors:
object of abstract class type "CDropweapon" is not allowed
pure virtual function "CComponent::Sizeof" has no overrider

**Comment by kbbytes** [comment]
thank you <3

**Comment by Jupeyy** [comment]
np
