### ISSUE TITLE
Cloning groups/layers feature

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#489]
Could make life of mappers easily. With this feature you could just clone layer instead of full map to do backup or any other cool things =)

**Comment by def-** [comment]
I don't understand. Why would you want to clone a layer?

**Comment by BannZay** [comment]
partial backup instead of full map copying before fatal changing (nobody want 99 copy of one map in folder). 
This way you can clone layer - make changing - easy compare it - decide about backup.
I`m not fun of this feature but on my thoughts it could be helpful

**Comment by def-** [comment]
Hm, I see no problem with having 99 copies of one map. When mapping I would always save map with new file name, counting up. Then you can always check the changes.
