### ISSUE TITLE
Firefox overlay stays on

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet#4892]
Not sure if we can do anything about this.

![Screenshot_2022-03-24_19-45-09](https://user-images.githubusercontent.com/10178629/159990109-5613163a-43aa-4ea7-a5af-3670668f67df.png)

**Comment by def-** [comment]
Sounds like a Firefox problem, not DDNet problem.

**Comment by Chairn** [comment]
Yeah, i don't think there's anything we can do.
