### ISSUE TITLE
Mouse cursor should be yellow on groups/layers buttons

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#490]
Using logic it should be yellow? Right? =D

**Comment by Soreu** [comment]
It is yellow on group's and layer's buttons (the ones to toggle visibility & saving), though changes to red when hovering over group's or layer's name...

Anyway, could someone explain why is it like so? ._.

**Comment by def-** [comment]
I'm not sure. For my taste the mouse color should not change at all. The text is probably just not set as `ms_pUiGotContext` and so this ends up being false: https://github.com/ddnet/ddnet/blob/master/src/game/editor/editor.cpp#L5210

**Comment by BannZay** [comment]
After 50+ hours working in editor I finally found that cursor is changing it collor. On my thoughts changing mouse color unnecesary
