### ISSUE TITLE
Two ranks with same name in /top5

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4903]
@srdante Do you want to take a look? Apparently caused by https://github.com/ddnet/ddnet/pull/4849

As reported by I.K.U. on Discord

![unknown](https://user-images.githubusercontent.com/2335377/160294981-54828bc6-c2da-44fc-87dc-f18b6cd0fbe7.png)

**Comment by srdante** [comment]
I'll be checking more later today.

Map: Old Style

![image](https://user-images.githubusercontent.com/35383529/160297954-5d5b258e-d83a-4cd9-b775-7d99fba2b862.png)

![image](https://user-images.githubusercontent.com/35383529/160297957-ba92f00b-7ebd-4860-be28-6b669d102da3.png)

**Comment by srdante** [comment]
It's currently happening when the same player has tops on different servers. 

This happened with the addition of the server in the group by. 

But taking a look at the logic of why the server column is used (for  the `HasLocal` variable value). I will need to change the query logic, I think the "group by" is not applicable there, maybe we have to use "distinct".

**Comment by srdante** [comment]
Although this is the only function that gives an incorrect result (because of the server column that needs to be obtained), the following functions also need to be changed for a more correct approach: `ShowRank, ShowTeamRank, ShowTop, ShowTeamTop5`.

**Comment by def-** [comment]
Would be cool to also add a test case for this in our unit tests
