### ISSUE TITLE
unnecessary hookline change revert? 

### ISSUE THREAD

**Issue by sjrc6** [ddnet/ddnet#4926]
The player hookline that is rendered in the https://github.com/ddnet/ddnet/pull/4921 bug report video is not from the local player, I don't see how this change could possibly have caused this bug. 

I did a test and from what I can tell calculating the local hookline from the mouse position is identical to the old way except that it updates quicker. 

https://user-images.githubusercontent.com/22122579/160928974-75d80554-4c7a-4085-9644-b6ee17f94ecb.mp4

**Comment by Chairn** [comment]
I think i already had this bug long ago, so it might not be linked to this.

**Comment by def-** [comment]
Damn. Another idea would be that this happens because you move to a very far location in map. I tried reproducing it but couldn't, so I guess I'll revert the revert. Thanks for checking.

**Comment by sjrc6** [comment]
But am I wrong in thinking that the the bug from the video is unrelated because it's not a local hookline? I tested it far away on the map as well but this code is not even getting run in that video.

**Comment by def-** [comment]
I didn't realize the video showed another player watching, then it has always been inaccurate, so this was nothing new. Only your own hookline is 100% accurate.
