### ISSUE TITLE
allow changing the alpha of hook collision lines

### ISSUE THREAD

**Issue by l-ouis** [ddnet/ddnet#4928]
If we allow changing the color of them, I don't see why we can't change the alpha value of them.

**Comment by sjrc6** [comment]
This is super easy to implement so I went ahead and did it, https://github.com/sjrc6/TaterClient-ddnet/commit/3a197aa3dae24e9a411aeb4ca36dd0a2bef6e6be. If others think it's a good idea I can make a PR.

**Comment by def-** [comment]
Sure.

**Comment by Jupeyy** [comment]
#4930
