### ISSUE TITLE
Only send timeout code to official ddnet servers

### ISSUE THREAD

**Issue by timakro** [ddnet/ddnet#493]
At the moment the timeout code is sent to every server with the gametype DDraceNetwork. I suggest sending it only to official servers from ddnet-servers.json.

**Comment by def-** [comment]
Then you couldn't use timeout protection on other servers.

**Comment by timakro** [comment]
If there are other servers using the timeout protection there should be an option to allow it for specific servers.

**Comment by def-** [comment]
Yes, those specific servers with gametype DDraceNetwork.

**Comment by def-** [comment]
For completeness sake: A proper solution would be to have a public+private key. The server gets sent the public key of a player. When that player claims to have reconnected the server send a text to the client, which the client has to sign using its private key and send back. Then the server can use the public key to verify. I don't think anyone is looking to implement this.
