### ISSUE TITLE
Detect failed vulkan startup

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4936]
@Jupeyy Would it be possible to detect a failed vulkan startup and try next time with opengl again? We saw a few reports of people setting vulkan and being unable to restart client again.

One hacky solution: Write out the config with opengl enabled before starting vulkan, then overwrite it with vulkan enabled after that succeeded.

**Comment by murpii** [comment]
@def- maybe use steams startup options?

**Comment by def-** [comment]
That's still a manual step, we should automatically detect the problem.

**Comment by Jupeyy** [comment]
from the crash reports of one person it looks like this doesnt even happen at startup but after one or more frames.

Will think about a solution, not so ez in this case

**Comment by Jupeyy** [comment]
When i use 4000 skins i get a device lost too

My first guess is that the window is not responding for too long which causes the OS to trigger a timeout

https://docs.microsoft.com/de-de/windows-hardware/drivers/display/timeout-detection-and-recovery


I'll investigate a bit.

I'd prefer to fix it that way if thats the reason

**Comment by def-** [comment]
Definitely, my assumption was just "broken drivers" again.

**Comment by Jupeyy** [comment]
So apparently FSAA causes this, nouaa and me on discord found out
