### ISSUE TITLE
Can't /tp to tiles on the edge of maps

### ISSUE THREAD

**Issue by sjrc6** [ddnet/ddnet#4953]
The center of the free camera doesn't reach the outside most ~8 tiles. 

(In the picture I can't reach the top) 
![image](https://user-images.githubusercontent.com/22122579/161670763-6e6387ec-e18b-4f68-a555-affc7fca83a2.png)

**Comment by C0D3D3V** [comment]
Are probably rather exactly 6.25 blocks. Until now, the Freecam was limited by 200 units, there is actually no reason for it. I'll make a fix.
