### ISSUE TITLE
Spec broken on jao shooter when zooming

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#4956]
4619e825f3907772fac625b7398355fba1324066 is the first bad commit
commit 4619e825f3907772fac625b7398355fba1324066
Author: c0d3d3v

Steps to reproduce:
- Spec someone in jao shooter
- zoom out far
- zoom in again
- zoom not working anymore & trying to spec someone else doesn't work

@C0D3D3V

**Comment by C0D3D3V** [comment]
I can reproduce it, but I don't have to zoom back in to do so. It is enough to zoom out so that the prediction time is negative. 

I mean it is already a problem on the map that /showall does not work.

**Comment by C0D3D3V** [comment]
@Jupeyy could you test my fix, and the close the issue?

**Comment by Jupeyy** [comment]
Thanks
