### ISSUE TITLE
editor - layer coloring resets when re-entering UI

### ISSUE THREAD

**Issue by WaRNe0nx3** [ddnet/ddnet#4962]
Layer coloring resets when re-entering UI, it should stay at the old color for fine adjusting the colors while mapping. I think this didn't happen in earlier versions iirc. 
Happens in 16.0.2 and 16.0.3

![ddnet_bug1](https://user-images.githubusercontent.com/46048422/162515702-604750b8-3efe-4f86-ba97-8ddc3d557be6.gif)

**Comment by Jupeyy** [comment]
this was fixed in #4952

just use the nightly version for now
https://ddnet.tw/news/nightly-build-revived/

Thanks for the report tho
