### ISSUE TITLE
Wrong calculation of m_Angle in CCharacterCore

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#4969]
I have a funny bug for you today, which is already for more than 11 years in the code and certainly already noticed by a few. Spoiler in 0.7 it is already fixed. I would suggest we also fix it
It is about this function
our angle: https://github.com/C0D3D3V/ddnet/blob/dbd9c40893a18dccb7f70f0e2bb77c4384877973/src/game/gamecore.cpp#L143-L152
0.7 angle: https://github.com/teeworlds/teeworlds/blob/81c95de3f14b9df1947bf67347784730aba7bed1/src/game/gamecore.cpp#L103

result of the calculation using our function and the new form 0.7: (first column are coordinates)
```
          our       new
0|1:      201       402
1|1:      201       201
1|0:      0         0
1|-1:     -201      -201
0|-1:     -201      -402
-1|-1:    1005      -603
-1|0:     804       804
-1|1:     603       603
```

Since the angle is only used for client side display and not for physics
This is a visual bug 😄 You can see it in the following video

 Left is the player, Right is the view of a other player
https://user-images.githubusercontent.com/14315968/162616126-3fe48abc-2c9e-453c-b6cf-a95da70c755a.mp4

**Comment by fokkonaut** [comment]
https://github.com/ddnet/ddnet/issues/4138
