### ISSUE TITLE
[RFC] Automapper for gamelayer

### ISSUE THREAD

**Issue by H-M-H** [ddnet/ddnet#498]
> Make an automapper for gamelayer.

Requested by Im 'corneum.

Ok, the question is do we need this and if so, how should it work ?

**Comment by timakro** [comment]
I don't see the purpose of this. In my opinion you are creating the gamelayers and then applying a design. I think normal automappers should have the ability to see how the gamelayers look to be able to build a design for them. In my opinion also the "auto game tiles placers" are working in the wrong direction.
