### ISSUE TITLE
Generated files are out of sync with generating scripts

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#5017]
Should probably be tested in CI.

scripts/generate_unicode_confusables_data.py
scripts/generate_unicode_tolower.py

CC @Chairn 
CC #4854

**Comment by Chairn** [comment]
Looks like i miss a file names `UnicodeData.txt` to test my changes

**Comment by Chairn** [comment]
Is it fine if i move them to generated folder? But in that case i need to include `UnicodeData.txt` and `confusables.txt` to the git as well.

**Comment by def-** [comment]
Yes, would make sense I think.

**Comment by Chairn** [comment]
`UnicodeData.txt` is 1.8MB and `confusables.txt` is 700kB

**Comment by def-** [comment]
Hm, we could store them xz-9e-compressed and decompress them on-the-fly, but adds one dependency.

**Comment by def-** [comment]
```
-rw-r--r-- 1 deen deen  81K Jun  8  2015 confusables.txt.xz
-rw-r--r-- 1 deen deen 169K Jul  6  2021 UnicodeData.txt.xz
```

**Comment by heinrich5991** [comment]
Since we only regenerate them irregularly, I'd say it makes sense to not generate them every build and keep the generated files in source control.
