### ISSUE TITLE
Can't launch the game after enabling Vulkan renderer.

### ISSUE THREAD

**Issue by Obydux** [ddnet/ddnet#5020]
[2022-04-25 18:13:57][client]: starting...
[2022-04-25 18:13:57][sdl]: SDL version 2.0.16 (compiled = 2.0.16)
[2022-04-25 18:13:57][gfx]: Created Vulkan 1.0 context.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
[2022-04-25 18:13:58][assert]: /run/build/ddnet/src/engine/client/backend/vulkan/backend_vulkan.cpp(7077): Either use 1 main thread or at least 2 extra rendering threads.

I get this before the game closes by itself after trying to run it. Happens both on Steam and Flatpak versions. I use Arch Linux and have an Radeon integrated GPU and use the amdgpu Mesa driver. `vkcube` and `vulkaninfo` works on my system and tell that my system supports Vulkan 1.3.208.

**Comment by def-** [comment]
Have you changed the value of `gfx_render_thread_count` in settings_ddnet.cfg?

**Comment by Jupeyy** [comment]
i guess hardware_concurrency returned 2 xd let me fix the clamp

**Comment by Obydux** [comment]
> Have you changed the value of `gfx_render_thread_count` in settings_ddnet.cfg?

No i didn't change anything there

**Comment by Jupeyy** [comment]
> > Have you changed the value of `gfx_render_thread_count` in settings_ddnet.cfg?
> 
> No i didn't change anything there

your CPU only has 2 cores and no hyperthreading tho, right?

**Comment by Obydux** [comment]
> ok then #5021 will fix it
> 
> for now go into ~/.teeworlds and add `gfx_render_thread_count 1` in settings_ddnet.cfg
> 
> or start ddnet from terminal with `./DDNet "gfx_render_thread_count 1"`

Thank you, this fixed it
