### ISSUE TITLE
`bind ctrl+shift+0 r[command]` cannot work.

### ISSUE THREAD

**Issue by CAESIUS-TIM** [ddnet/ddnet#5028]
`bind ctrl+shift+0 r[command]` cannot work.

**Comment by heinrich5991** [comment]
What are you trying? What do you expect to happen? What happens instead? Why can't it work?

**Comment by CAESIUS-TIM** [comment]
`bind ctrl+shift+1 "say ctrl+shift+1"`, and it can work.
`bind ctrl+shift+0 "say ctrl+shift+0"`, but it can't work.

**Comment by CAESIUS-TIM** [comment]
### keyboard_test.cfg

```
bind ctrl+1 "say 1"
bind ctrl+2 "say 2"
bind ctrl+3 "say 3"
bind ctrl+4 "say 4"
bind ctrl+5 "say 5"
bind ctrl+6 "say 6"
bind ctrl+7 "say 7"
bind ctrl+8 "say 8"
bind ctrl+9 "say 9"
bind ctrl+0 "say 0"

bind ctrl+shift+1 "say !"
bind ctrl+shift+2 "say @"
bind ctrl+shift+3 "say \"#\""
bind ctrl+shift+4 "say $"
bind ctrl+shift+5 "say %"
bind ctrl+shift+6 "say ^"
bind ctrl+shift+7 "say &"
bind ctrl+shift+8 "say *"
bind ctrl+shift+9 "say ("
bind ctrl+shift+0 "say )"

bind ctrl+q "say q"
bind ctrl+w "say w"
bind ctrl+e "say e"
bind ctrl+r "say r"
bind ctrl+t "say t"
bind ctrl+y "say y"
bind ctrl+u "say u"
bind ctrl+i "say i"
bind ctrl+o "say o"
bind ctrl+p "say p"
bind ctrl+a "say a"
bind ctrl+s "say s"
bind ctrl+d "say d"
bind ctrl+f "say f"
bind ctrl+g "say g"
bind ctrl+h "say h"
bind ctrl+j "say j"
bind ctrl+k "say k"
bind ctrl+l "say l"
bind ctrl+z "say z"
bind ctrl+x "say x"
bind ctrl+c "say c"
bind ctrl+v "say v"
bind ctrl+b "say b"
bind ctrl+n "say n"
bind ctrl+m "say m"

bind ctrl+shift+q "say Q"
bind ctrl+shift+w "say W"
bind ctrl+shift+e "say E"
bind ctrl+shift+r "say R"
bind ctrl+shift+t "say T"
bind ctrl+shift+y "say Y"
bind ctrl+shift+u "say U"
bind ctrl+shift+i "say I"
bind ctrl+shift+o "say O"
bind ctrl+shift+p "say P"
bind ctrl+shift+a "say A"
bind ctrl+shift+s "say S"
bind ctrl+shift+d "say D"
bind ctrl+shift+f "say F"
bind ctrl+shift+g "say G"
bind ctrl+shift+h "say H"
bind ctrl+shift+j "say J"
bind ctrl+shift+k "say K"
bind ctrl+shift+l "say L"
bind ctrl+shift+z "say Z"
bind ctrl+shift+x "say X"
bind ctrl+shift+c "say C"
bind ctrl+shift+v "say V"
bind ctrl+shift+b "say B"
bind ctrl+shift+n "say N"
bind ctrl+shift+m "say M"

bind ctrl+minus "say -"
bind ctrl+shift+minus "say _"
bind ctrl+equals "say ="
bind ctrl+shift+equals "say +"
bind ctrl+leftbracket "say ["
bind ctrl+shift+leftbracket "say {"
bind ctrl+rightbracket "say ]"
bind ctrl+shift+rightbracket "say }"
bind ctrl+backslash "say \\"
bind ctrl+shift+backslash "say |"
bind ctrl+semicolon "say \";\""
bind ctrl+shift+semicolon "say :"
bind ctrl+apostrophe "say '"
bind ctrl+shift+apostrophe "say \"\\\"\""
bind ctrl+grave "say `"
bind ctrl+shift+grave "say ~"
bind ctrl+comma "say ,"
bind ctrl+shift+comma "say <"
bind ctrl+period "say ."
bind ctrl+shift+period "say >"
bind ctrl+slash "say \" /\""
bind ctrl+shift+slash "say ?"
```

**Comment by CAESIUS-TIM** [comment]
### keyboard_test.cfg

bind ctrl+1 "say 1"
bind ctrl+2 "say 2"
bind ctrl+3 "say 3"
bind ctrl+4 "say 4"
bind ctrl+5 "say 5"
bind ctrl+6 "say 6"
bind ctrl+7 "say 7"
bind ctrl+8 "say 8"
bind ctrl+9 "say 9"
bind ctrl+0 "say 0"

bind ctrl+shift+1 "say !"
bind ctrl+shift+2 "say @"
bind ctrl+shift+3 "say \"#\""
bind ctrl+shift+4 "say $"
bind ctrl+shift+5 "say %"
bind ctrl+shift+6 "say ^"
bind ctrl+shift+7 "say &"
bind ctrl+shift+8 "say *"
bind ctrl+shift+9 "say ("
bind ctrl+shift+0 "say )"

bind ctrl+q "say q"
bind ctrl+w "say w"
bind ctrl+e "say e"
bind ctrl+r "say r"
bind ctrl+t "say t"
bind ctrl+y "say y"
bind ctrl+u "say u"
bind ctrl+i "say i"
bind ctrl+o "say o"
bind ctrl+p "say p"
bind ctrl+a "say a"
bind ctrl+s "say s"
bind ctrl+d "say d"
bind ctrl+f "say f"
bind ctrl+g "say g"
bind ctrl+h "say h"
bind ctrl+j "say j"
bind ctrl+k "say k"
bind ctrl+l "say l"
bind ctrl+z "say z"
bind ctrl+x "say x"
bind ctrl+c "say c"
bind ctrl+v "say v"
bind ctrl+b "say b"
bind ctrl+n "say n"
bind ctrl+m "say m"

bind ctrl+shift+q "say Q"
bind ctrl+shift+w "say W"
bind ctrl+shift+e "say E"
bind ctrl+shift+r "say R"
bind ctrl+shift+t "say T"
bind ctrl+shift+y "say Y"
bind ctrl+shift+u "say U"
bind ctrl+shift+i "say I"
bind ctrl+shift+o "say O"
bind ctrl+shift+p "say P"
bind ctrl+shift+a "say A"
bind ctrl+shift+s "say S"
bind ctrl+shift+d "say D"
bind ctrl+shift+f "say F"
bind ctrl+shift+g "say G"
bind ctrl+shift+h "say H"
bind ctrl+shift+j "say J"
bind ctrl+shift+k "say K"
bind ctrl+shift+l "say L"
bind ctrl+shift+z "say Z"
bind ctrl+shift+x "say X"
bind ctrl+shift+c "say C"
bind ctrl+shift+v "say V"
bind ctrl+shift+b "say B"
bind ctrl+shift+n "say N"
bind ctrl+shift+m "say M"

bind ctrl+minus "say -"
bind ctrl+shift+minus "say _"
bind ctrl+equals "say ="
bind ctrl+shift+equals "say +"
bind ctrl+leftbracket "say ["
bind ctrl+shift+leftbracket "say {"
bind ctrl+rightbracket "say ]"
bind ctrl+shift+rightbracket "say }"
bind ctrl+backslash "say \"
bind ctrl+shift+backslash "say |"
bind ctrl+semicolon "say \";\""
bind ctrl+shift+semicolon "say :"
bind ctrl+apostrophe "say '"
bind ctrl+shift+apostrophe "say \"\\\"\""
bind ctrl+grave "say `"
bind ctrl+shift+grave "say ~"
bind ctrl+comma "say ,"
bind ctrl+shift+comma "say <"
bind ctrl+period "say ."
bind ctrl+shift+period "say >"
# without space, "/" would be recognized as a chat command
bind ctrl+slash "say \" /\"" 
bind ctrl+shift+slash "say ?"

**Comment by C0D3D3V** [comment]
try `bind shift+ctrl+0 "say lol"`
this worked for me

**Comment by C0D3D3V** [comment]
`bind ctrl+shift+0 "say )"` works too

**Comment by C0D3D3V** [comment]
what keyboard layout do you use? What input locales do you have set?

**Comment by C0D3D3V** [comment]
maybe you have set a global bind in your operation system for ctrl+shift+0, so that you OS stops sending these keys to ddnet

**Comment by CAESIUS-TIM** [comment]
> maybe you have set a global bind in your operation system for ctrl+shift+0, so that you OS stops sending these keys to ddnet

my ubuntu can but win10 can't. that's possibly true but I can't find out.

**Comment by C0D3D3V** [comment]
try this https://groups.google.com/g/leo-editor/c/XqAQ48gE40Y
I think you can close this issue as it depends on the operating system and is more or less a desired behavior.
