### ISSUE TITLE
Specific weapon removal shields not shown in vanilla

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#5039]
https://github.com/ddnet/ddnet/pull/4728#issuecomment-1112860690

I forgot the vanilla compatibility of this feature.

The thread already has a small discussion about it. Perhaps we could simply show a normal shield as @Zoozti proposed?
>I think its the best way to just show vanilla/old client players a normal shield. So they see they will lose weapons and dont get surprised by an invisible tile

CC @C0D3D3V @def- @edg-l @fokkonaut @Zoozti

**Comment by fokkonaut** [comment]
As I proposed, but yes. Just send a normal shield and not a specific one, then add an entity ex which holds the info. Why do we have entityEx, if we dont use it for what its made for?

**Comment by Zoozti** [comment]
Would it even show the different graphics then. 
DDNet is already unplayable with vanilla client. We should stop restricting our game for a literally not existing group of players.
Vanilla dropped compatibility with us btw, not the other way around. So we should continue and not still try to keep them

**Comment by fokkonaut** [comment]
> Would it even show the different graphics then. DDNet is already unplayable with vanilla client. We should stop restricting our game for a literally not existing group of players. Vanilla dropped compatibility with us btw, not the other way around. So we should continue and not still try to keep them

If you code it like that, of course, lol.
Vanilla should imo never be dropped.

**Comment by heinrich5991** [comment]
Please move the "should we keep vanilla support?" question to #5041. Assume we want to for this issue.

**Comment by fokkonaut** [comment]
> Vanilla dropped compatibility with us btw, not the other way around. So we should continue and not still try to keep them

The message of this sentence is completely wrong, because vanilla 0.7 is a thing which is being planned for a long time already, it was clear that there will be major version changes.

**Comment by Chairn** [comment]
Isn't it possible to show a shield and the weapon behind it? I.e. send both entity to the client.

**Comment by heinrich5991** [comment]
> Isn't it possible to show a shield and the weapon behind it? I.e. send both entity to the client.

Heh, nice idea. :)

**Comment by heinrich5991** [comment]
This also affects DDNet clients not on the newest version.

**Comment by C0D3D3V** [comment]
Could we maybe introduce a warning, "Your client is to old for this map, this map contains Feature/Elements.. that are only availibe since version x. If you want to play on this map without problems, then upgrade...". And for Vanilla clients something similar, that advertices the ddnet client.

**Comment by C0D3D3V** [comment]
But for this feature in particular we can just send the default shield.
