### ISSUE TITLE
Allow choosing of tileset used with cl_overlay_entities

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#505]
I play with entities on a lot because map makers sometimes make the tiles too difficult to differentiate, but the tiles used when entities are on are kinda ugly. It would be nice if I could "steal" tiles from any other [downloaded] map when entities are on.

(Originally I was thinking that you should be able to override the tileset when entities are off, but I think overriding the entity tiles themselves makes more sense (so you can still toggle with ease)).

**Comment by Ekidoxx** [comment]
I would be really glad if you would share with us (e.g. in [this forum thread](https://forum.ddnet.tw/viewtopic.php?f=93&t=398&start=50)) what exactly you don't like in the current entities, so that maybe they could be improved (even though I'm aware not everyone will always like them)

**Comment by timakro** [comment]
The entities clear tileset maps a graphic to each game tile. Normal tilesets used in maps don't do that, so it isn't possible to display them automatically based on the game tiles.

**Comment by d3faultdotxbe** [comment]
This was meant to be an enhancement, please reopen and tag appropriately.

@timakro I kinda get what you mean about it not being "possible", but I disagree: foreach game tile type, use the visual tile most frequently used with that game tile through the entire map (simply count). And really I'm just talking about the most common game tiles (the ground, freeze, deep, etc)... the more rare game tiles (jetpack, endless, etc) should stay exactly how they are.

@Ekidoxx There's nothing wrong with them in the usability sense, they just look oldschool and I prefer the ddmax/etc colorful tiles. I also want to be able to periodically change them in the options.

**Comment by timakro** [comment]
> foreach game tile type, use the visual tile most frequently used with that game tile throughout the entire map (simply count). And really I'm just talking about the most common game tiles (the ground, freeze, deep, etc)... the more rare game tiles (jetpack, endless, etc) should stay exactly how they are.

Sounds like it would result in a ton of code and wouldn't work as expected sometimes but it at least is a solution that could work.
