### ISSUE TITLE
Fails building with bam 0.5.x

### ISSUE THREAD

**Issue by josephgbr** [ddnet/ddnet#506]
When building DDNet with bam 0.5.0, the following error message is displayed and building won't continue:

> $ bam  -t -t release
[string "src/base.lua"]:38: this file for version 0.4.x of bam. you are running 0.5.x.
backtrace:
  [string "src/base.lua"](38): CheckVersion global
  bam.lua(1): (null) 
bam: script error (-t for more detail)

Environment: Arch Linux 64-bit, [bam 0.5.0-1](https://www.archlinux.org/packages/community/x86_64/bam/), [lua 5.3.3-1](https://www.archlinux.org/packages/extra/x86_64/lua/), AUR package: [teeworlds-ddnet](https://aur.archlinux.org/packages/teeworlds-ddnet) (I'm the maintainer of this package)

**Comment by FallenKN** [comment]
fist line in bam.lua -> CheckVersion("0.4")
May you notice that the bam.lua is currently still for 0.4

**Comment by heinrich5991** [comment]
@FallenKN Yes, but it should probably be updated.

**Comment by josephgbr** [comment]
@heinrich5991 thanks for cherry-picking the solution. Off-topic: Did you notice that bam requests adding `-t` flag when I already added it? Do you know to whom should this be reported?

**Comment by heinrich5991** [comment]
That would be https://github.com/matricks/bam/issues/new.

**Comment by josephgbr** [comment]
@heinrich5991 filed a bug request. thanks.

**Comment by heinrich5991** [comment]
Fixed by #522.
