### ISSUE TITLE
(feature request) +release for binding actions on key releases

### ISSUE THREAD

**Issue by cookstown** [ddnet/ddnet#5071]
Hi,
I am new to dummy playing, I don't know a lot about bindings, especially about sophisticated bindings.
However this is a binding I use:
```
# on
bind mouse1 "+fire; +toggle cl_dummy_copy_moves 1 0"
# off
bind mouse1 +fire
```
This makes the dummy copy my moves when I fire. And keeps them afterwards. Like this:
*"firecopy" gif*
![firecopy_walk demo](https://user-images.githubusercontent.com/4086396/167149533-ae1c2f33-8f9b-4e7f-acb7-3a6bcf1365b9.gif)

It can be useful for throwing: (I don't know how it is done by pros, maybe there is a simpler way and I am making it complicated)
*throw gif with stopping*
![firecopy_throw demo](https://user-images.githubusercontent.com/4086396/167149886-eb9fffbd-108f-4ab5-87bc-6db79ec0a004.gif)

Now what I do is as you see in the gif, I fire again to stop the dummy. There is also `dummy_reset` that could be used to do that.
And that's exactly what I want to use for the suggested feature "+release".
I would bind *mouse1* to *"+release dummy_reset"*. Which would reset the dummy, when I release the mouse button.

Just an idea.
Maybe I could even implement it myself. Would it then be legit to use it?

Thanks for reading.

The final result could then be like this:
*firecopy reset gif*
![firecopy_reset demo](https://user-images.githubusercontent.com/4086396/167149971-84c845eb-72dd-40f2-aeb3-3785143d99a2.gif)

**Comment by heinrich5991** [comment]
I'm generally against adding more dummy capabilities or input capabilities. These usually have unintended consequences that result in new input features we cannot drop anymore.

**Comment by cookstown** [comment]
You're probably right.
