### ISSUE TITLE
Mousewheel up and down each  trigger randomly one of two keys

### ISSUE THREAD

**Issue by timakro** [ddnet/ddnet#508]
I finally figured out why my mousewheel wasn't working for 50% of the scrolling. Mousewheel up triggers randomly either the key `mouse4` or `mousewheelup`. Similarly mousewheel down triggers sometimes `mouse5` and sometimes `mousewheeldown`. By default only one key for up and one key for down is bound. A workaround is to bind both keys for up and down to `+prevweapon` and `+nextweapon`.

**Comment by Henningstone** [comment]
May I ask on which operating system you are on? I had similar problems on Ubuntu 15.10 after the port to SDL has been done, and I fixed it by installing libsdl 2.0.4 from source, since Canonical's repos did only give me 2.0.2 (which is somehow buggy...)

**Comment by timakro** [comment]
I'm on debian using libsdl2-2.0.0, it's very likely to be the SDL version.

**Comment by FallenKN** [comment]
May this can help #492
