### ISSUE TITLE
Translation For Server and Cilent

### ISSUE THREAD

**Issue by Ninecloud2077** [ddnet/ddnet#5081]
I want to translate a more language for DDNet Cilent
But I don't know what should I do
Then I want to translate for Server
But I can't find any json file
So how to translate for ddnet?
thx

**Comment by Jupeyy** [comment]
Hi, Client side translations are stored in text files in `data/languages`

For server side translations see discussions such as #3091

It's currently not implemented tho

**Comment by def-** [comment]
What language? You'll need to add an entry in data/languages/index.txt, then create a new corresponding file in data/languages

**Comment by Ninecloud2077** [comment]
ok thanks
