### ISSUE TITLE
Mouse selection has wrong position when there is a grey bar at top

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5082]
![screenshot-20220509@000315](https://user-images.githubusercontent.com/2335377/167317596-5d6e81b9-0a42-4cee-af1b-7210246bed26.png)
@Jupeyy

**Comment by Jupeyy** [comment]
SDL 2.0.22 or what? ^^

**Comment by def-** [comment]
Yes

**Comment by Jupeyy** [comment]
Yeah I guess you know what issue this relates to then ^^ 
The issue I opened on SDL that wasn't fixed

**Comment by heinrich5991** [comment]
Presumably https://github.com/libsdl-org/SDL/issues/5572?
