### ISSUE TITLE
Use libevent for HTTP callbacks?

### ISSUE THREAD

**Issue by edg-l** [ddnet/ddnet#5083]
With the new masterserver using HTTP, thus increasing our HTTP usage I think we could take advantage of this library (and i think @Learath2  mentioned it)

https://libevent.org/

> The libevent API provides a mechanism to execute a callback function when a specific event occurs on a file descriptor or after a timeout has been reached. Furthermore, libevent also support callbacks due to signals or regular timeouts.

> libevent is meant to replace the event loop found in event driven network servers. An application just needs to call event_dispatch() and then add or remove events dynamically without having to change the event loop.

> Libevent additionally provides a sophisticated framework for buffered network IO, with support for sockets, filters, rate-limiting, SSL, zero-copy file transmission, and IOCP. Libevent includes support for several useful protocols, including DNS, HTTP, and a minimal RPC framework.

We could also maybe think about adding some basic RPC support so instead of fifo we have an advanced way to control and monitor the server (+ windows support?) ?

**Comment by heinrich5991** [comment]
What feature or thing do you want to accomplish with libevent? Adding a RPC server?
