### ISSUE TITLE
:bug: Vulkan sometimes renders clipped quads

### ISSUE THREAD

**Issue by AssassinTee** [ddnet/ddnet#5094]
## Bug

I have multiple clipped quad regions and one quad is always rendered in the wrong region. This only happens ingame and with Vulkan

Ingame (Vulkan):
One blue stars appears between all red stars

![screenshot_2022-05-13_15-41-52](https://user-images.githubusercontent.com/821401/168302934-4cf86c6c-1733-43dd-9e0b-15ff93a85c73.png)

Editor(Vulkan):
No blue star

![screenshot_2022-05-13_15-41-39](https://user-images.githubusercontent.com/821401/168303057-85fc28d6-dc0c-4cfe-8cf1-1b203c082365.png)

Ingame( OpenGL 3.0.0):
No blue star

![screenshot_2022-05-13_15-51-23](https://user-images.githubusercontent.com/821401/168303097-6ae5c422-be0e-4cb3-a9f3-a1ddaa94a47b.png)

Map:

[run_space_time.zip](https://github.com/ddnet/ddnet/files/8688529/run_space_time.zip)

## Reproduce

1. activate Vulkan as rendering engine and restart
2. load this map
3. go to the place on the screenshot
4. See the blue star
5. Repeat 1-4 with OpenGL
6. See no blue star

**Comment by Jupeyy** [comment]
Can you please try a nightly version?

**Comment by AssassinTee** [comment]
@Jupeyy seems to be fixed on nightly:

![screenshot_2022-05-13_19-17-27](https://user-images.githubusercontent.com/821401/168335183-8f971269-8bb6-4320-8b30-968213804968.png)

so this issue can be closed I guess
