### ISSUE TITLE
Can't type into editor inputs when entering the editor using 'cl_editor 1'

### ISSUE THREAD

**Issue by hus3h** [ddnet/ddnet#5095]
- Reproduction: you have to be in a server, in F1 or using a bind execute `cl_editor 1`, try using inputs (_Save As_ for example), doesn't take any keys except _backspace_ and _delete_ (_enter_ to submit also works)
- Applies to all inputs including layer options and server commands
- Entering the editor through the UI icon and using ctrl+shift+e works fine
- Pressing ctrl+shift+e, even if you don't input anything and immediately close the editor, fixes it till client is closed (makes you able to use `cl_editor 1` without problems)

This affects at least version 15.9.1 and up for me (could be present in older versions, didn't check). Tested in 15.9.1 from Fedora DNF repositories and 16.0.3 (compiled). Also tested using a fresh settings file and with both Vulkan and OpenGL.

**Comment by Robyt3** [comment]
I can't reproduce it with current master (344eeaf8aa988bdc030254c7d6e5477bfb646e81), version 16.0 and version 16.0.3 on Windows 10.

**Comment by Robyt3** [comment]
Now I can reproduce it. Seems to happen only with a custom editor bind.

1. Connect to a server.
2. Open local console and `bind e "cl_editor 1"`
3. Close console
4. Press `e`
5. Select the quad layer's name editbox.
6. The editbox cursor is shown but typing in the editbox doesn't work.
