### ISSUE TITLE
ever since v10.x DDNet wont execute for me

### ISSUE THREAD

**Issue by tempcke** [ddnet/ddnet#512]
I have tried clean downloads from the website including 10.2 however anything 10.x when I try to execute it by double clicking the icon nothing seems to happen.  If I execute it from the terminal I get this error:
```
logikos@logikos-main ~/Downloads/DDNet-10.2-linux_x86_64 $ ./DDNet
./DDNet: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
```

if it matters my os is linux mint 17.3

**Comment by def-** [comment]
The requirement changed from SDL1.2 to SDL2.0. On Linux we don't package that, so you have to install it yourself using your distribution's package manager.

**Comment by tempcke** [comment]
So anyone who downloads DDNet for linux and tries to run the DDNet executable by double clicking it (as many users would) there is no feedback to the user whatsoever. the user has no idea why nothing happens and it just appears broken.  Which is what I assumed for several 10.x versions until I had the idea to try to execute it from the CLI.  Perhaps at the very least check for the dependencies and notify the user so they know what they have to do to make it work....

**Comment by def-** [comment]
Yeah, I never understood why desktop environments or distributions don't provide an error message for this. It's not just a problem for DDNet, but for every other software as well.

**Comment by CytraL** [comment]
Perhaps using the new package formats like FlatPack?
