### ISSUE TITLE
Used tele numbers detecion broked

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#513]
Tele popup menu(where you can change tele number in editor) do not get different colors depends on existing teles with this number anymore. Probably cause 3960dc36d87159a9fcec40ef4cbcf6d16d138bdb

**Comment by BannZay** [comment]
Cant reproduce anymore

**Comment by timakro** [comment]
Deen fixed it here af250dd74e362eae93668b23e673906cb6d6742d
