### ISSUE TITLE
Don't enable the GNU Gold Linker by default

### ISSUE THREAD

**Issue by edg-l** [ddnet/ddnet#5136]
![image](https://user-images.githubusercontent.com/15859336/168749660-fc30dc9e-b995-4c2a-97c7-5a080d8c4fc7.png)

It was way better before this was a thing.

**Comment by def-** [comment]
Well, gold is still faster than ld at least.

**Comment by edg-l** [comment]
My system uses `lld` by default, so this auto option essentially makes it worse for no reason.

I think most systems use lld by default anyway
