### ISSUE TITLE
Shields and weapons sometimes move away / don't appear

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5137]
This started yesterday after switching to new server version (@heinrich5991's rebased pr_ddnet_serverbrowse_http_server branch. Update: happens on master too so not related to the branch)
![weirdstuff](https://user-images.githubusercontent.com/2335377/168760246-cbe2feba-d52a-42b2-8c69-2b5789d76406.png)
I'm not sure what change is causing this, I can't reproduce it.

Old change: c5230110
New change: c082a842
Suspicious looking changes: https://github.com/ddnet/ddnet/pull/4959 https://github.com/ddnet/ddnet/pull/5125 https://github.com/ddnet/ddnet/pull/5076

Anyone got an idea or know how to reproduce it reliably?

**Comment by C0D3D3V** [comment]
do they also not work, or are they only not visible?

**Comment by def-** [comment]
They don't work, people are cheating maps, some can't finish. I think the IPO change is responsible, probably some optimization.

**Comment by C0D3D3V** [comment]
If they really move away as if they were on a mover, then draggers and turrets should also move away. This would mean that vec2 m_core is no longer initialized with (0,0) (The motion direction vector of the entities) xD
this is just a guess, I'll test out a little.

**Comment by def-** [comment]
I have disabled IPO and haven't seen this since then. But I could never reproduce it locally, only on server, so might depend on compiler version.

**Comment by def-** [comment]
It is pretty crazy that this bug came from enabling IPO, but seems pretty sure now. Locally I didn't see anything with asan+ubsan. Maybe has to be run with the compiler on Debian 11.

**Comment by C0D3D3V** [comment]
I could not reproduce it either. I tried first to set all bits in the heap to 1, then to free the heap again and only then to create the entities. But for me it does not happen that m_core is not initialized with (0,0). This is probably a compiler bug which is related to IPO. I personally don't think  IPO will give us much of an improvement anyway, I don't see any big advantages.

If you would send me the binary that was created for debian 11 I could debug what the cause could be, but that doesn't really get us anywhere.

**Comment by def-** [comment]
I built this again from c082a8426d1fa66332ac8465ce23e086a4f976e0 (pr_ddnet_serverbrowse_http_server)

**Comment by def-** [comment]
Cellegen got it on Nightly build on Windows:

https://user-images.githubusercontent.com/2335377/169350809-2bdbb774-2479-4f59-afcb-2e260103c4e6.mp4

@C0D3D3V so should be reproducable with mingw windows nightly build at least

**Comment by def-** [comment]
Not getting it on macOS even with 20 reloads

**Comment by C0D3D3V** [comment]
But still with IPO right? 
Interesting is that it does not look like they would move (or they move very fast) they just do not appear at all.

**Comment by def-** [comment]
Yes, we still build the nightly with IPO (since it's default in Release/RelWithDebInfo builds)

**Comment by def-** [comment]
![screenshot-20220521@120927](https://user-images.githubusercontent.com/2335377/169646787-959488f7-8e5d-4f33-9e4a-708ebd5c5a74.png)
Can reproduce on current Arch with IPO RelWithDebInfo build

**Comment by def-** [comment]
They are actually slowly moving away:
```
Clipped: 0 460 1041 -2.03082e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.03741e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.03741e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.03741e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.044e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.044e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.044e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.044e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.0506e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.0506e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.0506e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.05719e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.05719e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.05719e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.05719e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.06379e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.06379e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.06379e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.07038e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
Snap: 2 0x55ae085814f0
Snap: 2 0x55ae08581490
Clipped: 0 460 1041 -2.07038e+32 976
Snap: 2 0x55ae085a8ed0
Clipped: 0 460 1041 inf 944
Snap: 2 0x55ae085c99f0
```

**Comment by def-** [comment]
For some reason m_Pos in CPickup keeps getting modified. I found no code that should do this, the object is constructed with new on heap and not destructed.
