### ISSUE TITLE
Mark all overridden functions with `override`

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#5139]
Gives some better diagnostics in case you fail to override a function due to a typo.

**Comment by edg-l** [comment]
Mysql database code gives not marked override warnings still

**Comment by def-** [comment]
This shows the disadvantage of having a new compiler warning that only works in Clang, but not GCC.

**Comment by heinrich5991** [comment]
My gcc actually supports `-Wsuggest-override`. It just gives a warning for compiling as C. Let me fix our CMakeLists.txt, as we no longer have any pure-C files.

**Comment by def-** [comment]
Ok, then maybe just the older GCC versions we use in CI with mysql backend don't have it.

**Comment by heinrich5991** [comment]
#5147 makes the current situation fail CI. :)

**Comment by Chairn** [comment]
> Ok, then maybe just the older GCC versions we use in CI with mysql backend don't have it.

I have gcc 7.5, and the flag does work. Flag was added in GCC 5.1 from a quick search :)
