### ISSUE TITLE
Crash on alt-tab with OpenGL 3.3 / Vulkan

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5143]
```
[2022-05-17 20:06:28][datafile]: loading done. datafile='downloadedmaps/RedCastle2_de71ee62.map'
[2022-05-17 20:06:28][client]: loaded map 'downloadedmaps/RedCastle2_de71ee62.map'
[2022-05-17 20:06:28][client/network]: loading done
[2022-05-17 20:06:28][textrender]: Found non empty text container with index 992
[2022-05-17 20:06:28][assert]: /home/deen/isos/ddnet/ddnet-source/src/engine/client/text.cpp(1912): text container was not empty
```
Doesn't happen with OpenGL 3.0, reported by Nice on Discord

**Comment by def-** [comment]
Assert came from 27922faea1

**Comment by def-** [comment]
@Kaffeine @Jupeyy any idea?

**Comment by Kaffeine** [comment]
I added the debug message to investigate a similar issue. I think I added debug message to the end of `CreateTextContainer()` to see what text caused the issue (you can match the ContainerIndex).

```diff
diff --git src/engine/client/text.cpp src/engine/client/text.cpp
index ee04811f6..6b62a503d 100644
--- src/engine/client/text.cpp
+++ src/engine/client/text.cpp
@@ -1006,6 +1006,8 @@ public:
     TextContainer.m_LineCount = pCursor->m_LineCount;
     TextContainer.m_GlyphCount = pCursor->m_GlyphCount;
     TextContainer.m_CharCount = pCursor->m_CharCount;
     TextContainer.m_MaxLines = pCursor->m_MaxLines;
     TextContainer.m_StartX = pCursor->m_StartX;
     TextContainer.m_StartY = pCursor->m_StartY;
     TextContainer.m_LineWidth = pCursor->m_LineWidth;
     TextContainer.m_UnscaledFontSize = pCursor->m_FontSize;
 }
+
+dbg_msg("TextRendering", "container_index: %d, text: %s", ContainerIndex, pText);

 return ContainerIndex;
```

In my case it turned out that I forgot to add `TextRender()->DeleteTextContainer()` to `CKillMessages::OnWindowResize()`.

(In my custom client I've added killer assistant to the kill messages)
![image](https://user-images.githubusercontent.com/374839/169035691-4db91a13-ff36-4b0c-bbf4-6949c2b3ae45.png)

**Comment by Jupeyy** [comment]
I really wonder how the text container index is >900

sounds like it creates some stuff every frame

**Comment by Robyt3** [comment]
I can't reproduce it on Windows 10. Is the window redrawn while you resize it? For me the window's contents are not redraw while I resize it, but it appears that the game is still updating, as I don't get disconnected when I keep holding the resize-ribbon.

Manual text containers are used for:
- chat
- killmessages
- score HUD
- FPS
- nameplates
- UI elements (the Connect and Refresh buttons and a lot of label texts everywhere)

I don't think the length helps a lot. It could be any player name in a kill message or the score hud. Or it could be the Connect/Refresh-buttons which are both 7 letters.

If anyone can reproduce it, please narrow it down by selectively disabling above systems with the config options.

**Comment by def-** [comment]
No, that was another repro from Nice. Maybe we need his config or find out what he's doing special :D

**Comment by Desour** [comment]
Idk if it helps you, but I just got this crash with an index < 900 (with OpenGL 3.3):
```
2023-01-20 18:18:21 I textrender: Found non empty text container with index 238 with 5 quads
2023-01-20 18:18:21 I assert: <path>/src/engine/client/text.cpp(1971): text container was not empty
```

**Comment by Jupeyy** [comment]
Yeah thanks. Was it on ddrace or some vanilla mod? I kinda feel like it's probably edge case. So such info might help too ^^

**Comment by Desour** [comment]
It was on a ddnet fng server (iirc it said version ddnet 0.6.3).

**Comment by Robyt3** [comment]
realfail on Discord got this crash with Vulkan when pressing Windows key.

[DDNet_assert_log_10220_2023-02-24_15-42-53.txt](https://github.com/ddnet/ddnet/files/10826564/DDNet_assert_log_10220_2023-02-24_15-42-53.txt):

```
2023-02-24 15:42:53 I textrender: Found non empty text container with index 402 with 7 quads
2023-02-24 15:42:53 I textrender: Found non empty text container with index 620 with 4 quads
2023-02-24 15:42:53 I textrender: Found non empty text container with index 593 with 5 quads
2023-02-24 15:42:53 I assert: /home/deen/isos/ddnet/ddnet-source/src/engine/client/text.cpp(1971): text container was not empty
```

[DDNet_assert_log_44720_2023-02-24_15-48-18.txt](https://github.com/ddnet/ddnet/files/10826565/DDNet_assert_log_44720_2023-02-24_15-48-18.txt):

```
2023-02-24 15:48:18 I textrender: Found non empty text container with index 665 with 5 quads
2023-02-24 15:48:18 I assert: /home/deen/isos/ddnet/ddnet-source/src/engine/client/text.cpp(1971): text container was not empty
```

Graphics config:

```
gfx_screen_width 1920
gfx_screen_height 1080
gfx_screen_refresh_rate 60
gfx_desktop_width 1920
gfx_desktop_height 1080
gfx_refresh_rate 1000
gfx_3d_texture_analysis_ran 1
gfx_3d_texture_analysis_renderer "NVIDIA GeForce RTX 3060/PCIe/SSE2"
gfx_3d_texture_analysis_version "4.6.0 NVIDIA 472.08"
gfx_render_thread_count 3
gfx_backgroundrender 1
gfx_backend Vulkan
```

**Comment by Robyt3** [comment]
Is it possible for the windows resize listener to be called at the same time as another frame is rendered? I can force this crash when I manually call `CChat::OnRender()` at the end of `CChat::OnWindowResize`.

**Comment by Kaffeine** [comment]
I have the same crash in my fork. 

I've added this debug output and the text is always the same as in the last kill message.

```
diff --git src/engine/client/text.cpp src/engine/client/text.cpp
index b1b092537..11e30cb08 100644
--- src/engine/client/text.cpp
+++ src/engine/client/text.cpp
@@ -152,6 +152,8 @@ struct STextContainer
 {
        STextContainer() { Reset(); }
 
+       char aText[20];
+
        CFont *m_pFont;
        int m_FontSize;
        STextString m_StringInfo;
@@ -939,7 +941,9 @@ public:
 
                TextContainerIndex = GetFreeTextContainerIndex();
                STextContainer &TextContainer = GetTextContainer(TextContainerIndex);
                TextContainer.m_pFont = pFont;
+               str_copy(TextContainer.aText, pText);
 
                TextContainer.m_SingleTimeUse = (m_RenderFlags & TEXT_RENDER_FLAG_ONE_TIME_USE) != 0;
 
@@ -1965,6 +1969,7 @@ public:
                        {
                                dbg_msg("textrender", "Found non empty text container with index %d with %d quads", pTextContainer->m_StringInfo.m_QuadBufferContainerIndex, (int)pTextContainer->m_StringInfo.m_QuadNum);
                                HasNonEmptyTextContainer = true; // NOLINT(clang-analyzer-deadcode.DeadStores)
+                               dbg_msg("text", "Container text: %s", pTextContainer->aText);
                        }
                }
```

I had some changes in KillMessages but I've reverted them and still have this crash on Alt+Tab.
For me it happens 2-3 times per hour (and I Alt+Tab maybe 10-20 times per hour). There is a lot of kill messages in the gametype I play so maybe it increases the chance for a crash.

It still maybe a different issue in my code, though I don't see how it could be possible.
For me it did never happen on 16.5 and it breaks my game after I rebased on 16.7. I tried to find the clue but I could not.

Maybe "alt+tab when a kill message added/removed" would give you a clue, or maybe it is a wrong lead.

**Comment by Robyt3** [comment]
Reported by teini94:

```
2023-05-07 04:26:17 I textrender: Found non empty text container with index 301 with 9 quads '+00:00.28'
```

**Comment by Robyt3** [comment]
Happened again with d873095d337a768748cdb46ce6a24468c6548b24:

```
2023-05-13 21:13:11 I textrender: Found non empty text container with index 175 with 6 quads 'Team 0'
2023-05-13 21:13:11 I textrender: Found non empty text container with index 735 with 6 quads 'Team 0'
2023-05-13 21:13:11 I textrender: Found non empty text container with index 708 with 6 quads 'Team 0'
2023-05-13 21:13:11 I textrender: Found non empty text container with index 681 with 6 quads 'Team 0'
```
