### ISSUE TITLE
restart command and then go through start

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5144]
sometimes ends up without time.

I think we never used restart on official servers

Reported by teini94

**Comment by Robyt3** [comment]
I can't reproduce it on a minimal map. Can you share a demo where it happens? @teini94

But I can confirm the other problem you reported, switches are not reset to their default when the round is restarted. So doors will keep the same state as before the restart.

The warmup timer is also not shown to players that are currently racing, as the race time overrides the warmup timer.

**Comment by teini94** [comment]
well maybe its when there is only 1 spawn?
like the map Jumper - just write restart 5 
and race with a bounce of guys sometimes most cant finish

**Comment by Robyt3** [comment]
Seems to be fixed according to @teini94. If it happens again, please comment or open another issue.

**Comment by teini94** [comment]
seems like doors work (they may did before?)
but laserlines still dont work
