### ISSUE TITLE
No more console output on Windows on nightly

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5150]
@Robyt3 could be related to https://github.com/ddnet/ddnet/pull/5142
Reported by bencie on Discord #bugs

**Comment by Robyt3** [comment]
It works in the server and tools but not in the client. So I think it's caused by `AllocConsole` which is only used in the client. I assume `AllocConsole` opens a new console but the logger uses the old console handle, whereas before it was retrieving the current standard output handle everytime.

**Comment by Robyt3** [comment]
The client console is also weird because it always opens in a new console window, instead of using the existing one when you start from a commandline. It doesn't do that on upstream and we also don't use `AllocConsole` there.
