### ISSUE TITLE
recommendations for the new ddnet hud

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#5159]
This should be a collection of the recommendations and a little discussion about what is good and could be build in.

by @l-ouis: 
1. Gun seems a little small compared to the other weapons  (Needs more investigation, I think it is fine)
~~2. Dummy actions icons could be larger for better visibility.~~ Done (only bigger border)
~~3. Could we change angle to 0>360 instead of 0>180>-180>0? seems a lot more intuitive~~ Done
~~4. Is there any way to disable stars now that we have the freeze bars?~~ Done
~~5. Or (instead of 4?) also make freeze bars visible while inside freeze as well~~ Done

by @ChillerDragon 
~~6. Can we please get a config to disable the jump indicator~~ Done

**Comment by C0D3D3V** [comment]
About 4. and 5.:
The stars are sent by the server, so they cannot be deactivated on the client side (you could just not show stars in general, but that would be goofy, because then shots also have no stars.). But one could consider for new ddnet versions to no longer send stars. However, some have already said they will not use the freezebar (that's why I added the option to disable the freezebar), because the stars give them enough information.

**Comment by heinrich5991** [comment]
The goal should be to remove config options, not add them. Config options create untested complexity.

**Comment by l-ouis** [comment]
1. i just thought it looked small compared to ingame (maybe gun is scaled to be bigger ingame?)
2. ill try to experiment later, this one isn't too important tho
3. yeah 0->360 from the right makes most sense (the way commonly used in a trigonometry class for example)

**Comment by C0D3D3V** [comment]
> maybe gun is scaled to be bigger ingame 

You just do not see how small it is because it is behind the Tee xD

**Comment by HiRavie** [comment]
It's redundant to show both the freeze bar and stars, so stars should be removed to avoid clutter

**Comment by C0D3D3V** [comment]
Maybe we should not show the freezebar directly after leaving freeze, but wait a few ticks. so that when you come out of the freeze and are directly unfreezed, the freezebar is not displayed unnecessarily. On a local server during testing I didn't notice this negatively at all, but now during gameplay it's quite strange.

**Comment by l-ouis** [comment]
i think many players would prefer more info than less

**Comment by ChillerDragon** [comment]
> The goal should be to remove config options, not add them. Config options create untested complexity.

Can we please get a config to disable the jump indicator -.-
I am happy to test that :D I would use that config always.
