### ISSUE TITLE
Use `std::unique_ptr` when returning an owned object

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#5160]
I'd think that it'd be useful, from now on, to use `std::unique_ptr` instead of a raw pointer when returning an owned object. What do you think?

**Comment by def-** [comment]
Raw pointers should not be used in modern C++ at all. So I agree. I think I might have added some code using unique_ptr already.

**Comment by edg-l** [comment]
I agree too.

**Comment by heinrich5991** [comment]
> Raw pointers should not be used in modern C++ at all.

Raw pointers sound fine for unowned pointers to me. `shared_ptr` isn't free either, `unique_ptr` is only not free because of ABI stuff.

**Comment by heinrich5991** [comment]
Seems like there's approval for this.
