### ISSUE TITLE
custom hud asset crashes game

### ISSUE THREAD

**Issue by bencie** [ddnet/ddnet#5168]
on steam, win10, nightly version there's a bug that constantly crashes the client, basically if you put any png file in %appdata%\teeworlds\assets\hud that is not called default.png, then itll crash upon refreshing assets. when you name it default.png, it'll keep using the default hud png (in steam dir, ddnet\data ) without crashing, and the only way to change the hud image is by replacing the file in ddnet\data

**Comment by C0D3D3V** [comment]
could you add the png you tested please?

**Comment by bencie** [comment]
custom: https://cdn.discordapp.com/attachments/934928193356464168/977194503809167421/hud.png
default: https://cdn.discordapp.com/attachments/934928193356464168/977194941379932211/hud.png
