### ISSUE TITLE
m_StartTime can underflow into positive

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#5170]
https://github.com/C0D3D3V/ddnet/blob/8b31dbb108b8f2fb8f127bfb52f0b3fcc1f13a30/src/game/server/entities/character.cpp#L1842

reported by Hav on discord

**Comment by C0D3D3V** [comment]
finish with negative time is not possible since it is checked in  OnCharacterFinish
https://github.com/ddnet/ddnet/blob/79f377b1338728de8cde936e0b10d0a1946a00b4/src/game/server/teams.cpp#L195-L197

But maybe we want to fix the overflow anyway

**Comment by C0D3D3V** [comment]
how about we let players die as soon as underflow occurs?

**Comment by C0D3D3V** [comment]
it is server side, it is used as linked above to calculate the finish time:
`float FinishTime = (float)(Server()->Tick() - GetStartTime(pPlayer)) / ((float)Server()->TickSpeed());`
`GetStartTime()` returns `m_StartTime` of the player.

However, with Time Penalty tiles and Time Bonus tiles, this value is directly manipulated. This is not a problem, you can go as far as you want into the minus, the result (the finish time) remains correct. Time Bonus tiles are not available on ddnet maps anyway. 
It only becomes a problem if you go over a Time Penalty tile so often (which works very fast because you can just bounce out and in with another tee and get penalties in every tick) that m_StartTime jumps from negative to positive again. If this happens, the calculation will be wrong because now m_StartTime is much bigger than the server tick and you would have a negative time. The server then only lets you finish as soon as m_StartTime has changed back to negative by waiting.

**Comment by Chairn** [comment]
Can we switch all integer timers to `int64_t` ?

**Comment by C0D3D3V** [comment]
not really because we are limited by 32 bit in the net obj that we send to the client. Also not really useful, 
2147483647/50/60/60/24 =~497.10 days should be enough for a racing game. And with penalty blocks you can max double that if you go into negativ. But I would like to limit it to a lower minimum of -2147483648... because overflow into positive can allow cheats

**Comment by Chairn** [comment]
Oh that actually corresponds exactly to the new worst time on Time Shop, 11930 hours is 497 days. So we are already reaching this limit with some map.

**Comment by C0D3D3V** [comment]
[Hav](https://ddnet.tw/players/Hav/) & [Skystrife](https://ddnet.tw/players/Skystrife/) are also these that reported that bug to me and probably also used it to get the best time on the map, that is possible if you let it underflow into positive, and then go so close to server tick that you can finish and do not to have to wait very long, so that the server lets you finish
