### ISSUE TITLE
Don't use STUN servers for LAN

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5180]
No use anyway. @heinrich5991

**Comment by heinrich5991** [comment]
Why not? Perhaps we should specify that we're talking about UDP connectivity to the internet.

But then again, without an internet connection, we shouldn't get any STUN server to query…

**Comment by def-** [comment]
Can STUN tell the client something useful when the server is in LAN and not reachable via Internet?

**Comment by heinrich5991** [comment]
> Can STUN tell the client something useful when the server is in LAN and not reachable via Internet?

STUN only checks the client's UDP connectivity to the internet. It doesn't matter if the server is connected to the internet or not.
