### ISSUE TITLE
sv_netlimit keeps causing "Stressing network" bans

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5207]
Started happening recently. Not sure yet why.

**Comment by fokkonaut** [comment]
Because player want to join a full server at any cost, since new slots are often instantly taken, therefore they spam connect.

**Comment by Robyt3** [comment]
Maybe caused by the milliseconds/nanoseconds changes? @Jupeyy

**Comment by def-** [comment]
Aaaah, good idea. Maybe it's become much easier to trigger this now.

**Comment by Jupeyy** [comment]
i assume its the floats used there, maybe i provide a fix without floats, but not really time rn
