### ISSUE TITLE
Prefix for `std::vector` variables

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#5209]
Which prefix do we want? Options are: None, `a` (like array) or `l` (like list).

**Comment by heinrich5991** [comment]
I'd vote for `a` because an `std::vector` is basically a growable array.

**Comment by Jupeyy** [comment]
i mainly used `v` lately. `a` collides with static sized arrays, that's not really nice. We can also use not prefix tho. we also don't use prefixes for almost anything else

**Comment by fokkonaut** [comment]
I also use v in my mod

**Comment by Chairn** [comment]
I'd prefer v as well to indicate its dynamic nature vs a for static array.

**Comment by trml** [comment]
Would prefer a prefix over no prefix, and a over v since their usage is often interchangeable.

**Comment by C0D3D3V** [comment]
a also sounds more sensible to me than v (and l). I would not like to add too much complexity, I find a as a prefix almost unnecessary, but better than v which brings hardly any more information. I don't really like prefixes anyway, with most array variables it's obvious from the name that it's an array. And the editor (your IDE) usually gives enough support to determine if it's an array or a vector (without additional time).  So I would also use a over v.

**Comment by Jupeyy** [comment]
but how does a give more information than v when a is used by two different types?

Also how are static arrays and vectors interchangable? they are completly different things

**Comment by C0D3D3V** [comment]
The next question would then be do you give sets (and if we ever use stacks) a prefix as well?

I think he mean you can interchange them in for each loops? 
a would tell me that it is some kind of list :D What kind of list is not said, yes. 
you can of course make this prefix granular and also use l or v for any kind of dynamic std lists. But please don't make it too granular, that just makes the variable names more unattractive in my opinion.

**Comment by Jupeyy** [comment]
yes, probably the best is to not use any prefix

if u have a list of skins, name ur var skinlist
problem solved xd

**Comment by trml** [comment]
> I think he mean you can interchange them in for each loops?

Mainly this, yes, they both represent contagious memory (and both have a size function/operator), and in some situations (depending on the information you are interested in) "a" might be specific enough (while in others not). Also, for a moment I was mistakenly thinking about dynamically allocated arrays as well, but I just remembered that "p" is used for those (I guess these are being increasingly replaced by vectors).

**Comment by Chairn** [comment]
> contagious 
contiguous :)

**Comment by trml** [comment]
> contiguous :)

Exactly :)

**Comment by heinrich5991** [comment]
> if u have a list of skins, name ur var skinlist
> problem solved xd

Well, that's basically what the prefix does, except that the prefix is shorter.

**Comment by heinrich5991** [comment]
> also takes less than a second before the IDE/code editor tells you anyway

That depends on your IDE/editor, and is also not available when looking at code on github or reviewing pull requests on github.

**Comment by C0D3D3V** [comment]
> not available when looking at code on github

I agree for that it is a good use case, maybe then use v (or l) for dynamic growing lists
However, github could also improve its rudimentary IntelliSense, which is almost usable for python code.

**Comment by heinrich5991** [comment]
C0D3D3V: In favor of v, l.
Chairn: In favor of v.
fokkonaut: In favor of v.
Jupeyy: In favor of none or v.
heinrich5991: In favor of a.
trml: In favor of v.

Sounds like there's almost consensus on v, and seeing that, I also don't mind it. So:

`v` as a prefix for `std::vector` variables.

**Comment by C0D3D3V** [comment]
Just for the record, I would like to change my vote to "In favour of none or v"
However, this does not change the result
