### ISSUE TITLE
cl_reset_wanted_weapon_on_death does not work reported by Banana090 

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#5211]
reported  here https://github.com/ddnet/ddnet/issues/3114

the problem that cl_reset_wanted_weapon_on_death does no longer work is because m_Controls.OnPlayerDeath is no longer triggered here:
 https://github.com/C0D3D3V/ddnet/blob/d13f5db996bc6fc3a35a5358f2bdc1477d8f9464/src/game/client/gameclient.cpp#L1509-L1513
 
 because of the fast respawn patch maybe (you also most of the time see now scoreboard if you die, but respwawn instantly...)
 the player death probably could be checked with other events, like ~~NETEVENTTYPE_SPAWN  NETEVENTTYPE_DEATH~~ (also used if you pause)  ~~or the game info flag GAMEOVER~~ (only used if the server stops the round)
 
 use of `m_Alive` is probably the only way or checking CNetMsg_Sv_KillMsg

**Comment by Chairn** [comment]
In my test, player would now always spawn with its last weapon. @laxa who introduced this setting is no longer active, so i think we can get rid of this setting (PR on the way).

**Comment by C0D3D3V** [comment]
I also do not need the option xD But what if you wanted to reset the weapon on spawn? Since it is not working for a while I do not think anyone used it... so we can probably get rid of it.
