### ISSUE TITLE
Vanilla 0.7 Scoreboard Ping display not working correctly on DDNet servers

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#5220]
![image](https://user-images.githubusercontent.com/60477660/170299554-ae011ef1-97de-4389-9f07-997295426d7d.png)

**Comment by Robyt3** [comment]
Also, when you open the scoreboard on a 0.7 client it shows the client in the chatting state (with the chat emote). And when actually chatting it doesn't show the emote. Seems like some flags are getting mixed up.
