### ISSUE TITLE
Do not mem_zero classes

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet#5228]
Basically title.

This is UB as soon as the class is virtual (haven't found any case in our codebase) and for any class member variable as well.
Example here:
https://github.com/ddnet/ddnet/blob/8e3d5c1b5920e17274e126b8f8d8ad0b49dd6354/src/game/client/gameclient.cpp#L1100-L1104

Member variable that is probably UB (in CCharacterCore), it depends on STL implementation hence why it crashes with MSVC and not with other compilers:
https://github.com/ddnet/ddnet/blob/8e3d5c1b5920e17274e126b8f8d8ad0b49dd6354/src/game/gamecore.h#L225

What happens is:
1. `TempCore` is initialized, `m_AttachedPlayers` is default initialized (default constructor)
2. `TempCore` is completely zeroed-out, erasing any data in `m_AttachedPlayers`
3. `TempCore` is used and may trigger any UB in `m_AttachedPlayers`.

I think we need to either initialize all members, either using c++11 assignment or defining all default constructor. We should also forbid any mem_zero on classes to prevent further problem. To clarify, we could change prefix to `S` for POD struct.

Thanks to Tater on discord (@sjrc6) for noticing this bug ;)

**Comment by Chairn** [comment]
mem_zero called on variables, most aren't problematic:
```bash
grep -rin 'mem_zero\(&?(\w+), sizeof\(\1' | wc -l
119
```

mem_zero called on classes:
```bash
grep -rn 'mem_zero.*, sizeof\(C' | wc -l
15
```

**Comment by C0D3D3V** [comment]
as far as i understand this correctly:
https://stackoverflow.com/questions/2417065/does-the-default-constructor-initialize-built-in-types

 you could also just call the default constructor instead of filling the whole memory with zeros.

But I also think that explicit constructors would be more robust and so everyone who doesn't have C++ Deep knowledge would know what's going on (how the members of a class are initilized).

**Comment by C0D3D3V** [comment]
Your grep commands only work if I add `E` to the argument list ;)

**Comment by def-** [comment]
This check sounds like it should have found this: https://clang.llvm.org/extra/clang-tidy/checks/bugprone-undefined-memory-manipulation.html
Not sure why it didn't

**Comment by Chairn** [comment]
It doesn't specify mem_zero :cry: 

Should we get rid of all the mem_zero on classes and keep them only for arrays?

**Comment by Learath2** [comment]
Definitely should be something we avoid, though `mem_zero`ing a POD is safe. How about we do a template to check the argument to `mem_zero` points to a POD?

A clang-tidy check if available might be preferable to the template.

**Comment by def-** [comment]
> It doesn't specify mem_zero 😢
> 
> Should we get rid of all the mem_zero on classes and keep them only for arrays?

But we use memset inside of mem_zero. Let me check if using memset directly would work.

**Comment by def-** [comment]
Ok, turns out the check is not sufficient. It only checks for not trivially copyable data structures, but CTeamsCore and CCharacterCore are trivially copyable.

**Comment by heinrich5991** [comment]
It's definitely not a "game breaking bug" to invoke UB if it doesn't cause issues in practice. If there's a game breaking bug, please report it as something less broad than "do not mem_zero classes".

**Comment by heinrich5991** [comment]
My mistake, it was talking about a specific crash.

**Comment by Chairn** [comment]
Issue mix a special case that was solved today, and also the general case that is, in my opinion, another bug waiting to happen :)

**Comment by trml** [comment]
It also kind of looks like mem_zero is called in the overloaded `new` operator for all gameworld entity classes, defined in MACRO_ALLOC_HEAP.

**Comment by Chairn** [comment]
Looks like it's safe to do that as the constructor is called after returning the pointer.

**Comment by heinrich5991** [comment]
Done and ensured in #6256.
