### ISSUE TITLE
Disconnect "trap" when closing menu while disconnect button is clicked down.

### ISSUE THREAD

**Issue by cookstown** [ddnet/ddnet#5229]
I read the message in the end in discord and found the same behavior on my client (ddnet git client).
1. Join a map on a server.
2. Open game menu via Escape key
3. Hold Disconnect button
4. Press escape while still holding Disconnect
5. Press escape again

actual behavior:
you get disconnected from the server

proposed behaviour:
just the game menu opens

discord message:
guys, there's this annoying thing, idk if it's intended. so, you press esc, hold the disconnect button and press esc again. now you have set up a trap for whenever you press esc
this is really annoying
[discord link](https://discord.com/channels/252358080522747904/293493549758939136/979173570968162326)

**Comment by C0D3D3V** [comment]
kind of duplication of https://github.com/ddnet/ddnet/issues/3560
but also a nice scenario explained.

**Comment by C0D3D3V** [comment]
I didn't consciously notice this before, but it really is enough to press ESC the second time, even if you don't press a mouse button in the game, the mouse event is triggered in the game menu.

**Comment by def-** [comment]
Can't reproduce on macOS
