### ISSUE TITLE
Suppress log colors when redirecting stdout to a file

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#5233]
Usually all cli programs that have colors turn those off when stdout is being redirected by `>` or piped using `|`
Which can be sad because you lose colors when grepping. But it actually makes some sense. To not store the color escape sequences in a log file for example.

**Comment by C0D3D3V** [comment]
https://unix.stackexchange.com/a/515781
this could help if you want to implement it

**Comment by ChillerDragon** [comment]
Yea its usually checking the tty I think.

I had a look at `ls`


```c
static bool
stdout_isatty (void)
{
  static signed char out_tty = -1;
  if (out_tty < 0)
    out_tty = isatty (STDOUT_FILENO);
  assume (out_tty == 0 || out_tty == 1);
  return out_tty;
}


print_with_color =stdout_isatty ();
```
