### ISSUE TITLE
Initialisation of classes

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet#5247]
Recently, we had some bug due to badly initialized classes or overriding whole class with mem_zero. An easy would be to initialise all class members everywhere in the code. One way is to declare a default constructor and to zero initialize each members. Other way is to use C++11 assignment in the class declaration.

1. Default constructor with initialisation in initialiser list (either in header or source file)
```c++
class A {
public:
    A()
    : m_i(0) {}
private:
   int m_i;
};
```
2. Default constructor with initialisation in constructor body (either in header or source file)
```c++
class A {
public:
    A()
    {
        m_i = 0;
    }
private:
   int m_i;
};
```
3. C++11 assignment (header file mandatory)
```c++
class A {
private:
   int m_i = 0;
};
```
4. No initialisation at all, keep it like it is.

. 1. and 2. require more manual work and will trigger Wreorder when inserting new member variable. 3. is, imo, shorter and most concise and not require any more work when adding member variables. 4. is keep it like it is.

edit: added choice 4

**Comment by def-** [comment]
3 where we have the same value in all constructors, otherwise 1 if possible, otherwise 2.

**Comment by Chairn** [comment]
3. guarentee value to be initialized. There are overridden by any constructor

**Comment by Chairn** [comment]
I added 4th choice to not change anything

**Comment by heinrich5991** [comment]
I think I also like 3 best.

**Comment by C0D3D3V** [comment]
I also think 3 makes the most sense for us. I think I agree with deen.

**Comment by heinrich5991** [comment]
Seems like consensus is 3.
