### ISSUE TITLE
We somehow fixed the shotgun bug -> reintroduce it?

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#5258]
probably introduced by https://github.com/ddnet/ddnet/commit/6b497afba497c4e61d7d6d9940d63c97533917a3

we could check if it was hitting a player or a block...

**Comment by C0D3D3V** [comment]
I just tested if it works again if I revert that commit... no success, so it is probably something different.

**Comment by Chairn** [comment]
Somehow removing a bug is a high priority as it prevents some map to be finished (Puzzle Partner, Stacked) according to Skystrife on discord.
https://discord.com/channels/252358080522747904/757720336274948198/979805028174925905

**Comment by C0D3D3V** [comment]
xD "removing a bug is a high priority"  well formulated :) 
(but you can stop using discord links ^^ since it will not be opened in the desktop app it is kind of useless)

**Comment by Chairn** [comment]
```shell
68bcd21eff9fbace8605eec8122f860499e03c21 is the first bad commit
commit 68bcd21eff9fbace8605eec8122f860499e03c21
Author: Dennis Felsing <dennis@felsin9.de>
Date:   Thu May 26 01:22:14 2022 +0200

    asan+ubsan clean

:040000 040000 c2a05ed35a2813cf52fb342fec10feccff5c2f4c 777420887b27ed36ba256603dc2b8736563e4c00 M      scripts
:040000 040000 9b4332345d8861463c081da7bb45c552e3baddf4 ce94f0ab3e0d532ce47c86263c5f4a093e6d5a13 M      src
```
@def-

**Comment by heinrich5991** [comment]
> (but you can stop using discord links ^^ since it will not be opened in the desktop app it is kind of useless)

You can paste them into discord and click them there. I like them in case you want to go digging for a conversation later.
