### ISSUE TITLE
Demo vs. downloaded map mismatch error

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#526]
Let's say a demo's map is ctf9 (so non vanilla/default). Let's say the downloaded map is ctf9_1234 while the demo is ctf9_1111. Because of this mismatch, it cannot play the demo. After deleting the downloaded map, the demo can be played.

**Comment by def-** [comment]
Same in Vanilla?

**Comment by def-** [comment]
Tried it out, cannot reproduce.
