### ISSUE TITLE
Swapping doesn't swap no collision state

### ISSUE THREAD

**Issue by bencie** [ddnet/ddnet#5279]
When you go through a no collision tile, and swap with someone, you'll keep your no collision state. Works both in team 0 and in team. (Credit to pexi for showing me the bug)
Video: https://cdn.discordapp.com/attachments/968635358302576640/980864997930442853/Base_Profile_2022.05.30_-_18.06.28.07.DVR_Trim.mp4

**Comment by C0D3D3V** [comment]
Indeed only m_Collision is saved but not m_NoCollision

**Comment by C0D3D3V** [comment]
Strange that we even have two different variables for the same job

**Comment by C0D3D3V** [comment]
I will make a PR to remove m_NoCollision and replace it with !m_Collision where it is needed
