### ISSUE TITLE
16.1 Client crash in `std::clamp` call

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#5282]
From [Discord](https://discord.com/channels/252358080522747904/757720336274948198/980930740759965706):
> [10:28 PM] Reteah: I have got quite a few crashes after updating to 16.1 client version. It aborts after complaining about an assertion error on a std::clamp call: 
/usr/include/c++/12.1.0/bits/stl_algo.h:3623: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = int]: Assertion '!(__hi < __lo)' failed.

**Comment by C0D3D3V** [comment]
from Reteah
```
#0  0x00007fa86c45a36c in ?? () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7fa85cc88000 (LWP 18118))]
(gdb) bt
#0  0x00007fa86c45a36c in  () at /usr/lib/libc.so.6
#1  0x00007fa86c40a838 in raise () at /usr/lib/libc.so.6
#2  0x00007fa86c3f4535 in abort () at /usr/lib/libc.so.6
#3  0x00007fa86c792002 in std::__glibcxx_assert_fail(char const*, int, char const*, char const*)
    (file=<optimized out>, line=<optimized out>, function=<optimized out>, condition=<optimized out>)
    at /usr/src/debug/gcc/libstdc++-v3/src/c++11/debug.cc:60
#4  0x000055ce0cfae200 in CStun::Update() ()
#5  0x000055ce0cfa80c5 in CNetClient::Update() ()
#6  0x000055ce0d042f1b in CClient::PumpNetwork() ()
#7  0x000055ce0d043544 in CClient::Update() ()
#8  0x000055ce0d044b99 in CClient::Run() ()
#9  0x000055ce0cf5b33e in main ()
```

and from me (— 23.05.2022):
![grafik](https://user-images.githubusercontent.com/14315968/171156351-cdd26921-1bf2-4cb3-905b-a41a45aa5df1.png)

![grafik](https://user-images.githubusercontent.com/14315968/171156367-550f25ad-e42f-4504-a57a-b7e85e160b4c.png)
