### ISSUE TITLE
Jump tile's switch number is ignored

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#5283]
From [Discord](https://discord.com/channels/252358080522747904/757720336274948198/980990314267422740):
> 2:25 AM] Skystrife: For a map if you use the tile to change the number of jumps a tee can have, that block cannot be toggled with a switch despite being in the switch layer, changing the switch number for it is useless
> [3:11 AM] Chairn: that's not a bug, that's by design
> [3:11 AM] Chairn: switch number is used to select number of jump
> [5:09 AM] Skystrife: the delay is used for the number of jumps, the switch number is useless and should be used to toggle it like its used for everything else
> [5:19 AM] Skystrife: that's a switch number 2 that sets jumps to 1 but it doesnt turn on or off from switch it just always is active
> ![](https://cdn.discordapp.com/attachments/757720336274948198/981034200364883998/unknown.png)

**Comment by C0D3D3V** [comment]
I would prefer, searching for maps if any used switches with same number as a jump tile number ... If there are only few or none, we can implement switchable jump tiles

**Comment by heinrich5991** [comment]
Is there precedent for switchable tiles which have no graphical representation?

**Comment by heinrich5991** [comment]
And maybe: What's the benefit of adding switchable jump tiles?

**Comment by C0D3D3V** [comment]
> switchable tiles which have no graphical representation

Thats a good point, we probably have to make tile layer switchable to (like we would have to do for solid doors).

**Comment by Robyt3** [comment]
Fixed by #6534. The switch number is not longer rendered for jump tiles.
