### ISSUE TITLE
cl_dummy_copy_moves should be [set to] 0 when dummy connects

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#529]
Sometimes when I play a map using dummy_copy, then change map or server, dummy_copy is still enabled. If I then, for example, beat the noob filter with my primary before connecting my dummy, having dummy_copy still enabled often kills my primary (esp since `kill` command affects both tees).

I can't think of any reason why dummy_copy would need to be enabled at the moment the dummy connects, so it'd be nice to ensure it's always set to 0 at that point.

**Comment by BannZay** [comment]
d78c565f8a124157c89a245623cea06d8a9c710f should help

**Comment by timakro** [comment]
Maybe also `cl_dummy_hammer` then?

**Comment by BannZay** [comment]
> Maybe also cl_dummy_hammer then?

Ye, I guess it will be right
