### ISSUE TITLE
Undetermined crash in nightly server build

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet#5294]
Reported by @l-ouis on discord. It happens with a gore map when approaching some area in the map. Here's the crash report
[DDNet-Server_crash_log_101744_2022-05-31_18-09-30.txt](https://github.com/ddnet/ddnet/files/8810125/DDNet-Server_crash_log_101744_2022-05-31_18-09-30.txt)

I couldn't get anything from it, even with the `parse_drmingw.sh`script (only outputs `??:0`)...

**Comment by def-** [comment]
```
Parsing address: 42D187 (img base: 400000)
/home/deen/isos/ddnet/ddnet-source/src/game/server/entities/character.h:164
Parsing address: 43DE13 (img base: 400000)
/home/deen/isos/ddnet/ddnet-source/src/game/server/gameworld.cpp:273
Parsing address: 415AA0 (img base: 400000)
/home/deen/isos/ddnet/ddnet-source/src/engine/server/server.cpp:2817
Parsing address: 4E928E (img base: 400000)
/home/deen/isos/ddnet/ddnet-source/src/base/system.cpp:3880
Parsing address: 4013B1 (img base: 400000)
/build/mingw-w64-crt/src/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:323
Parsing address: 4014E6 (img base: 400000)
/build/mingw-w64-crt/src/mingw-w64-v10.0.0/mingw-w64-crt/crt/crtexe.c:204
Parsing address: 7FFC11E17034 (img base: 400000)
??:0
Parsing address: 7FFC13A02651 (img base: 400000)
??:0
```

**Comment by Jupeyy** [comment]
Well then you used a wrong version probably

also always compare the source code against the version used

**Comment by C0D3D3V** [comment]
@Chairn 
> It happens with a gore map when approaching some area in the map
what is a "gore map" and could you ask him to give instructions to reproduce the bug

**Comment by Jupeyy** [comment]
gores

**Comment by Jupeyy** [comment]
The addresses generally fit, but seems like a lot of important information was lost by the optimization

**Comment by Jupeyy** [comment]
What? xd

**Comment by Chairn** [comment]
Given that IPO messes up the stack report, i think we can close this one.

**Comment by heinrich5991** [comment]
How does one remove the reminder?

**Comment by def-** [comment]
Not possible from what I can tell.

**Comment by Chairn** [comment]
I searched and couldn't find a way either :(
