### ISSUE TITLE
Integration test script doesn't work for me

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#5295]
It doesn't launch the second client before the first one is closed or made windowed. Making it windowed from the start also fixes it.

It's also a bit fishy that it relies on sleeps to make sure the client2 has started, the sleeps are barely enough for my computer.

Arch Linux
Linux 5.17.9-arch1-1
X11, window manager i3 4.20.1

**Comment by Chairn** [comment]
Client could create an empty file so that they synchronize ?
