### ISSUE TITLE
Add /team {player_name} command ! 

### ISSUE THREAD

**Issue by Astramast** [ddnet/ddnet#5318]
The idea is that I write :
`/team PlayerName `
in chat and it makes me join the player's team.

**Comment by def-** [comment]
There could be collisions when players have names 0-63

**Comment by heinrich5991** [comment]
Perhaps `/join <player name>`.

**Comment by Chairn** [comment]
duplicate https://github.com/ddnet/ddnet/issues/3878  (https://github.com/ddnet/ddnet/issues/3878#issuecomment-855743202)
