### ISSUE TITLE
still fragments in freezebar

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#5319]
On huge zoom-out sometimes you can see fragments in the freezebar:
![grafik](https://user-images.githubusercontent.com/14315968/171733370-eec1e6e9-a36f-4232-9a5d-bcddcb1387c1.png)

This does not only happen to freezebar, I also have seen such fragments in Quad layer and Tile layers, even tees have fragments sometimes. This is a old graphics bug, from our engine. Would be nice if we could fix this. I already tried to address this, in the way it is done in vanilla by clipping a small margin on all sides of the quad texture... but this is only a workaround, and I do not want to increase the clipping if possible

**Comment by def-** [comment]
What renderer are you using? This should only happen on OpenGL 1, and not with OpenGL 3

**Comment by Jupeyy** [comment]
Did you build the HUD like game.PNG is built inside the client (it does not rely on the sprite rendering from render. CPP)?
This is not necessarily a bug in the engine, but probably a thinking problem.
If there are gaps in skins or tile layers. Could simply be a very old map

**Comment by C0D3D3V** [comment]
> What renderer are you using? This should only happen on OpenGL 1, and not with OpenGL 3

I think this happens with all renders. Since I started developing with this, before the Vulkan backend was released, I would say at least both OpenGL 3 and Vulkan. I can test the other backends later.

**Comment by def-** [comment]
@Jupeyy I thought this shouldn't happen with OpenGL3?

**Comment by Jupeyy** [comment]
If he didn't use same method as game.PNG then it happens that's why I added #2987

**Comment by Jupeyy** [comment]
BTW ogl 1 works correct too on game PNG . just not for tiles

**Comment by C0D3D3V** [comment]
So what is your suggestion?

**Comment by Jupeyy** [comment]
do it like game.png does it

**Comment by C0D3D3V** [comment]
What is the difference to my `LoadHudSkin` xD I think I'm blind

**Comment by Jupeyy** [comment]
ah then remove your offset again and fix the hud.png
i dont know your code

**Comment by C0D3D3V** [comment]
I would expect that it does not bleed no matter how the hud.png looks like.

**Comment by Jupeyy** [comment]
> I do not think it is my driver, because vanilla did the same for the ninja bar.

This is defs not an argument xD, vanilla is randomness pure. Why should i add so much complexity to the code if it doesnt fix an actual problem.

I'll look into it, but this must be a bug in the code or in the driver. The technique is litterally used everywhere.. Ravie would have killed me already if it wouldnt work ^^

**Comment by Jupeyy** [comment]
`Graphics()->WrapClamp();`
fixes it

also your code uses `Graphics()->QuadsBegin();` 

That is streamed data, pls use createquadcontainer which buffers the vertices, see how the hud.cpp does it.
Anything ingame should use only buffered vertices. Especially if its not behind a config

**Comment by C0D3D3V** [comment]
I do not think you can use a buffered quad container because the quads change every percentage... With every change of the percentage QuadsSetSubsetFree gets other values...

Thanks I will try it with WrapClamp. I already ask you that (what the wrap mode does), when I developed the freezebar, but you had not answered.

**Comment by C0D3D3V** [comment]
Or would you like a quad container for every possible percentage (so like 100)?

**Comment by C0D3D3V** [comment]
Graphics()->WrapClamp(); indeed fixes the pixel porridge that I made screenshots of, I will test later if this also works for the small slices that I hardcoded with the slice value.

I have not much experiences with shaders, if you help me. I will try it.

**Comment by C0D3D3V** [comment]
Is there a reason why WrapClamp is not the default mode?

**Comment by Jupeyy** [comment]
mhh hard to say, guess bcs its not default in opengl

also at least quads rely on repeat mode

btw random thought, u could try to use the scissor/clip to fix the percentage problem

then it works without needing a shader, and also works in GL 1.x, so probs better anyway

**Comment by C0D3D3V** [comment]
Is it possible to activate WrapClamp on Quads that are mapped? Because I have seen such pixel puree on Quads like backgorund moons or other things (that are made out of two quads)

**Comment by Jupeyy** [comment]
sadly no, this is sadly also a limitation from the vanilla days

the mapformat has many annoying limitations, more control over level of detail etc. is requested a lot by mappers.

No you are right, they are from exactly this problem
