### ISSUE TITLE
Cleanup terminal colors on quit

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#5324]
Not too dramatic but would be nice to restore the colors in the terminal when client or server quit.

![image](https://user-images.githubusercontent.com/20344300/171813823-fe511906-b0cc-4689-8554-ce52c2754154.png)

**Comment by ChillerDragon** [comment]
> I think we should restore color to default after each line actually. Safest way to handle hard exits.

Would also be nice if we can ensure proper cleanup even if there is an hard exit. Maybe not for SIGKILL.

**Comment by heinrich5991** [comment]
> Would also be nice if we can ensure proper cleanup even if there is an hard exit. Maybe not for SIGKILL.
> Imo putting all cleanup code in one place and run it once at the end is smoother.

We already shut down gracefully on ctrl-c.

**Comment by ChillerDragon** [comment]
> > Would also be nice if we can ensure proper cleanup even if there is an hard exit. Maybe not for SIGKILL.
> > Imo putting all cleanup code in one place and run it once at the end is smoother.
> 
> We already shut down gracefully on ctrl-c.

Wasn't sure about that. But if its already there. One could slap color reset code there.
