### ISSUE TITLE
Client side TimeCP entities

### ISSUE THREAD

**Issue by MEmileTW** [ddnet/ddnet#5336]
It would be nice if we had the option of adding timeCP's on any map you wanted even if it was client-side. I asked players who speedrun maps regularly and they all said they would like being able to add them on the maps they're trying to speedrun.

**Comment by def-** [comment]
Or we have someone go through our official maps and add them there, that makes more sense to me.

**Comment by MEmileTW** [comment]
I'd be down to help doing that for sure.

**Comment by Chairn** [comment]
Yeah, i would also prefer to modify existing map to add time cp directly instead of messing with the client to add a feature that will be used by very few people.

**Comment by l-ouis** [comment]
i could help

if a team is editing all the maps itd be best to go from the popular maps down in terms of speedrunning

i also had the idea where normal tele cps could be used instead of timecps

**Comment by bencie** [comment]
I'd be down to help as well.

**Comment by def-** [comment]
Work in progress now:
https://docs.google.com/spreadsheets/d/1yMMBLSbS2cOSYsbIMkDZpMLaV6k930mXj5yVZF0Uuaw/edit?userstoinvite=louisaltgeer@gmail.com&actionButton=1#gid=0

**Comment by C0D3D3V** [comment]
I can make a short script tomorrow to list all maps that already have checkpoints (if that has not done someone else before I do it tomorrow ^^). 
@def- I think your link contains unwanted information (louis mail address)
Part of the verification process could be a short diff, that checks if only time checkpoints got added.



On comment to the topic of this issue. I think there are multiple ways to implement a client side time checkpoint system. That could also allow to save time checkpoints of not finish races. But in general that sounds more like a hacky workaroud, but it would be quite cool. To consider is also, that not every DDNet player is speedracing, so adding such a big feature (client side time checkpoints) that in the end is only used by a few... is probably only realistic if there would be a developer that wants to implement the complete thing, fix bugs and maintain it for a long time.

**Comment by def-** [comment]
Done already: https://ddnet.tw/tiles/CHECKPOINT_FIRST/

**Comment by def-** [comment]
louis found some bugs if you want to work on them @C0D3D3V :

i did some testing and seems like timecps dont work out of order
but skipping a cp does work
also found some bugs, timecps wont show if theyre too close to start, and won't show if it's a +0.00 split

**Comment by C0D3D3V** [comment]
I'll make a separate issue about it and see what I can get fixed quickly
