### ISSUE TITLE
Use `struct` for POD consistently, or use only `class` for everything

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#5338]
`struct` and `class` are identical except for the default visibility.

Should we use structs specifically to identify [POD types](https://stackoverflow.com/questions/146452/what-are-pod-types-in-c) and classes for everything else? Or just use classes for everything?

In any case, we agree that `struct`/`class` names will use the prefixes `S`/`C`.

@Chairn in https://github.com/ddnet/ddnet/issues/5337#issuecomment-1146625826

@heinrich5991 in https://github.com/ddnet/ddnet/issues/5297#issuecomment-1144250491 and https://github.com/ddnet/ddnet/issues/5297#issuecomment-1144712174

**Comment by Chairn** [comment]
Also end of my first post in https://github.com/ddnet/ddnet/issues/5228

**Comment by Learath2** [comment]
I want struct for PODs  (it might also be nice to not even have member functions on these). `S` for struct, `C` for class sounds perfect

**Comment by Chairn** [comment]
We can also encapsulate memset family function in a template function to test with `std::is_standard_layout` or `std::is_trivial`.
See https://stackoverflow.com/questions/7624714/c-how-do-i-use-type-traits-to-determine-if-a-class-is-trivial

**Comment by heinrich5991** [comment]
> I want struct for PODs (it might also be nice to not even have member functions on these). `S` for struct, `C` for class sounds perfect

What is the reason for this?

It doesn't seem particularly helpful to me.

A downside is churn in case someone wants to change a type from POD to non-POD.

> it might also be nice to not even have member functions on these

That sounds rather impossible, need operator< for some collections, and operator== is also very nice.

**Comment by heinrich5991** [comment]
Also using classes for everything is also very mechanical. Basically like running clang-format and not deciding indentations manually.

**Comment by Learath2** [comment]
> > I want struct for PODs (it might also be nice to not even have member functions on these). `S` for struct, `C` for class sounds perfect
> 
> What is the reason for this?
> 
> It doesn't seem particularly helpful to me.

A `struct` datatype and a `S` prefix would clearly indicate that something is a POD. So no weird behavior, you can treat it as data. 
`struct`s also have default `public` visibility on their members, as one would expect for a dumb POD.

> A downside is churn in case someone wants to change a type from POD to non-POD.

This I hadn't thought about, but how often is this a thing anyway?

> > it might also be nice to not even have member functions on these
> 
> That sounds rather impossible, need operator< for some collections, and operator== is also very nice.

I guess operator overloads also count as member functions. It wasn't my intention to include them in my statement.

**Comment by C0D3D3V** [comment]
I'm in favour of using only `class`. At least for everything that is not just a POD holder. So for everything that has at least one method I would use a class. 
 The only good use case that I see for `struct` is in the use as a data holder for file/network reads and writes, and even for this use case one could use classes with additional post-process functions and constructor for defined init values. (yes that is also possible in struct, but I think it is more uniform if everything that can do more then nothing is a class)  
 
For code readability, I think it would be good to stay with only `class`, and I think functions like `memezero`, `memset` (our wrapper `mem_zero`) could be omitted all,  because the compiler would optimize loops over arrays anyway, and for all other types the initialization should happen not through these functions.

**Comment by def-** [comment]
> This I hadn't thought about, but how often is this a thing anyway?

Now that we use std::vector/set/etc. it happens more often than before.

**Comment by heinrich5991** [comment]
Since we now have type-safe `mem_zero` thanks to @Chairn, I think the need of distinguishing "data classes" from "classes" isn't as urgent anymore.

Hence: Use `class` and the `C` prefix everywhere.

**Comment by Chairn** [comment]
This will add an ugly 
```c++
public:
```
in all current structs

**Comment by Robyt3** [comment]
> Use `class` and the `C` prefix everywhere.
