### ISSUE TITLE
Should we make cl_show_others default on?

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#5339]
I often see new players with nearly no experience struggle in solo parts, because they have no clue how to do the part easy.
If the new player then also speaks not your language, it is hard to tell him how he can watch you doing the part. 
Since we have `cl_show_direction` default on, probably to make it easier for new player to follow key presses of other players, we could think about also making `cl_show_others` default. Ideally, set the default to 2, since you usually don't want to see other teams.

**Comment by def-** [comment]
I'm ok with that. Other opinions?

**Comment by C0D3D3V** [comment]
An argument against it from teini94:
```
the thing is
about show_others on in ddnet
that its very distracting
imagine like stronghold 30 players on starts hard to see who is real etc
```


That is probably also true.


It is probably confusing for new players to see others but not be able to interact with them. In the new HUD you now see an icon that is supposed to symbolize "solo", is probably not quite clear for new players at first. But I think the learning curve is quite flat. 

However, new players now start with the tutorial, where show_others is on by default, so they learn it fast. 

Alternative would be that one explains new players a few basic settings in a settings tutorial tour.

**Comment by Chairn** [comment]
Not really pro or against, but yeah some settings tour that affect gameplay could be integrated in Tutorial map

**Comment by C0D3D3V** [comment]
I close that because I find a tutorial tour through the settings and a list of all commands better than any magic defaults to find out.
