### ISSUE TITLE
Freezed tee onpause indicator

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#535]
If tee freezed and player used pause/afk you cant see it. I guess it needs fix

**Comment by def-** [comment]
I don't understand.

**Comment by BannZay** [comment]
I`m talking about eye emotes.

**Comment by FallenKN** [comment]
I think he is talking about the blink eyes while being freezed prevents others to see if freezed player have paused their game with /pause or /spec

**Comment by ChillerDragon** [comment]
Imo emote pain would fitt. If a player is freeze and pause/spec his eyes turn pain.
Pain eyes are also used for deeped tees and then player can recognize fast that a player won't react if his eyes are pain.

**Comment by def-** [comment]
Don't see any good indication.
