### ISSUE TITLE
Tune lock instead of live freeze

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#5352]
converted from #4606.

@corneum wrote:
> Wouldn't it be better to add a tune zone tile that adds properties to a tee without having to stay in the zone?
> You could make the new live freeze tile with that and many more without adding a tile to the gamelayer

@heinrich5991 wrote:
> On the one hand, I like that this is a separate tile: It makes it intuitive when viewed in editor/entities, a property tune zones do not have. It also makes it possible to add a graphic for this.
> On the other hand, I don't know if this feature is going to be used often enough to warrant its own tile. Also, the customisability of your approach also sounds nice.

@corneum
> maybe its okay to do both. i dont want to hinder the release of this new tile. because you could already recreate more than just live freeze with it
> im more interested to get this tune lock tile at all because im having so many ideas with it. you could have a dummy that is in 0 gravity while you yourself are on normal gravity.
> do you think its possible to make it?

**Comment by corneum** [comment]
On the other hand, I don't know if this feature is going to be used often enough to warrant its own tile. Also, the customisability of your approach also sounds nice.

lol this did not concern you when adding 4 new shields xd

**Comment by C0D3D3V** [comment]
> Wouldn't it be better to add a tune zone tile that adds properties to a tee without having to stay in the zone?

duplication of  #4651

Also since live freeze is already implemented we can close this. But we keep in mind the possibility to create live freeze using tune lock for #4651
