### ISSUE TITLE
Team lock can kill finished tee`s

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#536]
Lets say you got finish but your mate was behind and fail, after pressing kill by them you got kill too (cause team locked) and no finish for both.

My solution : onfinish unlock the team, and dont let it be locked till at least one have finish. After full team finishing team can be locked again

**Comment by timakro** [comment]
This sounds confusing, we should better kill only players who didn't cross the finish line yet when a member of a locked team kills. I'm not sure if we should add this though because sometimes a player who crossed the finish line may not want to finish but restart with their partner.

**Comment by BannZay** [comment]
> we should better kill only players who didn't cross the finish line yet when a member of a locked team kills

But then finishers can just do kill for get finish. Sounds even worse then title of this issue. 

>   sometimes a player who crossed the finish line may not want to finish

I guess it happens very rarely. Usually players do unlock and kill failer.

**Comment by timakro** [comment]
> But then finishers can just do kill for get finish ignoring slow tee`s.

I'm not talking about changing the standard killing logic, a player who issues the kill command should always be killed. Just the other players in a locked team should only be killed if they didn't pass the finish line yet.

**Comment by BannZay** [comment]
I believe should be rule like "Or full team finish or nobody" (to not offend nobody)
Your solution break the rule. Thats why I do not like this solution

**Comment by timakro** [comment]
How does it conflict with that rule? To clear out all misunderstandings I implemented it here cf632d4c3e44c1dd8972f6c2e32b2a0e69198bae.

**Comment by BannZay** [comment]
Lets say 3/6 players have finish. so they can just KICK from team  rest 3 players which racing atm.
Its completele bad

**Comment by timakro** [comment]
Please test your question with my implementation.

**Comment by BannZay** [comment]
> Please test your question with my implementation.

So I did it, and my question still here.

If you sure in your code, I`m fully disagree with this logic. Finished tee`s shouldnt wait rest while they doing his 999 try`s.

**Comment by def-** [comment]
I don't like the change you're proposing. I belive it's good as is. People intentionally kill like that to prevent spamming the server with finishes while they're speed racing. Note that team lock is primarily meant for speed racers, not regular teams.
