### ISSUE TITLE
Remove or fix cl_nameplates_ha?

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#5365]
I noticed sometimes cl_nameplates_ha is displayed for other players (I saw this on ddnet server on tutorial map), but most of the time only for the own player and that only if cl_nameplates_own is on. 

I think this is mainly used for non race mods. And there it is not even shown on other players. 

I see three options:
- Show it on all players
- Or removing the option complete
- Or fix it so it is always only shown on the own player

I would suggest to remove the option completely.

Another thing to note, we should add opacity to all nameplate elements.

**Comment by heinrich5991** [comment]
Original PR: https://github.com/ddnet/ddnet/pull/2472.

**Comment by sirius1242** [comment]
This option renders for other players only in demos which are recorded by the server. I thought it might be a little helpful for videos of pvp mods, but it seems there is nobody else using it, you can remove it.

**Comment by heinrich5991** [comment]
Do you use it @sirius1242?

**Comment by sirius1242** [comment]
I used it when I made videos about teeworlds some time ago. And if I need it again, I can keep this function in my local version.
