### ISSUE TITLE
Should we put stuff into namespaces?

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#5367]
From https://github.com/ddnet/ddnet/pull/5363#issuecomment-1147355244
> I think I missed the tw namespace being introduced. What was the reason?

What's the reason for putting stuff into namespaces?

I can see the positive effect that we're less likely to clash with existing names.

I can see the negative effect that it's extra typing.

Absent of quantifications of these two, I'd think that the drawback outweighs the advantage.

**Comment by heinrich5991** [comment]
So `CCmdlineFix` can probably go outside the namespace.

**Comment by Jupeyy** [comment]
i'd say yes
