### ISSUE TITLE
Rendering lag on East Asian languages

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#537]
When TW language is set on an East Asian language (let's say Japanese) and you press tab for the scoreboard, it takes some milliseconds for it to load. I have a very fast computer, so I imagine slower computers suffer a lot more from this. After the first time pressing tab, it's okay, so my guess is it's a pre-render/caching problem.

**Comment by ACTom** [comment]
Yeah, it's fonts problem, but I don't know how to fix it, so when I add Chinese support, I have create a new font, and when user choose CJK language, ddnet load big font, else load small font.
Maybe someone can fix it.

**Comment by Jupeyy** [comment]
described in #809
referred to #684
