### ISSUE TITLE
Race ghost not clearly distinguishable from player

### ISSUE THREAD

**Issue by trml** [ddnet/ddnet#5386]
<img src="https://user-images.githubusercontent.com/9425859/173193899-703b2c3d-5e1f-4523-9de1-e8991217bf07.png" width="433" height="287" />

Maybe there could be a setting to control the darkness of the race ghost, or optionally default to something more distinguishable? (after #4938 @C0D3D3V)

**Comment by trml** [comment]
Ah, wait

**Comment by AssassinTee** [comment]
@trml `cl_show_others_alpha 50` and the ghost is transparent, I had the same issue, might also be a default config value problem

**Comment by trml** [comment]
@AssassinTee thanks, I wrongly assumed that one wasn't used for ghost. I wonder if the should perhaps be lower than 100, but that's perhaps a more general question, so closing this

**Comment by C0D3D3V** [comment]
you could request a seperate alpha config for ghosts :)

**Comment by trml** [comment]
@C0D3D3V yes, was perhaps thinking about that. Thought I'd try to play a little bit with a lower alpha first to see what it's like.
