### ISSUE TITLE
Frequently unresponsive on Windows 11

### ISSUE THREAD

**Issue by kyjsj** [ddnet/ddnet#5402]
The version of Windows 11 is 22000.xxx
`ddnet.exe` downloaded from both ddnet.tw/downloads and Steam is frequently unresponsive (not timeout).
Besides, to load `Assets` directory in `Setting` would report an unknown error but can still open it.

**Comment by def-** [comment]
Any other applications running? If this was happening for everyone on Windows 11 I would expect many more reports, yours is the first I have seen.

**Comment by def-** [comment]
Sounds like a bug with ToDesk. You can report it to them. Tell them DDNet is an OpenGL based game. You can also try if using Vulkan renderer in DDNet graphics settings fixes it.

**Comment by kyjsj** [comment]
I am sure it's not a bug with ToDesk now. It's more like TimeOut, but when timeout is occuring, ddnet.exe is unresponsive and I cannot move the cursor, `win+tab`, and `alt+tab`. Noted that the game window is full screen or full screen with no border.

**Comment by luk51** [comment]
running latest master on windows 11 fine.
the muse pointer is fixed to top left corner though until i click it
