### ISSUE TITLE
Add DDraceNetwork to Consoles Store

### ISSUE THREAD

**Issue by Itube17** [ddnet/ddnet#5425]
I saw already an pic where someone play teeworlds with controller. I would also help to make it playable.

**Comment by heinrich5991** [comment]
What is consoles store?

**Comment by Chairn** [comment]
I guess he speaks about play store and apple store? Maybe other stores? 

Sounds like duplicate of https://github.com/ddnet/ddnet/issues/4644

/remind me 1 week

**Comment by Chairn** [comment]
closed as duplicate of #4644
