### ISSUE TITLE
Vote Veto not working

### ISSUE THREAD

**Issue by Xandaros** [ddnet/ddnet#543]
Recently it has happened a few times to me that I was playing and some people would come along and vote for a map change. (Usually a group of tees that just finished and often the only other players)

Before, I could just veto the vote by voting against it, but that does not seem to work any more and the vote goes through, anyway.

**Comment by H-M-H** [comment]
You have been playing for longer than 20 minutes ?

**Comment by Xandaros** [comment]
Hmm, I didn't realise you have to have been playing for 20 minutes for veto to work. I figured there was a time like that, but 20 minutes seems a bit excessive.
