### ISSUE TITLE
Slow editor navigation

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#5441]
https://github.com/ddnet/ddnet/pull/5428

eb7e210fc1ec76192dcb62f7ef9cad7b7c5ee6b6
Slowed navigation down

**Comment by Robyt3** [comment]
What do you mean with navigation?

**Comment by Robyt3** [comment]
Okay, mouse scrolling with the middle mouse button appears to move the view/layers less with eb7e210fc1ec76192dcb62f7ef9cad7b7c5ee6b6.
