### ISSUE TITLE
DDNet-Server.exe refuses to start on Windows 10

### ISSUE THREAD

**Issue by wirlez** [ddnet/ddnet#545]
Worked fine until 10.3.1
I have confirmed that DDNet-Server.exe still works on 10.2.1

**Comment by heinrich5991** [comment]
What error message do you get? If there's a terminal that quickly pops up and immediately closes, can you try opening the server from a console?

**Comment by wirlez** [comment]
No error, it just refuses to start. Everything stops and eventually I have to restart explorer from task manager. I do not see any terminal that quickly pops up!

**Comment by H-M-H** [comment]
Did you start it via console ? Often this gives us some more info required to fix this.

**Comment by daverck** [comment]
It works for me.

**Comment by def-** [comment]
Can't reproduce.
