### ISSUE TITLE
Editor: save maps to tmp file instead of overwriting them

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#5451]
Currently map files are overwritten in place when being saved. So when the save process does not finish you end up with a corrupted map file.

That actually happend to me in my windows blue screen days. I was working on a big map that took around 1 second to save. Since I was aware of my pc being unstable I developed the habit of saving non stop. And one time my pc crashed during the save of the file. Which broke the map file.

It would be nice to save in a .tmp file first and then move the file.

**Comment by Robyt3** [comment]
Duplicate #4476.

As a workaround until we figure out a solution that works for all systems: just save to a different map file each time or use Git for your maps?

**Comment by ChillerDragon** [comment]
ops

**Comment by ChillerDragon** [comment]
> Duplicate #4476.
> 
> As a workaround until we figure out a solution that works for all systems: just save to a different map file each time or use Git for your maps?

Nowerdays I don't got my bluescreen windows anymore. And yea I commit after every mapping session.
