### ISSUE TITLE
Maybe a bug in the snapshot system

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#5455]
If a snapshot is spitted into multiple parts, the client receive them as `NETMSG_SNAP` identified by there part number.
There can be up to 64 parts. And in this line is checked if all parts were received 
https://github.com/ddnet/ddnet/blob/cd8706a84ab928a37d11b2c9a18ca4e91c5007e5/src/engine/client/client.cpp#L1946

But I think the check is wrong, because `m_SnapshotParts[Conn]` is of type `unsigned` and as far as I know `unsigned` is only 32bit long. I think we should use `uint64_t` for the parts bit array. 

But maybe I'm wrong. But since very big snapshots are very rare (I could not even get it triggered myself, somewhere must be an other limit that prevents to many snaps in a snapshot), I think this bug is not often triggered.

**Comment by Chairn** [comment]
unsigned is at least 16 bits. So could be 16, 32 or even 64 bits. So yes, this part should use intxx_t to have same width over different platforms.

**Comment by Chairn** [comment]
unsigned is at least 16 bits. So could be 16, 32 or even 64 bits. So yes, this part should use intxx_t to have same width over different platforms.

**Comment by Chairn** [comment]
unsigned is at least 16 bits. So could be 16, 32 or even 64 bits. So yes, this part should use intxx_t to have same width over different platforms.

**Comment by heinrich5991** [comment]
`unsigned` is 32 bit on all platforms we care about. If we wanted to have compatibility with other platforms, we need CI jobs for that. Our current code doesn't work with non-32bit `int`/`unsigned`.

**Comment by C0D3D3V** [comment]
I know now, why this bug is probably never triggered (or only very very rare). Because the compression (with skipping zero bytes and delta) is so good, that on big snaps only ~14 parts are used. Getting close to 31parts would require a snapshot that can not be compressed good. Since we already use `int64_t` in other places, I fixed it anyway (and  I will probably add it to https://github.com/ddnet/ddnet/pull/5210).

**Comment by Robyt3** [comment]
> Since we already use int64_t in other places, I fixed it anyway (and I will probably add it to https://github.com/ddnet/ddnet/pull/5210).

It's not really dependent on that PR, so just make a separate one for this fix?
