### ISSUE TITLE
"play offline" button

### ISSUE THREAD

**Issue by luk51** [ddnet/ddnet#5459]
imagine you are on a dummy map and get lags. wouldnt it be cool to have a button that sets up a server so you can play locally, without any messing around setting up your server.
i dont know if its a wanted feature, because it encourages or makes it easier to play offline.
also on solo maps it makes sense.
even novice - insane get played as single with dummy nowadays.

what do you think?

a related feature thats already there is the "load current" button in the editor, that loads the map you joined last.

this is how it could be implemented:
f1 command to play locally. (then you dont need a button, but new players wont notice)
you join a local server, dont need f2 access, same settings as the server/map (deepfly on/off etc)

also i would find it cool if you could play locally without cloning ddnet-maps, since you have the map already in downloaded maps.

intention:
no lags
play offline

tell me what you think

**Comment by C0D3D3V** [comment]
We already have a button to start a local server. But there could be made much improvemts to make it easier to start a server for local gameplay (also without internet connection), and to allow ingame configurations. 

Also the idea to use downloaded maps in your local server is not new, and I would also like to have that feature. 

Local servers would never the less only be there for fun solo games or lan parties, there is no way we could add them to the global ranking system.

**Comment by luk51** [comment]
> we can only trust ranks made on our official servers. if you can run on your own server and upload rank it‘s easy to cheat.
> 
> Playing with dummy accidentally got popular, the idea of the game is to play together with friends.

it would be without ranks. i had that idea as well, but i mean without.

**Comment by luk51** [comment]
ok, thanks for the feedback
