### ISSUE TITLE
Swap penalty isn't actually added to teams using swap

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#5460]
It's apparently only added to the actual tees swapping, but that gets reset on finish.

It should be added to the whole team.

**Comment by C0D3D3V** [comment]
The Penalty should not be added in `CSaveTee::Save` but in the functions that call  `CSaveTee::Save`. So `CGameTeams::SwapTeamCharacters` and `CSaveTeam::Save`.

**Comment by C0D3D3V** [comment]
fixed by #5461
