### ISSUE TITLE
ctrl+v in conosle also work in last select

### ISSUE THREAD

**Issue by BloodWod-513** [ddnet/ddnet#5467]
![image](https://user-images.githubusercontent.com/33897884/174820590-e57e034f-0364-46bb-b003-f94ec96a7361.png)

**Comment by heinrich5991** [comment]
I don't understand the issue.

What are you doing? What do you expect to happen? What happens instead?

**Comment by Robyt3** [comment]
1. Activate a UI editbox.
2. Activate the console.
3. Press any letter key: it correctly appears only in the console.
4. Press Ctrl+V: the clipboard appears in console and UI editbox. It should only appear in the console.

**Comment by Robyt3** [comment]
#5468
