### ISSUE TITLE
Input on macOS is broken for characters like ^ or `

### ISSUE THREAD

**Issue by H-M-H** [ddnet/ddnet#547]
Typing the characters mentioned above into a textfield results in this:
![ddnet-input-macos](https://cloud.githubusercontent.com/assets/7461564/18421328/39f5a754-7888-11e6-9de0-17146c8faef5.png)

Pressing escape, backspace and delete wont work for the textfield once you typed one of those characters.

**Comment by H-M-H** [comment]
@ACTom @TsFreddie 
I guess this is related to one of your recent contributions, any ideas ?

**Comment by H-M-H** [comment]
It seems this is related to setting the m_IsEditingText state in https://github.com/ddnet/ddnet/blob/master/src/engine/client/input.cpp. Always setting it to false allows to escape textfields (which obviously is not a solution but maybe a useful hint).

**Comment by ACTom** [comment]
Cannot reproduce it.I can press them normally.

OS:10.11.6 (15G1004)
DDNet:10.3.1

**Comment by H-M-H** [comment]
Further investigation:
It appears that as ^ \` are potential combining characters we get this event from sdl: `SDL_TEXTEDITING`. But for some reason it is impossible to leave editing mode (with german keyboard layout), except you switch to another input method like Pinyin (I just took one randomly ^^) and type some stuff which then can end editing mode.

**Comment by def-** [comment]
Please check if I just fixed this. (HEAD, not 10.6.4)
