### ISSUE TITLE
render everything in demos

### ISSUE THREAD

**Issue by luk51** [ddnet/ddnet#5472]
* zoom
* <s>new hud</s>
* emote chooser
* chat input
* scoreboard
* ...did i miss something?
* statboard
* show more chat

dont render
* ingame browser
* f1/f2 console

what do you think?

**Comment by luk51** [comment]
similar to this: #3291

**Comment by heinrich5991** [comment]
It is unclear to me what you're asking for.

We already use zoom to render, show the new HUD, show the emote chooser, show chat input, scoreboard, statboard and more chat ingame.

**Comment by luk51** [comment]
screencast vs rendered demo

https://user-images.githubusercontent.com/4086396/174900934-8d14f146-522c-4405-859b-5045e61b2e7d.mp4

**Comment by luk51** [comment]
i dont like open dead issues
