### ISSUE TITLE
error message when not compiled with vulkan

### ISSUE THREAD

**Issue by luk51** [ddnet/ddnet#5473]
i didnt compile with vulkan on windows 11 msvc. qhen i selected vulkan ingame the game wouldnt start anymore.
would be nice to have an error message or automatic switch to opengl.
"please compile with vulkan support" or something. or erase the option, when not compiled with.support.

**Comment by heinrich5991** [comment]
Removing the option sounds good.

**Comment by def-** [comment]
I can't reproduce this. You should not even be able to select Vulkan ingame if it's compiled with -DVULKAN=OFF. Are you sure Vulkan is disabled and not just enabled and somehow broken?

**Comment by luk51** [comment]
maybe i am assuming too much.
the actual facts are, that I can run ddnet client from the website with vulkan, but not the one i built myself

**Comment by def-** [comment]
Can you share the logging output when it fails?

**Comment by luk51** [comment]
```
PS C:\Users\lukas\Documents\ddnet\out\build\x64-Release> [2022-06-23 00:01:29][engine]: running on windows-win64-amd64
[2022-06-23 00:01:29][engine]: arch is little endian
[2022-06-23 00:01:29][storage]: couldn't open storage.cfg
[2022-06-23 00:01:29][storage]: using standard paths
[2022-06-23 00:01:29][storage]: added path '$USERDIR' ('C:\Users\lukas\AppData\Roaming/DDNet')
[2022-06-23 00:01:29][storage]: added path '$DATADIR' ('data')
[2022-06-23 00:01:29][storage]: added path '$CURRENTDIR' ('C:\Users\lukas\Documents\ddnet\out\build\x64-Release')
[2022-06-23 00:01:29][http]: libcurl version 7.81.0 (compiled = 7.81.0)
[2022-06-23 00:01:29][console]: executing 'settings_ddnet.cfg'
[2022-06-23 00:01:29][client]: starting...
[2022-06-23 00:01:29][sdl]: SDL version 2.0.16 (compiled = 2.0.20)
[2022-06-23 00:01:29][gfx]: Created Vulkan 1.0 context.
```
it just stays the same after this log. the windows starts and closes again, without reaching fullscreen ingame mode.
[CMakeLists.txt](https://github.com/ddnet/ddnet/files/8961860/CMakeLists.txt)

i didn't change cmakelists so vulkan should be the default for windows which is enabled?
i didn't install any other vulkan dependencies for building

these are my specs and hardware driver:
![gpus](https://user-images.githubusercontent.com/4086396/175160933-c7f08c91-66f6-4204-862d-13fb9cc326be.png)

i followed this video and build ddnet with msvc like that:
https://www.youtube.com/watch?v=qsoGOfBqPns

**Comment by def-** [comment]
@Jupeyy Any idea what would happen differently when compiling against Vulkan with msvc?

**Comment by Jupeyy** [comment]
Try the github action builds. They also use msvc

Are ddnet libs updated to latest? What msvc do u even use

**Comment by Jupeyy** [comment]
Opengl works?

**Comment by luk51** [comment]
https://github.com/ddnet/ddnet/actions/runs/2547594759 this one (msvc build) works :( https://github.com/ddnet/ddnet/actions/runs/2547594759
opengl works with my msvc build
is this the compiler version maybe?: Microsoft Visual Studio Community 2022
```
Version 17.2.3
VisualStudio.17.Release/17.2.3+32526.322
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA569
Microsoft Visual C++ 2022

ASP.NET and Web Tools 2019   17.2.392.13739
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.2.392.13739
Azure App Service Tools v3.0.0

C# Tools   4.2.0-4.22252.24+47cdc16a21bbb8a4aadfb666b011e2059e1be5d2
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.10418.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.2.0-4.22252.24+47cdc16a21bbb8a4aadfb666b011e2059e1be5d2
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.
```
Opengl works. Only Opengl 1.5 is there as an option though.

**Comment by luk51** [comment]
It's saying mingw in the prompt, because it's git bash, but I am building with visual studio msvc.
Since the build from your master branch works (ddnet/master with msvc) I'm proned to close the issue. Not interested in debugging windows building 😅 .
```lukas@DESKTOP-T72VSV7 MINGW64 ~/Documents/ddnet (master)
$ git submodule status
 02f8b2e0f3436347820cd36f35455f632ec8c590 ddnet-libs (remotes/origin/pr-vulkan-5-g02f8b2e)

lukas@DESKTOP-T72VSV7 MINGW64 ~/Documents/ddnet (master)
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

lukas@DESKTOP-T72VSV7 MINGW64 ~/Documents/ddnet (master)
$ git branch
* master
  no-goalshud-in-ddracemod

lukas@DESKTOP-T72VSV7 MINGW64 ~/Documents/ddnet (master)
$
```
