### ISSUE TITLE
Pressing escape ingame on macOS in fullscreen broken

### ISSUE THREAD

**Issue by H-M-H** [ddnet/ddnet#548]
Pressing escape in fullscreen on macOS while playing on a server will leave fullscreen and about immediately enter it again.

This behaviour has been introduced with this commit: https://github.com/ddnet/ddnet/commit/e5f23cd87cfa11775e47769ddedfb78a5379130a

@TsFreddie Ideas ?

**Comment by TsFreddie** [comment]
The IMEstate changing should only happens when opening chat and close chat (pressing esc).

I don't have a mac so I'll try to do whatever I can.

May I ask what keyboard layout and input method are you using?

**Comment by H-M-H** [comment]
Nothing fancy, just standard german keyboard layout (qwertz).

Thanks for your help :)

**Comment by elemongw** [comment]
This is still an issue, tested with the latest released version on a standard US qwerty keyboard. It happens while ingame no matter if you are typing in the chat or not.

**Comment by PathosEthosLogos** [comment]
Please fix this ASAP! This bug seems horrible.

**Comment by def-** [comment]
Can anyone check if this still happens with current HEAD? (Not 10.6.4 but the one that will be released after that)

**Comment by H-M-H** [comment]
It is gone now :+1:
