### ISSUE TITLE
Consider installing python dependencies/packages from pip

### ISSUE THREAD

**Issue by DanielNoord** [ddnet/ddnet#5483]
I was passing by as https://github.com/PyCQA/pylint/issues/7011 was reported against `pylint`. I was wondering why you were using such an outdated version of `pylint` (2.4 released in 2019 vs. 2.14.4 released a couple of days ago).

I found this is because you use `apt-get` to install `pylint`:
https://github.com/ddnet/ddnet/blob/82535814301c31a1966638429ad07d0c665858f3/.github/workflows/style.yml#L22

This means that you're dependent on updates to the package manager to get updates for `pylint`. Which apparently can take more than 3 years.
Github Actions allows you to install python dependencies quite easily and there are many tutorials online. That would make sure you have the latest version available, which might also be relevant for #5481.

**Comment by def-** [comment]
I have a WIP change open to fix newer pylint issues, could then also increase the version used in CI: https://github.com/ddnet/ddnet/pull/5395

**Comment by heinrich5991** [comment]
> This means that you're dependent on updates to the package manager to get updates for `pylint`. Which apparently can take more than 3 years.

This is kind of intended, we want to allow users to install using package managers and not depend on all software being updated using a language-specific package manager.

**Comment by DanielNoord** [comment]
> This is kind of intended, we want to allow users to install using package managers and not depend on all software being updated using a language-specific package manager.

I can understand that for end users, but since pylint is a development dependency isn't that different? Any contributor working on Python code will likely have Python and therefore pip installed.

**Comment by edg-l** [comment]
See https://pipenv.pypa.io/en/latest/
