### ISSUE TITLE
dump_local_console seems not to be correct UTF-8

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5488]
As reported on Discord by Ham5terzilla:

> russian lang in local console dump is corrupted, example:
> 
> [2022-06-24 12:30:08][chat]: NT RYSKI: Админ ебаный хуй
> ->
> [2022-06-24 12:30:08][chat]: NT RYSKI: РђРґРјРёРЅ РµР±Р°РЅС‹Р№ С…СѓР№

**Comment by Robyt3** [comment]
Works for me. What editor are they using? I tried opening the dump with Sublime Text and Windows' Notepad. Both correctly display the example above.

As we simply write the UTF-8 bytes to the file, there should be little room for errors:

https://github.com/ddnet/ddnet/blob/5bf8c23b9af0cfa36da1a1a0a037b3bf7393de63/src/game/client/components/console.cpp#L929-L949

**Comment by heinrich5991** [comment]
> [2022-06-24 12:30:08][chat]: NT RYSKI: РђРґРјРёРЅ РµР±Р°РЅС‹Р№ С…СѓР№

This looks like UTF-8 decoded as some random code page. Could we get a hexdump to be sure?

**Comment by heinrich5991** [comment]
Or an uploaded file.

**Comment by Ham5terzilla** [comment]
file: [local_console_dump_2022-06-24_12-39-00.txt](https://github.com/ddnet/ddnet/files/8976242/local_console_dump_2022-06-24_12-39-00.txt)
Used std windows notepad to open. 16010 client version.

**Comment by def-** [comment]
That file is indeed broken for me:
```
local_console_dump_2022-06-24_12-39-00.txt: Non-ISO extended-ASCII text, with CRLF, NEL line terminators
```

**Comment by Robyt3** [comment]
Opening the file in windows notepad works differently depending on whether you double-click the file in the windows explorer or whether you open notepad first and then use the open menu.
- When opening by double-click the file, the encoding is incorrectly detected as ANSI and the cyrillic characters are broken.
- When opening from inside Notepad with File > Open, you can select the encoding. Selecting either "Detect automatically" (which is the default) or "UTF-8" will show the cyrillic characters correctly.

I tried changing the default encoding that notepad uses to UTF-8 in the registry, but this only affects the encoding that notepad uses for new empty files and not for files opened by the shell. In any case, the encoding used for new files

**Comment by def-** [comment]
vim also wrongly interprets this file. Should we print a utf8 bom?

**Comment by Robyt3** [comment]
Adding a UTF-8 BOM (by resaving the file with Sublime Text) would allow notepad to detect the file automatically as UTF-8 with BOM.

But there could very well be something wrong with the UTF-8 we output. Resaving the file with SublimeText with UTF-8 encoding without BOM also allows notepad to correctly detect the file as UTF-8 again.

**Comment by Robyt3** [comment]
This is the difference when resaving the original file as UTF-8 (without BOM):

```diff
--- log.txt     2022-06-24 15:42:01.375065900 +0200
+++ log_UTF8.txt        2022-06-24 16:07:07.039176600 +0200
@@ -427,3 +427,3 @@
 [2022-06-24 11:35:27][chat]: Ñ? Ð¿Ð¾Ñ?Ñ?Ð°Ð»: f jq
-[2022-06-24 11:35:31][chat]: nameless tee: uglynosok: ÐYÐ¾ Ð¿Ð¾Ð²Ð¾Ð´Ñƒ Ð"Ð¡, Ð½ÐµÑ', Ñ? Ð½Ðµ Ñ?Ð¾Ñ?Ñ'Ð¾ÑZ Ð½Ð¸ Ð² ÐºÐ°ÐºÐ¸Ñ. Ð³Ñ?ÑƒÐ¿Ð¿Ð°Ñ. Ð¿Ð¾ Ð¾Ñ?Ñƒ. Ð"Ð° Ð¸ Ð² Ð¸Ð³Ñ?Ðµ ÐµÑ?Ñ'ÑO Ñ'ÐµÐºÑ?Ñ'Ð¾Ð²Ñ<Ðµ ÐºÐ°Ð½Ð°Ð»Ñ<, Ð¾Ð±Ñ%Ð°Ñ'ÑOÑ?Ñ? Ð¼Ð¾Ð¶Ð½Ð¾ Ð² Ð½Ð¸Ñ. Ð
+[2022-06-24 11:35:31][chat]: nameless tee: uglynosok: ÐYÐ¾ Ð¿Ð¾Ð²Ð¾Ð´Ñƒ Ð"Ð¡, Ð½ÐµÑ', Ñ? Ð½Ðµ Ñ?Ð¾Ñ?Ñ'Ð¾ÑZ Ð½Ð¸ Ð² ÐºÐ°ÐºÐ¸Ñ. Ð³Ñ?ÑƒÐ¿Ð¿Ð°Ñ. Ð¿Ð¾ Ð¾Ñ?Ñƒ. Ð"Ð° Ð¸ Ð² Ð¸Ð³Ñ?Ðµ ÐµÑ?Ñ'ÑO Ñ'ÐµÐºÑ?Ñ'Ð¾Ð²Ñ<Ðµ ÐºÐ°Ð½Ð°Ð»Ñ<, Ð¾Ð±Ñ%Ð°Ñ'ÑOÑ?Ñ? Ð¼Ð¾Ð¶Ð½Ð¾ Ð² Ð½Ð¸Ñ. ?
 [2022-06-24 11:35:36][chat]: *** 'Pioche' has left the game
@@ -966,3 +966,3 @@
 [2022-06-24 12:03:52][chat]: uglynosok: kekuus: go
-[2022-06-24 12:03:56][chat]: Ð³Ð°Ð²Ð¾Ñ?ÑƒÐ½: nameless tee: Ñ? Ð½Ðµ Ð·Ð½Ð°ÑZ Ð¿Ñ?Ð°Ð²Ð¸Ð», Ð½Ð¾ Ð¸ Ð² Ð¿Ñ?Ð°Ð²Ð¸Ð»Ð°Ñ. Ð½ÐµÑ'Ñƒ ÑƒÑ?Ð»Ð¾Ð²Ð¸Ñ? Ñ╬Ñ'Ð¾ ÐµÑ?Ð»Ð¸ Ñ'Ñ< Ð½Ðµ Ð·Ð½Ð°ÐµÑ^ÑO Ð¿Ñ?Ð°Ð²Ð¸Ð» Ñ'Ð¾ Ñ?Ñ'Ð¾ Ñ'ÐµÐ±Ñ? Ð½Ðµ Ð¾Ñ?Ð²Ð¾Ð±Ð¾Ð¶Ð´Ð°ÐµÑ' Ð¾Ñ' Ð¾Ñ'Ð²Ð
+[2022-06-24 12:03:56][chat]: Ð³Ð°Ð²Ð¾Ñ?ÑƒÐ½: nameless tee: Ñ? Ð½Ðµ Ð·Ð½Ð°ÑZ Ð¿Ñ?Ð°Ð²Ð¸Ð», Ð½Ð¾ Ð¸ Ð² Ð¿Ñ?Ð°Ð²Ð¸Ð»Ð°Ñ. Ð½ÐµÑ'Ñƒ ÑƒÑ?Ð»Ð¾Ð²Ð¸Ñ? Ñ╬Ñ'Ð¾ ÐµÑ?Ð»Ð¸ Ñ'Ñ< Ð½Ðµ Ð·Ð½Ð°ÐµÑ^ÑO Ð¿Ñ?Ð°Ð²Ð¸Ð» Ñ'Ð¾ Ñ?Ñ'Ð¾ Ñ'ÐµÐ±Ñ? Ð½Ðµ Ð¾Ñ?Ð²Ð¾Ð±Ð¾Ð¶Ð´Ð°ÐµÑ' Ð¾Ñ' Ð¾Ñ'Ð²?
 [2022-06-24 12:03:56][chat]: *** uglynosok joined team 2
@@ -1021,3 +1021,3 @@
 [2022-06-24 12:06:03][chat]: Industrialist: qeToast: qq
-[2022-06-24 12:06:03][chat]: nameless tee: Ð³Ð°Ð²Ð¾Ñ?ÑƒÐ½: Ð¥Ð¾Ñ?Ð¾Ñ^Ð¾, ÐµÑ?Ð»Ð¸ Ñƒ Ñ'ÐµÐ±Ñ? Ð´ÐµÐ¹Ñ?Ñ'Ð²Ð¸Ñ'ÐµÐ»ÑOÐ½Ð¾ Ð¿Ñ?Ð¾Ð±Ð»ÐµÐ¼Ñ<, Ð´Ð°Ð²Ð°Ð¹ Ð¿Ð¾Ñ?Ñ?Ð½ÑZ Ð¿Ñ?Ð°Ð²Ð¸Ð»Ð° Ð½Ð° Ñ?ÑƒÑ?Ñ?ÐºÐ¾Ð¼. Ð¢ÐµÐ±Ðµ Ð²ÐµÑ?ÑO Ð¿ÐµÑ?ÐµÑ╬ÐµÐ½ÑO, Ð¸Ð»Ð¸ ÐºÐ¾Ð½ÐºÑ?ÐµÑ
+[2022-06-24 12:06:03][chat]: nameless tee: Ð³Ð°Ð²Ð¾Ñ?ÑƒÐ½: Ð¥Ð¾Ñ?Ð¾Ñ^Ð¾, ÐµÑ?Ð»Ð¸ Ñƒ Ñ'ÐµÐ±Ñ? Ð´ÐµÐ¹Ñ?Ñ'Ð²Ð¸Ñ'ÐµÐ»ÑOÐ½Ð¾ Ð¿Ñ?Ð¾Ð±Ð»ÐµÐ¼Ñ<, Ð´Ð°Ð²Ð°Ð¹ Ð¿Ð¾Ñ?Ñ?Ð½ÑZ Ð¿Ñ?Ð°Ð²Ð¸Ð»Ð° Ð½Ð° Ñ?ÑƒÑ?Ñ?ÐºÐ¾Ð¼. Ð¢ÐµÐ±Ðµ Ð²ÐµÑ?ÑO Ð¿ÐµÑ?ÐµÑ╬ÐµÐ½ÑO, Ð¸Ð»Ð¸ ÐºÐ¾Ð½ÐºÑ?Ðµ?
 [2022-06-24 12:06:07][chat]: *** [D] ÐzÐ>Ð¯ joined team 1

```
