### ISSUE TITLE
Github reminders bot doesn't work

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#5518]
See #5221. I expected to get a reminder when the timer expires by the bot posting another comment or something to that effect.

**Comment by heinrich5991** [comment]
It'd be nice if the bot didn't spam the issue for everyone. Perhaps one could instead create a local calendar event instead?

**Comment by Robyt3** [comment]
The bot would be more convenient if it works, but if it doesn't do any reminders then we can get rid of it and use calendars or other reminder apps instead.

**Comment by Chairn** [comment]
Maybe we can try another reminder bot?

**Comment by def-** [comment]
Removed it
