### ISSUE TITLE
Restore possibility to determine freeze time without freeze bar

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#5527]
It used to be visible via the stars. After the stars got replaced by snow flakes that information got lost. I am not saying we need to mimic the old star movement exactly. And have 1000 snow flakes on a 1000 sec freeze time. But at least reduce it to 3, 2, 1 flakes in the end.

https://user-images.githubusercontent.com/20344300/176209886-4f472082-60fe-4b46-bdcb-5bfd263933b4.mp4

**Comment by C0D3D3V** [comment]
> After the stars got replaced by snow flakes
stars got replaced by freeze bar, so the information is not lost.

**Comment by Robyt3** [comment]
#8934 added an option to reenable the stars.
