### ISSUE TITLE
No freeze bar on rc7 and latest master

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet#5534]
With opengl 3.3 on ubuntu18. Also reported by Pastoer on discord.

**Comment by C0D3D3V** [comment]
Are you sure you was on a latest server?

**Comment by Chairn** [comment]
No, just saw it depends on server...
So the client needs at least to show it either everytime (why does it depend on server info?) or show stars in place of freeze bars.

**Comment by Chairn** [comment]
I think my point still stands, new client needs to show freezebar or stars even on old protocol that may be used by other mods.

**Comment by C0D3D3V** [comment]
old server send stars...

**Comment by Chairn** [comment]
hum, it doesn't? Or the client doesn't display them.

**Comment by C0D3D3V** [comment]
all official releases that are older then 16.2 send stars

**Comment by Chairn** [comment]
ok, so it was only ddnet server rc5 or 6 not showing neither freeze bar nor stars
