### ISSUE TITLE
Disable CI on data folder

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet#5543]
Disable CI runs on commits that only changes data folder, i.e. images or language files as these do not change the code.

This reduces *slightly* energy consumption.

**Comment by heinrich5991** [comment]
I'm not sure if it's worth it, but if we do want to do it, please do it in bors:

> [11:10 PM] heinrich5991: anyway. if you want to optimize the energy usage of the CI, I think it'd be best to allow bors to delay merging a PR until an important one comes around

**Comment by def-** [comment]
We don't notice failures in data files and failure to list them in CMakeLists.txt then.

I don't think it's worth it. On Discord you estimated a total 30 kWh to run CI on all our changes so far. Companies probably pay ~10 ct/kWh. So the energy consumption is worth ~ 3 €.

**Comment by Chairn** [comment]
Money doesn't matter (its not even ours anyway).

**Comment by def-** [comment]
If you want to save energy, find a better way to set defaults for lower CPU/GPU usage for DDNet client while keeping game play good.

If it takes you 1 hour to implement the change, you could have a larger environmental effect by working for 1 hour and donating that money.

**Comment by Chairn** [comment]
Looks like consensus is on not disabling CI for data folder.
