### ISSUE TITLE
16.2 Client black screen when connected to VPN

### ISSUE THREAD

**Issue by Kruimeldief** [ddnet/ddnet#5555]
I updated my DDNet client from 16.1 to 16.2 using the in-game update button and now the game won't start anymore. After the update (downloading new files), the client restarted itself and gave a black (full)screen. When clicking, the 'DDNet.exe is not responding' Windows pop-up appears after which I need to close the program. When restarting DDNet, the same black screen appears.

<img width="272" alt="image" src="https://user-images.githubusercontent.com/55532712/177303996-01061ae6-8d23-4e8a-8926-6d3dd431a82b.png">

Edit: ticket #5555 💪

**Comment by def-** [comment]
Does it work with the version from ddnet.tw directly?

**Comment by Chairn** [comment]
Can you post the crash log? It should be in data/dumps.

**Comment by Kruimeldief** [comment]
> Does it work with the version from ddnet.tw directly? If you download it again.
The same happens when downloading DDNet-16.2-win64.zip after unzipping it.


> Can you post the crash log? It should be in data/dumps.
> 
> Okay, there might be none if it is closed by Windows through a signal.
I can't find a file or folder named dump in the data folder. Neither in the original (in-game updated) game folder nor in the newly downloaded unzipped game folder.

**Comment by Kruimeldief** [comment]
I think I have found the problem. I'm often connected to a NordVPN server including just now. I disconnected and Teeworlds works again. Upon reconnecting with a NordVPN server, Teeworlds shows a black screen again.

Is this a bug or intentional?

**Comment by Learath2** [comment]
@heinrich5991 could this have something to do with the pnglite flag thing?

**Comment by Chairn** [comment]
> I can't find a file or folder named dump in the data folder. Neither in the original (in-game updated) game folder nor in the newly downloaded unzipped game folder.

Default data folder is actually in %appdata%/teeworlds or %appdata%/ddnet.

**Comment by Kruimeldief** [comment]
> > I can't find a file or folder named dump in the data folder. Neither in the original (in-game updated) game folder nor in the newly downloaded unzipped game folder.
> 
> Default data folder is actually in %appdata%/teeworlds or %appdata%/ddnet.

Ah, didn't know. I have no crash RTP/txt files in there of today. Happy to send them from 2022-05-09 and 2022-03-30.

**Comment by Kruimeldief** [comment]
If it helps, I can exclude programs from the VPN connection. By excluding the program _Console Window Host_ **while** DDNet is running with the black (full)screen, I'm able to refresh the black screen and let it continue to the DDNet menu without a restart. However, this has to be done manually each time (remove and re-add from VPN exclusion list). I'm not too tech savvy but I think it's because a new instance of _Console Windows Host_ is used each time.

Previously (in client 16.1), all I hate to exclude was the DDNet.exe application itself.

**Comment by Learath2** [comment]
@Kruimeldief if you can alt tab out while it's black, could you check the console `cl_show_console 1` see what it's stuck on?

**Comment by Kruimeldief** [comment]
> @Kruimeldief if you can alt tab out while it's black, could you check the console (`cl_show_console 1`) see what it's stuck on?
> 
> If not we could log to a file instead but it's rather hard to guide someone to do that, so let's check the console first.

@Learath2 I don't understand what you're asking from me. I can't alt-tab out of the black fullscreen window (it stays on top). And there's no console (_command prompt_?) open. But I did create a _dump file_ of the non-responding DDNet application via the task manager. The _DDNet.DMP_ file is 17 GB and I'm unsure which program I need to view it.
<img width="555" alt="image" src="https://user-images.githubusercontent.com/55532712/177354890-69ecf25b-fed6-4bc2-a452-972eabee1608.png">

**Comment by Learath2** [comment]
> > @Kruimeldief if you can alt tab out while it's black, could you check the console (`cl_show_console 1`) see what it's stuck on?
> > 
> > If not we could log to a file instead but it's rather hard to guide someone to do that, so let's check the console first.
> 
> @Learath2 I don't understand what you're asking from me. I can't alt-tab out of the black fullscreen window (it stays on top). And there's no console (_command prompt_?) open.

If you set `cl_show_console 1` in your config there will be a console when you alt tab. You can refer to the wiki if you don't know where to find the config.

**Comment by Kruimeldief** [comment]
I added `cl_show_console 1` to the following files but still no console (no duplicate entries). Am I doing it right?
* `%appdata%\Roaming\Teeworlds\settings_ddnet.cfg`
* `%AppData%\Roaming\DDNet\settings_ddnet.cfg`

**Comment by heinrich5991** [comment]
I don't understand where the problem comes from, can you help me, @Jupeyy?

**Comment by Robyt3** [comment]
I can reproduce the black screen/infinite loop by using an incorrect `bindaddr` setting, e.g. by starting the client with `DDNet "bindaddr test"`.

Maybe we should limit this loop to a finite number of attempts and then crash with an assertion and also try resetting the `bindaddr` setting, so it doesn't hang the client indefinitely without an error message:

https://github.com/ddnet/ddnet/blob/040726ea712885eb766fda0a1c9d83c3ae142b29/src/engine/client/client.cpp#L3068-L3071

**Comment by Kruimeldief** [comment]
@Robyt3 The bug seems to be introduced in 16.2.x because 16.1 works fine and all later versions (including the current version) have the black screen bug. Sharing this because you wrote ...
> Though the original issue doesn't seem to be related to the bindaddr setting.
