### ISSUE TITLE
Wrong hook position in pause

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#556]
67ef49857382c78bc7834379d13065736a627d7b
when others drag me, in pause I see wrong destination hook position
![screenshot_2016-10-02_16-31-12](https://cloud.githubusercontent.com/assets/17499770/19020900/e47384b8-88bd-11e6-8747-b37acdcd9fa8.png)

**Comment by FallenKN** [comment]
caused by this commits https://github.com/ddnet/ddnet/pull/549

It also seems to display unpredicted tees even with antiping enabled.

**Comment by heinrich5991** [comment]
Do unpredicted tees show in spectator mode?

**Comment by BannZay** [comment]
Antiping was disabled

**Comment by FallenKN** [comment]
@BannZay looks the same with enabled antiping
