### ISSUE TITLE
No DDNet 16.2 tag on github

### ISSUE THREAD

**Issue by theofficialgman** [ddnet/ddnet#5565]
for Pi-Apps, we use the ddnet info page https://info2.ddnet.tw/info to obtain the current release of ddnet for our updater.
it is expected that the version on the info page corresponds to a github tag (as instructed by one of the contributors).

However, there is no 16.2 tag on the github. Please correctly mark this tag on github so that users can build this.

**Comment by def-** [comment]
Thanks, fixed.
