### ISSUE TITLE
Global static constants in `SCREAMING_SNAKE_CASE` or `gs_CamelCaseWithPrefix`?

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#5569]
CC https://github.com/ddnet/ddnet/pull/5545#discussion_r913644432.

`SCREAMING_SNAKE_CASE` mirrors preprocessor constants (making them easier to upgrade?), `gs_CamelCaseWithPrefix` makes it easier to distinguish from preprocessor macros (but makes it unclear that we're talking about constants).

**Comment by heinrich5991** [comment]
I prefer `SCREAMING_SNAKE_CASE`, makes it clear that it's a constant.

**Comment by Chairn** [comment]
SCREAMING_SNAKE_CASE should be reserved for "non symbol", i.e. defines and enum solely.

We can also add a `c` letter into `gsc_MyGlobalVariable` to indicate its a constant.

**Comment by heinrich5991** [comment]
You say "should". Why should it be reserved for "non-symbols"?

`constexpr int MAGIC_NUMBER = 0x503;`, `static const int MAGIC_NUMBER = 0x503` and `#define MAGIC_NUMBER 0x503` behave similarly, so to me it looks okay to have the same naming convention for them.

**Comment by Robyt3** [comment]
I agree with `SCREAMING_SNAKE_CASE` for all global static constants. Though we should avoid the preprocessor when possible in favor of const/constexpr.

**Comment by heinrich5991** [comment]
Seems like we're going with `SCREAMING_SNAKE_CASE`.
