### ISSUE TITLE
Higlight hack

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#557]
There is hacker. He just write something like "**\* Noob has left the game" and everyone gots duplicate of this message as from server (yellow letters)
![screenshot_2016-10-02_17-50-31](https://cloud.githubusercontent.com/assets/17499770/19021436/b10e3d5a-88c9-11e6-8fc2-2fa11d32bc92.png)

**Comment by Henningstone** [comment]
This is rather a spambot... Look at the console. He repeats all chat messages that comes in.

**Comment by BannZay** [comment]
info about "entered and joined the game" is fake. Nobody has connected, as he could fake disconnect messages

**Comment by east** [comment]
Some other player on the server simply faked your ingame nick using unicode:
`BannZay -> BannZaỵ` (not noticeable in Teeworlds)

 He reflected all chat messages on the server, that's it.

**Comment by def-** [comment]
Solution: That should be caught by our confusables detection.

**Comment by heinrich5991** [comment]
@deen: Can you elaborate?

**Comment by def-** [comment]
We should remove these weird small modifiers (the dot below the y) before running `str_utf8_is_confusable`. Not sure what they're called and where to find a full list of them. Similar to how we disregard empty whitespaces now.

**Comment by CytraL** [comment]
perhaps only allow ascii for nicknames and utf8 for everything else ?¿?? This is good too for use TAB feature for nick-completion xD because for example i can't write russian characters.

**Comment by heinrich5991** [comment]
Perhaps only allow Russian characters and disallow Latin ones? :P

**Comment by heinrich5991** [comment]
I.e. I think it is a bad idea to prefer one alphabet to the other, just because we're more familiar with the Latin one – or because the development of the computers took place in places dominated by the Latin alphabet.

**Comment by CytraL** [comment]
hahahaha yeah i know... but is the most used standard :/ can use "extended ascii"... other with the same "codepage" can see the correct symbols.. no? perhaps i'm wrong... 
http://www.ascii-codes.com/cp855.html
