### ISSUE TITLE
Allow to show ghosts even when map hash does not match

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#5577]
Since we add to every map time checkpoints, and sometimes change little things or add chill areas, it would be nice that players could still use there old ghosts.

Requested by teini94 on Discord 
```
I mean u could mark ghosts who has the exactly same hash as the corrent map
```

**Comment by Chairn** [comment]
What happens when a modification changed a part?

**Comment by C0D3D3V** [comment]
We would just render the ghost inside blocks, if that really happens. But that is rare, and probably better than not beeing able to show old ghosts? Ghosts do currently not interact with the world. I see only one problem, for ghosts on test maps, where you change the map often, and maybe finish it multiple times inbetween. So it could be an option in the ghost browser to also show ghosts with wrong hash. 

(As a side note I also did not add freeze effect to ghosts, but instead record them as a ninja as before. That could also be chenaged one day)

**Comment by teini94** [comment]
maybe a command to disable ghosts on Test Servers

- also ghost limit is like 18~ I think ,then it doesnt show more.
- also ghosts will not show up with the same time, and/or those (same time) ghosts disappear when u disconnect.

If people know the tricks to get more as 1 ghosts.
