### ISSUE TITLE
Show Practice Indicator in Scoreboard for teams that are in practice

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#5579]
Requested by teini94 on Discord
```
so its harder to fake , epic server laggs or world records or something
```

**Comment by Chairn** [comment]
I don't really understand. Harder to fake server lags?

**Comment by C0D3D3V** [comment]
No Idea what he meant with that, he was probably refering to the lacer bounce bug you could create by teleporting in blocks and create lags. So with the indicator in scoreboard, you could notice that faster? and change server.

**Comment by C0D3D3V** [comment]
Since we now also display super as text in scoreboard, I think it is fine to show practice too as text. Or do we want to use a symbol?

**Comment by Chairn** [comment]
The same that we have in the hud?

**Comment by C0D3D3V** [comment]
duplication of https://github.com/ddnet/ddnet/issues/2223
