### ISSUE TITLE
Dummy needs to log in to rcon separately

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#5586]
Just a minor annoyance I noticed whilst testing some maps yesterday :)
fokkonaut mentioned this problem in issue #4721. 
Can this be fixed or is there a concern im not aware of?

Edit: Linked wrong issue, oops!

**Comment by C0D3D3V** [comment]
You are probably on an old server version or client version. I cannot reproduce this on a latest master server/client

**Comment by C0D3D3V** [comment]
How can you join with dummy first o.O
