### ISSUE TITLE
Server executable not found, can't run server (when installed with the server on linux)

### ISSUE THREAD

**Issue by theofficialgman** [ddnet/ddnet#5594]
Compiling DDNet and DDNet-Server from source (through mostly default cmake commands) to /usr/local. Clicking DDNet Server in the GUI errors that it can't find the executable

The executable is in the default path:
```
file /usr/local/bin/DDNet-Server 
/usr/local/bin/DDNet-Server: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=f46454191f32e7a06fdbd0732c372c75dfb4f89b, not stripped
```
```
file /usr/local/bin/DDNet
/usr/local/bin/DDNet: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=c9cded2570feda9a76614c15c62ce34ee35bc5b1, not stripped
```

the server does start if I manually execute it from terminal

**Comment by C0D3D3V** [comment]
You also get this error using the AUR build. I always thought the server gets not installed with the AUR package, but probably it does not look into the path.

**Comment by theofficialgman** [comment]
@def- I see this has been fixed according to the commit history
could this be picked to the 16.X.X series. I don't know how long you plan on waiting before a 17.X is released with the many changes from master

**Comment by def-** [comment]
This is not a regression in 16.2, so I didn't pick it to 16.2 branch.
Usually we release a new major version every ~6 weeks.
