### ISSUE TITLE
LookupHost test fails without internet connection

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5595]
I don't think our unit tests should depend on internet connection, it just hangs, using 100% CPU:
```
[ RUN      ] Jobs.LookupHost
[2022-07-09 11:25:20][host_lookup]: host='example.com' port=0 11
^C
```

**Comment by heinrich5991** [comment]
The lookup doesn't have a timeout? Perhaps we found a bug?

**Comment by def-** [comment]
I think lookups don't have a timeout, at least I waited a few minutes and only noticed it because my fan sped up a lot in that time. I guess normally it's not too bad because we don't busy-wait.

**Comment by Chairn** [comment]
Hmm, when i worked in the train with no connection active, it failed immediately.

**Comment by Robyt3** [comment]
References:

- the problem with `getaddrinfo`: https://skarnet.org/software/s6-dns/getaddrinfo.html
- the problem with `libresolv`: https://skarnet.org/software/s6-dns/libresolv.html
- s6-dns: https://skarnet.org/software/s6-dns/index.html

**Comment by Chairn** [comment]
Fixed by https://github.com/ddnet/ddnet/pull/5996
