### ISSUE TITLE
Deprecated crypto code

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#5597]
src/base/hash_openssl.cpp:23:2: warning: 'MD5_Init' is deprecated [-Wdeprecated-declarations]
src/base/hash_openssl.cpp:17:2: warning: 'SHA256_Final' is deprecated [-Wdeprecated-declarations]
src/base/hash_openssl.cpp:11:2: warning: 'SHA256_Update' is deprecated [-Wdeprecated-declarations]
src/base/hash_openssl.cpp:6:2: warning: 'SHA256_Init' is deprecated [-Wdeprecated-declarations]

**Comment by heinrich5991** [comment]
Theoretically part of #5548, but I guess it's fine to have an issue about these warnings specifically.
