### ISSUE TITLE
Feature request: Dummy-aware spectating

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#560]
Would be cool if switching between spectating a player and his dummy happened automatically. That is to say, the tee the screen is following is always the tee that is currently being controlled by the player, whether it's the "primary" or the "dummy".

The functionality should probably be a console config variable (defaulting to enabled), in case for some reason it's not desired. If you wanted to get fancy it could be a checkbox in the select-player-to-spectate menu (right shift)...

**Comment by timakro** [comment]
Might be something for the DDNet network character #392 by HMH.

**Comment by def-** [comment]
I don't think we should add more dummy support.
