### ISSUE TITLE
Overhaul UI layout/sizing

### ISSUE THREAD

**Issue by kaitlynia** [ddnet/ddnet#5605]
Whaddup nerds. You took my sacred ui_scale setting away so now I am forced to do the last ounce of whining I am even comfortable doing by addressing an existing issue with UI.

Elements are not resized for smaller resolutions. Some components like the "Refresh" button can be replaced with an icon (credit @Learath2 for the idea) or simply adjusted with a bit of font nudging and margin/padding adjustments. This is the most problematic on 5:4 resolutions but I believe 16.2 to be the best version for showing the UI's constraints. For example in this screenshot on 5:4, the Refresh button (if changed to an icon) could be resized so that there is still reasonable margins around the components, preserving the separation and clarity present on 16:9 resolutions
![image](https://user-images.githubusercontent.com/38897710/178139562-bd7ee628-83a0-4dd1-be08-d01134874ae8.png)

I rq talking about ui_scale I guess unless people think this stuff is worth doing anyway

**Comment by Robyt3** [comment]
Would be fixed by #5878.
