### ISSUE TITLE
Discussion about freezebar improvements

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#5607]
This issue should be just a container for all suggestions (also from discord) and room for discussions about them. So you dont have to search them in discord.

**Comment by C0D3D3V** [comment]
One idea I just came up with: We could use the weapon cursor as freeze bar/cirlce. Or maybe not directly the cursor but a circle around it.

**Comment by Chairn** [comment]
2 parts? I thought people wanted to have different line ending for start and end, so that would need 3 parts (left or end, middle, right or start)

**Comment by C0D3D3V** [comment]
With 2 Parts I mean a full version of the bar and an empty version, instead of only having half of each.

**Comment by VoxelDoesCode** [comment]
> One idea I just came up with: We could use the weapon cursor as freeze bar/cirlce. Or maybe not directly the cursor but a circle around it.

This sounds better for a weapon reload timer than a freeze timer, since it's linked to the weapon's cursor.

**Comment by heinrich5991** [comment]
Freezebar is already implemented.
