### ISSUE TITLE
Add a "Getting Started" document for new developers

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#5610]
That contains our business rules, like naming of variables: https://github.com/ddnet/ddnet/issues/2945
And useful information like how to use `formatting-revs.txt` https://github.com/ddnet/ddnet/pull/5604 or a general overview of our code architecture.

**Comment by def-** [comment]
That should just be in the README

**Comment by edg-l** [comment]
check out https://wiki.ddnet.org/wiki/Development

**Comment by C0D3D3V** [comment]
I guess  https://wiki.ddnet.org/wiki/Development should be linked in the Readme

**Comment by Robyt3** [comment]
> That contains our business rules, like naming of variables

> a general overview of our code architecture.

Already described in https://wiki.ddnet.org/wiki/Development.

> I guess https://wiki.ddnet.org/wiki/Development should be linked in the Readme

Done.

> And useful information like how to use formatting-revs.txt

Done.

Anything else or can this issue be closed?
