### ISSUE TITLE
Kill messages don't work with sixup

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#5623]
Join a DDNet-Server with teeworlds client at current master and execute `kill`. It does not show the kill message in teeworlds but it works in DDNet client.

**Comment by Robyt3** [comment]
Looks like this was intentional, as we send the `RACEFLAG_HIDE_KILLMSG` flag, which hides all kill messages when `GAMEFLAG_RACE` is set.

https://github.com/ddnet/ddnet/blob/3c6402830d0792d285852f5cd1159c7e4d558017/src/game/server/gamecontroller.cpp#L633

But the DDNet client displays the kill messages so this is inconsistent. Which is correct then? Should kill messages be shown or hidden for all clients?

**Comment by C0D3D3V** [comment]
but teeworlds uses the killmessage area to display finish times. We could do the same. If we want to display kills at all is an other question.
