### ISSUE TITLE
Do we want to add the move to vector commits to formatting-revs.txt? 

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#5629]
![grafik](https://user-images.githubusercontent.com/14315968/178710512-639688b7-cb33-4a9f-b1f2-cd16de2216cb.png)

80103888eae2fb8a9fd70ab0d7cd596b3ba39e22
0f097a0490bc711a1354df2516b6bebbfa095c93
d3eb9d6fe7d3777b23985063312410ef80fbe00a
24ad383211dc98e1c1886c054c604566a1561b77
ce54a0d07506f9c0b374d035fe5e8036bbac6c96
4a023342b7c3445874644c8c094458f177b04069
c6e195a39963874d4ba0d838dea58676de4f28eb
3f8fb732a38986cfaee06fc10312875fe7111582
0c69495522877ff44b60ebb6cdad14067c1c70c3

Or because they do change the behaviour not?

**Comment by C0D3D3V** [comment]
... forget my list above they are way to split up.

**Comment by Chairn** [comment]
I guess there's also my vector formatting name commit:
https://github.com/ddnet/ddnet/commit/01edaec628ec325d47d74a667ccaa2aed43f30c9 (already added)
https://github.com/ddnet/ddnet/commit/c9345e7d3

**Comment by def-** [comment]
switch to vector is not a pure formatting change, but also changes behavior.
