### ISSUE TITLE
Using `play` to play demo files doesn't work when first launching the client

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#5645]
When launching the client with `DDNet "play demos/my.demo"` command line it doesn't play the demo when the client finishes loading and instead the following error is shown in the console:

```
[demo_player]: playing passed demo file 'play demos/my.demo' failed: error opening demo file
```

If you type the same command `play demos/my.demo` into the console it plays the demo.

Would be nice if the `play` command also works on the initial start for integration/fuzz testing.

**Comment by Chairn** [comment]
Looks like it tries to look for a file named "play demofile"

**Comment by Robyt3** [comment]
Ah, it just expects the demo file without the `play` command. But when I launch with `DDNet demos/my.demo` instead it still fails with

```
[demo_player]: playing passed demo file 'demos/my.demo' failed: error opening demo file
```

Looks like it's always considering the given path as an absolute one. As a workaround I can pass the absolute path. But it would be preferable if it also looks for the demo in the storage.

**Comment by Chairn** [comment]
So we just need to add argv[0] to path passed through command line?

**Comment by Robyt3** [comment]
We need to check whether a path passed through command line is relative or absolute. I don't think there is a system method for that yet. 

Then we need to pass the correct storage type in

https://github.com/ddnet/ddnet/blob/a93dac515626b8527ae047d4299b96c1eda0ee8f/src/engine/client/client.cpp#L3204

and

https://github.com/ddnet/ddnet/blob/a93dac515626b8527ae047d4299b96c1eda0ee8f/src/engine/client/client.cpp#L3213

Or we don't check for absolute/relative path and instead just try the other storage type if one fails.
