### ISSUE TITLE
Inputs while speccing and GAMEINFOFLAG_BUG_DDRACE_INPUT

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#5652]
From what I can see, this flag is used to tell the client not to send inputs while specinfo is active, and that it should not reset inputs while chat is opened.
I dont send this flag on my server to be able to use "click to spectate" feature from 0.7 because it's very helpful and intuitive.
Is there a way we could send inputs while specinfo is active without losing the ability to set inputs to "hold" when using chat or /pause? Maybe a separate set of input data, used for spectating?

**Comment by Chairn** [comment]
Any info on why you closed this issue?

**Comment by fokkonaut** [comment]
Cuz I worked a way around it now, I dont think this really is worth it maybe.

**Comment by C0D3D3V** [comment]
No it is the other way around. On teeworlds you can not send inputs if you are in spec. But in ddnet you can if this flag is set.

**Comment by fokkonaut** [comment]
Exactly the other way around.
