### ISSUE TITLE
Feature proposal to redirect player to another server

### ISSUE THREAD

**Issue by Rei-Tw** [ddnet/ddnet#5662]
Hi,

After discussing with @murpii about multeasymap and funvoting issues, is it possible to implement a new feature to redirect a player to another server ?

It could be for example a tile that may contain the information of the fqdn or IP and the port of the server you want the player to join.

As an example for multeasymap, you could move people that frequently use the block part of the map to a server where voting each other is deactivated.

I don't know if such a feature is useful for DDRace in general, but this could even be useful for new gamemodes that might be DDNet based.

**Comment by murpii** [comment]
~~Perhaps only allow redirects to a server within the same Network, to avoid people from adding this tile in secret and malicious intend.~~

Edit, 4 years later: This should probably be a map specific server configuration.

**Comment by fokkonaut** [comment]
Yes, it should only allow moving players to a server with the same ip, but a different port.

**Comment by Learath2** [comment]
Same ip having to be hardcoded into the map sounds a little annoying to manage. Instead I propose servers send the clients a list of allowed redirect destinations. So malicious mappers can't redirect outside of the ips (or fqdns) the hoster allows.

**Comment by Rei-Tw** [comment]
Main issue of my example and idea (using a tile) is about data size ? (lets imagine fqdn is very long). Maybe this can be fixed by using some sort of tags that can be configured server-side, and then a specific packet is sent to the client asking him to switch server.

**Comment by heinrich5991** [comment]
This would first be a client feature that the server can trigger.

Then we can think about how to integrate it into a map

**Comment by Learath2** [comment]
The bigger question is what sort of issues can the ability to redirect a client to a server they might not want to connect to create.

How will we handle redirection loops? How about an unreachable destination? Is there actual security concerns with this given the server could just as easily proxy the connection and you wouldn't know any better?

**Comment by Rei-Tw** [comment]
Using a proxy could work aswell and doesn't even require a client-side modification. But still requires a tile to trigger a map change. Actually both methods could work (proxying or simple way to ask client to disconnect & connect to the other server).

What do you mean by "redirection loops"? Do you mean if someone is having fun mapping the connect tile on a spawn position ? For that I guess only some map analysis can be done (maybe ?).

For unreachable destination maybe client can be connected back to the original server if there is a timeout.

**Comment by heinrich5991** [comment]
The tile is a red herring. Let's discuss the actual protocol first.

**Comment by ChillerDragon** [comment]
Should there be user choice? Like the server is offering the client to redirect. The user is shown the ip and can click yes or no.

**Comment by Learath2** [comment]
> Should there be user choice? Like the server is offering the client to redirect. The user is shown the ip and can click yes or no.

This would certainly be better but it really reduces the utility of the tile as a tool of isolation. Blockers just won't accept the redirect and stay on the current swrver where they can annoy more people

**Comment by heinrich5991** [comment]
> Should there be user choice? Like the server is offering the client to redirect. The user is shown the ip and can click yes or no.

I don't see what user choice is adding here. The server can simply kick the client if it wants to redirect it. The safety of the redirect should not depend on the user being able to decide it.

**Comment by fokkonaut** [comment]
What about those proxy servers we had before, where you think you are on the real server while you are connected to a different one, that reads all your traffic?
Thats why I was thinking, lets just send a port, so the client takes the current address and just tries to connect to a different port on that address.
Should solve all usecases we need this for

**Comment by sjrc6** [comment]
Are there really any malicious implications for this if you already trust the server before you connect to it? A what benefit does a malicious server have sending you to a different malicious server? It would be cool for making events on server networks since you could create an optional redirect to the event/tournament server(s).

**Comment by Kaffeine** [comment]
The protocol feature allowing to move a client to another server sounds great, I think about this for a while (like: years).
What can we do with that feature:
- Move the clients to another server on shutdown
- Continuous maps (finished one map => joined to the server with the next part; I see drawbacks here but I also see benefits)
- Load balancing

A 'cookie' or 'opaque id' might be useful as well — to restore the player/character state on the new server.

A reconnect command (making the client reconnecting to *this* server) would also help.
After commit https://github.com/ddnet/ddnet/pull/4431/commits/d832800ebc3395e31b35d37b4aa80b1ef2dce9cd "my players" see "Update installed, please reconnect" message on the server updated. The startup takes an half of a second but the players connect seconds later and some just do not reconnect.

**Comment by heinrich5991** [comment]
Fixed by #6914.

**Comment by murpii** [comment]
@heinrich5991 Is this really "fixed"? It isn't a bug but a feature proposal. The foundation may be there, but it's currently unused and doesn't support what was actually proposed.

**Comment by ChillerDragon** [comment]
> @heinrich5991 Is this really "fixed"? It isn't a bug but a feature proposal. The foundation may be there, but it's currently unused and doesn't support what was actually proposed.

fyi there is an open follow up issue to extend the protocol https://github.com/ddnet/ddnet/issues/7480

But yea there is no way to trigger a redirect in a vanilla ddnet server but the client supports it for custom servers.
