### ISSUE TITLE
Editor tab hotkey buggy

### ISSUE THREAD

**Issue by saltyElefant** [ddnet/ddnet#5669]
As of version 16.2 the tab hotkey to show the map fullscreen often fails to respond.
OS win10 64bit.
Client versions tested: 16.2.2 non steam released and DDNet-16.2.2-20220729-win64

**Comment by Robyt3** [comment]
As anticipated, eb7e210fc1ec76192dcb62f7ef9cad7b7c5ee6b6 (#5428) is the first bad commit.
