### ISSUE TITLE
Remove or use CFlag dead code

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#5677]
[src/game/server/entities/flag.cpp](https://github.com/ddnet/ddnet/blob/192c7b2bb0a21b9015abe936af6fc0de16dcc539/src/game/server/entities/flag.cpp) and [src/game/server/entities/flag.h](https://github.com/ddnet/ddnet/blob/192c7b2bb0a21b9015abe936af6fc0de16dcc539/src/game/server/entities/flag.h) are entirely commented out. We shoud either remove this dead code or make it work again.

**Comment by C0D3D3V** [comment]
We have on multiple places dead code. I guess that was done to keep the diff with upstream small. For example we also have dead code for pickups, we commented out there the respawn timer (at least I remember it like that).

But I also think that it would be good to remove dead code. If someone needs that code he can look into the history, or look at upstream.

**Comment by C0D3D3V** [comment]
I just checked, the dead code for pickups was already removed.
