### ISSUE TITLE
1.5x demo speed

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#568]
Title says it all. For slower speeds, there are 0.75x, 0.5x, 0.25x, 0.1x, etc. speeds. 1.5x would be very nice to have added.

Also, there's an issue where it sometimes speeds up/down an extra notch. To clarify, instead of slowing down from 1x to 0.75x, it would go down from 1x to 0.5x instead, or 0.5x to 0.1x instead of 0.5x to 0.25x. Similar with speeding up. Please fix this.

**Comment by FallenKN** [comment]
so you want speed steps? +- 0,25x; 0,5x and so on?

**Comment by PathosEthosLogos** [comment]
I'm not sure what you're asking.

My first point was a suggestion to have 1.5x demo speed available. Currently, the demo viewer jumps from 1x to 2x.

My second point was a bug report where when I use mousewheel down to slow the demo down, it sometimes registers twice (maybe?). So, when it's supposed to slow down from 2x to 1x, it goes down from 2x to 0.75x instead. Similar for speeding up.
