### ISSUE TITLE
Freezebar behaves weird after using spec

### ISSUE THREAD

**Issue by Vy0x2** [ddnet/ddnet#5685]
The freeze bar behaves very weird when you do following steps:

1. Jump into freeze and land on a block
2. /spec
3. Wait some seconds
4. /spec

-> The remaining freeze bar is very small but you are still frozen for ~2 seconds

![de1e459165 1](https://user-images.githubusercontent.com/24738662/182042086-039c0f14-b5b9-4b92-a870-dd4aa7e311d8.png)
In this picture i was still frozen for 2 seconds

**Comment by Chairn** [comment]
How are you still frozen in a non freeze block?

**Comment by C0D3D3V** [comment]
Ah yes thanks for reporting, I forgot abour it :D I have seen that too, but I have forgotten to fix it.

**Comment by Robyt3** [comment]
Can't reproduce, works fine for me.

**Comment by Robyt3** [comment]
> /spec remembers your freeze duration.

Not for me.

**Comment by Vy0x2** [comment]
I may not be the best at explaining, so two videos:

https://user-images.githubusercontent.com/24738662/189230400-13d29a2f-a92f-469a-8216-b4e9cd0357e2.mp4

^ Here i was 2 min in spec and the freeze bar is tiny and you cant estimate the time left
@Robyt3 

---

https://user-images.githubusercontent.com/24738662/189230487-0fc809f5-6c73-4f00-910a-d3fb4bd68210.mp4

^ This looks like normal behaviour, i was a under a second in spec

**Comment by Robyt3** [comment]
Can you share the demo or a server with the bug? I can't reproduce it on servers with default configuration. When I enter /spec, I can still see my character and it's freezebar behaves normally, whereas your character seems to be hidden while in /spec. As far as I can tell the freeze duration is only remembered on servers where your character is hidden when you enter /spec. But I can't find a server that exhibits this behavior and also has freezebars enabled.

**Comment by Robyt3** [comment]
Okay, found it. It only happens with `sv_pauseable 1`.

**Comment by Robyt3** [comment]
Looks like a server issue. The `m_FreezeStart` that the server sends stays the same after leaving spec-pause, so the client thinks that the maximum freeze duration is larger than it actually is. Want to take over @C0D3D3V? I'm not familiar enough with most of this server code.

**Comment by C0D3D3V** [comment]
Yes I can fix it... I can do it in the next days...

**Comment by devdenn** [comment]
@C0D3D3V ?

**Comment by Vy0x2** [comment]
@C0D3D3V reminder

**Comment by Vy0x2** [comment]
fixed by #8150
