### ISSUE TITLE
Auto deleting demos that are "X" seconds or shorter length

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#569]
In the demo browser maybe next to the delete button, please add a text box where we can add the number of seconds (let's say I put in 5) and click delete, it deletes all demos shorter than 5 seconds.

Of course, the danger of using this is some of the race mod demos, where some runs can be shorter than 3 seconds, so perhaps the default can be 2.5 seconds.

**Comment by FallenKN** [comment]
better would be to not save those at all

**Comment by PathosEthosLogos** [comment]
Yes, that would be better.
