### ISSUE TITLE
Live chat translator

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#570]
https://www.teeworlds.com/forum/viewtopic.php?id=11588

Please add this to the client!

**Comment by H-M-H** [comment]
Not sure if this is a good idea as we probably need to call some google apis then.

**Comment by xushWT** [comment]
I am not using google, but some open api. See https://github.com/AllTheHaxx/AllTheHaxx for a cleaner implementation.

**Comment by necropotame** [comment]
I think it's a bad idea to have this in DDNet client because we should not rely on any kind of external API. Open or not (you seems to use mymemory.translated.net), the service could stop at any time or change it's API or conditions.

**Comment by Learath2** [comment]
Don't think we'll be implementing this.
