### ISSUE TITLE
Tune server command doesn't list tune settings in server console

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet#5711]
Basically title, server console suggests basic commands but not second entry for the tune commands, ~~and maybe as well for other commands to list possible values or min/max values just like the client console does.~~ (never mind it does for basic commands)

**Comment by Robyt3** [comment]
I can port https://github.com/teeworlds/teeworlds/pull/3120 and https://github.com/teeworlds/teeworlds/pull/2463.

Suggesting maps (https://github.com/teeworlds/teeworlds/pull/3041) would first require the necessary backend (server sending maplist in a throttled manner to authed clients).

**Comment by Chairn** [comment]
Sending maplist might be a security risks if we allow to explore all the disk using relative path going up (`..`).

https://github.com/teeworlds/teeworlds/pull/3120 is exactly what is needed to solve this issue :).

**Comment by Robyt3** [comment]
> Sending maplist might be a security risks if we allow to explore all the disk using relative path going up (..).

It wouldn't allow enumerating the maps dynamically. The server just scans the maps directory on start and then sends that list to authed clients. Vanilla also has a setting to configure the maplist sending, so either none, all, or only standard maps are send to the client.
