### ISSUE TITLE
Envelopes teleporting back and forth

### ISSUE THREAD

**Issue by Patiga** [ddnet/ddnet#5716]
On the map "Iris" the clouds teleport back and forth on the Vulcan backend

https://user-images.githubusercontent.com/44099679/183625118-ca43f324-abb8-40e1-9656-7adb5875b8d9.mp4

The envelopes seem harmless and smooth:

![2022-08-09-121738_1739x226_scrot](https://user-images.githubusercontent.com/44099679/183625178-ef46bacd-6fc6-4dc2-9b75-fda52c5b48f6.png)
![2022-08-09-121752_1738x225_scrot](https://user-images.githubusercontent.com/44099679/183625185-9ca8c35f-90ee-4e12-9a52-6031ca98b3a7.png)

Looking closely, you can see that the clouds sometimes get smaller/bigger while teleporting.

After bisecting, the bad commit is 53cb36bbe711dab1b333da7173deae94e46ba5f4
@Jupeyy your expertise :)

**Comment by Chairn** [comment]
Could almost be a feature :D

**Comment by Patiga** [comment]
Yes, sounds good :)
Negative alpha values can easily happen in envelopes, I would've guessed that this happens in a lot more maps
