### ISSUE TITLE
/top5timecp 1-25

### ISSUE THREAD

**Issue by teini94** [ddnet/ddnet#5739]
After ddnet added so many timecps why not use them even more.

Add a command to see how fast players reached each checkpoints
for example /top5 timecp1 (so u know if the fastest players did use that way for the his best time.) 
also /showtimecp name so it shows his times for timecps 1-25
so u can compare with ur time

**Comment by def-** [comment]
I don't think it fits well ingame. You can use `/timecp` to compare your times when racing against another player's. We could show the time cps on website maybe.

**Comment by teini94** [comment]
I think we arent useing f1 great
there is some potential - u can just make it so , it gets pushed up into ur f1 and it could be a great view 
like 
______________________________
|Name     | cp1   | cp2 |cp4 cp5
|Carl        |  25.4 |        |
|teini       |  25.3  |       |

**Comment by Chairn** [comment]
I think we need a real race interface where people can explore time cps and top5 correctly.

**Comment by Robyt3** [comment]
Included in #6825.
