### ISSUE TITLE
Minor Ghost rework

### ISSUE THREAD

**Issue by teini94** [ddnet/ddnet#5740]
After ddnet changes so many maps it only would be fair to renable old ghosts on the same maps(names) 
like HDP_OnOff_hash_235oöaesdfj.ghost
via the same hashes

while on it
- also let people be able to Create Ghosts themselves?
button to create a Ghost even if its not ur best time
(there can also be better ghosts if u finished with the same time I think)

- u may wanna mark these old ghosts now in ESC -> Ghosts with an Icon if they are not from the most current version

**Comment by C0D3D3V** [comment]
I guess this is the better issue instead of  #5578 so we can close  #5578

**Comment by C0D3D3V** [comment]
Eh, I meant  #5577
