### ISSUE TITLE
Disable new "debug infos" in PVP

### ISSUE THREAD

**Issue by teini94** [ddnet/ddnet#5741]
it doesnt help and its only in the view in pvp (like u do with zoom) , where u need to see the full screen
so u dont have to turn it On and Off all the time.

- position
- speed
- angle 
(may disable dummys)

**Comment by heinrich5991** [comment]
I'd delegate that to the player and let them turn it on and off. Zoom is only turned off in PvP because it's considered unfair.

**Comment by teini94** [comment]
would Suggest a Command like sv_pvp 1 so those things which are only in the way can be disabled on wish?

**Comment by heinrich5991** [comment]
You can make a PvP bind by binding the config options you'd like to have on a key.

`bind q "debug 0; cl_nameplates 0; …"`.
