### ISSUE TITLE
folders in demo directory dont show in browser

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5752]
> folders in demo directory dont show in browser

reported by louis for nightly

Might be Windows only, I can't reproduce on Linux. Might be related to https://github.com/ddnet/ddnet/pull/5750 @Patiga

**Comment by Robyt3** [comment]
Looks like #5750 used logical or `||` whereas it should be using bitwise or `|`.

**Comment by Patiga** [comment]
Ouch, good catch

**Comment by Robyt3** [comment]
What about symlinks to files on linux? They probably get shown and opened as directories now also.
