### ISSUE TITLE
Allow multiple connect addresses to LAN-Server

### ISSUE THREAD

**Issue by Zoozti** [ddnet/ddnet#5762]
commit 8996d152abe1eef489e6457617ef7df5f64e0765
heinrich5991 <heinrich5991@gmail.com>
Wed Jun 1 12:09:22 2022 +0200

That commit broke the possibility to connect to LAN-Server via leaving IP-field empty or write anything in it like "localhost".
That creates the problem that LAN-Server wont automatically reload itself when the current map is saved with a new version. This feature is incredible usefull for mappers and especially parts you have to test tile by tile

**Comment by Zoozti** [comment]
@heinrich5991

**Comment by heinrich5991** [comment]
Can you give steps to reproduce? I started a server locally on port 8303. I typed "localhost" into the connect box and pressed enter. I connected to the server successfully. The same also worked for "127.0.0.1", "[::1]", "localhost:8303", "127.0.0.1:8303", "[::1]:8303" and also using the console's "connect" command.

**Comment by Zoozti** [comment]
> Can you give steps to reproduce? I started a server locally on port 8303. I typed "localhost" into the connect box and pressed enter. I connected to the server successfully. The same also worked for "127.0.0.1", "[::1]", "localhost:8303", "127.0.0.1:8303", "[::1]:8303" and also using the console's "connect" command.

After restarting everything and also updating to 16.3.1 connecting to localhost works again and also the automatic reload after saving file.
But why was it changed that leaving IP Field empty will lead to lan server? Wont work anymore

**Comment by heinrich5991** [comment]
Bug can't be reproduced anymore, closing.

> But why was it changed that leaving IP Field empty will lead to lan server?

Accidental change, the empty string is interpreted as "no servers to connect to". I don't find that worth fixing.
