### ISSUE TITLE
[Steam] Mac Problems

### ISSUE THREAD

**Issue by M0REKZ** [ddnet/ddnet#5764]
The game won't start when running from steam, so i tried to run directly ddnet from terminal, and i see that its searching for a non-existent "libpng16.16.dylib", it look like a lib was forgotten.

**Comment by def-** [comment]
Thanks for the report, let me check.

**Comment by def-** [comment]
Will be fixed in 16.3.1, to be released in ~1 hour

**Comment by def-** [comment]
Should be fixed now, please try again.

**Comment by M0REKZ** [comment]
yeah, it can run good now, sorry for late reply
