### ISSUE TITLE
Unable to find all characters while saving

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5767]
Reported by NovaShock on Discord
![20220823183408_1](https://user-images.githubusercontent.com/2335377/186213365-7e9197e9-3aa1-4618-bc0e-a095fa0192e3.jpg)
@Zwelf any idea?

**Comment by def-** [comment]
Ok, apparently the player was in /spec:

> nope but he timed out while being in spec

**Comment by Zwelf** [comment]
Yeah, I didn't know that the message could appear. I think improving the message is the easiest fix and the one I would go for.
