### ISSUE TITLE
Input freezes after closing console while ingame

### ISSUE THREAD

**Issue by Henningstone** [ddnet/ddnet#577]
This problem has been there for quite a while now, and I'm not sure if there's already an issue, although I didn't find any, so let's open a new one.

When you close the console, you won't be able to input text anymore, unless you re-open the 'interface' where you wanna input the text (e.g. the chat); you'll also be unable to type into editboxes unless you reopen the menus.
This problem only occurs while being ingame on a server.

Easily reproducable:
- Join a server
- Open chat
- Open the console → Close the console
- Can't write in the chat anymore.

Pretty annoying.

I suppose it has something to do with the IME stuff again…

**Comment by necropotame** [comment]
I confirm this anoying bug. Thanks to provide a fix :)
