### ISSUE TITLE
Presist console history

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#5780]
I think @def- already declined the idea in #developer but I would like to propose it again.

It would be nice if the console commands would be written to a history file on disk and loaded on client launch. Like all common applications do it (some if configured). So when developing on the client and testing a feature that requires a few commands to be run to test it would be nice to quickly recompile -> restart client and then just press "arrow up" to get the last command.

**Comment by VoxelDoesCode** [comment]
I mean if anything, why not have a feature that has you manually save and un-save commands to/from the history, so if you do a bunch of unrelated commands, it wouldn't hoard up that much space? Not sure how it would work, but it seems more space friendly.

**Comment by ChillerDragon** [comment]
> I mean if anything, why not have a feature that has you manually save and un-save commands to/from the history, so if you do a bunch of unrelated commands, it wouldn't hoard up that much space? Not sure how it would work, but it seems more space friendly.

Thats weird and unintuitive. If you care about disk space turn history off or change the max history file size to something you are comfortable with.

**Comment by heinrich5991** [comment]
> So when developing on the client and testing a feature that requires a few commands to be run to test it would be nice to quickly recompile -> restart client and then just press "arrow up" to get the last command.

Workaround for this specific usecase: Keep it in the clipboard and press ctrl-v after opening the console.

**Comment by ChillerDragon** [comment]
> > So when developing on the client and testing a feature that requires a few commands to be run to test it would be nice to quickly recompile -> restart client and then just press "arrow up" to get the last command.
> 
> Workaround for this specific usecase: Keep it in the clipboard and press ctrl-v after opening the console.

Not using my clipboard during development would be more annoying than typing it in again.

**Comment by ChillerDragon** [comment]
Duplicate of #3553

**Comment by Kaffeine** [comment]
> why not have a feature that has you manually save and un-save commands to/from the history

In bash (and maybe other shells) there is a convention to use leading space to omit a command from history (and also omit duplicates).
https://datawookie.dev/blog/2023/04/configuring-bash-history/#what-goes-into-the-history

```
 say This command won't be saved
say This command will be saved
```

**Comment by Kaffeine** [comment]
> Keep it in the clipboard and press ctrl-v after opening the console.

Personally I modify the code between the client(s) and server restarts, so I have quite a lot of C++ in the clipboard instead of the needed commands.
Also, usually as a dev I think "this should work, so I'll do a test manually and won't need those commands again". Then it crashes. A few tests and hours later I write files for `exec` but it is still far from being convenient.
