### ISSUE TITLE
Blinking on RUS servers

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#579]
Some weird blinking on RUS servers happened to me(a lot of people, may everyone got it) today. !Seems! like tee change position for ~0.1 sec to another place and then back. Quads also have blink effect. 
If in pause mode you choose some blining tee and in right moment unpause your camera got freezee, so you cant move (and even change overlayentities value)

I`m tried to make demo with this blinking but on demo I cant see it, BUT demo is bugged. Client crah if you will try to call demo menu (press escape) while demo playing. If anyone wants I can upload demo. 

Can reproduce on latest, 9.3.1 and vanilla client.

**Comment by def-** [comment]
That's a problem caused by the DDoS protection of RUS server.

**Comment by BannZay** [comment]
@def- , there no possibility to hide blinking in client?

**Comment by def-** [comment]
Well, the packets are just not going through reliably. I don't think that's something worth optimizing for.
