### ISSUE TITLE
Creating server.

### ISSUE THREAD

**Issue by IS2Coffee** [ddnet/ddnet#5801]
for some reason, the cmd keep saying i need to create a new rule to let through udp on port 8303, but i already did that and i tried to disable the firewall and nothing.

**Comment by def-** [comment]
Is the server visible in server browser in Internet tab? Can you post the full error message please?
Did you forward UDP port 8303 on your router? Do you have an IPv4 address from your ISP, so that you can actually forward ports?

**Comment by IS2Coffee** [comment]
ERROR: the master server reports that clients can not connect to this server.
[2022-09-03 09:15:26][register/6/ipv4]: ERROR: configure your firewall/nat to let through udp on port 8303.
[2022-09-03 09:15:41][register/6/ipv6]: registering...

**Comment by IS2Coffee** [comment]
The server is actually not visible in internet, just in LAN.

**Comment by IS2Coffee** [comment]
"Did you forward UDP port 8303 on your router?" Yes, and I created a rule that makes the door go through the wall.

**Comment by IS2Coffee** [comment]
Port*

**Comment by IS2Coffee** [comment]
"Do you have an IPv4 address from your ISP, so that you can actually forward ports?"I guess yes, v"found a "Firewall SPI" option in the configs and just this.

**Comment by def-** [comment]
What is firewall SPI? You have to do this on your router.

**Comment by IS2Coffee** [comment]
"...forward other ports fine?" I did a test and, yes.

**Comment by IS2Coffee** [comment]
"You can google for guides for how to forward ports for your specific router model" i did this and nothing changed.

**Comment by def-** [comment]
Try `sv_ipv4only 1` and `sv_register ipv4` in your autoexec_server.cfg

**Comment by IS2Coffee** [comment]
"Try sv_ipv4only 1 and sv_register ipv4 in your autoexec_server.cfg" So, i did this and still the same thing.

**Comment by IS2Coffee** [comment]
[2022-09-03 12:50:47][register/6/ipv4]: registering...
[2022-09-03 12:50:48][register/6/ipv4]: ERROR: the master server reports that clients can not connect to this server.
[2022-09-03 12:50:48][register/6/ipv4]: ERROR: configure your firewall/nat to let through udp on port 8303.

**Comment by heinrich5991** [comment]
Can other people connect to your server using your public IP address? Check https://duckduckgo.com/?t=ffab&q=what+is+my+ip+address&ia=answer to find your public IP address.

**Comment by srdante** [comment]
@IS2Coffee Some ISPs do not support open ports to residential IPs. This could be your case.

**Comment by Robyt3** [comment]
Stale.
