### ISSUE TITLE
Unused tiles may be missed pretty easy

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#582]
We have Unused button already, but we still cant check unused tiles on existed maps (yes its possible to check layer by layer with turned info on, but its worse)

What about mark by new some picture (like question mark) if tile is unused in DDNet.
P.s.: so situations like [this](https://forum.ddnet.tw/viewtopic.php?f=13&t=4377) shouldnt happens in future

**Comment by def-** [comment]
I went through all DDNet maps and removed unused tiles. In new maps they can't be set accidentally, since you have to toggle the "unused" button first.
