### ISSUE TITLE
Filter newline chars out of http serverbrowser server names

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5826]

**Comment by def-** [comment]
@heinrich5991 ^

**Comment by heinrich5991** [comment]
> can this also be done on the server already?

I'd prefer to keep the old system where the masterserver is not aware of the structure of the server info – this way mods can easily extend and repurpose fields. This is the same way it also worked for the old-style serverinfo via UDP, the game server was in full control.

> Else everything that parses server info has to deal with it

Yes, that's true. If we want to keep the server info free-form, this will remain the case anyway.
