### ISSUE TITLE
Default colors for laser doors and laser freeze

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#5841]
![image](https://user-images.githubusercontent.com/366230/190667577-1ff8c517-9534-4b78-b599-7b9df5920acb.png)

I hadn't thought about it at all. We talked about the default laser color for shotgun, and I like it. The default laser color for the rifle shouldn't change, probably.

Are the default colors for doors (turquoise) and freeze (red) a good choice?

I think the red for freeze doesn't look like something that will freeze you, red is usually not used for freeze. Grey would probably make it hard to see though.

Might be a good chance to find good defaults before it ships in a release.

**Comment by VoxelDoesCode** [comment]
I'll try out a few colors and ask some people what work.
