### ISSUE TITLE
Safe_reload

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#585]
For mappers will be nice to have possibility to fast try their changes on map. I suggest to have reload which keep players and their states(collision, endless, weapons, etc) on their previous.
 Like a save race state - reload (update) map - load race state. 

Feature also may be helpfull if map needs some minor/design fix

**Comment by timakro** [comment]
Nice idea, I'm on it!

**Comment by def-** [comment]
Should be doable using the save-load system, handling team 0 as a team and just keeping the save data in memory.

**Comment by Learath2** [comment]
I started with this, then got stuck thinking what to do with the switches. Should I just have them reset to their default state? Because you might have added/removed switches before reloading.

**Comment by Learath2** [comment]
Actually this is so ugly I don't really want to finidh or touch it anymore :P

If anyone wants to finish it up it's at https://github.com/Learath2/ddnet/commit/24ced58d4350df499314b0f2705c391069d165fa. Left comments on what needs to be done.

**Comment by BannZay** [comment]
very first implementation may just keep players on their previous locations (what will solve 95% of the problem)
I didn't thought about deep things like switches. I would save all possible states (including existing switches) before reload. I dont mind it is critical to lost some state consistance while developing a map
