### ISSUE TITLE
Mark corner of map by kill tiles

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#586]
You are not able to go out of the map, but you also cant know when you got killed(you can feel it but cant be sure)

**Comment by Henningstone** [comment]
Do you mean the map boarder when you say "corner"? If so: I think it's not necessary to visualize it as you aren't supposed to go there anyway. Also it'd look quite ugly to have kill tiles all over the place on maps where you can get close enough to the boarder for it to come in sight.

**Comment by timakro** [comment]
I agree, we should display something else there. Repeating the tiles at the border doesn't make much sense in the game layers.

**Comment by BannZay** [comment]
Ye, I wanted to say border.

 I mean we should display kill tiles just after repeting border tile. Because, if border tile is air, and you will go far away from real border you'll get killed

@timakro, also we cant remove this behaviour, cause mappers actively used it. They know - there will be a lot of space (if border tile is air)

**Comment by timakro** [comment]
Ah, your right ofcourse.
