### ISSUE TITLE
Serverbrowser doesn't refresh after disconnecting from server / aborting joining a server.

### ISSUE THREAD

**Issue by luk51** [ddnet/ddnet#5863]
Serverbrowser doesn't refresh after disconnecting from server / aborting joining a server.

Steps to reproduce:
1. Join a server
2. Stay there a short while
3. Disconnect to get back to serverlist

Actual Behaviour:
The serverlist still is the same as before joining the server.

Improvement Suggestion:
Add a refresh after disconnecting from the server.

**Comment by Robyt3** [comment]
Fixed by #5864.
