### ISSUE TITLE
Autoconnecting dummy on DDNet dummy server

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#587]
Imagine, after connecting to the server you are already have connected dummy with you in team.
Its nice, agree? 
Client will skip two steps for you: connecting and choosing team for you

**Comment by FallenKN** [comment]
Imagine you know how to use binds.
Feature above is totally useless, maybe makes sense in a dummy server not more.
Atleast for me.

**Comment by BannZay** [comment]
Binds takes time, also team can be used already. Issue title

**Comment by FallenKN** [comment]
This must be a joke

**Comment by BannZay** [comment]
@FallenKN, no jokes here

**Comment by d3fault** [comment]
say '/team 3'; dummy_connect; cl_dummy 1; say '/team 3'; say '/lock';

@FallenKN ^doesn't work as expected when that entire line is pasted at once. the dummy doesn't join team 3, and the primary character is warned "you can't change teams that fast". also, how to not hardcode team '3'?

**Comment by FallenKN** [comment]
create cfg and exec it

**Comment by heinrich5991** [comment]
@FallenKN How would that help? Apparantly executing all of that at once just doesn't work. Probably the `dummy_connect` + something with the dummy doesn't.

**Comment by FallenKN** [comment]
dunno maybe 1000 lines between the commands to simulate delay

**Comment by timakro** [comment]
@FallenKN This must be a joke

**Comment by FallenKN** [comment]
@timakro oh shit you got me
what about an usefull delay function instead🤔

**Comment by timakro** [comment]
Btw, you can use `/mc;team 1;lock` to chain chat commands, doesn't help here though.
