### ISSUE TITLE
Add tests for base functions

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#5873]
Optimally use/integrate a code coverage tool with gtest to figure out which functions need more tests. Should be possible in the CI on Ubuntu with gcov/lcov. Not sure if possible on Windows in the CI, but should be possible manually with a [Visual Studio plugin](https://github.com/atlaste/CPPCoverage).

**Comment by def-** [comment]
I think it's pretty clear what is tested and what isn't based on the few tests we have. I could still add an automatic coverage run. I don't see any good reason for Windows support.
