### ISSUE TITLE
Close game button and settings button are in inconsistent locations (from #5861)

### ISSUE THREAD

**Issue by sjrc6** [ddnet/ddnet#5881]
IMO this is not good UX. If you try to click the settings button it is going to be in a different spot depending on if you are in-game or in menus. even worse the button which replaces it when you are in-game causes the game to close. 

from https://github.com/ddnet/ddnet/pull/5861
![image](https://user-images.githubusercontent.com/22122579/192169474-037ee1ac-038f-4119-9d48-0de3fd50a387.png)
![image](https://user-images.githubusercontent.com/22122579/192169475-d746d1b0-03d4-4818-9cba-8e53f2ac50ac.png)

**Comment by heinrich5991** [comment]
Not entirely clear to me what to do. Maybe move the demo or serverbrowser icon to quit's ingame position? I like that the X is the right-most button ingame.

**Comment by sjrc6** [comment]
I would be fine moving the power button to the furthest left location which also reduces hitting it on accident. But then it becomes in an inconsistent location but alt+f4 is always available.

**Comment by def-** [comment]
My attempt in https://github.com/ddnet/ddnet/pull/5882 is to move the Home button to the very right, so that closing the current menu is always at the very right, and immediate-quit is always second from right.

**Comment by sjrc6** [comment]
> My attempt in #5882 is to move the Home button to the very right, so that closing the current menu is always at the very right, and immediate-quit is always second from right.

Yeah that seems fine. It is maybe a bit annoying that the close game button is now where the settings used to be but at least it's always in the same spot.
