### ISSUE TITLE
refactor ingame and menu browsertabs

### ISSUE THREAD

**Issue by tscheki** [ddnet/ddnet#5892]
The tabs for the browser appear in two menus: ingame and in the "menu".

The layout of the browser tabs could be put into a helper function.
The code for the ingame tabs and the menu are not exactly the same, but it's maybe possible to simplify it.
(Right now the function `CMenus::DoButton_MenuTab` conflicts.)

I started working on it as a draft: https://github.com/luk51/ddnet/tree/refactor-serverbrowser-ingameserverbrowser

**Comment by Robyt3** [comment]
Feel free to open a PR.
