### ISSUE TITLE
Question when searching server lists

### ISSUE THREAD

**Issue by Ninecloud2077** [ddnet/ddnet#5899]
> I can't login my discord,so I have to report here.Sorry for that.  

Some Chinese players said that they can't see servers with other mods(like MMOTee,InfClass).I had these questions,too.  
I saw:

* Abroads' servers without DDNet could show successfully.
* I had Teeworlds Cilent(v0.6.5),and I could see and join Chinese Infc servers in it.

I heard DDNet are using own master servers now.Is this the reason of the question?Thanks for help.

**Comment by def-** [comment]
Yes, there is currently a problem with the Chinese Firewall blocking our master server from contacting Chinese servers. We don't have a good solution yet.
CC @heinrich5991

**Comment by Ninecloud2077** [comment]
Thanks!

**Comment by def-** [comment]
@heinrich5991 Any workaround yet? KoG is having the same problem

**Comment by Ninecloud2077** [comment]
OK.So all Chinese servers whitelisted?  
I got a news:My Chinese friend called HotPot ran a server.It through firewall successfully.Is it helpful?

**Comment by Ninecloud2077** [comment]
> Here are some Chinese servers not working.Most of them reported from ST-Chara.  
> I'm sorry that I can't login discord.I have to report here.
* 119.91.226.180,port from 8300 to 8306
* 81.68.156.138:8300
* 1.117.162.18:8300
* 101.80.8.251:42036
* 49.235.112.31:8300
* 101.34.12.14:8300

**Comment by def-** [comment]
I whitelisted the DDNet-based Chinese servers manually. But this method doesn't work for Teeworlds-based servers. @heinrich5991 is working on another solution.

**Comment by Ninecloud2077** [comment]
OK.ips of the above are all Teeworlds-based servers.

**Comment by def-** [comment]
I think this is kind of the approach @heinrich5991 is trying.

**Comment by heinrich5991** [comment]
The masterserver backward compatibility should now be running in China as well. I don't see any of the servers you mentioned though. Would need to debug this with you more closely.

**Comment by amir1376irani** [comment]
Also Iran's situation is same!

**Comment by ErrorDreemurr** [comment]
Last week, the master can't register china server again.But before last sunday, the master can register.

**Comment by ErrorDreemurr** [comment]
Wait, where is ddnet master2.In China?

**Comment by Learath2** [comment]
master2 is indeed in China

**Comment by ErrorDreemurr** [comment]
From status.tw to register a Chinese server to ddnet master.
If this server not be register to ddnet master

**Comment by def-** [comment]
master2.ddnet.org is in China, but it just mirrors master1.ddnet.org right now I think. So if master1.ddnet.org can't communicate with the server, it's not shown.

**Comment by ErrorDreemurr** [comment]
Idea:
Master can synchronize server data from each other master server.
Let master2 to register server, instead of having it to mirrors master1.
This may solve the problem

**Comment by heinrich5991** [comment]
Yea. This also needs the server to automatically select the master to register to. This isn't implemented yet. See also #5156.

**Comment by ErrorDreemurr** [comment]
wait, i think it maybe DNS problem?

**Comment by ST-Chara** [comment]
and also this one 101.43.26.223
I'm sorry to bother you. @def- 
thanks

**Comment by worldawa** [comment]
Can you whitelist this DDNet server? @def- thanks.
1.117.77.182

**Comment by def-** [comment]
Done
