### ISSUE TITLE
Time score field in http register

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#5910]

**Comment by heinrich5991** [comment]
A description would be nice.

I'd probably implement this by adding a global field that the scores are to be interpreted as times?

**Comment by fokkonaut** [comment]
i would rather keep it simple here, as the client does not even have an option to display the score in any other way (and i would be very unsure whether that would make any sense)

**Comment by heinrich5991** [comment]
Does 'rather' imply that your solution is different from mine?

What do you specifically suggest? I don't understand the issue. Do you want to add a JSON field somewhere? Where? What would it be named?

Currently, I don't understand what this feature requests wants to have.

**Comment by edg-l** [comment]
See #4561 #4415

**Comment by fokkonaut** [comment]
Simply a field for time score, values: 0, 1, like passworded.

**Comment by heinrich5991** [comment]
> See #4561 #4415

Indeed, duplicate of #4561.
