### ISSUE TITLE
Add a "counter" above the Friend heart in Server list

### ISSUE THREAD

**Issue by refeax** [ddnet/ddnet#5911]
it would be nice if there was a small number above the friend heart that says how many friends are in this one server
(see screenshot for reference)
![DDNet_wnGq83UXPv](https://user-images.githubusercontent.com/21314733/194363548-8ea8df9d-863b-4567-91dc-c1c250f61447.png)

**Comment by l-ouis** [comment]
![image](https://user-images.githubusercontent.com/69405348/202889011-cd743750-38ef-4386-914f-2e3d0143a81b.png)

I was working on this - if this looks good, then I can make a PR. Was worried that it might seem a bit cluttered if both friends and playernumber is in the double digits (especially if playernumber is in triple digits, like with fokkonaut's server.)

**Comment by def-** [comment]
I guess one alternative would be to have the number of players inside the heart, but would be quite small then.
How does it look with 128/128 players and 128 friends? I guess it won't fit.

**Comment by l-ouis** [comment]
Yes, it gets smushed
![image](https://user-images.githubusercontent.com/69405348/202909126-46857dd2-b98b-4d0a-9125-3da43fea6a66.png)
![image](https://user-images.githubusercontent.com/69405348/202909157-14d8523e-4d29-4ba9-bf55-1fea35a0ffd7.png)

Might happen a bit on fokkonaut's server, giving less space for the Name column could fix that case

**Comment by def-** [comment]
would be ok I guess, not as bad as I imagined
