### ISSUE TITLE
Option to disable running/sitting animations

### ISSUE THREAD

**Issue by Anime-pdf** [ddnet/ddnet#5920]
I read heinrich5991's comments on animations PR and why you shouldn't add more config options, but i think this is too big update to just leave it as it is. I already posted in #bugs some negative comments by some good players, maybe you received other complaints too, so please consider adding options to disable them.

**Comment by WaRNe0nx3** [comment]
This atrocity of a "running" animation is the most unnecessary change to ddnet I noticed so far. It has literally no use, yet it is so irritating to actually race with this. This needs to be removed or at the very least be optional in my opinion.

The sitting animation can be useful to identify paused players unfreezed and freezed, this can improve the experience in some cases. Not a fan of the looks, but it doesn't negatively affect the gameplay too much.

**Comment by heinrich5991** [comment]
> It has literally no use,

It's supposed to look nice. I think there's an update coming that changes how it looks like: #5919.

**Comment by hopetez** [comment]
I completely agree with @WaRNe0nx3, something that completely changes the feeling of the game should definitely be optional, especially for us speedrunners & racers out there.

**Comment by heinrich5991** [comment]
> But what about people that play competitive mods? These animations are messing everything up, it's like halving community on ddracers and fngers instead of one group of players. I don't think that we should go over old problem of "1 mod = 1 client"

Can you explain what the running animation messes up in FNG? Or does the sitting pose also mess something up?

**Comment by gerdoe-jr** [comment]
> Can you explain what the running animation messes up in FNG? Or does the sitting pose also mess something up?
I started paying more attention to new animations instead of just looking for players. Before we had walking, mid-air, idling states and running, sitting, walking, mid-air, idle states now. 
But its my personal problem. By the way, isn't #5558 doing same thing we discuss about (adding an option to make game process customized)?

**Comment by WaRNe0nx3** [comment]
So what's the plan, will it be removed/made optional, or do speedrunners have to fork and make their own client without this?
Really not enjoying maps with lot of ground movement right now.

**Comment by def-** [comment]
@VoxelDoesCode

**Comment by heinrich5991** [comment]
No, @heinrich5991. It wasn't @VoxelDoesCode who pushed against the option.

Have you tried the new release candidate?

**Comment by heinrich5991** [comment]
I don't think we need an option for this.
