### ISSUE TITLE
config_directory.bat does not work if %APPDATA% contains white space

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#5936]
config_directory.bat does not work on my machine (Win11). 

Execution of the script:
![image](https://user-images.githubusercontent.com/17499770/195161114-c7afbae2-a601-4792-bea2-4540337b4d72.png)

It does not work because my %APPDATA% contains white space in the path,

Script that would work (with double quotes around the path):
```
if exist "%APPDATA%\DDNet\" (
	@start explorer "%APPDATA%\DDNet\"
) else (
	@start explorer "%APPDATA%\Teeworlds\"
)
```

**Comment by def-** [comment]
Can you make a pull request with this fix?
