### ISSUE TITLE
Translations in need of a cleanup

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#595]
I was trying to complete the translations for Korean and Japanese, but there were lots of strings that are repeated (big issue with uppercase and lowercase) and unused and saw this in other language files as well. Can this be improved?

**Comment by timakro** [comment]
I wrote some python scripts several years ago which should help with that issue https://github.com/ddnet/ddnet/tree/master/data/languages/scripts.

**Comment by necropotame** [comment]
@deen, @heinrich5991, I think using Crowding could help a lot with translations. I've already the code ready from TeeUniverse and InfClass for this. I've also tested Transifex, but it's much less robust and didn't work well for some languages. The workflow is:
- Use xgettext (or a custom script) to extract translations in .pot format
- Give it to Crowdin and let the translators do the job.
- Get all .po from Crowdin and use a script to convert it in the format that you want. (already done)

What do you think about it?

**Comment by def-** [comment]
I believe translations are useless and we should just offer English language.
