### ISSUE TITLE
Opinion about voting in game

### ISSUE THREAD

**Issue by Ninecloud2077** [ddnet/ddnet#5952]
I found out some servers with a lot of players,and players in them can't ban or move other players by vote.A player said that "Votes never work at all".
I watched them some time,and I saw:There were many afk in some servers.They could't vote so votes was failed most of time.
I had got an idea:Servers could see players which was afk,because there was a sleeping emote on their head.When someone called a vote,the least number of the players which agreed should be the same as the number of active players,but not the number of all players(without dummies).

**Comment by heinrich5991** [comment]
I *think* AFK players are already not counted for votes.

**Comment by Chairn** [comment]
AFK players are already ignored. For a similar issue, see https://github.com/ddnet/ddnet/issues/5091
