### ISSUE TITLE
Compilation is broken on windows with mingw64

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet#5969]
culprit is https://github.com/ddnet/ddnet/pull/5810

Error message is:
```shell
E:\Teeworlds_DDNet\ddnet\src\base\system.cpp: In function 'void* shell_execute(const char*)':
E:\Teeworlds_DDNet\ddnet\src\base\system.cpp:3874:26: error: '_control87' was not declared in this scope
  unsigned oldcontrol87 = _control87(0u, 0u);
```

@Robyt3 any idea?

**Comment by Chairn** [comment]
Works fine with gcc from MSYS, so i guess i have an outdated version of mingw (once again...)

**Comment by heinrich5991** [comment]
Perhaps it could use the standard
```
       int fegetenv(fenv_t *envp);
       int fesetenv(const fenv_t *envp);
```
functions instead.

**Comment by heinrich5991** [comment]
The function also forgets to check the return value of `MultiByteToWideChar`.

**Comment by Robyt3** [comment]
We don't check the return value of any `MultiByteToWideChar` call and `WideCharToMultiByte` results are also checked only in some places.
