### ISSUE TITLE
Pseudo-double-clicking servers bug

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#597]
In the server list menu, click one server and quickly click another server joins the second clicked server. It's wrongly recognized as a double click.

**Comment by Henningstone** [comment]
Confirming this bug. The error is right here: https://github.com/ddnet/ddnet/blob/b42ae74d29d04e650ecc4651202d3cf0cd24456b/src/game/client/components/menus_browser.cpp#L471.

Proposal to fix it: We could be using the `DoubleClicked` variable instead, which determines whether one single item has been double clicked.
