### ISSUE TITLE
editor context menu out of screen

### ISSUE THREAD

**Issue by WaRNe0nx3** [ddnet/ddnet#5982]
context menu out of screen making some options inaccessible, behavior persists after restart.

ddnet 16.4
desktop fullscreen 1920x1080
opengl 3.0.0

![ddnet_editorbug](https://user-images.githubusercontent.com/46048422/197807445-94353a0b-c783-4d2b-a31e-0dd1e3e59607.png)

**Comment by def-** [comment]
@sctt Could this be related to your change "[Editor] Editor: Added "Order" button in quads popup [sctt]"?

**Comment by Robyt3** [comment]
This already happened before #5820.
