### ISSUE TITLE
freeze laser color incorrect

### ISSUE THREAD

**Issue by WaRNe0nx3** [ddnet/ddnet#5986]
I set up dark grey for freeze lasers but it uses the green rifle laser color for the rotating freezing lasers.
Otherwise rifle, shotgun, and door colors work.

ddnet 16.5 & 16.4
![ddnetlasers](https://user-images.githubusercontent.com/46048422/198119842-3dd04f6e-4648-4706-91d5-492d975140af.png)

**Comment by fokkonaut** [comment]
Fixed in #5886

**Comment by Robyt3** [comment]
Fixed by #5886
