### ISSUE TITLE
default.png skin is bad, and questions on shipped skins

### ISSUE THREAD

**Issue by l-ouis** [ddnet/ddnet#5988]
![image](https://user-images.githubusercontent.com/69405348/198352152-946a083e-4262-44b3-b2b4-521f9c11180f.png)
The default skin shipped with client has been faulty for a long time now.
The picture is not a great visualization, but the borders are slightly asymmetrical and there is a saturated fringe on the inside.
i pasted/rotated the border from the left side onto the right side to show that the border strength is different.

![image](https://user-images.githubusercontent.com/69405348/198352459-549f34ab-8014-437b-8f94-a3cb91ad996a.png)
compare to a newly rendered default skin from the svg database, which looks much cleaner in my opinion

Also: maybe we could alter the selection of shipped skins in the client? Here are some changes I would propose:

- remove less popular skins (still keep them in database) and add more popular skins currently in database but not shipped
- remove all the bloat coala_, kitty_ , and santa_ skins, which can just stay in the database but not in default client (it takes up a lot of space in the skin list, and can easily be applied with the built-in Skin prefix option)

If these changes seem good, I can work with ravie and make a pull request with all the changes

**Comment by def-** [comment]
Sounds good to me. I think as the Skin DB team you can also change skins in client as you see fit.

**Comment by Chairn** [comment]
But what if it's irregularities and asymmetries that makes it beautiful?

**Comment by heinrich5991** [comment]
All skins that are added to the client need to have a clear open-source license from the author.

**Comment by l-ouis** [comment]
todo: also investigate this:

https://github.com/ddnet/ddnet/pull/6242#issuecomment-1374250992

haven't had time to work on the other stuff above but will get to it at one point

**Comment by Kaffeine** [comment]
> remove all the bloat ... santa_ skins

I'm against this change.  `santa_` skins are [activated for the Christmas](https://github.com/ddnet/ddnet/blob/3ff799770c91ba2c485d6159f6e6f47cf6badafb/src/game/client/components/skins.cpp#L306) add a lot of depth to the game.

In my mod (which has to rely on vanilla skins until https://github.com/ddnet/ddnet/issues/7055 is solved) also features winter theme with those skins. It would be disappointing to have it worked for years and suddenly do not work anymore in a new release.

![image](https://github.com/ddnet/ddnet/assets/374839/73280782-48f1-4f6b-ba9a-e9d0d89a03aa)

![image](https://github.com/ddnet/ddnet/assets/374839/bc2c8cc5-7259-4d99-82af-67b61f4d33b4)

(for my client I also added santa ninja skin)

I have nothing against removing other skins, as well as  `coala_`, `kitty_ ` which are not used by ddnet.

**Comment by l-ouis** [comment]
> My mod (which has to rely on vanilla skins until https://github.com/ddnet/ddnet/issues/7055 is solved) also features winter theme with those skins. It would be disappointing to have it worked for years and suddenly do not work anymore in a new release.

I'm not sure if there's a large percentage of players on updated clients that play without [x] Download Skins, but I guess there are at least a few.
Keeping them in the database but not the client might actually make the holidays more special, since the santa skins would seem to "come out" for a couple of months instead of just always being an easy option to select in the menu.
