### ISSUE TITLE
"Exclude" filter in the server list menu does not work for server mod type

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#599]
For example, if you exclude "DDRace" as a filter, some servers with the DDRace mod _type_ will not be filtered.

**Comment by Henningstone** [comment]
That is because it [isn't meant to be like this](https://github.com/ddnet/ddnet/blob/98a2f459b6bf0a1df55a081e750e3678844b524b/src/engine/client/serverbrowser.cpp#L247-L257). Exclude filters are only matched against server name and map. But it would probably make sense to implement it...

**Comment by PathosEthosLogos** [comment]
Yep, the filters for game type is actually separate, on the right side of the server list menu. There's also a filter by IP address and ping. I don't think anybody would use the IP filter though.

**Comment by Learath2** [comment]
Works as intended.

Could add a "Exclude gametype" filter to the right, but feels useless to me, reopen if you'd want that or come up with a more elegant way.

**Comment by heinrich5991** [comment]
@Learath2 People can't reopen issues that you close for them.

@PathosEthosLogos Just comment on this issue and some responsible person will reopen this issue.
