### ISSUE TITLE
Hide the switch number for tiles that are not affected by it

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#5995]
teini94 mentioned that mappers like to use switch number 0 for jump tiles, because it's confusing when two numbers are shown on them. Technically it shouldn't make a difference, because jump tiles are not affected by the switch number. Selecting switch 0 was disabled by #5993.

For example:

![screenshot](https://user-images.githubusercontent.com/23437060/199234500-490aebca-9372-4c1e-a8a2-2f02f2a60701.png)

The left tile uses switch number 0 and delay 2, hence setting the number of jumps to 2. The right tile uses switch number 1 instead.

This needs some discussions from mappers. I'm not very familiar with all the available tiles.

Maybe there are also tiles where switch number 0 has a purpose other than visually hiding the switch number in the editor? I'm seeing some `Collision()->GetSwitchNumber(MapIndex) == 0` checks:

https://github.com/ddnet/ddnet/blob/79ea9d1de3f4339ba6f3e9e67f371836c285e72c/src/game/server/entities/character.cpp#L1655

that seem to make the respective tile always enabled when the switch number is 0. I assumed selecting number 0 was an editor bug, because this line was already present before #5993 and had minimum 1 and maximum 255:

https://github.com/ddnet/ddnet/blob/79ea9d1de3f4339ba6f3e9e67f371836c285e72c/src/game/editor/popups.cpp#L1649

**Comment by heinrich5991** [comment]
Would be nice if the unused number is set to some fixed value, maybe 0.

**Comment by Robyt3** [comment]
I changed it in #5997 so switch number 0 is allowed again, as this switch is always enabled, so it's useful e.g. to place freeze tiles that are always enabled. Tiles that don't work with switch number 0 (e.g. switch open/close tiles) should be made unplaceable and the switch number should be hidden for tiles where it doesn't have any effect (e.g. jump tiles).
