### ISSUE TITLE
"Insecure RUNPATH '$ORIGIN/../lib/ddnet' in file ('usr/bin/DDNet-Server')"

### ISSUE THREAD

**Issue by rffontenelle** [ddnet/ddnet#6001]
When packaging DDNet with both `DISCORD` and `DISCORD_DYNAMIC` build flags set to ON, the generated `DDNet-Server` binary comes with a library runpath '$ORIGIN/../lib/ddnet'. This does not happen with these two flags are disabled.

Running [namcap](https://wiki.archlinux.org/title/Namcap) against the binary DDNet package, it complains:

```
ddnet E: Insecure RUNPATH '$ORIGIN/../lib/ddnet' in file ('usr/bin/DDNet-Server')
```

From readelf:

```
$ readelf -d /usr/bin/DDNet-Server | grep RUNPATH
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib/ddnet]
```

Environment:
- DDNet version 16.5
- Distro: Arch Linux
- building [ddnet](https://aur.archlinux.org/packages/ddnet) AUR package

Steps to reproduce (I'll use build instructions from Arch):
1. build and install Discord Game SDK (in Arch: `git clone https://aur.archlinux.org/discord-game-sdk.git && cd discord-game-sdk && makepkg -si`)
2. build and install DDNet (in Arch: `git clone https://aur.archlinux.org/ddnet.git && cd ddnet && makepkg -siC`)
3. check RUNPATH and get library runpath set: `readelf -d /usr/bin/DDNet-Server | grep RUNPATH`<br>
Now testing without discord-game-sdk:
4. disable discord by removing `-DDISCORD=ON` and `-DDISCORD_DYNAMIC=ON`, or by setting it to OFF, in cmake arguments (in Arch: from the PKGBUILD file).
5. Repeat steps 2 and 3, and get no library runpath output

Logs and PKGBUILD (a.k.a. Arch's package build rules file):

[CMakeOutput.log](https://github.com/ddnet/ddnet/files/9929753/CMakeOutput.log)
[CMakeError.log](https://github.com/ddnet/ddnet/files/9929755/CMakeError.log)
[ddnet-16.5-2-x86_64-build.log](https://github.com/ddnet/ddnet/files/9929758/ddnet-16.5-2-x86_64-build.log)
[ddnet-16.5-2-x86_64-check.log](https://github.com/ddnet/ddnet/files/9929760/ddnet-16.5-2-x86_64-check.log)
[ddnet-16.5-2-x86_64-package.log](https://github.com/ddnet/ddnet/files/9929761/ddnet-16.5-2-x86_64-package.log)
[PKGBUILD-namcap.log](https://github.com/ddnet/ddnet/files/9929762/PKGBUILD-namcap.log)
[PKGBUILD](https://github.com/ddnet/ddnet/files/9929774/PKGBUILD.txt)

**Comment by def-** [comment]
based on CMakeLists.txt I would only epxect this for DDNet, not DDNet-Server:
```
  if(STEAMAPI_KIND STREQUAL SHARED OR DISCORD_DYNAMIC)
    set_own_rpath(${TARGET_CLIENT})
  endif()
```

**Comment by rffontenelle** [comment]
I worked around this issue by disabling ANTIBOT build flag.

ANTIBOT was enabled, and CMakeLists.txt showed my that enabling it causes `set_own_rpath(${TARGET_SERVER})` to be run. What I don't understand is why it was ON *without* having a library runpath in the DDNet-Server, nor why enabling DISCORD_DYNAMIC *together* with ANTIBOT made the library runpath pops up in DDNet-Server, but problem is solved on my side.
