### ISSUE TITLE
Don't close vote menu

### ISSUE THREAD

**Issue by Anime-pdf** [ddnet/ddnet#6022]
Add option to let people keep vote menu opened after starting a vote. `cl_show_votes_window_after_voting` basically.
It will be handly for other mods and for ddnet, when you voting server difficulty first and map after.

Menus dont have much config options afaik, so adding new option and testing it with other options mustn't be a problem.

Duplicate of https://github.com/ddnet/ddnet/issues/813

**Comment by def-** [comment]
Reopened the original.
