### ISSUE TITLE
Communication Authentication Server <-> Players/Servers

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6037]
Figure out how to safely get authentication data from other players to your client. We could only trust the http master server for this, which we also run, and not the game server. Registration server could tell the http master who is logged in where.

**Comment by heinrich5991** [comment]
It'd be good if this would run separately from the HTTPS master, so that the registration server can go down and the more simple HTTPS master can still allow people to play.

**Comment by def-** [comment]
If the auth server is down, what account will players' ranks be assigned to?

**Comment by heinrich5991** [comment]
In general, people should still be able to connect to servers if the auth server is down.

In case we do public-private key cryptography for the individual sessions, we can prove a key and later associate it with the account.
