### ISSUE TITLE
Account administration

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6039]
Implement a frontend to administer your account from website/client. Register, delete account (disables but keeps ranks), change email address, change password, connect to some auth service (mainly Steam I guess).

**Comment by edg-l** [comment]
We need to decide the language/framework to do this.

Personally, if we don't have JS haters we can do this easily with Reactjs (nextjs) or vuejs, i am knowledgable with reactjs but not vuejs.

Or we can go the templatey way using python with flask and jinja.

We can whip up a frontend really fast using bootstrap and react, in my opinion, and later customize it more.

**Comment by def-** [comment]
I'd just use the current Python website we have already probably, even PHP would be fine. We shouldn't new fancy tools just because they exist, or next someone wants to remake the entire website (yet again) and it never gets finished.

**Comment by edg-l** [comment]
I never made a new website because i know you don't like new shiny stuff, the current one is pretty unmanageable with all those scripts in different places.

**Comment by heinrich5991** [comment]
I'd like to have a website that also works without much JS.

**Comment by edg-l** [comment]
https://ch.tetr.io/ imagine ddnet having a web like this
