### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6041]
Think about what achievements we want to have and make them show up on website/client. Some should be stackable so you can improve on them, design some nice graphics for them:
a) Number of days with finishes every day: 7 days / 14 days / ...
b) Long finish: 4 hours / 8 hours / ...
c) Reach points: 1000 / 2000 / ...
d) Team rank with same friend on number of maps: 10 / 20 / ...
e) Perfect time finish with :00.00
f) Team finish with large number of players: 16 / 32 / 64
g) Top ranks: 1 / 2 / 4 / 8 / ...
h) All maps finished on server: Novice / Moderate / ...
i) Account age and still active: 1 year / 2 years / ...

**Comment by edg-l** [comment]
This could be crazy but accounts allow for this, we could gather even more data:

- Number of hammers perfomed,
- Bullets shooted
- Tees hooked
- Deaths
- Time on air
- Time on ground
- Time on a edge
- Time on freeze
- Time spectating

And it could be used on achievements too.

**Comment by def-** [comment]
I don't think those are interesting/challenging things to achieve.

**Comment by murpii** [comment]
> Deaths would be nice to track, or time in freeze. Something fun

https://user-images.githubusercontent.com/60477660/201716503-70760abb-1aea-4ea0-92b8-404f8e851f66.mp4

**Comment by sjrc6** [comment]
This would open the possibility of steam achievements, do we want that? I personally like when games have hard achievements you can showcase on your profile.

**Comment by Robyt3** [comment]
>> This could be crazy but accounts allow for this, we could gather even more data:

> I don't think those are interesting/challenging things to achieve.

I think having a statistics page with various stats like this would already be interesting. I agree not everything should be an achievement.

> This would open the possibility of steam achievements, do we want that? I personally like when games have hard achievements you can showcase on your profile.

I think it would be best to synchronize achievements between Steam and ingame. For example like in Factorio.

**Comment by lolipodass** [comment]
> > Deaths would be nice to track, or time in freeze. Something fun
> 
> https://user-images.githubusercontent.com/60477660/201716503-70760abb-1aea-4ea0-92b8-404f8e851f66.mp4
> 
> 

Yes, it's true, but it can be like a time in games on Steam, it doesn't give anything exept watching on them.  at the same time, you can farm them (as some do it in the steam) and no one will limit you to do this.  it can be just like an interesting statistic and nothing more

**Comment by l-ouis** [comment]
I think these should be grouped into "stats" and "achivements". stats have a singular value and achievements are generally a specific goal and can be tiered. Here's a list of some of stats I think would be nice to display on profile (borrowing some from deen):
- # of points
- # of rankpoints
- # of rank1s
- # of finishes
- # of deaths
- account age
- longest playing streak
- longest finish
- largest team finish

**Comment by heinrich5991** [comment]
It's important to not cause bad incentives with achievements or stats. This means not including achievements that make it useful to fail a run or so.

Also, we should try to avoid achievements that get people too addicted. Duolingo is a bad example in that regard, I think.

**Comment by Chairn** [comment]
On a technical note, how should achievements be implemented? I was thinking of allowing some callback functions to be called after some events (connection, finish, death, etc.).

**Comment by heinrich5991** [comment]
How do achievements interact with non-DDNet hosted servers? Are they tracked on the client (should we just include a checkbox for the achievements) or on the server?

**Comment by def-** [comment]
Only official server.

**Comment by def-** [comment]
> Also, we should try to avoid achievements that get people too addicted. Duolingo is a bad example in that regard, I think.

I was also worried about this and it's one of the reasons I'm conflicted about our existing points system and adding achievements before (has been planned on and off for 9 years). Would it help to set the highest achievements to still be reasonable? Maybe not max out at 20.000 points but 4000 points as the last level?

**Comment by Robyt3** [comment]
Seems like this was closed together with other issues related to DDNet Season 2, but I'd like achievements regardless of accounts. I'd simply store relevant stats on the client-side. For Steam these could also be synced with the Steam cloud. Probably only track achievements on community servers.
