### ISSUE TITLE
Physics changes

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6043]
Kicker suggests removing the possibility to skip gametiles. Sounds good to me and makes mapping less annoying.

I'm not sure if we want to get rid of strong/weak.

Any other physics changes that would be reasonable for season 2?

**Comment by Learath2** [comment]
Clipping into/through doors and stoppers. Maybe sanify the shotgun bugs a bit?

I think strong/weak can stay but they do need some UX. It's just too entangled with everything, it changes the feel of hammer flies and throws even :/

**Comment by def-** [comment]
UX is independent of season 2.

**Comment by Learath2** [comment]
> UX of strong/weak is independent of season 2, if we keep it.

I know, just gave my justification for keeping it. I.e. better UX can save it

**Comment by VoxelDoesCode** [comment]
I think dummy should have an option to be nerfed in maps, so that people don't get cheap R1s by pseudoflying

**Comment by heinrich5991** [comment]
Options are bad. Gameplay shouldn't change between maps.

**Comment by Chairn** [comment]
- Allow all tiles to have effect in a single tick
- Use same interpolation method for all tiles
- Prevent skipping

Gameplay wise, i also like some of our bugs that makes the game what it is today, not sure we should get rid of all of them. Just maybe normalize them in some way.

**Comment by sjrc6** [comment]
If there are any physics changes would that mean maintaining 2 different physics system for old maps/servers?

**Comment by def-** [comment]
No, change physics at the point of introducing season 2.
