### ISSUE TITLE
Account related SQL tables/design and the auth backend

### ISSUE THREAD

**Issue by edg-l** [ddnet/ddnet#6044]
## Database of choice
We need to decide the database of choice for the auth backend that will store the account data.

I suggest postgresql

## The data layout

Maybe it's worth discussing how the tables will be laid out and structured, to think of the best and most efficient way while keeping most of the data open to exports.

A good idea would be to have a minimal table with all the sensible private data such as the email and password hash, and then a separate table with more public facing data such as the current nickname, country, etc.

As for account IDs, i would use UUIDs.

(click to go to plantuml and edit it if you want)
[![UML](http://www.plantuml.com/plantuml/png/JOz13e8m44NtSugvW1oWYGe9BDovWCGT6TinLA4rxH1ZZ7SN593b_vbvBp-DGa7whWNmvojhmKnhtpl15w0rkCMgEkI0t95jXrGMfnBmJZ4-V31rGx6Ps_U2E0P_iIsF2FhHwXMgZnmSTRpGT60IDZN9KELPMG1-dy9pEja3nfjr_vGaoQYRF4gjB9lTl40fQo1bPuPr7m00)](http://www.plantuml.com/plantuml/uml/JOz13e8m44NtSugvW1oWYGe9BDovWCGT6TinLA4rxH1ZZ7SN593b_vbvBp-DGa7whWNmvojhmKnhtpl15w0rkCMgEkI0t95jXrGMfnBmJZ4-V31rGx6Ps_U2E0P_iIsF2FhHwXMgZnmSTRpGT60IDZN9KELPMG1-dy9pEja3nfjr_vGaoQYRF4gjB9lTl40fQo1bPuPr7m00)

## What data?
We have to decide what useful data can be stored on a per account basis.

**Comment by heinrich5991** [comment]
It'd make sense to use MariaDB for this; we already have to run it.

**Comment by Chairn** [comment]
Need another table for achievements
