### ISSUE TITLE
Include echo messages in demos/replays

### ISSUE THREAD

**Issue by Chikowitz** [ddnet/ddnet#6047]
So my initial question in the discord was:
_how can I output a message in the game chat that will be visible only to me and will be visible in demos?
echo command is visible in the chat, but not in demos_
https://discord.com/channels/252358080522747904/745926398140612678/1041994877237469246

Learath2 says that it should be doable, so I figured I'd post it in here.

Lumpy ◐ω◑

**Comment by def-** [comment]
`/w` with your own name

**Comment by Chikowitz** [comment]
wow actually a good idea, working for me, ty
