### ISSUE TITLE
Leveling System

### ISSUE THREAD

**Issue by bubliman** [ddnet/ddnet#6048]
### Leveling system
ddnet has no way of quickly assessing someones skill level and has no infinite progression. A leveling system could allow for players to be motivated to improve at the game and make replaying maps more meaningful rather then just for fun. 

Here are a few examples of situations that would give <sub>XP</sub>, these are the main 3 categories that fit pretty much everything in ddnet 
**Grand achievements**
_- Example1: first finish of a map 20000<sub>XP</sub> * 1 (novice difficulty modifier) * 0.3 (if repeated finish) * Rank multiplier (R1 - 15, R2 - 10, ...) = 20000<sub>XP</sub>_ 
**Sustained actions**
_- Example2: two players speed-fly for 8s, 300<sub>XP</sub> on start and 50 <sub>XP</sub> per second = 700<sub>XP</sub>_
**Combo-able actions**
_- Example3: one player is hammer-hit by someone and then he pulls off a 5 hammer-hit combo (only if withing a certain time window of each other for hammer-hit i would imagine less then 1s),  so 6<sup>5</sup><sub>XP</sub> = 7776<sub>XP</sub>_

### Suggested implementation with requirements 

1. - [ ] **Figure out a way of detecting actions that should have XP awards** (hammerhit, wallhammer, speedfly, onetile laser solo, ...)
2. - [ ] **Make a nice looking HUD for displaying the XP gained and level progression**  (DDNet client only, for older clients it could be displayed with server message)
3. - [ ] **Display other players levels** either in TAB or in-game next to their name (DDNet client only, for older clients /level cmd)
4. - [ ] **Figure out rewards for leveling up**, one of my ideas is to make a new really good lookin skin collection that's locked behind certain levels (10,20,30,40,50), or some cosmetic things (this skin would be locked serverside, if someone renamed it locally that would be only visible to him)
6. - [ ] **Figure out the math behind the system**, I think that it should be based around if u finish all maps you would get lvl 100, so make all of the numbers fit that scale, when you go past lvl 100 no more rewards after that.

Let me know what you think about this, is it even possible to detect hammerhits etc.? Would this be a viable thing for ddnet? Is this something that aligns with the vision for ddnet?

**Comment by bubliman** [comment]
This could also tie in with Achievements #6041 and potentially for skill level Matchmaking #3660

**Comment by heinrich5991** [comment]
This sounds like assessing someone's grinding, not like assessing someone's skill. Similar to the points we have today, but even more grindy.

**Comment by bubliman** [comment]
> This sounds like assessing someone's grinding, not like assessing someone's skill. Similar to the points we have today, but even more grindy.

Hmm, I feel like the grindiness behind points is that it makes you play shit maps to get them, with this system you can progress with any playstyle, whether that's finishing as many maps as you can or just playing team 0 brutal maps. So I feel like it would reflect someones skill way more accurately then points.

**Comment by Chairn** [comment]
I don't see any way of implementing such complex detection unfortunately.

**Comment by bubliman** [comment]
Okay, I agree that it is very difficult and propably it is not possible to track every possible mechanic. But if it were to be done you could even track stuff like hammerhit accuracy these kinds of stats could be very neat for the profile page. Now let's get into the hypothetical would it be worth it to work on this?

**Comment by heinrich5991** [comment]
> But if it were to be done you could even track stuff like hammerhit accuracy these kinds of stats could be very neat for the profile page.

This sounds like a bad idea. People will start optimizing for this, playing worse because they might miss a hammerhit otherwise.

**Comment by bubliman** [comment]
Okay, since there is no interest, i'm closing the issue
