### ISSUE TITLE
Auto recording demo limit deleting the latest instead of oldest auto recorded demo and file name convention

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#605]
I think it used to work fine until the same patch as the file naming convention changed.

The file name should be date and time first.

Then, there can be another column to sort by map. This is just reading the file name, so there shouldn't be much lag from it... right?

When auto recording a demo and maximum number of auto recorded demos are reached, the most recent demo is replaced instead of the oldest one. Please fix this!

**Comment by Learath2** [comment]
Is this still the case @PathosEthosLogos?
