### ISSUE TITLE
Different colored name for friend's name in the chat

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#606]
Right now, there are red, blue, and purple colors for red team, blue team, and spectators. How about opposite color of the purple, so some hue of green for someone added into friend list?

**Comment by necropotame** [comment]
Green is the color for team chat in non-team based gametypes, if I remember well.

**Comment by FallenKN** [comment]
iirc those all can be changed in the ddnet client already, but you should definitly go with another color then green, yellow is also used for server messages.

**Comment by necropotame** [comment]
Why not just display an heart-like icon? I think it's better than having a 5th color in the chat.

**Comment by FallenKN** [comment]
would you really recognize a heart-like icon since those unicode names are allowed?

**Comment by PathosEthosLogos** [comment]
Actually, that's a better idea. I think heart icon should be used. It can be a bright color, maybe an icon instead of unicode text heart.

**Comment by Henningstone** [comment]
What about a unicode text heart in a different color? (red?) ;)

**Comment by necropotame** [comment]
I though more about something like that:

![DDNet Chat Mockup](https://s24.postimg.org/usrlq71xh/ddnet_chat.png)

**Comment by PathosEthosLogos** [comment]
@necropotame Can you reference the code for that on Github?

**Comment by necropotame** [comment]
It's just a mock-up made with InkScape. But if @def- or @east are interested, I can work on it and create a PR

**Comment by PathosEthosLogos** [comment]
@necropotame Not sure what PR is, but if you just start coding and request a merge, I'm sure they'll be happy to add it in.

**Comment by FallenKN** [comment]
I agree with @PathosEthosLogos
PR=Pull Request

**Comment by def-** [comment]
Looks a bit complicated. I like that the chat is actually just text. Other opinions?

**Comment by PathosEthosLogos** [comment]
@heinrich5991 Oh man, great update, but can you make it so that just the heart is red, not the player alias? If a player is in the blue team, it doesn't distinguish it. So, just the red heart and default colors for the player aliases on either teams.

**Comment by Learath2** [comment]
Eeeh introduces some ugliness in the code that's why I avoided it, I'll give it a look over see if I can find a nice way to do it.

**Comment by Henningstone** [comment]
@Learath2 you could spare on a lot of ugliness by using the system that's already there i.e. not simply prepending the heart to the name, but rendering it right before the name. As background information, here is how the chat rendering roughly works:
1. figure out the needed name color and set it [{#}](https://github.com/ddnet/ddnet/blob/4e39aea2f737473bb10ccd2b8553e155f96e39a7/src/game/client/components/chat.cpp#L754-L786)
2. render the name [{#}](https://github.com/ddnet/ddnet/blob/4e39aea2f737473bb10ccd2b8553e155f96e39a7/src/game/client/components/chat.cpp#L788)
3. figure out the needed message color [{#}](https://github.com/ddnet/ddnet/blob/4e39aea2f737473bb10ccd2b8553e155f96e39a7/src/game/client/components/chat.cpp#L788)
4. render the message [{#}](https://github.com/ddnet/ddnet/blob/4e39aea2f737473bb10ccd2b8553e155f96e39a7/src/game/client/components/chat.cpp#L818)

This is done by using a `CTextCursor`, I'll assume you know how that works.
So your job would be simply prepending the following to the above list:
1. figure out if a heart is needed (well you already have code for this one)
2. if so, set the text color to red and render the heart

I'd implement this [here](https://github.com/ddnet/ddnet/blob/4e39aea2f737473bb10ccd2b8553e155f96e39a7/src/game/client/components/chat.cpp#L752). If you stick to the system, the result will be even cleaner than it's now :)

**Comment by Learath2** [comment]
That's how I had it at first but I didn't quite like the offset heart. Well i'll take a screenshot tomorrow and we can look at it.
