### ISSUE TITLE
esc key work unnormally

### ISSUE THREAD

**Issue by fr233** [ddnet/ddnet#608]
esc key sometime work sometime don't work.
example:i click esc key then that bar(i don't know what's its name) appear,but after it appear,i click esc key and that bar don't disappear;or i click esc key and that bar  appear and quickly disappera.
there is no this problem with teeworlds,only appera in ddnet.
os:archlinux
desktop:gnome

**Comment by fr233** [comment]
sorry,my fault,it work on wayland.

**Comment by fr233** [comment]
sorry,it work on xorg

**Comment by PathosEthosLogos** [comment]
Resolved?

**Comment by fr233** [comment]
@PathosEthosLogos 
Haven't,it's strange.whether I login with wayland or xorg,that bar wound't work nornally,but after I log out and relogin,whether using waylang or xorg,that bar would work normally.

**Comment by def-** [comment]
Can't reproduce.
