### ISSUE TITLE
Suggestion: shortcuts review

### ISSUE THREAD

**Issue by NouaaTW** [ddnet/ddnet#6089]
Hi, it would be really great and better to make these changes: 

- add ctrl+A which would select everything and cover it in blue instead of just ctrl+c to copy everything
- add ctrl+X to cut
- add ctrl+F in both consoles (F1 & F2) which would bring up a search bar to search for keywords etc..

ctrl+A would be more suitable for beginners, because a new player trying to figure out how to copy something won't know it that easily

Thank you for taking this into consideration (and we can discuss things in case I'm wrong somewhere 😄 )!

**Comment by def-** [comment]
Sounds reasonable

**Comment by TheNoobestNoob** [comment]
I had this idea in my head for months, maybe it's time to realize it

**Comment by Robyt3** [comment]
The text input changes were added by #6530.

Searching in the console is requested in #5815 already.
