### ISSUE TITLE
Second favorites tab or folder

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#609]
Exactly as the title

**Comment by FallenKN** [comment]
for what reason?
Something like recent would be cool.

**Comment by PathosEthosLogos** [comment]
For whatever reason people can think of, so infinite reasons. There's favorites and DDNet tab.

Personally, with master servers going down recently, I thought about making that server list provided by ChickenMilk/EVIL into favorites, but I didn't really want to lose my favorites.

Recents would be pretty cool too.

**Comment by Henningstone** [comment]
> Personally, with master servers going down recently, I thought about making that server list provided by ChickenMilk/EVIL into favorites, but I didn't really want to lose my favorites.

Serverlistcache ftw! Go for it!
