### ISSUE TITLE
f1 console same color as the chat

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#610]
For example, if the line starts with [teamchat] in the console, then it would be green, just like in the chat.

**Comment by necropotame** [comment]
Colors should be related to the state of the console, like success if a command or something like this. Using colors for chat log seems not a good idea for me.

**Comment by PathosEthosLogos** [comment]
Definitely a valid point, but I'm pretty sure there are enough colours to go around for both chat and console-related text. :)

**Comment by kamillentee** [comment]
af2e19c4e7ff4775c9fa27131736230344f94013
