### ISSUE TITLE
Black screen when pressing shift key at chat

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6103]
As reported by uq on Discord

> Only when vulkan -> Intel (R) UHD Graphics 630 choosen

https://user-images.githubusercontent.com/2335377/206266890-6e9b72d7-e3c2-45bc-a368-243c8947ed31.mov

@Jupeyy

**Comment by Jupeyy** [comment]
nothing cross platform that i know of. maybe there is a windows only API call to prevent smth like this

**Comment by edg-l** [comment]
closing, open if happens again, but this looks like something we can't fix
