### ISSUE TITLE
sqlite timestamp entries don't contain correct timezone

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6105]
Seems that using sqlite3mysql is off by 1 hour, which suspiciously looks like the CET->UTC difference. In MySQL we store local time, I guess in Sqlite we store UTC.

**Comment by Zwelf** [comment]
A workaround for that is to run `set time_zone = '+0:00';` before running the sqlite3mysql script:

```bash
> sudo mysql
MariaDB [(none)]> set time_zone = '+0:00';
Query OK, 0 rows affected (0.000 sec)

$ sqlite3mysql --sqlite-file /home/strct/dev/ddnet-maps/ddnet-server-2022-12-10.sqlite --ignore-duplicate-keys --mysql-insert-method IGNORE --sqlite-tables record_race record_teamrace record_saves --mysql-password 'PW2' --mysql-host 'localhost' --mysql-database teeworlds --mysql-user teeworlds
```

Looks like mysql still works as expected with UTC as timezone (new ranks still show as "5 secs ago"). And the transferred ranks have the correct timestamp set.
