### ISSUE TITLE
All ranks stay in _backup tables now?!

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6106]
On all servers I'm seeing many ranks in _backup tables, even when there seem to be no network problems. In combination with https://github.com/ddnet/ddnet/issues/6105 this is causing duplicate ranks.
@Zwelf

**Comment by Zwelf** [comment]
That is not good. Does this affect all tables or only record_race? Unfortunatly I can only really start investigating in the evening.

Yes we store and handle timestamps as utc: https://github.com/ddnet/ddnet/blob/7e848131aa47d83306641fa7a15422129aa02d51/src/game/server/scoreworker.cpp#L407

I its using utc timestamps everywhere.

**Comment by def-** [comment]
All of them, also teamrace and saves.
My quick fix:
```
begin;
delete record_race from record_race inner join record_race b on record_race.Map = b.Map and record_race.Name = b.Name and record_race.Time = b.Time and record_race.Timestamp != b.Timestamp and DATE_SUB(b.Timestamp, INTERVAL 1 HOUR) = record_race.Timestamp and record_race.Timestamp >= "2022-12-06" and b.Timestamp >= "2022-12-06";
commit;
begin;
update record_teamrace inner join record_race b on record_teamrace.Map = b.Map and record_teamrace.Name = b.Name and record_teamrace.Time = b.Time and record_teamrace.Timestamp != b.Timestamp and DATE_SUB(b.Timestamp, INTERVAL 1 HOUR) = record_teamrace.Timestamp and record_teamrace.Timestamp >= "2022-12-06" and b.Timestamp >= "2022-12-06" SET record_teamrace.Timestamp = b.Timestamp;
commit;
begin;
delete record_saves from record_saves inner join record_saves b on record_saves.Map = b.Map and record_saves.Savegame = b.Savegame and record_saves.Timestamp != b.Timestamp and DATE_SUB(b.Timestamp, INTERVAL 1 HOUR) = record_saves.Timestamp and record_saves.Timestamp >= "2022-12-06" and b.Timestamp >= "2022-12-06";
commit;
```

**Comment by def-** [comment]
I have reverted https://github.com/ddnet/ddnet/pull/5948 on official servers temporarily until we have a solution for this and #6105.
