### ISSUE TITLE
Swap timeout sometimes resets

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6155]
![image](https://user-images.githubusercontent.com/2335377/208268811-7e44437c-853e-40ce-88bd-de950bc6ddad.png)
As reported on Discord by bencie. I have seen this too

**Comment by def-** [comment]
It uses the last swap time of the team you are in, so if someone in team 0 requests a swap too, then your time gets reset. This makes no sense for team 0

**Comment by Chairn** [comment]
Is it the same problem as https://github.com/ddnet/ddnet/issues/5184 ?
