### ISSUE TITLE
suggesting (sign , filters servers novice >insane)

### ISSUE THREAD

**Issue by hussainx3** [ddnet/ddnet#6174]
![4444444](https://user-images.githubusercontent.com/75770812/208919925-e762b50c-fc56-4b0b-b3ff-3151487ee1eb.png)
i always looking for map unfinished and i bad in remember maps name so always unpurposely i join this maps i don't like
 ( will be nice if i can just put sign dislike on it)
 
![555555](https://user-images.githubusercontent.com/75770812/208922024-878eb9f8-b11e-46be-979e-df9bb1740def.png)
and this i think is should be first thing in Filters but still not exist
for example i want maybe hide insane server(it's impossible for me anyway) or i want see only novice maps

**Comment by def-** [comment]
Write the names of the maps you don't like in Exclude in search, use `;` to separate multiple entries.

**Comment by def-** [comment]
I don't think we should filter out too much, especially by default, or giving players the chance. If someone just selects Novice, and there currently are no Novice servers in his region, he won't see any other servers and end up not playing. Even though he might join a Moderate server and with the help of some nice players manage to finish it, or they might end up switching to a Novice map for him.

**Comment by hussainx3** [comment]
hmm another thing
![666666666](https://user-images.githubusercontent.com/75770812/208926823-3ed07ec6-99a3-4e5a-8856-ee1d6ed1254f.png)
make they in one page can make them useful more i always stay in Filter bcs i always use it
![777777777](https://user-images.githubusercontent.com/75770812/208927435-2d191159-7b62-4c61-8bd4-49dfb67df486.png)
check info ( to know who in server) or if my friends online (i never check this feel lazy to change and back for filter)
