### ISSUE TITLE
ECON usage

### ISSUE THREAD

**Issue by Avolicious** [ddnet/ddnet#6189]
I am interested if there are some users of eCON out there. Is it widely used?

**Comment by def-** [comment]
Official servers are using fifo exclusively at DDNet

**Comment by Avolicious** [comment]
KoG aswell, only FIFO

**Comment by danielkempf** [comment]
AwB too, only FIFO

**Comment by danielkempf** [comment]
But there are some usecases econ would be cool :)

**Comment by ChillerDragon** [comment]
@jxsl13 made some projects and uses it for zcatch servers

https://github.com/jxsl13/TeeworldsEconDiscordModerationBot
https://github.com/jxsl13/TeeworldsEconVPNDetectionGo
https://github.com/jxsl13/TeeworldsEconVPNDetection

And this is used on my vanilla server and fokkonauts F-DDrace server

https://github.com/chillavanilla/TeeworldsEconMod

I also usually use econ for administration of servers over fifo

**Comment by fokkonaut** [comment]
I personally use econ from my mobile a lot, to help users with their accounts, and so on...
