### ISSUE TITLE
Dual-GPU detect default selected GPU

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#6200]
I'd like to be able to detect what GPU is selected as default on Windows for Vulkan, so if anyone has a modern laptop with a dual GPU, please enable the Vulkan backend -> check the order of the GPUs listed in settings -> graphics -> graphics cards (in the client).
Then change the default GPU to the one that is not the first entry and redo it.

If the order changes its clear, that the default GPU always comes first.
If not I've no idea if we can detect it.

It would be nice to know this to prevent ppl with NVIDIA optimus asking why the FPS are capped, since the bridge is slower than the integrated GPU. It would then match the OpenGL behavior so they either wouldn't ask, or would've asked anyway^^

I need this info before next release where we want to test vk default

**Comment by Robyt3** [comment]
I have an old "gaming" laptop that has an integrated Intel HD Graphics 4000 and an NVIDIA GeForce GTX 660M. In Windows I can choose which graphics processor to launch the game with, but in the game I don't get the menu to select a GPU, so it seems the game doesn't detect that there are multiple GPUs.

**Comment by Robyt3** [comment]
It seems that I can't launch the game with Vulkan and the integrated graphics. Windows always uses the NVIDIA GPU when I select the Vulkan backend (as shown in the log in the console). When I select the OpenGL backend then I can use both CPUs by selecting them in Windows, but I don't get a selection box in the game.

**Comment by Jupeyy** [comment]
ah too bad, yeah vulkan has to run on both GPUs
ty for testing tho

**Comment by szaross** [comment]
I have a Thinkpad P50 with Intel HD Graphics 530 and Nvidia Quadro M1000M.

When playing on Vulcan on Nvidia graphics (internal display) GPUs are listed as follows: 
-auto(Quadro M1000M)
-Intel HD Graphics 530
-Quadro M1000M
Changing GPU to Intel and restarting does not change the order of GPUs on the list

Using external display swaps Intel with Nvidia (2nd and 3rd) on the list. The behaviour stays the same.

**Comment by Jupeyy** [comment]
Thanks for testing. With changing I meant changing the default GPU in Windows it Nvidia control panel, could you test that too?

**Comment by szaross** [comment]
My bad.
Changing GPU in Nvidia control panel makes it go 2nd on the list.
auto(...) stays the same.
Intel:
-auto(Quadro M1000M)
-Intel HD Graphics 530
-Quadro M1000M
Nvidia:
-auto(Quadro M1000M)
-Quadro M1000M
-Intel HD Graphics 530

**Comment by Jupeyy** [comment]
That's the information I was looking for. Thanks again
