### ISSUE TITLE
Replace github actions with dockerfiles

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#6201]
I was wondering if it was a good idea to remove all the github action specific yamls in .github/workflows and replace those with dockerfiles. The CI would still run and build those dockerfiles so it should function the same way.

The advantage would be that dockerfiles are more portable than github workflows. Meaning they could also power gitlab pipelines or any other git cloud provider pipeline. Or even be run locally.

**Comment by def-** [comment]
Docker is not "free software" anymore, so I would be hesitant about making us dependent on a/another company. We could use a free alternative like Podman, but with it being less familiar to people I'm afraid this move might hurt people more than help.

**Comment by heinrich5991** [comment]
Dockerfiles would be more opaque to people looking into how to build stuff. It wouldn't explain what packages we install etc.

**Comment by ChillerDragon** [comment]
> Docker is not "free software" anymore, so I would be hesitant about making us dependent on a/another company. We could use a free alternative like Podman, but with it being less familiar to people I'm afraid this move might hurt people more than help.

I haven't touched podman yet but from what I heard its pretty much of a drop in replacement.

I can't be the only one that keeps pushing to github to debug the pipeline because locally everything works -.-

> Dockerfiles would be more opaque to people looking into how to build stuff. It wouldn't explain what packages we install etc.

We can replicated the same structure including the dependency installs in dockerfiles

**Comment by heinrich5991** [comment]
> I haven't touched podman yet but from what I heard its pretty much of a drop in replacement.

I've tried to use it, it doesn't seem to be a drop-in replacement.

> Also as of right now we are dependent on microsoft. Docker seems more independent to me.

I don't think we're particularly dependent on Microsoft due to Github actions.

**Comment by ChillerDragon** [comment]
oke

**Comment by Learath2** [comment]
It is particularly annoying to debug issues in github workflows, I'll give you that.

**Comment by def-** [comment]
Yes, I've also had it a few times where I can't reproduce an issue and have to add debugging echos all over and push 20 times to fix it, with this horrible 10 min turnaround time for each run breaking all concentration.

**Comment by def-** [comment]
I think you can run github actions locally with https://github.com/nektos/act, but I haven't tried

**Comment by Learath2** [comment]
> I think you can run github actions locally with https://github.com/nektos/act, but I haven't tried

This is extremely fragile and heavy. It took me hours to get it to work on podman and injecting github contexts in there is also very annoying

**Comment by def-** [comment]
This is my main complaint with all this move-everything-to-cloud-use-CI-everywhere etc, it's getting harder to run things locally. Seems like no good solution: https://stackoverflow.com/questions/59241249/how-to-run-github-actions-workflows-locally
