### ISSUE TITLE
No "CheckVersion" in bam.lua

### ISSUE THREAD

**Issue by Tardo** [ddnet/ddnet#622]
Is this intentional?

**Comment by heinrich5991** [comment]
Yes. It runs on bam 0.4 and 0.5.

**Comment by CytraL** [comment]
Nobody thinks about the standards around here? You oblige treat your mod in a special way for automated systems.

Is this going to be done with all the bam versions that come out?
If not... in the future people need read some documentation for know bam version?

**Comment by heinrich5991** [comment]
Yes, it is, where possible. `CheckVersion` unfortunately terminates the build process if there is a mismatch, so there is no easy way of calling that function without abandoning support for either bam 0.4 or bam 0.5.

**Comment by CytraL** [comment]
Ok, sounds good use an universal bam :)
If i use 0.5 for compile... binary is located in 'build' folder?
Why like support 0.4?

**Comment by heinrich5991** [comment]
https://github.com/ddnet/ddnet/pull/507#issuecomment-228601084

Basically because Teeworlds 0.6 only compiles with bam 0.4.

**Comment by CytraL** [comment]
Ok! thx heinrich5991!

**Comment by CytraL** [comment]
The last thing...  why not use, for example:
 - bam.lua  -> 0.4 (for now...)
 - bam50.lua -> 0.5

and call it: bam -s bam50.lua

You can use "CheckVersion"

**Comment by heinrich5991** [comment]
@CytraL You can make a pull request to insert a commented-out `CheckVersion("0.5")` if you want. I guess that would be picked up by your script, wouldn't it?

**Comment by CytraL** [comment]
Yes... but for now works without CheckVersion.. i force use '0.4' when not detect bam version. The problem can appear in the future and new possible bam versions and if this mod not upgrade the "bam.lua" for work with stable bam (in the future)

Cheers and thanks... i'm not work on teeworkds no more ;) if my app fails compiling DDNet in the future... it fails no problem :D

**Comment by def-** [comment]
We're switching to cmake anyway.
