### ISSUE TITLE
Only translate graphics errors with a user-defined action

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6223]
I noticed that there are lots of new strings to translate for 16.7, not sure if we win anything by translating these very specific error messages or just confuse the translators and create additional work for us to translate the errors back into English.

But when we get the error message in Russian it will be harder for us to understand 😄 Can the user do anything with "Submitting to graphics queue failed." or "No vulkan queue family properties found."? The ones with an action like "Failed during initialization. Try to change gfx_backend to OpenGL or Vulkan from settings_ddnet.cfg in the config directory and try again." seem helpful.

**Comment by heinrich5991** [comment]
> [5:23 PM]heinrich5991: alternatively, include an error code
> [5:23 PM]heinrich5991: rustc does it
> [5:23 PM]heinrich5991: V-0001
> [5:23 PM]heinrich5991: to V-0015

**Comment by def-** [comment]
Another easy fix would be to mark them as [Graphics Errors] so it's clear those are not that important to translate.
