### ISSUE TITLE
Moderators timeout upon receiving too many rcon lines

### ISSUE THREAD

**Issue by bencie** [ddnet/ddnet#6224]
I encountered this issue when I tried to dump_log, dump_antibot and status using 1 bind on a populated server. With some testing, I noticed that every single time i hit the bind, I can only receive 174 lines (6 pages) of rcon before it stops, and doesn't finish printing everything. When I hit this bind on a populated server, it causes me to be unable to read/send messages, emotes, but I can still play and interact with the game for about a minute, after that I get timed out.
The bind used: bind x "rcon_login name password; rcon show_ips 1; rcon dump_log; rcon status; rcon dump_antibot"

**Comment by murpii** [comment]
#3691
