### ISSUE TITLE
Color picker label is not width constrained

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet#6237]
This causes the picker to be potentially moved more right than expected when using non english languages:
![image](https://user-images.githubusercontent.com/10178629/210888854-525a1bf4-0662-4c65-af0a-044e4c55d9df.png)

**Comment by VoxelDoesCode** [comment]
I looked into this: It turns out none of the labels are width constrained. One example is when you set your language to Dutch, and go to Appearance > Chat.
![image](https://user-images.githubusercontent.com/95713843/220259139-232e08dd-d3c4-4f5b-968a-15bd40c0f501.png)4ff27042.png)
