### ISSUE TITLE
Invisible Ammo

### ISSUE THREAD

**Issue by Adrinaline** [ddnet/ddnet#625]
Hey there,
I wanted to do a mod based on the DDrace mod.
So first of all i downloaded this ddnet source on github, compiled it (Linux, raspbian), and started a lan server. All fine! No problems.

After that i changed the mod name in path: "ddnet-10.3.5\src\game\server\gamemodes\gamemode.h"
from:
#define GAME_NAME "DDraceNetwork"
#define TEST_NAME "TestDDraceNetwork"
to:
#define GAME_NAME "Banger"
#define TEST_NAME "TestBanger"
i compiled it on Linux "Raspian" (without installing any packets), no errors, but after i startet a lan server and shooted with gun, grenade,... i couln'd see my Ammo.

Did i do something wrong or is this a bug in the source?
Greetings Adrenaline

**Comment by timakro** [comment]
I could imagine there are problems with anti ping, do you have that enabled?

**Comment by timakro** [comment]
The client decides whether the server is a DDNet server or not by looking at the gametype. In the other direction when connecting to a server the client sends a special network message to tell the server that it is a DDNet client. There are some small protocol changes between DDNet clients and servers, for example a tweak to the network messages that are sent when a projectile is fired. When you change the gametype you get a situation where the server knows that the client is a DDNet client and expects it to support the protocol changes but the client thinks that the server is a vanilla server and therefore expects the vanilla protocol.

A quick fix would be to make the server simply ignore this special network message and therefore making it treat the client as a vanilla client. To achieve that you could simply comment out this code block on the server https://github.com/ddnet/ddnet/blob/5b512989cb82730b63c2dc332b15aca9c6d8333c/src/game/server/gamecontext.cpp#L1553-L1607. Although there might be some protocol changes other than the projectile tweak which the DDNet client accepts regardless if it thinks that the server is DDNet or not. So you could search for cases like that and in case your find some still support those parts of the protocol changes. But that would probably not be worth it, I doubt there is even one case like that.

**Comment by Adrinaline** [comment]
@timakro 

Wow, thanks timakro for the fast responding!
Your answer is good explained and very helpful!
I will try that, the server will ignore this 
> special network message
.^^

Thanks!
Adrenaline

**Comment by timakro** [comment]
No problem, good luck!

**Comment by Adrinaline** [comment]
Ty :),
Now i can see the projectile, thanks a lot^^
