### ISSUE TITLE
DoS attack sample code

### ISSUE THREAD

**Issue by MageDelfador** [ddnet/ddnet#6273]
[redacted]
I hope this can help solve the problem

**Comment by def-** [comment]
Hey @MageDelfador , thanks for trying to help. I guess the code shouldn't be public though. We'll discuss this internally. I also like the points in scoreboard you implemented in https://github.com/MageDelfador/DDNet-show-points-in-game, really impressive to do that by rewriting memory. We have an idea to implement that in the client itself: https://github.com/ddnet/ddnet/issues/6140#issuecomment-1353456152
