### ISSUE TITLE
Speeder tiles in game layer cause entities in front/switch layer to move up continuously

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#6315]
https://user-images.githubusercontent.com/23437060/215289197-09fc8249-dadd-47b3-b1f6-6e728459cd66.mp4

[speeder_bug.map.zip](https://github.com/ddnet/ddnet/files/10528186/speeder_bug.map.zip)

**Comment by fokkonaut** [comment]
What exactly is the issue here? Could you record the video with overlay entities enabled?

**Comment by Robyt3** [comment]
Another video with entities enabled:

https://user-images.githubusercontent.com/23437060/222767692-67de9abd-be43-4767-8c55-cfb12f4f7594.mp4

Also see the map above.

**Comment by fokkonaut** [comment]
And whats the bug? Thats expected behaviour, you have to place more arrows, to form a path

**Comment by Robyt3** [comment]
Oh. I guess I got confused by the description and thought the speeders were supposed to change the rotation speed of the lasers, but that's determined by the individual type of the laser. So the speeder just don't work when they are on the front layer, but I guess that's expected from a bunch of tiles.
