### ISSUE TITLE
Add `/lasttp` command to teleport to last checkpoint in practice

### ISSUE THREAD

**Issue by trikiman** [ddnet/ddnet#6318]
u already have /tp on practice
what about /lasttp
it will be tp on your last tp. it will very helpful.

**Comment by Chairn** [comment]
In general, i believe we could enable some more testing command in practice, such as totele, totelecp, etc.

**Comment by trikiman** [comment]
i think most usefull after /tp will be /lasttp and then totele totelecp adn etc. 
...no i think most usefull will be /lasttp and then /tp  most ppl will be use it for training. simple: they will be use /tp 1 time and then 50x /lasttp for training and repeat and repeat.

**Comment by trikiman** [comment]
Maybe bettter /tp with some cmd
like /tp {last:1,0} {weapon:sg,rocket,laset,jetpack} {savespeed:1,0} {noweapon:1,0} {unfrezze:1,0}  and other possible cmd
