### ISSUE TITLE
gen_lib.sh there is a problem

### ISSUE THREAD

**Issue by PCX-LK** [ddnet/ddnet#6320]
When cloning/compiling the SDL
This script outputs these
![image](https://user-images.githubusercontent.com/62936489/215941622-03ce628f-4c17-4f87-8e38-21104f7b553e.png)
But that's what is actually compiled
![image](https://user-images.githubusercontent.com/62936489/215941655-060606e7-8ae7-43fe-988c-6a255317ed4f.png)
Not SDL2, but SDL3

**Comment by def-** [comment]
Where are you getting your libSDL version from?

**Comment by PCX-LK** [comment]
> Where are you getting your libSDL version from?

I didn't make any changes, just ran
```
scripts/compile_libs/gen_libs.sh .. /DDNET-lib android
```

**Comment by Jupeyy** [comment]
yeah the script simply builds from master/main branch.. you can temporarily ues a stable release i guess in the script files

as soon as they release SDL3, we probably switch to it anyway:tm:

**Comment by PCX-LK** [comment]
> yeah the script simply builds from master/main branch.. you can temporarily ues a stable release i guess in the script files
> 
> as soon as they release SDL3, we probably switch to it anywaytm

I tried specifying the "SDL2" branch to compile and the result was exactly what the script wanted
