### ISSUE TITLE
Add option to only reset jump on dummy switch

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#6331]
There is ``cl_dummy_resetonswitch`` for making sure inputs never stuck on dummy switch.
But I would make the bold statement that jump is one of the least needed inputs to ever be stuck.
So it would be nice to be able to opt out of it in favor of avoiding annoying fails due to accidental jump stucks while keeping the hook/dir/fire stuck on switch active.

**Comment by heinrich5991** [comment]
No, dummy is too strong already.
