### ISSUE TITLE
parameter cl_prediction_margin doesn't save

### ISSUE THREAD

**Issue by mwinkens** [ddnet/ddnet#6332]
parameter `cl_prediction_margin` is missing the SAVE flag
see https://github.com/ddnet/ddnet/blob/e09b4eb754bcf523054896e908df445adadcd9a6/src/game/variables.h#L24
this drives me nuts.

git blame @trml

**Comment by Chairn** [comment]
You can add cl_prediction_margin 123 to your autoexec_client.cfg file though
