### ISSUE TITLE
memory leak with entities

### ISSUE THREAD

**Issue by Henningstone** [ddnet/ddnet#636]
Every time you switch between gamemodes while using entities, memory is being leaked as the image for the entities is reloaded every time you go on a different gametype, but never unloaded. Look at the code, you'll immediately see what I mean:

https://github.com/ddnet/ddnet/blob/master/src/game/client/components/mapimages.cpp#L112

**Comment by heinrich5991** [comment]
The line referenced was https://github.com/ddnet/ddnet/blob/4c1053c6c4ce44bcc1f235c5141a6321c7c4c5de/src/game/client/components/mapimages.cpp#L112.
@Henningstone Please press `y` before copying the link from GitHub, this will create a permanent link. Your link is already outdated due to the fix. ^^

**Comment by Henningstone** [comment]
Oh, didn't know that you could press `y` there! Thanks for pointing it out, @heinrich5991
