### ISSUE TITLE
Bring back editor popups when gui is hidden

### ISSUE THREAD

**Issue by HiRavie** [ddnet/ddnet#6385]
Some recent update has broken editor popups when the gui is hidden, which now got fixed by removing the popups completely in that situation. It would be nice to get a proper fix since editing quads while gui is hidden is a useful little feature that even vanilla client has.

**Comment by def-** [comment]
@Robyt3

**Comment by Robyt3** [comment]
The popups are part of the GUI so it felt weird to me that they are shown when the GUI is hidden (#6177). I guess we could try to only show the quad point, quad pivot and sound source popups while the GUI is hidden and close the other popups. Or is there a use for any other popup while the GUI is hidden? Tough it would be easier to show all popups when the GUI is hidden, although I consider it's inconsistent.
