### ISSUE TITLE
Zoom Editor feature freeze bug

### ISSUE THREAD

**Issue by AssassinTee** [ddnet/ddnet#6390]
Activating Zoom, zooming out of the map (mousewheel down) and setting really high zoom values might freeze or even crash your game.

![screenshot_2023-03-07_22-51-04](https://user-images.githubusercontent.com/821401/223562950-be2b4e57-22d3-4d3e-8cf1-539638db42d1.png)

**Comment by Robyt3** [comment]
Closed by #7390.
