### ISSUE TITLE
Typing umlaut dots makes the chat consume all input on macOS

### ISSUE THREAD

**Issue by nzyuzin** [ddnet/ddnet#640]
Steps to reproduce on macOS:

1. Open chat
2. Type alt-u (umlaut two dots)

Result: all input is consumed by the chat field: enter, esc, f1, etc. don't function; all typed displayed symbols go into chat field. The game is practically dead as the only action a user can take is to close it.

Could be related to #547.

![umlauts_bug](https://cloud.githubusercontent.com/assets/4072673/23534138/123db700-ffb6-11e6-88e4-fba725852189.jpeg)

**Comment by H-M-H** [comment]
This indeed is the same thing, currently entering combining characters does not work properly on macOS.

**Comment by def-** [comment]
This should be fixed in HEAD.
