### ISSUE TITLE
macOS fullscreen: Opening menu in game will force game to go windowed and fullscreen back

### ISSUE THREAD

**Issue by nzyuzin** [ddnet/ddnet#641]
Steps to reproduce on macOS:
0. Enable fullscreen
1. Join a server
2. Press `esc` to open ingame menu

The game will for a moment switch to windowed mode, then reenter fullscreen (screen will blink and user's desktop will be seen) and only then show ingame menu. Same happens when closing menu with `esc` or when exiting consoles with `esc`.

**Comment by H-M-H** [comment]
Duplicate of #548
