### ISSUE TITLE
``cmake -DCLIENT=OFF`` no longer works

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#6412]
```
CMake Error at CMakeLists.txt:3022 (install):
  install TARGETS given target "game-client" which does not exist.


CMake Error at CMakeLists.txt:3048 (install):
  install TARGETS given target "game-client" which does not exist.
```

@Kaffeine any ideas?

**Comment by Kaffeine** [comment]
On it. I hotfixed like that for my fork: https://github.com/infclass/infclass-client/commit/6c1eb402b000f4af361d8ff86eac30582ddfe6c6 and I thought it was broken before my commit.

**Comment by ChillerDragon** [comment]
> On it. I hotfixed like that for my fork: [infclass@6c1eb40](https://github.com/infclass/infclass-client/commit/6c1eb402b000f4af361d8ff86eac30582ddfe6c6) and I thought it was broken before my commit.

Thanks for sharing a hotfix

**Comment by Kaffeine** [comment]
I confirm, it is a regression after commit https://github.com/ddnet/ddnet/pull/6345/commits/3ba80cccaed47621df6cf704ef55e6e88ff06f1e

**Comment by Kaffeine** [comment]
Oh, I see now. The hotfix is the correct fix.

https://github.com/ddnet/ddnet/commit/3ba80cccaed47621df6cf704ef55e6e88ff06f1e#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL2973-L2976

```
 set(CPACK_TARGETS
-  ${TARGET_CLIENT}
-  ${TARGET_SERVER}
+  game-client
+  game-server
   ${TARGET_TOOLS}
 )
```

`TARGET_CLIENT` and/or`TARGET_SERVER` were conditionally undefined.
