### ISSUE TITLE
increase max bind length pls

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#642]
I know i could work with the `exec` command and use several setting files, but the max bind length is annoyingly short.
Can't we just double it somehow?

for example my toggle hud bind doesn't fit in ._.

`bind m "toggle cl_showhud 1 0;toggle cl_nameplates 1 0;toggle cl_showchat 1 0;toggle cl_showkillmessages 1 0;toggle cl_show_broadcasts 1 0"`

the last two values get eaten by the evil maximum and if i launch the client and check the settings agian i see:

`bind m "toggle cl_showhud 1 0;toggle cl_nameplates 1 0;toggle cl_showchat 1 0;toggle cl_showkillmessages 1 0;toggle cl_show_broadcasts "`

**Comment by necropotame** [comment]
This can be solved by using some sort of dynamic strings. Someone is against them?

**Comment by Learath2** [comment]
TW in general is against dynamic allocations but it seems we have said fuck you to that in DDNet long ago :)

**Comment by heinrich5991** [comment]
It's important to keep allocations out of the game. Since `bind`s aren't created during the game but by the user, dynamic allocations are ok.
