### ISSUE TITLE
Antialiasing in menu and editor

### ISSUE THREAD

**Issue by Marmare314** [ddnet/ddnet#6424]
Maybe we could have two seperate settings for FSAA, one for ingame and one for the menu/editor. Because the setting can be changed without restarting the game I was hoping that this might be possible. This would make the menu/editor look a lot better without affecting the ingame performance.

**Comment by Robyt3** [comment]
Changing the FSAA setting makes my screen flash black for a moment, so changing it on-the-fly wouldn't be inconvenient. Does FSAA even do anything noticeable ingame? The only thing where I notice FSAA is with the round corners of the UI rectangles, which are a smoother with FSAA enabled.

**Comment by Marmare314** [comment]
The corners are the only thing I notice too. But this makes the game look a lot more polished to me.

**Comment by Marmare314** [comment]
As was mentioned some clients flicker when changing FSAA and for some it requires a restart, so this does not seem possible.
