### ISSUE TITLE
auth_remove command unexpectedly removes sv_rcon_helper_password

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#6427]
When using the command `auth_remove <user>` to remove an authorization, it seems to also remove the `sv_rcon_helper_password` without any clear explanation, but the `sv_rcon_mod_password` remains functional.

**Comment by Robyt3** [comment]
Can you provide the exact sequence of commands to replicate this?

**Comment by murpii** [comment]
> Can you provide the exact sequence of commands to replicate this?

Crude DDNet Test server setup:
`sv_rcon_helper_password test4321` as public login
`sv_rcon_mod_password <[REDACTED]>` as mod login for official testers
and a bunch of moderator auths:
`auth_add_p foo admin <hash> <salt>`
`auth_add_p bar mod <hash> <salt>`
(Can be generated here: https://ddnet.org/modauth/password.html)

To replicate the issue:
Start Test server -> Login into rcon as foo(admin) -> Remove bar(mod) using `auth_remove bar` -> Log out of rcon -> Leave `username` empty and hit enter -> `test4321` as password -> Wrong password

**Comment by Robyt3** [comment]
I can't reproduce this on a local server by following these instructions. The only way to cause this is by explicitly removing the auth key `default_helper`, which represents the password set with `sv_rcon_helper_password`. Removing any other auth key does not prevent the default helper from logging in (both with username `default_helper` and without username). Does it also happen to you on a local server or is this somehow specific to the test servers?

**Comment by murpii** [comment]
> I can't reproduce this on a local server by following these instructions. The only way to cause this is by explicitly removing the auth key `default_helper`, which represents the password set with `sv_rcon_helper_password`. Removing any other auth key does not prevent the default helper from logging in (both with username `default_helper` and without username). Does it also happen to you on a local server or is this somehow specific to the test servers?

I haven't tested this on locally. This issue happens on our test servers. It's definitely reproducible there.

**Comment by murpii** [comment]
You can find the current setup in the ddnet-scripts repository. It should still be up-to-date.
