### ISSUE TITLE
Enable -Wextra warnings

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#643]
DDNet currently generates a lot of `-Wextra` warnings, maybe these could be fixed and then `-Wextra` could be enabled while building.

**Comment by heinrich5991** [comment]
Also, `-Wformat=2` with appropiate attributes on `dbg_msg` and similar would be nice.

**Comment by heinrich5991** [comment]
`-Wshorten-64-to-32` (clang) or equivalently `/wd4267` (MSVC).

**Comment by def-** [comment]
Don't think we should enable `-Wextra`. Lots of warnings about unused parameters, makes merging with any other TW project harder.
