### ISSUE TITLE
Return codes for success and failure (`int`, `bool`)

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#6436]
How do we want to communicate success and failure in the code base? According to https://github.com/ddnet/ddnet/pull/6429#issuecomment-1472749751, we're currently using 0 as success and non-0 as failure for functions returning `int`. We use `true` as success and `false` as failure for functions returning `bool`.

These are currently opposites, and since you can't see (at a call site) whether a function returns `int` or `bool`, it seems error-prone to me. I think it'd make sense to unify this somehow. E.g. #6429 moves this towards `true` for success.

@Robyt3 argues that he finds `if(function()) { /* success */ }` more readable than `if(function()) { /* failure */ }`.

For functions returning different kinds of errors, it might make more sense to treat 0 as success because there's usually one success path but many failure paths. I'm not sure if we even use that in the code base. `str_hex_decode` returns multiple error codes, but I don't think they're used by any caller.

Prior art
---------

curl uses 0 as success. zlib uses 0 as success. WINAPI mostly uses non-0 as success. I think most POSIX APIs that don't return a value use 0 as success.

**Comment by def-** [comment]
New functions should use bool return types in my opinion.

**Comment by heinrich5991** [comment]
Should they return `true` for success or failure?

**Comment by def-** [comment]
true for success of course.

**Comment by Learath2** [comment]
`bool` returns and `true` for success is what I'd also vote for. If we were sticking with C, I'd probably prefer `int` returns and `0` for success.

For functions returning different kinds of errors I'm honestly not sure how best to handle them, should they maybe be using `enum`s for their return type? With an `enum` class we could maybe override the `bool` cast. `if(!function()) { /* handle error */ }` is a really pretty pattern so it's quite annoying that we can't have it for those kinds of functions unless we pick `0`/`false` for success.

**Comment by Robyt3** [comment]
For `enum`s I think both `if(foo() != FOO_SUCCESS) { /* handle error */ }` and `if(foo() == FOO_SUCCESS) { /* handle success */ }` are good patterns.

**Comment by edg-l** [comment]
true for success

**Comment by heinrich5991** [comment]
`true` for success.
