### ISSUE TITLE
Scoreboard bug on precise times

### ISSUE THREAD

**Issue by mwinkens** [ddnet/ddnet#6453]
The Serverhighscore has a rounding problem with times in thousands:
server highscore: 22.995 sec
scoreboard (showing 00:23):
![screenshot_2023-03-23_00-23-21](https://user-images.githubusercontent.com/104770531/227063685-3cbb2d3d-7c57-4f61-8686-a514a2d79c69.png)

This is a result from using `str_time_float` which in turn is using `llroundf` instead of `lfloorf`

ping @hopetez

**Comment by def-** [comment]
This comes from https://github.com/ddnet/ddnet/pull/3487
