### ISSUE TITLE
logfile command not logging local console to file

### ISSUE THREAD

**Issue by bencie** [ddnet/ddnet#6458]
Recently the "logfile" command doesn't work for me, my local console doesn't get output to the file that was specified in the "logfile" command. It seems like the text file stopped updating on 2022 December 5th, and hasn't been updated or modified since then. I tried to delete the file so that it hopefully creates it again, but it didn't.
Here's some of my settings:
> loglevel = 3
> logfile = innerlog.txt
(I changed loglevel from 4 to 3 in an attempt to somehow try and fix this, neither worked)
Let me know if any more info is required

**Comment by def-** [comment]
That should be `logfile innerlog.txt`, not `logfile = innerlog.txt`

**Comment by bencie** [comment]
Sorry for the confusion, i set it as "logfile innerlog.txt" , not with the equals sign, that was just a way to show what my current values are ^^

**Comment by def-** [comment]
@heinrich5991 I can reproduce, doesn't work.

**Comment by def-** [comment]
@bencie I think the log files moved to be written to config directory.

**Comment by bencie** [comment]
Okay thanks, didn't realize

**Comment by def-** [comment]
Caused by this change by @Robyt3 , seems intentional:
```
a62bf7c3342c736df9b731664ca2637b7879dcf4 is the first bad commit
commit a62bf7c3342c736df9b731664ca2637b7879dcf4
Author: Robert Müller <robytemueller@gmail.com>
Date:   Sat Nov 5 16:20:51 2022 +0100

    Write log files to storage unless given as absolute path

 src/engine/client/client.cpp | 2 +-
 src/engine/server/main.cpp   | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)
```
