### ISSUE TITLE
Ninja Bug and noticable client slowdown

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#6464]
The ninja attack direction is wrong and the client feels extremely janky with each attack. Only happens after crossing the startline.
Reproduced on map "Rapid":

https://user-images.githubusercontent.com/60477660/227745827-06e1f9f7-fc9a-4a66-89da-b8273a08cafc.mp4

Leftside: recorded with the bad commit
Rightside: recorded without the bad commit
```
e4157a744b720fb89216640f6586a61cd44a1bd1 is the first bad commit
commit e4157a744b720fb89216640f6586a61cd44a1bd1
Author: Zwelf <zwelf@strct.cc>
Date:   Thu Jan 5 20:24:06 2023 +0100

    Remove unused `m_FreezeTime == -1` state

    Reduces code complexity. Both `g_Config.m_SvFreezeDelay`[[1]] and `GetSwitchDelay(int Index)`[[2]] can only return non-negative numbers, therefore this is currently dead code and can be removed.

    The last time it was possible to pass a negative number was removed in https://github.com/ddnet/ddnet/commit/561ce6466671397979ed77f0cbf368f93f33361f#diff-29ffe32916052e1066eed938021aadfeb29f855d7c63d9c1ca3350aceffb79f3L1624

    [1]: https://github.com/ddnet/ddnet/blob/c8ea372d9851709c2fe4db7362bdc07d263079ff/src/engine/shared/config_variables.h#L213
    [2]: https://github.com/ddnet/ddnet/blob/c8ea372d9851709c2fe4db7362bdc07d263079ff/src/game/mapitems.h#L467

 src/game/client/prediction/entities/character.cpp | 15 +++++-------
 src/game/server/entities/character.cpp            | 30 ++++++++++-------------
 2 files changed, 19 insertions(+), 26 deletions(-)```

**Comment by Robyt3** [comment]
@Zwelf

**Comment by murpii** [comment]
Some additional info by JimmyJazz and SoapySandwich on discord:
>Soapy and I were about to post this bug with the janky ninja. Just wanted to say that it happens also when you interact with another tee. Ie getting hooked or hammered. We were in the process of recording it. We also had 2 other bugs we found that we were gonna show  trml.
Also just so you know, the bug would also happen on older clients prior to this latest version. It's just that this latest version makes it happen on every ninja. On prior versions, it would happen only on the first ninja. So not sure if that information would be important. Just a heads up.
