### ISSUE TITLE
Death effect got bigger?

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#6476]
Reported by @cyberfig probably related to https://github.com/ddnet/ddnet/pull/6439 ? @Robyt3

**Comment by fokkonaut** [comment]
https://cdn.discordapp.com/attachments/617614400739737604/1090255787248595034/DDNet_Client_2023-03-28_14-46-55.mp4

**Comment by fokkonaut** [comment]
https://user-images.githubusercontent.com/35420825/228240864-b07ec3f7-f152-4a82-bb26-e8bdd1c1bd3e.mp4

**Comment by Jupeyy** [comment]
fixed by linked pr
