### ISSUE TITLE
[Bug] changing name to the name of the best player will show time of the best player

### ISSUE THREAD

**Issue by the-ssd** [ddnet/ddnet#6483]
1. change you name to the name of the best player (on the map)
2. now your time is false

the best option is to implement accounts but this can time consuming
another problem is migration to accounts

if at some point account will be added please use a hash of the password instead of password itself for security

**Comment by def-** [comment]
This is kind of by design, since we don't have accounts yet, see https://github.com/ddnet/ddnet/issues/3411
