### ISSUE TITLE
Redundant timeout code generation code and client settings

### ISSUE THREAD

**Issue by timakro** [ddnet/ddnet#649]
This code https://github.com/ddnet/ddnet/blob/a13cdc25b2695c2be3bc1b849f5ad957c344a106/src/game/client/gameclient.cpp#L336-L357 and the settings `cl_timeout_code` as well as `cl_dummy_timeout_code` are unused.

**Comment by heinrich5991** [comment]
Not entirely, no. They're used when the user explictly unsets `cl_timeout_seed`.

**Comment by timakro** [comment]
Didn't notice that, thanks.
