### ISSUE TITLE
need report button

### ISSUE THREAD

**Issue by p6oy** [ddnet/ddnet#6498]
when i need reporting someone, it is difficult.

**Comment by def-** [comment]
We had a /report command, it kept being abused. You can report in Discord in #reports instead.

**Comment by p6oy** [comment]
i am a chinese and as u know, i cannot use discord









p6oy
 ----------Reply to Message----------
 On Thu, Apr 6, 2023 13:52 PM Dennis ***@***.***&gt; wrote:

  

 
We had a /report command, it kept being abused. You can report in Discord in #reports instead.

**Comment by def-** [comment]
I think the Chinese community have their own system for reports, right? The Chinese moderators are not on Discord either anyway.

**Comment by p6oy** [comment]
so that is the problem. i dont even know there is a chinese community. the info of the server always leads me to the ddnet.org and discord.









p6oy
 ----------Reply to Message----------
 On Thu, Apr 6, 2023 14:44 PM Dennis ***@***.***&gt; wrote:

  

 
I think the Chinese community have their own system for reports, right? The Chinese moderators are not on Discord either anyway.

**Comment by def-** [comment]
If you have DDNet client set to Simplified Chinese, on the start menu you can click on "开黑啦" to land on https://chat.teeworlds.cn/
