### ISSUE TITLE
replace images with the same name not working anymore

### ISSUE THREAD

**Issue by WaRNe0nx3** [ddnet/ddnet#6500]
can no longer replace images in the editor with the same name, this sucks while working on tilesets.
this used to work, now it displays "image named 'xxx' was already added." in red text.

I guess "readd" option was added for this case, but this doesn't work when the map/client was closed.

**Comment by def-** [comment]
@Robyt3 Sounds unexpected

**Comment by Robyt3** [comment]
Yes, readd was broken by adding the error messages. I can fix it more easily after #6492 is merged.
