### ISSUE TITLE
Debloat the Internet tab by hiding DDNet and KoG servers

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#6506]
Thoughts?

Two positives I can think of:
- Minimal Moderation Needed: Official servers are exclusively listed under their designated tabs.
- People will always be able to locate our servers and refrain from joining servers that falsely claim to be official DDNet servers.

This complements #5654

**Comment by def-** [comment]
Super annoying if you want to search for someone and need to check in 3 tabs.

**Comment by murpii** [comment]
Then a filter may be most appropiate I think. This would provide users with greater control over their search results and reduce the clutter in the tab.

**Comment by Vy0x2** [comment]
I think another order would be good:
DDNet, KoG, Other Servers, All Servers, Lan

Favorites could be moved into a filter? imo all servers/other servers are more often needed than favorites (who uses them?)

**Comment by def-** [comment]
I'd prefer https://github.com/ddnet/ddnet/issues/5654
