### ISSUE TITLE
discussion vs needs-discussion

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#6554]
We have two labels, https://github.com/ddnet/ddnet/labels/discussion and https://github.com/ddnet/ddnet/labels/needs-discussion, which seem to be applied in the same way. The description of "discussion" says it's a meta-discussion, whatever that might mean. Merge the two labels?

**Comment by Jupeyy** [comment]
Only thing i can think of is, needs discussion is more code releated, while discussion is like a conversation about smth

Maybe we want to rename, but do we want to loose this difference?

**Comment by Robyt3** [comment]
I agree that the labels are currently used somewhat inconsistently, but I think that it's useful to have some distinction.

Issues with https://github.com/ddnet/ddnet/labels/discussion are usually general discussions about something.

https://github.com/ddnet/ddnet/labels/needs-discussion to me means that there must be a discussion before solving the underlying issue/implementing a feature, but the discussion is not the goal of the issue.

**Comment by edg-l** [comment]
i agree with robyt

**Comment by edg-l** [comment]
i think it clears for now, you can reopen if you want to discuss more

**Comment by heinrich5991** [comment]
I'm gonna rename "discussion" to "meta-discussion".
