### ISSUE TITLE
Bors publicly hosted instance is deprecated

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#6558]
bors comments

> The publicly hosted instance of bors-ng is deprecated and will go away soon.
> 
> If you want to self-host your own instance, [instructions are here](https://github.com/bors-ng/bors-ng#how-to-set-up-your-own-real-instance).
> For more help, visit [the forum](https://forum.bors.tech/).
> 
> If you want to switch to GitHub's built-in merge queue, visit [their help page](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue).

**Comment by def-** [comment]
Makes sense to use the Github merge queue I think.
