### ISSUE TITLE
Rcon pages locked to 199

### ISSUE THREAD

**Issue by Vy0x2** [ddnet/ddnet#6569]
Is there a reason why the remote console is limited to 199 pages while the console is not?
I would be in favor of removing this cap

**Comment by Robyt3** [comment]
Each console's backlog is limited to 1 MB of messages (although this size also includes other message attributes). The maximum number of pages is dependent on the length of the lines. I just tested it and got to remote console page 247 with a `rcon "echo a"` bind.

**Comment by Vy0x2** [comment]
I see, weird coincidence that it was 199 in my case =) Should be fine then and thanks for looking into it.
