### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#657]
What do you prefer?

```
int function(void *very_long_arguments, void *indeed,
    int what_to_do_about_them)
```

```
int function(
    void *very_long_arguments,
    void *indeed,
    int what_to_do_about_them)
```

```
int function(void *very_long_arguments,
    void *indeed,
    int what_to_do_about_them)
```

etc.

Just asking because we have a lot of very long lines, and running `clang-format` over the code might improve readability.

**Comment by heinrich5991** [comment]
CC @deen @east @Learath2 @necropotame

**Comment by necropotame** [comment]
The second one is the most readable for me. Thanks for asking :)

**Comment by def-** [comment]
If you run clang-format, then it should be integrated in the CI, so that new PRs are checked for style automatically.

**Comment by Learath2** [comment]
1st,3rd,2nd in order of best to meh

**Comment by necropotame** [comment]
@Learath2, you know that in C++, one can just put the entire code in one line, and save a lot of break lines? :P :troll:

**Comment by Learath2** [comment]
I'm all for least amount of lines while keeping readability. F.e.giving braces their own line is pointless, braces around a single statement is pointless etc...

**Comment by PathosEthosLogos** [comment]
Is there anything in the Google coding style guidelines about this?

**Comment by H-M-H** [comment]
I prefer the 2. version.

What about this:
```
if(...)
while(...)
```
vs
```
if (...)
while (...)
```

It seems leaving out spaces there is more dominant:
```
> rg "(for|while|if|switch)\(" **/*.c* **/*.h | wc -l
8345
> rg "(for|while|if|switch) \(" **/*.c* **/*.h | wc -l
3434
```
Even though I like a space there better.

**Comment by def-** [comment]
2nd is better, but 1st is traditional TW style. The more we change, the harder it gets for others to merge ddnet stuff. do we want to care about that?

**Comment by H-M-H** [comment]
I would go for cleaning things up and adding some formatter also for CI as you proposed earlier.

**Comment by def-** [comment]
I think I tried that before and eeeee or someone else wasn't happy.

**Comment by heinrich5991** [comment]
I would stick to the original TW style as long as possible, it creates the least changes while maintaining a consistent style.

**Comment by H-M-H** [comment]
But keep in mind: even if we stick to original TW style there are already 3000+ occurrences only with extra spaces that would have to be changed to be consistent. So to be consistent in whatever way there has to be changed quite a lot.

**Comment by def-** [comment]
Please count correctly, exclude external libs:

    egrep "(for|while|if|switch)\(" src/**/*.{c,cpp,h} | grep -v "/external/" | wc -l
    8217
    egrep "(for|while|if|switch) \(" src/**/*.{c,cpp,h} | grep -v "/external/" | wc -l
    1333

**Comment by H-M-H** [comment]
Oops, forgot to exclude those, leaves us still 1000+.

**Comment by heinrich5991** [comment]
We don't have to change these immediately. If we ensure that new code adheres to the standard, we will hopefully converge to a reasonably consistent codebase.

**Comment by Learath2** [comment]
I vote not to change the existing code style. Not against some line
wrapping rules tho.

**Comment by eeeee** [comment]
clang-format ships with a script which lets you reformat only the lines you're changing: https://clang.llvm.org/docs/ClangFormat.html#script-for-patch-reformatting

We could try using that at least.

**Comment by edg-l** [comment]
I guess we can close this now since we auto format.
