### ISSUE TITLE
UI: Some text is invisible with the Vulkan backend

### ISSUE THREAD

**Issue by CAESIUS-TIM** [ddnet/ddnet#6572]
This is a problem from a chat group member and I am trying to seek more details from him. Not much hope...

He has reinstalled from Steam, and done nothing about `%Appdata%\DDNet\` and `...\common\DDraceNetwork\`

version: 16.9

![ddnet_issue](https://user-images.githubusercontent.com/60285058/236774674-84a97fb4-aa7c-432e-9768-9f8cabff657a.jpg)

https://user-images.githubusercontent.com/60285058/236774693-8564bb2c-7cb2-4bed-81ac-f821a3b9a05c.mp4

**Comment by Jupeyy** [comment]
https://wiki.ddnet.org/wiki/GFX_Troubleshooting#Some_text_is_invisible_with_the_Vulkan_backend

**Comment by CAESIUS-TIM** [comment]
> https://wiki.ddnet.org/wiki/GFX_Troubleshooting#Some_text_is_invisible_with_the_Vulkan_backend

thx!
