### ISSUE TITLE
Times in Scoreboard ordered incorrectly and Best Time is always shown

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#6594]
PeX — Today at 00:14
Wrong sort after new finishes. Sry if it was posted somewhere
![Image 1](https://media.discordapp.net/attachments/757720336274948198/1107793163453726720/screenshot_2023-05-16_01-07-34.png)

Skeith — Today at 03:38
shows a completely wrong time when someone just connects as well, weird
![Image 2](https://media.discordapp.net/attachments/757720336274948198/1107844385938341978/image.png)

Furthermore, I discovered that the diff for the best time is always shown, regardless of whether or not a person has completed the map previously.

Thanks to Skeith for testing:
![Image 3](https://media.discordapp.net/attachments/757720336274948198/1107846890827022467/image.png)

**Comment by Robyt3** [comment]
Should be fixed by #6616.
