### ISSUE TITLE
Pretty sure ``PACKER_BUFFER_SIZE`` is too high

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#6599]
PACKER_BUFFER_SIZE is set to 2048
and NET_MAX_PACKETSIZE to 1400

All packets bigger than NET_MAX_PACKETSIZE will be dropped and can not be sent. So why bother having a buffer that is 2048?

https://github.com/ddnet/ddnet/blob/22df50c9bda271fbef4e2c7c28793384d48e0a80/src/engine/shared/packer.h#L11

https://github.com/ddnet/ddnet/blob/22df50c9bda271fbef4e2c7c28793384d48e0a80/src/engine/shared/network.h#L58

PACKER_BUFFER_SIZE should be something like NET_MAX_PACKETSIZE - NET_PACKETHEADERSIZE

**Comment by heinrich5991** [comment]
`CPacker` just a generic buffer, no need to match the maximum packet size.

**Comment by ChillerDragon** [comment]
Isnt it just used for networking. Seems missleading to me as if i could fill the packer and send it over the network.
