### ISSUE TITLE
Use `enum` instead of two `bool`s for editor settings

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#6609]
Combine these two into one enum with three values:

https://github.com/ddnet/ddnet/blob/ac820ce62d2830dfa4d6e148c6da8541bda138d2/src/game/editor/editor.h#L1037-L1038

And combine these two into one enum with three values:

https://github.com/ddnet/ddnet/blob/ac820ce62d2830dfa4d6e148c6da8541bda138d2/src/game/editor/editor.h#L922

https://github.com/ddnet/ddnet/blob/ac820ce62d2830dfa4d6e148c6da8541bda138d2/src/game/editor/editor.h#L1057

**Comment by tarunsamanta2k20** [comment]
@Robyt3 what would be the three values?

**Comment by Robyt3** [comment]
For proof border selection (new enum `EProofBorder`):

- `PROOF_BORDER_OFF` (when `m_ProofBorders` is `false`)
- `PROOF_BORDER_INGAME` (when `m_ProofBorders && !m_MenuProofBorders` is `true`)
- `PROOF_BORDER_MENU` (when `m_ProofBorders && m_MenuProofBorders` is `true`)

For show tile selection (new enum `EShowTile`)

- `SHOW_TILE_OFF` (when `m_ShowTileInfo` is `false`)
- `SHOW_TILE_DECIMAL` (when `m_ShowTileInfo && !m_ShowTileInfoHex` is `true`)
- `SHOW_TILE_HEXADECIMAL` (when `m_ShowTileInfo && m_ShowTileInfoHex` is `true`)

**Comment by tarunsamanta2k20** [comment]
@Robyt3 I have defined those enemies. where should i set those conditions?

**Comment by Robyt3** [comment]
What I mean is that the usages of the two variables `bool m_ProofBorders` and `bool m_MenuProofBorders` should be replaced with just one variable `EProofBorder m_ProofBorders`. The variable `m_MenuProofBorders` can be removed. The conditions above describe when each new enum value should be used instead of the original two bool variables. For example if you find a condition `if(m_ProofBorders && m_MenuProofBorders)` in the old code then it should be replaced with `if(m_ProofBorders == PROOF_BORDER_MENU)` when using enums. An existing condition `if(!m_ProofBorders)` (checks if proof borders are off) should be replaced with `if(m_ProofBorders == PROOF_BORDER_OFF)`.

You can put the enum definition in `editor.h` close to the variable declarations.

Preferable handle the two enums `EProofBorder` and `EShowInfo` in two separate commits or PRs.

Also take a look at our style guidelines: https://wiki.ddnet.org/wiki/Development#Code_conventions

**Comment by tarunsamanta2k20** [comment]
@Robyt3 please join me as a member of your organization.
