### ISSUE TITLE
Move server browser secondary tabs to the top and use icons

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#6613]
|     On 0.7 the tabs are on the top and use icons:      |     We have the tabs at the bottom and use text:      |
|-------|----------|
|     ![upstream](https://github.com/ddnet/ddnet/assets/23437060/1a53d058-c108-490a-a2f2-94350a1338fe)      |        ![current](https://github.com/ddnet/ddnet/assets/23437060/c2f77af4-6502-45c7-9ace-7d8897e5f4bb)     |

A) Should we also move the tabs to the top? Tabs in other locations are also mostly at the top and not the bottom. We could also remove the "Friends" header in this case.

B) Should we use icons instead of text for the tabs?

**Comment by Robyt3** [comment]
Teeworlds uses custom images for those icons, but I think using the icon font consistently is preferable. Here are some of the alternatives I came up with:
- Alternative 1:
   - ![1](https://github.com/ddnet/ddnet/assets/23437060/d688dc1b-8d08-4967-afe3-c3e1d2f5103c)
   - My preferred choice.
- Alternative 2 (info icon not in a circle):
   - ![2](https://github.com/ddnet/ddnet/assets/23437060/927378af-85a9-4925-b5a0-5776eaf0ab3a)
   - Slightly more like the teeworlds icon.
- Alternative 3 (using "filter" icon for the filter instead of "list" icon):
   - ![3](https://github.com/ddnet/ddnet/assets/23437060/4cc18caf-9403-45b9-b09f-e5a5a62ddd95)
   - I'm not sure I like the "filter" icon. Maybe ["filter-list" from Font Awesome](https://fontawesome.com/search?q=filter-list&o=r) would be better, but it's only included in the Pro version.
- Alternative 4 (make server info the first tab):
   - ![4](https://github.com/ddnet/ddnet/assets/23437060/e60d9f06-72b1-4687-aea2-8d8e12b92d13)
   - I don't think it makes much sense and will only further confuse players after we already move the tabs to the top and use icons instead.

**Comment by heinrich5991** [comment]
LGTM, I like 1 or 2. The heart might also be a nice touch.

**Comment by murpii** [comment]
I like 2. It's worth considering swapping out the heart icon used in the "Players" column of the server browser with the one used in the filter, if you do end up with either 1-4.

<img src="https://i.imgur.com/cpnHSaZ.png" width="200" />

**Comment by sjrc6** [comment]
I like the bigger buttons but it's worth noting that the distance between those buttons and the "close" button is much further on 0.7 
![image](https://github.com/ddnet/ddnet/assets/22122579/87efae31-a89b-4f68-8eea-6ef3cf24513a)
![image](https://github.com/ddnet/ddnet/assets/22122579/25942376-0d76-4f32-b28d-89345507c0c0)
