### ISSUE TITLE
Masterserver problems

### ISSUE THREAD

**Issue by RemakePower** [ddnet/ddnet#6637]
After my server shutdown 20 minutes, I find that master2.ddnet.org still have the my server's info on the list.
But master1.ddnet.org remove it.

**Comment by def-** [comment]
@heinrich5991 @TsFreddie Any problems with syncing master2?

**Comment by heinrich5991** [comment]
Yea, there were some connection problems around that time.

**Comment by Robyt3** [comment]
Closing under the assumption that it was a temporary problem. Please comment or reopen if it's still an issue.
