### ISSUE TITLE
Add scroll bar / mouse wheel scrolling to consoles

### ISSUE THREAD

**Issue by Vy0x2** [ddnet/ddnet#6642]
Would be a way better user experience and more convenient if it would be possible to scroll through the consoles with the mouse wheel or a scroll bar on the right side.

- Maybe add a user setting with how many lines a mouse wheel should skip (1-2-3-4 lines at a time)
- Look how this gets used and if its very good get rid of the pages in the console

idea by :v

**Comment by heinrich5991** [comment]
Scrolling with mouse indeed sounds like a good idea. Any particular reason why you closed this?
