### ISSUE TITLE
Clan looks like friend when there isn't any players with this clan

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6643]
Reported by Nice on Discord
![image](https://github.com/ddnet/ddnet/assets/2335377/4a023356-5b72-4910-96ec-41bfc6e87184)

**Comment by Robyt3** [comment]
Any suggestions how to differentiate better in this case? Upstream does it like this as well. The empty space before the clan is enough to differentiate for me. Maybe render offline clan friends with a purple background (clanmates = blue, offline = red, purple = both)? Or add some kind of icon and remove all of the empty space from offline friends list items.

**Comment by Robyt3** [comment]
With purple background color:

![purple-background](https://github.com/ddnet/ddnet/assets/23437060/25efbbd9-50f7-4d1f-b904-2f4bba75e2ce)
