### ISSUE TITLE
[Windows] Setting sound sample rate/frequency to 1 results in the game not starting

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#6653]
Cannot reprod on Linux

reported by ᲼᲼᲼᲼᲼᲼᲼᲼#0402 on discord

**Comment by Robyt3** [comment]
Cannot reproduce it on Windows either.

**Comment by Robyt3** [comment]
`snd_rate` is now clamped between 5512 and 384000 so this should hopefully no longer happen. If it still happens then we need more information about their audio hardware, audio driver and the lines about audio initialization from the console log.
