### ISSUE TITLE
long nickname

### ISSUE THREAD

**Issue by YasuhisaWise** [ddnet/ddnet#6681]
Return the old length of nicknames!
![image](https://github.com/ddnet/ddnet/assets/134871279/96b38e4c-0d6a-4651-ae16-4e615517a434)
![image](https://github.com/ddnet/ddnet/assets/134871279/d64d2199-dfe2-4ba2-bd23-7e50ba1459d3)
![image](https://github.com/ddnet/ddnet/assets/134871279/65666327-da6a-4989-a2bc-768b8cf7d9fe)
![image](https://github.com/ddnet/ddnet/assets/134871279/c01036d6-8d3b-4167-9384-25eb6ba9c353)
![image](https://github.com/ddnet/ddnet/assets/134871279/0e1506db-2eb9-45d1-8c53-243caba17379)
![image](https://github.com/ddnet/ddnet/assets/134871279/6fb1434f-f9ba-4330-9d21-05921757a09b)

**Comment by Jupeyy** [comment]
This is probably not going to happen.

But if you got more of these oldschoool screenshots you can share them, very interesting :D

**Comment by Chairn** [comment]
Feels like none of these are from ddrace server at the time. Last one is DDRace64 but i don't thnik it's affiliated to DDRace ?

**Comment by YasuhisaWise** [comment]
blocker "1 copy love box
![image](https://github.com/ddnet/ddnet/assets/134871279/81d7b4d3-94fe-4bc0-be57-487654b2293a)

**Comment by YasuhisaWise** [comment]
> This is probably not going to happen.
> 
> But if you got more of these oldschoool screenshots you can share them, very interesting :D

![image](https://github.com/ddnet/ddnet/assets/134871279/c01036d6-8d3b-4167-9384-25eb6ba9c353)
![image](https://github.com/ddnet/ddnet/assets/134871279/0e1506db-2eb9-45d1-8c53-243caba17379)
![image](https://github.com/ddnet/ddnet/assets/134871279/6fb1434f-f9ba-4330-9d21-05921757a09b)
