### ISSUE TITLE
Broadcast timer overwrites other broadcasts

### ISSUE THREAD

**Issue by Zwelf** [ddnet/ddnet#669]
Currently the broadcast timer overwrites other broadcasts. It would be nice if the broadcast timer doesn't get send while another broadcast is displayed.

**Comment by necropotame** [comment]
I've done it for InfClass. There is a system of priority and a system to avoid flooding (broadcast sent only if the text is different). The main point is that you must specify the level of the broadcast (and optionally the duration) when you emit it: 
````SendBroadcast(ClientID, "Teams are locked", BROADCAST_PRIORITY_GAMEANNOUNCE, BROADCAST_DURATION_GAMEANNOUNCE);````

**Comment by Ryozuki** [comment]
is this still happening?

**Comment by Zwelf** [comment]
Yes, the broadcast timer still overwrites other broadcasts.

**Comment by Ryozuki** [comment]
Ah you mean from the command /time ?

**Comment by Zwelf** [comment]
I am talking about the timer from #602, which is send to non-ddnet clients (e.g. vanilla client) via broadcast.
