### ISSUE TITLE
Editor autosave

### ISSUE THREAD

**Issue by HiRavie** [ddnet/ddnet#6693]
Arrow suggested to add an autosave feature to the editor, I think it's a good idea. It should save the current edited map once in a while in a special folder so the main maps folder doesn't get cluttered.

**Comment by def-** [comment]
See also undo feature in https://github.com/ddnet/ddnet/issues/6045

**Comment by VoxelDoesCode** [comment]
Yeah, but undo/redo is being worked on right now.

**Comment by Robyt3** [comment]
One issue is that saving will block the client while it saves, but I think that's unavoidable. We should show a popup or hint while autosaving and add a variable to configure the autosave interval in minutes (0 disables).
