### ISSUE TITLE
 ddrace scoreboard in PVP demos

### ISSUE THREAD

**Issue by teini94** [ddnet/ddnet#6700]
I suggest enable cl_ddrace_scoreboard 0 also for PVP(example ICTF) demos

**Comment by Robyt3** [comment]
Demo files don't contain the game type, so there is no way to correctly detect whether to show score or time right now. The `cl_ddrace_scoreboard 1` setting simply overrides the game type to be `DDraceNetwork` internally, so time score mode is used.

Maybe if we solve #8207 by adding the server record to the snapshot, we could instead assume time score mode for the scoreboard if a server record is in the snapshot. Or we define the score kind separately in the snapshot.

**Comment by heinrich5991** [comment]
> Or we define the score kind separately in the snapshot.

We already do, I think. `GAMEINFOFLAG_TIMESCORE`.

https://github.com/ddnet/ddnet/blob/b94dfc5b7757806317b1e4a6a78d1b3368bc396a/src/game/client/gameclient.cpp#L1777

So maybe we could drop the backward compatibility with old DDNet demos and thus start supporting PvP game mode demos.
