### ISSUE TITLE
Add file autocomplete for console ``exec`` command

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#6701]
I have a bunch of nested folders for all my client and server configs. And most of the time I have to look up the paths before running ``exec myfolder/somesubfolder/config.cfg`` because there is no way to list files from the console or even better auto complete paths.

It should autocomplete all active storage locations. This feature will leak the file structure but ``exec`` already leaks most file contents so thats not much worse from a security perspective i guess.

**Comment by ChillerDragon** [comment]
If I open a pr for this would it be merged? Or is this making the console too much of a full terminal again? @def-

**Comment by def-** [comment]
Would it only be for exec or how would you detect which command takes a file?

**Comment by ChillerDragon** [comment]
I thought only about exec but now that you mention it all config variables that expect a file name also could profit from it. Configs could get either a new config type or config flag. And for commands they could get a new argument type.

**Comment by ChillerDragon** [comment]
The complicated thing about supporting it for multiple commands and configs is which storage location they use. It should autocomplete all storage locations for reading but only the write storage location for writing. But auto completing all at all times would also be an improvement to the current situation.

**Comment by def-** [comment]
I think this is too complex to be worth it.

**Comment by ChillerDragon** [comment]
I personally only need it for ``exec`` would it be okay to just hardcode that command?

**Comment by def-** [comment]
I don't like it. If someone else thinks it makes sense and wants to review it, then go ahead.

**Comment by heinrich5991** [comment]
> I personally only need it for `exec` would it be okay to just hardcode that command?

No.

**Comment by ChillerDragon** [comment]
Well if neither all nor one work. We can close this issue as out of scope. Sadge.
