### ISSUE TITLE
Change country selection behavior in serverfilter

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#6746]
As of right now, if all countries are enabled, selecting one of the countries disables all other countries. This behavior is a bit annoying if you wish to exclude just one country while keeping all the others enabled.

To achieve that in the current way it's implemented, I have to re-select every single country and leave the one I don't want disabled and do that every single time I wish to change my selection. My current workaround is to leave one of the countries which I rarely play on permanently disabled.

Could this be changed? Maybe allow managing deselection via right click?

**Comment by def-** [comment]
@Robyt3 any idea?

**Comment by Robyt3** [comment]
Right-click behavior was changed in #3996.
