### ISSUE TITLE
Text and players go invisible and world's objects come blank on Linux

### ISSUE THREAD

**Issue by FlopffyGrape** [ddnet/ddnet#6760]
Like the title said, Here's the images that  I took:

![image](https://github.com/ddnet/ddnet/assets/98635550/bad49820-f846-4783-b476-e882a690617f)
![image](https://github.com/ddnet/ddnet/assets/98635550/e0b84353-9164-46e1-beb9-b33e086b5134)

This happen to me when I'm using Linux Ubuntu 22.04, I downloaded it from Steam and also try downloading it from ddnet website ( Linux x86-64 package ), even building it from source but the bug still cause..

Hope you can fix it. Thanks!

**Comment by Jupeyy** [comment]
Sounds like a problem in your setup?

Can you give details about your hardware and drivers?

**Comment by FlopffyGrape** [comment]
> Sounds like a problem in your setup?
> 
> Can you give details about your hardware and drivers?

Here
![image](https://github.com/ddnet/ddnet/assets/98635550/b51b13e8-b6ca-466a-abd5-c64e1359281d)

**Comment by Jupeyy** [comment]
Mh really old computer. Additionally you use wayland.

I guess you could try to manually set the graphics backend to opengl 1. Normally this is done automatically, but apparently your drivers act like they support a newer OpenGL or Vulkan version, even tho they apparently not.

right click ddnet in steam -> properties -> general -> launch options:
```
"gfx_backend OpenGL; gfx_gl_major 1"
```
**WITH** the `"`

![image](https://github.com/ddnet/ddnet/assets/6654924/f3659bf3-36fd-496b-bc30-4a04e5ff7cc0)

**Comment by FlopffyGrape** [comment]
> Mh really old computer. Additionally you use wayland.
> 
> I guess you could try to manually set the graphics backend to opengl 1. Normally this is done automatically, but apparently your drivers act like they support a newer OpenGL or Vulkan version, even tho they apparently not.
> 
> right click ddnet in steam -> properties -> general -> launch options:
> 
> ```
> "gfx_backend OpenGL; gfx_gl_major 1"
> ```
> 
> **WITH** the `"`
> 
> ![image](https://user-images.githubusercontent.com/6654924/248456716-f3659bf3-36fd-496b-bc30-4a04e5ff7cc0.png)

Thanks A lot!! It worked for me

**Comment by Jupeyy** [comment]
Good to hear
