### ISSUE TITLE
is "client_score_kind" not working?

### ISSUE THREAD

**Issue by Filto001** [ddnet/ddnet#6767]
hey, putting "client_score_kind\":\"points\" instead of ""client_score_kind\":\"time\"" in [server.cpp](https://github.com/ddnet/ddnet/blob/d84023395165b56a5d1b815271d35bb5d9f07e39/src/engine/server/server.cpp#L2282) doesn't work for me, the scoreboard still shows the time format. have I made a mistake or do I need to change something else?

**Comment by def-** [comment]
@heinrich5991 via 623a8935fb

**Comment by Robyt3** [comment]
Which scoreboard do you mean? The server info flag only determines how score are interpreted in the server browser scoreboard. You need to _not_ set `GAMEINFOFLAG_TIMESCORE` when snapping `CNetObj_GameInfoEx` so scores are rendered as points in the ingame scoreboard.

**Comment by Filto001** [comment]
yeah alright it's good now, if there's no other bug, the issue can be closed
