### ISSUE TITLE
A few ideas to further extend the functionality of the reserved slot

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#6769]
We've enabled moderators to join full servers using their authentication credentials via reserved slots. I can think of a few more ideas that might help moderators.

1. Bypass the name_ban system
   - This would allow us to name ban every staff member, preventing normal players from impersonating staff members

2. Silence the `"..." entered and joined the game` system message for the reserved slot, so bad actors don't leave in panic.
   - Addition: join into spec, instead of team 0

3. Don't highlight the moderator in whatever cl_authed_player_color is set to.
   - Alternatively, if 1. is implemented, this function could be removed altogether.

There's something im not quite sure about. Is the reserved slot considered a "unique" player slot? Example: If a regular player leaves the server after a moderator joins using the reserved slot, will the reserved slot become available again, or does the moderator who used the reserved slot need to leave for it to become accessible?

**Comment by Vy0x2** [comment]
> 1. Bypass the name_ban system

Moderators would have to login every time when they join a server then? I think that would be annoying. I dont see a reason to give the privilege to moderators that they cant be faked, accounts will solve this problem 

> 2. Silence the "..." entered and joined the game system message for the reserved slot, so bad actors don't leave in panic.

Would be cool, but unsure if its unnecessary. Could force reserved slot into spectator team so the reserved slot doesnt get abused.

> 3. Don't highlight the moderator in whatever cl_authed_player_color is set to.

Moderators should be able to control then if its getting highlighted. Current moderation is not having much trouble with auth highlight tho.

**Comment by heinrich5991** [comment]
> 2. Silence the `"..." entered and joined the game` system message for the reserved slot, so bad actors don't leave in panic.
> 
>     * Addition: join into spec, instead of team 0

This doesn't do much. The client would still see that a new player joined, and this could be seen as an even stronger signal that a moderator joined.

> 1. Bypass the name_ban system
> 
>     * This would allow us to name ban every staff member, preventing normal players from impersonating staff members

I don't like that. Nicknames are kind of free-for-all in DDNet currently.

> 3. Don't highlight the moderator in whatever `cl_authed_player_color` is set to.

I don't understand that. You mean: remove the `cl_authed_player_color` feature?
