### ISSUE TITLE
Deepfly prediction does not work. 

### ISSUE THREAD

**Issue by sjrc6** [ddnet/ddnet#6774]
in prediction/entities/charecter.cpp there is code that attempts to predict deepfly but it seems like the client isn't able to know the status of sv_deepfly even when the command is set in the maps server settings.

The client console reports "chatresp: No such command: sv_deepfly."

I think might be a broader issue with the CFGFLAG_GAME flag I'm not sure? 
sv_hit seems to be predicted correctly.

```cpp
// don't fire hammer when player is deep and sv_deepfly is disabled
if(!g_Config.m_SvDeepfly && m_Core.m_ActiveWeapon == WEAPON_HAMMER && m_Core.m_DeepFrozen)
    return;
```

**Comment by trml** [comment]
I actually think sv_hit is only predicted correctly by luck, and that these are not really sent to the client (last time I checked), so the solution is perhaps to send the server settings. Maybe as a part of GameInfoFlags?

There seems to be an extra `ExecuteFile` step in `CGameContext::LoadMapSettings` that the client doesn't do, where the server loads `.map.cfg` files, but not sure if the client downloads those.

**Comment by sjrc6** [comment]
I thought the idea of CFGFLAG_GAME was so the client could update the value on map load.
