### ISSUE TITLE
Consistent naming for `std::list` variables

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#6779]
Current `std::list` variables in our code:

```cpp
std::list<std::shared_ptr<CDemoEdit>> m_lpEditJobs;
std::list<CCacheChunk> m_Cache;
std::list<int> Indices = ...;
std::list<CCharacter *> listOfChars;
std::list<int> m_IDs;
std::list<int> Indices = ...;
std::list<int> Indices;
std::list<std::shared_ptr<CDataFileWriterFinishJob>> m_lpWriterFinishJobs;
std::list<int> Indices = ...;
std::list<CCharacter *> HitCharacters = ...;
std::list<CCharacter *> listOfChars;
```

Option A (prefix for list and its element type):

```
std::list<std::shared_ptr<CDemoEdit>> m_lpEditJobs;
```

Option B (no prefix for list and its element type):

```
std::list<std::shared_ptr<CDemoEdit>> m_EditJobs;
```

Option C (no list prefix, but prefix for the element type):

```
std::list<std::shared_ptr<CDemoEdit>> m_pEditJobs;
```

Option D (replace with `std::vector`)
```
std::vector<std::shared_ptr<CDemoEdit>> m_vpEditJobs;
```

I think we didn't want to go overboard with different prefixes. I definitely don't like option C. I'd slightly prefer A, but B would also be fine. If we don't need any of the special properties of `std::list` then using only `std::vector` would be preferable as well.

**Comment by edg-l** [comment]
or maybe dont use linked lists

"It is usually implemented as a doubly-linked list"

D:

**Comment by heinrich5991** [comment]
Most of these should probably indeed not be `std::list`s.

Without looking at the context, just from the name alone, these three seem like they might be lists for a legitimate reason:
```
std::list<std::shared_ptr<CDemoEdit>> m_lpEditJobs;
std::list<CCacheChunk> m_Cache;
std::list<std::shared_ptr<CDataFileWriterFinishJob>> m_lpWriterFinishJobs;
```

**Comment by Robyt3** [comment]
This is the only legitimate use of `std::list` as far as I can tell, as we remove from arbitrary positions and insert either at the beginning or end:

https://github.com/ddnet/ddnet/blob/05ddfba954a9772c782491a91ba98f2d740b22e7/src/game/client/prediction/gameworld.h#L120

These two should be `std::deque`s instead, as we only add at the end and remove from the beginning:

```
std::list<std::shared_ptr<CDemoEdit>> m_lpEditJobs;
std::list<std::shared_ptr<CDataFileWriterFinishJob>> m_lpWriterFinishJobs;
```

Everything else can be `std::vector`. `CCacheChunk` is only a wrapper for another `std::vector<uint8_t>`, so `std::list` doesn't have any benefit here that I know of.
