### ISSUE TITLE
server registration problem

### ISSUE THREAD

**Issue by XCWQW1** [ddnet/ddnet#6783]
In China, the tws server seems to be unable to register to the main server with IPV6?
------------------------------------------------------------------------------------------------------------------------------
在中国，tws的服务器貌似IPV6无法注册到主服务器？

**Comment by XCWQW1** [comment]
If I use dynamic IPV6\IPV4, is there a way to use the domain name to register?
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
如果我是动态的IPV6\IPV4有办法使用域名进行注册吗？

**Comment by def-** [comment]
Unfortunately registering via domain names is not (yet) supported. CC @heinrich5991 

We haven't tried ipv6 much, do you have a working ipv6 connection?

**Comment by XCWQW1** [comment]
At present, I have some ddnet servers registered to the main server with IPV6, and they are on the same server as the teeworlds server. I can ensure that my IPV6 can be accessed through the external network. I have tried to let my friends directly write the IPV6 address to connect Enter the teeworlds server, he can enter
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
目前我有一些ddnet的服务器用IPV6注册到了主服务器上，并且和teeworlds的服务器在同一台服务器上，我可以确保我的IPV6可通过外网进入，我尝试过让我的朋友直接写IPV6地址连入teeworlds服务器，他是可以进入的

**Comment by heinrich5991** [comment]
If DDNet servers can register but Teeworlds servers can't, it's probably a problem with the old masterservers. I don't think I want to debug the old masterservers right now.

**Comment by XCWQW1** [comment]
It seems that the infection mode, manufacturing, mmotee and the like are all developed based on teeworlds 6.0. They seem to have no version of ddnet and must be registered to the main server of tws. Can these tws6.0 servers be directly registered to ddnet servers? (The registration of IPV4 seems to be no problem. For IPV6, I have been reminded that I do not have an open firewall, but I can directly fill in the ip external network to join the server.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
貌似感染模式，制造，mmotee之类的好像都是基于teeworlds 6.0开发，他们貌似没有ddnet的版本 必须要注册到tws的主服务器。是否能让这些tws6.0的服务器直接注册到ddnet的服务器呢？（IPV4的注册貌似没问题 IPV6的我这里一直提示我没有开放防火墙，但是我直接填写ip外网是可以加入到服务器的
