### ISSUE TITLE
Wrong skin copyright

### ISSUE THREAD

**Issue by HiRavie** [ddnet/ddnet#6830]
I did not make kitty_x_ninja.
https://github.com/ddnet/ddnet/blob/68d78754ebcc284078091f89957add2caec4b491/data/skins/license.txt#L30

**Comment by def-** [comment]
Do you know who did?

**Comment by Robyt3** [comment]
According to the commit message of 8d621dfc003315662a44a0d3a7156fc0f2876192 it's made by `patwo.*`.
