### ISSUE TITLE
Killfeed not showing deaths in teams

### ISSUE THREAD

**Issue by bencie** [ddnet/ddnet#6838]
If a tee dies in an unlocked team mid run, they will not show up in the kill feed. 

https://github.com/ddnet/ddnet/assets/78111412/4060fe48-5795-4101-a5ed-47136c726a72

**Comment by def-** [comment]
@VoxelDoesCode ^

**Comment by VoxelDoesCode** [comment]
I'll look into that tommorrow. There's also another team kill issue that I want to fix so I'll include that too.
