### ISSUE TITLE
Disable auto-selection of last played server on game launch

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#6845]
Suggested by 0x314 on Discord:

> After the recent update when I open the game, it automatically selects and scrolls to the last server I played. And usually, it's empty or has a low player amount, so the scroll position is in the middle or even at the end, so I have to scroll up every time to see the most populated server (as it used to be before this update)
Is it possible to disable this new thing? 
I find it really annoying to scroll up every time I launch the game 😐

**Comment by murpii** [comment]
Clearing the Server address field after each launch would probably be easiest.

**Comment by heinrich5991** [comment]
I like having it on the last server I played. ^^ At least just for pressing enter. Helps if you restart the client, e.g.

**Comment by Robyt3** [comment]
I also prefer to have the previous server stay selected after restarting.

I'm also not convinced that starting the server browser view scrolled up to the top instead of scrolled to the selected server is more convenient in general. It's definitely not worth it to add an option for this.

**Comment by doroginalexanderqt** [comment]
No need to consider your personal preferences as a source of truth, since it wasn't like this before. 
You can't just change certain UX patterns without a discussion, and I'm not sure the discussion about it existed somewhere.
IMO currently it's just a bug and the bug should be fixed.

Here is another guy struggling with it
<img width="606" alt="image" src="https://github.com/ddnet/ddnet/assets/21317159/3a08a859-9a17-4967-b97d-4a509a89bd0d">

So ye, idk how could UX worsening be changed silently.

**Comment by l-ouis** [comment]
> I'm also not convinced that starting the server browser view scrolled up to the top instead of scrolled to the selected server

IMO there's no good reason to have it automatically scroll to your selection. I don't see a scenario in which you restart the client and then proceed to join another server close by on the server list from your last selected one. I more often scroll to the top (with player# and ping sorting) to see if any of my friends are online.

And as heinrich said, the automatic scroll isn't needed for joining the server anyways (just press enter)

**Comment by murpii** [comment]
> I like having it on the last server I played. ^^ At least just for pressing enter. Helps if you restart the client, e.g.

> I also prefer to have the previous server stay selected after restarting.

I assume it's convienent for debugging issues on a localhost server?


On the flip side I can see why this is annoying for regular users.
A regular user starts the game, plays Grandma for an hour, regrets playing it because for how long it is, and then quits for the day. On the next day, you're looking at an empty server, instead of all well populated servers.

There isn't really a reason for a regular user to restart his client over and over again.

Another person on discord even wants this disabled at all times, so each time you pull up the server browser, you're always right at the top.

**Comment by l-ouis** [comment]
I think just having the scroll start at the top but having latest server still selected satisfies everyone's needs

People who are testing something and need to quickly rejoin after restarting can simply press enter
And the casual day-to-day player will start off at the top of the server list and select what they want using mouse
