### ISSUE TITLE
Regression: Multi-line chat messages sometimes overlay the next chat message

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#687]
I haven't seen this bug at all until the past week or two. I'm too lazy to figure out which commit introduced the bug. As you can see from the screenshots, chat lines are sometimes covering other chat lines.

I'm on a Debian Jessie amd64 box running the latest commit ( 125764815b8029348fd121a18216b0d11f534937 )

![screenshot - 03142017 - 01 31 32 am](https://cloud.githubusercontent.com/assets/7715155/24061321/3a31fcbc-0b14-11e7-86b0-5cf65f64293c.png)
![screenshot - 03172017 - 01 13 18 pm](https://cloud.githubusercontent.com/assets/7715155/24061320/3a2c0c6c-0b14-11e7-95ea-85cb4fe9c350.png)

**Comment by Learath2** [comment]
My fault :( 3bd94b9a is probably to blame.

**Comment by d3fault** [comment]
@Learath2 
Seems mostly fixed as of 2849e23 but it's still bugged for votes (note: the map name and f3 reason can't be too short OR too long, Bl0odDens3 called via /map is the right length to trigger the bug):
![vote over chat](https://cloud.githubusercontent.com/assets/7715155/24623399/21e51cec-185d-11e7-8c25-2e7f62716da3.png)

**Comment by Learath2** [comment]
@def- also reported an occurrence of this on IRC.

I don't see anything else wrong tho.

**Comment by d3fault** [comment]
Here's another, this time not a vote. 2849e23 did seem to make it appear less often, and I think every time I see it now it only overflows a little bit on the left.  Hmm, maybe the client IDs being enabled has to do with it? I'll play with them disabled for a little and see if it still occurs.
![asdf](https://cloud.githubusercontent.com/assets/7715155/24799172/b10cc796-1b4e-11e7-8d89-b9af0380e484.png)

**Comment by d3fault** [comment]
Disabling client IDs changes it so you need a few more chars to trigger the bug.
![asdf2](https://cloud.githubusercontent.com/assets/7715155/24799497/44fb954e-1b50-11e7-996b-ee23bde94058.png)

**Comment by Learath2** [comment]
Figured it out, just need to patch it, maybe tomorrow.
