### ISSUE TITLE
RFC: Remove Windows line ending treatment

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#6875]
The Windows default editor is able to work with pure `\n` endings nowadays. Maybe it's time to drop the `\r\n` code?

I just saw it in #6874.

**Comment by Chairn** [comment]
I know @Jupeyy will scream at me for that but, isn't there a risk of breaking things for older windows platform that are still being used ?

**Comment by heinrich5991** [comment]
Apparently it's been available since 2018. Perhaps we should keep it for the config file code (because users might manually edit that), but for the rest, it could maybe go?

https://devblogs.microsoft.com/commandline/extended-eol-in-notepad/

**Comment by TsFreddie** [comment]
2018 is still Windows 10 era. I'd say we can drop it once we or one of our dependencies dropped support for windows 7.

**Comment by heinrich5991** [comment]
Let's revisit it in a couple of years I guess.
