### ISSUE TITLE
Force the reserved slot into the spectator team

### ISSUE THREAD

**Issue by Vy0x2** [ddnet/ddnet#6880]
Problem:
When moderators use the reserved slot on full servers they might forget it and start playing the map. They dont moderate then and active moderators cant join the server.

Solution:
Force the player of an reserved slot into the spectator team so he cant play the map but rather can only moderate in this state.

Addition:
Introduce a new variable to switch between this behaviour and the normal one.

**Comment by refeax** [comment]
I’m all for this idea. It can be frustrating when you need to join a server to quicky check something, but someone is already using the reserved slot for an unknown time

**Comment by heinrich5991** [comment]
I'd prefer to start by talking to the respective moderators before doing a code change. Have you tried talking to them yet?

**Comment by Vy0x2** [comment]
I am a friend of creating technical limits.
I dont write down the names of the moderators when i encounter this situation so i cant speak to anyone specific.
