### ISSUE TITLE
Feature request: Queue system

### ISSUE THREAD

**Issue by bencie** [ddnet/ddnet#6883]
On new t0 map releases, almost all the people trying to finish the map in team 0 are trying to join the same 1 server, so it's extremely hard for people to join the server once it becomes full. The new map sus'terism is an extremely good example for this, usually 10+ of my friends are on it at any time these couple of days, and it's really hard to get other friends or yourself into the full server.

Currently it's up to chance whether you or another person connects first, and it's really annoying to wait 30+ minutes due to this.
A queue system would be so useful, once you try to join a full server, you'll be added last into the queue, and can see how many players are waiting in front of you. This would just mean everyone has to wait around the same time to join instead of randomly joining within 1minute or 1hour depending on luck.

One concern I imagine this idea bringing up, is how it should be handled if a person tries to connect dummy in a full server. Does the dummy get added to the queue, or completely prevented to join? How is it displayed to them that their dummy is in a queue, and their position in queue?

**Comment by Chairn** [comment]
Also most people are joining only to spec. Maybe we could add some spectator only slots ?

**Comment by heinrich5991** [comment]
Duplicate #3453. You can ask to re-open there.

**Comment by refeax** [comment]
I am all for bencie's and aswell as for Chairn's suggestions. Both make alot of sense, since I do consider the current system to be problematic.
