### ISSUE TITLE
Should we accomodate building the headless client with as few dependencies as possible?

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#6893]
Pro: easier to build minimal container images. Should we even support that?
Con: maintenance overhead

CC #6889
CC #6891 (might also be useful regardless of this issue, apparently openSUSE doesn't ship libnotify?)

**Comment by ChillerDragon** [comment]
I would even propose allowing to build the non headless client with as little required dependencies as possible.

**Comment by Jupeyy** [comment]
Any feature, option or whatever that can be toggled makes it harder to consistently debug ddnet.
In fact for the best result it would probably the easiest if all ppl use the same hardware, software, enjoy the same cosmic rays, be the same person, go back to the big bang, ok i stop

**Comment by ChillerDragon** [comment]
:trollface:

**Comment by def-** [comment]
@ChillerDragon What is the use case of headless client?

**Comment by ChillerDragon** [comment]
> @ChillerDragon What is the use case of headless client?

My personally biggest use case is it being a base for my curses client.

But as I said already. This should not only apply to the headless client.

The reason why I want to minimize required dependencies in general is to reduce effort for the first or even final compile in any environment. Environments being for example a debian vps that just runs headless clients (would be slimmer without gfx libs). Or a less mainstream/non desktop distro that does not have all packages or we don't have a install command in the README such as alpine and openSUSE. I also tinkered with porting ddnet to serenityOS once where minimal dependencies reduce the effort. In my head there is some random dude on the internet on some weird distro/os trying to build ddnet to play some game because no other game would run or compile :D

**Comment by def-** [comment]
A curses client should run on a system without X11 installed, so we should accommodate removing all graphics/X11 dependencies for headless client.

**Comment by ChillerDragon** [comment]
> A curses client should run on a system without X11 installed, so we should accommodate removing all graphics/X11 dependencies for headless client.

Sounds nice for me. But I have to admit that does not make much sense. You said you do not want me to pr the curses client. So offical ddnet will probably stay without the curses client. And now you are saying you want to increase maintenance to allow compiling a downstream project with less dependencies? :D

**Comment by Jupeyy** [comment]
Also our friend ChillerDragon does not like if a player joins a team and blocks a slot, so he obviously dislikes that a player without graphics blocks a slot either, right? 

@ChillerDragon I assume rn u have X11 installed. What even is the overhead of X11 deps? Can only be a few mb?

**Comment by ChillerDragon** [comment]
> Also our friend ChillerDragon does not like if a player joins a team and blocks a slot, so he obviously dislikes that a player without graphics blocks a slot either, right?

Every tee I can interact with physically is a win for me. If it moves or not. If it is a human or not.

> @ChillerDragon I assume rn u have X11 installed. What even is the overhead of X11 deps? Can only be a few mb?

Idk deen brought up x11. I can not remember installing x11 on my vps I just ran the apt command from the ddnet readme and it compiles ddnet headless just fine. In a true container tryhard manner every mb is worth. And also my other argument stands that every library that has to be compiled from source or its package name has to be manually searched makes the life of a user on a non standard system harder.

**Comment by heinrich5991** [comment]
> I also tinkered with porting ddnet to serenityOS once where minimal dependencies reduce the effort.

Could that person simply stub out the dependencies? libnotify is pretty contained, no?

> we don't have a install command in the README such as alpine and openSUSE

I think the better solution would be to include the installation commands.

---

I think all in all, I'd say supporting the headless client outside of integration tests in CI is out of scope.
