### ISSUE TITLE
Editor modified state is not updated when envelopes are changed

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#6906]

**Comment by Robyt3** [comment]
Most of this was already fixed together with the other envelope editor changes.

I can only see these remaining issues:
- Clicking "Sync." checkbox does not set modified state.
- Changing curve type of line segments does not set modified state.
- Modified state is incorrectly set all the time while the envelope name lineinput is selected.

**Comment by Marmare314** [comment]
Moving envelopes also does not update the modified state.

**Comment by Robyt3** [comment]
Confirming the "Map Details" popup also does not update the modified state.
