### ISSUE TITLE
Optional scrubbing of ip addresses from rcon console

### ISSUE THREAD

**Issue by east** [ddnet/ddnet#694]
Since ip addresses are considered sensitive / confidential information it's reasonable to hide them from non-administrators (moderators in our case).

My idea is to implement a feature that optionally allows the hiding of ip addresses from specific 'rcon authorities' (like moderators).

**Comment by Learath2** [comment]
I couldn't see any messages that included a clients IP in `server.cpp` and a quick `str_format.*ip.*` didn't seem to reveal anything except the mute messages. 

I do suck at regex so would appreciate help in finding messages.
