### ISSUE TITLE
Client versions 16.9 and newer don't launch on macOS 10.15

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#6947]
![error](https://github.com/ddnet/ddnet/assets/23437060/5eee3f79-f0d7-4e6b-9493-914d2455e35b)

Last version that worked for this user was 16.8.

Support for macOS 10.15 ended November 30, 2022 so maybe that's the cause. Anyone else using macOS 10.15 so we can test this?

**Comment by def-** [comment]
Weird. We build DDNet with CMAKE_OSX_DEPLOYMENT_TARGET 10.13, the libraries still with 10.9, so I'd expect this to work. Maybe the ? or trying to run it from command line has more information about the source of the error.

**Comment by Robyt3** [comment]
We got it fixed by following this tutorial: https://iboysoft.com/howto/cannot-be-opened-because-it-is-from-an-unidentified-developer.html

In particular, removing the attribute `com.apple.quarantine` from the executable fixes this issue:

```
sudo xattr -r -d com.apple.quarantine ./DDNet
```

For some reason, using `sudo spctl --master-disable` to disable the Gatekeeper feature on its own did not work.
