### ISSUE TITLE
Add a new network message for chat commands

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#6953]
Add a new network message that sends the chat command payload. To avoid leaking chat commands to public chat on servers that do not have a chat command system. If ddnet users bind for example ``bind x say /save mysecretddetpass`` and hit that bind accidentally on a vanilla or other server. Regular chat messages should still be handled as chat commands for backwards compat.

**Comment by heinrich5991** [comment]
> Add a new network message that sends the chat command payload. To avoid leaking chat commands to public chat on servers that do not have a chat command system.

That doesn't sound particularly helpful. Server owners of these places would still be able to see your leaked password.

**Comment by ChillerDragon** [comment]
> > Add a new network message that sends the chat command payload. To avoid leaking chat commands to public chat on servers that do not have a chat command system.
> 
> That doesn't sound particularly helpful. Server owners of these places would still be able to see your leaked password.

Same applies for rcon auth binds. And yet I feel more comfortable binding rcon login than my city server /login myacc mypw chat command. It is way more realistic that the 5 people currently connected to the server will read the chat message and instantly act on it than the one server administrator being an evil actor. Most servers probably do not even have logging in place especially not vanilla servers for custom ddnet messages. It also reduces the very common /spec and /pause spam and some trolls even keep their /emote binds while playing a round of pvp. I also leak my ip to the server owner and still appreciate that it is not being sent to public chat.

Its a easy 10 lines implementation code wise and it will drastically reduce leaked passwords and other unwanted chat messages. Saying its not unhackable and thus should not be done does not seem very productive to me.

**Comment by heinrich5991** [comment]
> Same applies for rcon auth binds. And yet I feel more comfortable binding rcon login than my city server /login myacc mypw chat command.

Sounds like the invisibility of rcon auth packets gives you a false sense of security.

> Its a easy 10 lines implementation code wise

I very much doubt it.

> **drastically** reduce leaked passwords and other unwanted chat messages.

I also doubt that.

**Comment by ChillerDragon** [comment]
I realized a flaw in this idea. If we make the ddnet client stop sending chat messages starting with a / it will break 3rd party servers or old ddnet servers not supporting the new command system server side. If anyone has an idea how to not send chat commands on servers that will just print it to public chat but keep sending them on any kind of server that interprets chat messages as chat commands please let me know. If not I guess this issue has to be closed : (

**Comment by ChillerDragon** [comment]
The client could drop all chat messages starting with a single slash. Unless it gets sent a message from the server stating it supports chat commands.

To stay compatible with servers that do not support that feature. One could be more explicit with maybe two slashes instead of one.

**Comment by ChillerDragon** [comment]
I still would like to reduce the amount of leaks happening because credential binds made for chat command servers were accidentally pressed on non chat command servers. But I have not figured out how exactly. The initial suggestion was flawed.

**Comment by heinrich5991** [comment]
Credential binds will hopefully become unnecessary with accounts.
