### ISSUE TITLE
Masterserver doesn't accept `Content-Type: application/json; charset=utf-8`

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#6955]
From [Discord](https://discord.com/channels/252358080522747904/293493549758939136/1078374803016265838):
> [6:56 PM] Matodor: and master server don't support Content-Type header with charset
> ```
> Content-Type: application/json; charset=utf-8
> ```
> [6:57 PM] Matodor: i got `{"status":"error","message":"The request's Content-Type is not supported"}` when send with `charset=utf-8`
> [7:00 PM] ChillerDragon: try content type application/json 🤷 random guess xd
> [7:00 PM] ChillerDragon: without charset
> [7:00 PM] Ryozuki: where
> [7:00 PM] ChillerDragon: why would you need to specify the charset?
> [7:02 PM] Ryozuki: i mean u get a result with a err and u unwrap it, panicking
> [7:02 PM] Matodor: because i want write in C#: 
> ```
> request.Content = JsonContent.Create(_interactor.ServerInfo);
> ```
> instead of 
> ```
> request.Content = JsonContent.Create(_interactor.ServerInfo, mediaType: new MediaTypeHeaderValue("application/json")
>             {
>                 CharSet = null,
>             });
> [7:02 PM] Matodor: by default it sends with  charset

I think it'd be sensible to accept `Content-Type: application/json; charset=utf-8` as well.

**Comment by BurnyLlama** [comment]
I am looking in to it right now.

The error comes from here:

```rust
fn register_from_headers(
    headers: &warp::http::HeaderMap,
    info: &[u8],
) -> Result<Register, RegisterError> {
    Ok(Register {
        address: parse(headers, "Address")?,
        secret: parse(headers, "Secret")?,
        connless_request_token: parse_opt(headers, "Connless-Token")?,
        challenge_secret: parse(headers, "Challenge-Secret")?,
        challenge_token: parse_opt(headers, "Challenge-Token")?,
        info_serial: parse(headers, "Info-Serial")?,
        info: if !info.is_empty() {
            if headers.typed_get() != Some(headers::ContentType::json()) {
                return Err(RegisterError::unsupported_media_type());
            }
            Some(json::from_slice(info).map_err(|e| {
                RegisterError::new(format!("Request body deserialize error: {}", e))
            })?)
        } else {
            None
        },
    })
}
```

The problematic call is `headers::ContentType::json()` which comes from the [warp](https://crates.io/crates/warp) crate. Which, if it fails to detect proper JSON calls this:

```rust
impl RegisterError {
    fn new(s: String) -> RegisterError {
        RegisterError {
            is_unsupported_media_type: false,
            message: Cow::Owned(s),
        }
    }
    fn unsupported_media_type() -> RegisterError {
        RegisterError {
            is_unsupported_media_type: true,
            message: Cow::Borrowed("The request's Content-Type is not supported"),
        }
    }
    fn status(&self) -> warp::http::StatusCode {
        use warp::http::StatusCode;
        if !self.is_unsupported_media_type {
            StatusCode::BAD_REQUEST
        } else {
            StatusCode::UNSUPPORTED_MEDIA_TYPE
        }
    }
}
```

And yeilds the error you noticed.

So this might be a problem with warp -- at least the version currently in use -- and not the code in the DDNet codebase. I will try to look further in to it though.
