### ISSUE TITLE
Hammer while in super is sometimes uneffective

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet#6960]
Not sure what caused this, but hammering frozen tees while in super and being in freeze too is uneffective. It does trigger single tick unfreeze but won't move the tee. 

Video here:
https://discord.com/channels/252358080522747904/757720336274948198/1136083810124046356

https://cdn.discordapp.com/attachments/757720336274948198/1136083808488276118/Aardvark_2023-08-02_01-42-31.demo.mp4

**Comment by Jupeyy** [comment]
"Its not a bug, u are inside of tune zone with "hammer-strength 0" setting" - Kicker

**Comment by Chairn** [comment]
Nice mapper aside not telling anything....
