### ISSUE TITLE
Translation updating script sometimes breaks translations with context

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#6971]
https://github.com/ddnet/ddnet/pull/6967#discussion_r1285220104

**Comment by Robyt3** [comment]
The issue can be reproduced by removing the context from the first of these two translations, assuming they are next to each other:

```
[Ingame controller mode]
Relative
== Relativ

[Ingame controller mode]
Absolute
== Absolut
```

Running `update_all.py` will then also cause the context of the second translation to be removed. I assume the script skips one more line than it should because the first context is missing. I don't understand the translations scripts enough to fix it though.

In the long run we should consider switching to a more structured format for translations, e.g. upstream uses json.

**Comment by def-** [comment]
> I don't understand the translations scripts enough to fix it though.

This is always my problem too :D
