### ISSUE TITLE
Emote on focus lost

### ISSUE THREAD

**Issue by ArijanJ** [ddnet/ddnet#6975]
Add an option to display an emote (Zzz) when the player alt-tabs or clicks off the game, would be useful for letting other players in the run know when you've clicked on a notification and they shouldn't start any parts involving you, or should save you last.

**Comment by heinrich5991** [comment]
I think this would make it more acceptable for players to tab out of the game. I think it would be a bad idea for this reason.

**Comment by ArijanJ** [comment]
👍
