### ISSUE TITLE
Localized HUD possibly overlaps with Pagetabs

### ISSUE THREAD

**Issue by H-M-H** [ddnet/ddnet#699]
I guess this needs to be adjusted: https://github.com/ddnet/ddnet/blob/c5269fc7646d4a214b96b55b63afaada8ae26417/src/game/client/components/menus_settings.cpp#L1323-L1334

With german localization HUD becomes Aussehen, which is to long and thus overlaps with the pagetabs in the HUD settings menu.

**Comment by Learath2** [comment]
Nothing a simple TextWidth() won't fix, I'll commit in a minute.
