### ISSUE TITLE
Automatic Multi-View tee selection doesn't work for tees in teams

### ISSUE THREAD

**Issue by Possseidon** [ddnet/ddnet#7007]
When switching from Free-View to the new Multi-View it will automatically focuses the currently visible tees for Multi-View. However this does not seem to work if those tees are in a team.

While it does make sense to default to team 0 when there is tees with different teams on screen (since you can't spectate multiple teams at once currently), I do think it would still very much make sense for it to work if all tees on screen are actually in the same team anyway.

**Comment by Vy0x2** [comment]
I think this would be a good feature to add 👍
I can implement this in the next weeks, quite busy right now.

**Comment by Possseidon** [comment]
> quite busy right now

Fine, I'll do it myself :P
