### ISSUE TITLE
Editor layer selection cleared on map load

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#7024]
Reported on discord

> │11:22:44       bridge_ | &lt;QuiX&gt; Hello! In the editor, when loading between maps you used to be able to copy the game group elements, to be able to copy parts and put it in other map. I tried it but wasn't able to do It in the new version. Is it another way of doing it now or it got removed?

https://github.com/ddnet/ddnet/assets/20344300/8f0b99ce-5c8c-419c-8fed-30de5eff6751

**Comment by Robyt3** [comment]
It caused crashes so the saved brushes are currently cleared when loading another map. Would be good if we can support copying between maps again though.
