### ISSUE TITLE
Missing entities text, font glyphs and languages

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7041]
Reported by Marian3127 and T tee on Discord.

Entities text, some glyphs and all languages except English are missing on 17.2 but everything works with 17.1.

![1](https://github.com/ddnet/ddnet/assets/23437060/9e80e05a-cf4f-4cd0-8f9c-88503c7e5231)

![2](https://github.com/ddnet/ddnet/assets/23437060/7fdb9fc1-e98a-4d52-986a-4f828d4fdaf1)

![3](https://github.com/ddnet/ddnet/assets/23437060/87e655f0-407b-4bca-a8f2-bb61cdb0017a)

No error messages related to fonts or languages reported.

**Comment by def-** [comment]
The font looks different than on my system which is why I guess he uses a custom font and that breaks things.

**Comment by Robyt3** [comment]
Seems like they or the client somehow copied some of their data folders, in particular the `fonts` and `languages` subfolders, into their config directory at some point. Because the format of the language `index.txt` and the fonts have changed, files were not being loaded correctly anymore.
