### ISSUE TITLE
Initial pause of demo player when rending is unintuitive

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7044]
Reported by Astramast on Discord:

> I just updated to 17.2 and i cant render demos
> i just have the first frame of the demo and it just freeze
> i can stille control the demo panel while rendering is frozen
> i can play demos tho
> i have a .mp4 in the videos folder tho
> but it always have 261 bytes and doesnt play (tried with 30s & 1m demo)

The demo playback is initially paused due to `cl_video_pause_on_start` being `1` being default.

There should be a better indication that demo playback and rendering is initially paused, like a big paused symbol and a message "Unpause to start rendering…" or something like this.

**Comment by Kaffeine** [comment]
I agree 100%. It should be 0 (the same behavior as before) by default. I'll open an MR in 20 minutes.

**Comment by Kaffeine** [comment]
Also I think it is a bad idea to use `Config` for that. It is just happened that there are `m_ClVideoShowChat`, `m_ClVideoSndEnable`, and `m_ClVideoShowhud`, so I thought to do the same with pause.
@Robyt3 does it make sense if I remove the config var entirely and wire up a boolean arg to `IClient::DemoPlayer_Render()` instead?
