### ISSUE TITLE
Holding mouse down after double-clicking adds another envelope point

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7052]
1. Double click to add another envelope point
2. On the second click, keep holding the left mouse button down.
3. Move the mouse somewhere else so it's not directly above the previous point (the selection rectangle should be open right now)
4. Releasing the left mouse button adds another envelope point at the position where it was released

@Marmare314

**Comment by Marmare314** [comment]
I can't reproduce this. The box selection is opened which may not be the best behaviour but is not terrible either, however no point is created when releasing the button. Can you try again if this still works?

**Comment by Robyt3** [comment]
Yeah, still happens. Here is a video:

https://github.com/ddnet/ddnet/assets/23437060/12770cc3-44ed-41ef-95be-21e8b591f268

No point is created when the box selection is small because the points would be too close together.

**Comment by Marmare314** [comment]
Not sure what I am doing wrong, but I still can't reproduce this.

https://github.com/ddnet/ddnet/assets/49279081/1d98524d-0476-4644-a725-540dc9e58dcd

**Comment by Robyt3** [comment]
It only seems to happen with `gfx_asyncrender_old 0`. Doesn't happen with `gfx_asyncrender_old 1` to me.
