### ISSUE TITLE
Composite input broken in input fields other than the chat

### ISSUE THREAD

**Issue by Socialdarwinist** [ddnet/ddnet#706]
Examples:
Compose Key + " + u should return ü,
but it returns " after pressing ".
Dead Key Acute + u should return ú,
but it returns u.
One can come upon this in the server name field, the player name field, &c., &c.

Note that I am aware of the PR regarding IMEs #683, but as it appears to me that the relevant devs have at least not all noticed this specific bug, I presume that this problem has been brought to mind ere an imperfect merge occur.

**Comment by H-M-H** [comment]
Possibly related to: #547 #640 
Which OS do you use ?

**Comment by Socialdarwinist** [comment]
Not macOS, but Arch Linux.

**Comment by def-** [comment]
Can't reproduce, I'm also on Arch Linux, most recent SDL2, etc. I use xcompose a lot and reported a bug to SDL2 about this once and they fixed it, so make sure that you have the most recent version.

**Comment by Socialdarwinist** [comment]
It is still like I have described, @def-. And I use the recent master, have compiled the client_debug all again after deletion of all .o files. Of course I have also the most recent SDL2 package.

**Comment by def-** [comment]
Ok, so how can I reproduce this? I have X11, xmonad, German keyboard layout and use xcompose config from here: https://github.com/kragen/xcompose

**Comment by Socialdarwinist** [comment]
I have the default German keyboard layout (plus three other non-Latin ones, which causes AllTheHaxx/AllTheHaxx#287 for those, the most annoying thing on DDNet for me right now, and #683 should be worked on by someone other than necropotame now). My desktop environment is Cinnamon and sometimes MATE.

**Comment by def-** [comment]
Thanks for the report, finally figured out that you said "other than chat"
