### ISSUE TITLE
Use ISO 3166-2 for country flags

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7071]
Suggested by Jurai! on Discord. We currently use ISO 3166-1 for country flags but add our own codes for countries not covered by that standard. For example the flags of England, Scotland, and Wales currently use the codes XEN, XSC and XWA respectively. We could use ISO 3166-2 in addition to ISO 3166-1 for these cases, so we would use GB-ENG, GB-SCT and GB-WLS instead.

**Comment by Robyt3** [comment]
Maybe we should also show the full country name in a tooltip when hovering the flag.

**Comment by def-** [comment]
Sounds like it would be backwards-incompatible. I'd argue for not adding any further X**

**Comment by Robyt3** [comment]
This is only about renaming some of the existing `X**` flags. In the network protocol and to store the selected country we only use the numeric country codes, so it's shouldn't break anything if we change the names/abbreviations. The `X**` flags all have ISO 3166-1 numeric country codes in the `900-999` range, which is for user-assigned countries.

**Comment by def-** [comment]
Oh right, then it's fine to rename them.
