### ISSUE TITLE
Use new format for country flags

### ISSUE THREAD

**Issue by JuraIBOZO** [ddnet/ddnet#7090]
Suggested by Jurai! on Discord. We currently use old format of some flags like: Mongolia (Using now: Mongolian People's Republic), Martinique (Using now: Snake Flag what stepped down at October 2018 year), Reunion (Using now: Drapo la Rényon what stepped down at 28 March 2003 Year)

Links of old flags:
Old Mongolia flag: https://en.wikipedia.org/wiki/Mongolian_People%27s_Republic
Old Martinique flag: https://ru.m.wikipedia.org/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:Snake_Flag_of_Martinique.svg
Old Reunion flag: https://ru.wikipedia.org/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:Unofficial_flag_of_Reunion_(MLK).svg

Links for new flags what im suggest:
New Mongolia flag: https://en.wikipedia.org/wiki/Flag_of_Mongolia
New Martinique flag: https://en.wikipedia.org/wiki/Flag_of_Martinique
New Reunion flag: https://en.wikipedia.org/wiki/Flag_of_R%C3%A9union (Lö Mahavéli)
![mongolia](https://github.com/ddnet/ddnet/assets/142632373/60bbdd71-985e-47b6-8170-6dc534a46f23)
![reunion](https://github.com/ddnet/ddnet/assets/142632373/4463ef7d-91b1-48f1-8208-39e77020d735)
![martinique](https://github.com/ddnet/ddnet/assets/142632373/c59a5d95-0a0c-4ceb-9c42-743974e56dda)

**Comment by def-** [comment]
Sounds good. Just need someone who can make them in TW style.

**Comment by JuraIBOZO** [comment]
> 

![reunion](https://github.com/ddnet/ddnet/assets/142632373/86d186f7-500c-4ba7-bfec-362a8a9e5590) Reunion (RE)
![mongolia](https://github.com/ddnet/ddnet/assets/142632373/9a120f56-498b-4e18-9bc9-6cf775a2c666) Mongolia (MN)
![martinique](https://github.com/ddnet/ddnet/assets/142632373/1f337803-61dd-47ba-8a62-626769f2535e) Martinique (MQ)
![malawi](https://github.com/ddnet/ddnet/assets/142632373/959f62c2-99b8-4653-ae27-b54043bc6eed) - Malawi (MW)
![guadeloupe](https://github.com/ddnet/ddnet/assets/142632373/dcf67db3-9a0d-4bb1-a679-7ae88f208fb0) - Guadeloupe (GP)

**Comment by JuraIBOZO** [comment]
> Sounds good. Just need someone who can make them in TW style.

![Paraguay](https://github.com/ddnet/ddnet/assets/142632373/b9a7f3b2-f73d-4110-97a2-990eaca87a07) Paraguay (PY)
