### ISSUE TITLE
Hearts next to friends still shown next to "cleared" chats after map change

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#710]
Hearts next to friends names works as intended, but when you change map, the chat log is cleared, and well for some reason the hearts "are not" cleared. See attached image. @Learath2 
![hearts](https://cloud.githubusercontent.com/assets/7715155/24577454/d118f9c2-1682-11e7-94df-f2e6f788d83b.png)

edit: the hearts are green because I made them green ;-)

**Comment by Learath2** [comment]
Do the hearts keep going up with further chat messages? I'm trying to track this down in code but can't seem to figure out what exactly causes the hearts to be treated any different then the messages themselves.
