### ISSUE TITLE
MOTD logged above other messages in local console / Lacking setting to disable MOTD logging

### ISSUE THREAD

**Issue by Socialdarwinist** [ddnet/ddnet#711]
![bildschirmfoto vom 2017-04-01 14-52-28](https://cloud.githubusercontent.com/assets/20446122/24578915/ac569f68-16eb-11e7-8b0d-59fb22f6896e.png)

The workaround to disable MOTD logging in the local console would serve me entirely, but [there is no setting for this](https://ddnet.tw/settingscommands/), as far as I have rummaged the settings documentation.

There is cl_print_broadcasts, which I need to have on 0, because else InfClass spams me with useless information in F1, so there should be a cl_print_motd too – for for example on InfClass, one cannot need MOTD logging.

(I am running the master on Arch Linux).

**Comment by Learath2** [comment]
Caused because the server sends motd's with `\n` in it instead of multiple motd messages. Not sure if we should be the ones fixing this.

If we do maybe on the console level just don't print anything after the first `\n`.

**Comment by necropotame** [comment]
As long as MOTD is able to display \n, there is no problem to send them. And this is a nice way to send a long text without be interupted by chat messages. I don't think that InfClass is to blame here.

In the console, we should display each line as a new console line. And of course implement the new setting :)

**Comment by Learath2** [comment]
Well I'll tokenize on `\n` and print each line separately.  Don't think this deserves a setting tbh.

**Comment by necropotame** [comment]
In InfClass, MOTD is used to display leaderboard, help pages, list of commands. For example, the best players and the challenge of the day are shown each time the map change. TW is limited and some mods try to overcome this limitation as they can :P
It deserves a settings because as you see, some mods use it often, and since there is one settings for broadcast, it seems logical to add one for MOTD too.

**Comment by Learath2** [comment]
Am I missing something here? If we tokenize on `\n` it will work fine either way no?

It shouldn't be hard to disable but unless you spam the console it should be fine.

**Comment by Henningstone** [comment]
I'll clean up some confusion here: the literal `\n` is already being handled correctly ([see here](https://github.com/ddnet/ddnet/blob/4a0abf67472563e030fa22d1fa60b16932f180f6/src/game/client/components/motd.cpp#L67-L83))

But what I assume is causing the overlapping is if the server doesn't send a literal `\n` but instead an already escaped one `0x0A`. And indeed this case is not taken care of.
