### ISSUE TITLE
Sometimes zoom changes quickly when first joining a server

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7111]
Like it starts zoomed out too far and zooms in very quickly when joining a server after first launching the client. Doesn't happen consistently though. I'm using default zoom settings.

Could be related to #7016.

**Comment by k-i-o** [comment]
maybe it's related to the problem someone else posted because the zoom defaults to every tick

**Comment by Robyt3** [comment]
Likely also closed by #7125.
