### ISSUE TITLE
Server setting improvement

### ISSUE THREAD

**Issue by pmax22** [ddnet/ddnet#7124]
This is something I suggested on DDNet's discord.
![image](https://github.com/ddnet/ddnet/assets/14247576/6f461ca5-4c12-47c1-bea0-62ad62857cec)

I also shared the idea to k2d222 here:
https://github.com/k2d222/twwe/issues/77

**Comment by pmax22** [comment]
I believe it's possible to extract all the values from https://ddnet.org/settingscommands/

**Comment by ChillerDragon** [comment]
Related issue  #1406

**Comment by Marmare314** [comment]
Looks good, but I would also remove the entry field at the top. Instead each setting should be editable in place (ie each row is a text entry instead). To me the entry field looks more like a search bar.
