### ISSUE TITLE
Add support for multiple game controllers

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#7127]
The teeworlds code base has this concepts of gamemodes and multiple game controllers that get instantiated depending on sv_gametype. Sadly ddrace/ddnet removed this moddability by hardcoding the ddracecontroller all over the code base. It would be nice if one could create a new file in src/game/server/gamemodes/mod.cpp and in gamecontext add a if statement on this line

```
	m_pController = new CGameControllerDDRace(this);
```

To conditionally run another controller. When using a new game controller ddnet should still run fine. The ddrace.cpp controller should basically be empty or removed. So that not creating one does not break the game. Similiar to how in teeworlds when creating a mod.cpp you get a fully functional dm or tdm based gamemode. It would be nice if for ddnet you get a fully functional ddnet based gamemode.

**Comment by Kaffeine** [comment]
I'm sure DDNet would welcome refactoring removing the casts to CGameControllerDDRace. E.g. the devs accepted such changes here: https://github.com/ddnet/ddnet/pull/3502/files#diff-29ffe32916052e1066eed938021aadfeb29f855d7c63d9c1ca3350aceffb79f3L66

It seems that we (mods devs) are responsible for that cleanup, as there is no strong reason for ddnet devs to spend time on that.

I'd suggest my layout again (and again, there is no reason for ddnet to complicate the code for the sake of mods):
- There is Mod controller referenced by the generic code only in this one line,
- CPlayer class construction delegated to the Controller ([example](https://github.com/infclass/teeworlds-infclassR/blob/1a16492ac5bc5ad04fce44962d199b62c79c0838/src/game/server/gamecontext.cpp#L1707C77-L1707C77)), so it can create Mod-specific CPlayer instances ([example](https://github.com/infclass/teeworlds-infclassR/blob/production/src/game/server/infclass/infcgamecontroller.cpp#L3220-L3250). The mod Player constructor takes a pointer to the mod GameController as the first argument and saves it to access the controller without casts.
- Now the mod CPlayer subclass can create custom mod Characters by overriding `CPlayer::TryRespawn()` ([example](https://github.com/infclass/teeworlds-infclassR/blob/1a16492ac5bc5ad04fce44962d199b62c79c0838/src/game/server/infclass/infcplayer.cpp#L44). The mod Character constructor takes a pointer to the mod GameController as the first argument and saves it to access the controller without casts.

It would be ok to use DDRace GameController from some CDDRaceCharacter.

I'm yet to come to some solution for CGameContext modification. In the most cases we can delegate the work to GameController and customize the behavior in mod subclass but it does not fit everything.
Also most of the mods need custom chat and console commands, and I don't see a way to correctly handle them in the GameController. I added commands registration to the mod Controller but it (expectedly) does not work with server config files (the are not available for `server -f myConfig.cfg`).

**Comment by Kaffeine** [comment]
> The ddrace.cpp controller should basically be empty or removed.

That is questionable. If ddrace will be totally integrated into the game then it will be even harder to modify and opt-out ddnet features. There are some advantages in having ddnet features isolated from basic the gameplay logic to DDRace Game Controller.

With different pros/cons and needs, it _can_ be an acceptable compromise option to move everything from `CGameControllerDDRace` into `CGameController` so we still can override methods to adjust the behavior.

**Comment by ChillerDragon** [comment]
> > The ddrace.cpp controller should basically be empty or removed.
> 
> That is questionable. If ddrace will be totally integrated into the game then it will be even harder to modify and opt-out ddnet features. There are some advantages in having ddnet features isolated from basic the gameplay logic to DDRace Game Controller.
> 
> With different pros/cons and different mod needs, it _can_ be an acceptable compromise option to move everything from `CGameControllerDDRace` into `CGameController` so we still can override methods to adjust the behavior.

The [CGameControllerDDRace](https://github.com/ddnet/ddnet/blob/a07fd521f75e0ef638eb1522b9a391d91870462b/src/game/server/gamemodes/DDRace.cpp) currently holds a lot of core functionality. If a fork adds its own controller it has to either re implement all of that or lose access to features such as teleporters/teams/finish races. All of that should be in the [IGameController](https://github.com/ddnet/ddnet/blob/a07fd521f75e0ef638eb1522b9a391d91870462b/src/game/server/gamecontroller.cpp) which can then either be inherited or overwritten by forks depending on the need. As long as the mod controller and the ddnet controller can not co exist there should be no code in the ddrace controller that a fork might need.

**Comment by heinrich5991** [comment]
Core functionality depends on the game mod. If the game mod doesn't want to have any ddnet functionality, then they'd prefer to keep it in `CGameControllerDDRace`. I see we're in an interesting architectural discussion. ^^

**Comment by ChillerDragon** [comment]
> Core functionality depends on the game mod. If the game mod doesn't want to have any ddnet functionality, then they'd prefer to keep it in `CGameControllerDDRace`. I see we're in an interesting architectural discussion. ^^

It is cleaner to overwrite a method and do not call the parent class to opt out. Than to copy paste code that has to be maintained and updated to opt in.

**Comment by Kaffeine** [comment]
@ChillerDragon frankly speaking I had come to the same conclusion (and think that it would be better to keep more ddrace stuff in the base game).

Here is my opinion on various parts of DDNet codebase.

#### Controller
I think it would be right to have general (not race-specific) stuff in the base game. If you want more DDRace stuff, you can subclass the mod controller from `CGameControllerDDRace` and again `overwrite a method and do not call the parent class to opt out`. It is also possible to move race stuff to some Race GameController and maybe inherit DDRace controller from that, if that level of complexity makes any sense.

#### GameContext
I'd like to have one Context fit all mods. Maybe we can move most of the mod-specific stuff to `CGameControllerDDRace`? Namely, the chat and console commands. Other mods (e.g. `dm`) don't need those, and can't "override a method to opt them out".

#### Tiles
Probably it would be easier and better for mods compatibility to keep most of the ddrace tiles in the base game, even if some mod won't use them (e.g. I don't see application for freeze tiles in violent mods but hm it does not hurt that much to have it in the code).

#### Teams
I was against CTeam / CTeamCore in the base game API but I found an application for them and now tends to think they are useful for a wide range of gametypes, so they're better to stay in the base game.

#### Entities

It is disappointing to have `ENTTYPE` in `CGameWorld`. It seems to be possible to develop some registration mechanism. Years ago I made some prototype for 0.7 [1](https://github.com/InfectionDust/teeworlds-reinfected/blob/a8ab94219f3f2920527d1ffd9cb0a61f671c7a0f/src/game/server/infclass/infcgamecontext.cpp#L82-L93), [2](https://github.com/InfectionDust/teeworlds-reinfected/blob/a8ab94219f3f2920527d1ffd9cb0a61f671c7a0f/src/game/server/infclass/infcgamecontext.cpp#L25-L47) but I'm yet to get back to this topic. This is something I can work on as a part of my contribution to https://github.com/ddnet/ddnet/issues/7042.

In my idea `CGameWorld` 'll have an API for custom entities registration. `IGameController` 'll register the base game classes, and the Mod Game Controller 'll register the mod-specific classes.

**Comment by sjrc6** [comment]
I recently did exactly what this discussion is about, making a new game mode by creating a new game controller, my issue isn't losing things in the ddnet controller as much as other parts of the code cast the m_pController to CGameControllerDDRace so you have to keep those functions in your controller, I did a macro hack to avoid renaming all those casts. 

I don't see many downsides to moving ddnet specific stuff into the CGameControllerDDRace, assuming there is only 1 controller active at a time it's very easy to just copy anything you need to your new controller, although it would make merging harder.

**Comment by ChillerDragon** [comment]
> I recently did exactly what this discussion is about, making a new game mode by creating a new game controller, my issue isn't losing things in the ddnet controller as much as other parts of the code cast the m_pController to CGameControllerDDRace so you have to keep those functions in your controller, I did a macro hack to avoid renaming all those casts. 
> 
> 
> 
> I don't see many downsides to moving ddnet specific stuff into the CGameControllerDDRace, assuming there is only 1 controller active at a time it's very easy to just copy anything you need to your new controller, although it would make merging harder.
> 
> 
> 
> 

Yea this issue is basically about removing the casts. And got super side tracked.

**Comment by heinrich5991** [comment]
Yea, these casts should go away.
