### ISSUE TITLE
Client and server should quit immediately when running as admin/root

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7131]
There should never be a reason to need elevated privileges (root on Unix, admin on Windows).

This will prevent issues where files/folders were created as admin and are not readable/writeable for the normal user.

**Comment by heinrich5991** [comment]
I don't know much about Windows in that respect. As far as I understand it, most users use a single admin account for all their work. But there's still these UAC prompts that they sometimes have to confirm. What exactly should we detect on Windows?

**Comment by Robyt3** [comment]
On Windows we should detect if the client was launched with "Run as Admin", i.e. by confirming the UAC. Launching the client without these elevated privileges but as a user belonging to the admin group should still behave the same as before.

**Comment by Robyt3** [comment]
Currently too annoying that we have to add a flag to disable it because the GitHub Windows runners run everything with admin privileges.
