### ISSUE TITLE
Chat rendering bug on OpenGL

### ISSUE THREAD

**Issue by HiRavie** [ddnet/ddnet#7151]
Join a server and wait for chat to disappear, then use `chat all hi`
![screenshot_2023-09-08_17-24-14](https://github.com/ddnet/ddnet/assets/65019210/1210f964-3cd9-4e89-a2c3-acb42b2097a6)

**Comment by furo321** [comment]
I'm able to reproduce it with `cl_showchat 0` and `cl_showquads 0`.

**Comment by Robyt3** [comment]
Thanks, I can also reproduce it with those settings when using OpenGL. For me it appears like the screen is not cleared exactly when the caret in the chat input is rendered.
