### ISSUE TITLE
PNG images using an indexed color palette cannot be loaded

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7157]
The log message "bytes in row incorrect" is printed if you try to load a PNG image that uses an indexed color palette.

Supporting PNGs with an indexed color palette would allow us to optimize these images more and reduce the total install size. This also would reduce issues like #7121 in the future. The online PNG optimizers that I tried were not configurable, so they will use an indexed color palette if it reduces the size.

We already show the pnglite incompatibility warning for skins with an indexed color palette, so I think it's fine if we actually support loading those images in the client.

**Comment by heinrich5991** [comment]
> Supporting PNGs with an indexed color palette would allow us to optimize these images more and reduce the total install size.

By what amount?

> This also would reduce issues like #7121 in the future.

That can also be fixed by adding a check in CI.

**Comment by Robyt3** [comment]
> By what amount?

We have less than 10 MB of images in the `data` directory (50 MB of files in total) so it wouldn't save that much in total. For most images a reduction in size of 20%-70% could be expected.
