### ISSUE TITLE
Add a command to list the (available) votes

### ISSUE THREAD

**Issue by Kaffeine** [ddnet/ddnet#7160]
Currently there is not way to get the current list of votes via console. We can add or remove votes but we can't check if there are some extra votes or if some vote removed from the list.

We have:
- `add_vote s[name] r[command]`
- `remove_vote s[name]`
- `clear_votes`
and also
- `force_vote s[name] s[command] ?r[reason]`
- `add_map_votes`
- `vote r['yes'|'no']`

I suggest to add `votes` (like `bans`, `mutes`) or `dump_votes` (like `dump_sqlservers`, `dump_antibot`), or maybe `votes_dump` (like `tune_zone_dump`). Maybe we also want to have pagination (https://github.com/ddnet/ddnet/pull/5375/files).

**Comment by Robyt3** [comment]
`votes` seems good if it logs them to the console. `dump_votes` if it writes votes to a text file. Pagination is definitely necessary for official servers.
