### ISSUE TITLE
add cmd deep

### ISSUE THREAD

**Issue by trikiman** [ddnet/ddnet#7161]
why only undeep? in f2

**Comment by Robyt3** [comment]
I see, these commands are only for testing anyway, so it doesn't really need a discussion.

There are other asymmetries as well:

- `ninja` exists but not `unninja`
- `unsolo` exists but not `solo`

**Comment by murpii** [comment]
We currently offer `unsolo` and `undeep` only as chat commands for practice. It would be logical to also provide them as server commands.

**Comment by sjrc6** [comment]
if we have these commands we might as well make them complete

**Comment by trikiman** [comment]
1 when u tested map or create on lan/public server.
2 Some times u need deep dummy/player.
3 here 2 ways how do to that 1 open edit map, add deep tile, save map, reload map, teleport into plays where u place deep tile and last teleport into place where u test. ah and ofc after all u need dont forget delete this deep from map after test
3.1 second way can  u already find deep tile on map, but here can be problem, on one tile can be 2 tiles (simple: deep and start) on dummy map is it often. its problem cus need team require, need strong, need no use any cheat(if use u cant join team). 
3.2 so all this is not problem if u do it one time and just waste about 5-15 sec. but if ur player/dummy just killed u need do it again and again every time.
4 so if there was a command deep it will be save about 10 min per test one map where deep parts exist.
