### ISSUE TITLE
Reckoning core updating each tick

### ISSUE THREAD

**Issue by 0xfaulty** [ddnet/ddnet#7170]
Seems m_ReckoningCore (server side) updating each tick even when one tee on server stand still, no direction moves, no cursor moves. Based on the data in the Predicted character is always wrong (check my screenshot) and because of this it always doesn't equals so do re-send.  
  
![image](https://github.com/ddnet/ddnet/assets/22517228/fce4a57d-646f-4587-8ea7-a164d2cb631f)
![image](https://github.com/ddnet/ddnet/assets/22517228/0cd4b39f-08a0-43a8-a4d3-6c39f11f091d)
![image](https://github.com/ddnet/ddnet/assets/22517228/95581810-95ba-4fb3-9b3e-38618c32ec29)

**Comment by 0xfaulty** [comment]
I compared with teeworlds, seems it was broked two yers ago by adding Reset() call to CCharacterCore::Init()

**Comment by Learath2** [comment]
While investigating this I've also found that `m_Jumps = -1` (only ground jump available) completely breaks reckoning since `DDRacePostCoreTick` is where it's accommodated for and `m_ReckoningCore` does not go through it. Not sure who to ping to get it fixed :)
