### ISSUE TITLE
HTTP Map download segfault

### ISSUE THREAD

**Issue by Learath2** [ddnet/ddnet#718]
https://paste.pr0.tips/B3

Appears to be some kind of race condition when a map changes while another map is being downloaded. Unfortunately I wasn't running it in gdb :/

**Comment by def-** [comment]
Does your OS/distribution save core files somewhere by default?

**Comment by Learath2** [comment]
No it doesn't. Don't think it generated a core dump.

**Comment by def-** [comment]
Then enable it for the future, very useful: https://wiki.archlinux.org/index.php/Core_dump

**Comment by Learath2** [comment]
I'll just assume it's #727, no point keeping this open.
