### ISSUE TITLE
Veto powers shouldn't reset on map change

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#719]
I right this very moment find myself playing the same map over and over (dying) because SP | Someone is circling us like a vulture waiting to changemap at 19:59 if we decide to try another. The whole "20 mins in server gives you veto powers" should persist after a map change.

**Comment by def-** [comment]
Not sure if that's so easy to implement. I think the players reconnect to the server on map change.

**Comment by east** [comment]
Wasn't it only about being 20 minutes in race?
> Not sure if that's so easy to implement. I think the players reconnect to the server on map change.

Nah, that's not the case. The engine client itself is not reconnected only the gamecontext player.

**Comment by heinrich5991** [comment]
> Wasn't it only about being 20 minutes in race?

You have to be 20 minutes into the race or twenty minutes on the server AFAIK, one suffices.

Not sure if this is the right way to deal with the problem. One person being able to outvote others seems to be the actual problem. Did it look like bots?

**Comment by def-** [comment]
Well, if you have 5 public IPs, there's no problem connecting from all of them to a server and forcing every vote, even without bot.

**Comment by heinrich5991** [comment]
Well, can we do anything against that? Interesting question.

**Comment by def-** [comment]
Give everyone veto, so that votes have to be unanimous.

**Comment by heinrich5991** [comment]
This problem is not unique to map votes, is it? Kick votes can be just as harmful to a single player.

**Comment by def-** [comment]
Yeah, but being unable to kick a blocker is even more harmful.

**Comment by d3fault** [comment]
I disagree that votes should be unanimous, that would be annoying. The core problem is unsolvable because SP | Someone has unlimited IP addresses. And yea @heinrich5991 it's not unique to map votes... but to evade SP votekicking you, just join a team.

**Comment by Learath2** [comment]
Unlimited IP addresses? He should stop being greedy and share some... \s

Veto is supposed to protect players that are in the middle of a run, don't think it'd be appropriate for being on the server for 20 mins. What about unanimous votes ignoring people that didn't vote?
