### ISSUE TITLE
Add our own buffering for Windows file I/O

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7226]
We are not using the internal buffer for I/O on Windows anymore due to #6937.

Although no problems have been reported yet, it seems like a good idea to do our own buffering to avoid too many `ReadFile`/`WriteFile` calls.

An analysis of the I/O operations showed that the number of writes has increased severely due to removing the buffer:

- Saving large map file:
   - Without buffer: 3500 writes
   - With buffer: 379 writes
- Saving `ddnet_settings.cfg`:
   - Without buffer: 2310 writes
   - With buffer: 14 writes

**Comment by heinrich5991** [comment]
I think it might be nice to go back to using `FILE *` for file handling on Windows, would there be any blockers to this? I think we can at least go from `HANDLE` to `FILE *`: https://stackoverflow.com/questions/70490289/get-file-stream-from-file-handle. Maybe the other way around also works.
