### ISSUE TITLE
Multi-line chat overlap

### ISSUE THREAD

**Issue by Learath2** [ddnet/ddnet#723]
This one seems to be older. It's the wrapping algorithm for `CTextCursor`, it just can't find where to break so it inserts a `\n` which is obv wrong.

![image](https://cloud.githubusercontent.com/assets/490500/24835599/ac5b0488-1d06-11e7-921c-2f2765860d06.png)

**Comment by d3fault** [comment]
There seems to be many variations of this, heh "no good deed goes unpunished" @Learath2 (thx for the hearts ;-P). Here's one involving the scoreboard.

Steps to reproduce:
1) Join a server that sends you a "welcome" message in chat (DDNet main)
2) Type a message (or receive one from someone else)
3) Press tab to bring up the scoreboard, observing that the "welcome" message now overlaps the player message

I couldn't confirm that this _only_ works with a server "welcome" message (/lazy), but it at least works with that.

![untitled](https://cloud.githubusercontent.com/assets/7715155/24840894/8ca3789e-1d2b-11e7-89fe-0a1fc3386eda.png)
^It's hard to see, but under the server welcome message I wrote the chat message "test"

**Comment by d3fault** [comment]
Here's another one, this time not involving scoreboard or server welcome message. The player is on me friends list tho...
![untitled2](https://cloud.githubusercontent.com/assets/7715155/24841474/94ff5792-1d3a-11e7-85e8-d5ab75999b05.png)

**Comment by Learath2** [comment]
If you see one of these again can you disable friend messages and check again?

I'm sure I didn't see these before :/

**Comment by Rootkitee** [comment]
Learath same drill :)?

**Comment by Learath2** [comment]
They don't seem to be in 10.4.3 :/

**Comment by Learath2** [comment]
Well I'm stuck I really don't see why the last one is happening nor can I find a good solution to the one I reported. Open to suggestions :(

**Comment by def-** [comment]
I think this is fixed.
