### ISSUE TITLE
Leaderboard size drops last clan-name character

### ISSUE THREAD

**Issue by ExcuseMeSir** [ddnet/ddnet#724]
If i put in a clan name the last letter is not shown even though it's not more than allowed.
![screenshot_2017-04-09_15-04-45](https://cloud.githubusercontent.com/assets/27141237/24837524/69c40112-1d36-11e7-8765-8c5fd0623274.png)
It changes if the Leaderboard expands.
![screenshot_2017-04-09_15-09-19](https://cloud.githubusercontent.com/assets/27141237/24837530/8dad5aec-1d36-11e7-93f7-03202e8e7a09.png)
I play Teeworlds in Fullscreen.
Version: v.0.6.3, 9.2
OS Windows 10

**Comment by Learath2** [comment]
Should be an easy fix for someone who knows what all the constants in `scoreboard.cpp` are about. They were last touched by GreyFoX, oy and SushiTee...
