### ISSUE TITLE
RFC: Overhaul demo browser UI

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7275]
The following screenshots show my proposed overhaul of the demo browser UI.

The demo details are moved to a side panel on the right, which is the same size as the server browser side panel.

The side panel can be collapsed/expanded with the button above the scrollbar.

The UI elements in the bottom are moved and most of them use icons.

The "Markers" column is removed to get back some vertical space and because I don't consider it very useful see for all demos and sort by.

Screenshots:
- Changes:
![changes](https://github.com/ddnet/ddnet/assets/23437060/108b72d5-9a59-4949-a135-565cee86dae5)
- Before:
![old](https://github.com/ddnet/ddnet/assets/23437060/51bb7ead-4151-4835-a259-82c04c1a60aa)
- Before (1280x1024): 
![old_5-4](https://github.com/ddnet/ddnet/assets/23437060/402086b0-7603-4fc5-9843-4ae9fc4ae1bf)
- After:
![new](https://github.com/ddnet/ddnet/assets/23437060/5577364b-2cc5-4a01-a1f8-3606708118a5)
- After (side panel collapsed):
![new_collapsed](https://github.com/ddnet/ddnet/assets/23437060/a8978b17-2dba-41b1-99d1-ad5c5a7d83a8)
- After (1280x1024):
![new_5-4](https://github.com/ddnet/ddnet/assets/23437060/be5dc3eb-c4db-49c5-b706-93357a2015c4)
- After (1280x1024) (side panel collapsed):
![new_5-4_collapsed](https://github.com/ddnet/ddnet/assets/23437060/4b9e8f1d-6c09-4cd0-bc72-3a4801b0bcde)

**Comment by def-** [comment]
Is there a good reason to collapse the sidebar?

**Comment by Robyt3** [comment]
> Is there a good reason to collapse the sidebar?

It would allow reading slightly longer filenames temporarily, but that's not convincing enough to have this feature.
