### ISSUE TITLE
Add admin interface for maps (or files) upload

### ISSUE THREAD

**Issue by Kaffeine** [ddnet/ddnet#7285]
Add a UI allowing players with admin access to upload maps to the server.

The task splits onto network and UI parts. I'm not really familiar with the networking and/or maps download process so the only thing I can say is that we'd need a custom message to upload a file.

For the UI I see the follow options:
1. Some custom console (F1) command which lookups for a given map name in the standard directories and using RCON access upload the file to `$config_directory/maps`.
2. Add a new `Server` tab (maybe replace or enhance the `Server info` tab for admins) and add some 'upload a map' button somewhere. There is a big room for new options, e.g. we can add a file or maps browser and options to add/remove/replace or activate (`sv_map`) any of them. It makes some sense to use `Server info` because we can make the server name and MOTD fields editable.

The main issue is that it is complicated to organize file upload access for admins (who are not familiar with `ssh` and other stuff). I see there are possible security risks but I'm sure a lot of small servers would accept it.

**Comment by ChillerDragon** [comment]
Could you elaborate?

**Comment by Kaffeine** [comment]
@ChillerDragon sure (I'm sorry I didn't submit the whole text at once)

**Comment by def-** [comment]
Use ssh. This is outside of our scope.

**Comment by Learath2** [comment]
Or sftp/ftp for less tech savvy admins. I agree not really something I think we should implement in the game

**Comment by Kaffeine** [comment]
Okay, I see your points about the in game admin UI. The hoster'd have to admin an extra service, open extra ports, and teach the admins how to use it but ok. I didn't really expect you to like the idea but I had to take the chance.

What would you say about a long-term goal to create a web admin panel? The logs and econ are cool but not really convenient. We deserve better tools.
I imagine a web panel with:
- overview (similar to 'server info' ingame tab)
- current player list (click+confirmation to mute/kick/ban),
- the chat stream with infinity backlog, search, and options to moderate in a few clicks
- the full configuration like `about:config` in virtually all browsers),
- the maps list,
- the votes list,
- logs and econ for completeness
- the performance graphs (e.g. game tick processing time; I've seen [ddnet graphs](https://ddnet.org/stats/server/))

Such panel can utilize an extra access to the server, maybe some REST API.

**Comment by ChillerDragon** [comment]
A rest API seems redundant. Most of that can be implemented with Econ or fifo already. A websocket endpoint in the server would be nicer for that.

But yea sounds like a nice community project.

You can also try using/extending existing projects such as trashmap and upTee https://github.com/upTee/upTee
