### ISSUE TITLE
add into frend list into f1

### ISSUE THREAD

**Issue by trikiman** [ddnet/ddnet#7286]
some times u need add friend pll who already left server (simple if u flw him) . it will be great if u can add on friend list  on f1.

**Comment by Steinchen99** [comment]
What exactly do you mean by that? I couldn't quite figure out what you are trying to say.

**Comment by trikiman** [comment]
![image](https://github.com/ddnet/ddnet/assets/39918652/ee679e2a-09da-4509-bdd8-8ab14b2ac208)
i mean u can add into frind just cklicing by mouse

**Comment by trikiman** [comment]
> What exactly do you mean by that? I couldn't quite figure out what you are trying to say. There already is the command "add_friend" for f1

i didnt know about that but will more ui freindly if possible add to friend just by mouse.

**Comment by Learath2** [comment]
This is far too much work, the console isn't built for this, there is nothing clickable in there. I think you can just copy and paste the name and do `add_friend`.

**Comment by Robyt3** [comment]
Agreed. This is too specific and too much work. You can select your friend's name with the mouse and copy it with Ctrl+C. Then paste it to use the command `add_friend`.

**Comment by trikiman** [comment]
ye i didnknow about it, so i will do it. htas better then other ways.
