### ISSUE TITLE
Allow importing mp3 files

### ISSUE THREAD

**Issue by Marmare314** [ddnet/ddnet#7298]
I'm not sure how feasible this is, but it would be very convenient if some other common sound file formats could also be imported into the editor. They would then need to be converted internally.

**Comment by def-** [comment]
Not worth it, the sound feature in maps is not used widely anyway.

**Comment by Robyt3** [comment]
I don't think we should add more image/sound format decoders to the client. Too much work for only a minor improvement to convenience.
