### ISSUE TITLE
Mod Support: Support custom sound events

### ISSUE THREAD

**Issue by Kaffeine** [ddnet/ddnet#7299]
Feature request: support a netmsg to play a custom sound (e.g. embedded into the map or downloaded via https://github.com/ddnet/ddnet/issues/7296).

We'd want to play a sound at a certain position (like `NETEVENTTYPE_SOUNDWORLD` does) or globally, like it does `NETEVENTTYPE_SOUNDGLOBAL`.

Right now most of the mods have to use flag captured/drop/returned global sounds to announce important events, and re-use default sounds for our custom events. The biggest issue is that there is no sound which would fit certain use-cases. E.g. I need a short alarm/warning sound to warn the player about a building destruction (similar to a bomb timer 'beep' sound). I'd also like to use custom sounds for the many custom weapons/objects.

I think this does not strictly require #7296 as we can use the map embedded sounds for now. I'm yet to come with a detailed plan (can take days), feel free to suggest it.

Would it make sense to reference the sounds by SHA256 or we'd prefer short string names or something else?

The server can send an indexed list of custom sounds and use those indices instead of sha/names. Another benefit is that (later) the client can use the list to download the missing assets (#7296).

**Comment by fokkonaut** [comment]
All of that is possible using https://github.com/ddnet/ddnet/issues/7042#issuecomment-1729472518
But again, no official answer from ddnet, so...

**Comment by Kaffeine** [comment]
> All of that is possible using [#7042 (comment)](https://github.com/ddnet/ddnet/issues/7042#issuecomment-1729472518) 

Some forks have server and client side LUA support but there is no code implementing a communication channel between the server-client scripts. Having that in DDNet is a too distant, complex and very questionable goal.

Do you mean that you'd prefer to have it this way: server-side LUA sends custom event to the client-side LUA and the client script parse it and plays the sound?

**Comment by ChillerDragon** [comment]
Can this be closed as completed @Kaffeine?

https://github.com/ddnet/ddnet/pull/8723 got merged
