### ISSUE TITLE
Insertion of content with line breaks into chat is disfigured

### ISSUE THREAD

**Issue by Socialdarwinist** [ddnet/ddnet#731]
If you take a file with multiple lines – I have done it with config files with not too long lines –, copy some contingent lines into the clipboard and paste them into a chat, the following happens:
The first two lines get sent separately without further user interaction.
If you try to send the rest by the Enter key, only the last line gets sent.

**Comment by def-** [comment]
That's kind of expected to me. The server just rejects your spam.

**Comment by Socialdarwinist** [comment]
Why spam? I wanted to send configurations in that case. Better that newline characters get replaced by tabulators or something like that.

**Comment by def-** [comment]
But it's a newline, why would it be replaced by anything else? You could replace them in your editor beforehand. Spam because players should not be able to send 10 lines in less than a second or something like that.

**Comment by Socialdarwinist** [comment]
If the newline is replaced by a non-newline character, it is not 10 lines, huh? Certainly the described behavior is the most awkward behavior against spam.

**Comment by def-** [comment]
Then your line gets too long and will be cut off anyway.

This is supposed to be a game client, not a general purpose chat.

**Comment by Socialdarwinist** [comment]
Well, maybe peope share contents of their Teeworlds configuration files. Or else, people met there and do not know each other on other channels, so past some things btw. And then there is nothing wrong with it if private messages (/w) are used.
There is still no answer here why the newline characters causes lines to be sent immediately after pasting, without user interaction.

**Comment by def-** [comment]
We only support sending and receiving a single line. So the newline character is like pressing enter in the chat, causing the lines to be separated.
