### ISSUE TITLE
Make mode switching more intuitive

### ISSUE THREAD

**Issue by Marmare314** [ddnet/ddnet#7313]
Currently it is not very obvious that the `Layers` button switches between the different editor modes (map view, image view, sound view). The simplest solution is to just have 3 buttons:
![screenshot_2023-10-07_00-24-11](https://github.com/ddnet/ddnet/assets/49279081/1c5e7337-dc11-4c46-81d6-f5ba87cd8354)
Although it is not as pretty as the old button it is a lot more intuitive.

Another option would be to remove the image and sound view and use popups for them instead, which would be accessible from the menubar. I like this option better, however it would be a lot more work to implement.

**Comment by furo321** [comment]
What about a dropdown button instead?

https://github.com/ddnet/ddnet/assets/141338449/59b0fdc3-f4d6-4de3-8ba6-518b73944505

**Comment by Robyt3** [comment]
Positioning three buttons like in the first screenshot doesn't fit, because the chat mentions and ingame moved warning are already shown above the layers button.

I think adding a dropdown could be disruptive for our mappers. You'd need another click to switch each time.

Maybe all three buttons icons would fit next to each other in one row if you used icons instead.

**Comment by Marmare314** [comment]
> Positioning three buttons like in the first screenshot doesn't fit, because the chat mentions and ingame moved warning are already shown above the layers button.

They could also be moved somewhere else. They could fit nicely into the status bar if they are made shorter using icons.

**Comment by Robyt3** [comment]
I think three tabs with icons [layer-group](https://fontawesome.com/search?q=layer-group&o=r&m=free), [images](https://fontawesome.com/search?q=images&o=r&m=free) (or [image](https://fontawesome.com/search?q=image&o=r&m=free)) and [music](https://fontawesome.com/search?q=music&o=r&m=free) would fit.
