### ISSUE TITLE
multispec issue

### ISSUE THREAD

**Issue by trikiman** [ddnet/ddnet#7332]
If someone don't press any buttons about 10 sec (pplz can set up it by urself) multispec ignore this tee.
 
 For what?
 8 ppl  team
 6 wating when last 2 catch other.
  so i dont wanna watch how 6 other just stay afk.
  i wanna watch how last 2 do parts.

**Comment by Robyt3** [comment]
You can select the individual players to spectate in the spectate UI, I don't think we want to add unexpected behavior where players are removed from multiview after some time.
