### ISSUE TITLE
Render Demo: Add Option to adjust zoom level before rendering

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#7334]
Suggestion by filop on Discord:
> ![image](https://github.com/ddnet/ddnet/assets/60477660/3c4a9ce0-4620-4727-9d27-18ccf4744f79)
like this
im playing on 14 zoom
so every time i want to demo
im going to setting and discount zoom

**Comment by Jupeyy** [comment]
he can pause the rendering with the pause symbol... isnt that good enough?

**Comment by murpii** [comment]
> he can pause the rendering with the pause symbol... isnt that good enough?
The video pause, along with the user interface, is then included in the Video as well. I don't think people want that.

**Comment by Jupeyy** [comment]
oh ok. then i guess the pause feature is kinda buggy

it should not render at all and u can resume the demo with space bar (so no UI)

**Comment by murpii** [comment]
> oh ok. then i guess the pause feature is kinda buggy
> 
> it should not render at all and u can resume the demo with space bar (so no UI)

When you examine the screenshot closely, you'll notice that the pause feature isn't the only problem. 😸

**Comment by Robyt3** [comment]
You mean the broken layout on 5:4 resolutions? I'll fix that.

**Comment by Robyt3** [comment]
Pausing works correctly. Frames are only rendered to the video file when the demo playback is not paused. As long as you close the demo controls before you unpause, you won't see them in the rendered video. The play/pause indicator is not included in the rendered demo either.
