### ISSUE TITLE
Disable debug commands in the release version

### ISSUE THREAD

**Issue by Zwelf** [ddnet/ddnet#736]
Compiling the release version of the client may exclude the debug commands, so this unexpected behavior can not happen again: https://forum.ddnet.tw/viewtopic.php?f=45&t=5131

**Comment by def-** [comment]
Don't see why.

**Comment by PathosEthosLogos** [comment]
Maybe make it require confirmation from the player

**Comment by Learath2** [comment]
I don't see how it can be confused with anything else, they are clearly marked with `dbg_*`.

**Comment by H-M-H** [comment]
Please consider the average age of our players :P

**Comment by def-** [comment]
Nope
