### ISSUE TITLE
Entering in menus doesn't work after opening console

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#738]
start writing in player name field in settings, open console (f1), close console, can't write anymore.

**Comment by Learath2** [comment]
@necropotame maybe? #683 might fix that too.

**Comment by Socialdarwinist** [comment]
I want to mention that you cannot write in the chat anymore either after opening the console, which annoyed me much already because I want to reread sometimes by the console whereto I am actually answering.

**Comment by Socialdarwinist** [comment]
It is likely related to #577.

**Comment by def-** [comment]
Fixed
