### ISSUE TITLE
Improve support for t0 runs

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7380]
We should better support t0 runs without having to manually set a password on servers.

**Comment by murpii** [comment]
My suggestion on discord was to allow players to apply team 0 rules to teams. IDK how feasable this is though.

**Comment by bencie** [comment]
Maybe a new team that acts like a second team 0, but of course those players can't interact with the actual team 0? This new team could also have /lock and /invite enabled so that randoms or trolls can't prevent them from speedrunning

**Comment by heinrich5991** [comment]
What @bencie or @murpii said sounds good, I'd also like that from a theoretical perspective.

An interesting question would be if it's too complicated to implement without too many bugs.
