### ISSUE TITLE
Add Favourite Ghosts + Ghost Sorting

### ISSUE THREAD

**Issue by teini94** [ddnet/ddnet#7386]
Make Ghosts sortable in ghost menü
by Time / Date / Name / Favourites (sorted by time) (favourites to Compare) Black Star/ [Super Favourites for All Time Best Runs] White Star

- so u can mark ur best runs even tho they have 1 fail in it.
- comparing

**Comment by Robyt3** [comment]
Ghost sorting seems useful I guess. Not sure about the favorite ghosts, but if anyone wants implement it I wouldn't be against it (see favorite skin code for reference).
