### ISSUE TITLE
Editor PointPopup displays invalid hex color value

### ISSUE THREAD

**Issue by Kaffeine** [ddnet/ddnet#7409]
Regression after commit bb5e203f3a96db25812e1b64a2ca00fd7f84f624.

Before (the correct and expected hex value):
![image](https://github.com/ddnet/ddnet/assets/374839/236da76f-6f37-4402-b6b9-55974cbc0432)

After (`#0208ff80` has invalid red and green components):
![image](https://github.com/ddnet/ddnet/assets/374839/7dd9de9a-4c80-49d3-808d-9d19525d120e)

CColor components are `{r = 1, g = 3, b = 255, a = 128}`.

**Comment by Robyt3** [comment]
See #5844. I think the best solution would be to avoid the conversion between RGBA and HSVA when possible, by making the color picker popup support both RGBA and HSVA in different tabs. Using the RGBA tab exclusively would preserve the correct colors in the editor, whereas using the HSVA tab would preserve correct colors for config variables.

**Comment by Kaffeine** [comment]
> This is caused by lossy conversion between different color formats. The config variables are integers that represent colors as HSLA with 8 bit per component (0 - 255). The color picker internally uses HSVA and color components are presented as floats in `[0.0f; 1.0f]`. You can find failing test cases that illustrate the lossy color conversion/packing at https://github.com/Robyt3/ddnet/tree/Color-Conversion-Tests. Not sure if this is solveable.

I thought there is some rounding issue (like a `floor` or `ceil` instead of `round`). Would double precision in the dialog keep both color representations accurate enough?

------
For Infclass I use colors to encode extra data for (clipped/invisible) quads. In this particular case the green component defines the damage points on the quad touched by a tee (here on the screenshot, a tee 'll lose 3hp per sec on the fire). It is a bit unfortunate for ddnet editor users to have this value messed up.

We have to use a [custom map editor](https://www.teeworlds.com/forum/viewtopic.php?id=11710) with [PTUM](https://github.com/ddnet/ddnet/pull/601) for better mods support but of course some users are used to DDNet editor and want to use it despite of the missing mods support, and this color editor is the show-stopper for them.

It is disappointing to have a custom standalone editor (yet another big codebase I have to maintain) but we have what we have.

**Comment by Robyt3** [comment]
> For Infclass I use colors to encode extra data for (clipped/invisible) quads. In this particular case the green component defines the damage points on the quad touched by a tee (here on the screenshot, a tee 'll lose 3hp per sec on the fire). It is a bit unfortunate for ddnet editor users to have this value messed up.
> 
> We have to use a [custom map editor](https://www.teeworlds.com/forum/viewtopic.php?id=11710) with [PTUM](https://github.com/ddnet/ddnet/pull/601) for better mods support but of course some users are used to DDNet editor and want to use it despite of the missing mods support, and this color editor is the show-stopper for them.
> 
> It is disappointing to have a custom standalone editor (yet another big codebase I have to maintain) but we have what we have.

Interesting, thanks for sharing this. I didn't consider that color values would be used for other purposes, so I was not giving this bug much priority because the human eye can't really tell the difference between these conversion errors.

> I thought there is some rounding issue (like a `floor` or `ceil` instead of `round`). Would double precision in the dialog keep both color representations accurate enough?

Naively switching to `double` only seems to improve the precision a bit, but there are still values that cannot be represented with the popup. I think we have to avoid the conversion entirely if we want to avoid losing information, i.e. add an RGBA tab to the color picker popup and change this to the default tab when the color picker is used in the editor. Also refactor the HSVA tab so the existing value is not modified if you only view the value.
