### ISSUE TITLE
Client version format has changed, redundant 0 was added

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7410]
For example shown in the console and in the start menu.

Current master:
![screenshot_2023-11-03_15-56-32](https://github.com/ddnet/ddnet/assets/23437060/8d6da8bc-1c78-471c-b52a-0d5824dcbe4c)

Release 17.3:
![screenshot_2023-11-03_15-57-01](https://github.com/ddnet/ddnet/assets/23437060/551eaa18-89ff-4bf0-b971-89a717995c29)

Was probably not intentional to change the format with all the other version fixes.

**Comment by Kaffeine** [comment]
I'll fix it (feel free to assign the issue to me).

**Comment by Kaffeine** [comment]
This is the issue: https://github.com/ddnet/ddnet/pull/7310#discussion_r1349328591

```diff
-# Extra support for CMake pre-3.0
-if(VERSION_PATCH STREQUAL "0")
-  project(DDNet VERSION ${VERSION_MAJOR}.${VERSION_MINOR})
-else()
-  project(DDNet VERSION ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH})
-endif()
+project(DDNet VERSION ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH})
```

It seems that the code has nothing to do with CMake pre-3.0, it just drops the `VERSION_PATCH` from `DDNet_VERSION` (which we then propagate to `GAME_RELEASE_VERSION` definition in C++.

**Comment by Kaffeine** [comment]
Do we want to always show the minor version component?
IOW, what display version we want for 18.0.0?

1. `18.0`
2. `18`

**Comment by def-** [comment]
18.0 as always.
