### ISSUE TITLE
Ghost doesnt show up if above 100min?

### ISSUE THREAD

**Issue by teini94** [ddnet/ddnet#7413]
Ghosts of 1:30 hours gets displayed but ghosts at 4hous not anymore
maybe 100min is the problem? cause 3 digits?
4hours didnt get saved only into the ghost folder but doesnt show up

**Comment by Robyt3** [comment]
Please share some example ghost files. Zip them to upload them here on GitHub, or send them in #developer on Discord.

**Comment by Robyt3** [comment]
[Just_Speedfly'_tèíñi94®0cK_b600363643cc86528154f06d441cb4078253ae94c7ecb64a9bd9d8ddc53c6e77_tmp_2496.zip](https://github.com/ddnet/ddnet/files/13257632/Just_Speedfly._teini94.0cK_b600363643cc86528154f06d441cb4078253ae94c7ecb64a9bd9d8ddc53c6e77_tmp_2496.zip)

**Comment by Robyt3** [comment]
This ghost file is considered invalid because the number of ticks is `0` and the time is `-1` because it's a temporary file and not from a completed run. I guess it was not deleted properly after recording was restarted, e.g. due to the server restarting.
