### ISSUE TITLE
UX: Store the list of muted players (like we store the friends list)

### ISSUE THREAD

**Issue by Kaffeine** [ddnet/ddnet#7418]
Use-case: a player is stalkering another player — follows on the servers and sends insults. Mute by name could help (until the 'follower' evolve and also change the name every time but it'll make their 'Friends' function useless (the follower friends won't be able to find him/her).

**Comment by Robyt3** [comment]
You can use the `add_foe` command the same way `add_friend` is used to permanently mute players. Making this command more accessible is not wanted. See https://github.com/ddnet/ddnet/issues/3756#issuecomment-813278835.
