### ISSUE TITLE
Ban non-release versions from official DDNet servers

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#7426]
Apparently client authors are trying to get a "nice-looking" number. Obviously, the moment it was widely used for detecting bots, it became useless at it.

We could just ban all versions that do not correspond to an actual release on official DDNet servers.

This would discourage client authors from putting a nonfunctional number there.

**Comment by murpii** [comment]
This doesn't make sense to me. It's still commonly used to identify older bot clients which are no longer maintained.

**Comment by Learath2** [comment]
If we start banning non-release versions automatically, bot authors will just fix it for still maintained clients. I think it's nice as is, skiddies too lazy to use a real version, and users too stupid to set a real version get caught

**Comment by heinrich5991** [comment]
> If we start banning non-release versions automatically, bot authors will just fix it for still maintained clients.

Yes.

The issue I wanted to raise is specifically about **non-bot** client authors thinking they need a good-looking version number.

**Comment by Robyt3** [comment]
Seems good. Client versions are meant to allow the server to handle clients differently depending on the client version. It doesn't make sense to allow clients with unsupported versions. Those client should either send a correct version so they get the correct messages, or not send a version like a vanilla client so they get treated like a vanilla client.

**Comment by sjrc6** [comment]
I think it's better to let them keep sending wrong versions and not performing any automated action so they continue to give themselves away. Cheat clients are currently very unhardened against detection I think it's better if it stays that way.

**Comment by heinrich5991** [comment]
Implemented this into the antibot. Not because it has something to do with bots but because we don't want people to accidentally ban new release versions.

It's only a check that confirms that the sent client version isn't newer than a dynamic number. I put 17040 for the currently released version.

**Comment by Sedonya** [comment]
Bot clients will just switch to the official version, wouldn't that make it harder to detect bad clients?

**Comment by heinrich5991** [comment]
This change is not about bot clients. This change is about (allowed) custom clients messing with the version number in ways that will make them break in the future.
