### ISSUE TITLE
saving the /lasttp position after death

### ISSUE THREAD

**Issue by lolipodass** [ddnet/ddnet#7441]
now, after death the /lasttp command does not work, which reduces the possibilities of the command, it would be very convenient if the position would be saved. Because this command would be very useful on maps where there is a large number of kills

**Comment by furo321** [comment]
Already fixed in #7280.

**Comment by lolipodass** [comment]
@furo321 
And when will it be available on the servers? When 17.4 comes out? And what about saving the full state - i.e. both weapons and solo mode.

**Comment by def-** [comment]
official servers will have it once they restart, usually once per night

**Comment by furo321** [comment]
> what about saving the full state - i.e. both weapons and solo mode.

It's a nice idea, and has already been suggested in #7339. I'll hopefully get around to implementing it soon.
