### ISSUE TITLE
Text in search bar => i have to press `Pos1` and `End` twice

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#7442]
dunno why, but as soon as i put smth in the search bar i have to press pos1 and end twice to navigate to first and last item.

When restarting client it works for the current search filter..  but as soon as it's changed, same stuff

RC

**Comment by Robyt3** [comment]
Seems like it's already a bug in 17.3, not related to the 17.4 RC. The search input uses the Pos1/End keys first if it can and the listbox get the input otherwise.

**Comment by Jupeyy** [comment]
> Seems like it's already a bug in 17.3, not related to the 17.4 RC. The search input uses the Pos1/End keys first if it can and the listbox gets the input otherwise.

ah interesting. is this intendet behavior then?
only problem is that i cannot unfocus the search bar except clicking an item

**Comment by Robyt3** [comment]
> only problem is that i cannot unfocus the search bar except clicking an item

Yeah, that's not ideal, but I'd say that the order of inputs is otherwise intended like this.

**Comment by Jupeyy** [comment]
I dunno if it ever was like that, but i guess it's no bug then.

maybe pos1 & end for the list should have a higher prio, dunno how often u need pos1 in the search bar. Personally i never used it, but purely logically it defs makes sense like it is now
