### ISSUE TITLE
Enforce teeish simplicity for community logos (and replace kog logo)

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#7478]
The logos should be clear/clean and low in details since they are rendered at a small size.
There should be cap on the details that can be included.

I would argue that the current KOG logo is unacceptable and disrupts the current simple and clean look of the client.
Compared to all the other big, low detail and clean icons and graphics used. The hook in the background of the KoG logo is barley visible at that size. And the overall logo looks cheap compared to the ddnet one.

![image](https://github.com/ddnet/ddnet/assets/20344300/9a54db86-2244-4ef6-9c49-8af1cc0122fa)

I am not saying the KoG logo is ugly or unteeish. It looks quite nice in full size on their [web page](https://kog.tw/).

[![image](https://github.com/ddnet/ddnet/assets/20344300/d4b4d3e5-15d6-41ad-89c0-9360b1f0274c)](https://kog.tw/)

It just does not fit color and proportion wise into the ddnet server browser.

![image](https://github.com/ddnet/ddnet/assets/20344300/d62235ec-2cdc-4b79-90c0-2358232b43d0)

**Comment by fokkonaut** [comment]
Enforce teeish - yes. KoG change - no.

**Comment by Avolicious** [comment]
> And the overall logo looks cheap compared to the ddnet one.

Wow. Calling it cheap sounds rude in this context.

**Comment by ChillerDragon** [comment]
> > And the overall logo looks cheap compared to the ddnet one.
> 
> Wow. Calling it cheap sounds rude in this context.

Oh no :c Thats why i did clarify that the logo is nice in full scale. But don't you think the server browser looks broken now? All these tiny white areas look messy compared to the rest of the ui and the ddnet logo.

**Comment by ChillerDragon** [comment]
Maybe the whole scaling of the browser should be refactored. So that logos can render a tee as their icon without it looking too small.

**Comment by Jupeyy** [comment]
> Maybe the whole scaling of the browser should be refactored. So that logos can render a tee as their icon without it looking too small.

i think the browser is already really huge

but i agree that the logo doesn't scale down well.
The hook looks even weirder than it does at fullscale xd
the white outline makes the details of the tee hard to see.

could try different colors. maybe remove the hook and scale the whole icon up a bit

**Comment by ChillerDragon** [comment]
> > Maybe the whole scaling of the browser should be refactored. So that logos can render a tee as their icon without it looking too small.
> 
> i think the browser is already really huge

The players tab looks also like a fine size to me. And in there you can see tees displayed that look clean.

![image](https://github.com/ddnet/ddnet/assets/20344300/3d81803c-d0ff-4a26-bc46-2a67519d5f28)

Imagine a K and G around one of those tees and it would look smooth af.
