### ISSUE TITLE
Codecov should not fail PR runs

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7497]
See #7496.

**Comment by def-** [comment]
I think it should, otherwise codecov might break easily.

**Comment by def-** [comment]
Oh, you meant decreasing coverage, yes, will fix.

**Comment by Robyt3** [comment]
Not yet fixed, see #7503.

I don't think we need the individual annotations:

https://github.com/ddnet/ddnet/pull/7503/checks?check_run_id=18826935888

**Comment by Robyt3** [comment]
Weird, seems like codecov/patch temporarily shows failures but in the end the check goes green again.
