### ISSUE TITLE
`name_ban` should check the player's clan field if it contains any of the banned strings/characters

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#7516]
We have name banned certain characters and strings, but this restriction does not extend to the clan field. This has led to people using the clan field as a workaround to include the prohibited characters/strings instead. Could this be changed?

**Comment by heinrich5991** [comment]
I feel like that's using the wrong tool for the job. Name bans do similarity search, but adding single characters as name ban doesn't work well with similarity search.
