### ISSUE TITLE
Use 0.7 message ids instead of reimplementing as ddnet ex message

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#7518]
https://github.com/ddnet/ddnet/pull/7515#issuecomment-1821223297

Those message ids are unused in 0.6 and were added in 0.7:

[35 NETMSGTYPE_SV_RACEFINISH](https://chillerdragon.github.io/teeworlds-protocol/07/game_messages.html#NETMSGTYPE_SV_RACEFINISH)
[36 NETMSGTYPE_SV_CHECKPOINT](https://chillerdragon.github.io/teeworlds-protocol/07/game_messages.html#NETMSGTYPE_SV_CHECKPOINT)
[37 NETMSGTYPE_SV_COMMANDINFO](https://chillerdragon.github.io/teeworlds-protocol/07/game_messages.html#NETMSGTYPE_SV_COMMANDINFO)
[38 NETMSGTYPE_SV_COMMANDINFOREMOVE](https://chillerdragon.github.io/teeworlds-protocol/07/game_messages.html#NETMSGTYPE_SV_COMMANDINFOREMOVE)
[39 NETMSGTYPE_CL_COMMAND](https://chillerdragon.github.io/teeworlds-protocol/07/game_messages.html#NETMSGTYPE_CL_COMMAND)

Now furo added the racefinish message https://github.com/ddnet/ddnet/pull/7515
And I was thinking about adding the command info messages for ddnet.

Furo implemented it as a ddnet ex net message instead of using the message id 35. Heinrich said this is how it should be. I would propose to implement them using the numeric id. Seems simpler and feels like that is the reason why the net message ex was added in the first place so that now those ids are free to use.

Allows removing duplicated code in the server bridge. For example the following:

```C++
		CNetMsg_Sv_RaceFinish RaceFinishMsg;
		RaceFinishMsg.m_ClientID = ClientID;
		RaceFinishMsg.m_Time = Time * 1000;
		RaceFinishMsg.m_Diff = 0;
		if(pData->m_BestTime)
		{
			RaceFinishMsg.m_Diff = Diff * 1000 * (Time < pData->m_BestTime ? -1 : 1);
		}
		RaceFinishMsg.m_RecordPersonal = (Time < pData->m_BestTime || !pData->m_BestTime);
		RaceFinishMsg.m_RecordServer = Time < GameServer()->m_pController->m_CurrentRecord;
		Server()->SendPackMsg(&RaceFinishMsg, MSGFLAG_VITAL | MSGFLAG_NORECORD, -1);
	}
	else
	{
		protocol7::CNetMsg_Sv_RaceFinish Msg;
		Msg.m_ClientID = ClientID;
		Msg.m_Time = Time * 1000;
		Msg.m_Diff = 0;
		if(pData->m_BestTime)
		{
			Msg.m_Diff = Diff * 1000 * (Time < pData->m_BestTime ? -1 : 1);
		}
		Msg.m_RecordPersonal = (Time < pData->m_BestTime || !pData->m_BestTime);
		Msg.m_RecordServer = Time < GameServer()->m_pController->m_CurrentRecord;
		Server()->SendPackMsg(&Msg, MSGFLAG_VITAL | MSGFLAG_NORECORD, -1);
	}
```

Could just be

```C++
		protocol7::CNetMsg_Sv_RaceFinish Msg;
		Msg.m_ClientID = ClientID;
		Msg.m_Time = Time * 1000;
		Msg.m_Diff = 0;
		if(pData->m_BestTime)
		{
			Msg.m_Diff = Diff * 1000 * (Time < pData->m_BestTime ? -1 : 1);
		}
		Msg.m_RecordPersonal = (Time < pData->m_BestTime || !pData->m_BestTime);
		Msg.m_RecordServer = Time < GameServer()->m_pController->m_CurrentRecord;
		Server()->SendPackMsg(&Msg, MSGFLAG_VITAL | MSGFLAG_NORECORD, -1);
```

**Comment by heinrich5991** [comment]
I think the 0.7 code should go into the translation layer, the DDNet message can be translated into a 0.7 message there.

The if branch you wrote shouldn't be added.

**Comment by heinrich5991** [comment]
By adding numeric 0.7 IDs to our code, we get a mishmash of 0.6 and 0.7 message IDs in our code. I do not like that.

**Comment by ChillerDragon** [comment]
> By adding numeric 0.7 IDs to our code, we get a mishmash of 0.6 and 0.7 message IDs over the network in our DDNet client-server connection. I do not like that.

Yes that would happen. But seems smoother than having the same message twice. Once as 0.6 and once as 0.7. Also what's so ugly about defining the ddnet protocol as 0.6 backwards and partially 0.7 forward compatible at the same time.

**Comment by ChillerDragon** [comment]
> The if branch you wrote shouldn't be added.

FYI it got added

https://github.com/ddnet/ddnet/blob/eba86204db87db93c67f2851a1f44c5428b36960/src/game/server/teams.cpp#L774-L799

**Comment by heinrich5991** [comment]
It should get moved to the 0.7 compatibility layer.
