### ISSUE TITLE
Add chat command info net message from 0.7

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#7524]
Teeworlds 0.7 added a [NETMSGTYPE_SV_COMMANDINFO](https://chillerdragon.github.io/teeworlds-protocol/07/game_messages.html#NETMSGTYPE_SV_COMMANDINFO) net message. I would love to see that in ddnet. It should use the same arguments as the 0.7 message same as https://github.com/ddnet/ddnet/pull/7515 I would also like it to use the same ID but that discussion is held [here](https://github.com/ddnet/ddnet/issues/7518).

It allows us to get rid of the hardcodet chat command completion. Which enables ddnet clients to receive custom commands on custom servers for tab completion. And also is forward compatible to new ddnet server commands.

It also comes in handy for https://github.com/ddnet/ddnet/pull/5949

It also comes in handy for https://github.com/ddnet/ddnet/pull/7087
The streamer censor mode also looks at hardcodet commands. I suggest to extend the [args](https://chillerdragon.github.io/teeworlds-protocol/07/game_messages.html#NETMSGTYPE_SV_COMMANDINFO_args_format) to include some new type such as ``p`` for password. Imo ``s`` for secret would be nicer since it is more generic but that is already used by string. I am not sure if it should be word split like ``s`` or also contain spaces like ``r``. Then the ddnet client can replace all password arguements with *** if the streamer mode is active.

I gave the implementation a try once but then rage quitted on the memory allocation of the commands on the client side. So if anyone wants to take this, please :)

**Comment by Robyt3** [comment]
> The streamer censor mode also looks at hardcodet commands. I suggest to extend the [args](https://chillerdragon.github.io/teeworlds-protocol/07/game_messages.html#NETMSGTYPE_SV_COMMANDINFO_args_format) to include some new type such as `p` for password. Imo `s` for secret would be nicer since it is more generic but that is already used by string. I am not sure if it should be word split like `s` or also contain spaces like `r`. Then the ddnet client can replace all password arguements with *** if the streamer mode is active.

Adding a separate argument type and therefore changing argument parsing shouldn't be necessary for this. It also limits the hidden parameter to string values unless you'd add multiple types for hidden strings, integers etc. Instead, this could be encoded as part of the parameter name, e.g. `?s[hidden:code]` for the `timeout` command.

**Comment by ChillerDragon** [comment]
Yea also sounds good. Not sure if I like the name "hidden" but can't think of anything better
