### ISSUE TITLE
Synchronized option for envelopes is broken

### ISSUE THREAD

**Issue by H-M-H** [ddnet/ddnet#755]
It appears this has been introduced with the new timer. Broken means these envelopes are not adjusted to racetime.

After having a short look the reason is probably that the time for synchronized envelopes is still calculated via gametime which does not work anymore and instead the warmuptime should be used: https://github.com/ddnet/ddnet/blob/3878d6fb56bcdb2fc22f0085466890780bddc16a/src/game/client/components/maplayers.cpp#L105-L110

**Comment by heinrich5991** [comment]
This is on purpose. It is now *actually* synced to all clients, regardless of race time.

**Comment by H-M-H** [comment]
Ok, this leaves the question about the purpose of the synchronized checkbox in mapeditor then. So either we remove this https://github.com/ddnet/ddnet/blob/3878d6fb56bcdb2fc22f0085466890780bddc16a/src/game/editor/editor.cpp#L4453-L4454 or restore its functionality.

**Comment by heinrich5991** [comment]
To my understanding, there's nothing broken (except maybe that string). Synchronized means synchronized over all clients, non-synchronized doesn't give that promise (and isn't, in practice).

**Comment by H-M-H** [comment]
I see, the description for the synchronized checkbox is clearly wrong then. But now I wonder if we need the non-synced way at all, especially as some mapper asked me if it is possible to sync envelopes to racetime, so there could be synced to gametime and synced to racetime. Not sure if this is feasible, if not lets just update the description.
