### ISSUE TITLE
/swap feature?

### ISSUE THREAD

**Issue by ftk** [ddnet/ddnet#756]
The idea is to be able to swap places with another consenting player(position, time, weapons, etc).
This feature has been implemented in, for example https://github.com/SNSnoop/iDDNet and was deemed useful by not-so-pro-gamers.

If this is something within DDNet policy, I can start working on pull request

**Comment by SheikhZayx** [comment]
> If this is something within DDNet policy

Isn't it already kind of possible? Join a team, `/save`, change names, `/load`?
So it seems DDNet approves or at least doesn't prevent it.
IMO a convenient feature as it gets rid of the above mentioned process.

**Comment by FallenKN** [comment]
save and load only works in a team while swap could be used without

**Comment by heinrich5991** [comment]
This isn't using DDRace as intended IMO, I think people should try to play their own race.

**Comment by Henningstone** [comment]
Wasn't this even discussed some time ago somewhere? If memory serves it was rejected due to the reason @heinrich5991 mentioned and something else.
After all, the save and load thing that @SheikhZayx was talking about isn't what it's meant to be used for anyway...

**Comment by def-** [comment]
not wanted, should not be done.
