### ISSUE TITLE
Overlapping doors with different IDs do not work as expected

### ISSUE THREAD

**Issue by Destoros** [ddnet/ddnet#7562]
Building two doors with different IDs, such that they overlap (see picture) disables the top door. 
![grafik](https://github.com/ddnet/ddnet/assets/59802456/b510673e-4654-429e-aec2-d8c374ab2c3d)
Visually it is still closed but the tee can pass through it.

The video below shows two stacked doors with different IDs. First I confirm that the door works by running into it. Next I deactivate the bottom door with ID1 for 3 seconds and now I can easily pass through door 2, even though it should be closed (and is also visually closed). Then I waited a few seconds and verified that both doors were closed again and started the same test for the other door, which delivered the expected result of blocking me, since one door was still closed.
https://github.com/ddnet/ddnet/assets/59802456/b5eb79c1-d7a9-45e8-8ade-529d4bad5d53

Stacking two doors this way always causes **the top door** to be disabled (i.e. only the place of the door inside the map matters and not the ID to determine which door malfunctions)

The expected behavior would be, that both switches need to be hit before a tee can pass through. 

**map**: 
[stacked_doors_bug_map.zip](https://github.com/ddnet/ddnet/files/13507982/stacked_doors_bug_map.zip)

**Comment by Destoros** [comment]
Bump

**Comment by def-** [comment]
I'm afraid of changing anything here since it might break existing maps depending on that behavior.

**Comment by Destoros** [comment]
Ah right, it probably will break something. I guess this can be closed now.
