### ISSUE TITLE
Tees are missed in spec mode

### ISSUE THREAD

**Issue by SleepySlippers** [ddnet/ddnet#7569]
```rust
uname -a
Linux me-GF65-Thin-10UE 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

I just pulled the 17.4 version. And when i press `Q` or `P` spec mode. There are no tees (me included). But sometimes they are spuriously appears for a short amount of time.

I checked out back to 17.3 all works fine.

I could provide more info if you ask me :) .

**Comment by furo321** [comment]
Could you provide a video of it happening?

**Comment by SleepySlippers** [comment]
It was on commit eba86204d but now I cant reproduce such behavior current master also works well. sorry for report. I closes the issue. mb smth was wrong with my laptop
