### ISSUE TITLE
`sv_auto_demo_record 1` doesn't do anything.

### ISSUE THREAD

**Issue by furo321** [ddnet/ddnet#7573]
Due to `DemoRecorder_HandleAutoStart()` being called from `StartRound()`, it won't actually start the demo recording as DDNet doesn't call `StartRound()` anywhere except if you manually do the command `restart`. 

So maybe the starting of a recording should be moved somewhere else?

**Comment by Robyt3** [comment]
The auto server demos seem to use the same demo recorder as the manual demo recording (`record` command) which is also not ideal. The client uses separate recorders for manual recording and auto demos.
