### ISSUE TITLE
HTTP serverlist showing wrong region

### ISSUE THREAD

**Issue by swarfeya** [ddnet/ddnet#7578]
My server is being shown from a different region than it is - it is located in germany, yet it is being shown as being from ASIA (expected EUR) - The IP from the server is 176.116.18.87. Sadly, because of this newer players (that have the serverlist sorted by players & ping) cant see my server in the top.

![image](https://github.com/ddnet/ddnet/assets/135431730/937494e4-737b-426c-845a-839362113773)
![image](https://github.com/ddnet/ddnet/assets/135431730/6cca4685-56fe-4567-accb-6275c4eb8c46)

**Comment by heinrich5991** [comment]
Should be fixed.

**Comment by swarfeya** [comment]
same issue again - i am moving hosts soon & it is being identified as NA (na:us) instead of EU (eu:nl). 
Server-IP: 191.96.11.73
![image](https://github.com/user-attachments/assets/ef320048-e4f5-4808-ba65-9566654c0e28)
