### ISSUE TITLE
Debug and building new version 

### ISSUE THREAD

**Issue by StormAxs** [ddnet/ddnet#7579]
After marge a ddnet to my client while building game i'm getting error with discord

 (C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\objidl.h(10694,14): error C2011: 'IStorage': 'class' type redefinition (compiling source file C:\Users\storm\CLionProjects\StormAcl\src\engine\client\discord.cpp) [C:\Users\storm\CLionProjects\StormAcl\cmake-build-debug-visual-studio\game-client.vcxproj]

C:\Users\storm\CLionProjects\StormAcl\src\engine/storage.h(18,7): message : see declaration of 'IStorage' (compiling source file C:\Users\storm\CLionProjects\StormAcl\src\engine\client\discord.cpp) [C:\Users\storm\CLionProjects\StormAcl\cmake-build-debug-visual-studio\game-client.vcxproj]
) and now while buiding clear ddnet client i'm getting crashed with this reason -  https://i.imgur.com/6f1DXXj.png

**Comment by heinrich5991** [comment]
Does the problem still appear?

**Comment by archimede67** [comment]
I believe this was a custom client and the issue has probably been fixed since then.
