### ISSUE TITLE
Bug: Setting sv_vote_time to any value above 60 causes votes not to be displayed

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#7583]
Title. Tested on a official DDNet server.

**Comment by Robyt3** [comment]
The client currently discards any vote with a timeout longer than 60 seconds. We can change the protocol to along longer timeouts, but the votes wouldn't be shown for old clients. Adding backwards compatiblity for this is not great. The vote timeout is normally only sent once. If we do that and clamp it to maximum 60 seconds than the vote timer will go into the negative on the client-side after 60 seconds. Alternatively we need to send the current vote status to every client every second so old clients would show 60 seconds timeout the entire time until the last 60 seconds. Alternatively, we disallow vote timeouts above 60 seconds.

**Comment by heinrich5991** [comment]
We could potentially remove the limit on the client side, but keep it on the server side for now.
