### ISSUE TITLE
DDNet appdata.xml not being updated anymore

### ISSUE THREAD

**Issue by miguilimzero** [ddnet/ddnet#7607]
DDNet flatpak uses the https://github.com/ddnet/ddnet/blob/master/other/ddnet.appdata.xml file displays relevant information on gnome-software and flathub website. However since version 15.4, the file is not being updated anymore.

Should the file be removed from DDNet repo and moved to Flathub one or updated here?

**Comment by heinrich5991** [comment]
Permalink: https://github.com/ddnet/ddnet/blob/6a858287e9e9ab63a86e30274b8a43ea86a42955/other/ddnet.appdata.xml.

**Comment by def-** [comment]
I don't think it makes sense for us to maintain version numbers manually in the file. What if we just remove them?
