### ISSUE TITLE
DDNet setting impossible screen resolution after switching monitor on Wayland

### ISSUE THREAD

**Issue by miguilimzero** [ddnet/ddnet#7609]
1. Use Linux + Wayland (DDNet native Wayland) (Vulkan)
2. Open DDNet and set fullscreen on the second monitor
3. Close DDNet
4. Open DDNet (The thing here is that DDNet must open fullscreen on the second monitor at first)
5. Change DDNet screen to the primary monitor
6. DDNet will disappear from your screen (but still open)

Even closing and opening DDNet, will not show again. After checking the settings file, the DDNet sets the screen's width and height to 1 and then renders an invisible game:

```cfg
gfx_screen_width 1
gfx_screen_height 1
```

**Comment by miguilimzero** [comment]
@Jupeyy It seems to be. When I open the game on XWayland and try to change the selected screen, the game goes to Windowed mode instead of disappearing.

**Comment by Jupeyy** [comment]
I don't have multi monitor so I cannot test.
Theoretically, if SDL provides cross platform support, it should also perform the same on all logic we implement.

So this is either some undefined logic
a bug in sdl2
a bug in wayland / the compositor

I guess if you want it to be fixed you have to investigate yourself. Or other devs can test their behavior, but i think generally not many ppl here use wayland (yet)

**Comment by miguilimzero** [comment]
I investigated and it was happening only with flatpak version. I bumped the runtime and shared dependencies (https://github.com/flathub/tw.ddnet.ddnet/pull/52), and it's now working correctly. Probably some old bug with SDL2. Thanks for the help.
