### ISSUE TITLE
Document file naming convention

### ISSUE THREAD

**Issue by Kaffeine** [ddnet/ddnet#7623]
Please add file naming conventions — currently most of the file names are lower cased words joined without separator but we also have underscore separated names such as `base/hash_bundled.cpp`, `engine/server/name_ban.cpp`, `game/editor/map_grid.cpp`, etc. It is not clear what is the preferred scheme. There is also [DDRace.cpp](https://github.com/ddnet/ddnet/blob/master/src/game/server/gamemodes/DDRace.cpp).

**Comment by heinrich5991** [comment]
Vote for lowercase with underscores.

**Comment by ChillerDragon** [comment]
Closed by https://github.com/ddnet/ddnet/pull/8288
