### ISSUE TITLE
Password manager and binds based on gametype

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#7633]
https://github.com/ddnet/ddnet/pull/3552 could have saved both problems and is merged in teeworlds. Still think that one is really needed.

If one plays on multiple servers it makes sense to bind arrow keys to rcon up/down/left/right in ddrace but to the chat commands /up /down /left /right in city. And there are a bunch of those. Having a config for every gametype and then cyceling through those with a bind on switching server is just annoying.

Then there are accounts in block, city and now gores too. Having one login bind for all servers would be super useful.

If https://github.com/ddnet/ddnet/pull/3552 is such a big risk (for whatever theoretical and not proofen reason) I suggest solving these issues another way. The client could load an additional config file on entering certain gametypes. And the client could suggest saving credentials that are being sent as chat commands. And auto sending them on the same ip. I actually have a manual password manager in [chillerbot-ux](https://github.com/chillerbot/chillerbot-ux) and that is one of the reasons why I could never switch back to vanilla ddnet again. Having long secure passwords on every server with accounts that exists and casually joining them would not be possible without a password manager.

**Comment by heinrich5991** [comment]
I'd consider this out-of-scope for DDNet.

If we ever get accounts (#3411) in DDNet proper, at least the password problem will be solved.

**Comment by Kaffeine** [comment]
> binds based on gametype

+100. I had to write a custom client for that (and a few dozens of the mod players actually use it).
