### ISSUE TITLE
ESC Bug (+scroll bug, password, editor,)

### ISSUE THREAD

**Issue by teini94** [ddnet/ddnet#7644]
I'm on beta.

1.
- cant close the callvote menu with ESC the first time when I click on callvote anymore AND cant Scroll the votelist , 
before clicking on a vote to close it

- also not if u switch from serverinfo/ghost to callvote.
- also in editor cant close LOAD MAP with ESC. 
- also not if u click save copy in editor 

2. if u enter a password u cant just click Enter anymore u have to click on it
- it also doesnt get accepted instantly even if put in f1

(u cant delete empty rows in callvote menu

**Comment by furo321** [comment]
This has already been fixed by #7635.

**Comment by heinrich5991** [comment]
I.e. will be fixed when the beta is rebuilt during the night. Thanks for the report!
