### ISSUE TITLE
/save dj cheat (bug)

### ISSUE THREAD

**Issue by Ryozuki** [ddnet/ddnet#766]
If you /save while in the air and lost doublejump, you can get it back by loading again.

Reported by Im' corneum here (moderator subforum): https://forum.ddnet.tw/viewtopic.php?f=34&p=53766&sid=2bc2c9f90058aee588ada595f25bf764#p53766

**Comment by def-** [comment]
Please report cheats privately in the future.

**Comment by def-** [comment]
fixed.
