### ISSUE TITLE
Do not let the client assume available chat commands

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#7665]
Since https://github.com/ddnet/ddnet/pull/7649 the server can inform the client about what chat commands it has.
The ddnet client has a list of commands which matches the current ddnet version and it will always autocomplete those.
@furo321 decided to keep that list around. I suggest to remove that hardcodet list. Since it can be wrong on non ddnet servers or on ddnet servers in another version. We can also wait a few releases with this change to give server maintainers time to update. But then we should not keep using a old hack that has misleading autocompletions when there is already a cleaner system in place.

> heinrich5991: having an incorrect list is worse than having no list at all

**Comment by Robyt3** [comment]
> The ddnet client has a list of commands which matches the current ddnet version and it will always autocomplete those.

That shouldn't be the case. As soon as the first chat command message is received the hardcoded commands are removed from the list.

**Comment by ChillerDragon** [comment]
> > The ddnet client has a list of commands which matches the current ddnet version and it will always autocomplete those.
> 
> That shouldn't be the case. As soon as the first chat command message is received the hardcoded commands are removed from the list.

Yes on new servers that do send it. I should have probably clarified that this only applies to servers that do not send commands.

**Comment by ChillerDragon** [comment]
If now a new command is added and that client joins a old server it autocompletes the new command which does not exist. And if it joins a non ddnet server it still autocompletes ddrace commands and some of them might exist while other commands the mod implemented do not get autocompleted which is super confusing for players.

**Comment by Robyt3** [comment]
We should give server mods some more time to start using #7649 before we remove the hard-coded chat commands.
