### ISSUE TITLE
out of bounds copy artifact

### ISSUE THREAD

**Issue by mwinkens** [ddnet/ddnet#7670]
This white line doesn't exist and exists at a part where the background cement is copied because it is out of bounds. 
The vertical white line next to the black bricks, left and right!
This is only happening in the client and not in the editor and not even on every frame!

Screenshot of bug:
![screenshot_2023-12-16_20-18-28](https://github.com/ddnet/ddnet/assets/104770531/6f685499-853e-4008-a061-4fb8f1100a4c)

Same part without bug:
![screenshot_2023-12-16_20-16-46](https://github.com/ddnet/ddnet/assets/104770531/758bb5a8-7cf7-40c5-b646-65ebb6b643d3)

**Comment by Jupeyy** [comment]
can you please name the map?

the editor does not even support tile map extension does it?

**Comment by mwinkens** [comment]
What are you talking about? Here is the map
[run_venice.zip](https://github.com/ddnet/ddnet/files/13693858/run_venice.zip)

**Comment by mwinkens** [comment]
seems to be an issue occuring with fsaa > 0, as we found out in chat
