### ISSUE TITLE
Client crashed on Arch Linux (Vulkan & NVIDIA)

### ISSUE THREAD

**Issue by Bamcane** [ddnet/ddnet#7675]
Client only crashed when use any fullscreen(Vulkan)

**Comment by Bamcane** [comment]
Oh wait, it happened also intel

**Comment by Jupeyy** [comment]
do you use wayland?

**Comment by Bamcane** [comment]
> do you use wayland?

No, X11

**Comment by Jupeyy** [comment]
can you install vulkan validation layers and start DDNet with (https://archlinux.org/packages/extra/x86_64/vulkan-validation-layers/)
`./DDNet "dbg_gfx 4"`

This might only work with Intel, you should have significant performance slowdown if it worked

> Oh wait, it **also** happened when intel
So both Intel & Nvidia? or only one of them?

**Comment by Bamcane** [comment]
Both of them, I'm using OpenGL3.3.0 to render now

**Comment by Jupeyy** [comment]
> Both of them, I'm using OpenGL3.3.0 to render now

so did the validation layers trigger an error in your console?

**Comment by Bamcane** [comment]
I don't why but after i "sudo pacman -Syuu" update the vulkan it's fixed
