### ISSUE TITLE
Colors RGB 

### ISSUE THREAD

**Issue by ElYeK** [ddnet/ddnet#768]
Could Implement A system where possible insert numerically Customize Colors in format RGB.
To have a range more extensive and creating colors Unique .

That's my idea Know If it is feasible Please  :yellow_heart: .

**Comment by Learath2** [comment]
You mean in settings? I was thinking of some kind of HSL color picker a while back. I might do that and add a hex color input at the bottom.

**Comment by ElYeK** [comment]
Exactly based on the Configuration Please add.

**Comment by def-** [comment]
I don't think we need this. You won't be able to select any more colors anyway. The current color selector in GUI is ok.
