### ISSUE TITLE
Add details back to sound layers again

### ISSUE THREAD

**Issue by mwinkens** [ddnet/ddnet#7689]
#7366 removed details from sound layers, but sometimes you map a nice detail or easteregg which is gone with gfx_high_detail 0. Then there is coming sound from no-where

A Tee playing guitar:
![screenshot_2023-12-21_15-57-37](https://github.com/ddnet/ddnet/assets/104770531/968bb7b7-3b45-4395-aa42-d24ceb27da07)

No Tee playing guitar
![screenshot_2023-12-21_15-57-38](https://github.com/ddnet/ddnet/assets/104770531/d4051946-4ea3-42a2-97dd-557d18f818e6)

@def-  @furo321

**Comment by heinrich5991** [comment]
CC #7366

**Comment by mwinkens** [comment]
here is another map from mine, where this feature could be used: https://uniqueclan.net/map/run_aquila_rift
I am not sure if I used it back then.
