### ISSUE TITLE
Handling of maps with unknown UUID map items

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7701]
> This change silently corrupts maps with unknown future items instead of crashing. That seems like a downgrade. IMO, it should either show an error or try to re-add the future map items as well.

_Originally posted by @heinrich5991 in https://github.com/ddnet/ddnet/issues/7693#issuecomment-1868297260_

The same also applies to the editor, which was already doing what the tools are also doing now.

**Comment by heinrich5991** [comment]
The editor is different, I think. The tools try to faithfully reproduce the original data file, only changing a couple of data items. The editor builds up a new map from ground up.
