### ISSUE TITLE
Set Players Into AFK State During Timeout Protection Period

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#7755]
Some players don't immediately try to reconnect to make use of the timeout protection (due to the server being full, for example). The AFK state usually kicks in quite late. So my suggestion is to set all players who are considered timed out by the server into the AFK state early. This should also aid players who managed to stay connected during a DoS attack in determining whom to help and whom to avoid on HH maps.

**Comment by furo321** [comment]
I think that's how it originally worked, but doesn't anymore after some code was changed which broke it (#5781).
