### ISSUE TITLE
Include the current Unix timestamp in the 'Copy info' feature.

### ISSUE THREAD

**Issue by gummibaer12345** [ddnet/ddnet#7756]
It would be great to append a Unix timestamp to the information displayed when selecting 'Copy info' on Server info / Browser.

Example:
[Servername]
Address: ddnet://[Server-address]
My IGN: [Ingame nickname]
[current Unix timestamp]
<t:1704301200:f> copy & paste it in Discord, and you'll witness the magic.

This enhancement makes it effortlessly straightforward to identify the time when this information was retrieved. No more need to ask when a particular event occurred! ^^

**Comment by Chairn** [comment]
It should also include the timezone to avoid times in the future for people more west than the poster

**Comment by Robyt3** [comment]
I don't see the need for this either. Discord shows the exact date a message was posted when hovering the date.

**Comment by heinrich5991** [comment]
> This enhancement makes it effortlessly straightforward to identify the time when this information was retrieved.

I assume you ran into this while administering KoG? Can you give an example situation of when this would be useful.

**Comment by gummibaer12345** [comment]
> > This enhancement makes it effortlessly straightforward to identify the time when this information was retrieved.
> 
> I assume you ran into this while administering KoG? Can you give an example situation of when this would be useful.

I feel a bit silly now! 😄 Honestly, I can't provide a specific example because it was a spontaneous idea, and I didn't think it through. I suppose it's fine to determine the time using the Discord date/time when the message was sent. This feature might come in handy when someone reports a server crash, for instance. In such cases, a mod can simply copy the text and forward it to the admins.... or they could just link to the corresponding original message 😄 . So, I imagine this doesn't happen very often.

**Comment by gummibaer12345** [comment]
> It should also include the timezone to avoid times in the future for people more west than the poster

It converts the time zones for the reader's timezone, basically.

**Comment by heinrich5991** [comment]
> > I assume you ran into this while administering KoG? Can you give an example situation of when this would be useful.
> 
> […] So, I imagine this doesn't happen very often.

I think we don't need the feature then. If we figure out a good reason to have it, we can re-open this feature request.
