### ISSUE TITLE
"Happy DDNet birthday" broadcast is only shown for a split second.

### ISSUE THREAD

**Issue by furo321** [ddnet/ddnet#7758]
https://github.com/ddnet/ddnet/assets/141338449/8505f576-fb73-4308-aef0-a745dd67e31c

This happens because the broadcast is sent before the client knows the current tick. Which means `m_BroadcastTick` will be set to `500` (which is the current tick (0) + 10 seconds). But then the client will receive its first snapshot which will set the correct tick (causing the broadcast to disappear).

**Comment by ChillerDragon** [comment]
Yes big bug! I can confirm! I ran into this issue 10 times hehe
