### ISSUE TITLE
Shields seem to cause issues on map border

### ISSUE THREAD

**Issue by Devinci24** [ddnet/ddnet#7759]
Shields seem to cause issues on map border

![broken_shields](https://github.com/ddnet/ddnet/assets/98612843/7e75cf2a-c314-47af-a044-84c20658f200)

map example:

![broken_shields_map](https://github.com/ddnet/ddnet/assets/98612843/c0bddb58-d9dd-4b4b-8cb5-2972b2710e3e)

**Comment by Robyt3** [comment]
See https://github.com/ddnet/ddnet/issues/6489#issuecomment-1493135874.

According to this error message, you should not put those entities so close to the border. Doesn't seem like a necessary check though, we could probably remove it.
