### ISSUE TITLE
`/tp` command teleports to (0,0) when invalid numbers entered

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7765]
@Steinchen99 reported:

> Everytime i write on this server 
> `/tp brainless tee`
> i get teleported to the upper left corner of the map ( 0 | 0 as coordinates ) 

Names containing spaces need to be quoted now to be used with `/tp`. In the above command the parts of the name are parsed as numbers instead, which gives (0,0) because they are invalid. When a number is invalid, the command should show an error message to the user instead of teleporting them to (0,0).

**Comment by heinrich5991** [comment]
I think we should rename the command to teleport to coordinates so that you can still teleport to names with spaces without quotes.

**Comment by heinrich5991** [comment]
Fixed by #7813.
