### ISSUE TITLE
Extend "list" messages with item number field

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#7769]
It has been one day without reactions to my comment in a closed pr so I am escalating it to an issue!!

https://github.com/ddnet/ddnet/pull/7764#issuecomment-1879581904

https://github.com/ddnet/ddnet/pull/7764 added net messages for start and end of lists such as rcon commands. I would love to see an int argument for the start message that contains the number of items that will be sent.

**Comment by heinrich5991** [comment]
I added the start and end messages because I have a tool that wants to see if it received all the votes.

Do you have a use case for this, too? Do you want to implement a loading bar in some client?

**Comment by ChillerDragon** [comment]
> Do you have a use case for this, too? Do you want to implement a loading bar in some client?

Not sure. But if the message is already there might as well spice it up a bit. As long as the rcon command sending is so slow (which seems to be improved by https://github.com/ddnet/ddnet/pull/7650) I would love to see progress as a user. As a dev I probably have better stuff to do than this. But maybe some other devs that are more motivated want to do it or @sjrc6 wants to add it to his client.

Seems like a missed opportunity if this simple change does not get added for possible future use.

**Comment by ChillerDragon** [comment]
I still think this would be cool. But seems like it would be on me to implement it. Also there is no rush anymore to add it since the protocol got already released without this field. So the if statement I wanted to avoid is already needed.

Closing this now. I might shoot a pr in 5 years when I want a loading bar.

**Comment by ChillerDragon** [comment]
Oh there is a loading status in the console now. Yea that one could really use some progress status?
Loading without seeing its progress is a bit unsatisfying.

![image](https://github.com/ddnet/ddnet/assets/20344300/67d4d51d-c8c4-4629-8719-421bb06bb40f)

**Comment by heinrich5991** [comment]
Is that the DDNet client or your client? Either way, if someone wants a progress bar there, a number would be nice indeed.

**Comment by ChillerDragon** [comment]
> Is that the DDNet client or your client? Either way, if someone wants a progress bar there, a number would be nice indeed.

That is DDNet

**Comment by ChillerDragon** [comment]
Closed by https://github.com/ddnet/ddnet/pull/8351
