### ISSUE TITLE
Auth access Denied

### ISSUE THREAD

**Issue by MyNewBie** [ddnet/ddnet#777]
"bool IsAuthed" cant return "int m_Authed" to what was it before map change .
https://github.com/ddnet/ddnet/blob/master/src/game/server/gamecontext.cpp#L948

**Comment by Learath2** [comment]
Map changes don't reset or change rcon status in anyway nor have I observed any wrong behaviour. Could you be a little more specific?

**Comment by MyNewBie** [comment]
use "int" instead "bool" . its clear , https://github.com/ddnet/ddnet/blob/master/src/engine/server.h#L146 bool return to 0 and 1.

**Comment by Learath2** [comment]
Fixed by 1a9710a
