### ISSUE TITLE
Community filters

### ISSUE THREAD

**Issue by Syrinok** [ddnet/ddnet#7774]
Community filters seem a bit more annoying to use than the previous setup since you can't use your favorites as servers you trust / frequently play on anymore, it has to be used like the previous DDNet tab. ~~When servers get ddosed, they don't keep the ddnet community tag, so they just disappear from your favorites.~~ (**EDIT**(heinrich5991): moved to #7776).

Seems like a step backwards in terms of playability, the change essentially just removes the Favorites tab.

**Comment by heinrich5991** [comment]
Perhaps we could get a "move community to tab" button.

**Comment by heinrich5991** [comment]
> When servers get ddosed, they don't keep the ddnet community tag, so they just disappear from your favorites.

There should be no change here. Can you elaborate what you mean? Servers shouldn't lose the DDNet tag, even if DoSed.

**Comment by Syrinok** [comment]
> > When servers get ddosed, they don't keep the ddnet community tag, so they just disappear from your favorites.
> 
> There should be no change here. Can you elaborate what you mean? Servers shouldn't lose the DDNet tag, even if DoSed.

Noby's fng server disappeared from my favorites tab, but was still able to be connected to, I assume it's due to the DDNet tag disappearing when server information isn't visible (server name, connected players)
