### ISSUE TITLE
Changing version.h doesn't regenerate CMake

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#7775]
From [Discord](https://discord.com/channels/252358080522747904/293493549758939136/1193584718860529775):
> [4:59 PM]Learath2: Small issue I noticed while messing around with it. Changing the version in version.h doesn't cause a regeneration of from as it should
> [4:59 PM]Learath2: s/from/the cmake cache/

**Comment by Kaffeine** [comment]
Oh. I think I can fix it. We need to set [CONFIGURE_DEPENDS](https://cmake.org/cmake/help/latest/prop_dir/CMAKE_CONFIGURE_DEPENDS.html) on `version.h`.
