### ISSUE TITLE
Data Race in `str_timestamp_ex` and ThreadSanitizer discussion in general

### ISSUE THREAD

**Issue by Learath2** [ddnet/ddnet#7788]
We have uses of `localtime` in the code which is not thread-safe, `localtime_r` has been available in POSIX for a long time, `localtime_s` is available in msvcrt and `localtime_r` is available in mingw. Or we could bump up to C++20 and use `std::chrono::zoned_time`.

In more general ThreadSanitizer seems to find some actual real issues, at least I haven't encountered any false positives. It is expensive resourcewise though, so should we maybe enable it on CI if the resource cost isn't prohibitive?

**Comment by heinrich5991** [comment]
> Both the 32-bit and 64-bit versions of [gmtime](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/gmtime-gmtime32-gmtime64?view=msvc-170), [mktime](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/mktime-mktime32-mktime64?view=msvc-170), [mkgmtime](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/mkgmtime-mkgmtime32-mkgmtime64?view=msvc-170), and localtime all use a single tm structure per thread for the conversion. Each call to one of these routines destroys the result of the previous call.

[`localtime` is thread-safe on Windows](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-localtime32-localtime64?view=msvc-170), on everything else we can use `localtime_r`.
