### ISSUE TITLE
Better community icons

### ISSUE THREAD

**Issue by HiRavie** [ddnet/ddnet#7789]
I've adjusted the logos to look better at small scale.
![ddnet](https://github.com/ddnet/ddnet/assets/65019210/a35984a2-61b8-4134-bdfa-80e9c8d4c5eb)
![kog](https://github.com/ddnet/ddnet/assets/65019210/8ffa00b0-ea7b-4ac0-8a01-f5d564e0e240)

**Comment by Robyt3** [comment]
See also #7478.

**Comment by def-** [comment]
Updated
