### ISSUE TITLE
master info is expired in OnClientEnter, OnStartInfoNetMessage and OnClientConnected seems redundant

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#7793]
Does the master have to be informed this precisely? Imo which ever one is called later should be used. I think one of them is even twice a tick so its only marked twice and not sent twice. But the other one is sent twice i think. If they are all in the same tick it might be okay then its just weird but not useless bandwidth at least.

https://github.com/ddnet/ddnet/blob/80f77c500e05c2ca4ea9060b911a090180a0ee08/src/game/server/gamecontext.cpp#L2828

https://github.com/ddnet/ddnet/blob/80f77c500e05c2ca4ea9060b911a090180a0ee08/src/game/server/gamecontext.cpp#L1562

https://github.com/ddnet/ddnet/blob/80f77c500e05c2ca4ea9060b911a090180a0ee08/src/game/server/gamecontext.cpp#L1692

**Comment by heinrich5991** [comment]
`ExpireServerInfo` should be called whenever the server info changes. If it doesn't change in one of these places, it could be removed. This would likely be on you to investigate.

**Comment by ChillerDragon** [comment]
Yea it might change. But these messages are all called together within a super short time frame. Isn't expensive to do such a big json http request and should be ratelimited a bit more? Well yea but if nobody other than me wants to investigate that I am closing that issue to avoid yet another stale issue.

**Comment by heinrich5991** [comment]
> Isn't it expensive to do such a big json http request and shouldn't it be ratelimited a bit more?

It is already rate-limited to 1/s.

**Comment by ChillerDragon** [comment]
Oh I did not know that for me it looked unratelimited. Yea then this is an non issue anyways.
