### ISSUE TITLE
`NETMSG_RCON_CMD_GROUP_END` is not sent when client is logged out

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7796]
CC #7764 @heinrich5991 Is this intentional, i.e. are `NETMSG_RCON_AUTH_STATUS` / `protocol7::NETMSG_RCON_AUTH_OFF` supposed to be used to specify the end of rcon command sending already or should we also send `NETMSG_RCON_CMD_GROUP_END` when a client is logged out? Are `NETMSG_RCON_CMD_GROUP_END` without matching `NETMSG_RCON_CMD_GROUP_START` allowed/no-op or would we have to prevent that case explicitly?

**Comment by heinrich5991** [comment]
Good question. Should I add another `NETMSG_RCON_CMD_GROUP_ABORTED`? What would you prefer?

**Comment by Robyt3** [comment]
I'd be fine with using `NETMSG_RCON_AUTH_STATUS` / `protocol7::NETMSG_RCON_AUTH_OFF` for this purpose. We already deregister all temporary commands on the client-side when receiving `NETMSG_RCON_AUTH_STATUS` with `cmdlist=0` so it makes sense that this also marks the end of `NETMSG_RCON_CMD_GROUP_START` for the purpose of displaying a status message in the console while receiving commands.

**Comment by heinrich5991** [comment]
If I understand that correctly, we're happy with the status quo. Thanks!
