### ISSUE TITLE
[Assertion Error] Demo recorder alreay recording

### ISSUE THREAD

**Issue by CAESIUS-TIM** [ddnet/ddnet#7802]
![image](https://github.com/ddnet/ddnet/assets/60285058/da7b1331-1972-4247-85e0-5218ec2941a3)

**Comment by jxsl13** [comment]
that one I also had in chiller's ddnet-insta mod

**Comment by Robyt3** [comment]
Should both be fixed by #7571 already with latest nightly, assuming both were caused by using the `record` command.

**Comment by jxsl13** [comment]
I did enable my demos using the config file, so that demos should be recorder all the time.

**Comment by Robyt3** [comment]
Should be fixed in nightly by #7571 and #7837.
