### ISSUE TITLE
Get rid of spinning when waiting for HTTP requests to finish

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#7811]
See https://github.com/ddnet/ddnet/pull/7683#issue-2047522575.

**Comment by furo321** [comment]
Why should it be removed? The linked comment doesn't exactly explain it for me.

**Comment by Robyt3** [comment]
https://github.com/ddnet/ddnet/blob/217103a0ee1f6dd0f78617a64f9a284d4dc626f2/src/engine/shared/http.cpp#L407-L416
