### ISSUE TITLE
textur error message but its skin

### ISSUE THREAD

**Issue by teini94** [ddnet/ddnet#7818]
textur error message but its a skin from another Player.

as another player put on a skin called Bob today this error message appeared and was distracting
cause I didnt had that skin downloaded yet it seems.
I hope its a bug.

![screenshot_2024-01-16_19-24-33](https://github.com/ddnet/ddnet/assets/110184616/b90b04de-c1e2-4d69-a231-13273f3eb91c)

**Comment by heinrich5991** [comment]
Related to #7683 according to @Robyt3.
