### ISSUE TITLE
Current approach to add functionality for existing code

### ISSUE THREAD

**Issue by gerdoe-jr** [ddnet/ddnet#7828]
I was a little upset while working on #7820 because the rescue functionality is divided into completely different files that have actually nothing to do with rescuing

My question is: is there anything that will be less overwhelming than remaking the whole ddnet (or server part only) on ECS basis to be able to make (i.e rescue) code cleaner? Maybe, I'm doing something wrong on #7820

**Comment by heinrich5991** [comment]
I don't know how to structure the code better.

The only thing I could offer is moving the rescue stuff to its own file and only calling the functions from everywhere, instead of accessing the rescue internals from everywhere.
