### ISSUE TITLE
Toggle dynamic camera works only if dyncam is disabled

### ISSUE THREAD

**Issue by mahdiG** [ddnet/ddnet#783]
Hi. I've bound toggle dynamic camera to a key but it only works if dynamic camera (from Settings>General) is disabled. If dynamic camera is enabled the bind doesn't work.

**Comment by FallenKN** [comment]
I guess this happens, because your bind toggles cl_dyncam but this is not related to the dynamic camera settings of menu_settings.cpp for some reason
