### ISSUE TITLE
Move 'Show name plates' from HUD to 'Name Plate'

### ISSUE THREAD

**Issue by gerdoe-jr** [ddnet/ddnet#7830]
> furo — Today at 8:14 PM
or use cl_nameplates 0
[image.png](https://media.discordapp.net/attachments/745926398140612678/1197952207388168313/image.png?ex=65bd22ef&is=65aaadef&hm=94c3489027d8800dde6f961b66cd36e60eeb25befd8e00007c49ebd94348eeb7&=&format=webp&quality=lossless&width=1708&height=683)
No clue why it's under "HUD" and not "Name Plate"

**Comment by heinrich5991** [comment]
![image](https://github.com/ddnet/ddnet/assets/366230/08c1c441-4e51-4504-ac19-e1d81eafe9a4)
