### ISSUE TITLE
More inconsistencies in appearance settings

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7833]
More inconsistencies like #7830.

The "Show chat" checkbox should be moved to the Chat tab.

The "Show kill messages" checkbox should be removed, because it already exists on the Info Messages tab.

![image](https://github.com/ddnet/ddnet/assets/23437060/3706ac17-4d33-41c2-9319-cffef3f9a8c3)

**Comment by BlaiZephyr** [comment]
apart from adding the show chat to the chat tab, i'd personally reformat it;

from this:
![image](https://github.com/ddnet/ddnet/assets/101197249/35016d06-58e0-4204-bb1d-4553c5cfa029)

to this:
![image](https://github.com/ddnet/ddnet/assets/101197249/aa927f0b-c322-4617-baea-9db8fed7b221)

having it on the right side feels weird to me personally.

**Comment by arianaargyrakis** [comment]
I am a new contributor. I can try to fix it if no one has done it.

**Comment by BlaiZephyr** [comment]
@arianaargyrakis i'd say feel free as long as the issue is still open, the change is accepted and no pull request is linked to it yet :rocket: !
