### ISSUE TITLE
Feature request: Option to register servers by domain and SSL (instead of IP)

### ISSUE THREAD

**Issue by mwinkens** [ddnet/ddnet#7845]
Do I really have to write why I want that feature?
- This would allow servers to have more dynamic IP addresses without favorites being lost
- Fricking SSL support allowing servers to **verify themselves**, this prevents phishing attack by servers pretending to be another one.
- ~~Multiple servers under one domain, allowing interesting new architectures. This could make it possible for a server to send a player to a different one (with a smart loadbalancer)~~ (unrelated)

related: #2851

**Comment by Avolicious** [comment]
Hey,
 
>     * Fricking SSL support allowing servers to **verify themselves**, this prevents phishing attack by servers pretending to be another one.

HTTPS master is already implemented & uses TLS (SSL is not used anymore).

>     * Multiple servers under one domain, allowing interesting new architectures. This could make it possible for a server to send a player to a different one (with a smart loadbalancer)

How do you sync gamestates across multiple gameservers? You can take a look for #6757 

Cheers,

**Comment by ChillerDragon** [comment]
The first point is exactly the issue you mentioned right? #2851

I don't understand how this helps with phishing. You mean a user can remember the domain better than the ip? So the user can look at the connection field and see the domain. That does already work. You can point your domain to your ip. But I think the master server does not let you register it as domain. But yea I would say most users go based on server name anyways and that could still be faked.

About the load balancer. You don't need http/https/Domains to load balance. You just need a reverse proxy. That would be the abandoned #4791

**Comment by heinrich5991** [comment]
> * Fricking SSL support allowing servers to **verify themselves**, this prevents phishing attack by servers pretending to be another one.

This would be solved by something like #5411 (#6961) as well. Although I don't think "phishing" would be prevented by TLS certificates.

> * This would allow servers to have more dynamic IP addresses without favorites being lost

I guess something like that would also be implementable using #6961, servers have their public key and you can favorite servers using that. This is also, as you mentioned, #2851.

> * Multiple servers under one domain, allowing interesting new architectures. This could make it possible for a server to send a player to a different one (with a smart loadbalancer)

Seems unrelated.

**Comment by mwinkens** [comment]
Thank you all for cross linking this references! I wasn't aware of the linked issues.

@Avolicious 
> HTTPS master is already implemented & uses TLS (SSL is not used anymore).
I don't get your point here, can I register my own game-server with https? If yes, please link the documentation. Or do you say, that the masterservers themself use TLS/SSL, because I am aware of this.

>How do you sync gamestates across multiple gameservers?
I already implemented a multiworld server. You can _just_ expand on it and let servers communicate with each others redirecting the client where it's needed. As far as I remember world switching worked with triggering a "mapdownload".

---

@heinrich5991 thank you, I wasn't aware of the issues you linked and I am very surprised, that GitHub didn't already tell me, that issues like this exist. I really searched before, maybe I missed the keywords

---

@ChillerDragon 
So let's make an example, I have my own server, with a secured domain done with let's encrypt and a dyndns service.
Now I want to register my server as `myserver.dnsservice.com` and if a client joins my server and adds it to the favourites, it saves the public key and the domain. If the user then tries to connect to the server again, the domain and ssl check can be done in order to verify the server.

Also multiple checks could be done at the masterserver. You can't register a server under your domain, if the ip or ssl certificate of the registering server doesn't match with the domain. Do you understand how this could prevent phishing?  You can't add a server with the same domain in order to phish for rcon or userpasswords (some mods have accounts). Currently you can just register a server under the same name and there is no way to know if it's the same server. Especially if the ip changes regularly. This might also require adding the domain to the server name or in a column.

---

My third point was just an idea, the other two are way more important to me. Dns shuffeling just came into my mind. I am aware that this is already possible, and I shouldn't have added this above.

**Comment by ChillerDragon** [comment]
Yea being able to submit a domain instead of an ip to the master server would be cool. I would move that to another issue. @heinrich5991 what do you think? So on register the server can send a hostname. The master server verifies the hostname points to the same ip and then registers it as that instead of the ip. Or in addition to the ip. And then when a ddnet client user clicks in the server browser on the server it shows the domain instead of the ip in the input field.

Would this be problematic somehow? If the dns entry changes? If the ddnet client users dns is broken (but then the master it self doesnt work either)? It allows "spoofing" hosts and forcing the master to do a request to any domain. Is that bad?

**Comment by heinrich5991** [comment]
> I don't get your point here, can I register my own game-server with https? If yes, please link the documentation. Or do you say, that the masterservers themself use TLS/SSL, because I am aware of this.

DDNet servers today use a HTTPS POST request to https://master1.ddnet.org/ddnet/15/register to register themselves (protected using TLS since it's HTTP**S**).

> You can _just_ expand on it and let servers communicate with each others redirecting the client where it's needed.

That's possible today using the redirect message.

> Also multiple checks could be done at the masterserver. You can't register a server under your domain, if the ip or ssl certificate of the registering server doesn't match with the domain. Do you understand how this could prevent phishing? You can't add a server with the same domain in order to phish for rcon or userpasswords (some mods have accounts).

I don't think this prevents phishing in any useful sense of the word "prevent". It'd require people to actively check the domain of the server they're logging in to, which I don't think people do, even for websites.

**Comment by heinrich5991** [comment]
Since I don't think this helps with phishing, the only remaining concern is favoriting domains, which is covered by #2851.
