### ISSUE TITLE
Blockworlds application to newest community feature

### ISSUE THREAD

**Issue by Rei-Tw** [ddnet/ddnet#7846]
Hi everyone,

I've been told by Avolicious that I'd need to apply to be part of the newest community feature (and suggested to open an issue).
I think the community feature is part of this issue #5654.

What do we have to provide to be considered as trusted and part of that newest feature ?

PS: I forgot to mention that previously we were trusted on KoG tab.

**Comment by fokkonaut** [comment]
+1

**Comment by heinrich5991** [comment]
This will need #7699 to resolve, other than that, I think nothing stands in a way to become registered as a community. You'll need a community icon in the style of the existing ones.

**Comment by furo321** [comment]
> The community icons should be 128x64 pixel RGBA PNG images. They should be compatible with pnglite due to the warning popup being shown otherwise. Please first test the icon locally to ensure that it looks good at the resolution displayed in the client and that it fits together with the other images.

https://github.com/ddnet/ddnet/issues/7448#issuecomment-1808654835

**Comment by Robyt3** [comment]
Isn't this issue a duplicate of #7448? Both are about Blockworlds.

**Comment by Rei-Tw** [comment]
> Isn't this issue a duplicate of #7448? Both are about Blockworlds.

Looks like yes, Didn't see it was already asked in the past. I can close that one & continue on the other issue.
