### ISSUE TITLE
Filter bug, when selecting `None`

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#7847]
If you had countries selected, then press `None` => then you can't select countries anymore, but the countries you selected previously are still part of the filter process.

That easily leads to 0 servers, without intuitively understanding why it happens

**Comment by Jupeyy** [comment]
Or it seems like it generally filters all servers then, independent of the country selected

**Comment by Scrumplex** [comment]
This also happens when you have anything deselected in game type filter
