### ISSUE TITLE
Windowed borderless does not work correctly when selecting other screen

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7848]
If you use windowed borderless you cannot use another screen except screen 0. If you do, a second window which does not update is rendered on the choosen screen and the game is rendered on screen 0 normally.

Happens with OpenGL and with Vulkan.

Happens with Windows 10. Can anyone confirm it also happens on Linux/macOS?

Happens with SDL 2.26.5 and 2.28.5.

**Comment by Robyt3** [comment]
Seems like this happens when the window size is larger than the resolution of the selected screen. When I select the correct size of my secondary screen windowed fullscreen also works. We should update the window size when changing the screen.

**Comment by BlaiZephyr** [comment]
it works fine between my 3 monitors on both Vulkan and OpenGL (2x 1920x1080 60hz, 1x 1680x1050 60hz), and it auto updates the resolution when swapping between 1920x1080 -> 1680x1050 - the only notable thing is the time it takes to swap (between 5 and 15 seconds, depending on if it has to adjust the resolution or not)

**Comment by Robyt3** [comment]
Closed by #7937.
