### ISSUE TITLE
Editor - Autorule doesn't work anymore

### ISSUE THREAD

**Issue by pmax22** [ddnet/ddnet#7849]
Autorule doesn't work. I tried to change it multiple times but it says "none" (the rule file of the same name as the image contains rules).
I tried the same thing on 17.1 and autorule works there.

**Comment by archimede67** [comment]
Can you provide the image and the rule files? I just tested with one of my images and it works just fine

**Comment by Robyt3** [comment]
The `.rules` files have been moved to the subfolder `data/editor/automap` to separate them from the other editor files.
