### ISSUE TITLE
Updater broken?

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#7867]
Someone with version 18.0 showed updater logs that contained downloads for "DDNet-unsupported-unsupported". Is this a bug in the updater?

If the platform is unsupported-unsupported, the update button should probably not be shown, too.

**Comment by Learath2** [comment]
This happened to me as well. I think it was an issue in the build 18.0, unsupported-unsupported should have never had an autoupdater to begin with

**Comment by Learath2** [comment]
Nevermind, it's an issue in current master and unrelated to building. It seems to have broken with the curl multi patch.

**Comment by Jupeyy** [comment]
fixed in #7868
