### ISSUE TITLE
Add ipv6 support to ``bindaddr``. And fix ipv4 support when ``sv_ipv4only 0``

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#7870]
**teeworlds** version tested (working): [a1911c](https://github.com/teeworlds/teeworlds/tree/a1911c8f7d8458fb4076ef8e7651e8ef5e91ab3e) (current master jan 28 2024)
**ddnet** version tested (not working): dcdc66d1dfd3fa086473ea779aec7c28f5d44f5e (current master jan 28 2024)

---

my bisecting journey:

**ddnet** version oldest known not working: 1abe73c2e ``git reset --hard HEAD~1543`` :x:
**ddnet** version latest known working: 9e6ee2154 ``git reset --hard HEAD~1544`` :heavy_check_mark: 

I guess I blame this :shrug: @heinrich5991 @def-  https://github.com/ddnet/ddnet/commit/1abe73c2ec8b8323102f584229a810d4e8f8c909 https://github.com/ddnet/ddnet/pull/5272

---

It works like this in teeworlds and in ddnet for me on my debian laptop.

:heavy_check_mark:  ```./teeworlds_srv "bindaddr 0.0.0.0;sv_port 8888"```
:heavy_check_mark:  ```./DDNet-Server "bindaddr 0.0.0.0;sv_port 8888"```

So far so good. But here is where it gets weird:

:heavy_check_mark: ```./teeworlds_srv "bindaddr 127.0.0.1;sv_port 8888"```
:x: ```./DDNet-Server "bindaddr 127.0.0.1;sv_port 8888"```

<details>

```
2024-01-28 11:36:48 I host_lookup: host='127.0.0.1' port=0 3
2024-01-28 11:36:48 I net: failed to bind socket with domain 10 and type 2 (99 'Cannot assign requested address')
2024-01-28 11:36:48 I server: couldn't open socket. port 8888 might already be in use
$ echo $?
255

```

</details>

Okay 127.0.0.1 is a weird ip whatever. Lets try one of my ips in ``ip a``. I tested this on two vps with public ipv4s and the local network ip of my laptop in a wifi. All systems running debian 12. All systems same result (tw works, ddnet does not) here one example:

```
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 5a:f9:e3:45:3a:a5 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    altname ens3
    inet 45.142.178.158/22 brd 45.142.179.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2a03:4000:4a:ed4:58f9:e3ff:fe45:3aa5/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::58f9:e3ff:fe45:3aa5/64 scope link 
       valid_lft forever preferred_lft forever
45: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none 
    inet 10.8.0.1/24 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::71bc:d351:eadf:35db/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
```

:heavy_check_mark: ```./teeworlds_srv "bindaddr 45.142.178.158;sv_port 8888"```
:x: ```./DDNet-Server "bindaddr 45.142.178.158;sv_port 8888"```

Okay to be fair the tw server shows a warning ``[2024-01-28 04:52:58][net]: failed to bind socket with domain 10 and type 2 (99 'Cannot assign requested address')``
I got so used to this warning showing up because it never breaks anything. Maybe it does not work in teeworlds and ddnet has just the better error handling. So this time I looked closer. The tw server seems to have bound the ip correctly:

```
$ netstat -tulpn | grep 8888
udp        0      0 45.142.178.158:8888     0.0.0.0:*                           2370574/./teeworlds
```

Also connecting to the server worked fine ``./teeworlds "connect 45.142.178.158:8888"``

**Comment by ChillerDragon** [comment]
Okay this works :partying_face: 

:heavy_check_mark:  ```./DDNet-Server "bindaddr 127.0.0.1;sv_port 8888;sv_ipv4only 1"```

I tried printing the NETADDR that failed to bind and got ``unknown type 11``. And 11 is ``NETTYPE_ALL`` so thats what made me try the other branch here:

https://github.com/ddnet/ddnet/blob/d60852a020aed61b72d8f9e20dcd94501e53e6ee/src/engine/server/server.cpp#L2775

I assume there a bunch of places in the code that only allow ``NETTYPE_IPV4`` or ``NETTYPE_IPV6`` and not ``NETTYPE_ALL``. But then if I do not use ``bindaddr 127.0.0.1`` it still uses ``NETTYPE_ALL`` and it works. So that can not be the issue.

Either way its nice that I can make it work using ``sv_ipv4only 1`` but I have yet to discover how one then binds a ipv6 address. Also it seems like a bug to me that this used to work without ``sv_ipv4only`` and now it does not work anymore.

**Comment by heinrich5991** [comment]
I think it always tries to bind an IPv4 and an IPv6 socket. and then it fails because binding the IPv6 socket to that address doesn't work.

**Comment by ChillerDragon** [comment]
Fixed by https://github.com/ddnet/ddnet/pull/8709
