### ISSUE TITLE
Bugs in the editor

### ISSUE THREAD

**Issue by Zavo1** [ddnet/ddnet#7893]
After updates, in the editor there is no information about parameters of such blocks as "speedup" and "tele". Maybe some others.
<img width="288" alt="image" src="https://github.com/ddnet/ddnet/assets/131773563/505757ad-ee93-456c-acd1-35877ebd1fd6">

**Comment by archimede67** [comment]
You probably set `cl_text_entities` to `0`. Check it in F1.

**Comment by Robyt3** [comment]
Doesn't make sense to me to apply this setting to the editor, seems like an oversight because it probably reuses the same map rendering code.

**Comment by Robyt3** [comment]
Maybe it should be a separate config variable for the editor then so it's less confusing that the client config variable also has an effect on the editor.

**Comment by heinrich5991** [comment]
@Zavo1 Can you confirm this is the problem btw?

**Comment by Zavo1** [comment]
I deleted the DDNet folder from AppData\Roaming\. After restarting, the problem disappeared.

**Comment by heinrich5991** [comment]
Sounds like it was the problem.

**Comment by heinrich5991** [comment]
> Maybe it should be a separate config variable for the editor then so it's less confusing that the client config variable also has an effect on the editor.

@Robyt3 Do we want to have this? I'd be fine with the status quo.

**Comment by Robyt3** [comment]
Fine for me. I'd also prefer not adding another option and making the map rendering code more convoluted. Maybe it should be added to an FAQ in the Wiki if this problem is reported more often.
