### ISSUE TITLE
Changelog for mod-makers to keep up with the high development pace

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#7895]
DDNet is growing. Many changes, many things that can break server-side mods. Either client changes (e.g. team color update) or protocol changes (e.g. mouse target being sent in zoomed state) are things which can break mods.
Initially, I was tracking DDNet's development actively to keep up with those changes, but recently it's gotten too much plus I've been too busy lately aswell, so it's really annoying to update after a few versions just to see some things have been broken and you have to search for commits or reasons why things broke.

I suggest DDNet maintaining a Mod changelog, so that mod-makers can easily fix and adjust things.

**Comment by heinrich5991** [comment]
Maybe we could tag the relevant PRs that something on the network (in the wider sense) changed.

**Comment by jxsl13** [comment]
#7777

**Comment by ChillerDragon** [comment]
Yea I also would love to see that. But I am having a hard time properly defining how it should look like. I guess it also depends on who the change log is for. I see 3 slightly different groups here:
- Users of the software. Players and server admins. That want to know new features and breaking changes such as config variables being renamed, database format being changed and similar.
- People implementing a ddnet compatible system but are no forks. Such as fokkonaut who is running a teeworlds fork that tries to keep up with the essential new ddnet extensions. Or people developing network libraries or other implementations from scratch or hard forks. These mostly do not care about little code refactors. And more on a higher level list of features that affect the client/server connection.
- then there is the #7777 people. Soft forks that are merging the code. Those care about all changes that break forks. Those would like a short notice on breaking abi's such as common methods being renamed or changed. Such as "this is how the new vs old http request is done". Or "run this sed/script to apply the refactor/rename to your parts of the code base". Wireshark does that it's so cool.

**Comment by ChillerDragon** [comment]
> Maybe we could tag the relevant PRs that something on the network (in the wider sense) changed.

Imo the fitting place for that changelog would be a GitHub release. Having a list of links to protocol changing prs would already be neat.

**Comment by ChillerDragon** [comment]
Another thing we could start doing is those ping groups the big projects are using. So users can opt in to be notified if certain things are touched. So on network related changes we could just ping @network-subscribers in the pr

**Comment by BlaiZephyr** [comment]
> Another thing we could start doing is those ping groups the big projects are using. So users can opt in to be notified if certain things are touched. So on network related changes we could just ping @network-subscribers in the pr

im 90% sure github action's can do that pretty consistently, but someone would need to set it up for related files, maybe make it possible for people to subscribe to certain github tags on issue's aswell? -> client, server, engine

**Comment by jxsl13** [comment]
with conventional commits it would be possible to automatically generate changelogs with different sections like breaking changes.

**Comment by heinrich5991** [comment]
> Additionally: https://www.conventionalcommits.org/en/v1.0.0/

I think I don't want to do machine-readable commit messages. I don't want to burden contributors with more stuff.

**Comment by ChillerDragon** [comment]
@edg-l yo mr compiler dev do you know how these notifications work? Would that make sense for us?

https://github.com/llvm/llvm-project/pull/80590#issuecomment-1925613334

This is a thing too. https://github.com/marketplace/actions/issue-label-notifier
But that would require adding recipients to the git repo which seems weird. So you have to pr your self into the news letter.

Or we finally move away from microsofts closed source platform. GitLab has this feature https://docs.gitlab.com/ee/user/project/labels.html#subscribing-to-labels

Related issues:
- https://github.com/isaacs/github/issues/581
- https://github.com/bevyengine/bevy/issues/2228

**Comment by ChillerDragon** [comment]
Okay I created a ddnet-meta github repository. Where a bot will post a comment into an issue every time a new https://github.com/ddnet/ddnet/labels/PR%3A%20Mod-relevant%20change label pops up in ddnet.

So you can go [here](https://github.com/ChillerDragon/ddnet-meta/issues/1) and subscribe only to that issue. Not the whole repo. And you will get a notification from github as soon as someone adds the label to a pr.

![image](https://github.com/ddnet/ddnet/assets/20344300/a1f9d6cd-6b5c-4584-b1f4-f6fac9dc5ce4)

The code of the bot is in the same repo. Contributions welcome. It is currently running on my vps and checking every 5 minutes. Feel free to fork it and let it send into your telegram group chat instead.

**Comment by ChillerDragon** [comment]
Another somewhat related thing is deprecation. I would really appreciate that if a change is rolled out that affects downstreams/mod makers. There is at least one ddnet release with the old feature still working but showing deprecation warnings. Either via macros and warnings during compilation or via logging.

**Comment by heinrich5991** [comment]
I don't think doing deprecations for mods is worthwhile.

**Comment by ChillerDragon** [comment]
Okay then is there anything left to do or can we mark it as completed @fokkonaut

**Comment by heinrich5991** [comment]
I'd call it completed.

**Comment by ChillerDragon** [comment]
Yo @fokkonaut out of curiosity did you end up enabling notifications for https://github.com/ChillerDragon/ddnet-meta/issues/1?
Because I built that and keep labeling prs actively mostly for you.
