### ISSUE TITLE
Editor - HD-off only Layers

### ISSUE THREAD

**Issue by Jan38** [ddnet/ddnet#7900]
Hello dear DDNet development team,

I would like to suggest adding the option to make a layer only appear when high details is turned off. 

For some of my maps, I want a nice/beautiful design with tiles that have round corners. But when people want to see exactly where the edges of the tile are, they quickly switch to entities. To prevent that, I often map my HD-off version of the map with square tiles. Since the round tiles don't cover the square tiles, I have to hide the square tiles behind a second background. This leads to the square tiles being behind the game layer, which looks unpleasant. 

Here is an example what I mean:
![Screenshot 2024-02-02 202828](https://github.com/ddnet/ddnet/assets/24591248/c8a72bd0-cefb-4250-8bf3-5af3e9731a43)

It's not a big problem, but I thought maybe it's also not a big fix.

However, this is just a suggestion. Even if it never gets implemented, I really appreciate the amazing work and development you guys have done for the game and the community. You guys are awesome!

**Comment by heinrich5991** [comment]
I think the current situation is fine, I'd prefer not to add it. HD off and on aren't supposed to be completely different versions of the map.

I'd generally suggest to map clearly so you can see where the tiles are, not aim for a beautiful map first, but a playable one.

**Comment by archimede67** [comment]
I agree with @heinrich5991, I don't think it makes much sense to have HD off only layers.
