### ISSUE TITLE
Editor - Collapse groups when loading map

### ISSUE THREAD

**Issue by Jan38** [ddnet/ddnet#7902]
Hello dear DDNet development team,

I would like to suggest that the groups are collapsed/closed instead of opened when loading a (new) map. Or maybe they remember whether they were opened or closed when I saved the map. That would help me keep things organized, as I mostly use one group at a time while the rest are closed. Also a button to open/close all of them at once would be very helpful. 

However, these are just suggestions. Even if none of them are ever implemented, I really appreciate the amazing work and development you guys have done for the game and the community. You guys are awesome!

**Comment by heinrich5991** [comment]
> Also a button to open/close all of them at once would be very helpful.

I could see having this, I have a slight preference to not have the rest.

**Comment by archimede67** [comment]
> Or maybe they remember whether they were opened or closed when I saved the map.

I can see this being useful too
