### ISSUE TITLE
Editor - Crash with quads

### ISSUE THREAD

**Issue by pmax22** [ddnet/ddnet#7904]
The game crashes if you click on the center of a quad (green dot) and press the **up** or **down** directional key.
(left and right are fine).

**Comment by Robyt3** [comment]
Can confirm, I get a crash due to nullptr access here:

https://github.com/ddnet/ddnet/blob/863ae5f9b6b74b794925a01a6fddeb136f5d0030/src/game/editor/popups.cpp#L831

when I switch the current layer with up/down key while the quad pivot popup is open.

**Comment by Robyt3** [comment]
Also crashes with version 17.3 already.
