### ISSUE TITLE
Editor - Envelope menu issue

### ISSUE THREAD

**Issue by pmax22** [ddnet/ddnet#7905]
You can't properly click and check the boxes (such as sync.) or reach the text box when changing the size of the envelope menu.
You can see my cursor over the sync. option. I can't click on it.
![image](https://github.com/ddnet/ddnet/assets/14247576/707c1b43-43ce-4708-a4a6-05104231a612)
Same problem with the name text box.
![image](https://github.com/ddnet/ddnet/assets/14247576/44110aab-8422-4b96-9034-e91e7a3f8d0e)

**Comment by archimede67** [comment]
I don't think we should change the sync checkbox. I do think it is good as it is right now, and many mappers are probably used to it being a checkbox and not a toggle button.

**Comment by Robyt3** [comment]
It's currently the only checkbox in the editor and it's not working correctly, i.e. like checkboxes in the menus. I think it's better if we use a toggle button like for all other editor functions, so the UI is consistent.

**Comment by ewancg** [comment]
Latest upstream uses a toggle button, maybe this issue should be closed

**Comment by Robyt3** [comment]
Fixed by #7816 and #7910.
