### ISSUE TITLE
Bug: Hookline no longer properly simulates the hook while stationary

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#7911]
Reported by keskinkarga and YK

https://github.com/ddnet/ddnet/assets/60477660/812cea95-d507-4cc7-a0ae-38a19fe3bb92

Windows 11, Steam version, Nightly Build

**Comment by furo321** [comment]
Should be fixed by #7863

**Comment by murpii** [comment]
It does, thanks!

**Comment by Robyt3** [comment]
Fixed by #7863.
