### ISSUE TITLE
[BUG] fs_listdir could block main thread

### ISSUE THREAD

**Issue by Bamcane** [ddnet/ddnet#7921]
Create a link directory in the maps directory, it linked its parent directory
DDNet will try to list it until finishing, but it will never finish

**Comment by Robyt3** [comment]
> Create a link directory in the maps directory, it linked its parent directory

Do you have a specific reason for doing so or did you do this only for testing?

This seems like too much effort to fix. We'd have to collect all the folders which were already considered in the directory listing functions, which is possible but requires changing every invocation of the functions. However, we need to determine if two paths are identical, seems much harder to do correctly on all systems.

**Comment by Bamcane** [comment]
> > Create a link directory in the maps directory, it linked its parent directory
> 
> Do you have a specific reason for doing so or did you do this only for testing?
> 
> This seems like too much effort to fix. We'd have to collect all the folders which were already considered in the directory listing functions, which is possible but requires changing every invocation of the functions. However, we need to determine if two paths are identical, which seems much harder to do correctly on all systems.

I think we should ignore symlinks, like 0.7

**Comment by Robyt3** [comment]
Symlinks are likely already used by some, we shouldn't ignore them again.

Seems easier to ignore this bug because I don't see any reason to have symlink directory loops inside DDNet folders.

**Comment by heinrich5991** [comment]
> I think we should ignore symlinks

That seems like less utility than following symlinks but locking up when the users does a symlink loop.
