### ISSUE TITLE
Move auto mapper rules to the upstream json format to stay compatible

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#7930]
It would still not be fully compatible because ddnet added new automapper keywords teeworlds clients would not understand.
But still imo there should only be one format for auto mappers. And teeworlds is not changing. Also json is kinda industry standard makes it easier to build tooling around it with all the parsers that already exist for it. Also this would allow the ddnet client to run all the automapper rules that were developed for teeworlds (for example [this 4k lines master piece](https://github.com/ChillerDragon/teeworlds/blob/ac00727ba5a2581a25d89d11e2b8b29869944e97/datasrc/editor/automap/jungle_deathtiles.json) lmao).

teeworlds:

https://github.com/teeworlds/teeworlds/blob/a1911c8f7d8458fb4076ef8e7651e8ef5e91ab3e/datasrc/editor/automap/grass_main.json

ddnet:

https://github.com/ddnet/ddnet/blob/8214e26132201ece4e5321c65a58e0ac8732ee4a/data/editor/automap/grass_main.rules

**Comment by heinrich5991** [comment]
> But still imo there should only be one format for auto mappers. And teeworlds is not changing.

That's not a reason for which we will change.

**Comment by ChillerDragon** [comment]
> That's not a reason for which we will change.

What about json being the better format?

**Comment by heinrich5991** [comment]
> What about json being the better format?

You can give arguments for that. I'm not sure if we want to invalidate all existing automapper rules though.

> Im not saying ddnet should change backwards. I am saying it should move forward like the upstream. Could you elaborate on the problems you see that made you close the issue @heinrich5991

We don't care about being aligned with Teeworlds at the moment.

**Comment by ChillerDragon** [comment]
The script could also be written to convert ddnet to json. Maybe you don't care about the alignment. But the users might care.

What is the disadvantage of json that is so obvious that you closed the issue without explaining it?

**Comment by heinrich5991** [comment]
> What is the disadvantage of json that is so obvious that you closed the issue without explaining it?

Someone proposing a change of file formats should list the advantages. Changing a file format isn't something that should be easily done, especially since it might invalidate older community contributions.

> With json we would have linters. Editor support and (de)serialisation libraries.

Yea, editor support sounds nice. I'm not sure if JSON is easier to write by hand though, seems less like a config file format and more like a machine-readable interchange format.

**Comment by ChillerDragon** [comment]
It feels to me that you closed this because our ideology does not align. Staying compatible with teeworlds is something convenient for mappers. You might not agree with that argument but you should still consider the proposed change it self and pick your own arguments for and against it. I have the impression that you closed the issue without explaining it because it's "yet another chiller compatibility thing". And it feels like you did so solely because of my proposed arguments to add the change and not because of json it self.

**Comment by heinrich5991** [comment]
> Staying compatible with teeworlds is something convenient for mappers.

We can also achieve that by someone writing a conversion script from the Teeworlds format to the DDNet format.

**Comment by heinrich5991** [comment]
> It feels to me that you closed this because our ideology does not align.

That sounds like a pretty good reason to close an issue. DDNet does not aim to be compatible with Teeworlds, therefore the change of this issue has a lot less reasoning behind it.

**Comment by ChillerDragon** [comment]
> Someone proposing a change of file formats should list the advantages. Changing a file format isn't something that should be easily done, especially since it might invalidate older community contributions.

That is what I wanted to hear. Thanks. Yes this change is tied to implementation effort for which I probably am responsible my self. Old community contributions should not be invalidated. The new format should come with at least a port script or better a client built in converter even if just for a time.

> I'm not sure if JSON is easier to write by hand though, seems less like a config file format and more like a machine-readable interchange format.

Writing 4K lines in it was okay. But I have no direct comparison. I did a lot of copy paste and then adjusting it. The named x and y vs positional x and y is for sure more straight forward for people who are getting started writing it.

Also yaml to json converters are everywhere. If one wants to write it in yaml and then export it as json that's easily possible.

**Comment by ChillerDragon** [comment]
> We can also achieve that by someone writing a conversion script from the Teeworlds format to the DDNet format.

It's less annoying to do it once when ddnet changes the format than to do it every time when going from ddnet to teeworlds and back. It reduces the ddnet is a drop in replacement for teeworlds effect.

**Comment by ChillerDragon** [comment]
> > It feels to me that you closed this because our ideology does not align.
> 
> 
> 
> That sounds like a pretty good reason to close an issue. DDNet does not aim to be compatible with Teeworlds, therefore the change of this issue has a lot less reasoning behind it.

Shouldn't it be about the "what" not the "why"?

**Comment by ChillerDragon** [comment]
Apple released pkl which has nice editor support and compiles to json. https://pkl-lang.org/
Should be straight forward to then add nice auto completion and validation for writing auto mappers.

**Comment by heinrich5991** [comment]
Sorry, this is still not convincing me. If you don't find another maintainer that wants this, I'm closing it.

**Comment by ChillerDragon** [comment]
@heinrich5991 json is a "well-understood" format :stuck_out_tongue_winking_eye: 

https://github.com/ddnet/ddnet/pull/8283#issuecomment-2241718263
