### ISSUE TITLE
Bricked graphics in in-map menu caused by specific commit

### ISSUE THREAD

**Issue by Socialdarwinist** [ddnet/ddnet#794]
59b33b95e425955b2af3e81fcf7de650f29b706a has bricked the display of the class menu in InfClass, I have found this out for certain by going back and forward in the commit history and recompiling.

![bricked class menu](https://user-images.githubusercontent.com/20446122/28210997-96bdd4cc-689a-11e7-80ef-afdf5e45b11c.png)

@def-

**Comment by def-** [comment]
So where do you get your  images from? Their path should not contain ".."

**Comment by Socialdarwinist** [comment]
I just join any InfClass server, the downloaded maps of which contains a class menu.

**Comment by Socialdarwinist** [comment]
I do not see any paths with “..”. And if you forbid certain paths, this is very lame. Inodes can have any name not containing NUL and slashes.

**Comment by Socialdarwinist** [comment]
I guess you mean relative paths in the storage.cfg. I do not know why those should be forbidden, but no, the bug happens with a completely default setup.

**Comment by Stitch626** [comment]
The InfClass code uses "../skins/<skinname>" .

**Comment by def-** [comment]
I don't know if it's a good idea to let a map open random pngs across your system.

**Comment by Stitch626** [comment]
I don't think its a good idea. You could allow files in the base folder of the executable. But we have still the ability to embedd graphics :)

**Comment by def-** [comment]
Embedded graphics would be my favorite solution for this. Alternatively calculate the full path, check if it starts with the base path, and then still allow it. then something like "$DATADIR/mapres/../skins/" will work again but you still can't escape $DATADIR.

**Comment by Stitch626** [comment]
Sounds like a solution.

**Comment by Socialdarwinist** [comment]
Yes. At least those graphics in the data folder are not random at all.

**Comment by def-** [comment]
Well, some people change those and then the map looks different for them.

**Comment by Socialdarwinist** [comment]
In the case of InfClass, I do not fear changes of the graphics. First of all, nobody will replace the current measurements of the tee skins, and second it cannot be worse than it now looks.

**Comment by heinrich5991** [comment]
Generally, it is a good idea to not let file paths contain `/` or `\` -- this stops the remote server from letting the client load arbitrary files. The same protection exists for map names.

How much of an impact would adding the images into the map have?

**Comment by Socialdarwinist** [comment]
It would require more than 100 kB extra for each map (think about users in bad internet countries), extensive changes in the InfClass repository, and redownloading of all maps of InfClass users now. I think I am not wrong to say that it is easier to have the path filter modified to an equitable extent.

**Comment by eeeee** [comment]
100 kB doesn't sound like a big deal when if have http map download enabled. Do you need help with enabling that on your server?

**Comment by def-** [comment]
HTTP map download right now only works with DDNet client and only downloads from http://maps.ddnet.tw/ . Would be nice to extend it so that it can be used with any HTTP server and the gameserver can determine the URI.

**Comment by Socialdarwinist** [comment]
Unlike what appears of me by my using git and compiling, I can’t even program a line, @eeeee, and other people are also unlikely to do anything programming-wise in the repository – it would be sad if I and @necropotame have just freed our time from Teeworlds and then already the clients cease to support the elaborate server without extensive changes in it.
And it sounds appalling that we have to deliver different maps depending on the client used. I have no clear idea how this should be accomplished. More, the idea of downloading the map via HTTP does not seem applicable because it is just not the case that we make a map and end. [The maps used by the server](https://github.com/necropotame/teeworlds-infclass/tree/master/data/maps) of course do not contain the classes beforehand, but these get added by a generator depending on the current implementation of classes. If new classes are added, all maps have to be generated and spread anew. I would also question how the changing visibility of elements in the class menu dependent of configuration and player choice works.
Hell, add it to InfClass if you want, it would give free InfClass a competitive advantage over non-free servers because their maps would not land on the map database.
Of course the best thing would be if there was a protocol whereby arbitrary graphics could be loaded and saved and savely used in addition to everything, the original idea of TeeUniverse. But this has always been only planned for far future and is now completely out of sight, as @necropotame has been grossed out and jumped of the sinking ship. You could maybe draw the classes with thousands of quads. Or add a security dialogue laying down the accessed files to be answered by players before access to upper-path files is allowed, with a “do not ask again for this server” option.
So add something, but do not shuffle off onto me.

**Comment by Learath2** [comment]
We could do a `str_comp_num` on abspath and basepath but that means we need to make some changes on the infrastructure we use on the official servers. Give us a minute, let us think this through.

Why did @necropotame jump ship anyways?

**Comment by necropotame** [comment]
Hi here :) 

Just to say that IMO, any images in ./data should be accessible because they are part of the game itself. So allowing one ".." seems reasonable. And in general, DDNet client try to preserve compatibility over version and in this case, it's broken. But you to you guys :) I've made this use if external images like a hack to free some byte from my maps.

Concerning TeeWorlds in general, I'm now working on my own game project (no more tile \o/), so, yes, I will not in a near future work on TW & DDNet.

**Comment by def-** [comment]
We could use realpath, but unfortunately that follows symlinks, which would be too strict in my opinion.

I suggest that what InfClass is doing is a bug anyway, since a map should only be able to access mapres, not skins.

**Comment by Socialdarwinist** [comment]
“A map should only be able to access mapres”? Which rationale says so? Here we have the evidence why maps should access skins as well. If it had not been possible, it should have been built in.
Again, it is not conceivable why you should be able to allow access to mapres, but not to skins. If there is already a delineated exception, there is no hindrance of adding another one. In fact, the separation of mapres and skins is artificial, they can well be in the same folder.

**Comment by def-** [comment]
No one guarantees you that the skins even exist. Some old DDNet versions had LOTS of skins bundled and we removed them again. That should not break maps. Someone might like to replace their local skins (in ~/.teeworlds/) with cat skins (we have a topic for that in the forum) and that should also not break maps.

**Comment by Socialdarwinist** [comment]
It does not break maps if the standard skins are replaced with cat skins. It is then still ensured that classes the player plays look the same as in the class menu. But when we use graphics of the skins in the class menu, but a user has replaced the standard skins, the graphics do not denote anything for him: They will be different from the actually used skins. So accessing the skins in the skins folder via the map ensures compatibility with user-changes. Your argument makes no sense.
