### ISSUE TITLE
Add editor component api for getting currently hovered tiles

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#7943]
Clicking and hovering tiles is nice imo. That is why I added a feature already that involves clicking tiles. And I am planning to add more. Maybe even some that hover tiles. Now this issue is a proposal of adding a central piece of code that gets called on mouse move. And iterates on all tiles that are currently under the cursor. So from all groups and layers. And then it calls a callback with those tiles. And now a bunch of editor components can register their callback there.

Pseudo code would look like this
```C++
void CEditor::OnMouseMove()
{
	for(auto EditorComponent : m_vEditorComponents)
	{
		for(size_t g = 0; g < m_Map.m_vpGroups.size(); g++)
		{
			for(size_t l = 0; l < m_Map.m_vpGroups[g]->m_vpLayers.size(); l++)
			{
				std::shared_ptr<CLayerTiles> pTiles = std::static_pointer_cast<CLayerTiles>(m_Map.m_vpGroups[g]->m_vpLayers[l]);
				int x = UI()->MouseWorldX();
				int y = UI()->MouseWorldY();
				CTile Tile = pTiles->GetTile(x, y);
				EditorComponent.OnHoverTile(Tile);
			}
		}
	}
}
```

Then there would be one central location where we can properly think about how to make it fast. Iterating all tiles on hover seems expensive.

And all the feature developers can just hook in there and get this nice callback without having to worry about performance.
This could help with the existing ctrl+left click tile to select layer #4958 and would also be used by my planned click on tele or switcher to go to the counter part #7931

This could also come in handy for any kind of hover annotations. Such as hover tele FROM and instantly see lines to the tele TO (#2415).
Or some grid only at the current mouse cursor. Drawing a box around all tiles currently under the cursor. To understand how parallax and offsets affect the grids.
Hover tunes and get a detailed box on what the tune is.

@Marmare314 added the nice editor components lets spice em up with some callbacks #7014

**Comment by heinrich5991** [comment]
Sounds good to me.
