### ISSUE TITLE
Server can bring client in a weird state

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#7965]
i haven't debugged it yet, but entities aren't loaded:
![image](https://github.com/ddnet/ddnet/assets/6654924/5f550484-8b26-4716-8308-9575373a94e4)

changing entities assets results in an assert:
![image](https://github.com/ddnet/ddnet/assets/6654924/9347be87-c71a-4aed-a429-c147ee56dc75)

this can be reproduced on this server: 5.181.50.244:10000

**Comment by Jupeyy** [comment]
Also note: the code for the server was not changed in ~2 years.

So something in the client changed to cause this I assume

**Comment by Robyt3** [comment]
Seems to happen for any server that wants the client to use anything except the DDNet entities. You can reproduce this on any server by forcing the choice of entities in the client by setting `EntitiesModType` manually in the following:

https://github.com/ddnet/ddnet/blob/8870eb94aa5351edc82655cb9cd1d0270ff9b868/src/game/client/components/mapimages.cpp#L186-L204

**Comment by Robyt3** [comment]
Testing with different release versions, the first version where this happens is 16.8, so it's probably related to this change

> [Client] Merge entity textures to reduce memory usage [Jupeyy] (#6275)

**Comment by 0xfaulty** [comment]
> Testing with different release versions, the first version where this happens is 16.8, so it's probably related to this change
> 
> > [Client] Merge entity textures to reduce memory usage [Jupeyy] (#6275)

Could we have MAP_IMAGE_MOD_TYPE_HIDE or smth like that where server could disable client entities (current behaviour)? Bcs I use that bug to prevent clients to see some map details in some areas :)

**Comment by Robyt3** [comment]
> Could we have MAP_IMAGE_MOD_TYPE_HIDE or smth like that where server could disable client entities (current behaviour)? Bcs I use that bug to prevent clients to see some map details in some areas :)

Needs a discussion and is separate from this bug, so I opened a separate issue #7970 for this.
