### ISSUE TITLE
allow autocompletion | show tooltips when using "bind x [command]"

### ISSUE THREAD

**Issue by BlaiZephyr** [ddnet/ddnet#7966]
as of right now, if you bind a key using the console, the description will always display the bind tooltip, it should allow autocompletion of *edit*: the current argument based on the cursor position and the corresponding tooltip
![image](https://github.com/ddnet/ddnet/assets/101197249/dfd02404-1a69-44f8-966e-221ca7b47888)

**Comment by archimede67** [comment]
What would be "the current command"? In your example, you bind multiple commands to one key.
We could do something similar to the map settings input where we show the current argument based on the cursor position

**Comment by BlaiZephyr** [comment]
> What would be "the current command"? In your example, you bind multiple commands to one key. We could do something similar to the map settings input where we show the current argument based on the cursor position

english wording - yes that was exactly what i meant ^^

**Comment by ChillerDragon** [comment]
I developed a hacked workflow where I would cut all then type the command get hints and completion and then insert the cut again :D 

But yea that feature would be nice

**Comment by ChillerDragon** [comment]
Closed by #8352 I assume? Or do you still miss something @BlaiZephyr?

**Comment by BlaiZephyr** [comment]
sorry didnt even get a notifcation! - looks good to me, thanks a lot @ChillerDragon !!!
