### ISSUE TITLE
Adding flag so server can cleanly disable client entity textures

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7970]
> Could we have MAP_IMAGE_MOD_TYPE_HIDE or smth like that where server could disable client entities (current behaviour)? Bcs I use that bug to prevent clients to see some map details in some areas :)

_Originally posted by @0xfaulty in https://github.com/ddnet/ddnet/issues/7965#issuecomment-1938987668_

**Comment by heinrich5991** [comment]
No, the client is a user agent and does not serve the server.
