### ISSUE TITLE
Crash when trying to open old map

### ISSUE THREAD

**Issue by M0REKZ** [ddnet/ddnet#7985]
The next Assertion Error appears when trying to open this old map with the editor, game told to report the issue here

Need to note that this only happens on editor

<details>
An assertion error occurred. Please write down or take a screenshot of the following information and report this error.
Please also share the assert log which you should find in the 'dumps' folder in your config directory.

/Users/deen/ddnet-source/src/game/editor/mapitems/envelope.cpp(51): invalid number of channels for envelope

Platform: macos
Game version: 18.0.3 75934e16aa4eea3a1f93f3876b6cbc42bd689c54
OS version: Darwin 23.3.0 (arm64, Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:27 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8103)

GPU: Apple - Apple M1 - 4.1 Metal - 88
</details>

[Moon 1.0.map.zip](https://github.com/ddnet/ddnet/files/14319578/Moon.1.0.map.zip)

[DDNet_assert_log_2024-02-17_13-37-31_1122.txt](https://github.com/ddnet/ddnet/files/14319595/DDNet_assert_log_2024-02-17_13-37-31_1122.txt)

**Comment by Robyt3** [comment]
Do you know how this map was created? The third envelope has 8 channels, so it's invalid, as only envelopes with 1, 3 and 4 channels are supported.

Versions 12.0.1 and 15.7 also crash with this map, but only when selecting the third envelope. Version 16.9 crashes when hovering the envelope channel buttons of the third envelope.

**Comment by M0REKZ** [comment]
> Do you know how this map was created?

I just downloaded the map from some random place
