### ISSUE TITLE
Client crash related to ghosts when finishing map

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#8003]
Reported by Peter0x44 on Discord:

> /usr/include/c++/13.2.1/bits/stl_vector.h:1125: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = CMenus::CGhostItem; _Alloc = std::allocator<CMenus::CGhostItem>; reference = CMenus::CGhostItem&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)
> just crashed the INSTANT I finished a map

**Comment by Peter0x44** [comment]
Hey, thanks for filing this issue.
