### ISSUE TITLE
multi-view: shaking camera if someone tp, /spec, kill etc. 

### ISSUE THREAD

**Issue by trikiman** [ddnet/ddnet#8027]
I saw how 4er team doing part with tp and it was uncomfortable to watch cus camera just shaken.

**Comment by trikiman** [comment]
Just video. https://discord.com/channels/252358080522747904/295908390956433410/1212171359413604443
if they fail part it's even worse.

**Comment by heinrich5991** [comment]
https://cdn.discordapp.com/attachments/295908390956433410/1212171357886881833/2024-02-28_01-53-29.mp4 (can't click it directly, need to re-post it in Discord).

**Comment by ewancg** [comment]
https://github.com/ddnet/ddnet/assets/36348486/5171d114-77c0-4685-9385-1ca052cb7aab
