### ISSUE TITLE
Friendlists online Players affected by filters

### ISSUE THREAD

**Issue by ScReeNyDev** [ddnet/ddnet#8032]
Hey there,

i mostly got used to the Serverbrowser update and prefer it, but there is one thing that became kinda annoying. Before the update i could swap to the internet tab and look at my friendlist to see if anyone is online at all. Now with just one tab and one filter, i have to reset all filters(communities, countries, types) to get that information. 

Within the Friendlist there are three Categories(Online Players, Online Clanmates, Offline). I could also imagine that something called online being affected by filters could be confusing to some. My Suggestion would be to decouple the filter from the friendlist entirely or add another category to the friendlist. The latter could create some issues with selecting a server that is not in the list tho.

**Comment by heinrich5991** [comment]
If we do it entirely decoupled, the friendlist would not work for LAN servers anymore. Not too bad, I guess.

**Comment by ScReeNyDev** [comment]
not important anymore with favorite community tabs, thanks

**Comment by AssassinTee** [comment]
> If we do it entirely decoupled, the friendlist would not work for LAN servers anymore. Not too bad, I guess.

This was maybe true back when we only had global and lan, but now we have community tabs making this an issue IMO
