### ISSUE TITLE
Prevent overflow of mousesensitivity marker in settings by using an alternating scale

### ISSUE THREAD

**Issue by Socialdarwinist** [ddnet/ddnet#804]
![mousensoverflow](https://user-images.githubusercontent.com/20446122/28491055-72a04962-6ee9-11e7-9eb3-18bbcf8d6fa4.png)

The mouse sensitivity bar currently only shows and sets values from five to five hundred correctly though the configuration variable supports up to hundred thousand. The picture shows the controls tab with `1067` being set for `inp_mousesens`.

Now it would be awesome if the mouse sensitivity configuration bar in the GUI would alternate its range, shown by a literal scale above the sensitivy bar (in the more explicit German: durch eine sich verändernde Maßstabsanzeige). Like a user begins with a range 0–500, but if he reaches say 450 the scale becomes 1–1000, then if he reaches 900 it becomes 1000–5000 and so on and so back.

It’s not that I would need it, but the notion is thrilling and DDNet could show off what it is really able to do, and it can also not be excluded that newbies leave because of such a trifle, it undergirding the view that they can never become familiar with the controls. I bring this forth forthy I have thought this out as a most refined manner of fixing a wee bug.

**Comment by Learath2** [comment]
Didn't we have a PR that added a text box to input any sens + a clamped slider?

**Comment by Socialdarwinist** [comment]
I find nothing here relevant relating to “sensitivity” or “mousesens” in PRs.

**Comment by Learath2** [comment]
Well would that work for you?

**Comment by Socialdarwinist** [comment]
I can’t really grasp what a “clamped slider” is. And a text box is what the local console is. As I said, the issue is not at all for my needs, but rather about that the sensitivity selection can be better anyway to reflect actually possible mousesensitivity, and I think that I have written down a pleasant concept.

**Comment by Socialdarwinist** [comment]
Another possibility would be a slider for changing the scale, like when you zoom in or out in a map service where you zoom in to move less distance when dragging the map and the other way around.

**Comment by def-** [comment]
Fixed by https://github.com/ddnet/ddnet/commit/f09a0f640fad9c411b327c9c4c86cd21acd3aef6
