### ISSUE TITLE
CMake build on OSX

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#805]
Doesn't work yet

**Comment by Learath2** [comment]
Don't really have a mac to test on but it's not linking the correct frameworks iirc. #781 fixed frameworks.

It also fixed a linking problem with objective-c and C++ interacting, idk how bam manages to properly get that to link but I think the way it's done in #781 is the correct way. It does break bam tho which is even weirder.

**Comment by H-M-H** [comment]
SDL_main is indeed not required anymore (as of SDL2) https://wiki.libsdl.org/MigrationGuide. It has also been thrown away in official teeworlds-repo alongside with some Objective-C: https://github.com/teeworlds/teeworlds/commit/0a8ce055cd1ef1148ed8cb4187ca3ab8fe31fe79
