### ISSUE TITLE
macOS CI `brew link` step failing

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#8053]
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.12

To list all files that would be deleted:
  brew link --overwrite python@3.12 --dry-run
```

Related to #8018 I assume.

See:
- #8046
- https://github.com/ddnet/ddnet/actions/runs/8129305597/job/22216240909

**Comment by MilkeeyCat** [comment]
i changed `build.yml` to what it looked like before my change and it still fails https://github.com/MilkeeyCat/ddnet/actions/runs/8129515894/job/22216711882

**Comment by Robyt3** [comment]
Maybe the macOS CI updated to python 3.12, so we need to add the overwrite for that instead of for 3.11.

**Comment by MilkeeyCat** [comment]
i think the easiest solution would be to use `macOS-14` instead of `macOS-latest` :\

**Comment by MilkeeyCat** [comment]
> error: externally-managed-environment
> 
> × This environment is externally managed
> ╰─> To install Python packages system-wide, try brew install
>     xyz, where xyz is the package you are trying to
>     install.
>     
>     If you wish to install a non-brew-packaged Python package,
>     create a virtual environment using python3 -m venv path/to/venv.
>     Then use path/to/venv/bin/python and path/to/venv/bin/pip.
>     
>     If you wish to install a non-brew packaged Python application,
>     it may be easiest to use pipx install xyz, which will manage a
>     virtual environment for you. Make sure you have pipx installed.
> 
> note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
> hint: See PEP 668 for the detailed specification.

this is an error as well btw
