### ISSUE TITLE
cross compile with cmake

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#807]
in order to build the official releases with cmake I need cross-compiling support, see: https://github.com/ddnet/ddnet-scripts/blob/master/ddnet-release.sh

**Comment by necropotame** [comment]
You can check CMake toolchain for that. Here is an example of release script for Linux 32/64 and windows : https://github.com/teeuniverse/teeuniverse/tree/master/scripts/release

**Comment by def-** [comment]
Would be nice to have this feature since the dpi awareness stuff seems to be cmake only, not bam.
