### ISSUE TITLE
fail to register into the master server.

### ISSUE THREAD

**Issue by lankerens** [ddnet/ddnet#8080]
why i cant register into the master server.

log like this.

2024-03-10 21:25:39 I http: libcurl version 8.0.1 (compiled = 8.0.1)
2024-03-10 21:25:39 I host_lookup: host='localhost' port=0 1
2024-03-10 21:25:39 I host_lookup: host='localhost' port=0 2
2024-03-10 21:25:39 I console: executing 'autoexec_server.cfg'
2024-03-10 21:25:39 I server: added maps to votes
2024-03-10 21:25:39 I console: failed to open 'myServerconfig.cfg'
2024-03-10 21:25:39 I server: starting...
2024-03-10 21:30:55 I register/6/ipv4: registering...
2024-03-10 21:30:57 E register/6/ipv4: ERROR: the master server reports that clients can not connect to this server.
2024-03-10 21:30:57 E register/6/ipv4: ERROR: configure your firewall/nat to let through udp on port 18888.
.........

config like this 
sv_port 18888
sv_register ipv4

**Comment by heinrich5991** [comment]
You need to forward port 18888 on your router to your computer.

**Comment by lankerens** [comment]
> You need to forward port 18888 on your router to your computer.

firewalld is down. Ports 18888 and 8303 are open. what does forwarding mean.

**Comment by heinrich5991** [comment]
Do you host this server at your home? Or is it on some server you rented somewhere?

If it's at home, "port forwarding" means that you have to tell your router that packets from the outside coming to port 18888 should be routed to your computer.

**Comment by lankerens** [comment]
> Do you host this server at your home? Or is it on some server you rented somewhere?
> 
> If it's at home, "port forwarding" means that you have to tell your router that packets from the outside coming to port 18888 should be routed to your computer.

yep, it running on my rented server

**Comment by heinrich5991** [comment]
Can you connect to your game server via IP address with the DDNet client?

**Comment by lankerens** [comment]
> Can you connect to your game server via IP address with the DDNet client?您可以使用 DDNet 客户端通过 IP 地址连接到您的游戏服务器吗？

sure, open ddnet client. i can use ip:18888 connect server and play game .  but it can only be accessed by searching......
I deployed via linux

**Comment by heinrich5991** [comment]
Is your server located in China? If so, could you send me your server's IP address? Server registering doesn't work in China currently, because the Chinese firewall blocks our network packets.

**Comment by lankerens** [comment]
> Is your server located in China? If so, could you send me your server's IP address? Server registering doesn't work in China currently, because the Chinese firewall blocks our network packets.

u r right.  ok. i have send email to u.  thank u of ur help

**Comment by heinrich5991** [comment]
Does it work now? The server should be whitelisted now.

**Comment by lankerens** [comment]
> Does it work now? The server should be whitelisted now.

yep. it work now.  love u. bro
