### ISSUE TITLE
empower work of /tpxy

### ISSUE THREAD

**Issue by lolipodass** [ddnet/ddnet#8082]
At the moment, /tpxy is a pretty useful command, but using it creates a lot of monotonous work. For example, sometimes you just need to move one coordinate to the left or right, but to do that you have to write not only the x coordinate but also the y coordinate, which is very annoying on large maps, +1000 blocks. 
I think it would be to everyone's benefit to give the option to leave the coordinate untouched if you don't pass it. For example, "/tpxy 20.13" would only teleport along the x-axis. 
Or even add the ability to transmit only the y-coordinate - for example "/tpxy _ 20.13" or "/tpxy -1 20.13" or some other variant.
And the second useful feature for the command, the ability to not teleport itself to a certain coordinate, but the ability to move itself. For example, you just need to move yourself to the right by one coordinate from 20.13 to 20.16. But again, for this will have to write a lot for such a simple action. That is to add the ability to write like this "/tpxy +0.3" or something else.
But for this it may be even better to add a new command - /movexy or something else to call it.

**Comment by bencie** [comment]
Both of these are already possible. You can use the tilde `~` prefix to teleport relatively from where you are. So the commands for your examples would be:
/tpxy 20.13 ~0
/tpxy ~-1 ~0

**Comment by lolipodass** [comment]
> Both of these are already possible. You can use the tilde `~` prefix to teleport relatively from where you are. So the commands for your examples would be: /tpxy 20.13 ~0 /tpxy ~-1 ~0

well, but then I would like something to be written about this at least somewhere, because now the description is so simple, and it doesn’t say anything about existence ~. /help is not really helpful xd
