### ISSUE TITLE
More lag than ever when viewing scoreboard for the first time when in CJK

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#809]
How to reproduce:
1. Open DDNet client
2. Set to Japanese
3. Join server
4. Press the key bound to show scoreboard

There was already delay before, but with the latest patches, the lag is absolutely horrendous. Clicking on different tabs (for the first time, before rendering anything), like players, server info, etc. also causes massive lags.

**Comment by def-** [comment]
I don't remember that we changed anything about that.

**Comment by heinrich5991** [comment]
We changed some libs, dunno which?

**Comment by def-** [comment]
freetype sounds like the obvious culprit

**Comment by Learath2** [comment]
It's easy to handle ASCII and maybe extended Latin but I really don't know how we can handle CJK better. Can't really pre-render the glyphs in that case, right? Are there maybe some commonly used glyphs we could render to an atlas on language choice?

**Comment by def-** [comment]
What about rendering text async? Text is not essential for gameplay, so it would be better to show a few frames without text while it is rendering in the background.

**Comment by PathosEthosLogos** [comment]
Any updates on this? Now it takes 3 seconds, which is longer than opening DDNet and joining a server, and I have an SSD.

**Comment by Learath2** [comment]
We could possibly cheat by pre-rendering all the phrases used in the GUI on language selection.

**Comment by Jupeyy** [comment]
@PathosEthosLogos you can check if the current DDNet version improves this behaviour for you.

**Comment by Learath2** [comment]
@PathosEthosLogos Is this still relevant?

**Comment by PathosEthosLogos** [comment]
Sorry for late reply -- 

@def- @Learath2 @Jupeyy I can confirm that the lag is now gone! It feels amazing.

Case closed!
