### ISSUE TITLE
Exploiding bullet bug (visuel)

### ISSUE THREAD

**Issue by teini94** [ddnet/ddnet#8091]
![screenshot_2024-03-11_23-47-34](https://github.com/ddnet/ddnet/assets/110184616/b2fedefa-aca1-4e8e-adea-17411b234c88)
as u see here I am flying in the air on top of exploding bullets

https://github.com/ddnet/ddnet/assets/110184616/89a01157-9d03-41bc-97b1-c9a149b93a27

**Comment by Robyt3** [comment]
Duplicate of #5368.
