### ISSUE TITLE
/practice commands /weapons

### ISSUE THREAD

**Issue by teini94** [ddnet/ddnet#8092]
add /laser /rocket /jetpack /shotgun and /weapons 
but not only /weapons (cause picking up weapons is a skill of speedrun)

**Comment by BlaiZephyr** [comment]
Is there a scenario where typing /Grenade is faster than redoing a part that gives you that weapon or Just teleporting to quickly Grab it?

**Comment by teini94** [comment]
ye like when u rejoin a map and wanna keep training the part with ur big team, and all have to relocate the last position of the last weapon somewhere in the map

**Comment by bencie** [comment]
> Is there a scenario where typing /Grenade is faster than redoing a part that gives you that weapon or Just teleporting to quickly Grab it?

I'd say yes, usually after dying you'd need to find the weapon in the map to pick it up, and in worst case scenario you need to find all 3 weapons in a big map.

**Comment by BlaiZephyr** [comment]
> > Is there a scenario where typing /Grenade is faster than redoing a part that gives you that weapon or Just teleporting to quickly Grab it?
> 
> I'd say yes, usually after dying you'd need to find the weapon in the map to pick it up, and in worst case scenario you need to find all 3 weapons in a big map.

Didnt think of that scenario tbh :P
