### ISSUE TITLE
Swap player/dummy colors, save skin/color presets

### ISSUE THREAD

**Issue by kaitlynia** [ddnet/ddnet#8095]
This should be fairly simple to implement in DDNet, especially since @sjrc6 has already implemented it as part of TaterClient. Swapping player/dummy skin/color I don't think is in TaterClient though. Where I think this should go in the UI:

![image](https://github.com/ddnet/ddnet/assets/38897710/efbb85b4-d004-499d-b6e0-6495de366ce8)

If this is too crowded, we could always repurpose the tee portrait on the left as a dropdown menu for the expression picker on the right, freeing up that space. (realized I forgot to include a save button, I guess this would be to the right or left of the preset numbers)

**Comment by Robyt3** [comment]
Skin presets have already been suggested in #6031.

I don't see the motivation for adding a UI feature to swap player and dummy skin colors. Setting the color manually seems simple enough. If you need to change it often then you could create binds for that.

**Comment by heinrich5991** [comment]
I think that both this and #6031 are too niche to warrant a UI. I'd prefer if that was left to custom clients.

**Comment by kaitlynia** [comment]
One of the advantages of swapping colors is to keep a color combination you like, swap them, then maybe decide to swap back if you don't like your new changes. This is simpler still with presets but I understand the reasoning that it is niche.

I still think it is worth doing, separately, to change the expression picker to be part of the portrait on the left. Conserving space as well as making it a bit more obvious for new players

**Comment by Robyt3** [comment]
> One of the advantages of swapping colors is to keep a color combination you like, swap them, then maybe decide to swap back if you don't like your new changes. This is simpler still with presets but I understand the reasoning that it is niche.

That's too niche. You can remember the color values or write them down if you want to keep them. Or use `player_color_body; player_color_feet` in the console so the values are printed in the console so you can change back if necessary.
