### ISSUE TITLE
Client crash with assertion `src/engine/shared/http.cpp(443) : Request not done`

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#8107]
Reported by @MilkeeyCat on Discord:

> [happened] when i was joining a map
> i was playing before

![image](https://github.com/ddnet/ddnet/assets/23437060/62a15577-1bda-4a84-96ee-36c423c2da5d)

6df1d251

**Comment by MilkeeyCat** [comment]
> Thread 1 "DDNet" received signal SIGILL, Illegal instruction.
> dbg_break () at /home/alex/personal/ddnet/src/base/system.cpp:205
> 205             __builtin_trap();
> (gdb) bt
> #0  dbg_break() () at /home/alex/personal/ddnet/src/base/system.cpp:205
> #1  0x0000555555c829af in dbg_assert_imp(char const*, int, bool, char const*)
>     (filename=0x5555556066f0 "/home/alex/personal/ddnet/src/engine/shared/http.cpp", line=449, test=false, msg=0x555555606899 "Request not done")
>     at /home/alex/personal/ddnet/src/base/system.cpp:198
> #2  0x0000555555c4cb71 in CHttpRequest::ResultAgeSeconds() const (this=0x555558db1a20) at /home/alex/personal/ddnet/src/engine/shared/http.cpp:449
> #3  0x00005555558fb0e8 in CServerBrowserHttp::Update() (this=0x5555562c2560) at /home/alex/personal/ddnet/src/engine/client/serverbrowser_http.cpp:403
> #4  0x00005555558d53bd in CServerBrowser::Update() (this=0x7fffefa87308) at /home/alex/personal/ddnet/src/engine/client/serverbrowser.cpp:1201
> #5  0x0000555555882a1f in CClient::Update() (this=0x7fffef9d6010) at /home/alex/personal/ddnet/src/engine/client/client.cpp:2640
> #6  0x0000555555883f13 in CClient::Run() (this=0x7fffef9d6010) at /home/alex/personal/ddnet/src/engine/client/client.cpp:2948
> #7  0x000055555588c22d in main(int, char const**) (argc=1, argv=0x7fffffffdb78) at /home/alex/personal/ddnet/src/engine/client/client.cpp:4537

here's backtrace if it helps somehow =]

**Comment by def-** [comment]
@Learath2 Related to http changes?

**Comment by heinrich5991** [comment]
According to stack trace, it's my #8099.
