### ISSUE TITLE
Log messages skipped during startup

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#812]
```
[17-07-24 20:52:59][datafile]: loading data index=21 size=11688 uncompressed=1000000
Skipped 46 log messages because of full queue.
[17-07-24 20:52:59][datafile]: loading data index=35 size=3221 uncompressed=500000
```

Sounds like it shouldn't happen outside of stress situations.

**Comment by def-** [comment]
Well, messages can get created quite quickly and we don't want to block. We used to block when the queue is full, and that caused huge problems with slow disks. We could just increase the queue to a more reasonable size.

**Comment by def-** [comment]
fixed
