### ISSUE TITLE
Client crashes when switching layers with autorule menu open

### ISSUE THREAD

**Issue by lomination** [ddnet/ddnet#8121]
Hi there,

I'm using 18.0.3 on Linux (Ubuntu).

I have noticed that the ddnet client crashes (always) when I press the up or down arrows and the autorule menu of a tile layer is open. This only happens when I switch from a tile layer to a non-tile layer such as game. The client may be trying to open the autorule menu in the newly selected layer, but it can't because it doesn't have an autorule menu.

This was (fortunately) not my case, but it could be quite annoying if someone loses a map because of this :/ It looks easy to do this by mistake.

After the crash, the console displays: `Segmentation fault (core dumped)`.

**Comment by BlaiZephyr** [comment]
isnt this a duplicate of #8116 ?

**Comment by archimede67** [comment]
Seems like it, but this one is more specific

**Comment by lomination** [comment]
Yes it is, I didn't know that an issue had already been created on github, my bad
