### ISSUE TITLE
Don't close vote menu automatically if not wanted

### ISSUE THREAD

**Issue by MrCosmo666** [ddnet/ddnet#813]
Would it be possible to make the automatically closing of the vote menu after calling a vote optional? It's a nice feature but currently it's a bit annoying for me while testing my mod. I think a simple config option to enable/disable that would not be bad.

https://github.com/ddnet/ddnet/commit/b495b1681ca5ef62540cf0f1e881a8b142c52d0f#diff-9266540b75421428fa2bf1a3b55de980R651

**Comment by def-** [comment]
f1, cl_show_votes_after_voting 1

**Comment by MrCosmoTW** [comment]
Doesn't work for me. I'm talking about "Call Vote" for server settings. Not about voting using f3 or f4. There is no code line which can stop SetActive(false); from executing. Please visit the link I've posted above before closing my issues.

**Comment by def-** [comment]
Just press Escape again and it's open again immediately?

**Comment by MrCosmoTW** [comment]
Wow. Didn't come to this idea by myself... Dennis. Please step back from ddnet and let heinrich handle it.

Just say you won't add cause "reason here" and close the issue. Don't just close it without reading it. As I said, for some people it would be easier if there is an option to disable the automatically closing of the vote menu. So why not adding a simple config variable for that.

**Comment by def-** [comment]
Comment by @Anime-pdf :

> Add option to let people keep vote menu opened after starting a vote. cl_show_votes_window_after_voting basically.
It will be handly for other mods and for ddnet, when you voting server difficulty first and map after.
> Menus dont have much config options afaik, so adding new option and testing it with other options mustn't be a problem.

I'm not sure if we really want another option for this. Isn't pressing escape quickly fast enough?

**Comment by Anime-pdf** [comment]
Yes, but that is just addiction to my point 😄.
My main idea is that this feature will be cool for everyone who plays custom gamemods, teeworlds is a big playground after all.

**Comment by edg-l** [comment]
why not add a simple server provided menu feature to the protocol to new ddnet clients, so we avoid hacky call votes

**Comment by Matodor** [comment]
`ui_close_window_after_changing_setting 0` work for me in votes menu, but `cl_show_votes_after_voting` - no.

**Comment by def-** [comment]
Forgot we added that option, thanks @Matodor .
Solution: `ui_close_window_after_changing_setting 0`
