### ISSUE TITLE
Allow the usage of 70hz in the display resolutions

### ISSUE THREAD

**Issue by tomasmfc** [ddnet/ddnet#8138]
Would be nice to be able to use my the 70 hz that my monitor has (not that it is much)

**Comment by archimede67** [comment]
I'm not sure what you mean. You are talking about a refresh rate, which you can set in the graphics settings:

![image](https://github.com/ddnet/ddnet/assets/13364635/d3bc4f95-02de-4f27-a03f-5d8f8cece283)

**Comment by Robyt3** [comment]
The screen refresh rate shown and selected in the resolution list on the right side is only relevant if you use VSync, which is not recommended if you want lower input delay. If you want to select a value that's not shown in the list you could use `gfx_screen_refresh_rate 70` in the local console (F1).

**Comment by Calinou** [comment]
It appears this option is not a refresh rate setting, but a FPS limiter.

This is exactly like the option in the General tab, which is also a FPS limiter despite being called a refresh rate setting. When you have both limits set, it seems the lowest value is retained.

I suggest renaming both values from "Refresh Rate" to "Max FPS", and perhaps remove the one in the General tab in favor of the one in the Graphics tab.

**Comment by tomasmfc** [comment]
> The screen refresh rate shown and selected in the resolution list on the right side is only relevant if you use VSync, which is not recommended if you want lower input delay. If you want to select a value that's not shown in the list you could use `gfx_screen_refresh_rate 70` in the local console (F1).

it resets on client reset. any way to make it persistent?

**Comment by Robyt3** [comment]
> > The screen refresh rate shown and selected in the resolution list on the right side is only relevant if you use VSync, which is not recommended if you want lower input delay. If you want to select a value that's not shown in the list you could use `gfx_screen_refresh_rate 70` in the local console (F1).
> 
> it resets on client reset. any way to make it persistent?

@tomasmfc Try setting `gfx_display_all_video_modes 1` so the resolution list shows all resolutions including not strictly compatible ones. Maybe it's not supported according to your display driver, so it's reset again. As I said above, unless you specifically have to use VSync to avoid tearing, you should not use VSync, so the `gfx_screen_refresh_rate` setting is meaningless.

**Comment by Jupeyy** [comment]
Search the internet for how to set custom resolutions for your graphics card, but other than that, there is nothing ddnet can do. We get all supported resolutions from SDL2
