### ISSUE TITLE
Maintainers personal opinions should not block merges

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#8142]
The current state for ddnet contributors is more annoying than it should be in my opinion.

If the pr is reviewed by deen it gets merged within 2 minutes no questions asked.
If the pr gets reviewed by heinrich it gets a bunch of nit picks that have to be solved before it can be merged.
If the pr gets reviewed by robsti it gets a bunch of nit picks that have to be solved before it can be merged.

The opinions of heinrich and robsti do not always align.

The whole thing causes a back and forth every time which is exhausting and time consuming. It makes contributing to ddnet no fun.

I propose that maintainers should avoid requesting changes that are based on their opinion at all cost. All opinions should be discussed in issues instead (for example https://github.com/ddnet/ddnet/issues/6436). Then the results of that get added to a style guide and maybe even to the CI. So it is clear for contributors what the rules are. And ideally the contributor gets no opinionated feedback on prs that pass the pipeline anymore.

Opinions that I encountered that could be fixed by tooling:
- Minimum variable name length
- Usage of ``goto``
- Assignments in if statements
- Methods with default arguments
- Method overloading
- Class member variable initialization directly with the declaration
- ``struct`` or ``class``

**Comment by heinrich5991** [comment]
> I propose that maintainers should avoid requesting changes that are based on their opinion at all cost.

What does that mean? PR reviews are for upholding code quality. Can you describe a change that falls under opinion-based and one that falls under code quality?

**Comment by ChillerDragon** [comment]
> What does that mean? PR reviews are for upholding code quality. Can you describe a change that falls under opinion-based and one that falls under code quality?

All the opinions I listed above. If for example you dislike default arguments for parameters that should not be a manual nitpick comment every time. That should be one ddnet style guide that is enforced by all maintainers equally and known to the contributors if they check the style guide. Or even better covered by the CI.

Everything that can be generalized and is happening multiple times should have a clear process. Contributors should be able to check for code quality them self to speed up the review process.

I do not see a difference between opinions and quality. Currently the quality checks depend on the opinions of the individual maintainers on what good code looks like.

If too short variables are bad code quality that should be a clear rule documented somewhere. And not only fixed for the variables that robsti writes manual nitpick comments to.

**Comment by heinrich5991** [comment]
I agree that it's helpful to add as much automatic checks as possible as long as it's not stopping legitimate code too much and as long as implementing the checks doesn't cost too much time.

> I do not see a difference between opinions and quality. Currently the quality checks depend on the opinions of the individual maintainers on what good code looks like.

> I propose that maintainers should avoid requesting changes that are based on their opinion at all cost.

If that's your definition of opinion, then I disagree. In my opinion, manual review can and should always be able to spot problems with the code quality. I could probably agree to a less extreme version of your statement.

**Comment by ChillerDragon** [comment]
I am not saying manual review should stop. Just a few things could be optimized. For examples robstis agenda of long and readable variable names. That should not be a nit pick comment every time but something standardized which is known to all maintainers and contributors. And it could also be enforced in the CI with https://clang.llvm.org/extra/clang-tidy/checks/readability/identifier-length.html

**Comment by heinrich5991** [comment]
> readable variable names.

This is something that cannot be encorced by CI. Trying to enforce it using CI is going to lead to worse variable names, especially if you go by length only.

**Comment by ChillerDragon** [comment]
> > readable variable names.
> 
> This is something that cannot be encorced by CI. Trying to enforce it using CI is going to lead to worse variable names, especially if you go by length only.

In my head length 3+ with the exception of x, y, i could work

**Comment by ChillerDragon** [comment]
Also this one for example. I do not enjoy wasting energy on the assignment in if statement discussion.

https://github.com/ddnet/ddnet/pull/5949#discussion_r1532452661

Imo this should be a clear rule not something that is discussed over and over again. Could also be caught by clang tidy in the CI

https://clang.llvm.org/extra/clang-tidy/checks/bugprone/assignment-in-if-condition.html

**Comment by heinrich5991** [comment]
I think it's okay not trying to put everything into CI. I think it's okay if you personally create a PR to add it (at least the very last one) to clang-tidy.

> Also this one for example. I do not enjoy wasting energy on the assignment in if statement discussion.

You could also avoid wasting energy on that discussion by following the rule the maintainer wants you to follow. Like on most open-source projects.

**Comment by ChillerDragon** [comment]
> You could also avoid wasting energy on that discussion by following the rule the maintainer wants you to follow.

It would be smoother if those things could be fixed while working on the pr when the CI fails. And not 2 weeks later when the review comment comes in. If you think the CI is too strict what about writing down those style rules?

**Comment by heinrich5991** [comment]
Yes, adding the rules to some sort of document sounds good.

**Comment by ChillerDragon** [comment]
> Yes, adding the rules to some sort of document sounds good.

Okay where? I know teeworlds has some style guide markdown but I don't think ddnet has any yet.
Should that be some CONTRIBUTING.md at the root of ddnet/ddnet or a new repo?

**Comment by ChillerDragon** [comment]
There is a CONTRIBUTING.md now
