### ISSUE TITLE
``game/generated/client_data.h`` is no longer copied to ``./src``

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#8152]
In non standard ddnet compile setups line 22 might compile while 23 will fail.

https://github.com/ddnet/ddnet/blob/7e8dc57194b542c425dd6a6158fe952702a96298/src/game/client/gameclient.cpp#L22-L23

I encountered that in https://github.com/ddnet/ddnet/pull/8151 and https://github.com/ChillerDragon/ddnet_hotui/
You could argue that every build system can probably be tweaked into making it work. But it would be nice if ``game/generated/client_data7.h`` was as easy to compile as ``game/generated/client_data.h``

![image](https://github.com/ddnet/ddnet/assets/20344300/1d1608ad-4b91-4291-bb3a-b485c539a804)

**Comment by ChillerDragon** [comment]
Oh I noticed that ``src/game/generated/client_data.h`` is no longer recreated. That was probably a old left over file from when I built ddnet before this commit 254793604c3c768926da07f6780f7026da203ded

I still think it would be nice if both were copied. Makes it easier to integrate tooling.

**Comment by heinrich5991** [comment]
Generated files should not end up in src/ because you might have multiple build directories. What's the issue with adding the build directory to your tooling?

**Comment by ChillerDragon** [comment]
> Generated files should not end up in src/ because you might have multiple build directories.

Yea I guess that makes sense. Closing as unwanted.

> What's the issue with adding the build directory to your tooling?

With https://github.com/ChillerDragon/ddnet_hotui/ I just did ``-Ibuild`` and that worked. But in https://github.com/ddnet/ddnet/pull/8151 I still do not know how to fix it. So since it happend to me twice I wanted a more permanent fix. But seems like there is none.
