### ISSUE TITLE
Community country/type filters are sometimes changed when restarting the client

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#8158]
Reported by APFFF on Discord:

> Why do the country selectors for servers always "reset" when launching the game?

It doesn't always reset though. Seems like sometimes the selection is kept and sometimes it is changed mostly arbitrarily.

Doesn't seem to affect the community filter itself.

**Comment by TsFreddie** [comment]
Found the cause, but I'm not sure how to fix it. The bug is blocked by the "strictly disallow excluding all countries" UX design.

https://github.com/ddnet/ddnet/blob/ff991af6dd3dd50ad9c4313c09bf4017b7c086ab/src/engine/client/serverbrowser.cpp#L1973-L1977

Since "midfun" community only has CHN servers, excluding CHN will cause `CleanFilter()` (which is called upon getting ddnet-info.json it seems) to call the above routine and reset the filter.

**Comment by TsFreddie** [comment]
Do people actually know that country and type filter is saved per community? Changing to a global country and game mode filter probably solves a lot of the issues we are having with the current filter.

**Comment by def-** [comment]
@Robyt3 Any idea?

**Comment by Robyt3** [comment]
> Since "midfun" community only has CHN servers, excluding CHN will cause CleanFilter() (which is called upon getting ddnet-info.json it seems) to call the above routine and reset the filter.

This also applies to the none-country/type of the none-community.

> Changing to a global country and game mode filter probably solves a lot of the issues we are having with the current filter.

That would reintroduce the problems that either 1) the filters are messed up when you switch between tabs, or 2) it's possible to select filters that exclude all servers, which the per community country/type filters were supposed to solve.

I'll try to think about a solution when I have more time.

**Comment by TsFreddie** [comment]
My thoughts are maybe either:

1. move the available options cache into serverbrowser from menus, so the filter can be conditioned to pass when none selected and while allowing the underlying state to select none.
2. defer the "none selected" cleaning routine to menu. So only clean the respective filter when the menu update the cache AND it is currently showing only one options.
