### ISSUE TITLE
button "reconnect now"

### ISSUE THREAD

**Issue by daverck** [ddnet/ddnet#820]
Hi,

Sometime a user lose connection for a short time but has to wait 300 sec to reconnect.
Can you do a reconnect now button ?

I think user has also only 1 chance to reconnect : can you improve that ?

regards,

**Comment by def-** [comment]
That's a bit dangerous. If someone learns your timeout  code they could kick you out.

**Comment by heinrich5991** [comment]
It also allows for faster player swapping.

**Comment by def-** [comment]
Also, I don't think it is 300 seconds, after 100 seconds and you reconnect and get your tee back.

**Comment by daverck** [comment]
So the timeout code isn't sent to the server only ?

**Comment by def-** [comment]
It is.
