### ISSUE TITLE
/timecp name broken 

### ISSUE THREAD

**Issue by teini94** [ddnet/ddnet#8214]
/timecp name show better timecp anymore 
I assume since atleast around 1-1,5months?

but maybe just since around newest version.

2. While fixing it we could also allow to see "/timecp name" without the need of having the map finished.

**Comment by teini94** [comment]
maybe it could help to use     
/timecp "name" 
so we may can also see players with numbers as a name (not sure if that worked before)

**Comment by dobrykafe** [comment]
Thanks for reporting this. It seems that I didn't properly test [my change](https://github.com/ddnet/ddnet/pull/8085) and the `/timecp` query is failing in mysql.

> ... While fixing it we could also allow to see "/timecp name" without the need of having the map finished.

> maybe it could help to use /timecp "name" so we may can also see players with numbers as a name (not sure if that worked before)

These two things that you mentioned should already be possible.

**Comment by BlaiZephyr** [comment]
> These two things that you mentioned should already be possible.

what about giving someone a hint that it's working? some `the player "%s" doesnt have a Checkpoint` and `tracking checkpoints of "%s"`

**Comment by furo321** [comment]
> what about giving someone a hint that it's working? some the player "%s" doesnt have a Checkpoint and tracking checkpoints of "%s" currently the only info a user gets is when checkpoints are not allowed

This is already the case. See #8085
