### ISSUE TITLE
reset timer for team crossing back the start line

### ISSUE THREAD

**Issue by daverck** [ddnet/ddnet#822]
When playing in "team 0" timer reset for the player when it cross back the start line 
but when playing in team timer don't reset when the whole team come before the start line.

**Comment by heinrich5991** [comment]
This is intended. Races in teams are supposed to be self-contained, i.e. you shouldn't be able to do part of the race and come back to the start line to reset your time.

**Comment by daverck** [comment]
it shouldn't be a problem if the whole team come back at a given moment

**Comment by heinrich5991** [comment]
Possible problems are: Carried weapons, doors, speed that might not be achievable within the starting area, other status flags (infinite jumps, no player collision/hooking, endless hooking, solo, ...).

**Comment by daverck** [comment]
we can consider changing the starting tiles to reset all that (except doors) when crossing backward 

some player will bit a bit frustrated over their record
but it would be better imo

**Comment by heinrich5991** [comment]
> we can consider changing the starting tiles to reset all that (except doors) when crossing backward

Why "except doors"? Having doors disabled doesn't constitute a clean record.

Also, how would you go about resetting the current speed of the tees?

**Comment by daverck** [comment]
speed of tees is just right :)

**Comment by daverck** [comment]
in the same vein, it would be nice if tees could team up after crossing the start line if they get back behing the start line

**Comment by def-** [comment]
No, we don't want to add back ways to cheat.
