### ISSUE TITLE
Issue with Persisting Settings in DDNetRaceNetwork Browser

### ISSUE THREAD

**Issue by PotatoCreator** [ddnet/ddnet#8222]
When adding a featured community in the DDNetRaceNetwork browser tab, there is an issue where the settings do not save correctly upon switching between the "DDNET" tab and the "All Server" tab. Currently, any changes made to settings in one tab automatically apply to both tabs, which is not the intended behavior. The settings are expected to be retained independently for each tab, allowing for customization that is specific to either the "DDNET" servers or the "All Server" list. This problem affects the usability and customization flexibility of the network browser interface.

(https://github.com/ddnet/ddnet/assets/111995771/a48201da-dab9-4b96-91c3-85378f53f805)

**Comment by Robyt3** [comment]
Please try the current nightly version, this should be fixed by #8198.

**Comment by PotatoCreator** [comment]
> Please try the current nightly version, this should be fixed by #8198.

Oh, thats nice! Thanks!
