### ISSUE TITLE
Add `/team0mode` indicator to HUD

### ISSUE THREAD

**Issue by dobrykafe** [ddnet/ddnet#8225]
Just like practice and lock is currently shown.

**Comment by BlaiZephyr** [comment]
talked to a few people But noone seems to have a good idea for such Indicator, how could one possibly indicate team0mode properly with a Symbol..

**Comment by def-** [comment]
The text "t0" if nothing else works. But I like the idea of a boat, maybe a boat of a few tees, or a literal boat. Because that's what t0 lifestyle is, isn't it? ;)
