### ISSUE TITLE
key binding for vote ban quickly

### ISSUE THREAD

**Issue by daverck** [ddnet/ddnet#824]
one more :)

**Comment by heinrich5991** [comment]
What do you mean? I assume you want a bind to votekick a player with a specific name?

**Comment by savander** [comment]
Perfect bind for trolls !

**Comment by daverck** [comment]
maybe just something to open the voteban tab

**Comment by savander** [comment]
Not usefull at all. It's not hard to press esc and then switch tab to votes.

**Comment by heinrich5991** [comment]
When you press the escape key, the last open tab is opened automatically. So if you want to votekick someone, you can click on that tab, and when you want to votekick again, you can just press escape to open the menu on the same page.

**Comment by daverck** [comment]
yeah i guess

**Comment by Jubjub** [comment]
I think a `/vote` command would be actually very convenient combined with name tab completion.

**Comment by def-** [comment]
`callvote` exists already
