### ISSUE TITLE
docs folder

### ISSUE THREAD

**Issue by H-M-H** [ddnet/ddnet#826]
Does anyone use this: https://github.com/ddnet/ddnet/tree/master/docs ? Appears to be some tool to generate docs and according to http://www.naturaldocs.org/ the latest release is from 2011. To me it looks like we can just delete it.

**Comment by def-** [comment]
Agreed. I did that when I redid the ddnet repo (which was reset again).

**Comment by heinrich5991** [comment]
Yea, can probably delete this.
