### ISSUE TITLE
sound.cpp: Sample was not unloaded

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#8262]
![IMG_7947](https://github.com/ddnet/ddnet/assets/2335377/34c3f528-5c88-4fc8-99ce-9531f7e34057)
[DDNet_assert_log_2024-04-23_21-33-32_20668.txt](https://github.com/ddnet/ddnet/files/15098260/DDNet_assert_log_2024-04-23_21-33-32_20668.txt)
Reported by Tsin

**Comment by Robyt3** [comment]
@def- Can you also share the map and RTP file?

Not sure if directly related, but when reducing  `NUM_SAMPLES` to `100` (so loading more sounds will fail) and loading a map containing sounds, starting the sound preview for a sound that could not be loaded will crash the client.

**Comment by def-** [comment]
[Uploading GalacTees.map.zip…]()

**Comment by def-** [comment]
[DDNet_win64_crash_log_2024-04-23_21-34-54_12672_70ed41b37f18d50689dbd1f7f6ff27d71bfe0274.RTP.zip](https://github.com/ddnet/ddnet/files/15113394/DDNet_win64_crash_log_2024-04-23_21-34-54_12672_70ed41b37f18d50689dbd1f7f6ff27d71bfe0274.RTP.zip)

**Comment by def-** [comment]
[GalacTees.map.zip](https://github.com/ddnet/ddnet/files/15113398/GalacTees.map.zip)
[DDNet_win64_crash_log_2024-04-23_21-34-54_12672_70ed41b37f18d50689dbd1f7f6ff27d71bfe0274.RTP.zip](https://github.com/ddnet/ddnet/files/15113400/DDNet_win64_crash_log_2024-04-23_21-34-54_12672_70ed41b37f18d50689dbd1f7f6ff27d71bfe0274.RTP.zip)

**Comment by Robyt3** [comment]
```
0x00000001404377e7: dbg_break() at src/base/system.cpp:205
 (inlined by) dbg_assert_imp(char const*, int, bool, char const*) at src/base/system.cpp:198
0x0000000140234feb: dbg_assert_imp(char const*, int, bool, char const*) at src/base/system.cpp:200
0x0000000140052ffd: CSound::AllocSample() at src/engine/client/sound.cpp:304
0x0000000140053480: CSound::LoadOpusFromMem(void const*, unsigned int, bool) at src/engine/client/sound.cpp:606
0x000000014019fd84: CEditorMap::Load(char const*, int, std::function<void (char const*)> const&) at src/game/editor/mapitems/map_io.cpp:584
0x000000014013cf6a: CEditor::Load(char const*, int) at src/game/editor/editor.cpp:8764
0x000000014002b267: CClient::Run() at src/engine/client/client.cpp:2867
0x000000014043595f: IClient::State() const at src/engine/client.h:126
 (inlined by) main at src/engine/client/client.cpp:4543
0x00000001400012ee: __tmainCRTStartup at src/mingw-w64-v11.0.0/mingw-w64-crt/crt/crtexe.c:273
0x00000001400013e6: WinMainCRTStartup at src/mingw-w64-v11.0.0/mingw-w64-crt/crt/crtexe.c:164
```

**Comment by Robyt3** [comment]
I can't reproduce the assertion. Maybe it's caused by a race condition between the sound loading thread for the game sounds and the editor loading the map sounds, which both use `AllocSample` and `UnloadSample` without synchronization.
