### ISSUE TITLE
m_vPending in log.cpp is a memory leak device

### ISSUE THREAD

**Issue by sjrc6** [ddnet/ddnet#8265]
![image](https://github.com/ddnet/ddnet/assets/22122579/8d5a8d51-403e-4fcb-bdae-c31fdb3679fe)

Every chat message leaks 4000bytes 

As far as I can tell m_vPending does nothing, but I could be wrong. I could only observe it getting cleared when the game launches and it also doesn't get accessed otherwise.

**Comment by Robyt3** [comment]
Seems like this is the pending log messages for the future file logger, which never get cleared if no logfile is set on client/server side.

As a workaround, you can set a logfile, which should prevent the leak.

**Comment by sjrc6** [comment]
If I set a log file then wouldn't it fill up my hard drive with the messages instead of my ram?

**Comment by Robyt3** [comment]
> If I set a log file then wouldn't it fill up my hard drive with the messages instead of my ram?

Yes, but more slowly because it wouldn't allocate 4 KiB for every log message but only write as many bytes as the messages contain.

**Comment by sjrc6** [comment]
For me this isn't a viable solution. I've just removed m_vPending from my build for now.

**Comment by hardliner66** [comment]
Alternatively as a workaround you could try setting `/dev/null` as a log file, but then its still doing unnecessary work. Not logging to file shouldn't leak memory tho.
