### ISSUE TITLE
Proposal for a New DDNet Game Mode

### ISSUE THREAD

**Issue by PotatoCreator** [ddnet/ddnet#8267]
Thanks to @BlaiZephyr for the non-LLM summary:

core idea: a new gamemode where Player's would be placed inside of a queue or lobby to compete on a short solo map (should take 20-25 seconds) for the fastest time achieved, one round should last approx. 5 minutes.

wanted features:

1. a new way to submit maps for that specific gamemode and an automated map rotation ( by using discord for example)

2. point allocation based on player count (e.g. in a 10-player round, points decrease from 10 for first place to 1 for the last)

<details>
<summary>
LLM-generated text for this.
</summary>
Here is a link for a discord message about this: https://discord.com/channels/252358080522747904/293493549758939136/1233464600155127808

Dear Developer Team,

I am excited to propose a dynamic new game mode for DDNet that could function as a seasonal event or a regular interactive mode, facilitated by both staff and players. This concept focuses on creating a high-energy, competitive environment through brief, intense gameplay challenges.

Game Mode Overview:
Players begin in a lobby map to prepare. The map then switches to a challenge map, estimated to take 10-20 seconds to complete. The game will pause until all players have loaded and are ready. Participants will have 5 minutes to run the map as many times as possible to record the fastest time. After the timer expires, the game pauses to calculate rankings, awarding points based on order of finish (e.g., in a 10-player setup, points decrease from 10 for first place to 1 for the last). The map changes after each round, starting the process anew.

Additional Requirement:
To continually refresh and enhance the map pool for this mode, I propose setting up a dedicated system on Discord. This would allow players to submit their map creations for consideration. Each submission must include:

A defined spawn point.
A clear start and finish line.
Settings adjusted for sv_solo_server to ensure it is suitable for solo attempts.
The submitted maps could then be evaluated by a testing team or the event host before being approved for inclusion in the game mode.

Technical Requirements:

Automated Game Management System: To handle game pauses, timing, and point tallying.
Dynamic Map Rotation: Ensures smooth transitions between games with diverse challenges.
Scalable Point Allocation System: Automatically assigns points based on the number of players and their finishing order.
Server Stability Enhancements: Necessary adjustments to accommodate quick map changes and simultaneous player activities.
Administrative and Monitoring Tools: For initiating events, overseeing game progress, and managing player interactions.
Map Submission and Approval Process on Discord: A system to manage map submissions, including testing and approval workflows.

I initially tried to discuss this idea with Main Admin "deen" but he is away and suggested I bring this proposal here for further refinement and input. Your feedback and suggestions are highly appreciated as I aim to make this engaging new mode a part of our gaming community.

I am open to any ideas and improvements that would enhance this game mode and look forward to collaborating closely with you to realize this vision.
</details>

**Comment by BlaiZephyr** [comment]
so ddrock+ ?

**Comment by sjrc6** [comment]
Is this taken from trackmania?

**Comment by PotatoCreator** [comment]
> Is this taken from trackmania?

Hmm, Interesting. I didn't think of it, but seems like a similar concept except they have elimination and everyone is running at same pace.

**Comment by TylerStocks1** [comment]
Sounds quite similar to the AwB gamemode also on tw.

**Comment by PotatoCreator** [comment]
> > > Is this taken from trackmania?
> > 
> > 
> > Hmm, Interesting. I didn't think of it, but seems like a similar concept except they have elimination and everyone is running at same pace.
> 
> Most online trackmania servers work similarly without the points. They load a new map every 15 minutes then show a leaderboard at the end of all the best times in those 15 minutes.

True! Now I get what you meant. I didn't have that on mind. Wouldn't that still be interesting? I have tested this manually with a smaller group of people and everyone loved it.

**Comment by PotatoCreator** [comment]
> Sounds quite similar to the AwB gamemode also on tw.

Never heard of that, do you have any recording of it?

**Comment by TylerStocks1** [comment]
> > Sounds quite similar to the AwB gamemode also on tw.
> 
> Never heard of that, do you have any recording of it?

I do not unfortunately. You can search in the bar AwB and a server should show. the gameplay isnt exactly the same as you said, but similar. basically players can do a 1v1 race in a short gores map. and who ever wins the race wins "Points" from the other player.

**Comment by heinrich5991** [comment]
Can someone edit the first post to a summary? It looks very much LLM generated to me.

**Comment by heinrich5991** [comment]
Thanks a lot, it's actually readable this way. I replaced the first post.

**Comment by PotatoCreator** [comment]
> Thanks a lot, it's actually readable this way. I replaced the first post.

Ye, It was chatgpt, wanted the text look more professional, but I think I went away with it a little. I'm sorry.

**Comment by PotatoCreator** [comment]
Can I get assigned?

**Comment by def-** [comment]
I don't think it should be part of DDNet. You can work on it independently.
