### ISSUE TITLE
master server reports 0.7 players as spectators and spectators as players

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#8277]
``"is_player"`` seems to be flipped on 0.7 servers

![image](https://github.com/ddnet/ddnet/assets/20344300/15eda1b1-6272-4917-b5fb-c7ea2c505593)

**Comment by ChillerDragon** [comment]
@heinrich5991 is this a [libtw2](https://github.com/heinrich5991/libtw2) issue?

**Comment by ChillerDragon** [comment]
Maybe this line?

https://github.com/heinrich5991/libtw2/blob/23a45d70cf33ba7723b881ec27fb2cb40025d640/serverbrowse/src/protocol.rs#L557

I am having a hard time finding the code for it.

**Comment by heinrich5991** [comment]
> @heinrich5991 is this a [libtw2](https://github.com/heinrich5991/libtw2) issue?

Yes. The backward compatibility runs the [`stats-browser`](https://github.com/heinrich5991/libtw2/tree/23a45d70cf33ba7723b881ec27fb2cb40025d640/stats-browser) code.

**Comment by heinrich5991** [comment]
Fixed by https://github.com/heinrich5991/libtw2/commit/ac6b4c422aebd43bc18a5f9a3526b999e62e0b5c.
