### ISSUE TITLE
Network layer should not be reporting packets from addresses other than server we connected to

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#8285]
> Why is this done here? It should be done at the network layer already, the network layer should not be reporting packets from addresses other than the server we connected to.

https://github.com/ddnet/ddnet/pull/8248#discussion_r1582984486

With "network layer" you mean checking this in `CNetClient::Recv`, @heinrich5991 ?

**Comment by heinrich5991** [comment]
Yes.

**Comment by Robyt3** [comment]
Seems like this is already checked when feeding the connection:

https://github.com/ddnet/ddnet/blob/952d3f6631cc0a1e6902ebf79b1cacca1e19ac72/src/engine/shared/network_conn.cpp#L260-L266

So the check that was moved in b264570218c522e94ee1a10f14470cc82a3462b5 seems unnecessary.

**Comment by heinrich5991** [comment]
Yea, sounds sensible, can be removed.
