### ISSUE TITLE
add mention-only chat

### ISSUE THREAD

**Issue by Bobtiz** [ddnet/ddnet#8299]
This may seem very unnecessary, but when there are a lot of people on a server or they don't stop talking, sometimes the chat becomes very long and difficult to read, that's why I wanted to propose adding a mention-only chat, which would be almost the same Same as the friends-only chat but instead of just messages from friends, only the mentions appear, so only important things appear.
Also, I don't think it's something difficult to do, I'm not a programmer or anything like that so I don't know if it's easy or not.
<3

**Comment by BlaiZephyr** [comment]
`cl_show_chat_friends 1`

**Comment by heinrich5991** [comment]
As mentioned in #8307, I don't think this is a useful filter. You'll miss half of the conversation because often only one of the messages contains the nickname.

**Comment by ChillerDragon** [comment]
Since the implementation got rejected in https://github.com/ddnet/ddnet/pull/8307. This proposal issue can be closed as "not planned".
