### ISSUE TITLE
`Skin name is not valid: xxx` is not a good error message

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#8300]
Someone asked me why his skin isn't working:
`Skin name is not valid: cf_glowcontrastcoalabopp`

Better say exactly what is wrong:
The name of the skin exceeds the 24 character limit

**Comment by ChillerDragon** [comment]
There is more than the length limit

```C++
	static bool IsValidName(const char *pName)
	{
		if(pName[0] == '\0' || str_length(pName) >= (int)sizeof(CSkin("").m_aName))
		{
			return false;
		}

		for(int i = 0; pName[i] != '\0'; ++i)
		{
			if(pName[i] == '"' || pName[i] == '/' || pName[i] == '\\')
			{
				return false;
			}
		}
		return true;
	}
```

**Comment by Jupeyy** [comment]
then all error variants should be named properly

**Comment by ChillerDragon** [comment]
* assign self *

**Comment by Robyt3** [comment]
There should be no need to list all the error variants.

Suggestion: `Skin names must be valid filenames shorter than 24 characters.`

I plan to eventually add `str_valid_filename` to summarize the second part of this function and potentially exclude names like `con`, `nul` etc. (see also #3529)
