### ISSUE TITLE
`time_timestamp` is affected by the year 2038 problem

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#8303]
It currently returns the unix timestamp as an `int`, which will overflow in the year 2038:

https://github.com/ddnet/ddnet/blob/9336b4cb37fdbcaa647bc1670a42ab0e7527a1e6/src/base/system.cpp#L2616-L2619

See https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by Robyt3** [comment]
`time` returns a `time_t`, which seems like the correct type to use currently, but I think we have to wait for C++20 so we can use [`time_since_epoch`](https://en.cppreference.com/w/cpp/chrono/time_point/time_since_epoch), which returns a `duration` representing the time from the last epoch, but [did not return the time relative to specifically the UNIX Epoch prior to C++20](https://stackoverflow.com/a/14032877). In that case, we should use the type `duration` instead to represent durations when possible.

In particular, the ban-system currently stores timestamps as `int`s to represent ban durations, which will break in the year 2038. It also assumes that `time`/`time_timestamp` returns the number of seconds since the epoch's begin, which is implementation-defined behavior. Either we switch it to using `duration` or `int64_t` once we can use `time_since_epoch`.

Apart from the ban-system, the `time_timestamp` function is only used for setting the current start time of the Discord activity, which internally is already `int64_t`.

The `time` function is also used in other functions in `system.cpp` but only with `time_t` where the value is passed to other time functions, so I think those uses should be fine already unless we would want to support historical implementations that only use 32-bit `time_t` in the year 2038.

The `time` function can also return `(time_t)(-1)` on error, if the current value cannot be represented as `time_t`, which we de not check at the moment.

**Comment by heinrich5991** [comment]
Simply changing the return type and places where it's used to `int64_t` should work. Most systems today will have 64-bit `time_t`.

I wouldn't worry too much about the Unix epoch being implementation-defined behavior. I know of no implementation that doesn't define it as the 1970-00-00 00:00:00, and certainly none of our primary platforms: Android, (even iOS), Linux, macOS, Windows.
