### ISSUE TITLE
Integration test fails on `Error: near line 1: in prepare, database is locked (5)`

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#8325]
https://github.com/ddnet/ddnet/actions/runs/8980020413/job/24662999972?pr=8318
https://github.com/ddnet/ddnet/issues/8261#issuecomment-2081216658

```
[*] Shutting down client1
[*] Shutting down client2
Error: near line 1: in prepare, database is locked (5)
[-] Error: no ranks found in database
[!] Warning: ./stderr_client1.txt
```

**Comment by ChillerDragon** [comment]
I assume this error comes from the `sqlite3` cli command. Maybe retrying that operation fixes it but not sure how to properly test that.

```diff
diff --git a/scripts/integration_test.sh b/scripts/integration_test.sh
index 292862907..e4cfad160 100755
--- a/scripts/integration_test.sh
+++ b/scripts/integration_test.sh
@@ -314,7 +314,13 @@ then
        echo "[-] Error: demo playback of client demo in client 2 was not started/finished"
 fi
 
-ranks="$(sqlite3 ddnet-server.sqlite < <(echo "select * from record_race;"))"
+tries=0
+while ! ranks="$(sqlite3 ddnet-server.sqlite < <(echo "select * from record_race;"))"
+do
+       sleep 1
+       tries="$((tries+1))"
+       [ "$tries" -gt 3 ] && break
+done
 rank_time="$(echo "$ranks" | awk -F '|' '{ print "player:", $2, "time:", $4, "cps:", $6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28 }')"
 expected_times="\
 player: client2 time: 1020.98 cps: 0.02 0.1 0.2 0.26 0.32 600.36 600.42 600.46 600.5 1020.54 1020.58 1020.6 1020.64 1020.66 1020.7 1020.72 1020.76 1020.78 1020.8 1020.84 1020.86 1020.88 1020.9
```

**Comment by heinrich5991** [comment]
The `.timeout` command might help. Retrying sounds brittle.

**Comment by ChillerDragon** [comment]
> The `.timeout` command might help. Retrying sounds brittle.

I don't understand how timeout fits here. But yes we could make sure the server is shutdown correctly before trying to access the database. Maybe always sleep between sending the shutdown and querying the ranks.

**Comment by heinrich5991** [comment]
> I don't understand how timeout fits here.

The timeout enables waiting for a locked database (check its documentation).

> Maybe always sleep between sending the shutdown and querying the ranks.

That sounds brittle again, we could instead wait for the server process to shut down.

**Comment by ChillerDragon** [comment]
> The timeout enables waiting for a locked database (check its documentation).

Ah a sqlite3 command. I thought you mean `timeout(1)`

**Comment by heinrich5991** [comment]
> > The timeout enables waiting for a locked database (check its documentation).
> 
> Ah a sqlite3 command. I thought you mean `timeout(1)`

Sorry for the confusion, should have linked its documentation: https://sqlite.org/cli.html.
