### ISSUE TITLE
segfault on vulkan_backend.cpp : ClearFrameData

### ISSUE THREAD

**Issue by BlaiZephyr** [ddnet/ddnet#8328]
from discord:

i managed to crash the client by setting `cl_refresh_rate` and `gfx_refresh_rate` to 240 aswell as turning `Vsync` on

and then turning cl_refresh_rate and gfx_refresh_rate to 1000 and turning `Vsync` off

`12:58:16: /home/melonarch/Projects/ddnet/build/Desktop-Debug/DDNet ist abgestürzt.`

gdb outputted the following:

```
0x00005555556a04c0 in CCommandProcessorFragment_Vulkan::ClearFrameData (this=0x555555fb6660, FrameImageIndex=4) at /home/melonarch/Projects/ddnet/src/engine/client/backend/vulkan/backend_vulkan.cpp:2048
2048                if(BufferPair.m_pMappedData != nullptr)
```

OS: Arch Linux x86_64
WM: Hyprland (Wayland)

**Comment by Jupeyy** [comment]
Could you start with `dbg_gfx 3` and check if in the  log
the value for `minimal swap image count` changes when you toggle vsync?

**Comment by BlaiZephyr** [comment]
weird but i'm not able to reproduce it anymore ._. - i'll close this for now - thanks anyway jupsti
