### ISSUE TITLE
Visual bug on default hammer cursor

### ISSUE THREAD

**Issue by Ryozuki** [ddnet/ddnet#834]
You can check it here:
![Bug](https://image.prntscr.com/image/JOoZIQJkRZSKy7EblFykNw.png)

Notice a vertical line on the top right side of the cursor?

**Comment by def-** [comment]
Of course, noticed that since the first day of playing Teeworlds. I believe this is might be fixed in TW0.7, you could check. But adding the fix from TW0.7 would probably make all tiles look wrong since they ran through borderfix.

**Comment by Redix** [comment]
It seems like https://github.com/teeworlds/teeworlds/commit/8eaa040e3ed2a7a40fdb21eec284d85c2540505e fixes this. 
This commit has nothing to do with the borderfix-fix from TW 0.7 (using 3D textures), so it should not break anything.
Besides that, isn't borderfix only applied to tilesets?

**Comment by def-** [comment]
Thanks, true
