### ISSUE TITLE
sv_max_clients_per_ip 

### ISSUE THREAD

**Issue by trikiman** [ddnet/ddnet#8340]
i create a new map with non-standard-mechanic, it is funny but have one huge problem it is copy dummy. I need somehow turn this off.  i think best way it is sv_max_clients_per_ip set 1 i know it is possible to avoid with vpn and other stuff, but it is enough. 
![image](https://github.com/ddnet/ddnet/assets/39918652/518e9718-9c7f-4262-b830-224548364b13)
can u plz add this for map setting? like this vars 
![image](https://github.com/ddnet/ddnet/assets/39918652/c6d68ca3-3b68-4d02-a664-b79eceddf50e)

**Comment by ChillerDragon** [comment]
There is also https://github.com/ddnet/ddnet/pull/4358 which could be added as a config. It would disable the connect dummy button.

**Comment by trikiman** [comment]
> There is also #4358 which could be added as a config. It would disable the connect dummy button.
i see here some problem:
1 what about pplz who dont update client? they dont allow join to this map?
2  what about ppl who have diff client? they too dont allow? bacause they can summon dummy?
i think sv_max_clients_per_ip best way

**Comment by teini94** [comment]
but doesnt that also disable timeoout protection?
cause u cant join?
maybe sv_dummy 0 would be a good setting

**Comment by ChillerDragon** [comment]
Yea max clients per ip should be the strongest protection. Bypassing that seems harder than writing an aimbot.

Mapping a hard part for dummy players is making the map potentially annoying. Can be bypassed with /save to use a human for that part and still abuse copy moves in the others. Also these days dummy players can finish every part.

I am not fully sure what the implications are of allowing to set the server max clients from a map. Can users then flood trash map servers with 64 tees? Is that annoying to debug for server admins if changing the map can break dummies or allow flooding until the config is reverted again?

What is the treat model here? Is connecting dummy only discouraged or does it have to be avoided at all cost? If it is only discouraged then the 3 year old allow dummy feature should do the job.

**Comment by heinrich5991** [comment]
`sv_max_clients_per_ip` also disallows multiple players from the same household, I really dislike that.

---

About the feature itself, I'm skeptical of allowing mappers to disallow dummies. I have a sense that this might cause more and more players to disallow them, and DDNet allowing dummies is really nice for a) bootstrapping servers and b) people playing alone, because no one is there to play with them.

**Comment by trikiman** [comment]
> What is the treat model here? Is connecting dummy only discouraged or does it have to be avoided at all cost? If it is only discouraged then the 3 year old allow dummy feature should do the job.

copy dummy is cheat. do not think about the client with two ips, because it is very difficult to fix and people with it will be few, even if they do r1 on the map it is allowed(think of it as a big skip that's not available to most people.). Map is about having fun and a new experience. 

> bout the feature itself, I'm skeptical of allowing mappers to disallow dummies. I have a sense that this might cause more and more players to disallow them

I agree( it's same like teamforce, i really hate teamforce, the most fun I've ever had in a zero team. But for new type of map we need a new stuff. this is cost for progress. Аnd the testers can control it, the map needs it or not.

> `sv_max_clients_per_ip` also disallows multiple players from the same household, I really dislike that.

i really dont see any other ways to fix it. The ways talked about above have more cons.
sv_max_clients_per_ip have only two:
1 timeout
2 same household
i think it is not big cost for new fun map mechanic

**Comment by heinrich5991** [comment]
> copy dummy is legit cheat.

Copy dummy is not considered to be a cheat in DDNet, not even a "legit cheat".

**Comment by trikiman** [comment]
> > copy dummy is legit cheat.
> 
> Copy dummy is not considered to be a cheat in DDNet, not even a "legit cheat".

on my map it is.

**Comment by heinrich5991** [comment]
I don't think a map setting for disallowing dummies would fit DDNet. Hence, I'd like to not add such a feature.

**Comment by def-** [comment]
sv_max_clients_per_ip is not suitable to limit dummy anyway, since there are many households/dormitories/LAN parties where multiple players will have the same IP on DDNet servers.

**Comment by trikiman** [comment]
> sv_max_clients_per_ip is not suitable to limit dummy anyway, since there are many households/dormitories/LAN parties where multiple players will have the same IP on DDNet servers.

1 ye i know and it is enough.

2 idk if u have statistic or no but i think ppl who play in the same ip like 1% form all players. 

so we dont have cons
1 cus it is fine
2 not so much ppl
3 this map bring smth new.

**Comment by ChillerDragon** [comment]
> 2 idk if u have statistic or no but i think ppl who play in the same ip like 1% form all players.

I also don't think it is a lot. But teeworlds lan parties in schools I have seen multiple times. I also know a bunch of tw players living together. And it would be sad if the occasional lan party is excluded from playing a specific ddnet map.
