### ISSUE TITLE
Settings should be saved automatically when client is minimized on Android

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#8366]
Since there's no guarantee that the client will be quit normally on Android. See https://github.com/ddnet/ddnet/pull/8362#issuecomment-2110640447.

**Comment by heinrich5991** [comment]
We could probably also save the config every x minutes. Or every time it's changed.

Putting the config into an sqlite3 DB is probably a bad idea on non-Android, because you can't edit it with a text editor anymore?

**Comment by sjrc6** [comment]
I like being able to intentionally force quit the client in order to make the settings not save for testing.

**Comment by heinrich5991** [comment]
> I like being able to intentionally force quit the client in order to make the settings not save for testing.

I was mostly thinking about Android.

However, thinking about it more, "intentionally force quitting the client" is the same as "client crashing". For the user, it'd probably be better if the config was saved on client crash. Perhaps we could add a console command to stop saving the config at all, even on client quit? @sjrc6

**Comment by heinrich5991** [comment]
> This already exists, you can set `cl_save_settings 0` so the config will not be saved when quitting.

Oops, TIL. 😅

**Comment by sjrc6** [comment]
> This already exists, you can set cl_save_settings 0 so the config will not be saved when quitting.

oh thanks haha
