### ISSUE TITLE
Improving Automapper Randomness

### ISSUE THREAD

**Issue by gamertyp** [ddnet/ddnet#837]
How randomness in automaper rules currently work is that you set a number x and then every xth case the rule fits it will be applied. This number x is defined as integer.

Problem:
The highest possibilitys you can get are:
1 <-> 100%
2 <-> 50% (every second case)

There is no way to define a probability of e.g. 70% except copying the same rule multiple times. Thus it would be nice if you could also set a float, which then will be either interpreted as e.g. "every 1.5th case", or as pure probability value, such as 0.7 <-> 70%. I would suggest the latter.

Note:
Float values and integers should be handled seperatly then, so that old rules still work.

**Comment by bojidar-bg** [comment]
Just to explain what was implemented, in the next version, it should be possible to specify both legacy-style "every nth" as well as modern-style "x%". Some examples:
```
Random 2 # 1/2, 0.5 probability
Random 1.5 # 1/1.5, 0.66 probability
Random 10% # 10/100, 0.1 probability
Random 3.2% # 3.2/100, 0.032 probability
```
