### ISSUE TITLE
add kill immunity for /practice

### ISSUE THREAD

**Issue by teini94** [ddnet/ddnet#8376]
example:in /practice useing Dyn Cam and using /tc to teleport often results in ur teleporting very unprecise into a kill tile and then u  respawn + ur view resets. so u have to go all the way over again with ur view quite annoying

so I would add kill immunity atleast for 1-2frames, so u should be able to use /lasttp and still change ur postion with /tc

**Comment by BlaiZephyr** [comment]
this has been discussed in multiple issues and Pullrequests before - see #2239 #7691 #3024

**Comment by Robyt3** [comment]
Duplicate of #2232.
