### ISSUE TITLE
Test Str.StrToInts fails in ppc64le

### ISSUE THREAD

**Issue by rffontenelle** [ddnet/ddnet#8386]
Building ddnet 18.2 in Fedora Rawhide (next version 41) under architecture ppc64le, Str.StrToInts fails with the output below (-v added). 

The build runs for the 18.2 version update for all architectures can be found in: https://koji.fedoraproject.org/koji/taskinfo?taskID=117534623

A separate build with `run_tests` verbose is available in https://koji.fedoraproject.org/koji/taskinfo?taskID=117952804. Here is the full [build.log](https://github.com/ddnet/ddnet/files/15380255/build.log)

RPM spec file: [ddnet.spec](https://github.com/ddnet/ddnet/files/15380274/ddnet.spec.txt)
Pull request for updating version: https://src.fedoraproject.org/rpms/ddnet/pull-request/11

Relevant output:

> [  PASSED  ] 271 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Str.StrToInts
 1 FAILED TEST
2024-05-20 16:38:38 I sql: SQLite statement: INSERT OR IGNORE INTO record_race(	Map, Name, Timestamp, Time, Server, 	cp1, cp2, cp3, cp4, cp5, cp6, cp7, cp8, cp9, cp10, cp11, cp12, cp13, 	cp14, cp15, cp16, cp17, cp18, cp19, cp20, cp21, cp22, cp23, cp24, cp25, 	GameId, DDNet7) VALUES ('Kobra 3', 'nameless tee', DATETIME('2021-11-24 19:24:08', 'utc'), 100.00, 'USA', 	0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 	0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 	0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 	'8d300ecf-5873-4297-bee5-95668fdff320', 0)
FAILED: CMakeFiles/run_cxx_tests /builddir/build/BUILD/ddnet-18.2/redhat-linux-build/CMakeFiles/run_cxx_tests 
cd /builddir/build/BUILD/ddnet-18.2/redhat-linux-build && /builddir/build/BUILD/ddnet-18.2/redhat-linux-build/testrunner
ninja: build stopped: subcommand failed.
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.LK0FV4 (%check)
    Bad exit status from /var/tmp/rpm-tmp.LK0FV4 (%check)
Child return code was: 1
EXCEPTION: [Error('Command failed: \n # /usr/bin/systemd-nspawn -q -M 5774553938f54555a29bfecf0296e517 -D /var/lib/mock/f41-build-51113557-6097625/root -a -u mockbuild --capability=cap_ipc_lock --bind=/tmp/mock-resolv.6y8ykwoq:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/fuse --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin \'--setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007"\' \'--setenv=PS1=<mock-chroot> \\s-\\v\\$ \' --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c \'/usr/bin/rpmbuild -bb --noclean --target ppc64le --nodeps /builddir/build/SPECS/ddnet.spec\'\n', 1)]

**Comment by heinrich5991** [comment]
```
[ RUN      ] Str.StrToInts
/builddir/build/BUILD/ddnet-18.2/src/test/str.cpp:1118: Failure
Expected equality of these values:
  aInts[0]
    Which is: 1127695164
  0x4336433C
    Which is: 1127629628
/builddir/build/BUILD/ddnet-18.2/src/test/str.cpp:1122: Failure
Expected equality of these values:
  aInts[0]
    Which is: -514903197
  0xE14E3263
    Which is: 3779998307
/builddir/build/BUILD/ddnet-18.2/src/test/str.cpp:1123: Failure
Expected equality of these values:
  aInts[1]
    Which is: 17133855
  0x0104701F
    Which is: 17068063
/builddir/build/BUILD/ddnet-18.2/src/test/str.cpp:1124: Failure
Expected equality of these values:
  aInts[2]
    Which is: 286818304
  0x10188000
    Which is: 270041088
```

Looks like a real issue.
