### ISSUE TITLE
Question: Teeworlds physics

### ISSUE THREAD

**Issue by vuchastyi** [ddnet/ddnet#841]
First of all, I want say that I don't know English perfect, and I use translator.

I am a web developer and I want to create complete copy of teeworlds as a web application (I know that it already exists, but nobody plays it). That's all I can say for the full clarity of my question.

Question: what is TeeWorlds physics in the game? I tried to do my physics, but I realised that it was not quite like the TeeWorlds. Considering that I want to create a COPY of the game, I appeal to you.
I do not really understand c++ to take physics straight from the source. But for me this is not a problem, since I've dealt with c++

For those who still do not understand what I need. I need formulas similar to the following:
```js
var PS = .3; // player speed A & D
var PSF = .3; // speed with which player falls
var PSJ = .4; // speed with which player jump up
```
Yes, it's not like formulas, it's rather variables. But I think you have it all calculated as a formula. Can someone help me?

**Comment by vuchastyi** [comment]
Will not there be security holes in use web sockets? If so, why?

**Comment by def-** [comment]
I can't offer you anything other than the source code. Which can be quite confusing because the order of calculations changes them ever so slightly. Also, having the wrong kind of float numbers can already change the results

**Comment by vuchastyi** [comment]
Hmm ... Thanks for the answer, I'll try

**Comment by def-** [comment]
I think it's a bad idea. Basically you will end up reprogramming every single line. If you're doing it for fun, it's fine of course.

**Comment by vuchastyi** [comment]
No, no, no ... Deen, if I'm not mistaken. TeeWorlds - is my favorite game since 10 years, after a lot of time, I noticed that this game began to lose its popularity very much. I want to return the former (probably big) popularity to this game. Maybe I'm a freak, but this is my idea that I want to translate into reality. I know that this will take many years, but I think that this game should and will be popular. Thanks to the creator of the game, thanks to you (DDNet), maybe not much to me (although it's too early for conclusions).

**Comment by eeeee** [comment]
Not sure why do you think that having a web version would "return the former" (not that it was ever that big) popularity. But FWIW I'm working on a major upgrade to the existing teewebs.net web version which would leverage a few tricks (webrtc, system pointer, overprediction) to make the lag low enough to be playable.

**Comment by vuchastyi** [comment]
eeeee, when u'll finish your upgrade? It would be great(upgrade), cuz i can't even look at gameplay in teewebs.net

**Comment by eeeee** [comment]
There's a lot of complexity involved (especially in webrtc), so cannot promise anything.

**Comment by vuchastyi** [comment]
eeeee, okey, so i'll wait for your upgrade

**Comment by def-** [comment]
not a bug
