### ISSUE TITLE
(Server Browser) Trim Strings on Search/Exclude Filter & Add Tooltip

### ISSUE THREAD

**Issue by refeax** [ddnet/ddnet#8411]
For user friendliness, multiple strings in the search & exclude filters should be trimmed (for example if there's a space inbetween)

Also there should be a tooltip somewhere near the filters that shortly explains how to put in multiple filters and maybe also how to use it generally, for example "Example of usage: "novice; solo; multeasymap" etc".

**Comment by heinrich5991** [comment]
I agree that trimming would be nice.

Not sure if we need this to be discoverable. Perhaps in the tooltip?
