### ISSUE TITLE
map_resave tool issue

### ISSUE THREAD

**Issue by sctt** [ddnet/ddnet#843]
hello everyone,

i've got an issue with map_resave tool: i've compiled and run it, it seems to work but the result map is quite messy.
it is able to copy every layer and image correctly, but it doesn't seem to copy very well any of the tiles placed on layers, i see a random disorder of tiles on random positions, with random rotation, random tile id, everything concerning tiles it's just random.

is that behavior intended? i expected to see an exact copy of the source map, not just in images/layers, but also in tiles arrangement.

thank you in advance for you clarification.

**Comment by heinrich5991** [comment]
`map_resave` is broken, even for vanilla.

**Comment by heinrich5991** [comment]
If you want to re-save your map, open it in the editor and save it again.

**Comment by sctt** [comment]
thank you heinrich5991 for your fast reply.

nope, in reality i was trying to create a tool for replacing images inside a map and using map_resave as a base to operate.

i thought that reading all Items and Data with DataReader from the source map, changing the one i was interested into and than save everything again with DataWriter was enough... but it doesn't seem so.

do you know if there is a way to maintain tiles distribution during this process?

thank you again.

**Comment by heinrich5991** [comment]
That would be enough, but `map_resave` doesn't do it. I think it saved too long items and too short data or so (don't think `GetDataSize` returns the data size or that `GetItemSize` returns the item size, both is wrong IIRC).

**Comment by sctt** [comment]
oh i understand, so i will just look around to see if i can fix up the sizes problem.
thank you!

**Comment by def-** [comment]
If you can make it work, please make a PR!

**Comment by sctt** [comment]
made PR [#844](https://github.com/ddnet/ddnet/pull/844) to fix map_resave
