### ISSUE TITLE
"DDNet" tab name is translatable, while "Tee" is not

### ISSUE THREAD

**Issue by EGYT5453** [ddnet/ddnet#8436]
## While I was remaking Ukrainian translation, I found that you can translate DDNet settings tab name
![DDNet](https://github.com/ddnet/ddnet/assets/113429882/7402587d-c8d8-4a5b-9034-8eb76b82b355)
### And... well...
![DDNetTab](https://github.com/ddnet/ddnet/assets/113429882/8e359544-d60e-493c-8cba-94d44620a3e0)
(No, I won't add this to my translation, don't worry about that)

## Robyt3 on Discord also suggested this:
> It's not just the "DDNet" string itself, a bunch of other strings contain "DDNet", which should more correctly be untranslated and replaced with GAME_NAME to be more mod-friendly

> DDNet Client updated! -> %s Client updated! (with GAME_NAME) inserted as the placeholder

## Also, I suggest making Tee settings tab name (see picture below) translatable (or rather transliteratable).
![TeeTab](https://github.com/ddnet/ddnet/assets/113429882/7e5cf45d-aef0-433d-8f1a-a6c52f57573d)
It would make sense for Cyrilic alphabets, as the string "Tee" consists of letters that are both in Latin and Cyrilic alphabets. Instead, you can transliterate the string ("Ті" for Ukrainian and Belarusian, "Ти" for other Cyrilic Slavic languages, etc.). After all, we have "Dummy" string translatable/transliteratable, so why not have "Tee" too? It would also benefit other languages, not just Cyrilic ones.

**Comment by heinrich5991** [comment]
The client's name should still be translatable, I think.

We should probably rename the settings tab though, all of the settings are for the DDNet client, why is one tab called "DDNet"? ^^

**Comment by EGYT5453** [comment]
So rename the tab to "Client" :^)
Also, can you explain exactly why client's name should be translatable?

**Comment by heinrich5991** [comment]
> Also, can you explain exactly why client's name should be translatable?

Because it might get transcribed or changed in some languages.

**Comment by Robyt3** [comment]
It looks to me like the DDNet settings page contains various general settings that were added in the DDNet client as opposed to various general settings mostly from Teeworlds being shown on the General settings page. I think we could merge the General and DDNet settings as only General settings and add multiple horizontal tabs instead.

**Comment by EGYT5453** [comment]
I found a term used for "tee" in Ukrainian wiki: "тії" (https://wiki.ddnet.org/index.php?search=тії)
While I don't really like it, because it's pronounciation is not the same as "tee" (the pronounciation of "тії" is "tee-yee"), it is still bettter then "тее".

**Comment by EGYT5453** [comment]
So, if "Tee" tab is now translatable and "DDNet" one should **_stay_** translatable, I'm closing this issue
