### ISSUE TITLE
Some demo errors are untranslatable

### ISSUE THREAD

**Issue by EGYT5453** [ddnet/ddnet#8438]
For now I only found two errors that are not translatable:
![Empty demo](https://github.com/ddnet/ddnet/assets/113429882/6076d479-5898-486d-a747-a9fa6a54a8e9)
(There is also an "Ok" button that is also not translatable)
![Error reading demo header](https://github.com/ddnet/ddnet/assets/113429882/8e80dd9c-1b71-4675-9f09-06718d940c37)

**Comment by Robyt3** [comment]
I don't think translating the various internal demo error messages makes sense. It adds unnecessary work for translators and it doesn't really help non-technical users.

> (There is also an "Ok" button that is also not translatable)

See #8457.

**Comment by EGYT5453** [comment]
Okay then ¯\\_(ツ)\_/¯
