### ISSUE TITLE
Bug: Weird Control-Find Behavior in Console with Cyrillic Characters

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#8451]
Control find (CTRL+F, in the in-game console) seems to highlight more than it should when searching for strings with cyrillic characters.

Screenshot:
![DDNet_VNZVeQcRy2](https://github.com/ddnet/ddnet/assets/60477660/534bc565-e5a4-4381-8c0b-11a8e436607f)

**Comment by Learath2** [comment]
Q: Did the full string actually contain `так` twice or is the 2nd match completely a hallucination?

**Comment by murpii** [comment]
> Q: Did the full string actually contain `так` twice or is the 2nd match completely a hallucination?

The latter, that was the end of the string

**Comment by Learath2** [comment]
Ah not a complete hallucination, there is another `так` in the middle that I didn't spot. It counts matches properly, but marks them wrong, I'll dig into it a bit

**Comment by Robyt3** [comment]
Fixed by #8454.
