### ISSUE TITLE
Don't send mouse target in zoomed state

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#8452]
![image](https://github.com/ddnet/ddnet/assets/35420825/49ca8c24-0630-4f6b-a2bc-99f8245b47a9)

Precision has been changed due to this.
We should revert this change where the mouse position gets sent in a zoomed state.

A fix would be to keep the normal mouse pos for everything physics related and either send required values such as follow factor, deadzone etc so the server can create the real position (also for dyncam, as that's currently not working correctly and gives wrong positions), OR send the zoomed position directly aswell. That's 2 32-bit integers though.

**Comment by sjrc6** [comment]
A proper fix would be to send the zoom float along with NETMSGTYPE_CL_SHOWDISTANCE then the server can get the exact same values that it gets now with a simple multiply. The size of the ints was only a concern in the context of resending multiple inputs per tick, you don't need to worry about that.

**Comment by heinrich5991** [comment]
> Precision has been changed due to this.

Can you give an example of this? This should be preventable.

> We should revert this change where the mouse position gets sent in a zoomed state.

The idea is that the server knows where the player points.

**Comment by sjrc6** [comment]
> > Precision has been changed due to this.
> 
> Can you give an example of this? This should be preventable.

Clients who play on a smaller zoom level will have their integer mouse positions scaled down to the world space rectangle of their screen, but there's less integer positions in this smaller rectangle so they lose precision by the scale factor.

**Comment by fokkonaut** [comment]
> > We should revert this change where the mouse position gets sent in a zoomed state.

> The idea is that the server knows where the player points.

Yes, and thats good, but https://github.com/ddnet/ddnet/issues/8452#issuecomment-2149249448

**Comment by fokkonaut** [comment]
Reminder: this get's really annoying
