### ISSUE TITLE
Team size in Scoreboard 

### ISSUE THREAD

**Issue by marcel-tw** [ddnet/ddnet#8496]
Small team size number for every team size > 1.
![1](https://github.com/ddnet/ddnet/assets/153835808/8fc21d30-cd42-4721-9cc7-0c3e3616c425)

**Comment by heinrich5991** [comment]
From the PR: What's the use case for this?

**Comment by murpii** [comment]
> From the PR: What's the use case for this?

To see if a larger team is even or uneven. That'd be my use-case.

**Comment by heinrich5991** [comment]
I think I'd vote against adding another number in the scoreboard which is already full of information, to check whether a larger team has an odd or an even number of players.

**Comment by archimede67** [comment]
> I think I'd vote against adding another number in the scoreboard which is already full of information, to check whether a larger team has an odd or an even number of players.

You may vote against but many regular players requested this feature, and while you might find it useless because of not playing the game that much, other players that play the game on a daily basis find it helpful (thus this feature request).

I still believe we should have a way to display the team size in scoreboard, but make it distinct and understandable.

**Comment by heinrich5991** [comment]
> while you might find it useless because of not playing the game that much

You can discuss based on merits, but this is not it. Please don't do that.

**Comment by heinrich5991** [comment]
No, I don't think it's fair to gatekeep people's opinions because they play too bad, or too little.

**Comment by BlaiZephyr** [comment]
i'd like to agree with murpi's usecase and archimede's feelings about this feature. It has been requested by a lot of people on discord and ingame. Many custom community clients (e.g T-Client, StA-Client) already have that feature and (after agreeing on a proper way of displaying it) wont bloat up the scoreboard to a point of disrupting readability imo. Of course you could go around and tell people to learn how to count, but this is a way of displaying information that many people want and agree on belonging into the scoreboard.

**Comment by archimede67** [comment]
> No, I don't think it's fair to gatekeep people's opinions because they play too bad, or too little.

I am not gatekeeping anyone's opinion. I am just stating that if you would play the same amount as the people who requested this feature, you would understand the use case for it.

**Comment by heinrich5991** [comment]
> I am just stating that if you would play the same amount as the people who requested this feature, you would understand the use case for it.

Yes, please skip that part. It's not nice.

**Comment by heinrich5991** [comment]
I've edited your original comment to skip the off-topic part and marked everything else as off-topic.

**Comment by archimede67** [comment]
> I've edited your original comment to skip the off-topic part and marked everything else as off-topic.

Now you are gate-keeping my opinion ? Please skip that too then.

**Comment by archimede67** [comment]
> Yes, please skip that part. It's not nice.

Those are just facts.

**Comment by furo321** [comment]
I think listing it in the scoreboard seems a bit out of place, and overall just confusing. I think it would be best to have it only say the amount of players with `/team`.
