### ISSUE TITLE
Provide ability to configure custom VPN ban messages via server setting

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#8518]
The default ban message is completely unhelpful. "Contact admin if mistaken" is too vague and lacks explanation. How should I know who the admin is?

**Comment by furo321** [comment]
A ban reason has a max size of 63 characters, which `VPN detected, try connecting without. Contact admin if mistaken` fits exactly into. But it might be possible to increase.

https://github.com/ddnet/ddnet/blob/248a24845e2b4450ead84cafe7ee68318fe86b0f/src/engine/shared/netban.h#L80

**Comment by jxsl13** [comment]
That's how I do it:

`VPN - https://zcat.ch/bans/`
