### ISSUE TITLE
Connect to ddnet servers with set password using custom browser protocol

### ISSUE THREAD

**Issue by MilkeeyCat** [ddnet/ddnet#8525]
It would be nice if there're was a way to connect to ddnet servers which have set password using `ddnet://` link. I don't know If anyone has a use case for it but I do xd.

**Comment by murpii** [comment]
XY Problem?

If you want to restrict access to your server and only let people connect through a special link, you might as well not register the server on the master list and remove the password. What’s the purpose of having a password if you're going to provide a direct way to bypass it and connect immediately?

**Comment by MilkeeyCat** [comment]
For example I have N game servers and I want to let certain people join the
server at a certain time but if some people happened to visit all the
servers, they would be able to connect to any server whenever they want.

**Comment by Robyt3** [comment]
Maybe you could solve that with an external whitelist? Have the players visit a website where they enter a password.

**Comment by MilkeeyCat** [comment]
Yea, I guess it will also work
