### ISSUE TITLE
Blacklist for skins

### ISSUE THREAD

**Issue by gerdoe-jr** [ddnet/ddnet#8532]
As pointed out in Discord conversation, you may be not interested in seeing some kind of skins. Kind of regex based list for all type of skins will fit, I guess

**Comment by def-** [comment]
If you copy default.png to alien_tee.png, your client won't download the actual alien_tee.png and show you default.png instead. No need for client modification.

**Comment by Robyt3** [comment]
The majority of skins in official databases should be acceptable for almost all players, else this would be the primary issue that need to be addressed.

This feature is too niche and an easy workaround is available, which also doesn't require players to learn regex. When you follow the workaround, make sure you copy the `default.png` into the `skins` folder in your config directory and not in the `data` folder, or the change may be lost on updates.
