### ISSUE TITLE
RFC: Android CI

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#8550]
I think it would be useful to add CI for the Android build, so we notice when it breaks in the future. It would also allow building and uploading the APK as an artifact.

This would require adding the precompiled libraries for Android to https://github.com/ddnet/ddnet-libs, as building the libraries would take too long to do it every time in the CI. The downside would be that this would increase the size of the ddnet-libs repository from around 228 MiB to around 400 MiB.

Another important point is that the CI would automatically have to accept the [Android SDK license](https://developer.android.com/studio/terms) on behalf of the CI user, as the Gradle build is otherwise not usable. That should not happen for forks without the consent of the owner though. Maybe there's a way to require the owner of each fork to accept the license by setting a specific secret/environment variable in their fork's repository settings, so the Android CI will terminate immediately with neutral result if this flag is not set (for example a property `ANDROID_SDK_LICENSE_ACCEPTED` which would have to be set to exactly the value `I accept the Android SDK license: https://developer.android.com/studio/terms`).

**Comment by heinrich5991** [comment]
I'm definitely in favor of an Android CI.

> The downside would be that this would increase the size of the ddnet-libs repository from around 228 MiB to around 400 MiB.

Maybe 400 MiB is okay. If not, we could split it off into ddnet-android-libs.

**Comment by def-** [comment]
400 MB is ok

**Comment by Robyt3** [comment]
@def- Do you want to build the libraries for Android (and eventually also the app) on your machine, or should I do that?

We should also update the libraries (SDL for Windows at least) for the next release, as there have been multiple reports of controller-related crashes and memory leaks that would be fixed by updating to the latest SDL version.

**Comment by def-** [comment]
I'd prefer a reproducible way to build it, like a Docker file using an Arch Linux base, to make sure it's easy to rebuild.

**Comment by Robyt3** [comment]
> I feel like the DDNet apk is already useful enough that we should start releasing it on DDNet.org properly (even if we call it a beta). @Robyt3 Is it possible for me to build it myself easily?

(moving the build related discussion from https://github.com/ddnet/ddnet/issues/9177#issuecomment-2461611792)

@def- See https://github.com/ddnet/ddnet/tree/50d8dfeb6a2134f3febd29d9d63547f1a63e5ab1/scripts/android for the building instructions. Should be relatively easy on Linux. I only tested in an Ubuntu VM but I assume it should mostly work on other Linux systems except for installing the packages.

After the setup, the next step would be to build the libraries and add those to ddnet-libs, which would only have to be done infrequently like usual for the libraries.

If #8632 is not yet merged into master you'll want to merge that PR manually into the version branch that you are building.

The build script will read the current version from `version.h`, so if you are overriding the name with a CMake variable etc. then you also need to e.g. `export TW_VERSION_NAME=DDNet-18.7-20241101` before running the build script to set the version for the APK.

I'm not sure if we want to build 1 APK (ARM+ARM64+x86+x64), 2 APKs (ARM+ARM64 and x86+x64) or 4 APKs (ARM, ARM64, x86, x64). I was previously building 2 APKs mostly because 1 large APK was above the size limit for Discord uploads, but I guess only 1 APK would be the easiest to use. In any case, I recommend using a different build folder for every APK that you end up building and also clear the build folder before building if you add/remove arches. If you want to build only 2 arches per APK then you need to run the build script twice (without clearing the build folder inbetween).

I've previously been building with a debug signing key only. Instructions for generating a release signing key are in the README, though I've never tested them I think.

**Comment by def-** [comment]
I'll implement the Android CI now
