### ISSUE TITLE
Potentional client redirect would not drop client in this state

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#8551]
https://github.com/ddnet/ddnet/blob/9db780ebbce53c3ac420fcb6df099b63ecc351b3/src/engine/server/server.cpp#L2976-L2986

The loop would break and other clients wouldnt be checked anymore

**Comment by Robyt3** [comment]
The `CNetServer::Drop` function will call the delete-client callback function (`CServer::DelClientCallback`) which should set the client state to `CClient::STATE_EMPTY` again before the check, so this seems correct.

**Comment by heinrich5991** [comment]
The problem is that the whole loop is getting broken out of if one of the clients is nonempty. This means that further clients will not get checked for `STATE_REDIRECTED`.
