### ISSUE TITLE
Client Redirect: Send Pong back when successfully received Redirect msg

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#8552]
Currently we just hope the client disconnects properly and drop the client after 10 seconds.
The client should send back a pong when it received the packet, to let the server know when to drop the client safely after the packet has been arrived.
I've tried to implement redirect feature on F-Client, but it seems like some underlying code is broken, which let's 0.7 clients disconnect poorly, and sometimes they just don't tell the server they have exited. This, plus the main reason it was made like that by @ChillerDragon was to prevent clients from being disconnect before receiving the packet, e.g. if their resend queue was too large or whatever.

https://github.com/fokkonaut/F-Client/commit/69a6038430a43802d3090f89716f62517747c5d0
https://github.com/fokkonaut/F-Client/commit/1ed429c90d91d03d4a32624377acc9bd3bb36bf2

**Comment by heinrich5991** [comment]
> Currently we just hope the client disconnects properly and drop the client after 10 seconds.

This is similar to how we handle disconnects (even a bit more graceful). Why is that a problem for redirects? Can you provide pcps?

**Comment by ChillerDragon** [comment]
The pong is basically the clients disconnect packet. We could mark it with a custom reason. Such as "redirected" to let the server know the client did not leave on its own.

**Comment by fokkonaut** [comment]
Not needed anymore, killing the character is just missing in ddnet (call to `CCharacter::Die()`)
Thats required so the tee is really gone, and it won't respawn since `CPlayer::Tick()` is not executed when `!CServer::ClientIngame()`, which is the case when state is `CServer::CClient::STATE_REDIRECTED`

**Comment by fokkonaut** [comment]
So the caller of `RedirectClient()` has to handle killing the tee
