### ISSUE TITLE
"Show messages from friends/team members" should stack

### ISSUE THREAD

**Issue by Anime-pdf** [ddnet/ddnet#8570]
If you set `cl_show_chat_friends 1` it shows messages from friends. `cl_show_chat_team_members_only 1` - team members only. If you set them both, you won't see any messages, would be nice if they showed both.
![friends](https://github.com/ddnet/ddnet/assets/55580385/73dff21f-5377-4a78-9cdf-a4d502be2851)
![team members](https://github.com/ddnet/ddnet/assets/55580385/d5e73cd3-4734-416b-b555-5d49c5ae5f01)
![both](https://github.com/ddnet/ddnet/assets/55580385/8202283c-6f63-4bed-b32c-bb322a25641c)

**Comment by heinrich5991** [comment]
They stack, but they'll only show chat messages that are both from friends **and** from your team.

**Comment by Anime-pdf** [comment]
That's fair, not very useful, but not worth changing ig
