### ISSUE TITLE
Game crashes after firing certain weapon

### ISSUE THREAD

**Issue by Milopab193** [ddnet/ddnet#8579]
Происходит краш игры после выстрела из определëнного оружия
===

Подскажите с чем связан краш игры, после выстрела из определëнного оружия игра зависает на пару секунд и вылетает, буду рад помощи

**Comment by def-** [comment]
Can you upload the crash dump from dumps directory?

**Comment by BlaiZephyr** [comment]
Please keep issues in english

**Comment by Robyt3** [comment]
See #8580.
