### ISSUE TITLE
Add an option to disable "auto close menu on call vote"

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#8586]

**Comment by heinrich5991** [comment]
Please add a motivation to your feature request.

**Comment by Anime-pdf** [comment]
There is actually an option, it's `ui_close_window_after_changing_setting 1/0`

Ref: https://github.com/ddnet/ddnet/issues/813

**Comment by fokkonaut** [comment]
> Please add a motivation to your feature request.

https://github.com/ddnet/ddnet/issues/813#issuecomment-1308432378

**Comment by heinrich5991** [comment]
Duplicate #813. Please include the motivation in the issue text next time.
