### ISSUE TITLE
Bullets and Plasma Turrets ignore teams

### ISSUE THREAD

**Issue by 12pm** [ddnet/ddnet#859]
Only the player that has "weak" (aka. that spawned last) gets affected by bullets/plasma turrets (gametile 220-225) in certain areas. Even if someone else is in a different team at the same spot, they don't trigger the gametile.
This can be abused to cheat parts or for trolling purposes (eg. blocking a bullet). It also limits solo maps since solo server handles each player like they are in a seperate team.

Should be fixed so that these bullets and plasma turrets work like switches. Preferably this would be fixed for solo parts as well.

**Comment by def-** [comment]
Unfortunately the code is quite messy and difficult/impossible to fix without changing behaviour.

**Comment by 12pm** [comment]
seems fixed :)
