### ISSUE TITLE
QoL: Make left-click track the most centered player in free-view spectating

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#8590]
and perhaps right-click to go back to free view?

**Comment by gerdoe-jr** [comment]
`bind mouse1 "+fire; spectate_closest"` and `bind mouse2 "+hook; spectate -1"`

**Comment by murpii** [comment]
> `bind mouse1 "+fire; spectate_closest"` and `bind mouse2 "+hook; spectate -1"`

Thanks, but this is supposed to be a QoL feature, not something a player needs to be bind.

**Comment by gerdoe-jr** [comment]
What exactly do you want to add if it's already possible with current implementation?

**Comment by BlaiZephyr** [comment]
making it default behaviour when in spectator-view would work

**Comment by murpii** [comment]
Yes, it should be set up that way by default.
