### ISSUE TITLE
Incorrect text alignment of movement information

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#8622]
Reported by RedRay32 on Discord:

![image](https://github.com/user-attachments/assets/3906ac3f-6295-4814-a0a8-321251d016f8)

The text appears to be misaligned at precise values like 10.00 and 100.00.

The text alignment code in `CHud::RenderMovementInformation` looks really weird. Should use text containers to render these texts and calculate the text width, which would also be more efficient.

**Comment by MilkeeyCat** [comment]
Hi, could you tell more pls about how should the text width be calculated?

**Comment by Robyt3** [comment]
`CHud::GetDigitsIndex` and the `s_TextWidth*` constants should be removed. The text widths (variables `w`) should be calculated with `TextWidth(FontSize, aBuf)`. That should already fix the alignment of the values. Using `TextWidth` basically renders the text again but invisible to determine the width, so it's likely less efficient than the old `CHud::GetDigitsIndex` based alignment.

Using a text container is more efficient, as the text is only layed out when it's changed instead of every time that it's rendered. Search for `TextContainer` in `infomessages.cpp/h` to find example usages. For example the width of a text container is returned with `TextRender()->GetBoundingBoxTextContainer(InfoMsg.m_TextContainerIndex).m_W`, which is very cheap as the text container caches the size of the bounding box.

I'd first start by replacing only one of the `TextRender->Text` calls with a text container. Once that works, consider how much duplicate code it would add if applied to all labels and probably try to extract it into a function first. The labels `X:` and `Y:` are rendered twice so you could probably use the same two text containers for those.

**Comment by MilkeeyCat** [comment]
I tried to add text container to player angle text https://github.com/MilkeeyCat/ddnet/commit/1d9d5b1ba59c9045d17ddd803982ddfa900dff46, is that right?

**Comment by Robyt3** [comment]
> I tried to add text container to player angle text [MilkeeyCat@1d9d5b1](https://github.com/MilkeeyCat/ddnet/commit/1d9d5b1ba59c9045d17ddd803982ddfa900dff46), is that right?

I commented on the commit.

**Comment by MilkeeyCat** [comment]
https://github.com/MilkeeyCat/ddnet/commit/36a9feb1bc6d56f7b8d48a6e23b9191ccfcec9cf is that better? :D

**Comment by Robyt3** [comment]
> [MilkeeyCat@36a9feb](https://github.com/MilkeeyCat/ddnet/commit/36a9feb1bc6d56f7b8d48a6e23b9191ccfcec9cf) is that better? :D

Yeah, looks good. Next try to apply that to the other labels while avoiding duplicate code.

**Comment by MilkeeyCat** [comment]
What do you think about dis https://github.com/MilkeeyCat/ddnet/commit/8df8b4c4cced698ac55ee05959709a6e267959aa

**Comment by Robyt3** [comment]
> What do you think about dis [MilkeeyCat@8df8b4c](https://github.com/MilkeeyCat/ddnet/commit/8df8b4c4cced698ac55ee05959709a6e267959aa)

Commented. Looks good after those comments are addressed.
