### ISSUE TITLE
VPN ban shouldn't say "banned for 10 minutes"

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#8647]
The "for 10 minutes" is confusing because the ban will just be reapplied afterwards.

**Comment by murpii** [comment]
From me:
> Hmmm, it's a useful for people to know when they can attempt to rejoin after they've been whitelisted, because I don't normally remove the ban

From Heinrich:
> maybe we can shorten the ban to 1 minute for this?

**Comment by def-** [comment]
> Hmmm, it's a useful for people to know when they can attempt to rejoin after they've been whitelisted, because I don't normally remove the ban

Then let's also remove the bans, that sounds better. How about we remove all DNSBL bans once we updated vpn_whitelist?

**Comment by murpii** [comment]
> > Hmmm, it's a useful for people to know when they can attempt to rejoin after they've been whitelisted, because I don't normally remove the ban
> 
> Then let's also remove the bans, that sounds better. How about we remove all DNSBL bans once we updated vpn_whitelist?

Is there an easy way to differentiate DNSBL bans from regular bans?

**Comment by def-** [comment]
Only based on text at the moment
