### ISSUE TITLE
fix /tc with dyn

### ISSUE THREAD

**Issue by teini94** [ddnet/ddnet#8666]
back in the dayz /tc and dyn worked nearly perfect even with longer distance

then heinrich wanted it change cause different mousemode?? or something
now its very annoying always teleporting 2 far or 2 low (and get killed cause into kill and then ur stuck in kill etc)

so if there is a real "mousemode" we can like use "tc mode 1 or 2 or something) so its good again

**Comment by heinrich5991** [comment]
Should just get fixed for dyncam, no need for two modes.

**Comment by furo321** [comment]
Huh, I don't think `/tc` ever worked with dynamic cam.
