### ISSUE TITLE
Add cmd to turn off particles like `cl_nameplates` but `cl_particles`

### ISSUE THREAD

**Issue by CovERUshKA** [ddnet/ddnet#8672]
I'm training a neural network and recording a server demo that includes all 64 bots at once and there is too much of particles on it so I cant see a thing. So I want to remove particles to see more.
![image](https://github.com/user-attachments/assets/b0e55824-6f88-4b7f-bdd6-2f100c3a2e54)

**Comment by heinrich5991** [comment]
This seems like a one-off thing. It doesn't really make sense to me to make that a option for everyone. It'd complicate server mods and confuse people who accidentally turn it on.

Do you need help with building DDNet yourself? I can probably find the one code line you need to change.

**Comment by CovERUshKA** [comment]
Then why there is `cl_nameplates` cmd? Seems the same. No?

I would consider changing `particles.png` file instead of rebuilding.

**Comment by CovERUshKA** [comment]
> > I would consider changing `particles.png` file instead of rebuilding.
> 
> Sounds like a good idea to achieve what you want to have.

It think it would be better if I had a cmd to turn them off

**Comment by heinrich5991** [comment]
What benefit does the command add, here?

**Comment by CovERUshKA** [comment]
> What benefit does the command add, here?

I think you're joking, but I'll answer anyway.

My path to turn off particles:
1) Create empty png
2) Replace original png with empty
3) Reopen the game
Time needed: ~5 min

Path with cmd:
1) Open console
2) Write `cl_particles 0`
Time needed: ~3 sec

**Comment by heinrich5991** [comment]
I see. Since I consider the use case to be niche, I think the 3 added minutes are an okay tradeoff for not implementing another customization option.

**Comment by Robyt3** [comment]
You can add a separate `transparent.png` to the folder `assets/particles` in your config directory. Then switch to this texture using `cl_asset_particles transparent` when you need it.

**Comment by CovERUshKA** [comment]
> You can add a separate `transparent.png` to the folder `assets/particles` in your config directory. Then switch to this texture using `cl_asset_particles transparent` when you need it.

It would be really easier. But why you don't want to implement it like `cl_nameplates` and other cmds I don't understand. Anyway, thank you for everything

**Comment by furo321** [comment]
Related PR #7242 which added transparent assets
