### ISSUE TITLE
Binds do not work correctly when using composite keys

### ISSUE THREAD

**Issue by archimede67** [ddnet/ddnet#8677]
When using composite keys to bind a movement command (or maybe a `+command` in general) which is used in a command bound to another key, the bind actually applies to the existing key instead of the composite bind.

Example where it affects the existing key:
![DDNet_euKjUrtwWO](https://github.com/user-attachments/assets/932fa267-0f05-4073-8d6a-6d644811a31d)

Example where it does not:
![image](https://github.com/user-attachments/assets/51800686-ed91-4adf-90ee-339ac25f2099)

**Comment by Robyt3** [comment]
See #8314.
