### ISSUE TITLE
'Go forward one tick' in demo view actually seeks by 2 ticks forward

### ISSUE THREAD

**Issue by Kaffeine** [ddnet/ddnet#8678]
Observation: there are 25 'Go forward one tick' clicks per in-game race timer second, and I'd expect to see 50 ticks (split moments) per second.
Maybe the recorder writes every second tick e.g. to save disk space?

**Comment by heinrich5991** [comment]
The client only writes snapshots received by the server. By default, the server only sends snapshots every second tick.

**Comment by Teero888** [comment]
The server only sends snaps at 25 ticks per second to save bandwidth. Everything else is interpolated. That's why demos are only recorded at 25tps. You can set sv_high_bandwidth to 1 to achieve 50 tps in demos on a local server.

**Comment by Kaffeine** [comment]
Thank you.
