### ISSUE TITLE
"Name" string can't be translated correctly

### ISSUE THREAD

**Issue by EGYT5453** [ddnet/ddnet#8679]
In Ukrainian and other Slavic languages, we have two words for "name", "ім'я" for personal names and "назва" for proper nouns (for example, Andrew is "ім'я", and DDNet is "назва"). Because server browser uses the same string as everything else, it is impossible to translate the string "Name" to these languages correctly.

**Comment by MilkeeyCat** [comment]
#8434?

**Comment by Robyt3** [comment]
Duplicate of #8434.

**Comment by EGYT5453** [comment]
Whoops, forgot about that one
