### ISSUE TITLE
Team count wrong

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#8681]
From [Discord](https://discord.com/channels/252358080522747904/757720336274948198/1269636434403397673):
> [2:41 PM]xteriche: why 6?
> ![image](https://github.com/user-attachments/assets/ab107021-5b9b-4f67-a5a3-6c6e124db71f)
> [2:42 PM]xteriche: if you count there are 8 of us
> [3:13 PM]RedRay32: does he count on one side only?

**Comment by def-** [comment]
@archimede67
