### ISSUE TITLE
Server info should be created with `CJsonStringWriter`

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#8684]
https://github.com/ddnet/ddnet/blob/00d941a3094568535bde921855501a77224162ad/src/engine/server/server.cpp#L2326-L2332

Should use `CJsonStringWriter` instead of `str_format` to create the json object. The fixed size `16384` buffer can be replaced with an `std::string` as well to remove the arbitrary size limitation.

CC #8542 which increases the size to `32768`, which would not be necessary then.

**Comment by heinrich5991** [comment]
Note that the serverinfo also has a length limit on the masterserver side.
