### ISSUE TITLE
Tuning variable `ground_control_speed` not working for small values

### ISSUE THREAD

**Issue by AssassinTee** [ddnet/ddnet#8688]
Ground control speed is not properly working for small speed values, I tested this out and it looks like a value of < 0.4 causes the tee not to move at all. A value between 0.9 and 0.5 causes the Tee only to move RIGHT on the ground. I attached a testmap

![screenshot_2024-08-06_13-13-15](https://github.com/user-attachments/assets/4d886374-f637-42e8-892d-8af654969cca)

[small_speed_bug.zip](https://github.com/user-attachments/files/16509448/small_speed_bug.zip)

**Comment by def-** [comment]
That's probably just because of float calculations? Very low chance we'll change that since it would affect physics.

**Comment by heinrich5991** [comment]
Probably rather because of the explicit rounding we do to all of the values of a character. But still, unlikely that we'll change anything there.

**Comment by heinrich5991** [comment]
Unlikely to change. Don't build a map around this. ^^

**Comment by AssassinTee** [comment]
@heinrich5991 can you label this with `wont fix`? Since this will never be fixed but is still a bug
