### ISSUE TITLE
[Sixup] Chat line bug

### ISSUE THREAD

**Issue by Bamcane** [ddnet/ddnet#8731]
I'm using Nightly-build version on my Arch Linux x64.
I found the sixup support on client cause a bug:

First to join a 0.7 server to received some messages from 0.7 players.
This step will keep a 0.7 skin on your chat line.

Next, join a 0.6 server.
And you will found that 0.7 skins in last server was displayed wrongly on chat line.
That means, you will see the chat from a 0.6 player who has skin that from 0.7.
Maybe he even was displayed with your 0.7 skin on chat line.

**Comment by def-** [comment]
@ChillerDragon
