### ISSUE TITLE
0.7 dm7 has some floating tiles

### ISSUE THREAD

**Issue by M0REKZ** [ddnet/ddnet#8747]
DDNet 0.7
![gg](https://github.com/user-attachments/assets/da593d0a-1abe-43c7-b6da-9bebab6410be)

Teeworlds 0.7
<img width="897" alt="ee" src="https://github.com/user-attachments/assets/ed8a4d49-6191-47c0-8349-6baae2b16db8">

**Comment by ChillerDragon** [comment]
Looks like a bug in the official map. But yea we should be able to work around that. I will have a look.

![image](https://github.com/user-attachments/assets/c8776d28-d85e-446e-b633-975b7593691d)

**Comment by ChillerDragon** [comment]
Okay so [in 2015 ddnet extended](https://github.com/ddnet/ddnet/commit/929919d44ba05a913030c556a28f6fd96d84b6e7#diff-d3cf443ce462f6e0cf9543319e40497f2c93505528a40cb7d923781643094f99) the grass_main_0.7.png with custom ddnet only tiles. So it is no longer compatible with the [teeworlds 0.7 version](https://github.com/teeworlds/teeworlds/blob/c56fa9e6a20cfc9d7d16502e18c7d7633acdf492/datasrc/mapres/grass_main.png).

So the name grass_main_0.7.png does not make too much sense anymore. Its more like grass_main_ddnet.png. That paired with the official teeworlds map having placed the unused index 177 causes the graphic glitch.

@maintainers can we get some executive decision here on how to approach this? I would propose something like renaming the grass_main_0.7.png to grass_main_ddnet.png (which requires automapper updates i think) and then adding the new file grass_main_0.7.png which is the actual teeworlds grass_main.png from 0.7.

**Comment by def-** [comment]
> https://github.com/maintainers can we get some executive decision here on how to approach this? I would propose something like renaming the grass_main_0.7.png to grass_main_ddnet.png (which requires automapper updates i think) and then adding the new file grass_main_0.7.png which is the actual teeworlds grass_main.png from 0.7.

ok

**Comment by heinrich5991** [comment]
Does any map actually use `grass_main_0.7`? Maybe we can simply remove our extra tiles?

**Comment by heinrich5991** [comment]
> I would propose something like renaming the grass_main_0.7.png to grass_main_ddnet.png

That doesn't work if anything uses the `grass_main_0.7`. I'd hope no one uses it.

**Comment by ChillerDragon** [comment]
> > I would propose something like renaming the grass_main_0.7.png to grass_main_ddnet.png
> 
> That doesn't work if anything uses the `grass_main_0.7`. I'd hope no one uses it.

by "doesn't work" you mean if its not embedded its displayed wrong? If non vanilla mapres are not embedded that is a map bug anyways and they would display wrong in the vanilla client. But all serious maps have it embedded so a rename would not break the maps.

**Comment by heinrich5991** [comment]
> by "doesn't work" you mean if its not embedded its displayed wrong?

Yes.

> If non vanilla mapres are not embedded […] they would display wrong in the vanilla client.

Yes, but displayed correctly in the DDNet client.

> But all serious maps have it embedded so a rename would not break the maps.

If that is the case, I don't see why we should keep our version at all.

**Comment by ChillerDragon** [comment]
> If that is the case, I don't see why we should keep our version at all.

I don't have the exact stats. Its just from what I remember from my kog map testing times. The modern ddnet client auto embedds anyways but before that there might have been a few maps slipped through where nobody noticed the bug because the ddnet client market share is so high. I assume at most a few kog maps are affected but it always has been a clear bug and the maps can still be easily fixed now.

I think the reason for keeping the ddnet version would be the same like for all custom mapres ddnet added. Someone thought it would be nice to have in the client.

**Comment by heinrich5991** [comment]
> I assume at most a few kog maps are affected but it always has been a clear bug and the maps can still be easily fixed now.

It'd be nice if someone could run the numbers here before we make incompatible changes. E.g. check all current KoG and DDNet maps.

**Comment by ChillerDragon** [comment]
> It'd be nice if someone could run the numbers here before we make incompatible changes. E.g. check all current KoG and DDNet maps.

Are you only concerned about kog and ddnet? If so why? Both kog and ddnet are still actively maintained the affected maps could be fixed.

**Comment by heinrich5991** [comment]
You're welcome to run it against my whole map archive, but I thought that only KoG and DDNet would be easier.

> Both kog and ddnet are still actively maintained the affected maps could be fixed.

Only if someone notifies them.
