### ISSUE TITLE
Demo cutting broken

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#8748]
Fussel reported that on newest nightly, demo cutting appears to be broken.

https://github.com/user-attachments/assets/690c9db1-e9cd-4d15-9ffe-19dc89cccc4c

Other demos:
[demos.zip](https://github.com/user-attachments/files/16638031/demos.zip)
geht.demo is before cutting, futsch.demo afterwards. Note that the demo's size decreases even though nothing was cut out.

**Comment by murpii** [comment]
That's not the only thing that's broken, try viewing this demo, recorded yesterday:
[demo.zip](https://github.com/user-attachments/files/16638222/demo.zip)

The game believes it's a DM type demo and the scoreboard doesn't go away. The entities are broken too.

**Comment by ChillerDragon** [comment]
Cutting 0.7 demos still works fine. I assume I introduced that bug in https://github.com/ddnet/ddnet/pull/5949.

**Comment by ChillerDragon** [comment]
> That's not the only thing that's broken, try viewing this demo, recorded yesterday: [demo.zip](https://github.com/user-attachments/files/16638222/demo.zip)
> 
> The game believes it's a DM type demo and the scoreboard doesn't go away. The entities are broken too.

I can't load that demo at all. Which version are you using?

**Comment by murpii** [comment]
> > That's not the only thing that's broken, try viewing this demo, recorded yesterday: [demo.zip](https://github.com/user-attachments/files/16638222/demo.zip)
> > The game believes it's a DM type demo and the scoreboard doesn't go away. The entities are broken too.
> 
> I can't load that demo at all. Which version are you using?

DDNet, Nightly build on windows 11

**Comment by ChillerDragon** [comment]
It is a bit annoying to test but it fails most of the time. But I am pretty sure the first bad commit is bae37ab7df8421722bc6ef0262263883ec341805

**Comment by ChillerDragon** [comment]
> DDNet, Nightly build on windows 11

Yes nevermind I forgot to unzip. I thought you sent a demo file and just renamed it to .zip so github wont complain.
