### ISSUE TITLE
IDEA: The server can register gametype color to masterserver

### ISSUE THREAD

**Issue by Bamcane** [ddnet/ddnet#8753]
Now we need to cheat DDNet client that this server's gametype is "XXX idm" in order to get a color

Why don't we let server register it to master?

**Comment by heinrich5991** [comment]
Because then people will abuse it.

> Now we need to cheat DDNet client that this server's gametype is "XXX idm" in order to get a color

No, you could also make a PR.

**Comment by Robyt3** [comment]
I'd rather not allow servers to show their gametype as rainbow colors, black, bright red etc.
