### ISSUE TITLE
Speed hud shows 0 x velocity when dashing with ninja

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#8756]
https://github.com/user-attachments/assets/7c8b7f9c-1bd6-45f7-bb80-52e72dd4d535

This clip is on a 0.7 vanilla server. But I can also reproduce on a 0.6 ddnet server.

**Comment by l-ouis** [comment]
ninja doesn't actually give you extra speed, it just teleports you in discrete units iirc
so this is technically more correct

**Comment by ChillerDragon** [comment]
> ninja doesn't actually give you extra speed, it just teleports you in discrete units iirc so this is technically more correct

Wtf i did not know that xd. That sounds so cursed.

I will assume you are right and close the issue as not wanted because its correct.
