### ISSUE TITLE
Allow tee without weapons.

### ISSUE THREAD

**Issue by Bamcane** [ddnet/ddnet#8758]
Like this commit in teeworlds 0.7:
#[Make the client able to have tee's without weapons ](https://github.com/teeworlds/teeworlds/commit/c579bc1b1b9106023337d78597c192a567aea4f6)

Although it's a non-released change in 0.7 now, but it's really useful for mod that changed weapons, isn't it?

**Comment by ChillerDragon** [comment]
Is there a label called **"ISSUE: Mod-relevant change"** for https://github.com/ddnet/ddnet/issues/7895
