### ISSUE TITLE
The game crashes when I update the tab of DDNet server list, on main tab "Internet" this issue is not observed

### ISSUE THREAD

**Issue by GreenG33K** [ddnet/ddnet#877]
The game crashes when I update the tab of DDNet server list, on main tab "Internet" this issue is not observed.
Version of the game 10.8.6 x64
Linux Manjaro x64 OS
In the logs the last lines are:

[2017-09-24 19:32:36] [fetcher]: task got https://info.ddnet.tw/info?name=Green -> ddnet-info.json.tmp
[2017-09-24 19:32:36] [fetcher]: downloading ddnet-info.json.tmp

Now I have downgrade the game version to 10.7.1 x64 and this problem is not observed

**Comment by def-** [comment]
Fixed by https://github.com/ddnet/ddnet/commit/553c97b52da44b1195bc7b4178b6aa491fac1f6f ?

**Comment by GreenG33K** [comment]
I just checked, the problem does not appear immediately, when the game starts everything is working fine, but after a certain time, if I update the list of DDNet servers, the game crashes.
I got the game from [https://ddnet.tw/downloads/DDNet-10.8.6-linux_x86_64.tar.xz](https://ddnet.tw/downloads/DDNet-10.8.6-linux_x86_64.tar.xz)

**Comment by Learath2** [comment]
Try removing `ddnet-info.json`

**Comment by GreenG33K** [comment]
**Learath2**, unfortunately, it doesn't help

**Comment by Learath2** [comment]
Could you compile a debug version and get us a backtrace?

**Comment by GreenG33K** [comment]
**Learath2**, I'm new, could you send me an Instruction ?

**Comment by GreenG33K** [comment]
**Learath2**, I do not know how correctly I did it
I'm new 
https://pastebin.com/QuW4rDMZ

**Comment by heinrich5991** [comment]
Can you write "backtrace" in the command prompt of gdb after it crashed?

**Comment by GreenG33K** [comment]
I don't know is it correctly I did, I got:
https://pastebin.com/nNcF3P9C
p.s. I'm new

**Comment by GreenG33K** [comment]
I managed to got another version of backtrace:
https://pastebin.com/PjmjJZ5g

**Comment by Learath2** [comment]
Should we maybe ignore SIGPIPE?

**Comment by Learath2** [comment]
Maybe a ridiculously old version of libcurl? https://sourceforge.net/p/curl/bugs/1180/

No one encountered this since. If you still have this problem please reopen.
