### ISSUE TITLE
Editor: prompt grow lable column

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#8867]
From https://github.com/ddnet/ddnet/pull/8864

> ![image](https://github.com/user-attachments/assets/baba5349-1221-45a8-b894-2f7107e6ecbe)
> In the screenshot why are some texts smaller? I think the text field should be made wider.

> On the small aspect ratio the longest description already gets quite tiny. So there isn't much more space. And I can see how there would be even longer descriptions in the future.
>
> ![image](https://github.com/user-attachments/assets/5d4145df-eeb5-41b8-981a-597dac17b4cd)
>
> So it would need a more sophisticated approach than just growing the column. For example only grow it if the aspect ratio is wide. Or only grow it if the currently filtered results contain no long descriptions. Or cut off the description and only expand it into a popup or multi line entry when being hovered. Or scroll descriptions. Or cut descriptions if the space does not fit.

**Comment by ChillerDragon** [comment]
So far I like the "grow column if aspect ratio allows it" option best.

**Comment by Robyt3** [comment]
I'd simply pick a width that fits all entries for the first column and use the rest of the width (with a small margin) for the description. Making the description text not scale down on 5:4 is less important IMO.

I think there should be a consistent margin on the left and right side also, currently there is no margin on the right side.
