### ISSUE TITLE
0.7 client translation context problem

### ISSUE THREAD

**Issue by Bamcane** [ddnet/ddnet#8887]
In Steam build,
If you join a 0.6 server when your `player_name` is empty, client will use your Steam nickname as your player name.
But this will not happen on join a 0.7 server now

**Comment by Robyt3** [comment]
I guess this should be changed to use the `CClient::PlayerName` function instead of the config variable directly:

https://github.com/ddnet/ddnet/blob/69fa7ea18f691d177cf7e94d40a3a1bf31f3dbf2/src/game/client/gameclient.cpp#L2500-L2503
