### ISSUE TITLE
Team chat overrides multiple keys binds.

### ISSUE THREAD

**Issue by Devinci24** [ddnet/ddnet#8901]
I have team chat binded on t and /tp binded on ctrl+t.

For some reason, when opening team chat even once, I can't use my tp bind anymore. Every time I try to it just opens the chat.
Closing the client and reopening it solves it.
Every other bind, having something in l and something else in ctrl+l for example seems to be working fine.
I use steam client.

Seems like a minor issue, but an issue nonetheless.

**Comment by Robyt3** [comment]
It also affects binds that open the consoles.

**Comment by Robyt3** [comment]
Also happens when using a composite bind that disconnects (as this causes the ctrl key release not to be handled by the binds):

Reported by むぎ on Discord:

> i think it has something to do with this added, i have disconnect bind on Ctrl+F, and other bind on F, after i use disconnect bind and connect again my F bind doesnt work and it just disconnects me
> without ctrl pressed
> it fixes itself after i press ctrl
