### ISSUE TITLE
Bug with server register

### ISSUE THREAD

**Issue by whoismez** [ddnet/ddnet#8908]
![image](https://github.com/user-attachments/assets/1fdbc492-cde2-445e-8bd1-598957993bb9)
How to fix it?

**Comment by def-** [comment]
Can you reach https://master1.ddnet.org/ in your browser?

**Comment by ChillerDragon** [comment]
Looks like there are only ipv6 errors. @whoismez is your ipv6 working?

```
curl -6 master1.ddnet.org
```

If not you can either fully turn off ipv6 on your system or fix it. Or turn off ipv6 registering on the ddnet server side with ``sv_register ipv4``

**Comment by whoismez** [comment]
> Can you reach https://master1.ddnet.org/ in your browser and also via `curl master1.ddnet.org` on your server?

Yes, I can

**Comment by whoismez** [comment]
> Looks like there are only ipv6 errors. @whoismez is your ipv6 working?
> 
> ```
> curl -6 master1.ddnet.org
> ```
> 
> If not you can either fully turn off ipv6 on your system or fix it. Or turn off ipv6 registering on the ddnet server side with `sv_register ipv4`

Thank u 😇
