### ISSUE TITLE
Map incorrectly reloaded when using `change_map` after callvote

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#8909]
1. Callvote to change map to any map, e.g. `ctf1`
2. Use `change_map ctf1` or `sv_map ctf1` in rcon
3. The server reloads the map even though the map name did not change
4. Use `change_map ctf1` or `sv_map ctf1` in rcon again
5. As expected, now the server does not reload the map

**Comment by furo321** [comment]
Bug from #8811, it prepends a slash to every map name which is not needed. This causes the map name to be technically different.
