### ISSUE TITLE
CTF returned flag counting bug

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#8927]
For some reason, sometimes, when flags are returned, they are not counted. I noticed it during game when I wanted to find out who returned some of the flags because I was AFK for a bit.

Then I watched the demo, and it seems that similar behaviour is demonstrated even when watching the demo. I can't tell if it's the exact same behaviour (e.g. if player 1's first flag return registered in game, but maybe not in the demo). This happens when watching the entire demo (meaning didn't skip any part of the demo, so counting flags doesn't skip)

Here is the stats screenshot at the end of the game (should be 6 flags each team)
![image](https://github.com/user-attachments/assets/d7a1009f-b468-424a-99e5-f3a5329c27ae)

Here is the demo file: https://twelo.pages.dev/dl/ctf3_2024-09-11_07-13-06.demo

**Comment by ChillerDragon** [comment]
By flag "return" you mean capture enemy flag? Or return to its own base?

**Comment by PathosEthosLogos** [comment]
> By flag "return" you mean capture enemy flag? Or return to its own base?

Yes, capture
