### ISSUE TITLE
Extend antibot to be a generic plugin system

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#8945]
Allow loading multiple modules at the same time that can affect the gameplay. The antibot module is basically already a plugin. Its api could be upgraded to allow loading more than one module and be rebranded to "plugin" instead of "antibot". Then it just needs a few more hooks and server admins can build their own mods using drag and drop.

It would also help with https://github.com/ddnet/ddnet/issues/7777 because there is now less need for modders to edit the actual ddnet codebase and cause git conflict surface.

**Comment by heinrich5991** [comment]
The API of the antibot is intentionally limited. I don't want to add such a plugin system for mods.
