### ISSUE TITLE
0.7 client: kill message skins are missing team information when switching to dummy

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#8977]
Was probably introduced in https://github.com/ddnet/ddnet/pull/8730

![image](https://github.com/user-attachments/assets/1d037de4-0258-4281-93e8-df0bf96c0742)

The chat is also affected

![image](https://github.com/user-attachments/assets/189908a5-6576-42f3-9c20-8f9a855b907d)

**Comment by Robyt3** [comment]
I don't understand why #8730 was applied only to 0.7 client info. Doesn't the same issue apply to all client info? If you connect main and dummy on a 0.6 server, both might get different info which is currently lost since we only store one info for both.

**Comment by ChillerDragon** [comment]
@Robyt3 I just started to wonder the same thing now. I assume 0.6 works otherwise someone would have complained.

**Comment by Robyt3** [comment]
> @Robyt3 I just started to wonder the same thing now. I assume 0.6 works otherwise someone would have complained.

Why does the same not work for 0.7? We always assume that main and dummy connect to the same server anyway, so why do we have to support separate client info for 0.7 but not 0.6? This makes it quite hard to understand the behavior of the code.

**Comment by ChillerDragon** [comment]
I guess the key is that in 0.6 it does not matter too much. Because the skin info is in the snap. So when you switch to another tee you instantly start consuming the correct skin info from the snap. But in 0.7 the skin info moved to a net message. So we as a client have to store it and update it on dummy switch.

**Comment by Robyt3** [comment]
> I guess the key is that in 0.6 it does not matter too much. Because the skin info is in the snap. So when you switch to another tee you instantly start consuming the correct skin info from the snap. But in 0.7 the skin info moved to a net message. So we as a client have to store it and update it on dummy switch.

I see. So I guess skipping in 0.7 demos also breaks skin info?

**Comment by ChillerDragon** [comment]
@Robyt3 for demos there is a demo only snap item.

https://chillerdragon.github.io/teeworlds-protocol/07/snap_items.html#obj_de_client_info

**Comment by Robyt3** [comment]
Closed by #8980.
