### ISSUE TITLE
SDL2

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#9]
It would be really nice to switch over to SDL2, so that everyone can use proper input methods, for arabic input for example. I also have a port lying around in some branches, but there were a few problems, on Linux at least. It always captured the mouse for me. Also the window was at the wrong position when you forcefully resize it. Maybe there were some more bugs that I just don't remember.

**Comment by imcaffrey** [comment]
@def- 
How to install SDL on Ubuntu?
it replies that many things are required...Sadly...while there are so many that I cant get them one by one...

Can DDNet be launched into Ubuntu Software Centre just like teeworlds client?

Thanks

**Comment by def-** [comment]
`apt-get build-dep teeworlds` should install all dependencies, including SDL. If you mean SDL2, no idea.

NICO tried to put it into Ubuntu, no idea how well it works: http://forum.ddnet.tw/viewtopic.php?f=3&t=834&hilit=ubuntu

**Comment by imcaffrey** [comment]
Thanks

**Comment by def-** [comment]
This would also allow platform independent paste.

**Comment by cinaera** [comment]
What's the state of this issue as the SDL2 pr has been merged into the teeworlds master?

**Comment by def-** [comment]
SDL2 is still as problematic as before for me as I described: https://github.com/teeworlds/teeworlds/pull/1246#issuecomment-64905811
