### ISSUE TITLE
Collapse tabs

### ISSUE THREAD

**Issue by AoeTW** [ddnet/ddnet#9008]
I just updated to the new version of DDNet and I noticed you can only see 13 people on the server at once. My suggestion is to be able to collapse the communities & Info to be able to see more people at once.
![Collapse](https://github.com/user-attachments/assets/6f349471-5cb2-4b36-b782-bc25db95635a)

**Comment by dropalways** [comment]
why would you want to see so many people (if your trying to look for someone why not instead add a search bar)

**Comment by AoeTW** [comment]
> why would you want to see so many people (if your trying to look for someone why not instead add a search bar)

To see who is on the server.

**Comment by dropalways** [comment]
just a simple - would be fine i think(ignore my bad example i dont do this for a living)
![DDNet_HFeTXSdgIz](https://github.com/user-attachments/assets/80c10e57-67f9-4a70-9432-da3ff4879822)

**Comment by AoeTW** [comment]
I think I would prefare double pressing or single pressing on it to collapse it, better than a small bottom on the side.

**Comment by SollyBunny** [comment]
As I said in #9237 I think the communities tab, if it goes anywhere should go in the filters section

**Comment by Robyt3** [comment]
See https://github.com/ddnet/ddnet/pull/9237#pullrequestreview-2434256597.
