### ISSUE TITLE
Teleporter behavior

### ISSUE THREAD

**Issue by axblk** [ddnet/ddnet#901]
Some thoughts on the teleporters:

- Right now it is possible to trigger tiles behind a teleporter if you are fast enough.

For example you might get frozen here when you fall very fast:
![teleport](https://user-images.githubusercontent.com/550744/31627500-cd7896ca-b2ad-11e7-9eb8-ccedbd1d3796.png)

- In case teleporters will be made predictable:

Teleportation relies on the position in the previous tick. Actually this is not available client-side, since (by default) not every tick is sent to the clients. So the first predicted tick for each snapshot will not be absolutely accurate. A solution would be to add the previous position to the snapshot.
One more thing that is needed for proper teleport prediction is the current checkpoint number.

**Solution for both:**
Teleporters can be moved to the `CCharacterCore::Move` / `CCollision::MoveBox` method. When a teleporter is touched, the movement will be cancelled and the position will be set to the teleporter output. Unskippable tiles also need to be triggered by this function then (via callback or a list).
Right now all tiles are triggered one tick after the real movement happened. With this change the tiles will be triggered immediately. While this makes the game a tiny bit more responsive, this forbids teleport prediction for older servers. When the client recognizes the teleportation earlier than the server, strange things will happen. To prevent this, some kind of ddnet net-version or hash will be needed, to activate the prediction.

In general, to my mind the core position should never be changed outside of `CCharacterCore::Move`. This makes prediction easier and prevents such bugs.

**Comment by Learath2** [comment]
This will change physics, I don't think we can fix this...

@heinrich5991 && @def-: Close if wontfix
