### ISSUE TITLE
Editor: the ctrl+right click selection is triggered by accident

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#9029]
Moving in the editor happens with ctrl drag. Some users reported that because of that in combination with right click to deselect tiles they accidentally activate the layer selector feature.

I see two possible options here:
- move the keybind to other keys (idk to what)
- add a config to disable the feature

**Comment by BlaiZephyr** [comment]
TiL you can move with ctrl+click :P - i and many others out of habit use mouse3 for that - it's the default key on most editing softwares like audio/video editing CAD/CAM software etc. - but i think we want to keep another way of navigating for people using a touchpad so the sanest thing for me sounds like making it a config you can turn on/off

**Comment by ChillerDragon** [comment]
I am also leaning towards config. I can not find another key bind that is as reachable. The flow works really smooth for me to select layers like this. But the feature is only useful because hitting that keybind is faster than any other way of selecting the desired layer.

**Comment by AoeTW** [comment]
I like to use ctrl+left click to move around because I'm used to it from Photoshop and other programs, so this happens to me a lot. Maybe shift+right would be a good alternative? We already have a lot of toggleable configs in the client and this feature is a bit niece for mappers only. So imo it would be best if we could find another hotkey I think?

**Comment by BlaiZephyr** [comment]
i know pinging this PR is getting quite annoying on these topics, but this could be fixed by
#7556
:P

**Comment by ChillerDragon** [comment]
@AoeTW I actually also move with ctrl+left and use the layer selector feature since two years in combination with it. Works pretty well for me. You should give it a try its really powerful for fast layer switching.

shift+right might work yes. Not sure did not investigate. But then we get a new complaint in two years because someone uses shift and presses it by accident. Also I am already used to ctrl+rightclick so I would prefer it to stay there. Thats why for now i sent the pr with a config. Lets see what the maintainers have to say.

**Comment by AoeTW** [comment]
> @AoeTW I actually also move with ctrl+left and use the layer selector feature since two years in combination with it. Works pretty well for me. You should give it a try its really powerful for fast layer switching.
> 
> shift+right might work yes. Not sure did not investigate. But then we get a new complaint in two years because someone uses shift and presses it by accident. Also I am already used to ctrl+rightclick so I would prefer it to stay there. Thats why for now i sent the pr with a config. Lets see what the maintainers have to say.

Yea I see how it could be really useful. But sadly I keep miss clicking it all the time. If I were to use it, I would personally prefer shift + right. I don't think I would miss click it but I do use shift + left click a lot for area mapping, so it is possible.

**Comment by AoeTW** [comment]
How about Alt + Right click? I would really love to use this feature honestly. Shift is bad because I use it a lot for placing tiles and ctrl for moving around. Alt seems like the perfect key

**Comment by ChillerDragon** [comment]
I agree with @BlaiZephyr we should get custom key binds (https://github.com/ddnet/ddnet/pull/7556) instead of changing the established ones from one hardcodet version to another hardcodet version.
