### ISSUE TITLE
Server side demos do not work with map paths

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#9033]
Assuming both maps exist ``foo.map`` and ``foo/bar.map``

This works:

```
DDNet-Server "sv_auto_demo_record 1;sv_map foo"
```

This does not:

```
DDNet-Server "sv_auto_demo_record 1;sv_map foo/bar"
```

Because it tries to write to a directory that does not exist in the demos directory.

```
2024-09-25 09:47:39 I demo_recorder: Unable to open 'demos/auto/server/foo/bar_2024-09-25_09-47-39.demo' for recording
```

Could also see that as a feature to organize demos in folders. But then the folders should be auto created instead of failing to record.

**Comment by heinrich5991** [comment]
Should probably strip the folder path.
