### ISSUE TITLE
"Leak IP" maybe broken

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#9035]
With the teeworlds master server you can see the server name and player count of your favorites even if they are not registered in the master ``sv_register 0``. In ddnet this is no longer possible because the client gets all its information from the http master server which does not know about unlisted servers.

**Comment by TsFreddie** [comment]
Can't you already do this using the "Leak IP" option once you favorite a server?

**Comment by ChillerDragon** [comment]
Ah good idea! But sadly no. I tried ``leak_ip_address_to_all_servers`` and the ui checkbox and reconnecting. Nothing worked.

![image](https://github.com/user-attachments/assets/21bcc084-178e-4911-9241-85a22417807b)

**Comment by TsFreddie** [comment]
sounds like a regression unless I terribly misremembered what "Leak IP" was for

**Comment by ChillerDragon** [comment]
> Can you give an example of a server where it doesn't work?

The servers are hidden for a reason. I sent you the ip on irc. But it can be tested with any ddnet server with ``sv_register 0``. You will see that for example the teeworlds 0.7 client displays the information correctly.

**Comment by Robyt3** [comment]
Works for me when adding local servers as favorites.

**Comment by ChillerDragon** [comment]
I hosted a public test server. Try ``add_favorite 45.142.178.158:8306``

**Comment by TsFreddie** [comment]
![screenshot_2024-09-25_17-08-36](https://github.com/user-attachments/assets/588a7659-68e5-45a7-91b8-52e5cb6e8c9b)

Looks fine for me even without "Leak IP" ticked. hmm..

**Comment by TsFreddie** [comment]
does this mean Leak IP maybe broken both way? it doesn't work when it should and it shouldn't work when it does?

**Comment by ChillerDragon** [comment]
No if its off for me it also does not work.

**Comment by ChillerDragon** [comment]
I tried disabling ipv6 on my machine. I tried using a vpn. Nothing works. I would blame the servers firewall if it wouldn't be working for fred. I would blame some issue on my client network side if it wouldn't be working from a teeworlds client.

Can anyone else reproduce or is this a me issue?

**Comment by heinrich5991** [comment]
I can reproduce your issue. I cannot reproduce @TsFreddie's behavior.

**Comment by ChillerDragon** [comment]
I verified with ``tcpdump`` on the server side that fred refreshing his browser causes the expected packet exchange. So there is no magic cache somewhere.

**Comment by Jupeyy** [comment]
My understand is (and always was) that Leak IP is only triggered if no master list exists at all :D

I've never seen it work otherwise, even from the beginning.

`leak_ip_address_to_all_servers` used to work tho
