### ISSUE TITLE
Switch between browser/lan/favorites with arrow key left and right

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#9038]
![image](https://github.com/user-attachments/assets/13dc44be-cc54-4410-86ca-822a36a54acc)

I have this shortcut in [term-ux](https://github.com/chillerbot/chillerbot-ux/blob/0939db3949fc8c76ebc67f565b069e7f9e2e28e7/README.md#term-ux-a-ncurses-terminal-client) and it feels quite natural there. I keep trying to press it in the ddnet client.

Any objections? Otherwise I would send a pr.

**Comment by Jupeyy** [comment]
Idc, but please make sure it does not work while a text input is focused, bcs i often use arrow keys there :D
