### ISSUE TITLE
muteip announces IP in chat

### ISSUE THREAD

**Issue by 12pm** [ddnet/ddnet#908]
This rcon command is probably hardly used, though when issued announces the muted IP via server announcement publicly in chat.
It should either announce the muted player name(s) or be completly removed since ``muteid`` is more convenient anyway.

**Comment by Learath2** [comment]
More generally muteid should be updated to work on ip's. Currently the muted person just joins their dummy and talks from there.

I was thinking of generalizing the ban system to support other kinds of ip based restrictions, maybe a way to prevent votes aswell.
