### ISSUE TITLE
Set collision line width to 1 for everyone but you

### ISSUE THREAD

**Issue by SollyBunny** [ddnet/ddnet#9081]
Having a non zero line width is nice when you are blind

Having 5 overlapping lines of the same width is not nice when you are blind

I think that line width should only apply to you (dummy not included) to bring focus to your own

This only would come into affect when you have everyones hook lines enabled

I already have the code for this, but wondering if I should make a PR (the code is just adding `Local && ` to a single line)

**Comment by kaitlynia** [comment]
I would actually use a non-default width if this were the case. Equally blind but I hate it when noobs shine lasers in my face for no reason
