### ISSUE TITLE
Add ``/top5points -1``

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#9089]
would be nice to see how many names collected points already

**Comment by BlaiZephyr** [comment]
you can't see the exact amount rn since i guess it just stops counting if you have less than 4 points but inputting `/top5points 999999` gives me 920174. which is still not accurate but close to what you want ig

**Comment by ChillerDragon** [comment]
Nice hack thanks for sharing @BlaiZephyr 

Still would be nice to have the same syntax for all top commands. Because ``/top5 -1`` works already like that.

**Comment by BlaiZephyr** [comment]
yeah but that would also not be accurate given how many names only have 1-4 points. I think Its better to fall back to the website (if we even store that there not sure right now) for such information

**Comment by kaitlynia** [comment]
I strongly dislike comments like "just use the website" as it's actively shutting down discussion without providing real solutions. Obviously OP knows about the website but they're posting **here** about the game.

If the 1-4 points case is a concern (and it's not, to me) you could supply another parameter for a points threshold (/top5points -1 5). This would implicate new API behavior though and goes outside of the scope of just the game.

**Comment by BlaiZephyr** [comment]
my comment was more about if we even need that "solution" - as i find it unnecessary, the data will never be accurate, what's the point on having inaccuracte data displayed?

**Comment by heinrich5991** [comment]
> I strongly dislike comments like "just use the website" as it's actively shutting down discussion without providing real solutions. Obviously OP knows about the website but they're posting **here** about the game.

It's a matter of resource allocation. If there's a way to view the information on the website already, then it might not be worth it to implement it ingame, too, but rather spend the time on other issues.

**Comment by ChillerDragon** [comment]
The ``/top5points 999999`` requires the user to already know the amount of players. If the number is too high it shows nothing.

But yes players with 0 points get inserted into the db and they share the last rank. So it is not really a reliable source for information. I still think it is nicer than doing a manual binary search with 9999999. And be consistent with /top5.

Also this is the kinda fun fact I would like to know right now while being in game. And I do not want to know it that much that I would bother to open my browser for it and navigate to the ddnet website.

I gave the query a try and rage quitted. My sql is not good enough to make it work. Since it seems like nobody else wants to implement it I will close the issue now to avoid a stale issue.
