### ISSUE TITLE
make CTRL-C trigger a proper shutdown

### ISSUE THREAD

**Issue by jxsl13** [ddnet/ddnet#9104]
Current behavior seems to be that the application is simply shut down but connected players are not cleanly disconnected.
It would be great if  CTRL-C triggered a proper disconnect for every connected player.

**Comment by Robyt3** [comment]
Works for me. The first Ctrl+C press triggers a proper shutdown and players are disconnected with "Server shutdown". The second press exits immediately if you prefer a fast and unclean shutdown.

**Comment by jxsl13** [comment]
probably my bad somewhere along the lines.
