### ISSUE TITLE
Weird mouse sensitivity in 144hz

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#911]
Got this message:

> Hey deen,
> 
> I changed to a 1080p 144hz monitor on tuesday, always played in 1280x1024, worked fine, everything nice.
> 
> Now 144hz, game seems fluid as butter, but the graphics are awkward, not as good as on my old monitor, mouse sens is odd as well.
> 
> Can u craft a custom client / or a released version where we can adjust mouse sens horizontal + vertical, with presets of 1280x1024 (preferably) and UI size adjustments for 1280x1024, so I can play on 1920x1080 and still have the same benefits (slightly off I know)
> 
> I'd love you more
> 
> Shiro

**Comment by Ryozuki** [comment]
I play at 144Hz on windows without any problem.

**Comment by PathosEthosLogos** [comment]
Same, closed?
