### ISSUE TITLE
Remove Invincible, allow super in practice, remove cross-team interaction from super

### ISSUE THREAD

**Issue by sjrc6** [ddnet/ddnet#9112]
The particle effects should be kept.

Having 2 modes that do the same thing except one has a feature that isn't useful doesn't seem worth it. It's quite a pain to have so many individual checks in the physics code for both of them.

**Comment by sjrc6** [comment]
If cross team interaction is required functionality then we can have a separate mode that isn't toggleable without rcon. Then you only need to check for that mode in the cross team interactions.

**Comment by def-** [comment]
Super puts you in a separate team, so I prefer the way invincible mode works and would argue to remove old super and rename invincible to super.

**Comment by sjrc6** [comment]
> Super puts you in a separate team, so I prefer the way invincible mode works and would argue to remove old super and rename invincible to super.

You could split super into 2 modes that are just a subset of the previous functions, then allow one of them in practice.

**Comment by def-** [comment]
That's not so easy implementation-wise because super is implemented as a special team 64.

**Comment by sjrc6** [comment]
> That's not so easy implementation-wise because super is implemented as a special team 64.

It turns out you're correct. This will be much more complicated than I expected.

**Comment by Learath2** [comment]
There is a reason I suggested not messing around with allowing super in practice mode. It's an old hack that is deeply entangled in the source code. Messing around with it is just calling for trouble.

If anything I agree with @def- that this new version could even replace the old super.

**Comment by sjrc6** [comment]
I worded the title poorly in retrospect, what I actually wanted was for invincible to inherit all of the super features except for the separate team, and then be renamed to super. However even that isn't possible because there are only 64 switch teams which makes it impossible for super team to not have immunity to switches, so the entire idea is rather pointless.
