### ISSUE TITLE
player_color_body has incorrect arguement validation

### ISSUE THREAD

**Issue by bencie** [ddnet/ddnet#9122]
player_color_body, player_color_feet, dummy_color_body, dummy_color_feet all only accept ints now. Previously you could also type certain colors, and hex color codes.
`$FF0101 is not a valid integer.`
`red is not a valid integer.`

**Comment by Learath2** [comment]
@Robyt3 I'm guessing this broke with your console color handling changes

**Comment by jxsl13** [comment]
what is that $ sign?

**Comment by Learath2** [comment]
> what is that $ sign?

It's the replacement for `#` I ended up using for hex rgb colors because `#` is a comment in the console and it was weird to handle

**Comment by Robyt3** [comment]
d452bcda8fce9ce294a92bb61b94192f585a3460 is the first bad commit

@KebsCS
