### ISSUE TITLE
CMake: Make release with version in it

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#923]
Like `python scripts/make_release.py $VERSION win64`, can I set $VERSION for cmake's `make package`? And why does it have a `-portable` at the end?

**Comment by heinrich5991** [comment]
It parses the version from `src/game/version.h`. `-portable` is an artifact from the way CMake handles packages. You can either rename the output file (the contents don't have `-portable` in them), or call our own target `package_default` instead of `package`.

**Comment by def-** [comment]
Alright, I guess.
