### ISSUE TITLE
Any plans to include ddnet in the debian repos?

### ISSUE THREAD

**Issue by itsrachelfish** [ddnet/ddnet#924]
Teeworlds is available as a package in Debian / Ubuntu by default, anybody can simply `apt install teeworlds` on a Debian based system and start playing. It would be nice if ddnet was available through an official repo as well.

Even a PPA would be better than needing to manually download DDNet any time a new version released.

Thanks!

**Comment by def-** [comment]
See also https://github.com/ddnet/ddnet/issues/261
