### ISSUE TITLE
Grounded unfreeze tile

### ISSUE THREAD

**Issue by l-ouis** [ddnet/ddnet#9244]
Tile that only unfreezes you if you're grounded while also in the tile
Motivation:
- Fixes cases where you land on the edge of a block yet don't get unfrozen (in some cases, unfreeze cannot be placed on the edges)
- Fixes case where you buffer jump while falling into an unfreeze tile, but double-jump before hitting ground due to still having double-jump
-  Better differentiation between unfreeze that plays a role in a part and unfreeze that exists to help flow (unfreeze on the ground after the part ends)

Cons:
- hard to design the tile png
- confusing to have multiple entities for a very similar functionality (in entities -- this is easy to design visually in maps and I think it makes sense when you're not in entities)
- more (?)

**Comment by Jupeyy** [comment]
I could swear I read about exactly that before, but can't find any related issue here.. Maybe that simply was on discord a while ago^^

**Comment by heinrich5991** [comment]
@l-ouis Please include a motivation in your feature requests.

**Comment by l-ouis** [comment]
@heinrich5991 done, sorry, I usually do ^^'

**Comment by heinrich5991** [comment]
I think that tile could be useful for mappers. I'm not sure if it would be confusing for players.

Also needs a decision of what should happen if you're only grounded between ticks and on this tile. A naive implementation would probably not unfreeze you then.

**Comment by sjrc6** [comment]
This would be the third solid tile. (hookable, unhookable, this). 

So maybe it's better to just have a generic system that lets you apply any effect to "solid" tiles. Then we don't need to duplicate this every time someone wants it for a new effect.

**Comment by sjrc6** [comment]
> Also needs a decision of what should happen if you're only grounded between ticks and on this tile. A naive implementation would probably not unfreeze you then.

It should behave the same as double jump refresh, to keep consistency.

**Comment by AssassinTee** [comment]
> This would be the third solid tile. (hookable, unhookable, this).
> 
> So maybe it's better to just have a generic system that lets you apply any effect to "solid" tiles. Then we don't need to duplicate this every time someone wants it for a new effect.

This doesn't need a third solid tile, it can be done with a tune:  `tune_zone 1 ground_unfreeze 1` and then paint your tune zone where you want this effect. You could also set this globally then as a tuning option for all surfaces.

Yes you could do it with a tile, but this way you don't break compatibility

**Comment by l-ouis** [comment]
Closing because I believe this better fits with a material modifier on solid tiles rather than a new tune or unfreeze tile.
