### ISSUE TITLE
QoL: Add a new parameter to `name_ban` that ignores case sensitivity

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#9250]
The issue: if we ban a player named Jason, they could just rename to "jason" to avoid the ban. Using distance 1 would solve that, but it would also block players named "Mason" or "mason", which isn't ideal. A new parameter that ignores case sensitivity would resolve this issue.

The given name is just an example. I have a couple individuals with a particularly unique names, where using the distance parameter is simply not doing the job.

**Comment by mwinkens** [comment]
Next time he'll rename to TheRealJason, I suggest IP banning and running one of the anti VPN scripts.

**Comment by AssassinTee** [comment]
Next time he'll rename to TheRealJason, I suggest IP banning and running one of the anti VPN scripts.

**Comment by heinrich5991** [comment]
What's the problem of them using a similar name? Their points have been lost. We can't ban all similar names, as @AssassinTee pointed out.

**Comment by heinrich5991** [comment]
If sometihng is done to the `name_ban` command, it shouldn't be implemented via yet another parameter, there needs to be something like keyword arguments instead. Optional args don't scale.

**Comment by murpii** [comment]
> What's the problem of them using a similar name? Their points have been lost. We can't ban all similar names, as @AssassinTee pointed out.

I'll provide a quick example. See: https://ddnet.org/maps/AiP-45-Gores

Name banning souppvp isn't enough. I'd have to nameban every variation with uppercase letters or lowercase letters if I want to prevent said name to be used. I can't use any large arguments for the distance parameter, because the name is already too short.

**Comment by KebsCS** [comment]
> Name banning souppvp isn't enough. I'd have to nameban every variation with uppercase letters or lowercase letters if I want to prevent said name to be used. I can't use any large argument for the distance parameter, because the name is already too short.

https://github.com/ddnet/ddnet/blob/master/src/engine/server/name_ban.cpp#L103
Setting `is_substring` to 1 will compare case insensitively

**Comment by murpii** [comment]
> > Name banning souppvp isn't enough. I'd have to nameban every variation with uppercase letters or lowercase letters if I want to prevent said name to be used. I can't use any large argument for the distance parameter, because the name is already too short.
> 
> https://github.com/ddnet/ddnet/blob/master/src/engine/server/name_ban.cpp#L103 Setting `is_substring` to 1 will compare case insensitively

Oh, that's my bad then. I guess the name I was comparing didn't consist entirely of Latin letters.
