### ISSUE TITLE
Winter menu theme background not large enough on wider screens

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#9300]
16:9 resolution on desktop:

![screenshot_2024-11-29_22-10-38](https://github.com/user-attachments/assets/1aa94159-517a-400a-bda4-baabac58077b)

191:90 resolution on Android (grey bar on the left side from missing background):

![Screenshot_2024-11-29-22-06-47-26_39a5dfb0fae685d668d14fdf8b7ac9b9](https://github.com/user-attachments/assets/b0aa2703-37b8-48f6-a1f9-6df55c7d6e4b)

**Comment by ASKLL-STAR** [comment]
**NEED REOPEN** _The "winter_night.map" in the package of the official website is lagging behind._ @Robyt3

During the process of using the Android version of DDNet, I found that this issue still remained unresolved. At first, I thought it was an issue of the "winter_night.map" file. However, after checking, I discovered that the SHA1 values of the "winter_night.map" in the "data" folder of the Win64 and Android apk downloaded from the official website (ddnet.org/downloads) are not consistent with that of the "winter_night.map" in the "data" folder of the Steam version and the source code.
Win64 package:
![Win64](https://github.com/user-attachments/assets/2fe053c2-3821-4870-9f23-a0cc3bf3f891)
Android package:
![Android](https://github.com/user-attachments/assets/a6dc43a5-81d7-4c09-9fe4-860c73ac8f9c)
Steam package(SHA1 not consistent):
![Steam](https://github.com/user-attachments/assets/48ab2e90-4040-4e7b-b7d7-3de9edaeeb54)

**Comment by Robyt3** [comment]
The PR #9390 is not part of the 18.8.2 release which should explain why it's not fixed on these versions yet. Are you perhaps using Steam nightly? The SHA1 starting with `34de` looks like the correct file, but you are correct it looks like this is also not fixed on Android yet with the nightly and this file version.

**Comment by ASKLL-STAR** [comment]
Ah, I'm currently using the Steam nightly build. This is most probably the origin of the issue. But I reckon it should be incorporated into the new version ASAP. After all, that gray bar is really a nuisance and quite an eyesore.

**Comment by ASKLL-STAR** [comment]
@Robyt3 close it

**Comment by Robyt3** [comment]
It's not fixed yet, there is still a grey bar with the winter theme.

**Comment by ASKLL-STAR** [comment]
It's has no problems in the v19.0
![Image](https://github.com/user-attachments/assets/7ff57d46-7a75-4b79-bbbd-d5eb2eafe666)
![Image](https://github.com/user-attachments/assets/e7ba25e3-b911-42fe-aabf-05f1d8fc15b0)

**Comment by Robyt3** [comment]
I think that's the nighttime winter theme? The issue only happens with the daytime winter theme I guess.
