### ISSUE TITLE
[ddnet on flatpak] app is freezes and crashes the system

### ISSUE THREAD

**Issue by lgor360** [ddnet/ddnet#9305]
i'm download ddnet from flatpak but when i try to start it... first its start to initialize. but freezes after 2 seconds... after 1 minute the system crashing...

**Comment by Jupeyy** [comment]
Does it also happen with the official release:
https://ddnet.org/downloads/

Because we don't host any flatpak version

**Comment by lgor360** [comment]
> Does it also happen with the official release:
> https://ddnet.org/downloads/
> 
> Because we don't host any flatpak version

okay! and... why does someone say there is an android version?...

**Comment by lgor360** [comment]
> Does it also happen with the official release:
> https://ddnet.org/downloads/
> 
> Because we don't host any flatpak version

okay! and... why does someone say there is an android version?...

**Comment by def-** [comment]
Android beta version is available on Discord: https://discord.com/channels/252358080522747904/1277345584080097320
