### ISSUE TITLE
upgrade deb version of the game!

### ISSUE THREAD

**Issue by lgor360** [ddnet/ddnet#9312]
please upgrade ubuntu/debian versions of game...

**Comment by def-** [comment]
Build it yourself from source! Instructions: https://github.com/ddnet/ddnet?tab=readme-ov-file#cloning

**Comment by lgor360** [comment]
> Build it yourself from source! Instructions: https://github.com/ddnet/ddnet?tab=readme-ov-file#cloning

yea, but... i cant download repository...

**Comment by lgor360** [comment]
> Hey, we aren't the maintainers of the Debian package and Debian isn't exactly known for having the latest versions of packages either. I recommend downloading DDNet from [the site](https://ddnet.org/downloads/) or from [Steam](https://store.steampowered.com/app/412220/DDNet/) to always get the latest versions.

i cant use steam because... i cant download one package...

**Comment by lgor360** [comment]
its means what i cant use ddnet on arm64?..

**Comment by def-** [comment]
Debian should provide old versions of DDNet, or you can upgrade your Debian version.

**Comment by def-** [comment]
According to https://repology.org/project/ddnet/versions Ubuntu stopped upgrading DDNet a while ago. These emails are listed if you want to get in touch with maintainers: [ubuntu-devel-discuss@lists.ubuntu.com](https://repology.org/maintainer/ubuntu-devel-discuss%40lists.ubuntu.com), [mmyangfl@gmail.com](https://repology.org/maintainer/mmyangfl%40gmail.com), [szlin@debian.org](https://repology.org/maintainer/szlin%40debian.org)

**Comment by lgor360** [comment]
> According to https://repology.org/project/ddnet/versions Ubuntu stopped upgrading DDNet a while ago. These emails are listed if you want to get in touch with maintainers: [ubuntu-devel-discuss@lists.ubuntu.com](https://repology.org/maintainer/ubuntu-devel-discuss%40lists.ubuntu.com), [mmyangfl@gmail.com](https://repology.org/maintainer/mmyangfl%40gmail.com), [szlin@debian.org](https://repology.org/maintainer/szlin%40debian.org)

okay... and just in case... i can install ddnet from source on arm64?

**Comment by def-** [comment]
https://github.com/ddnet/ddnet?tab=readme-ov-file#dependencies-on-linux--macos

**Comment by lgor360** [comment]
> https://github.com/ddnet/ddnet?tab=readme-ov-file#dependencies-on-linux--macos

okay! thanks!
