### ISSUE TITLE
invalid index-pack output when i try to git clona repository...

### ISSUE THREAD

**Issue by lgor360** [ddnet/ddnet#9320]
new problem on ubuntu 24.04 arm64.... why its so difficult...

**Comment by def-** [comment]
That sounds like a problem between you and github. If git doesn't work for you, you can also download the zip: https://github.com/ddnet/ddnet/archive/refs/heads/master.zip

**Comment by Robyt3** [comment]
Feel free to ask in the #developer channel on our Discord (https://ddnet.org/discord) if you need help building.

**Comment by lgor360** [comment]
> Feel free to ask in the #developer channel on our Discord (https://ddnet.org/discord) if you need help building.

discord is banned in Russian...

**Comment by lgor360** [comment]
> That sounds like a problem between you and github. If git doesn't work for you, you can also download the zip: https://github.com/ddnet/ddnet/archive/refs/heads/master.zip

okay! wait! did you know what where is a flatpak version of the game? if you do... how to change render engine? because... in default its Vulcan but... my pc is not like Vulkan and just close the game!

**Comment by furo321** [comment]
> how to change render engine without starting the game?

You can find a guide in the [wiki](https://wiki.ddnet.org/wiki/GFX_Troubleshooting#Game_not_starting).

**Comment by def-** [comment]
`./DDNet "gfx_backend OpenGL"` I think

**Comment by lgor360** [comment]
> `./DDNet "gfx_backend OpenGL"` I think

no... i start it with "flatpak run tw.ddnet.ddnet"

**Comment by Jupeyy** [comment]
`DDNET_BACKEND=GLES flatpak run tw.ddnet.ddnet`

**Comment by lgor360** [comment]
> `DDNET_DRIVER=GLES flatpak run tw.ddnet.ddnet`

FINALLY! THANKS SOOOOO MUCH! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS! THANKS!

**Comment by lgor360** [comment]
wait... where is the data folder for ddnet flatpak?.. where is not ddnet folder in .local/share...

**Comment by Jupeyy** [comment]
> wait... where is the data folder for ddnet flatpak?.. where is not ddnet folder in .local/share...

You can look it up in F1 console.
What hardware do you even use? Some kind of raspberry pi?

**Comment by lgor360** [comment]
> > wait... where is the data folder for ddnet flatpak?.. where is not ddnet folder in .local/share...
> 
> You can look it up in F1 console.
> What hardware do you even use? Some kind of raspberry pi?

raspberry pi 4b.
i look and... app/share/ddnet/data... where is not app directory in home and root (/) directory...

**Comment by Jupeyy** [comment]
Yeah the flatpak version probs doesn't allow file openers or has no default manager for that.

You have to understand the idea behind flatpak is to basically create a second system on your OS that is more up to date (that even includes drivers like OpenGL and Vulkan, and other deps) (but not kernel etc.)

> app/share/ddnet/data
Look in the console for another dir. That one is the data dir, you need the config dir

**Comment by Jupeyy** [comment]
> user dir

Ah yeah maybe they call it like that

**Comment by lgor360** [comment]
> > user dir
> 
> Ah yeah maybe they call it like that

nope... all directories isnt work! (i. e. ddnet isnt takes skins from them)

**Comment by Jupeyy** [comment]
For me it is in `~/.var/app/tw.ddnet.ddnet/.teeworlds/`

But anyway, this isn't really a support repo for flatpak issues, I recommend you to join our discord, bcs everytime we write here we might ping other maintainers.
It's also more chat friendly than here

**Comment by Robyt3** [comment]
> > Feel free to ask in the #developer channel on our Discord (https://ddnet.org/discord) if you need help building.
> 
> discord is banned in Russian...

There's also an IRC channel #ddnet on Quakenet ([Webchat](https://webchat.quakenet.org/?channels=ddnet&uio=d4)).
