### ISSUE TITLE
where i need to paste my skins in ddnet flatpak?

### ISSUE THREAD

**Issue by lgor360** [ddnet/ddnet#9323]
i paste my skins everywhere! in .local/share/ddnet, in .teeworlds and in my home directory but my skin isnt shown in the list of skins!

**Comment by Jupeyy** [comment]
Please stop open issues for beginner questions, aswell as flatpak related issues

**Comment by lgor360** [comment]
> ![image](https://github.com/user-attachments/assets/2579b5cc-0ba8-4f07-950e-2767e29f86aa)
> 
> that button could help!
> 
> if possible, could you join or ask these things on discord please? https://discord.gg/xeFzPpGD
> 

discord is blocked in Russian!

**Comment by lgor360** [comment]
> Please stop open issues for beginner questions, aswell as flatpak related issues

sorry... but.. where i can post this questions? (i cant open discord because its blocked)

**Comment by Jupeyy** [comment]
> > Please stop open issues for beginner questions, aswell as flatpak related issues
> 
> sorry... but.. where i can post this questions? (i cant open discord because its blocked)

I dunno if there is a russian chat for ddnet. Maybe https://www.reddit.com/r/ddnet if that works for you. Else try a VPN or smth

**Comment by furo321** [comment]
> sorry... but.. where i can post this questions? (i cant open discord because its blocked)

You can join the IRC webchat if you wish, https://webchat.quakenet.org/?channels=ddnet

**Comment by lgor360** [comment]
> > sorry... but.. where i can post this questions? (i cant open discord because its blocked)
> 
> You can join the IRC webchat if you wish, https://webchat.quakenet.org/?channels=ddnet

cool! I'm already running there!

**Comment by lgor360** [comment]
> > > Please stop open issues for beginner questions, aswell as flatpak related issues
> > 
> > 
> > sorry... but.. where i can post this questions? (i cant open discord because its blocked)
> 
> I dunno if there is a russian chat for ddnet. Maybe https://www.reddit.com/r/ddnet if that works for you. Else try a VPN or smth

i was banned in Reddit but im going to IRC chat
