### ISSUE TITLE
Shift+Tab auto complete hotkey conflicts with Steam community overlay hotkey

### ISSUE THREAD

**Issue by sjrc6** [ddnet/ddnet#9344]
If you launch the client through steam it's not possible to use the backwards autocomplete without rebinding the steam overlay.

**Comment by BlaiZephyr** [comment]
`ctrl+shift+tab`

**Comment by l-ouis** [comment]
same exists in cs2 - you cannot walk and view scoreboard without toggling overlay. I don't think backwards autocomplete should be changed since it's a very common combination, I think steam or steam users should change their overlay bind. (mine is personally shift f1)

**Comment by Robyt3** [comment]
I agree with @l-ouis, Shift+Tab was already the default hotkey to navigate to the previous item in virtually every browser and application before the Steam overlay was introduced.

**Comment by murpii** [comment]
As an alternative, you can use Ctrl+Shift+Tab instead.
