### ISSUE TITLE
Add config for map download url

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#9359]
https://github.com/ddnet/ddnet/blob/d270af955da372b2102b3606132c6e373b560229/src/engine/server/server.cpp#L1213

Servers with custom web map pools should not have to patch the code.

**Comment by Kaffeine** [comment]
> Servers with custom web map pools should not have to patch the code.

Why not? Patching is cool <s>and supporting others is not</s>.

Ok, [backported](https://github.com/ddnet/ddnet/pull/9395) from Infclass upstream.

**Comment by Kaffeine** [comment]
@heinrich5991, @ChillerDragon: this one can be closed.
