### ISSUE TITLE
keep vsync in mind if inactive

### ISSUE THREAD

**Issue by teini94** [ddnet/ddnet#9366]
if vsync on , keep it also in mind when you tab out of the game (inactive)
like cl_refresh_rate_inactive 60

i often use vsync to relax etc (since its not really useable anymore with vulkan (slomo))

**Comment by Jupeyy** [comment]
Sorry, but I don't understand this issue at all.

If V-Sync is enabled, it should be enabled regardless of inactive or not.
That V-Sync makes the rendering look slowmo makes no sense to me, how should a real time game be rendered in slow motion?

Maybe you can create a video showing your exactly problem?

**Comment by teini94** [comment]
if u have show_fps 1 enabled u can see sometimes when u tab into the game again that cl_refresh_rate_inactive xxx(example 600)
is used instead of vsync 


(this is more like an info: with vsync ur fps are just so slow (with vulkan) that u feel the game is slomo which makes it not useable for competive gaming but more for relaxing.)

**Comment by Jupeyy** [comment]
Well maybe the ingame FPS counter is a bit wrong then and laggs behind. If vsync is on it should never go above your monitors refresh rate. is it only a short burst of FPS or is it constantly too high?

**Comment by teini94** [comment]
fair point
