### ISSUE TITLE
Loading shaders doesn't go through `IStorage`

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#939]

**Comment by heinrich5991** [comment]
CC @Jupeyy

**Comment by Jupeyy** [comment]
It's not threadsafe, is it?

**Comment by Jupeyy** [comment]
Well it probably doesn't matter, though it would need the kernel in the other thread

**Comment by heinrich5991** [comment]
It looks thread-safe, you only read from the `IStorage`.

**Comment by Jupeyy** [comment]
it's more like, the thread has a pointer to the kernel, but since we wait for the thread it's no problem, yes.
But the backend then knows about the implementation.

**Comment by heinrich5991** [comment]
Engine stuff is allowed to know about `IStorage`, and I guess about its lifetime too.

**Comment by Jupeyy** [comment]
But why doesnt the system provide me this things. I mean why do i need to query it from a kernel, if the system could already do it. For me it just looks like alot of keeping track of things i shouldnt care about(as a backend). But thats just my opinion. something like io_open(%data%/...) would like fine.

**Comment by Jupeyy** [comment]
Or else, give me a hint how you would realize it. Just pushing a storage pointer to the parameter list of IssueInit and then send it through the cmd buffer?

**Comment by heinrich5991** [comment]
> But why doesnt the system provide me this things. I mean why do i need to query it from a kernel, if the system could already do it. For me it just looks like alot of keeping track of things i shouldnt care about(as a backend). But thats just my opinion. something like io_open(%data%/...) would look finer.

I think the idea behind this `IKernel` thing is that everything should have access to that anyway, as a replacement for global variables.

> Or else, give me a hint how you would realize it. Just pushing a storage pointer to the parameter list of IssueInit and then send it through the cmd buffer?

Pushing the `IStorage` into the thread some way is OK, `IssueInit` looks good.

**Comment by Jupeyy** [comment]
ok did it, will create the pr when the other stuff is merged cause i forgot to branch it
