### ISSUE TITLE
DDNet on Windows 7

### ISSUE THREAD

**Issue by KittenPro** [ddnet/ddnet#9398]
DDNet 18.8 breaks windows 7 support, 18.7 works well. When i try to launch 18.8 i get kernel32.dll GetSystemTimePreciseAsFile error.
![image](https://github.com/user-attachments/assets/8e6034c1-f909-4536-9cd2-b134ea1cbce3)

**Comment by Jupeyy** [comment]
Please note that Windows 7 is not supported by Microsoft anymore, you'll have to upgrade to Windows 10 or 11 for a secure system.
Thus we also don't give support for Windows 7 beyond best effort basis anymore.

If you want to fix this issue, you'll have to find out yourself how to fix it.

I __strongly__ recommend you upgrade to a secure system

**Comment by KittenPro** [comment]
> I couldn't find `GetSystemTimePreciseAsFileTime` in our codebase, so I guess it comes from one of our dependencies?

maybe, i can try to find conficting library

**Comment by KittenPro** [comment]
> See https://blog.rust-lang.org/2024/02/26/Windows-7.html

but 18.7 works

**Comment by def-** [comment]
That's unfortunate, so Rust has dropped win7 gnu support entirely, and even win7 msvc would be tier 3, so switching to it could be a risk to our users on win10+win11. We could just keep using an older Rust version, but it will break at some point.

**Comment by KittenPro** [comment]
> That's unfortunate, so Rust has dropped win7 gnu support entirely, and even win7 msvc would be tier 3, so switching to it could be a risk to our users on win10+win11. We could just keep using an older Rust version, but it will break at some point.

maybe making special builds for win7 will be a good solution? just compile using old rust version.

**Comment by heinrich5991** [comment]
I guess using an old Rust version for everyone would be the simplest course of action for now.

**Comment by def-** [comment]
I'll try to build a DDNet 18.8.1 with Rust 1.77.2, let's see if that helps.

**Comment by heinrich5991** [comment]
@KittenPro Does 18.8.1 work for you? In order to support your system, we need to know if the fix works.

**Comment by KittenPro** [comment]
> @KittenPro Does 18.8.1 work for you? In order to support your system, we need to know if the fix works.

yep, 18.8.2 works!! thx :)

**Comment by KittenPro** [comment]
> I just released 18.8.1, @KittenPro does it work on Win7 for you?

yesss, works! thx :)
