### ISSUE TITLE
best approach of implementing imgui to the client?

### ISSUE THREAD

**Issue by DefaultO** [ddnet/ddnet#9414]
I forked the client recently and started working on server mods, new experimental tiles and some mapping tooling for myself. It is getting tedious to manage all of these additions on my end with what the existing code offers to me.

What would be the best approach of implementing ImGUI into the ddnet client? I assume there is no need for it to the original repository, so I am not asking with the plan to do a pull request one day and introduce functionality tailored to my use-cases only, but to implement it for my own fork. Unless developers of the original game client would find it useful to have for the same reason I got tired with working with the console. Then we could work on it together. More or less.

I have never worked with the files directly inside the engine sub-folder. And from the looks alone and reading through some of them. Files that are interesting to me are the ones in the [backend folder](https://github.com/ddnet/ddnet/tree/master/src/engine/client/backend). The SDL implementation. And possibly the graphics source files. I still have to find my ways around the project. So I can't tell for sure.

I assume the ddnet game client is running on SDL2 because I spotted the SDL2 library somewhere. Thought I'd ask before starting to code like the contribuition guide suggested and maybe find someone who worked on the Vulkan implementation, or knows one or two things about the rendering in ddnet to assess how hard it would be to implement ImGUI and where the best place to call an Init function would be, or what best-practices to follow when it comes to the ddnet project.

**Comment by BlaiZephyr** [comment]
you're better off asking these things on our discord, but why do you want to add ImGUI ?

if all you want is a `Popup menu` - i would personally say just implementing it into our current UI implementation is easier and not as heavy as ImGUI. Ryozuki has a small blogpost that might help you in the beginning: https://edgl.dev/blog/ui-code-ddnet/ or just look at an existing implementation to understand how it works. For example `CMenus::RenderSettings` in `menus_settings.cpp`

if you still want to have ImGUI implemented, you should have a loot at `game/client/component.h` which seems to be what you're looking for.

**Comment by Jupeyy** [comment]
I never used imgui, but egui (which is a rust impl inspired by imgui).

At least for egui it only requires simple vertices that support colors and textures, as well as blending and for text rendering textures without mipmaps.

These are all things ddnet already supports.
The challenge is to simply start.

e.g. 
https://github.com/Jupeyy/dd-pg/blob/29bc281e6301402ad9289d252dc7283ddbb75aad/lib/ui-base/src/ui_render.rs
and
https://github.com/Jupeyy/dd-pg/blob/29bc281e6301402ad9289d252dc7283ddbb75aad/lib/ui-base/src/ui.rs

are basically all required to power it

**Comment by Jupeyy** [comment]
From their github page:
"Integrating Dear ImGui within your custom engine is a matter of 1) wiring mouse/keyboard/gamepad inputs 2) uploading a texture to your GPU/render engine 3) providing a render function that can bind textures and render textured triangles, which is essentially what Backends are doing."
https://github.com/ocornut/imgui?tab=readme-ov-file#getting-started--integration

**Comment by Jupeyy** [comment]
Anyway, next time please ask on a different chat, not github issues ^^
As melon already said this repo isn't the support forum for customization especially for personal use, I hope you understand that we can't solve every problem for every person.

**Comment by heinrich5991** [comment]
There's also #ddnet on Quakenet or also a Matrix channel, if you can't use Discord for whatever reason.

**Comment by BlaiZephyr** [comment]
> I don't need your useless replies, but actual answers.

good luck with fetching those.

>  But whining about that you won't add this to the base game isn't helpful at all.

Jupstar gave you answers and resources already, i'd consider that helpful.

> As melon already said this repo isn't the support forum for customization especially for personal use, I hope you understand that we can't solve every problem for every person.

I wouldn't define any of my replies as "whining" or "complaining", but rather making it clear that we can only help you so much because it's not in our interest to do so.

>I believe you banned me from everywhere. So if this is my only way to talk with other devs that worked longer on the game.

unlikely that you're banned from matrix, quakenet and discord, but if that's the case there certainly has to be a reason to it.

>The documentation is non existent. And while you might be speaking the truth regarding this specific case. It should contain information regarding the rendering pipeline/process of the game.

TiL documentation is meant to tell you exactly how to do task X in a 300K line codebase.

this is already closed,but i'll keep this as a last message to not get to `off-topic` - even tho i never was.

ImGUI has been implemented by others within DDNet before, i sadly couldn't reach out to him yet, seems like he's enjoying Christmas time - tho if he reads my message he might come back to you.
