### ISSUE TITLE
why can switch doors not be placed into walls/kill tiles

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#9427]
Just wondering why one can not place switch doors into collision or death tiles and so on.
Is there any specific reason for it? Or did that just happen and was never changed?

![screenshot_2024-12-26_09-38-56](https://github.com/user-attachments/assets/94378180-9fc6-4dc3-b2f5-2032fbbcf792)
![screenshot_2024-12-26_09-38-59](https://github.com/user-attachments/assets/70b687af-d1f4-43e2-8290-202a9cc8cb2b)

**Comment by Robyt3** [comment]
The door laser is stopped by walls on its path, so if it starts inside a wall then it's stopped immediately.

I suppose it would also be inconvenient in entities mode because you can't see the switch and game entities if they would overlap.

**Comment by ChillerDragon** [comment]
It stopping in walls could be disabled. I assume that breaks maps that depend on a switcher not going through a wall. Not sure if there are more problems caused by it.

We could decrease the switch tile entity texture. Giving it a transparent border which can reveal the underlying tile.

This is already implemented server side in S-DDRace by the way.

**Comment by ChillerDragon** [comment]
> I suppose it would also be inconvenient in entities mode because you can't see the switch and game entities if they would overlap.


It can already overlap with freeze

**Comment by l-ouis** [comment]
is there a certain reason this behavior is wanted? what cases is it different from just starting the door the block next to the hookable?

**Comment by ChillerDragon** [comment]
> is there a certain reason this behavior is wanted? what cases is it different from just starting the door the block next to the hookable?

It can look cleaner to hide the laser bubbles for open doors.

I personally don't even need it. This issue was just a question not a feature request. I think it won't go much further from here. I will just assume it just happend to be like this and there is no particular reason for being that way.

Closing the issue as the question is answered.
