### ISSUE TITLE
antiping on -> nameplates disappear

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#943]
instead shows own nameplate. did not notice this last time I played a few weeks ago.

**Comment by d3fault** [comment]
Confirmed. I joined a server to test it and toggling anti-ping toggled nameplates just like you described. BUT THEN the map changed and toggling anti-ping stopped toggling the nameplates (they were always on). weird

**Comment by d3fault** [comment]
the map change "fix" is intermittent hahaha glhf
