### ISSUE TITLE
Fix anti spoof plx

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#944]
yo ddnet guis,
my server is getting attacked by some TKEN packages so i filterd em.
But ddnet clients can't connect with this filter. And without the filter my server is ripped.
I guess it is your anti spoof package as far as i know. It would be nice to move it from udp to tcp or something so that it can't be abused to take my server down c:

**Comment by heinrich5991** [comment]
What kind of `TKEN` packages do you get? I suppose it wouldn't be any different if you were flooded with normal vanilla connection requests?

**Comment by ChillerDragon** [comment]
maybe, im noob. But it is defnetly a ddnet thing because vanilla clients can still connect on the server with the filter. And ddnet clients can't. And as i said i need this filter to keep the server alive while the attack which is running nonstop since 2 days. I guess moving the stuff to tcp and using syn cookies to protect agianst spoofing would be great c:

**Comment by heinrich5991** [comment]
If I read the source correctly, the DDNet protocol already has something similar to SYN cookies. The vanilla protocol does not, however. This won't help you in this situation though, what you're currently seeing is the equivalent of a SYN flood, and if you decide to block all SYN packets, it's clear that you're blocking everyone who wants to connect.
