### ISSUE TITLE
SQL stuff doesn't seem to do any locking whatsoever

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#946]
I have no idea how that hasn't fallen apart already. :o

**Comment by Learath2** [comment]
Locking is for wusses

**Comment by H-M-H** [comment]
Instead of locking one could also use two (threadsafe) queues, one for queuing sqlcommands and one for retrieving their results in the main thread. Like that we could keep all logic that alters the game in the main thread.

**Comment by def-** [comment]
Will be fixed by https://github.com/ddnet/ddnet/pull/2247

**Comment by heinrich5991** [comment]
Fixed by #2247.

**Comment by heinrich5991** [comment]
Also, :tada:!
