### ISSUE TITLE
mouse bug

### ISSUE THREAD

**Issue by lryjnks** [ddnet/ddnet#950]
Hello,

since the latest Windows 10 build the mouse doesn't work in DDnet anymore.

DDNet: 10.8.6
W10Pro: Version 1709 (Build 16299.64)

Video:

https://www.youtube.com/watch?v=F-Ow6H7_lJU

Vanilla Client works without problems

**Comment by FallenKN** [comment]
seems to be the old mouse mode

**Comment by lryjnks** [comment]
yeah thx
changed mouseold to 0 Now it works!
