### ISSUE TITLE
Dragging quads in editor

### ISSUE THREAD

**Issue by corneum** [ddnet/ddnet#963]
basicly i think this explains it: https://www.youtube.com/watch?v=XN4HTy0RlTE

**Comment by fokkonaut** [comment]
got this too. if you zoom in in editor and trying to move quads you will have this stucking thing. idk how to explain, the video shows it

**Comment by ChillerDragon** [comment]
https://user-images.githubusercontent.com/20344300/103445100-50c3f600-4c70-11eb-9dc6-cf9bade8cecd.mp4

I still have this issue on current master (71a371a4eed6ba82e2e04075dbc0c10e459b6e46) on arch linux.

**Comment by def-** [comment]
@timakro Can you take a look?

**Comment by timakro** [comment]
How do I reproduce this? Seems like zooming in/out is required?

**Comment by timakro** [comment]
@ChillerDragon

**Comment by ChillerDragon** [comment]
@timakro yes zoom in as far as possible and drag it slowly.
