### ISSUE TITLE
AIO write to stdout

### ISSUE THREAD

**Issue by Learath2** [ddnet/ddnet#964]
Crashes instantly on Windows 7 64bit. Can't seem to debug this at all :/ #914 might be related to this

https://paste.pr0.tips/s2 App Verifier output.

**Comment by heinrich5991** [comment]
>```
><?xml version="1.0" encoding="UTF-8" standalone="no"?>
><avrf:logfile xmlns:avrf="Application Verifier">
>	<avrf:logSession TimeStarted="2017-11-27 : 03:46:14" PID="13380" Version="2">
>		<avrf:logEntry Time="2017-11-27 : 03:46:33" LayerName="Heaps" StopCode="0x13" Severity="Error">
>			<avrf:message>First chance access violation for current stack trace.</avrf:message>
>			<avrf:parameter1>0 - Invalid address causing the exception.</avrf:parameter1>
>			<avrf:parameter2>7fef2da4e5a - Code address executing the invalid access.</avrf:parameter2>
>			<avrf:parameter3>575dcf0 - Exception record.</avrf:parameter3>
>			<avrf:parameter4>575d800 - Context record.</avrf:parameter4>
>			<avrf:stackTrace>
>				<avrf:trace>vrfcore!VerifierDisableVerifier+920 ( @ 0)</avrf:trace>
>				<avrf:trace>ntdll!RtlApplicationVerifierStop+d3 ( @ 0)</avrf:trace>
>				<avrf:trace>vfbasics!+7fef2d925d5 ( @ 0)</avrf:trace>
>				<avrf:trace>vfbasics!+7fef2d943fe ( @ 0)</avrf:trace>
>				<avrf:trace>vfbasics!+7fef2d93aaa ( @ 0)</avrf:trace>
>				<avrf:trace>ntdll!vsprintf_s+12b ( @ 0)</avrf:trace>
>				<avrf:trace>ntdll!RtlUnwindEx+852 ( @ 0)</avrf:trace>
>				<avrf:trace>ntdll!KiUserExceptionDispatcher+2e ( @ 0)</avrf:trace>
>				<avrf:trace>vfbasics!+7fef2da4e5a ( @ 0)</avrf:trace>
>				<avrf:trace>kernel32!RtlMoveMemory+a2 ( @ 0)</avrf:trace>
>				<avrf:trace>kernel32!WideCharToMultiByte+4f ( @ 0)</avrf:trace>
>				<avrf:trace>DDNet!write_text_ansi_nolock+182 (minkernel\crts\ucrt\src\appcrt\lowio\write.cpp @ 324)</avrf:trace>
>				<avrf:trace>DDNet!_write_nolock+3c5 (minkernel\crts\ucrt\src\appcrt\lowio\write.cpp @ 576)</avrf:trace>
>				<avrf:trace>DDNet!_write+27e (minkernel\crts\ucrt\src\appcrt\lowio\write.cpp @ 63)</avrf:trace>
>				<avrf:trace>DDNet!__acrt_stdio_flush_nolock+b4 (minkernel\crts\ucrt\src\appcrt\stdio\fflush.cpp @ 235)</avrf:trace>
>				<avrf:trace>DDNet!__acrt_stdio_end_temporary_buffering_nolock+4a (minkernel\crts\ucrt\src\appcrt\stdio\_sftbuf.cpp @ 103)</avrf:trace>
>				<avrf:trace>DDNet!__acrt_stdio_temporary_buffering_guard::~__acrt_stdio_temporary_buffering_guard+1f (minkernel\crts\ucrt\inc\corecrt_internal_stdio.h @ 415)</avrf:trace>
>				<avrf:trace>DDNet!&lt;lambda_96f4279ff90247a4c5c5d9824f56f8c1&gt;::operator()+6b (minkernel\crts\ucrt\src\appcrt\stdio\fwrite.cpp @ 39)</avrf:trace>
>				<avrf:trace>DDNet!__crt_seh_guarded_call&lt;unsigned __int64&gt;::operator()&lt;&lt;lambda_bdbcead8b570fa3d5ec6d9679862a6e5&gt;,&lt;lambda_96f4279ff90247a4c5c5d9824f56f8c1&gt; &amp; >__ptr64,&lt;lambda_4606be27f17b5e5579e09050fab91818&gt; &gt;+36 (minkernel\crts\ucrt\devdiv\vcruntime\inc\internal_shared.h @ 204)</avrf:trace>
>				<avrf:trace>DDNet!__acrt_lock_stream_and_call&lt;&lt;lambda_96f4279ff90247a4c5c5d9824f56f8c1&gt; &gt;+4b (minkernel\crts\ucrt\inc\corecrt_internal_stdio.h @ 256)</avrf:trace>
>				<avrf:trace>DDNet!fwrite+110 (minkernel\crts\ucrt\src\appcrt\stdio\fwrite.cpp @ 41)</avrf:trace>
>				<avrf:trace>DDNet!io_write+43 (e:\users\learath2\source\repos\ddnet\src\base\system.c @ 425)</avrf:trace>
>				<avrf:trace>DDNet!aio_thread+f4 (e:\users\learath2\source\repos\ddnet\src\base\system.c @ 548)</avrf:trace>
>				<avrf:trace>vfbasics!+7fef2d9ed34 ( @ 0)</avrf:trace>
>				<avrf:trace>kernel32!BaseThreadInitThunk+d ( @ 0)</avrf:trace>
>				<avrf:trace>ntdll!RtlUserThreadStart+21 ( @ 0)</avrf:trace>
>			</avrf:stackTrace>
>		</avrf:logEntry>
>	</avrf:logSession>
></avrf:logfile>
>```

I can't find `stdin` in the given output. Did you mean stdout?

**Comment by Learath2** [comment]
Definately meant stdout sry
