### ISSUE TITLE
Mute sound in server side instead on client

### ISSUE THREAD

**Issue by Tardo** [ddnet/ddnet#965]
So as not to stress the network with useless data.. I think it's better to mute the sound on the server side...

https://github.com/ddnet/ddnet/blob/master/src/game/server/entities/character.cpp#L479

**Comment by heinrich5991** [comment]
Have you tried measuring the impact of sending the sounds vs not doing that?

**Comment by Tardo** [comment]
Ufff... no xD 
Events are sent to all clients with a distance <= 1500.0f
https://github.com/ddnet/ddnet/blob/98a2f459b6bf0a1df55a081e750e3678844b524b/src/game/server/eventhandler.cpp#L50

And for example... entities are sent when position is DX <=1000.0f (X) and DY <= 800.0f the max distance "allowed" is 4000.0f?¿? (in vanilla is 1100.0f)
https://github.com/ddnet/ddnet/blob/98a2f459b6bf0a1df55a081e750e3678844b524b/src/game/server/entity.cpp#L44

**Comment by heinrich5991** [comment]
The idea behind that is that you don't get to see parts of the map you can't see on your screen anyway.

**Comment by Tardo** [comment]
yeah i know... net-clipping, but ddnet have too high values... why 4000.0f?

**Comment by ChillerDragon** [comment]
Can't you see everything with Zoom?

**Comment by heinrich5991** [comment]
If you zoom, the stuff will normally still be clipped.

**Comment by heinrich5991** [comment]
I think sending sound events has a negligible impact on bandwidth.
