### ISSUE TITLE
FakeSnap and network...

### ISSUE THREAD

**Issue by Tardo** [ddnet/ddnet#966]
Hi! first of all sorry for my ignorance about how network stuff works...
I'm trying to know how "FakeSnap" works... i see that instead on "OnSnap" this function don't check if the clientID is ingame
https://github.com/ddnet/ddnet/blob/03fa475b5e18c00d816846ac3a54afec03bd0035/src/game/server/player.cpp#L259

But checks that m_ClientVersion is >= VERSION_DDNET_OLD (2)... i see that "m_ClientVersion" is set to VERSION_VANILLA (0) but i can't found where is set to other value...

OnSnap and FakeSnap are sent the "same" information for the first 16 players?

**Comment by heinrich5991** [comment]
`FakeSnap` sends the player with the empty name to vanilla clients. The server uses that name to display chat of clients the vanilla client cannot see currently.

**Comment by Tardo** [comment]
Ok thx @heinrich5991 ... now i know why don't need check client and other stuff!! 
The ID 15 is reserved? what happens if exists 16 or more players playing?

**Comment by heinrich5991** [comment]
The vanilla client can handle 16 clients at most and crashes if you send more than that. DDNet works around that issue by only sending the 15 nearest clients and reserving client ID 15 for chat.

**Comment by Tardo** [comment]
Ok thx i can see that is related with "crashmeplx" rcon message.
