### ISSUE TITLE
[Client] HUD options

### ISSUE THREAD

**Issue by jxsl13** [ddnet/ddnet#970]
The granularity of the option whether a HUD element is visible or not should be more granular.

First off, it would be better to render the chat input line, even tho the rest of the chat is disabled(invisible), because the input disappears, when you stop chatting and thus does not disturb the gameplay like the chat does. This also allows you to see what you are actually typing, even tho the chat is disabled.(For those who ask, it makes sense, because you can read the chat in f1 console when necessary, but chatting via the f1 console with the say "" prefix is a pain in the ass)

Furthermore, it would be quite helpful to be able to disable chat, server messages and broadcast messages separately. Most server messages are unneccessary, but helpful for players, who play a mod for the first time and don't know mechanics and so on.)

Another HUD option that's missing is the ability to disable the rendering of emotes, because nowadays most use cases of emotes are spamming and disturbing gameplay.

Another helpful option would be to be able to force a skin on other players, like my preferred one, the default skin, or other optional skins) in order to have a fluent gameplay without being disturbed by weird skins(cars and what not).

I'm quite fond of sushi's clientpack mod's HUD options(for reference).
(zcatch player's perspective)

**Comment by Ryozuki** [comment]
These are really good ideas.

**Comment by def-** [comment]
cl_show_broadcasts exists already. cl_vanilla_skins_only exists already. Rest implemented
