### ISSUE TITLE
Server Security Token Seed exposed by brute force...

### ISSUE THREAD

**Issue by Tardo** [ddnet/ddnet#971]
Vulnerable function...
https://github.com/ddnet/ddnet/blob/32f919eee0eb2ed196852b60232696ca252ee7af/src/engine/shared/network_server.cpp#L144

```
[5a4ae8cc][NetDump]: Server Security Token (Local Client): 1960989836
[5a4ae8cc][NetDump]: *** Looking for server security token seed... please wait, this may take some time. ***
[5a4aec87][NetDump]: Server Security Token Seed: 109142
[5a4aec87][NetDump]: Server Port (Local Client): 45844
```

Without any algorithm optimization I get the seed within ~16 minutes...

**Comment by heinrich5991** [comment]
As far as I can tell, the security seed is 16 bytes long. In your output I dont see a seed that is that long. Can you share the method you use to obtain the seed?

**Comment by heinrich5991** [comment]
https://github.com/ddnet/ddnet/blob/32f919eee0eb2ed196852b60232696ca252ee7af/src/engine/shared/network.h#L318

**Comment by Tardo** [comment]
me fail... i'm using 4 bytes not 16.... sry for the mistake!

**Comment by heinrich5991** [comment]
Also note that just because a single generated token (that for a single address) coincides, does not mean that you have the token. In fact, approximately one in 4 billion seeds will generate the correct token for one sender address, but these are not guaranteed to be the actual server secrets.

**Comment by Tardo** [comment]
yeah totally wrong stuff.. sry! thx.

**Comment by def-** [comment]
But thanks for looking into security issues @Tardo , appreciate it!
