### ISSUE TITLE
OpenGL 3 fails on big map with Nvidia gtx1060

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#983]
According to ChillerDragon:

> [4:26 PM] fokkonaut: joining a biiiigggg map like BlmapChill with opengl3 = 1 is not possible
> [4:26 PM] deen: Well, that's a bug
> [4:26 PM] deen: It should be disabled by default, right?
> [4:26 PM] fokkonaut: it tells me to weak connection
> [4:26 PM] fokkonaut: ye its off by def
> [4:26 PM] fokkonaut: client crahes lul
> [4:27 PM] fokkonaut: possible fix? i really wanna use opengl3(edited)
> [4:27 PM] deen: it works for me
> [4:27 PM] deen: maybe your gpu doesn't have enough ram?
> [4:28 PM] fokkonaut: you joined blampchill?
> [4:28 PM] deen: es
> [4:28 PM] fokkonaut: sure that opengl was on
> [4:28 PM] fokkonaut: ?
> [4:28 PM] deen: yes
> [4:28 PM] deen: I can zoom out all the way with 60fps
> [4:29 PM] fokkonaut: i got a gtx 1060 it should work xD
> [4:29 PM] fokkonaut: but i cant join the server
> [4:29 PM] fokkonaut: to weak connedctiopn :x

**Comment by def-** [comment]
@Jupeyy Any ideas?

**Comment by fokkonaut** [comment]
i have the 6gb variant not  the 3gb

**Comment by savander** [comment]
Zotac 1060 AMP 6gb?

**Comment by ChillerDragon** [comment]
Im on windows10 with a GeForce GTX 980. And i can join BlmapChill with opengl activated. And zooming out feels great! But BlmapChill is a special map. It had many mappers on different operating systems i expirenced that this can lead to crashes server and client side. My client somtimes crashes when i open BlmapChill in editor. And a smaller map by NewTee was able to crash 30% of the joining clients on the server. It wasnt the map size.

So i guess the opengl code could be ok.

**Comment by fokkonaut** [comment]
hm pretty funny, i asked savander to give me his settings_ddnet.cfg and now i can join. i am about to find the setting causing this problem + i see white borders now between the cave tiles :/

**Comment by fokkonaut** [comment]
EVEN MORE FUNNY: i replaced savanders cfg settings with mine again and i can join wtf xD

**Comment by Jupeyy** [comment]
Even before anything Opengl 3 related is executed it allocates nearly 800MB of RAM at my system. When you use a 32-bit app on windows it won't allow you much more than 1.5 GB for pure memory data(or the heap sizes are just too small).

My code probably also allocated a few hundered MBs for such huge maps, so it's maybe a combination of both, if you run the 64-bit app, do you notice any problems?

ps: even if a free the memory i use, for the pure setup i will need such an amount of RAM for that maps, but maybe i can look at it.

**Comment by ChillerDragon** [comment]
@Jupeyy thank you for planning to fix it c:
And btw great work you did there.

**Comment by fokkonaut** [comment]
https://github.com/ddnet/ddnet/issues/988

**Comment by Jupeyy** [comment]
yeah, thanks.

I'm pretty sure it's because of the amount of RAM it uses. Either your RAM isnt very fast at allocating(since it's such a huge amount of alloc currently), or you ran out of RAM and windows or whatever OS you use tries to cache the RAM on your SSD/HDD, which leads to timeout since the client can't ping the server or something like that.

**Comment by def-** [comment]
You can try increasing the value of conn_timeout. What is it currently for you, @fokkonaut ?

**Comment by fokkonaut** [comment]
conn_timeout is set to 5. whats the maximum i should set it to?

**Comment by Henningstone** [comment]
Finding out whether RAM is the problem should be fairly easy right? Just open the task manager and and then join said map. The 'memory' graph should skyrocket if Jupeyy's theory is correct.

**Comment by def-** [comment]
Well, that's the reason, set conn_timeout to 100, the default. Problem solved. Bug can be closed.

**Comment by Jupeyy** [comment]
the problem is, it uses alot of RAM, i will fix this anyway. The map is bad mapped there are layers that are 9000x3000 tiles, that explains the issue, so atleast I should minimize that.
