### ISSUE TITLE
FPS drops on server refresh in debug mode

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#984]
The ingame server browser is great! I use it a lot to check current masterserver situation. And in ddnet11 it still works fine. But it has dramatically frame drops if you refresh the master while being in debug mode .-.

pls fix c:

**Comment by def-** [comment]
I assume this is with ctrl-shift-d, printing all ips to stdout synchronously, which is now slow on Windows.

**Comment by def-** [comment]
As a workaround you can set cl_show_console 0

**Comment by ChillerDragon** [comment]
Tested again and it is working smooth now. Probably due to the new aio.
