### ISSUE TITLE
Beep on Windows

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#985]
> Console window makes 2 beeps when joining a map on windows 7.

> edit: seems like it is related to the star symbol (difficulty rating), doesnt happen when joining non ddnet server

@heinrich5991 Sounds like another stdout issue?

**Comment by Learath2** [comment]
I think I always had this, just kinda got used to it :P

**Comment by def-** [comment]
I think I fixed this before, but can't find it. Usually this happens because the windows console has some other encoding and outputs a \BEL

**Comment by def-** [comment]
https://blogs.msdn.microsoft.com/oldnewthing/20070104-00/?p=28513

**Comment by Chairn** [comment]
Prevent people to rename with ascii character 7 also.

**Comment by Learath2** [comment]
Hmm I remember this being caused by BEL being one of the bytes of a UTF8 character.

**Comment by heinrich5991** [comment]
This shouldn't happen: BEL is ASCII and the only bytes < 128 in UTF-8 are plain ASCII bytes. Only bytes ≥ 128 are used to represent non-ASCII characters.

**Comment by Learath2** [comment]
Is it possible that a byte of a multibyte character being BEL is causing
this?

Something we have in the MOTD does cause a beep, disabling the command line
stops the beep and windows cmd.exe does sound like it could be stupid
enough. Maybe we need to put it in unicode mode somehow?

**Comment by fokkonaut** [comment]
Close?

**Comment by Learath2** [comment]
I think my last PR closes this. I tested on windows 7
