### ISSUE TITLE
Emoji not working in text entering field

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#986]
To replicate:
1. Enter a server to play
2. Enter bound key to start chatting
3. Paste an emoji

Another way:
1. View server list menu
2. Paste emoji into search or filter or any text field

You can try copy/pasting some of the emojis from getemoji.com
Emoji works fine when viewing chat, but not in f1, for example. Also please make sure it works in MOTD as well.

**Comment by fokkonaut** [comment]
its better if you cant use it in f1. then you can see how others did that one emoji + we dont want to get colorful console with these emojis.

**Comment by def-** [comment]
I think the current behaviour is better.
