### ISSUE TITLE
Wrong stuff with Windows build?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#989]
> Guys some weirdo shit is happening on new client..
> 1 - I've made a part where you basically need to fall on edge and then hold jump and < and wait for unfreeze. Tee should go between freeze, but suddenly it doesn't work, I touch the freeze every time.
> 2 - I'm getting stuck on vertical walls when I hold left or right, I can pretty much climb them this way, just wtf o.O
> I noticed it's happening only on my own server (as well as first bug). On official servers I 'lag' on the wall and get teleported down as soon as I touch the ground after some time which is also very annoying. I guess DDNet-Server.exe is now broken. 

https://forum.ddnet.tw/viewtopic.php?t=5803&p=60506#p60506

**Comment by def-** [comment]
It's possible that this is caused by a mingw-w64-gcc update to 7.2.1 or some different settings that cmake passes and bam didn't.

**Comment by heinrich5991** [comment]
That sounds like a compiler issue.

Also from that forum post:
>![image](https://user-images.githubusercontent.com/366230/34922382-4ac59ff6-f98f-11e7-8e81-b0bd84aecb8c.png)

**Comment by def-** [comment]
I believe that bam compiled with -O2 by default, while CMake now does -O3. So some of our floating point math is probably not correct.

**Comment by heinrich5991** [comment]
Could you try compiling with `-O2` and check whether the result changes?
