### ISSUE TITLE
Changes to force vote console command

### ISSUE THREAD

**Issue by 12pm** [ddnet/ddnet#991]
We plan to introduce a new "Helper" rank that has rcon access to force no on votes and mute people. For that there need to be code changes so that we can allow them to only use "vote no" and not "vote yes".

**Comment by Ekidoxx** [comment]
So, for kicking blocker you'd need to call a Moderator, but to prevent kicking random players, just find any available Helper being around?

**Comment by 12pm** [comment]
Yes, Helper's main task is to stop fun-votes.
