### ISSUE TITLE
Strange lines when zooming in the editor since ddn11

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#993]
According to bano:
![editor11](https://user-images.githubusercontent.com/2335377/35004553-c5f70c34-faf0-11e7-9a12-88a317712add.png)
might be related to opengl3 @Jupeyy

**Comment by Jupeyy** [comment]
nice screen,  the map maybe?? i dont have such things

**Comment by fokkonaut** [comment]
you have to press TAB to hide the top and left menus. then just move a bit thorugh the map and These borders appear (mine hsd text, such as the top menu buttons like add quad etc)

**Comment by Jupeyy** [comment]
Can you give me a map where it happens I cannot reproduce it. It doesn't happen when OGL3 is off?
